### ISSUE TITLE
BUG   下级级联平台设置的目录结构，只能向上一级设置树形结构，再传递给其上级级联平台时，树形结构无法展示

### ISSUE THREAD

**Issue by DavidSche** [648540858/wvp-GB28181-pro#1000]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
下级级联平台设置的目录结构，只能向上一级设置树形结构，再传递给其上级级联平台时，树形结构无法展示
最下级设置
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/b08f9342-864b-4e33-90ed-d2553b896f02)
本级看到的
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/b08f9342-864b-4e33-90ed-d2553b896f02)
上级看到的
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/a8722cac-6591-4caa-8994-4110b59e5a13)

向上级平台添加国标通道d的参数信息中无通道的parentid 信息，无法再上级平台中继续沿用通道原有的上下级关系
{
  "platformId": "",
  "catalogId": "",
  "all": true,
  "channelReduces": [
    {
      "id": 0,
      "channelId": "",
      "deviceId": "",
      "name": "",
      "manufacturer": "",
      "hostAddress": "",
      "subCount": 0,
      "platformId": "",
      "catalogId": ""
    }
  ]
}

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你的目标编号是随便写的还是按照国标来的

**Comment by DavidSche** [comment]
目录编号是按照国标来的，

原因初步分析 ：因为wvp中上级平台的目录存放在本级（第一级）平台的wvp_platform_catalog 表中，当推送到上级（第二级）平台时，是作为设备通道 存放在上级（第二级）的wvp_device_channel表中（这时有正确的上下级关系 parentid ），当在 第二级 wvp 的国标级联 上级平台列表的页面，点 选择通道，在弹出页面 通过 全选  再向更上级（（第三级））推送时（参见下图），传递对象使用的 ChannelReduce 对象的属性信息中没有 第二级 wvp_device_channel表 parentID 信息  。导致 第三级的wvp_device_channel 的表中的设备中通道数据没有了parentID 信息，无法再像第二级平台那样以树形结构展示。

![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/9ec832b5-fd20-4604-b2c4-79a76eae3b2b)

是否是这个原因导致，请大佬验证。

**Comment by 648540858** [comment]
是的。wvp的级联需要每一级手动设置目录，国标级联目录以及通道共享的内容会在新版本重做。
