### ISSUE TITLE
[BUG] 国标级联无法订阅下级平台中设备的位置信息

### ISSUE THREAD

**Issue by aiweilwf** [648540858/wvp-GB28181-pro#1001]
在下级平台通过GB28181协议接入到WVP平台后，由于只能通过设备订阅位置，此时下级平台在WVP中以设备形式出现、下级平台的设备以通道形式出现，因而WVP无法对下级平台中的设备进行位置订阅

**Comment by 648540858** [comment]
直接订阅下级平台呀，国标本来就不允许你直接订阅下级的下级。

**Comment by mrluoqiang** [comment]
> 直接订阅下级平台呀，国标本来就不允许你直接订阅下级的下级。

设备推上来移动位置信息，没有推送到级联得上级平台嘛
