### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by cocorecoco** [648540858/wvp-GB28181-pro#1003]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
请问下 单个wvp服务， 如果部署多个zlm节点， 内部是如何选择动态选择节点的， 对应的java代码在哪一块可以看到

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
MediaServerServiceImpl这个类的getMediaServerForMinimumLoad方法

**Comment by 648540858** [comment]
主要是通过在redis存储每个zlm的负载数，然后每次获取负载最低的那个来实现。
