### ISSUE TITLE
播放串流问题

### ISSUE THREAD

**Issue by energyjry** [648540858/wvp-GB28181-pro#1004]
**环境信息:**

 - 1. wvp-pro和zlmediakit都是Docker方式部署
 - 2. 部署环境 阿里云
 - 3. 多端口UDP收流。30000~30100
 - 4. 公网部署 

**内容描述:**
    当正在观看摄像头A视频的时候，重启了zlm和wvp程序。经抓包查看，摄像头A在程序重启后仍向之前分配的端口(30048)推送视频。此时有新的摄像头B需要播放视频，并恰好分配到相同端口(30048）时，就会出现播放是摄像头A的画面。即出现播放串流的情况。
    这个串流场景虽然偶然出现，但是只要满足上述场景，几乎必现。请问有什么解决方案吗？比如在程序重启的时候通知摄像头让他们停止推流？该如何实现。

谢谢！！！

**Comment by 648540858** [comment]
a推流不停的话，b推流到这个端口会被zlm拒绝，同时也不会分配这个端口。所以我觉得你说的情况不可能，

**Comment by energyjry** [comment]
zlm也重启了，所以有可能将之前分配给a的端口重新分配给b。但是a的推流不停，点播b的时候实际播放的是a推上来的视频流。的确是这样的情况，在公网环境部署的时候出现多次串流了。

**Comment by energyjry** [comment]
已解决。通过在代码中添加了@PreDestroy注解，在程序退出前给所有还在播放的设备发送BYE指令，防止摄像头推流不中断

**Comment by zzgwd** [comment]
测试也重现，同样是重启wvp和zlm后，AB摄像头都看到了A摄像头的流。再查看ZLM的rtp文件夹中，AB摄像头的ts文件完全一样。需要再wvp平台中停用B摄像头，再重新点播。B摄像头恢复正常。
测试如下。
A摄像头:xxxx0066，265编码
B摄像头:xxxx0033，264编码
B摄像头的rtp流变成了265，这个流其实是A摄像头的。
![3e2678fa5396214192a39427fa19aad](https://github.com/648540858/wvp-GB28181-pro/assets/12791750/688f6d3d-a9c3-49f8-8760-27180f7
![af5313125f669a8e7f0175fc1adcb69](https://github.com/648540858/wvp-GB28181-pro/assets/12791750/10b4c0ca-7ef2-456b-a7e7-0d54f4a42535)
bdc72)
两个摄像头的文件完全一致
![84879d6759fbc8a4f19e9579cbfcade](https://github.com/648540858/wvp-GB28181-pro/assets/12791750/4a8447d7-0eba-4f61-9508-35a2764c2a4a)
导致观看B摄像头看到的是A的画面

**Comment by energyjry** [comment]
@zzgwd 你可以抓包测试下，是不是和我的场景一样：重启后分配给B摄像头的收流UDP端口=重启前分配给A摄像头的收流端口，造成端口实际收到的仍是A摄像头的流？

**Comment by zzgwd** [comment]
@energyjry 是的，分配给B的udp是A的收流端口。测试发现另外的问题。会有概率出现摄像头无法通过新端口推流情况。导致流一直无法上来。
使用zlm动态分配端口，udp传输流。测试过程如下：
1. A摄像头使用**30002**端口推流,B摄像头使用30004端口推流正常。
2. 重启wvp，ZLM，出现B摄像头一切正常，A摄像头无法查看，ZLM的rtp文件夹中没有文件。
3. 查看日志，当点播时，wvp通过openrtpserver获取了新端口**30010**，sip下发端口给了摄像头，也收到回复。
4. 通过Wireshark抓包，发现A摄像头一直向**30002**端口推流，同时**30010**端口没有数据。B摄像头一切正常。
5. 使用netstat -ano|findstr "30002" 和 netstat -ano|findstr "30010"均未查询到端口占用。B摄像头的30004有占用。
6. 再次点击点播A，重新分配**30011**端口，情况如上无法收流。
7. 此时其他摄像头通过停止点播，再点播也会分配新的端口，测试其他摄像头可以切换过去。都没有出现问题。
8. 由于A未点播成功，通过程序无法停止点播。从界面上无法修改该问题。每次点播都会分配新的端口。

最后结果就是每次点击都会申请新的端口，下发摄像头，但摄像头响应后还是使用原来端口推送流。zlm就收不到流了。同时由于点播未成功，没有redis记录，界面无法停止。需要修改代码或重启服务解决。

**Comment by energyjry** [comment]
原因是wvp程序重启前未给A摄像头发送BYE，A检测不到服务端关闭了，一直仍向原30002端口推流不停止。A可能不支持推多路流，所以A就再也无法点播成功了。并且此时如果B恰好动态分配到了30002端口，B会出现A的画面。
可以参考下我的解决方案试试，在wvp程序退出前查询一下redis里还有哪些摄像头正在播放，给它们发送一拨BYE指令，让摄像头停止推流。

**Comment by eanfs** [comment]
> 原因是wvp程序重启前未给A摄像头发送BYE，A检测不到服务端关闭了，一直仍向原30002端口推流不停止。A可能不支持推多路流，所以A就再也无法点播成功了。并且此时如果B恰好动态分配到了30002端口，B会出现A的画面。 可以参考下我的解决方案试试，在wvp程序退出前查询一下redis里还有哪些摄像头正在播放，给它们发送一拨BYE指令，让摄像头停止推流。

【给它们发送一拨BYE指令，让摄像头停止推流。】 这个指令怎么发，我也遇到这个问题了

**Comment by eanfs** [comment]
> 已解决。通过在代码中添加了@PreDestroy注解，在程序退出前给所有还在播放的设备发送BYE指令，防止摄像头推流不中断

@PreDestroy注解 加在哪个类中？

**Comment by szylmzs** [comment]
> > 原因是wvp程序重启前未给A摄像头发送BYE，A检测不到服务端关闭了，一直仍向原30002端口推流不停止。A可能不支持推多路流，所以A就再也无法点播成功了。并且此时如果B恰好动态分配到了30002端口，B会出现A的画面。 可以参考下我的解决方案试试，在wvp程序退出前查询一下redis里还有哪些摄像头正在播放，给它们发送一拨BYE指令，让摄像头停止推流。
> 
> 【给它们发送一拨BYE指令，让摄像头停止推流。】 这个指令怎么发，我也遇到这个问题了

你的问题解决了吗 如何发bye指令 或者wvp有没有提供功能在重启前对所有设备发送bye指令

**Comment by energyjry** [comment]
我当时在wvp里自己加的，程序退出的时候对所有在线的设备发送一次bye指令。后来没在跟踪了，不知道现在wvp有没有优化掉。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月13日(星期四) 下午5:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [648540858/wvp-GB28181-pro] 播放串流问题 (Issue #1004)














   
原因是wvp程序重启前未给A摄像头发送BYE，A检测不到服务端关闭了，一直仍向原30002端口推流不停止。A可能不支持推多路流，所以A就再也无法点播成功了。并且此时如果B恰好动态分配到了30002端口，B会出现A的画面。 可以参考下我的解决方案试试，在wvp程序退出前查询一下redis里还有哪些摄像头正在播放，给它们发送一拨BYE指令，让摄像头停止推流。
  
【给它们发送一拨BYE指令，让摄像头停止推流。】 这个指令怎么发，我也遇到这个问题了
  
你的问题解决了吗 如何发bye指令 或者wvp有没有提供功能在重启前对所有设备发送bye指令

**Comment by szylmzs** [comment]
> 我当时在wvp里自己加的，程序退出的时候对所有在线的设备发送一次bye指令。后来没在跟踪了，不知道现在wvp有没有优化掉。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年6月13日(星期四) 下午5:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [648540858/wvp-GB28181-pro] 播放串流问题 (Issue #1004) 原因是wvp程序重启前未给A摄像头发送BYE，A检测不到服务端关闭了，一直仍向原30002端口推流不停止。A可能不支持推多路流，所以A就再也无法点播成功了。并且此时如果B恰好动态分配到了30002端口，B会出现A的画面。 可以参考下我的解决方案试试，在wvp程序退出前查询一下redis里还有哪些摄像头正在播放，给它们发送一拨BYE指令，让摄像头停止推流。 【给它们发送一拨BYE指令，让摄像头停止推流。】 这个指令怎么发，我也遇到这个问题了 你的问题解决了吗 如何发bye指令 或者wvp有没有提供功能在重启前对所有设备发送bye指令 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

就是之前说的加@PreDestroy注解的方式？
