### ISSUE TITLE
[BUG] 下级播放着时上级平台无法点播

### ISSUE THREAD

**Issue by ZhangDashuaix** [648540858/wvp-GB28181-pro#1008]
目前遇到一个问题：下级平台推送上级平台后，在上级平台点播关闭都是正常的，这时候我看到下级平台那边也是被播放的状态。但是当我在上级关闭点播，去下级平台播放的时候，上级平台就看不了下级平台的视频了。即便我将下级平台的点播关闭，上级平台也是点播超时。图片是上级平台的图片。
![image](https://github.com/648540858/wvp-GB28181-pro/assets/140698586/41cced01-4687-4a95-ab16-c6df6a970ecd)

**Comment by 648540858** [comment]
明白了，我测试下

**Comment by 648540858** [comment]
已修复

**Comment by DavidSche** [comment]
好像是 streamid 和 ssrc 的原因

**Comment by 648540858** [comment]
已经修复了, 我测试了下现在没有这个问题了，你再测测
