### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by yeChina** [648540858/wvp-GB28181-pro#1009]
- 1. 部署方式 wvp-pro / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu +arm
 - 3. 端口开放情况 
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
第一：首先非常感谢作者,已成功部署并级联到上级平台
第二：咨询一下 个 我们支持GB28181，现在想做支持GB35114，看了两个在sip上的交互流程框架上可以支持的，但是我不确定想问问是否可以？谢谢

**Comment by 648540858** [comment]
35114主要视频的一些加密，如果想做你需要而开zlmidiakit，我没能力做不了
