### ISSUE TITLE
关于iframe播放，需要登录问题。

### ISSUE THREAD

**Issue by wwwei233** [648540858/wvp-GB28181-pro#101]
我们拿到iframe 嵌入到其他项目网页，怎么需要登录呢?给我想的是直接就能观看其中的直播呀？有没有办法直接拿到ifram直接就能观看
![QQ截图20210524103923](https://user-images.githubusercontent.com/36079865/119289801-d840ee80-bc7d-11eb-9727-75c06a372866.jpg)
嵌入到其他网页
![QQ截图20210524105136](https://user-images.githubusercontent.com/36079865/119289879-0d4d4100-bc7e-11eb-9908-10ecde2183d2.jpg)

**Comment by 648540858** [comment]
关闭登陆鉴权

**Comment by wwwei233** [comment]
![QQ截图20210527112508](https://user-images.githubusercontent.com/36079865/119761747-f78a8680-bede-11eb-92d1-1bc699484339.jpg)
是这地方吗？改了没效果。其他没找到登录鉴权的地方

**Comment by 648540858** [comment]
是的， 我测试下

**Comment by 648540858** [comment]
我这里测试关闭接口鉴权是可以的，你在测试下。

**Comment by songkemail** [comment]
关闭了登录鉴权，还是提示要登录

**Comment by songkemail** [comment]
> 我这里测试关闭接口鉴权是可以的，你在测试下。

我这里试了，是不行的

**Comment by XieB** [comment]
已解决，通过修改前端项目逻辑，如下
![image](https://user-images.githubusercontent.com/11675821/174235491-a252d4e5-0164-4d1e-8c90-99689ed47162.png)

**Comment by littleantsos** [comment]
还是存在鉴权的问题，

**Comment by AirShen** [comment]
> 已解决，通过修改前端项目逻辑，如下 ![image](https://user-images.githubusercontent.com/11675821/174235491-a252d4e5-0164-4d1e-8c90-99689ed47162.png)

感谢。这个我改了确实好用。
