### ISSUE TITLE
SIP服务启动失败,请检查端口是否被占用或者ip是否正确

### ISSUE THREAD

**Issue by a173030685** [648540858/wvp-GB28181-pro#1010]
最新版本sip的ip不能配置为外网ip地址，配成内外ip或者0.0.0.0都可以监听成功，但是如果配成外网ip，则报错：SIP服务启动失败,请检查端口是否被占用或者ip是否正确

**Comment by lunasaw** [comment]
外网IP 网卡跟服务器在一起吗

**Comment by 648540858** [comment]
看配置文件注释。

**Comment by wucoder** [comment]
解决了吗兄弟

**Comment by a173030685** [comment]
> 解决了吗兄弟

解决了，有个配置要修改一下

**Comment by wucoder** [comment]
什么配置铁子细聊

**Comment by wangdongyang-work** [comment]
> > 解决了吗兄弟
> 
> 解决了，有个配置要修改一下

焯你妈有个配置要改你妈你说啊，什么傻逼东西啊
