### ISSUE TITLE
 [ 技术咨询 ]SD观看的时候自动给我录制，如何取消观看时录制

### ISSUE THREAD

**Issue by seven54** [648540858/wvp-GB28181-pro#1011]
大华设备，观看摄像头SD卡录像时，自动给我录制到了云端录相。如何取消这个观看就录制到云端录相

![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/ec1f4abd-c5c5-4325-bdb7-f5122076375b)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/c77974ca-2248-4022-865c-ae12e585718c)

**Comment by a24211317** [comment]
# [根据业务需求配置]
user-settings:
    # 推流直播是否录制
    record-push-live: false
这个改成false应该就不会自动录制了

**Comment by seven54** [comment]
好的。

**Comment by seven54** [comment]
我按操作方法不行。 截图如下：

**Comment by seven54** [comment]
我按操作方法不行，截图如下：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/1d7fad1e-2611-412a-807e-c9c085820f64)


![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/258764c0-476d-4bc6-924e-dba8a8e00e0f)


![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/50cb2d50-3654-4402-8e45-7e3759b60ada)

**Comment by a24211317** [comment]
修改配置之后流媒体应该也要重启下试试

**Comment by seven54** [comment]
重启了也一样。加上 record-sip: false 重启后解决了。但是不知道会不会影响拉流自动存储录相

**Comment by a24211317** [comment]
哦对 是这个参数 复制的时候没注意串行了
应该是会有影响的
