### ISSUE TITLE
技术咨询-平台支持告警功能吗

### ISSUE THREAD

**Issue by song01** [648540858/wvp-GB28181-pro#1013]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
平台支持告警功能吗？目前看后端代码没有进行告警的订阅，前端页面有告警相关的页面吗

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
支持主动告警，设备主动推送的。前端页面支持收到报警后通知了，手里没设备，没测试过，你可以自己测试下
