### ISSUE TITLE
希望wVP实现的新功能，更兼容性的mapper，和redis序列化

### ISSUE THREAD

**Issue by lunasaw** [648540858/wvp-GB28181-pro#1014]
**项目的详细需求**
项目兼容性
**这样的实现什么作用**
-Dfastjson.parser.safeMode=true：指定 fastjson 解析器在安全模式下运行。
这个异常在使用java-agent，使用FastJson版本不一致时会出现，通过序列化转换数据更安全
![image](https://github.com/648540858/wvp-GB28181-pro/assets/52351139/7f9c7372-006a-45a8-a1b3-53410700b9ee)

mybatis多参数的时候，jdk 1.8.0_201 的时候会编译，出现[1, 0, param1, param2]异常，加@Param可以兼容更多情况
![image](https://github.com/648540858/wvp-GB28181-pro/assets/52351139/9067d305-ab2a-4e85-ace4-5c0562c14c4f)

**Comment by 648540858** [comment]
谢谢建议
