### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by liukuan1** [648540858/wvp-GB28181-pro#1015]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境  ubuntu18
 - 3. 端口开放情况：全部
 - 4. 是否是公网部署 ：公网
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：海康威视
 - 7. 你做过哪些尝试
 - 8. 代码更新时间：最新代码

**内容描述:**
接口请求时候，获取到的是内网ip，不是公网ip，导致无法播放视频，是哪里配置有问题吗？

**截图**  
![微信截图_20230819112417](https://github.com/648540858/wvp-GB28181-pro/assets/13283263/6cbdcfb6-1b93-4e83-9a15-ed2679031cc0)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
stream-ip配置设置为公网ip

**Comment by liukuan1** [comment]
您的邮件我已收到，我将及时查看！谢谢！

**Comment by liukuan1** [comment]
![微信截图_20230823111713](https://github.com/648540858/wvp-GB28181-pro/assets/13283263/7ea2ee82-af77-4dbe-90b7-811ef28387ea)

**Comment by mengxing2017** [comment]
# 是否使用设备来源Ip作为回复IP， 不设置则为 false
    sip-use-source-ip-as-remote-address: false  这个配置设置为false

**Comment by mengxing2017** [comment]
use-source-ip-as-stream-ip: true  这个改成false

**Comment by liukuan1** [comment]
已解决，感谢
