### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by libinanshu** [648540858/wvp-GB28181-pro#1016]
各位朋友，这玩意是不是不能使用域名解析，如果是远程部署必须是静态公网？

**Comment by lunasaw** [comment]
测试hook ip可以配置域名，需要在wvp下发给zl的时候修改下发的地址，源代码是手动拼接的地址

**Comment by mengxing2017** [comment]
wvp必须是静态公网ip,zlm可以使用域名解析，但要定时刷新dns,否则ip一变，还是会收流超时

**Comment by 648540858** [comment]
sip.ip使用网卡ip，具体是什么就写什么，hook.ip,stream.ip都是直接拼接地址，可以配置为域名。sdp.ip是放在sip消息中，没测试过使用域名的兼容性如何，这个需要看设备了
