### ISSUE TITLE
media.rtp.enabled项设置为false时，前端页面拉不到流

### ISSUE THREAD

**Issue by liudebin2010** [648540858/wvp-GB28181-pro#1018]
**环境信息:**
 - 1. 部署方式  wvp-pro + zlm都是编译部署/
 - 2. 部署环境  ubuntu
 - 3. 端口开放
 - 4. 不是公网部署 
 - 5. 没使用https
 - 6. 设置完后服务都重启也没用

**描述错误**
当wvp-pro配置文件中的media.rtp.enabled项设置为false时，前端页面拉不到流，看日志推流正常，但前端页面没有得到能拉流的通知

**如何复现**
将media.rtp.enabled项设置为false后，前端页面都会出现

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
media.rtp.enabled项设置为false时是但单端口收流，你说的前端页面拉不到流是什么现象请具体描述下。是提示错误，还是播放窗口无内容
