### ISSUE TITLE
jwt token包含敏感信息

### ISSUE THREAD

**Issue by jianse** [648540858/wvp-GB28181-pro#1020]
https://github.com/648540858/wvp-GB28181-pro/blob/8fab1ed0e8d6535a1ec68ddb62c2999e0f5ab791/src/main/java/com/genersoft/iot/vmp/conf/security/JwtUtils.java#L65-L67

claims默认是不加密的，这意味着所有能拿到token的人都可以拿到用户名和密码。这是否有安全问题？

**Comment by 648540858** [comment]
目前这块没有太严格的安全性考虑，你可以提出你的建议，

**Comment by jianse** [comment]
这个问题应该已经被 #1043 修复了，顺便一说，https://doc.wvp-pro.cn 文档站的证书到期了
