### ISSUE TITLE
技术咨询 红外摄像仪收流超时

### ISSUE THREAD

**Issue by xue9957** [648540858/wvp-GB28181-pro#1021]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows
 - 3. 端口开放情况(全都开放)
 - 4. 是否是公网部署(否) 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 -  关闭ssrc校验；但是还是没有效果
 - 8. 代码更新时间

**内容描述:**
我在平台上注册的海康摄像头是可以正常收流播放成功 但是注册个TPC的红外摄像头就会出现收流超时 用最新的代码跟最新的ZLM的话会一直转圈 日志显示一直尝试注册但是过了1.2分钟就收流超时，想问下这是什么情况

**截图**  
![R}IY0L%JM__~ VDJJE5@YS0](https://github.com/648540858/wvp-GB28181-pro/assets/77611572/0e688014-c365-415b-8fa0-f73ae49bdcb0)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
看起来是跨网段的网络，大概率是配置问题

**Comment by xue9957** [comment]
> 看起来是跨网段的网络，大概率是配置问题

但是我海康的摄像头是能播放啊  就这个红外的就是收流超时

**Comment by mengxing2017** [comment]
使用udp也不行吗？你tcp/udp端口都开了吗

**Comment by xue9957** [comment]
> 使用udp也不行吗？你tcp/udp端口都开了吗

刚才给多端口开了就好了 谢谢啦
