### ISSUE TITLE
分屏控制无法显示子目录BUG

### ISSUE THREAD

**Issue by villers3** [648540858/wvp-GB28181-pro#1025]
**环境信息:**
<version>2.6.9</version>

**描述错误**
在分屏控制页面级联设备子目录无法显示

**如何复现**
1、添加级联设备
2、添加子目录

目前暂时改了代码：
wvp-GB28181-pro\src\main\java\com\genersoft\iot\vmp\storager\dao\DeviceChannelMapper.java
@Select(value = {" <script>" +
            "select * " +
            "from wvp_device_channel " +
            "where device_id=#{deviceId}" +
            " <if test='parentId == deviceId '> and (parent_id = #{parentId} or parent_id is null) </if>" +
            " <if test='parentId != null and parentId != deviceId'> and parent_id = #{parentId} </if>" +
            " <if test='parentId == null '> and parent_id is null </if>" +
            " <if test='onlyCatalog == true '> and parental = 1 </if>" +
            " </script>"})
    List<DeviceChannel> getSubChannelsByDeviceId(String deviceId, String parentId, boolean onlyCatalog);

wvp-GB28181-pro\src\main\java\com\genersoft\iot\vmp\service\impl\DeviceServiceImpl.java
  //if (ObjectUtils.isEmpty(parentId) || parentId.equals(deviceId)) {
        //    parentId = null;
        //}
        if (ObjectUtils.isEmpty(parentId) ){
            parentId = null;
        }

**Comment by Kender0221** [comment]
你这个问题就是设备列表能拿到，但是点击了之后没有通道。这个问题与摄像头后台配置参数有关系，大概率是缓存的问题。可以尝试修改一下摄像头后台的通道参数，然后同步一下即可。

**Comment by 648540858** [comment]
分屏显示会在新版本上重做，暂时不修改这块的BUG了，有兴趣可以自己尝试修改下
