### ISSUE TITLE
BUG最新版本代码录像有BUG

### ISSUE THREAD

**Issue by donnasky** [648540858/wvp-GB28181-pro#1026]
**环境信息:**

 - 1. 部署方式 docker一个镜像部署
 - 2. 部署环境 / ubuntu/ ...

**描述错误**
zlmediakit内有文件，但是读不出来
最新版本的代码，在AssistRESTfulUtils.java里新配置的路由错误，assit内无此接口，应该是list接口
![image](https://github.com/648540858/wvp-GB28181-pro/assets/19203869/09763708-cc89-4fb1-94f1-cd30b9eec42b)

**如何复现**
正常开启meida，拉流并录像
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你的assist没更新吧，这个接口是后来添加的

**Comment by donnasky** [comment]
> 你的assist没更新吧，这个接口是后来添加的

![image](https://github.com/648540858/wvp-GB28181-pro/assets/19203869/07bf6abc-bcb8-4242-b12b-1131d22da1ab)
assist上没搜到这个接口
