### ISSUE TITLE
技术咨询，请教下MP4录制文件的保存时长如何控制？

### ISSUE THREAD

**Issue by donnasky** [648540858/wvp-GB28181-pro#1029]
**环境信息:**

用的是最新的wvp和zlmediakit，在zlmediakit里设置了record.fileSecond为300，也就是希望5分钟保存一个录像文件，但是实测还是一小时一个，问下是不是wvp做了什么控制？还是我配置的不对

**内容描述:**

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/19203869/a9ba4dc4-42e9-41d6-a1df-60c8831103e7)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
assist默认1个小时1个，你用的是assist录制还是zlm的国标录制了？

**Comment by donnasky** [comment]
> assist默认1个小时1个，你用的是assist录制还是zlm的国标录制了？

用的assit，我在配置文件上没看到哪里改啊？

**Comment by mengxing2017** [comment]
改改源代码加个配置项就行了，assist代码不多，然后你发个pr即可

**Comment by donnasky** [comment]
> 改改源代码加个配置项就行了，assist代码不多，然后你发个pr即可

OK，我来研究研究

**Comment by 648540858** [comment]
录像分片长度配置在zlm中，
```
#mp4切片大小，单位秒
mp4_max_second=3600
```
