### ISSUE TITLE
视频流地址技术咨询

### ISSUE THREAD

**Issue by seven54** [648540858/wvp-GB28181-pro#1031]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/3e3b3bc3-fd15-45aa-86a9-3c2c3823f13e)
我们想用https查看视频流，现在想把返回的视频流址是IP，想改为域名。默认情况下，自签证书是不安全的。如果用购买的证书，可不可以替换

**Comment by lunasaw** [comment]
这里返回的是流媒体播放的地址, ZLM可以配置https的

**Comment by seven54** [comment]
现在通过外网https访问出现Your ip is not allowed to access the service.
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/be6d10c7-452e-4e25-9ea0-d460477e3a68)


通过wvp端口访问正常
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/697c6f54-1071-4ff4-a94b-f6d4f453f783)

**Comment by 648540858** [comment]
zlm的接口默认不支持公网访问的

**Comment by seven54** [comment]
是在wvp里面加访问白名单么。如下图

**Comment by 648540858** [comment]
zlm中，你这是直接访问的zlm的接口
```
#允许访问http api和http文件索引的ip地址范围白名单，置空情况下不做限制
allow_ip_range=127.0.0.1,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,10.0.0.0-10.255.255.255
```

**Comment by seven54** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/21f05e6f-87fd-4c11-b44a-7b848ac13c56)

**Comment by seven54** [comment]
好的。明白了。

**Comment by seven54** [comment]
还有个问题，开启防火墙看。视频都播放了了。需要开放哪些端口

**Comment by seven54** [comment]
还有个问题，开启防火墙看。视频都播放了了。需要开放哪些端口
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/54802461-485c-4084-a17e-bd3ec168eb71)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/80f3f6fe-b861-4c52-83b8-598c5f0e6630)
