### ISSUE TITLE
技术咨询：拉流时开启录制，日志报错：录像服务 代理失败；有的拉流地址没有进行录制

### ISSUE THREAD

**Issue by yebo-luo** [648540858/wvp-GB28181-pro#1032]
**环境信息:**

 - 1. 部署方式 wvp-pro+ wvp-assist + zlm都是编译部署/
 - 2. 部署环境 ubuntu 内网
 - 3. 代码更新时间 2023.05.25，wvp-pro-assist拉取了gitee最新的7月31日的代码
  之前wvp-pro的配置文件开启推流录制，可以正常查看云端录制视频。但是现在报了如下图的错误，还有一个rtmp拉流的地址开启录制无效，不生成录制mp4文件。
![image](https://github.com/648540858/wvp-GB28181-pro/assets/85433337/7ebc912d-a3e4-4513-bddd-3b70379cbf8f)

**Comment by 648540858** [comment]
这个错误原因不明，但是目前没发现有什么问题，rtmp不录制的问题，查看下你的源流是否可以播放，代理后的zlm流是否可以播放

**Comment by yebo-luo** [comment]
rtmp是可以正常播放的

**Comment by yebo-luo** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/85433337/cde89702-69f1-4a16-8fdd-70557c3f14eb)
请问wvp-pro的配置文件record-push-live: false和拉流时候的录制开关相关吗，哪个开了是启动云端录制的。

**Comment by xupuxjs** [comment]
录像服务 代理失败,也出现这种现象

**Comment by Lihy6472** [comment]
* 我也报这个错，云端录像也不行来着。点云端录像的查看默认没有视频，需要选一下才行，

![image](https://github.com/648540858/wvp-GB28181-pro/assets/116717391/a293e2cc-bad9-4f19-9672-7bfb32388476)

**Comment by XUXIAODI1119** [comment]
拉去最新的代码，目前也出现设置拉流，没有对应生成mp4文件视频。 大佬，这个问题您解决了嘛？是什么原因导致的，机器和服务目前都是走的内网
![image](https://github.com/648540858/wvp-GB28181-pro/assets/46105647/2fbe7713-e975-4902-b544-a2a4c7b89593)

**Comment by 648540858** [comment]
描述太少了，分析不出来

**Comment by 648540858** [comment]
提供下rtmp录制时的从流上线开始的zlm日志
