### ISSUE TITLE
技术咨询 如何设置开启录制以及相关说明

### ISSUE THREAD

**Issue by yebo-luo** [648540858/wvp-GB28181-pro#1033]
wvp-pro的配置文件record-push-live: false和拉流时候的录制开关相关吗，哪个开了是启动云端录制的。
![image](https://github.com/648540858/wvp-GB28181-pro/assets/85433337/572db777-e6bc-490d-8938-450c1a945792)

**Comment by yebo-luo** [comment]
有的需要开启录制，有的不需要怎么办

**Comment by yanpengfei-git** [comment]
<img width="804" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/37141737/19465264-e755-4bf9-9d0b-b5bfe681ba78">
楼主这个唯一id在哪获取，zlm是docker部署的

**Comment by 648540858** [comment]
推流的录制目前不支持分开控制
