### ISSUE TITLE
点播超时

### ISSUE THREAD

**Issue by yanpengfei-git** [648540858/wvp-GB28181-pro#1038]
**环境信息:**

 - 1. 部署方式zlm(docker) + 编译wvp-pro
 - 2. 部署环境 本地IDEA
 - 3. 端口开放情况 最新的zlm，防火墙已关闭
 - 4. 是否是公网部署  否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间

**内容描述:**
设备科已注册到平台，但是点击播放显示超时
zlm配置
`; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=nhExSIa881Kq1xZIUsMC7Uq6IohULbcf
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/usr/bin/ffmpeg
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -rtsp_transport tcp -i %s -y -f mjpeg -t 0.001 %s

[general]
check_nvidia_dev=1
enableVhost=0
enable_ffmpeg_log=0
flowThreshold=1024
maxStreamWaitMS=15000
mediaServerId=admin123
mergeWriteMS=0
resetWhenRePlay=1
streamNoneReaderDelayMS=20000
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fileBufSize=65536
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
alive_interval=10.0
enable=1
on_flow_report=
on_http_access=
on_play=http://192.168.10.11:18978/index/hook/on_play
on_publish=http://192.168.10.11:18978/index/hook/on_publish
on_record_mp4=http://127.0.0.1:18081/api/record/on_record_mp4
on_record_ts=
on_rtp_server_timeout=http://192.168.10.11:18978/index/hook/on_rtp_server_timeout
on_rtsp_auth=
on_rtsp_realm=
on_send_rtp_stopped=http://192.168.10.11:18978/index/hook/on_send_rtp_stopped
on_server_exited=https://127.0.0.1/index/hook/on_server_exited
on_server_keepalive=http://192.168.10.11:18978/index/hook/on_server_keepalive
on_server_started=http://192.168.10.11:18978/index/hook/on_server_started
on_shell_login=
on_stream_changed=http://192.168.10.11:18978/index/hook/on_stream_changed
on_stream_none_reader=http://192.168.10.11:18978/index/hook/on_stream_none_reader
on_stream_not_found=http://192.168.10.11:18978/index/hook/on_stream_not_found
retry=1
retry_delay=3.0
stream_changed_schemas=rtsp/rtmp/fmp4/ts/hls/hls.fmp4
timeoutSec=20

[http]
allow_cross_domains=1
allow_ip_range=
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=30
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:9b4605c/2023-08-26T23:02:19+08:00,branch:master,build time:2023-08-26T15:04:31)</center></body></html>
port=80
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[protocol]
add_mute_audio=1
auto_close=0
continue_push_ms=3000
enable_audio=1
enable_fmp4=1
enable_hls=1
enable_hls_fmp4=0
enable_mp4=0
enable_rtmp=1
enable_rtsp=1
enable_ts=1
fmp4_demand=0
hls_demand=0
hls_save_path=./www
modify_stamp=2
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
rtmp_demand=0
rtsp_demand=0
ts_demand=0

[record]
appName=record
fastStart=0
fileBufSize=65536
fileRepeat=0
sampleMS=500

[rtc]
externIP=
port=8000
preferredCodecA=PCMU,PCMA,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1,VP9,VP8
rembBitRate=0
tcpPort=8000
timeoutSec=15

[rtmp]
handshakeSecond=15
keepAliveSecond=15
port=1935
sslport=0

[rtp]
audioMtuSize=600
h264_stap_a=1
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
gop_cache=1
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=50000-50300
ps_pt=96
timeoutSec=15

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=554
rtpTransportType=-1
sslport=0

[shell]
maxReqSize=1024
port=0

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5

; } ---`
#mvp配置
`spring:

  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  redis:

    host: 127.0.0.1

    port: 6379

    database: 7

    password:

    timeout: 10000

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.198:3306/mvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 20000           
      initialSize: 10                       
      maximum-pool-size: 200           
      minimum-idle: 5                     
      idle-timeout: 300000              
      max-lifetime: 1200000                 

server:
  port: 18978

  ssl:

    enabled: false

    key-store: classpath:test.monitor.89iot.cn.jks

    key-store-password: gpf64qmw

    key-store-type: JKS

sip:

  ip: 192.168.10.11

  port: 5060

  domain: 4101050000

  id: 41010500002000000001

  password: bajiuwulian1006

  alarm: true

media:
  id: admin123

  ip: 192.168.10.11

  http-port: 8080

  stream-ip: 192.168.10.11

  sdp-ip: 192.168.10.11

  hook-ip: 192.168.10.11

  http-ssl-port: 8443

  secret: nhExSIa881Kq1xZIUsMC7Uq6IohULbcf
  rtp:
    enable: true
    port-range: 50000,50300 # 端口范围
    send-port-range: 50000,50300 # 端口范围
  record-assist-port: 18081
user-settings:
  play-timeout: 180000
  auto-apply-play: true
  device-status-notify: true
  allowed-origins:
    - http://localhost:8081
    - http://127.0.0.1:8081
logging:
  config: classpath:logback-spring-local.xml`

**截图**  
<img width="1710" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/37141737/5867c20e-8158-4b30-afc5-d43fafad031c">

**抓包文件**
  
**日志**
```
<img width="844" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/37141737/42a818ec-5eec-4cd4-ae86-b0388e636844">
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
zlm端口没开

**Comment by 648540858** [comment]
搜索issue找找吧，回答了很多了
