### ISSUE TITLE
 [ 技术咨询 ]用https域名出现新建拉流失败

### ISSUE THREAD

**Issue by seven54** [648540858/wvp-GB28181-pro#1039]
如下图所示，新建拉流。直接提示这个错误

![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/7fdc7d5c-7934-4f31-a4cc-e52ce982ecac)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/4109506a-e3c3-4d8c-aa2f-5005f39aa8a0)

**Comment by mengxing2017** [comment]
这个地址能用vlc拉流吗

**Comment by seven54** [comment]
解决这个问题了。需要在服务器做个本地hosts
