### ISSUE TITLE
建议增加经纬度和入库时间的显示

### ISSUE THREAD

**Issue by funthing** [648540858/wvp-GB28181-pro#104]
查看代码发现数据库中实有经纬度相关的字段的，只是设备入库的时候没有把经纬度写入数据库，经纬度用到的频率应该还是挺高的，另外就是没有入库时间的展示，不知道设备的推送时间，

**Comment by 648540858** [comment]
ok, 这个可以加一下

**Comment by 648540858** [comment]
已添加
