### ISSUE TITLE
前端报这个异常是否正常【咨询】

### ISSUE THREAD

**Issue by shuaigelsy** [648540858/wvp-GB28181-pro#1040]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况 为了测试完全放开
 - 4. 是否是公网部署 是
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台 
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 git上最新的代码

**描述错误**
点播后关闭窗口无法关闭流

**如何复现**
国标设备->通道->点播

**截图**  
![微信截图_20230830175815](https://github.com/648540858/wvp-GB28181-pro/assets/143484224/6080806d-d54b-4b9a-912a-ecfd417446aa)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
x只是关闭播放弹窗，想马上关闭需要点击停止按钮
