### ISSUE TITLE
分屏监控使用jessbuca播放器点播延时的问题【咨询】

### ISSUE THREAD

**Issue by Kender0221** [648540858/wvp-GB28181-pro#1041]
1、该如何解决。
2、ZLMediaKit开启了WebRTC,如何把分屏监控替换为WebRTC播放。

**Comment by mengxing2017** [comment]
分屏那里把播放器换掉就行了，直播那里有webrtc使用代码参考

**Comment by Kender0221** [comment]
> 分屏那里把播放器换掉就行了，直播那里有webrtc使用代码参考

Thanks bro
