### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by davidZhang666-bin** [648540858/wvp-GB28181-pro#1042]
使用海康执法记录仪注册平台后使用分屏监控报错
错误信息：
Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)

java.lang.NullPointerException: text
	at java.util.Objects.requireNonNull(Objects.java:228)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1775)
	at com.genersoft.iot.vmp.utils.DateUtil.getDifferenceForNow(DateUtil.java:112)

**Comment by Kender0221** [comment]
贴上来一堆没用的代码

**Comment by davidZhang666-bin** [comment]
错误原因大概是因为没有注册进来通道数量，在更新通道数量的时候会报错，不知道是摄像机的问题还是什么原因，会提示设备id不存在，我的设备不是普通的摄像机，是海康的执法记录仪...

**Comment by davidZhang666-bin** [comment]
> 

代码只报了这些错，所以只能贴上来问问了

**Comment by Kender0221** [comment]
> > 
> 
> 代码只报了这些错，所以只能贴上来问问了

系统信息有没有什么提示？

**Comment by 648540858** [comment]
至少把模版信息填写下，我也好知道你的基本情况，我先关了，不符合提问规范
