### ISSUE TITLE
BUG SSRC不一致导致的WVP 播放cup错误（一直转圈等待）

### ISSUE THREAD

**Issue by DavidSche** [648540858/wvp-GB28181-pro#1049]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 -   编译又部署
 - 2. 部署环境 windows / ubuntu/ centos ...
 -   centos
 - 3. 端口开放情况
 - 
 - 4. 是否是公网部署 
 -   否
 - 5. 是否使用https
 -  是
 - 6. 方便的话提供下使用的设备品牌或平台
 -  海康威视DS-7804N-K1/C（D） 主版本V4.72.109构建230107
 - 7. 你做过哪些尝试
 - 
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题

使用WVP级联时，经常会出现上级平台无法正常播放的情况，播放页面不断转圈，级联级别越多概率越大。
发现当上级平台播放时，同一个设备-通道在数据库中生成了两个 SSRC不同的key VMP_INVITE:PLAY   
参见下图
![1693805543502](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/4871b30e-42f7-4b39-b2ee-2ad87706b062) 
两个的状态不一样

![1693805543502](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/0cbe8bfa-fa8c-4225-9d03-98295c67c469)
![1693805543523](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/1ea8bd18-4cbd-4f78-b21f-8c38b27c7658)

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
我怎么复现你说的问题

**Comment by 648540858** [comment]
已经修复了
