### ISSUE TITLE
关于SIP命令交互

### ISSUE THREAD

**Issue by programcj** [648540858/wvp-GB28181-pro#105]
SipSubscribe 订阅消息没有删除的概念
SIP 消息如果超时发送怎么办？

**Comment by 648540858** [comment]
SipSubscribe 都一些是搭配DeferredResult使用的，DeferredResult有超时时间，一种是单独做了超时处理，比如src/main/java/com/genersoft/iot/vmp/gb28181/event/platformNotRegister/PlatformNotRegisterEventLister.java的87行
