### ISSUE TITLE
BUG   wvp 平台的国标级联的选择通道界面删除目录时，如果目录下有子目录，没有删除对应的子目录

### ISSUE THREAD

**Issue by DavidSche** [648540858/wvp-GB28181-pro#1052]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题

  BUG   wvp 平台的国标级联的选择通道界面删除目录时，如果目录下有子目录，没有删除对应的子目录，

 数据库中遗留着下级节点的数据，但他们的上级节点数据已经删除
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/c2ff83a3-706a-4478-af51-39bb2c84bfbb)

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你再测试下，我在当前代码没复现出来，我先关了
