### ISSUE TITLE
[BUG]   FFMPEG 拉流代理   在线http协议

### ISSUE THREAD

**Issue by lironghai** [648540858/wvp-GB28181-pro#1053]
**环境信息:**

 - 1. 部署方式： wvp-pro docker / zlm(docker) 
 - 2. 部署环境 ：docker ubuntu
 - 3. 端口开放情况：开放
 - 4. 是否是公网部署 ：否
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试：直接调用zlm接口
 - 8. 代码更新时间: 昨天 0904

**描述错误**
描述下您遇到的问题
拉流代理ffmpeg使用在线MP4 url 拉流失败；

**如何复现**
有明确复现步骤的问题会很容易被解决
添加ffmpeg拉流代理，使用在线的MP4视频地址

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

是由于dst_url地址协议头拼接问题，数据库内为flv:// ,实际应为rtmp:// ；修改为rtmp直接调用zlm addFFmpegSource接口是成功的；

**Comment by lironghai** [comment]
![企业微信截图_16938880673508](https://github.com/648540858/wvp-GB28181-pro/assets/34302941/f9ce1d43-2f24-476f-8dde-80b9a1cfe159)

**Comment by lironghai** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/34302941/07b4fafd-eeb9-4be3-b313-6bb5485ce28a)

**Comment by lironghai** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/34302941/c0248666-92e1-4882-9fa1-81ff94c98187)

**Comment by 648540858** [comment]
目前的接口是对两种拉流代理做了合并，所以协议支持的不完善，建议脱离wvp直接调用zlm的接口解决，后续考虑处理下。
