### ISSUE TITLE
web-src在dev模式下正常运行,run build无法生成dist目录和文件.无法正常打包

### ISSUE THREAD

**Issue by anyinlink** [648540858/wvp-GB28181-pro#106]
大家都没遇到吗好像build里的config的index.js里只配置了dev模式下的一些东西.prod模式下没地方配置.比如wvp的后端API地址

另外
    // Template for index.html   
     index: path.resolve(__dirname, '../../src/main/resources/static/index.html'),

这个文件是缺失了?

有没有完整打包过的?

**Comment by 648540858** [comment]
1 默认打包生成路径已经改了，不是使用dist，是在src/main/resources/static方便打包jar
2 如果你想前后端分离部署，两中方式，一是在web_src/config/index.js， 修改http://localhost:18080 为你实际的ip端口，而是使用nginx代理
