### ISSUE TITLE
EventSource收不到后台推过来的数据

### ISSUE THREAD

**Issue by adminDYY** [648540858/wvp-GB28181-pro#1060]
EventSource收不到后台推过来的数据，也不报错，后台已推送浏览器，但浏览器的EventSource没有收到信息open是是正常的，我怀疑webmvc5.3.22里面的SseEmitter升级导致的，因为之前是webmvc5.3.19里面的SseEmitter,所以我写了一个demo，来个版本我都有测试，结果我测得都没有问题，但是项目中的SseEmitter发出的数据前端无法收到，open正常

**Comment by 648540858** [comment]
这个推送我没有严格测试过，以前是好的，你可以测测提个PR，一直觉得这个推送没什么用
