### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by zhanpc** [648540858/wvp-GB28181-pro#1061]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows 
 - 3. 端口开放情况 全开
 - 4. 是否是公网部署  是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康威视
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间

**内容描述:**
摄像头注册 本地可以 公网注册一直不在线
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
端口放通了吗？udp端口哦
