### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by zhanpc** [648540858/wvp-GB28181-pro#1062]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows 
 - 3. 端口开放情况 全开
 - 4. 是否是公网部署  公网
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台 海康威视
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
wvo-pro webrtc界面是可以看到视频
webrtc得地址无法播放   使用得是liveplayer播放插件
wvp-pro直接返回得地址打开是400报错
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/86341644/2b7031de-0c26-47b9-ac93-58b4fe9c8693)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/86341644/fb610248-1a3c-445c-96c5-2501bd08c1e3)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
liveplayer不支持zlm的webrtc地址。只支持livegbs自己的webrtc
