### ISSUE TITLE
[BUG] 自动点播超时一次后下次无法点播

### ISSUE THREAD

**Issue by godlike10** [648540858/wvp-GB28181-pro#1063]
**环境信息:**

 - 1. 部署方式  wvp-pro + zlm都是编译部署/
 - 2. 部署环境  centos7
 - 3. 端口开放情况 使用端口都开放了
 - 4. 是否是公网部署  是
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题
程序运行了3天时间，前两天都正常，第三天的时候用potplayer 点播某路设备的视频一直黑屏，看了下日志，点播超时。
但是在wvp后台点播能够点播成功。
看了下代码感觉是流未找到事件中，已有点播记录，或者redis中的记录未被清理
![image](https://github.com/648540858/wvp-GB28181-pro/assets/6766502/0a9dbe63-72bc-4dfd-b956-5df60ca430d6)

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/6766502/eb02407f-e9a7-43f4-a1a2-ee5f553f958d)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
代码提交了，你测测吧
