### ISSUE TITLE
地址转换问题

### ISSUE THREAD

**Issue by xiaoxiao5009** [648540858/wvp-GB28181-pro#1066]
环境：
摄像头地址：23.62；
ZLM地址：32.160；
wvp地址：23.155

环境搭建完成后，视频一直播放不了，经过监测，在点击播放的时候，调用接口：
http://192.168.23.155:18080/api/play/start/34020000002000000001/34020000001320000001
得到返回值：
{
    "code": 0,
    "data": {
        "app": "rtp",
        "flv": "http://192.168.23.155:80/rtp/34020000002000000001_34020000001320000001.live.flv",
        "fmp4": "http://192.168.23.155:80/rtp/34020000002000000001_34020000001320000001.live.mp4",
        "hls": "http://192.168.23.155:80/rtp/34020000002000000001_34020000001320000001/hls.m3u8",
        "https_flv": "https://192.168.23.155:443/rtp/34020000002000000001_34020000001320000001.live.flv",
        "https_fmp4": "https://192.168.23.155:443/rtp/34020000002000000001_34020000001320000001.live.mp4",
        "https_hls": "https://192.168.23.155:443/rtp/34020000002000000001_34020000001320000001/hls.m3u8",
        "https_ts": "https://192.168.23.155:443/rtp/34020000002000000001_34020000001320000001.live.ts",
        "mediaServerId": "chenjw",
        "progress": 0.0,
        "rtc": "http://192.168.23.155:80/index/api/webrtc?app=rtp&stream=34020000002000000001_34020000001320000001&type=play",
        "rtcs": "https://192.168.23.155:443/index/api/webrtc?app=rtp&stream=34020000002000000001_34020000001320000001&type=play",
        "rtmp": "rtmp://192.168.23.155:1935/rtp/34020000002000000001_34020000001320000001",
        "rtsp": "rtsp://192.168.23.155:554/rtp/34020000002000000001_34020000001320000001",
        "stream": "34020000002000000001_34020000001320000001",
        "tracks": [
            {
                "channels": 0,
                "codecId": 0,
                "codecType": 0,
                "fps": 25,
                "height": 1080,
                "ready": true,
                "sampleBit": 0,
                "sampleRate": 0,
                "width": 1920
            }
        ],
        "ts": "http://192.168.23.155:80/rtp/34020000002000000001_34020000001320000001.live.ts",
        "ws_flv": "ws://192.168.23.155:80/rtp/34020000002000000001_34020000001320000001.live.flv",
        "ws_fmp4": "ws://192.168.23.155:80/rtp/34020000002000000001_34020000001320000001.live.mp4",
        "ws_hls": "ws://192.168.23.155:80/rtp/34020000002000000001_34020000001320000001/hls.m3u8",
        "ws_ts": "ws://192.168.23.155:80/rtp/34020000002000000001_34020000001320000001.live.ts",
        "wss_flv": "wss://192.168.23.155:443/rtp/34020000002000000001_34020000001320000001.live.flv",
        "wss_fmp4": "wss://192.168.23.155:443/rtp/34020000002000000001_34020000001320000001.live.mp4",
        "wss_hls": "wss://192.168.23.155:443/rtp/34020000002000000001_34020000001320000001/hls.m3u8"
    },
    "msg": "成功"
}

而23.155上没有开启80和443端口。

经过检查，发现用192.168.32.160可以正常播放，查看代码，发现里面有一个地址替换的内容：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37928689/a406dc58-9a36-42f2-a682-e3e17b363053)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37928689/344f4925-958b-4a1b-a0e6-24c83483f18a)
注释掉该代码，返回内容为：
{
    "code": 0,
    "data": {
        "app": "rtp",
        "flv": "http://192.168.32.160:80/rtp/34020000002000000001_34020000001320000001.live.flv",
        "fmp4": "http://192.168.32.160:80/rtp/34020000002000000001_34020000001320000001.live.mp4",
        "hls": "http://192.168.32.160:80/rtp/34020000002000000001_34020000001320000001/hls.m3u8",
        "https_flv": "https://192.168.32.160:443/rtp/34020000002000000001_34020000001320000001.live.flv",
        "https_fmp4": "https://192.168.32.160:443/rtp/34020000002000000001_34020000001320000001.live.mp4",
        "https_hls": "https://192.168.32.160:443/rtp/34020000002000000001_34020000001320000001/hls.m3u8",
        "https_ts": "https://192.168.32.160:443/rtp/34020000002000000001_34020000001320000001.live.ts",
        "mediaServerId": "chenjw",
        "progress": 0.0,
        "rtc": "http://192.168.32.160:80/index/api/webrtc?app=rtp&stream=34020000002000000001_34020000001320000001&type=play",
        "rtcs": "https://192.168.32.160:443/index/api/webrtc?app=rtp&stream=34020000002000000001_34020000001320000001&type=play",
        "rtmp": "rtmp://192.168.32.160:1935/rtp/34020000002000000001_34020000001320000001",
        "rtsp": "rtsp://192.168.32.160:554/rtp/34020000002000000001_34020000001320000001",
        "stream": "34020000002000000001_34020000001320000001",
        "tracks": [
            {
                "channels": 0,
                "codecId": 0,
                "codecType": 0,
                "fps": 25,
                "height": 1080,
                "ready": true,
                "sampleBit": 0,
                "sampleRate": 0,
                "width": 1920
            }
        ],
        "ts": "http://192.168.32.160:80/rtp/34020000002000000001_34020000001320000001.live.ts",
        "ws_flv": "ws://192.168.32.160:80/rtp/34020000002000000001_34020000001320000001.live.flv",
        "ws_fmp4": "ws://192.168.32.160:80/rtp/34020000002000000001_34020000001320000001.live.mp4",
        "ws_hls": "ws://192.168.32.160:80/rtp/34020000002000000001_34020000001320000001/hls.m3u8",
        "ws_ts": "ws://192.168.32.160:80/rtp/34020000002000000001_34020000001320000001.live.ts",
        "wss_flv": "wss://192.168.32.160:443/rtp/34020000002000000001_34020000001320000001.live.flv",
        "wss_fmp4": "wss://192.168.32.160:443/rtp/34020000002000000001_34020000001320000001.live.mp4",
        "wss_hls": "wss://192.168.32.160:443/rtp/34020000002000000001_34020000001320000001/hls.m3u8"
    },
    "msg": "成功"
}

这样可以直接播放，查看前端那边也是直接使用播放器插件选取的返回值中地址进行直接播放，
如果要用转换后的地址：192.168.23.155****来播放视频，
还需要单独添加什么功能模块或开启什么配置吗？

**Comment by mengxing2017** [comment]
stream-ip地是设置公网ip

**Comment by xiaoxiao5009** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我正忙，无法亲自回复你的邮件。我将在不忙，尽快给你回复。

**Comment by 648540858** [comment]
use-source-ip-as-stream-ip: 设置为false

**Comment by xiaoxiao5009** [comment]
谢谢，我们也尝试下，咱的社区加入有时间限制吗？
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年9月11日 10:18
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [648540858/wvp-GB28181-pro] 地址转换问题 (Issue #1066)
        
      
    
  

Closed #1066 as completed.
