### ISSUE TITLE
[BUG] 发送BYE时 getHostName()可能导致超时

### ISSUE THREAD

**Issue by 17863940205zm** [648540858/wvp-GB28181-pro#1068]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
停止点播时这行代码会出现解析域名等待超时的现象，byeURI.setHost(request.getRemoteAddress().getHostName());

**如何复现**
有明确复现步骤的问题会很容易被解决
如果这个IP地址不能够进行域名解析的话会出现阻塞的问题

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
好的，我测试下

**Comment by 648540858** [comment]
现在应该已经修复了，找不到这个了，我先关闭了
