### ISSUE TITLE
点播失败， 错误码： 486, Busy Here技术咨询

### ISSUE THREAD

**Issue by seven54** [648540858/wvp-GB28181-pro#1074]
大华摄像头，安装完SD卡之后，出现点播错误。
设备型号： DH-SD3200-ADP-PV-i
系统版本：V2.811.0000006.0.R, Build Date: 2023-04-27

![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/861b3cf5-2e4a-4b2f-b00f-caa533f68f38)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/deee6aed-7aff-4800-b060-6c431f64a991)

**Comment by qimingkunnanzheng** [comment]
我也是这个问题，请问解决了吗

**Comment by qimingkunnanzheng** [comment]
我也是这个问题，请问解决了吗

**Comment by seven54** [comment]
找客服升级到最新固件，可以将就着用。但是容易串流

**Comment by 648540858** [comment]
单端口收流？多端口的话开放了多少端口

**Comment by seven54** [comment]
不是收流，就是在线直播，SD卡本地存储看回放。如果摄像头不插SD卡，没问题。一插上SD卡，就出上面的问题。更新摄像头固件之后，上面截图问题没有了，但是出现串流现像，而且串流之后，国标通道很容易阻塞。

**Comment by 1294403205** [comment]
我也是这个问题摄像头连续挂了2天之后就出现这个问题了，需要把摄像头设置里面的的国标推流接入断开，然后再打开就好了
