### ISSUE TITLE
多节点时，子节点点播超时

### ISSUE THREAD

**Issue by qimingkunnanzheng** [648540858/wvp-GB28181-pro#1076]
**环境信息:**

 - 1. 部署方式 wvp-pro/ zlm + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos
 - 3. 端口开放情况   是
 - 4. 是否是公网部署   是
 - 5. 是否使用https  是
 - 6. 方便的话提供下使用的设备品牌或平台  大华
 - 7. 你做过哪些尝试  修改zlm配置id
 - 8. 代码更新时间  ### 最新

**内容描述:**
多节点时，只有主节点能播放，到子节点时通道一直转圈最后显示点播超时
**截图**  
子节点图片
![1694762238566](https://github.com/648540858/wvp-GB28181-pro/assets/144506949/c341c638-2a5c-45a7-a11c-85eea42c6d10)

主节点
![1694762075408](https://github.com/648540858/wvp-GB28181-pro/assets/144506949/93b8fd43-822e-4e3a-98c1-5a01564d6e6b)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
sdp ip不可以使用域名
