### ISSUE TITLE
技术咨询 语音对讲功能有吗

### ISSUE THREAD

**Issue by asd123wto** [648540858/wvp-GB28181-pro#1080]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 windows 
 - 3. 端口开放情况 全开
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试 调用语音广播命令API
 - 8. 代码更新时间 2023/09/20

**内容描述:**
语音对讲的api是语音广播命令API吗？如何实现对讲？现在我调用得到的是：
{
    "code": 0,
    "data": {
        "DeviceID": "33011024991327977322",
        "CmdType": "Broadcast",
        "Result": "Failed",
        "Error": "Timeout. Device did not response to broadcast command."
    },
    "msg": "成功"
}
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
作者接受语音对讲定制

**Comment by MengFanLu1** [comment]
对讲可以联系我，微信17686791164
