### ISSUE TITLE
海康威视4G摄像头注册，未携带授权头

### ISSUE THREAD

**Issue by zh52722** [648540858/wvp-GB28181-pro#1081]
**环境信息:**

 - 1. 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境是centos7.4
 - 3. 端口开放情况
 - 4. wvp和zlm在不同的内网下部署，都做了外网映射
 - 5. 未使用https

**内容描述:**
摄像头未启用4G时，可以正常连接。启用4G后，不能注册，参数缺少授权头，偶尔可以注册成功，但是不发送心跳
**截图**  
sip配置
![image](https://github.com/648540858/wvp-GB28181-pro/assets/7601234/c678d2e6-147a-4fca-b54c-c5cf60cb8f61)
zlm配置
![image](https://github.com/648540858/wvp-GB28181-pro/assets/7601234/9b545175-1b21-4a29-b5e1-642d09700cc8)
wvp公网映射
![image](https://github.com/648540858/wvp-GB28181-pro/assets/7601234/93b94cf1-3d96-415d-b14f-6a285d354e06)
4G摄像头配置
![image](https://github.com/648540858/wvp-GB28181-pro/assets/7601234/58f8d4d4-a88a-4492-94d5-72c7ebe6eb0e)
wvp日志截图
![image](https://github.com/648540858/wvp-GB28181-pro/assets/7601234/9504c212-995c-4451-9ad2-b83530beedd8)
抓包截图
![image](https://github.com/648540858/wvp-GB28181-pro/assets/7601234/b9a4601f-2945-493d-9e0f-3a59b56b7818)

**Comment by gpsim** [comment]
同样的问题，求解

**Comment by 648540858** [comment]
有的4G网络需要开启SIP功能才能正常使用，如果网线正常，4G心跳不通那么就是你的4G网络的问题了
