### ISSUE TITLE
国标设备在线，设备中的通道摄像头在线或离线，无法定期更新

### ISSUE THREAD

**Issue by 925008670** [648540858/wvp-GB28181-pro#1083]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
国标设备在线，设备中的通道摄像头在线或离线，无法定期更新

**如何复现**
国标设备在线，通道摄像头在线，然后在录像机中吧摄像头拔掉，录像机中无此摄像头，WVP网站中还是显示在线，等了一个多小时也没有更新，应该没有定时更新国标设备中的通道中摄像头在线离线机制，希望添加一个定时器，定期更新摄像头状态，不知拉流代理中的视频是不是也是如此，如果拉流代理中的视频修改为无人观看时停用，是不是设备无法观看的时候，状态也不会变更，没有做测试，希望修改此问题

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
国标的状态变更来自目录订阅，开启订阅可以实时更新通道状态，拉流代理停用会设置为离线
