### ISSUE TITLE
无法停止点播

### ISSUE THREAD

**Issue by cherryoooo** [648540858/wvp-GB28181-pro#1084]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
视频点播后,点击停止按钮,不能停止,错误信息为 [点播未找到]

**如何复现**
通道列表处点播视频,点播之后,点击后面的停止点播按钮,无法停止点播

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
日志贴下

**Comment by cherryoooo** [comment]
无法停止点播版本redis中inviteinfo信息:
<img width="1240" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/130945319/ea64a43a-f8aa-4267-b6f5-02757b46fed3">

正常(7.25版本)redis中inviteinfo信息
<img width="1431" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/130945319/c10f48e9-4e16-4ac8-92df-98673cc02c1b">


第一次点击点播能正常播放,播放后x掉播放窗口,再次点击,稳定显示播放超时,此时日志如下
<img width="1739" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/130945319/0bfad011-4b39-4d20-8e3a-d1de96ae86d8">


且该情况下点击停止播放仅打一行日志,如下
<img width="758" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/130945319/65a3e5cb-f93a-431c-bf87-4aca0b8347aa">
返回如下:
<img width="312" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/130945319/6c2634d2-c514-43ff-bec1-c59d4a6a1fba">


应该是redis中inviteinfo的key的问题,多次点播ssrc不一致会有多个,查询到的结果不为1,返回null,但是在不同机器上部署同一个版本一个没问题(参见正常redis中inviteinfo),一个存在问题(参见不正常redis中inviteinfo)
