### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by yuzhihaoGitHub** [648540858/wvp-GB28181-pro#1085]
**环境信息:**

**描述错误**
1.对接的海康摄像头，因为摄像头的视频编码是H265，点击转码发现视频流改变，转码也没有发生。
2.转码的流streamId通过 zlmresTfulUtils.getRtpInfo(mediaInfo, streamId)获取不到对应zlm的视频流，在hook通知后流ID替换在zlm不生效吧

<img width="685" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/53512354/d4d77f52-05d1-42cf-a48b-63b15a6f737f">

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
转码之前
<img width="742" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/53512354/c8740e49-5cfe-433b-8a3d-27c3911302af">
转码之后
<img width="739" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/53512354/59fb2196-be3f-4558-a3d0-fd6bb466ac3c">

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
转码功能目前没测试，可能是不能用的，后续考虑移除或重新实现。

**Comment by yuzhihaoGitHub** [comment]
哦哦好的感谢回答
