### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by JQYXQ** [648540858/wvp-GB28181-pro#1086]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
搭建完成后，使用没啥问题，但是看日志有很多默认设备一直再注册，请问大神这个是什么原因呢，有办法关掉吗，谢谢
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/34978472/3ffaf2d6-354b-444b-a731-29823649b012)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
正常是定时注册，不清楚的设备注册成功没，如果失败，设备可能会不断的注册，检查下设备的国标配置，看看是不是密码或者国标的信息填写错误了。
