### ISSUE TITLE
BUG关于截图未关闭刘导致的异常

### ISSUE THREAD

**Issue by yaoxiaojian-liuxiaojun** [648540858/wvp-GB28181-pro#1087]
**环境信息:**

 - 1. 部署方式 wvp-pro 编译部署/
 - 2. 部署环境 centos7

**描述错误**
wvp截图功能未关闭流

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/59216715/b05fad89-8860-47bb-ade4-ed2051d40b43)

**Comment by 648540858** [comment]
已修复
