### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by linkewei0580** [648540858/wvp-GB28181-pro#1088]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu/22
 - 3. 端口开放情况
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

服务器都部署在内网，内网目前功能正常，如果通过路由器做端口映射，通过公网访问wvp-GB28181-pro，查看视频需要改哪个参数，谢谢!

**Comment by 648540858** [comment]
修改wvp的配置，media下的stream ip配置为公网的ip, http-port需要映射到公网，内网，公网只能一侧使用

**Comment by scdn** [comment]
我用的是frp,不需要修改本地配置,直接在frp中添加条目

**Comment by linkewei0580** [comment]
> 我用的是frp,不需要修改本地配置,直接在frp中添加条目

frp 是另外的项目，有链接地址吗？

**Comment by scdn** [comment]
> > 我用的是frp,不需要修改本地配置,直接在frp中添加条目
> 
> frp 是另外的项目，有链接地址吗？

https://github.com/fatedier/frp
