### ISSUE TITLE
在接入华为摄像头的时候，查看录像会报错XML解析错误，

### ISSUE THREAD

**Issue by JonouZ** [648540858/wvp-GB28181-pro#1089]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker)
 - 2. 部署环境  ubuntu
 - 3. 端口开放情况  433 554  30000-50000 1935 等等都放开了
 - 4. 公网部署
 - 5. 使用https
 - 6. 华为车牌识别摄像头

**描述错误**
实时预览都没有问题，就是查询录像文件有问题，录像文件是在摄像头的tf卡中

 国标平台调用摄像头录像会报  eAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)
监测到的接收摄像头消息是正常的

**如何复现**
有明确复现步骤的问题会很容易被解决

[**截图**  ]
![企业微信截图_16956261591104](https://github.com/648540858/wvp-GB28181-pro/assets/56708898/02a2ab04-d86f-46fe-97a9-d249490c261f)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by JonouZ** [comment]
[wvp-2023-09-25.0.log](https://github.com/648540858/wvp-GB28181-pro/files/12712372/wvp-2023-09-25.0.log)

**Comment by 648540858** [comment]
抓包文件也发下

**Comment by JonouZ** [comment]
> 抓包文件也发下

cap文件不支持上传

**Comment by JonouZ** [comment]
抓包文件

**Comment by JonouZ** [comment]
抓包文件，麻烦你看下
[cap.zip](https://github.com/648540858/wvp-GB28181-pro/files/12720888/cap.zip)

**Comment by 648540858** [comment]
你用的什么版本的代码。模拟测试了一下并没有问题

**Comment by JonouZ** [comment]
2.6.8的版本，用的https和docker從我的iPhone傳送648540858 ***@***.***> 於 2023年9月30日 06:57 寫道：﻿
你用的什么版本的代码。模拟测试了一下并没有问题

**Comment by JonouZ** [comment]
Zlmeidakit也是docker部署的從我的iPhone傳送648540858 ***@***.***> 於 2023年9月30日 06:57 寫道：﻿
你用的什么版本的代码。模拟测试了一下并没有问题

**Comment by 648540858** [comment]
对比版本看了下，代码报错的位置在269是增加了兼容性处理的，建议更新到269再测试下

**Comment by JonouZ** [comment]
> 对比版本看了下，代码报错的位置在269是增加了兼容性处理的，建议更新到269再测试下

好的，我试试

**Comment by JonouZ** [comment]
> 对比版本看了下，代码报错的位置在269是增加了兼容性处理的，建议更新到269再测试下

更新到2.6.9 版本了，还是有报错的问题
![企业微信截图_16966586385521](https://github.com/648540858/wvp-GB28181-pro/assets/56708898/62ae12f0-2324-4120-b6d8-7c1f002c04b0)

**Comment by JonouZ** [comment]
![企业微信截图_16966586489214](https://github.com/648540858/wvp-GB28181-pro/assets/56708898/af1d8220-db30-4ccb-9fbc-76b56409ebc6)

**Comment by 648540858** [comment]
最新的这个发个抓包

**Comment by JonouZ** [comment]
[文件：test1.cap]

**Comment by JonouZ** [comment]
> 最新的这个发个抓包

[test1(1).zip](https://github.com/648540858/wvp-GB28181-pro/files/12837009/test1.1.zip)
最新的包，你看一下，

**Comment by JonouZ** [comment]
这是报错打印的日志
![企业微信截图_16966605783020](https://github.com/648540858/wvp-GB28181-pro/assets/56708898/34b31afe-7573-462f-bdb4-f15d86727bce)

**Comment by 648540858** [comment]
代码我单独测试没有问题，测试了二进制直接解析也没复现问题，不过测试代码与正式代码有一点不一样，我更新了一下，你试试看看是不是这除不一样的地方修复了这个问题

**Comment by 648540858** [comment]
如果还是不行就把 
```
sip-log: true
```
加上看看日志

**Comment by JonouZ** [comment]
> 如果还是不行就把
> 
> ```
> sip-log: true
> ```
> 
> 加上看看日志

好的，我再试试，

**Comment by JonouZ** [comment]
> > 如果还是不行就把
> > ```
> > sip-log: true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 加上看看日志
> 
> 好的，我再试试，

更新了代码，部署了一下，还是有报错呢
![企业微信截图_16966645062464](https://github.com/648540858/wvp-GB28181-pro/assets/56708898/cd46a503-c1e2-427a-a556-4c83edd748a7)

**Comment by 648540858** [comment]
日志文件给我一份

**Comment by JonouZ** [comment]
> 日志文件给我一份
[cap.zip](https://github.com/648540858/wvp-GB28181-pro/files/12837107/cap.zip)

**Comment by 648540858** [comment]
抓包和日志对不上，还的麻烦抓包和日志一起发我一份新的，我再研究下

**Comment by JonouZ** [comment]
> 抓包和日志对不上，还的麻烦抓包和日志一起发我一份新的，我再研究下

好的，你稍等

**Comment by JonouZ** [comment]
> > 抓包和日志对不上，还的麻烦抓包和日志一起发我一份新的，我再研究下
> 
> 好的，你稍等
[Desktop.zip](https://github.com/648540858/wvp-GB28181-pro/files/12837129/Desktop.zip)

**Comment by JonouZ** [comment]
> > > 抓包和日志对不上，还的麻烦抓包和日志一起发我一份新的，我再研究下
> > 
> > 
> > 好的，你稍等
> > [Desktop.zip](https://github.com/648540858/wvp-GB28181-pro/files/12837129/Desktop.zip)

补充一下：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/56708898/ef8670df-81f0-432e-a3b3-01321742164d)
华为这个摄像头有两个通道，第二个通道之前也是不行，但是刚才改了以后，目前看来是正常的，不知道后面会不会报错，但是第一个通道是一直都不行的，都报错

**Comment by JonouZ** [comment]
现在第二个通道也不行了，报错了
![企业微信截图_1696673511369](https://github.com/648540858/wvp-GB28181-pro/assets/56708898/0ab5eac6-ecb0-433a-8885-ff22b3db6e36)

**Comment by 648540858** [comment]
目前没找到原因，直接收到的数据包有错误字符，导致dom4j解析xml出错了，但是从抓包得到的数据直接解析却没有这个问题，这个设备有没有购买链接。我看看不行我自己买一个测测。

**Comment by xuanxuan-cc** [comment]
我们在本地测试也没有问题，本地的zlmediakit没有用docker起（http请求）；公网的zlmediakit是用docker启动的（https请求），跟这个有关系吗？

**Comment by xuanxuan-cc** [comment]
我们买的华为-好望下的 D2150-10-SIU 型号的摄像机

**Comment by 648540858** [comment]
没关系，我把整个udp数据包也测试了一下也没有问题。你的网络是什么样子的，设备到wvp之间的

**Comment by 648540858** [comment]
> 我们买的华为-好望下的 D2150-10-SIU 型号的摄像机

有购买链接吗

**Comment by 648540858** [comment]
华为的国标配置页面你看看能不能切换为tcp，

**Comment by JonouZ** [comment]
> 没关系，我把整个udp数据包也测试了一下也没有问题。你的网络是什么样子的，设备到wvp之间的
wvp 部署在公网服务器，摄像头是在我们的局域网下

**Comment by JonouZ** [comment]
> > 我们买的华为-好望下的 D2150-10-SIU 型号的摄像机
> 
> 有购买链接吗

这个我们也没有，厂家直接拿过来的

**Comment by JonouZ** [comment]
> 华为的国标配置页面你看看能不能切换为tcp，

这个我们切换过了

**Comment by JonouZ** [comment]
> > 华为的国标配置页面你看看能不能切换为tcp，
> 
> 这个我们切换过了，在观察一下

**Comment by 648540858** [comment]
那就只能是把服务部署在局域网测试下了，目前我测试发的数据包i是没有问题的，但是时好时坏，所以我怀疑是网络的问题，
局域网了接在一个路由下测试下吧

**Comment by JonouZ** [comment]
> 那就只能是把服务部署在局域网测试下了，目前我测试发的数据包i是没有问题的，但是时好时坏，所以我怀疑是网络的问题， 局域网了接在一个路由下测试下吧

局域网的环境我们测试过，但是没有https，局域网是可以的

**Comment by 648540858** [comment]
也可以再购买一个大华一起测试下，如有也有一样的问题，那就可以确定是网络的问题了

**Comment by JonouZ** [comment]
> 也可以再购买一个大华一起测试下，如有也有一样的问题，那就可以确定是网络的问题了

奇怪的是，我们还有一款摄像头，小厂的，各项数据都挺正常的

**Comment by 648540858** [comment]
小厂的那个，录像回放列表可以正常显示？

**Comment by xuanxuan-cc** [comment]
> 放列表可以正常显示？

嗯，都正常

**Comment by 648540858** [comment]
小厂的也抓个包给我看看

**Comment by JonouZ** [comment]
> 小厂的也抓个包给我看看
[Uploading Desktop.zip…]()

**Comment by JonouZ** [comment]
> 小厂的也抓个包给我看看

[Uploading 1.zip…]()

**Comment by JonouZ** [comment]
> > 小厂的也抓个包给我看看
> 
[Desktop.zip](https://github.com/648540858/wvp-GB28181-pro/files/12839644/Desktop.zip)

**Comment by JonouZ** [comment]
> 小厂的也抓个包给我看看

还有一种情况，每次华为摄像头重启之后，也是能看到录像文件，但是过一会就不行

**Comment by 648540858** [comment]
你试试出问题后在wvp的设备列表删除设备，然后重新开关下华为的国标配置，让设备重新注册下，然后重新查询录像列表，看看能不能好

**Comment by JonouZ** [comment]
> 你试试出问题后在wvp的设备列表删除设备，然后重新开关下华为的国标配置，让设备重新注册下，然后重新查询录像列表，看看能不能好

这个我们试过， 过一段时间还是出错

**Comment by 648540858** [comment]
当时是好的是吗，过一段时间还是出问题是吗

**Comment by JonouZ** [comment]
![企业微信截图_16967340873151](https://github.com/648540858/wvp-GB28181-pro/assets/56708898/0f26d4fc-9cb9-45e9-bf7b-0ac638cf621c)
这种情况，乱码的地方是随机的，只要出现在标签上，XML就会报错，这个有可能是网络问题么

**Comment by JonouZ** [comment]
> 当时是好的是吗，过一段时间还是出问题是吗

是的，

**Comment by 648540858** [comment]
目前考虑有两个可能的原因，一个是sip协议栈处理有问题，引入了错误的字符，一个是网络传输问题，数据到达协议栈时数据不全

**Comment by JonouZ** [comment]
> 目前考虑有两个可能的原因，一个是sip协议栈处理有问题，引入了错误的字符，一个是网络传输问题，数据到达协议栈时数据不全

第一种问题的情况下，我们这边需要怎么解决呀

**Comment by 648540858** [comment]
目前不好解决，我的手段复现不出问题来，所以还是需要我自己搞个设备来测试，浮现出问题来测试。但是局域网不出现，即使我买了设备也够呛

**Comment by 648540858** [comment]
还有一个思路，你们可以换一个云服务器厂商试试

**Comment by JonouZ** [comment]
> 目前不好解决，我的手段复现不出问题来，所以还是需要我自己搞个设备来测试，浮现出问题来测试。但是局域网不出现，即使我买了设备也够呛

和zlmediakit 有关系么

**Comment by 648540858** [comment]
没有，你不启动zlm也可以查询录像列表

**Comment by JonouZ** [comment]
> 没有，你不启动zlm也可以查询录像列表

明白了，估计暂时也复现不了

**Comment by JonouZ** [comment]
> 还有一个思路，你们可以换一个云服务器厂商试试
我们试试，还有一个问题，那个小厂摄像头的包，你看了么。 和华为的有啥不一样的

**Comment by 648540858** [comment]
还没看，主要是看看换行符有什么区别没

**Comment by JonouZ** [comment]
> 还没看，主要是看看换行符有什么区别没

OK

**Comment by JonouZ** [comment]
> > 还没看，主要是看看换行符有什么区别没
> 
> OK

[Desktop.zip](https://github.com/648540858/wvp-GB28181-pro/files/12839752/Desktop.zip)
这是最新的抓包，有时间你看一下

**Comment by 648540858** [comment]
确实有一些不一样，华为是使用\n, 小厂\r\n,这个目前是都兼容的，理论上是没有问题的，你先测试下不同云服务器是不是有不同的表现吧

**Comment by JonouZ** [comment]
> 确实有一些不一样，华为是使用\n, 小厂\r\n,这个目前是都兼容的，理论上是没有问题的，你先测试下不同云服务器是不是有不同的表现吧

好的，我先试试

**Comment by xuanxuan-cc** [comment]
我想问一下，就是摄像头首次注入到wvp平台就能正常查看录像视频文件，但是多次请求之后就会提示xml解析异常，可能是网络的原因导致的吗？

**Comment by xuanxuan-cc** [comment]
首次注册华为设备，国标平台调用摄像头录像文件都是正常的，多次调用不同的通道就会报xml解析异常，xml解析异常比较随机...

**Comment by xuanxuan-cc** [comment]
> 确实有一些不一样，华为是使用\n, 小厂\r\n,这个目前是都兼容的，理论上是没有问题的，你先测试下不同云服务器是不是有不同的表现吧

华为摄像头，刚接入国标平台，调取的录像文件都是正常的；就是多次请求查看录像、或者过一段时间请求录像文件，wvp后台就会报xml解析异常；很奇怪，为什么刚接入设备就正常呢？会不会这是一个突破口，考虑哪个解决方案比较好呢？

**Comment by xuanxuan-cc** [comment]
> 确实有一些不一样，华为是使用\n, 小厂\r\n,这个目前是都兼容的，理论上是没有问题的，你先测试下不同云服务器是不是有不同的表现吧

wvp拉取摄像头录像的时候，有规范摄像头返回的xml内容吗？我观察了小厂的摄像头，它无论有多少条录像，都是两个录像文件一个xml返回的；而华为的是很多路线文件都放入一个xml对象中返回。

**Comment by xuanxuan-cc** [comment]
> 确实有一些不一样，华为是使用\n, 小厂\r\n,这个目前是都兼容的，理论上是没有问题的，你先测试下不同云服务器是不是有不同的表现吧

另外，我还想问一下，wvp查看的摄像头录像条数有限制吗？比如，当摄像头返回超过30个录像文件的话，wvp不能正常查看之类的...

**Comment by linkewei0580** [comment]
直接tcpdump 抓包看看呢？
