### ISSUE TITLE
录像回放下载，支持进度条拖拽

### ISSUE THREAD

**Issue by 1216955142** [648540858/wvp-GB28181-pro#109]
求，可以扩展，在录像播放旁边，加一个录像下载功能，提供下载api接口与在线下载，录像回放支持进度条拖拽[https://images.gitee.com/uploads/images/2021/0619/181305_4e950239_1974955.jpeg](url)

**Comment by aGVsZWk** [comment]
哈哈，我也要这个

**Comment by 1216955142** [comment]
成功了，求大佬开源，666

**Comment by microsofter** [comment]
刚接触WVP，我这也有录像回放拖动和录像视频下载的需求，正在研究，后期多交流啊，期待上面两位大佬的作品！

**Comment by microsofter** [comment]
> 哈哈，我也要这个，进度条拖拽已经做出来了，录像下载正在搞

大佬开源了吗？

**Comment by 648540858** [comment]
录像回放已经支持拖拽控制了
