### ISSUE TITLE
最新版的接口需要怎么鉴权

### ISSUE THREAD

**Issue by fireicesion** [648540858/wvp-GB28181-pro#1091]
以前通过/api/user/login登录后，就可以正常调用其他接口
今天升级后通过/api/user/login登录后，调用其他接口返回
{
	"code": 401,
	"msg": "请登录后重新请求"
}

我看登录成功后有个accessToken返回值，调用接口时需要把这个附上吗？接口文档中也没提

**Comment by 648540858** [comment]
后续的请求需要添加请求头 'access-token'或者放在参数里

**Comment by paulguozy** [comment]
> 以前通过/api/user/login登录后，就可以正常调用其他接口 今天升级后通过/api/user/login登录后，调用其他接口返回 { "code": 401, "msg": "请登录后重新请求" }
> 
> 我看登录成功后有个accessToken返回值，调用接口时需要把这个附上吗？接口文档中也没提

我也遇到了同样的问题，但是我没看到有accessToken的返回值，请问您用的什么版本
