### ISSUE TITLE
技术咨询 分屏监控判断有无子设备根据id长度来 是否合理

### ISSUE THREAD

**Issue by PittYao** [648540858/wvp-GB28181-pro#1092]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
当添加NVR设备时，channelID为tree接口的id，通道号如下有D1,D2以此类推，前端根据id长度小于10来判断是否有子设备，当是通道号时所以点击系节点是查询下一层，不能触发播放，是小于10因为规范吗
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/26101917/0c634438-f42e-4092-b27c-c596522ea386)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/26101917/13b01427-a538-4eea-baed-40078667ebae)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/26101917/6c6be050-5385-4d24-9d8b-9616dcb8ca91)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
不合理，国标有字段判断是否有子设备的
