### ISSUE TITLE
在局域网环境下wvp与zlm搭建成功，但是摄像头在nat中播放视频超时，请问如何进行nat穿透

### ISSUE THREAD

**Issue by jinjie412** [648540858/wvp-GB28181-pro#1099]
摄像头在nat下，wvp服务器无法向摄像头发送推流指令，请教如何进行nat穿透

**Comment by lunasaw** [comment]
https://zhuanlan.zhihu.com/p/40816201 考虑udp打洞，GB28181点播机制设计

**Comment by jinjie412** [comment]
> 摄像头在nat下不影响啊，摄像头能向wvp推流就行

wvp什么显示摄像头注册成功了，但是在通道里面播放的时候，超时。摄像头是通过联通物联网卡上网的

**Comment by mengxing2017** [comment]
那你就用网线或者手机卡试一下咯，另外30000-30500/udp是否放通了

**Comment by jinjie412** [comment]
30000-30500/tcp 30000-30500/udp  都开通了

![35d34fb6ce4d68bacc4d429e8df2f59](https://github.com/648540858/wvp-GB28181-pro/assets/17948113/206d47b8-9fe6-43f0-b478-90e9f25a9d3a)

**Comment by lunasaw** [comment]
> 30000-30500/tcp 30000-30500/udp 都开通了
> 
> ![35d34fb6ce4d68bacc4d429e8df2f59](https://user-images.githubusercontent.com/17948113/274209758-206d47b8-9fe6-43f0-b478-90e9f25a9d3a.png)

播放超时看下流媒体日志有没有媒体注册相关的，没有就是推流没上去，再抓包看下设备收没有收到invite请求

**Comment by jinjie412** [comment]
> > 30000-30500/tcp 30000-30500/udp 都开通了
> > ![35d34fb6ce4d68bacc4d429e8df2f59](https://user-images.githubusercontent.com/17948113/274209758-206d47b8-9fe6-43f0-b478-90e9f25a9d3a.png)
> 
> 播放超时看下流媒体日志有没有媒体注册相关的，没有就是推流没上去，再抓包看下设备收没有收到invite请求

经过测试，摄像头 同样网络环境向其他搭建好的sip服务器可以正常播放，应该是我哪里设置不对，但是我搭建的wvp在局域网可以正常播放，暂时没找到问题在哪里。

**Comment by mengxing2017** [comment]
sdp-ip 摄像头是否可访问

**Comment by jinjie412** [comment]
> sdp-ip 摄像头是否可访问

摄像头可以在wvp注册成功，但是在通道里面播放就取流超时；你说的sdp-ip不是太明白

**Comment by mengxing2017** [comment]
wvp的配置文件有 sdp-ip、stream-ip这些配置项

**Comment by jinjie412** [comment]
> wvp的配置文件有 sdp-ip、stream-ip这些配置项

spring:
  # 设置接口超时时间
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  # [可选]上传文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: 127.0.0.1
    # [必须修改] 端口号
    port: 6379
    # [可选] 数据库 DB
    database: 7
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password:
    # [可选] 超时时间
    timeout: 10000
    # mysql数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.130:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: root
    password: 12345678
    hikari:
      connection-timeout: 20000             # 是客户端等待连接池连接的最大毫秒数
      initialSize: 10                       # 连接池初始化连接数
      maximum-pool-size: 200                # 连接池最大连接数
      minimum-idle: 5                       # 连接池最小空闲连接数
      idle-timeout: 300000                  # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      max-lifetime: 1200000                 # 是池中连接关闭后的最长生命周期（以毫秒为单位)
#[可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
  port: 18080
  # [可选] HTTPS配置， 默认不开启
  ssl:
    # [可选] 是否开启HTTPS访问
    enabled: false
    # [可选] 证书文件路径，放置在resource/目录下即可，修改xxx为文件名
    key-store: classpath:test.monitor.89iot.cn.jks
    # [可选] 证书密码
    key-store-password: gpf64qmw
    # [可选] 证书类型， 默认为jks，根据实际修改
    key-store-type: JKS

# 作为28181服务器的配置
sip:
  # [必须修改] 本机的IP，对应你的网卡，监听什么ip就是使用什么网卡，
  # 如果要监听多张网卡，可以使用逗号分隔多个IP， 例如： 192.168.1.4,10.0.0.4
  # 如果不明白，就使用0.0.0.0，大部分情况都是可以的
  # 请不要使用127.0.0.1，任何包括localhost在内的域名都是不可以的。
  ip: 0.0.0.0
  # [可选] 28181服务监听的端口
  port: 5060
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  # [可选]
  domain: 1000000000
  # [可选]
  id: 10000000002000000001
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  password: 123456
  # 是否存储alarm信息
  alarm: true

#zlm 默认服务器配置
media:
  id: FQ3TF8yT83wh5Wvz
  # [必须修改] zlm服务器的内网IP
  ip: 192.168.1.17
  # [必须修改] zlm服务器的http.port
  http-port: 6080
  # [可选] 返回流地址时的ip，置空使用 media.ip
  stream-ip:
  # [可选] wvp在国标信令中使用的ip，此ip为摄像机可以访问到的ip， 置空使用 media.ip
  sdp-ip: 
  # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip
  hook-ip: 
  # [可选] zlm服务器的http.sslport, 置空使用zlm配置文件配置
  http-ssl-port: 443
  # [可选] zlm服务器的hook.admin_params=secret
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
  # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
  rtp:
    # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
    enable: true
    # [可选] 在此范围内选择端口用于媒体流传输, 必须提前在zlm上配置该属性，不然自动配置此属性可能不成功
    port-range: 30000,30500 # 端口范围
    # [可选] 国标级联在此范围内选择端口发送媒体流,
    send-port-range: 30000,30500 # 端口范围
  # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
  record-assist-port: 18081
# [根据业务需求配置]
user-settings:
  # 点播/录像回放 等待超时时间,单位：毫秒
  play-timeout: 20000
  # [可选] 自动点播， 使用固定流地址进行播放时，如果未点播则自动进行点播, 需要rtp.enable=true
  auto-apply-play: true
  # 设备/通道状态变化时发送消息
  device-status-notify: true
  # 跨域配置，配置你访问前端页面的地址即可， 可以配置多个
  allowed-origins:
    - http://localhost:8080
    - http://127.0.0.1:8080
# [可选] 日志配置, 一般不需要改
logging:
  config: classpath:logback-spring-local.xml

**Comment by jinjie412** [comment]
> wvp的配置文件有 sdp-ip、stream-ip这些配置项



`
spring:
  # 设置接口超时时间
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  # [可选]上传文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: 127.0.0.1
    # [必须修改] 端口号
    port: 6379
    # [可选] 数据库 DB
    database: 7
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password:
    # [可选] 超时时间
    timeout: 10000
    # mysql数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.130:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: root
    password: 12345678
    hikari:
      connection-timeout: 20000             # 是客户端等待连接池连接的最大毫秒数
      initialSize: 10                       # 连接池初始化连接数
      maximum-pool-size: 200                # 连接池最大连接数
      minimum-idle: 5                       # 连接池最小空闲连接数
      idle-timeout: 300000                  # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      max-lifetime: 1200000                 # 是池中连接关闭后的最长生命周期（以毫秒为单位)
#[可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
  port: 18080
  # [可选] HTTPS配置， 默认不开启
  ssl:
    # [可选] 是否开启HTTPS访问
    enabled: false
    # [可选] 证书文件路径，放置在resource/目录下即可，修改xxx为文件名
    key-store: classpath:test.monitor.89iot.cn.jks
    # [可选] 证书密码
    key-store-password: gpf64qmw
    # [可选] 证书类型， 默认为jks，根据实际修改
    key-store-type: JKS

# 作为28181服务器的配置
sip:
  # [必须修改] 本机的IP，对应你的网卡，监听什么ip就是使用什么网卡，
  # 如果要监听多张网卡，可以使用逗号分隔多个IP， 例如： 192.168.1.4,10.0.0.4
  # 如果不明白，就使用0.0.0.0，大部分情况都是可以的
  # 请不要使用127.0.0.1，任何包括localhost在内的域名都是不可以的。
  ip: 0.0.0.0
  # [可选] 28181服务监听的端口
  port: 5060
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  # [可选]
  domain: 1000000000
  # [可选]
  id: 10000000002000000001
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  password: 123456
  # 是否存储alarm信息
  alarm: true

#zlm 默认服务器配置
media:
  id: FQ3TF8yT83wh5Wvz
  # [必须修改] zlm服务器的内网IP
  ip: 192.168.1.17
  # [必须修改] zlm服务器的http.port
  http-port: 6080
  # [可选] 返回流地址时的ip，置空使用 media.ip
  stream-ip:
  # [可选] wvp在国标信令中使用的ip，此ip为摄像机可以访问到的ip， 置空使用 media.ip
  sdp-ip: 
  # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip
  hook-ip: 
  # [可选] zlm服务器的http.sslport, 置空使用zlm配置文件配置
  http-ssl-port: 443
  # [可选] zlm服务器的hook.admin_params=secret
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
  # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
  rtp:
    # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
    enable: true
    # [可选] 在此范围内选择端口用于媒体流传输, 必须提前在zlm上配置该属性，不然自动配置此属性可能不成功
    port-range: 30000,30500 # 端口范围
    # [可选] 国标级联在此范围内选择端口发送媒体流,
    send-port-range: 30000,30500 # 端口范围
  # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
  record-assist-port: 18081
# [根据业务需求配置]
user-settings:
  # 点播/录像回放 等待超时时间,单位：毫秒
  play-timeout: 20000
  # [可选] 自动点播， 使用固定流地址进行播放时，如果未点播则自动进行点播, 需要rtp.enable=true
  auto-apply-play: true
  # 设备/通道状态变化时发送消息
  device-status-notify: true
  # 跨域配置，配置你访问前端页面的地址即可， 可以配置多个
  allowed-origins:
    - http://localhost:8080
    - http://127.0.0.1:8080
# [可选] 日志配置, 一般不需要改
logging:
  config: classpath:logback-spring-local.xml


`

**Comment by jinjie412** [comment]
> wvp的配置文件有 sdp-ip、stream-ip这些配置项

spring:
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    database: 7
    password:
    timeout: 10000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.130:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: root
    password: 12345678
    hikari:
      connection-timeout: 20000             # 是客户端等待连接池连接的最大毫秒数
      initialSize: 10                       # 连接池初始化连接数
      maximum-pool-size: 200                # 连接池最大连接数
      minimum-idle: 5                       # 连接池最小空闲连接数
      idle-timeout: 300000                  # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      max-lifetime: 1200000                 # 是池中连接关闭后的最长生命周期（以毫秒为单位)
server:
  port: 18080
  ssl:
    enabled: false
    key-store: classpath:test.monitor.89iot.cn.jks
    key-store-password: gpf64qmw
    key-store-type: JKS
sip:
  ip: 0.0.0.0
  port: 5060
  domain: 1000000000
  id: 10000000002000000001
  password: 123456
  alarm: true
media:
  id: FQ3TF8yT83wh5Wvz
  ip: 192.168.1.17
  http-port: 6080
  stream-ip:
  sdp-ip: 
  hook-ip: 
  http-ssl-port: 443
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
  rtp:
    enable: true
    port-range: 30000,30500 # 端口范围
    send-port-range: 30000,30500 # 端口范围
  record-assist-port: 18081
user-settings:
  play-timeout: 20000
  auto-apply-play: true
  device-status-notify: true
  allowed-origins:
    - http://localhost:8080
    - http://127.0.0.1:8080
logging:
  config: classpath:logback-spring-local.xml

**Comment by jinjie412** [comment]
spring:
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    database: 7
    password:
    timeout: 10000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.130:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: root
    password: 12345678
    hikari:
      connection-timeout: 20000             # 是客户端等待连接池连接的最大毫秒数
      initialSize: 10                       # 连接池初始化连接数
      maximum-pool-size: 200                # 连接池最大连接数
      minimum-idle: 5                       # 连接池最小空闲连接数
      idle-timeout: 300000                  # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      max-lifetime: 1200000                 # 是池中连接关闭后的最长生命周期（以毫秒为单位)
server:
  port: 18080
  ssl:
    enabled: false
    key-store: classpath:test.monitor.89iot.cn.jks
    key-store-password: gpf64qmw
    key-store-type: JKS
sip:
  ip: 0.0.0.0
  port: 5060
  domain: 1000000000
  id: 10000000002000000001
  password: 123456
  alarm: true
media:
  id: FQ3TF8yT83wh5Wvz
  ip: 192.168.1.17
  http-port: 6080
  stream-ip:
  sdp-ip: 
  hook-ip: 
  http-ssl-port: 443
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
  rtp:
    enable: true
    port-range: 30000,30500 # 端口范围
    send-port-range: 30000,30500 # 端口范围
  record-assist-port: 18081
user-settings:
  play-timeout: 20000
  auto-apply-play: true
  device-status-notify: true
  allowed-origins:
    - http://localhost:8080
    - http://127.0.0.1:8080
logging:
  config: classpath:logback-spring-local.xml

**Comment by jinjie412** [comment]
spring:
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    database: 7
    password:
    timeout: 10000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.130:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: root
    password: 12345678
    hikari:
      connection-timeout: 20000             # 是客户端等待连接池连接的最大毫秒数
      initialSize: 10                       # 连接池初始化连接数
      maximum-pool-size: 200                # 连接池最大连接数
      minimum-idle: 5                       # 连接池最小空闲连接数
      idle-timeout: 300000                  # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      max-lifetime: 1200000                 # 是池中连接关闭后的最长生命周期（以毫秒为单位)
server:
  port: 18080
  ssl:
    enabled: false
    key-store: classpath:test.monitor.89iot.cn.jks
    key-store-password: gpf64qmw
    key-store-type: JKS
sip:
  ip: 0.0.0.0
  port: 5060
  domain: 1000000000
  id: 10000000002000000001
  password: 123456
  alarm: true
media:
  id: FQ3TF8yT83wh5Wvz
  ip: 192.168.1.17
  http-port: 6080
  stream-ip:
  sdp-ip: 
  hook-ip: 
  http-ssl-port: 443
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
  rtp:
    enable: true
    port-range: 30000,30500 # 端口范围
    send-port-range: 30000,30500 # 端口范围
  record-assist-port: 18081
user-settings:
  play-timeout: 20000
  auto-apply-play: true
  device-status-notify: true
  allowed-origins:
    - http://localhost:8080
    - http://127.0.0.1:8080
logging:
  config: classpath:logback-spring-local.xml

**Comment by jinjie412** [comment]
> wvp的配置文件有 sdp-ip、stream-ip这些配置项

spring:
--mvc:
----async:
------request-timeout 20000
--thymeleaf:
----cache false
--servlet:
----multipart:
------max-file-size 10MB
------max-request-size 100MB
--redis:
----host 127.0.0.1
----port 6379
----database 7
----password:
----timeout 10000
--datasource:
----type com.zaxxer.hikari.HikariDataSource
----driver-class-name com.mysql.cj.jdbc.Driver
----url jdbc:mysql://192.168.1.130:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
----username root
----password 12345678
----hikari:
------connection-timeout 20000-------------#-是客户端等待连接池连接的最大毫秒数
------initialSize 10-----------------------#-连接池初始化连接数
------maximum-pool-size 200----------------#-连接池最大连接数
------minimum-idle 5-----------------------#-连接池最小空闲连接数
------idle-timeout 300000------------------#-允许连接在连接池中空闲的最长时间（以毫秒为单位）
------max-lifetime 1200000-----------------#-是池中连接关闭后的最长生命周期（以毫秒为单位)
server:
--port 18080
--ssl:
----enabled false
----key-store classpath:test.monitor.89iot.cn.jks
----key-store-password gpf64qmw
----key-store-type JKS
sip:
--ip 0.0.0.0
--port 5060
--domain 1000000000
--id 10000000002000000001
--password 123456
--alarm true
media:
--id FQ3TF8yT83wh5Wvz
--ip 192.168.1.17
--http-port 6080
--stream-ip:
--sdp-ip 
--hook-ip 
--http-ssl-port 443
--secret 035c73f7-bb6b-4889-a715-d9eb2d1925cc
--rtp:
----enable true
----port-range 30000,30500-#-端口范围
----send-port-range 30000,30500-#-端口范围
--record-assist-port 18081
user-settings:
--play-timeout 20000
--auto-apply-play true
--device-status-notify true
--allowed-origins:
------http://localhost:8080
------http://127.0.0.1:8080
logging:
--config classpath:logback-spring-local.xml

**Comment by lunasaw** [comment]
> > sdp-ip 摄像头是否可访问
> 
> 摄像头可以在wvp注册成功，但是在通道里面播放就取流超时；你说的sdp-ip不是太明白

收流超时 检查下流媒体的日志，有没有流注册上来。没有的话检查下端口是否正常。端口正常先测试ffmpeg主动推流能否播放

**Comment by mengxing2017** [comment]
你的公网ip明显访问不了192.168.1.17这个ip,老老实实把sdp-ip填了

**Comment by jinjie412** [comment]
> 你的公网ip明显访问不了192.168.1.17这个ip,老老实实把sdp-ip填了

就是你说的这个sdp-ip设置就好了，我偷懒了，膜拜大佬
