### ISSUE TITLE
技术咨询 使用录像下载接口下载录像的时候，下载到的都是12秒一个的视频切片，有办法直接下载一整个视频吗？

### ISSUE THREAD

**Issue by wangguodong8602** [648540858/wvp-GB28181-pro#1103]
**内容描述:**
使用录像下载接口下载录像的时候，下载到的都是12秒一个的视频切片，有办法直接下载一整个视频吗？

**Comment by 648540858** [comment]
下载完成后自动合并

**Comment by wangguodong8602** [comment]
如何自动合并呢，我没发现有自动合并这个功能啊

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月16日 18:08 |
| 收件人 | 648540858/wvp-GB28181-pro ***@***.***> |
| 抄送人 | wangguodong8602 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [648540858/wvp-GB28181-pro] 技术咨询 使用录像下载接口下载录像的时候，下载到的都是12秒一个的视频切片，有办法直接下载一整个视频吗？ (Issue #1103) |

Closed #1103 as completed.

**Comment by 648540858** [comment]
会调用assist服务合并，并在前端可以点击下载
