### ISSUE TITLE
BUG-下级WVP添加另一个WVP服务作为国标上级，当上级WVP服务关闭后重启下级WVP服务时无法正常启动180端口

### ISSUE THREAD

**Issue by aiwatcher** [648540858/wvp-GB28181-pro#1104]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 无屏蔽
 - 4. 是否是公网部署  否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试 
 - 启动上级wvp并监听5060端口，重启下级wvp正常启动
 - 8. 代码更新时间
 - github最新代码 v2.6.8

**描述错误**
在主机A（192.168.2.55）的WVP服务界面-国标级联添加上级平台，上级平台是另一台主机B（192.168.2.53）运行的同版本wvp服务，可以正常添加并完成级联，但是当关闭主机B后重启主机A的wvp服务时启动失败未监听HTTP 180端口，尝试多次。这时开启主机B并启动该主机上的WVP服务后再次尝试启动主机A的WVP服务时能够正常启动并监听HTTP 180端口。

**如何复现**
启动主机A时反复尝试启动或关闭主机B的WVP服务可稳定复现

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```
[wvp.20231011.log](https://github.com/648540858/wvp-GB28181-pro/files/12864396/wvp.20231011.log)

**Comment by aiwatcher** [comment]
补充：仅当添加上级平台配置通信协议设置为TCP时才出现此问题

**Comment by 648540858** [comment]
新代码已解决这个问题
