### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by lr897219186** [648540858/wvp-GB28181-pro#1106]
**内容描述:**
请问wvp目前是只支持作为下级平台级联至其它上级平台，自身不支持作为上级平台接受下级wvp或是其他下级平台的级联吗？

**Comment by aiwatcher** [comment]
实测作为上下级都可以

**Comment by lr897219186** [comment]
> 实测作为上下级都可以

可是我看这边只有级联上级平台，没有自身作为上级平台的入口诶
![image](https://github.com/648540858/wvp-GB28181-pro/assets/67771256/005bf59f-dea7-4171-ae36-8d514463bdc5)

**Comment by lr897219186** [comment]
> 实测作为上下级都可以

咦？可以吗？但我看这边只有上级平台的管理页面，没有下级平台的管理页面诶
![image](https://github.com/648540858/wvp-GB28181-pro/assets/67771256/b3acc51a-2b2b-4d4c-ac54-c583e9b8eb85)

**Comment by mengxing2017** [comment]
下级是由下级添加的，下级是爸爸，上级什么都不用操作

**Comment by lr897219186** [comment]
> 下级是由下级添加的，下级是爸爸，上级什么都不用操作

但是上级得需要点播下级平台的视频呀，就必须有个界面可以看到所有下级平台挂在的设备通道，但这个功能的话我貌似没看到有页面支持

**Comment by mengxing2017** [comment]
没注册上就看日志，下级信息填对了，国编设备里面自然后设备和通道

**Comment by lr897219186** [comment]
> 没注册上就看日志，下级信息填对了，国编设备里面自然后设备和通道

意思是说下级平台的设备也一并显示在国标设备里咯？我以为国标设备里只会显示本平台的设备，那我试下，谢谢指点！
