### ISSUE TITLE
技术咨询 录像保存路径被程序自动更改和星球是否支持开具发票

### ISSUE THREAD

**Issue by Kieyfr** [648540858/wvp-GB28181-pro#1109]
**环境信息:**

 - 1. 部署方式  zlm(docker)+wvp-pro-assist (docker)部署在centos服务器+ 编译wvp-pro 是编译部署在windows /
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康摄像头
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
开启wvp-pro后重启zlm(docker)会导致zlm的config.ini配置文件的保存录像路径被更改
星球是否支持开具发票

**截图** 
 
wvp-pro-assist配置
![wvp-pro-assist配置](https://github.com/648540858/wvp-GB28181-pro/assets/117817388/3447412a-3d94-41b0-9f34-031e19e76452)
wvp-pro-assist Dockerfile配置
![image](https://github.com/648540858/wvp-GB28181-pro/assets/117817388/be551334-5f5a-48f9-b1fd-73e5afa0cd75)
wvp-pro配置
![wvp-pro配置](https://github.com/648540858/wvp-GB28181-pro/assets/117817388/502b2b26-6011-444d-877b-99db54df452c)
zlm配置
![zlm配置](https://github.com/648540858/wvp-GB28181-pro/assets/117817388/a4920b9e-4ee6-426f-866f-0a6ee962c4a1)
上图的路径会自动更改
docker-compose编排文件
![image](https://github.com/648540858/wvp-GB28181-pro/assets/117817388/66288b49-6d9d-46c7-a190-76156d6e74ad)

如果进星球的话可以开具发票吗

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by Kieyfr** [comment]
我直接更改zlm的配置文件后在开着wvp的情况下重启zlm，配置就会变成以上地址，但是我没设置过这个配置

**Comment by lunasaw** [comment]
> 我直接更改zlm的配置文件后在开着wvp的情况下重启zlm，配置就会变成以上地址，但是我没设置过这个配置

assist的录像功能只是重命名了 zlm的录制文件，流程上是zlm先录制ok，然后回调服务assist会对这个文件重命名，在外部看来就是被移动了。

**Comment by Kieyfr** [comment]
但是我关闭assist后 zlm的录制位置也是会被更改，我想要将这个配置设定为对的地址，该怎么修改

**Comment by 648540858** [comment]
星球开发票直接在星球APP找星球客服就可以
