### ISSUE TITLE
关于单挂海康摄像枪报警事件推送

### ISSUE THREAD

**Issue by bigff-0527** [648540858/wvp-GB28181-pro#1111]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
用了海康单个摄像机，开启了移动侦测、区域入侵事件。wvp都查询不到报警事件记录，项目日志里也没有相关记录。打电话问过海康客服，回答我说 任何型号的设备都是主动上报报警给平台的，不管是国际还是其它。
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/58465932/9080abab-186d-4f0d-98be-af200bf60695)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
抓包，看看下级有没有推送过来，没推送就是下级配置问题

**Comment by bigff-0527** [comment]
> 抓包，看看下级有没有推送过来，没推送就是下级配置问题

我录像机能有报警数据。单个海康摄像机又没有。而且项目控制台有打印报警日志，但是数据库里没有这条记录啊
![image](https://github.com/648540858/wvp-GB28181-pro/assets/58465932/5fce62e0-116e-40fe-a2f1-e1dd53c29bdf)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/58465932/133e5f4d-79a8-4d61-95d6-49bdb4737b9e)

**Comment by 648540858** [comment]
看看是否开启了报警存储，默认报警不存的。数据很多。你最好自己实现分库分表和定时数据清理。

**Comment by bigff-0527** [comment]
> 看看是否开启了报警存储，默认报警不存的。数据很多。你最好自己实现分库分表和定时数据清理。
确实是没开启 配置文件sip 中的alarm。非常感谢
