### ISSUE TITLE
对于SIP请求部分，推荐封装请求包

### ISSUE THREAD

**Issue by lunasaw** [648540858/wvp-GB28181-pro#1113]
**项目的详细需求**
目前看wvp代码上下级交互大量使用了拼装xml构建请求，并且每个请求并没有特殊抽象，每次发起sip请求构建相当麻烦，并且代码冗余太多了，FromHear，ToHeader等等其他HeaderFactory直接可以抽象处理的。推荐基于sip的请求使用javax.xml注解的方式，使用java bean作为请求体，复写toString直接转成xml。并且使用将sip请求和spring 抽离，单测的时候也能用下
我这边写了一个基础库，sip请求响应封装完成。目前gb28181的实现还在完善，https://github.com/lunasaw/gb28181-proxy/ 希望后续能接入过来。 并且希望各位能一起讨论下，给点建议。
以下是简单的例子
只需要几行代码就可以发起一个注册请求。不需要重复构造sip的各种header
<img width="1287" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/52351139/fd9fc79f-454c-49da-a8da-9a0059c0987f">
其他见io.github.lunasw.gbproxy.client.test.cmd.ApplicationTest

特别是xml部分，现在拼接string的方式确实不太美妙。直接通过java对象toString的方式感觉优雅很多，可读性也高一些
<img width="1169" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/52351139/275aaa52-1220-4597-b503-94d396ff59ca">

**Comment by 648540858** [comment]
暂时不大算改，不是不能封装完善，写的很优美。而是如果封装了，就意味着灵活性降低，这样遇到不讲究的设备就很难去兼容了，比如你的封装了生成Message的方法，如果的有的设备需要特殊处理，改了机会影响所有的Message消息。最开始就是考虑的封装以及xml直接与java bean转换的方案。但是得不偿失。另外也会增加出错后的排查难度。   

如果有一天国标的设备足够规范，而我对国标足够了解到应付各种情况。那么我才会考虑封装起来。代码还是要为功能服务的。 

 目前sip协议栈用的jain sip。比较稳定和灵活。打不算更换了。谢谢。

**Comment by lunasaw** [comment]
> 暂时不大算改，不是不能封装完善，写的很优美。而是如果封装了，就意味着灵活性降低，这样遇到不讲究的设备就很难去兼容了，比如你的封装了生成Message的方法，如果的有的设备需要特殊处理，改了机会影响所有的Message消息。最开始就是考虑的封装以及xml直接与java bean转换的方案。但是得不偿失。另外也会增加出错后的排查难度。
> 
> 如果有一天国标的设备足够规范，而我对国标足够了解到应付各种情况。那么我才会考虑封装起来。代码还是要为功能服务的。
> 
> 目前sip协议栈用的jain sip。比较稳定和灵活。打不算更换了。谢谢。


那我这边可以基于你的项目自行替换再开源一版本吗

**Comment by 648540858** [comment]
可以呀，mit协议不限制这个的
