### ISSUE TITLE
技术咨询 多端口复用技术咨询

### ISSUE THREAD

**Issue by a24211317** [648540858/wvp-GB28181-pro#1114]
目前产品因防火墙问题不能开放大量端口，单端口模式感觉流卡顿严重，所以请问下技术上能不能实现多端口复用。
我们目前改了一版，但是存在串流问题，不清楚是不是ZLM不支持这么干

**Comment by 648540858** [comment]
暂时没有办法，wvp不支持多个端口复用

**Comment by a24211317** [comment]
请问zlm是否支持多端口复用呢，单端口没问题的话，多端口复用应该也是可以实现的。
不知道单端口是如何防止串流的，能帮忙解答下吗
