### ISSUE TITLE
【BUG】 下载较大国标录像文件失败

### ISSUE THREAD

**Issue by cangmu2007** [648540858/wvp-GB28181-pro#1115]
**环境信息:**

 - 1. 部署方式编译wvp-pro-gb28181+ zlm + wvp-pro-assist都是编译部署
 - 2. 部署环境 ubuntu 20.04
 - 3. 端口开放情况：内网，所有端口均开放使用
 - 4. 不开放公网部署
 - 5. 不使用使用https
 - 6. 海康NVR
 - 7. 你做过哪些尝试：尝试其他平台级联或者相机设备直连
 - 8. 代码更新时间：（2.6.9版本）

**描述错误**
尝试下载时长3小时左右国标录像文件，下载失败

**如何复现**
点击下载时长超过2小时的文件会有很大概率出现

**截图**  
![273531046-17db4165-4f87-49ea-8420-f386c33f1876](https://github.com/648540858/wvp-GB28181-pro/assets/8434048/fb6f2c8f-3bb5-46e3-9be7-cd3b018b99ce)

原因分析：
ZLM每隔10s左右会存储一个缓存视频文件，前端不断读取下载进度，当获取下载进度接口被调用时，assist会遍历缓存视频文件并通过ffmpeg获取文件视频长度计算下载进度，但是当文件数量达到一定程度时，遍历文件数量过多，导致遍历时间超过http超时时间，获取下载进度失败，从而前端判定异常stop下载
可以看到每次获取进度的时间都在变长
<img width="1264" alt="273533009-5a605ef0-c4e8-479b-82ed-5510542f64e0" src="https://github.com/648540858/wvp-GB28181-pro/assets/8434048/09979bb4-4f50-47c5-a97c-5a816befaf09">

获取下载进度时遍历文件（wvp-pro-assist源码）
![273533136-766d8749-01a5-42f9-a863-e81efc4094c3](https://github.com/648540858/wvp-GB28181-pro/assets/8434048/101f9008-bad1-4f90-8f2b-707afef1adef)

**Comment by 648540858** [comment]
正在重构下载方案，等重构完你再测测

**Comment by 648540858** [comment]
可以测试了，有问题你再打开

**Comment by cangmu2007** [comment]
> 可以测试了，有问题你再打开

好的，请问是使用wvp-28181-record分支测试还是直接用默认分支？
