### ISSUE TITLE
技术咨询-关于与zlm开启https

### ISSUE THREAD

**Issue by bigff-0527** [648540858/wvp-GB28181-pro#1117]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ... centos
 - 3. 端口开放情况 已开放
 - 4. 是否是公网部署 是
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
wvp配置文件已配置jks证书，浏览器也能用https访问wvp，但是点播会显示收流超时，zlm也配置了pem。以下是zlm截图
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/58465932/15336394-7a6e-4498-9dc0-b9e2207b7d0a)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/58465932/4a99881d-e536-421e-983e-328dcb5928ba)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by xiaoQQya** [comment]
看日志是 zlm 推流鉴权没有通过，禁止 RTP 推流。

wvp 开启了 https，zlm 配置文件里的 hook 接口要配置 https 的，从日志里面看你配置的是 http。

![image](https://github.com/648540858/wvp-GB28181-pro/assets/46475319/ae212bce-6ff4-48a7-b152-d45e66740de9)

**Comment by bigff-0527** [comment]
解决了，是与服务器 zlm配置的 https 端口没开放

**Comment by DingKun7** [comment]
能问下是怎么解决的吗

**Comment by bigff-0527** [comment]
> 能问下是怎么解决的吗

我是服务器端口没打开，比如：zlm的https是8084，我服务器没打开这个端口
