### ISSUE TITLE
[技术咨询] 国标级联通道号重复问题

### ISSUE THREAD

**Issue by xiaoQQya** [648540858/wvp-GB28181-pro#1118]
**环境信息:**

 - 1. 部署方式 docker
 - 2. 部署环境 docker
 - 3. 端口开放情况 开放外网端口
 - 4. 是否是公网部署 是
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台 大华、海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 git 12c4128

**内容描述:**

遇到问题：wvp 作为下级平台往上级平台级联时，本级平台两个不同设备下面存在着相同的通道号，推送通道里如果同时选中这两个通道，上级平台点播时只能看到通道号重复的最后一路视频。

思考建议：选择上级推送通道时能否自定义通道号。

**Comment by mengxing2017** [comment]
通道号重复是你们自己规划的问题

**Comment by xiaoQQya** [comment]
> 通道号重复是你们自己规划的问题

可是不同设备下面通道号有重复也是很正常的现象吧

**Comment by mengxing2017** [comment]
不正常，要规范来就不会出现重复的，出现重复的就是工作人员偷懒了

**Comment by mengxing2017** [comment]
前面的地区已经精确到县级了，后面还有六位自定义的数字，出现了重复，规划的人推卸不了责任

**Comment by xiaoQQya** [comment]
> 前面的地区已经精确到县级了，后面还有六位自定义的数字，出现了重复，规划的人推卸不了责任

您说的我明白，可能最早规划的人没有规划好，现在除了去修改设备通道号外，能否在 wvp 层面解决这个问题。

**Comment by mengxing2017** [comment]
在wvp层面解决这个问题可能性不大，即便在wvp解决了，那再级联一级呢？一样获取不到通道

**Comment by mengxing2017** [comment]
你可以看一下wvp的直播推流代码，那个可以自定义通道

**Comment by xiaoQQya** [comment]
> 你可以看一下wvp的直播推流代码，那个可以自定义通道

好的，谢谢
