### ISSUE TITLE
页面关闭时通知zlm拍快照的url改进

### ISSUE THREAD

**Issue by mingyuejingque** [648540858/wvp-GB28181-pro#112]
由于zlm config.ini里是用ffmpeg来拍快照， 但是如果观看h265流的时候 ffmpeg 不兼容 flv-h265 导致拍照失败。
看代码 PlayServiceImp.java  result.onCompletion 里用的是 flv 地址， 改成fmp4方式就能正常拍照了。

                        //String flvUrl = streamInfoForSuccess.getFlv();
                        // 请求截图
                        //zlmresTfulUtils.getSnap(flvUrl, 5, 1, path, fileName);
                        String mp4Url = streamInfoForSuccess.getFmp4();
                        zlmresTfulUtils.getSnap(mp4Url, 5, 1, path, fileName);

**Comment by 648540858** [comment]
好的

**Comment by 648540858** [comment]
e21abeea37342974790c02e85ddb94198456df61
