### ISSUE TITLE
[BUG]-设备达到一定数量，频繁的大面积掉线

### ISSUE THREAD

**Issue by aidelingyu** [648540858/wvp-GB28181-pro#1120]
**环境描述**
1、java原生启动
2、redis单机

**描述错误**
我们线上环境，设备数量达到700+时，差不多每半小时就会有200，300台设备离线，过段时间设备又上线。
通过对某一设备的抓包发现，过一段时间，心跳请求达到网卡时间和网卡响应该心跳的时间有几秒甚至几十秒的间隔，通过平台日志分析，平台收到心跳请求到平台处理心跳后在响应的时间间隔都是毫秒级。
使用top查看服务器资源，发现wvp占用了65%的cpu，有时甚至能达到90%
![image](https://github.com/648540858/wvp-GB28181-pro/assets/23529219/aea2bc35-a9e6-4a18-940d-49efee0bec7f)
使用top -Hp <pid>去查看线程，发现线程占用cpu最高的是lettcue的相关线程，怀疑跟redis操作有关。
接着查看redis的服务器资源，发现redis-server进程的cpu使用率达到100%左右。
然后，使用pref采集数据，发现占用cpu的操作也和lettuce相关，且还伴有加锁解锁。
![image](https://github.com/648540858/wvp-GB28181-pro/assets/23529219/fdb84f8c-02bf-4130-bf02-94279cd3dc51)
所有现象都证明了是redis的问题。因为掉线原因是两次心跳间隔时间超过了我们设置的100秒，所以平台认为设备下线了。
看心跳处理的逻辑。
发现在MessageRequestProcessor类的process方法中，调用了getSsrcTranscation方法，之后在从messageHandlerMap里面取出心跳的处理类KeepaliveNotifyMessageHandler在做处理。这个getSsrcTranscation方法中调用了redis的scan方法进行模糊搜索。
怀疑是因为这个调用导致大量心跳处理等待，随后注释了MessageRequestProcessor中的getSsrcTranscation调用，上线后观察了两天，设备没有在大规模下线了。

**如何复现**
上线大量摄像头

**结论**
心跳这里不能调用redis的scan方法。

**Comment by yaoxiaojian-liuxiaojun** [comment]
相关的scan操作key对应数量较少,所以这个结论需要再讨论一下.目前我们在22684设备数量的实践中未出现这个问题

**Comment by yaoxiaojian-liuxiaojun** [comment]
鉴于scan对应的key较少,结论需要再考虑一下 .我觉得应该检查redis没有释放连接的问题

**Comment by 648540858** [comment]
其实可以测试这里的scan查询花费了多长时间

**Comment by aidelingyu** [comment]
@yaoxiaojian-liuxiaojun 应该不是链接的问题，我把心跳那里的scan调用注释了，cpu使用率就下来了，观察了几天也没有再出现大面积掉线的问题了。

**Comment by aidelingyu** [comment]
@648540858 可以，有空了我在测一下scan的开销。从redis慢查询日志看，都记录的是scan查询。

**Comment by yaoxiaojian-liuxiaojun** [comment]
好的 ,有结果了可以回复一下吗  我对这里比较感兴趣

**Comment by saifreedom** [comment]
请问“设备数量达到700+时”是自己用虚拟摄像头还是真的用摄像头测试的，我想问问用什么软件可以做虚拟摄像头，能推荐下吗？

**Comment by aidelingyu** [comment]
@saifreedom 不是虚拟摄像头，都是真实的摄像头，是安装在用户家里的摄像头

**Comment by aidelingyu** [comment]
@yaoxiaojian-liuxiaojun 我认为应该就是MessageRequestProcessor 的process里面调用了redis的scan方法，去掉这个调用到现在已经两周了，都没出现大面积的频繁掉线。redis里大约有2万多个key，可能会导致scan相对较慢。

**Comment by lakersWin** [comment]
我的也是redis跟java的cpu都跑满了， 请问停掉之后对业务有什么影响吗。  我这边现在跑了7000多台

**Comment by aidelingyu** [comment]
@lakersWin 目前我这边对部分调用scan的地方做了改造的，没有让程序去扫描redis所有的key。scan就是对redis的所有key的一个模糊搜索，根据你们的业务，把这个模糊搜索改成精确匹配就行了
