### ISSUE TITLE
技术咨询-关于请求截图图片不显示

### ISSUE THREAD

**Issue by bigff-0527** [648540858/wvp-GB28181-pro#1124]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
请求截图API 返回的图片不可识别，后台快照也不显示了，之前是可以的。
并且服务器上的snap下图片都不能识别，下载到本地也是如此。
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/58465932/84799048-2c91-4238-b75b-19167eab54eb)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/58465932/afe80807-1fb6-430f-9f10-ff83a949efb8)

服务器截图
![image](https://github.com/648540858/wvp-GB28181-pro/assets/58465932/943fe5f8-9e6c-46d6-bf64-4815dce8b25d)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by keehub** [comment]
代码里的bug，老版本没问题

**Comment by 648540858** [comment]
你请求截图的时候点播了吗，点播之后才有截图

**Comment by bigff-0527** [comment]
解决了，是zlm的conf文件中 ffmpeg路径问题
