### ISSUE TITLE
部署wvp + assist + ZLMediaKit 进行7*24h不间断录像，录制的间隔和遗漏问题

### ISSUE THREAD

**Issue by luhengyu1** [648540858/wvp-GB28181-pro#1126]
我是根据wvp的文档进行配置的，如下图不间断录制功能总体能起到效果
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/1766ba43-6221-4699-90d1-a56b6be51f1b)

但是发现一个奇怪的小问题，就是录制预期应该是像绿色方框中这样一小时保存一次，但是为什么会有时候出现红色方框中这种情况？即不满一小时就保存了录制视频，并且前后时间不一致，有一些时间遗漏了

![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/90476e9d-9ecf-4560-b6f6-5ca36a7d9fb2)

**Comment by 648540858** [comment]
可能是你的视频流不稳定，设备是通过局域网接入的吗，你开启自动点播了吗

**Comment by luhengyu1** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/54528622-2e88-4b95-978e-10f622b905fd)
这是我的配置文件，应该是已经开启了自动点播，是公司内网接入的。
视频流不稳定是指什么？

**Comment by luhengyu1** [comment]
> ![image](https://user-images.githubusercontent.com/87296715/278913942-54528622-2e88-4b95-978e-10f622b905fd.png) 这是我的配置文件，应该是已经开启了自动点播，是公司内网接入的。 视频流不稳定是指什么？



> 可能是你的视频流不稳定，设备是通过局域网接入的吗，你开启自动点播了吗
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/3f66f01d-dffd-47d4-9d43-11b588e1883b)
这是我的配置文件，应该是已经开启了自动点播，是公司内网接入的。
视频流不稳定是指什么？

**Comment by luhengyu1** [comment]
> 可能是你的视频流不稳定，设备是通过局域网接入的吗，你开启自动点播了吗
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/8fdd968c-2533-459a-95ed-da69f1968c0d)
这是我的配置文件，应该是已经开启了自动点播，是公司内网接入的。
视频流不稳定是指什么？

**Comment by 648540858** [comment]
就是视频流时断时续，你可以单独播放这个视频流试试

**Comment by luhengyu1** [comment]
> 就是视频流时断时续，你可以单独播放这个视频流试试

单独播放是连续流畅的，当然我也是肉眼观察，不可能很长时间一直盯着看，平时经常点播都没啥问题

**Comment by 648540858** [comment]
视频到zlm上就会被zlm保存到硬盘上，wvp并不处理相关的内容，遗漏的内容我觉得还是没有实际发送到zlm上，这个问题只能尝试长期监测，我没有更好的办法了

**Comment by Ancientwwy** [comment]
你可以自己写个定时任务，定时的去点播你要录制的但是因为意外设备停止推流的通道，用来解决视频因为意外中断了导致设备没有推流无法录制，作为7*24小时不间断录制的一种容错机制。
