### ISSUE TITLE
请添加 GB/T-28181-2016 设备目录的相关功能

### ISSUE THREAD

**Issue by YTed** [648540858/wvp-GB28181-pro#1127]
**项目的详细需求**

GB/T 28181-2016 相比 2011 版本添加了设备目录的功能，具体的规范在标准文档 9.5.3.1、A.2.1、和附录O中。

**这样的实现什么作用**

在一些 GB28181 平台的实现中，作为国标级练关联的上级平台，下级平台必须把设备、通道添加到虚拟组织目录中，该上级平台才能收到相关消息，望添加相关支持。

**Comment by 648540858** [comment]
没有这个计划，这只是一种验证机制。目前没有打算实现
