### ISSUE TITLE
添加拉流地址后无法启动播放

### ISSUE THREAD

**Issue by 925008670** [648540858/wvp-GB28181-pro#1129]
背景：
八月份拉的wvp代码添加拉流正常，能够正常播放，2023年10月24日更新代码

最新代码
1、添加拉流代理，提示启动失败，或点击播放无法获取播放地址

**Comment by mengxing2017** [comment]
这点信息，没人能帮你的，最基本的日志要提供

**Comment by 648540858** [comment]
不符合提问规范
