### ISSUE TITLE
技术咨询 设备告警只支持NVR 的吗，单设备接入收不到告警通知

### ISSUE THREAD

**Issue by WalkerPlus** [648540858/wvp-GB28181-pro#1130]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
设备告警只支持NVR 的吗，单设备接入收不到告警通知，接入nvr 后可以收到告警通知，只接入一个摄像头就接收不到事件，是我配置有问题吗，需要怎么配置

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/16448447/c0a2feec-68b7-449a-992e-8633665f9e12)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
下级的问题，抓包看上报情况，上级是被动的，下级有上报就是上级问题，没上报就是下级配置问题，单摄像头不上报，可能是你摄像头不支持gb上报报警

**Comment by WalkerPlus** [comment]
> 下级的问题，抓包看上报情况，上级是被动的，下级有上报就是上级问题，没上报就是下级配置问题，单摄像头不上报，可能是你摄像头不支持gb上报报警

抓包了，摄像头直接接入没有数据，通过nvr接入 就有数据数据过来，不清楚什么原因

**Comment by bigff-0527** [comment]
海康的是吗？我的好像这样，单个摄像枪不行，录像机就有报警信息

**Comment by bigff-0527** [comment]
我的解决了，是要去wvp平台上设置布防SetGuard才可以。

**Comment by WalkerPlus** [comment]
> 我的解决了，是要去wvp平台上设置布防SetGuard才可以。

是的，我后面设置布防也收到了 但是在nvr 一直设置失败，你那也是吗

**Comment by bigff-0527** [comment]
> > 我的解决了，是要去wvp平台上设置布防SetGuard才可以。
> 
> 是的，我后面设置布防也收到了 但是在nvr 一直设置失败，你那也是吗

录像机我都不用任何设置，也能推送喔。单个摄像机就要设置

**Comment by WalkerPlus** [comment]
> > > 我的解决了，是要去wvp平台上设置布防SetGuard才可以。
> > 
> > 
> > 是的，我后面设置布防也收到了 但是在nvr 一直设置失败，你那也是吗
> 
> 录像机我都不用任何设置，也能推送喔。单个摄像机就要设置

我也是，单相机设置有效果，录像机我想撤销布防都是失败的，没有效果

**Comment by linkewei0580** [comment]
> 我的解决了，是要去wvp平台上设置布防SetGuard才可以。

在哪里设置？

**Comment by WalkerPlus** [comment]
> > 我的解决了，是要去wvp平台上设置布防SetGuard才可以。
> 
> 在哪里设置？

device/control/guard/ 这个接口

**Comment by linkewei0580** [comment]
> > > 我的解决了，是要去wvp平台上设置布防SetGuard才可以。
> > 
> > 
> > 在哪里设置？
> 
> device/control/guard/ 这个接口

界面不提供操作吗？

**Comment by linkewei0580** [comment]
> > 我的解决了，是要去wvp平台上设置布防SetGuard才可以。
> 
> 在哪里设置？

我后台有这个日志，界面上没体现
[处理报警通知]待处理数量：1
2023-11-01 11:47:00.682 [wvp-1] INFO  c.g.i.v.g.t.e.r.i.m.n.c.AlarmNotifyMessageHandler:184 - [收到报警通知]内容：{"alarmDescription":"视频动检","alarmMethod":"5","alarmPriority":"1","alarmTime":"2023-11-01 11:47:00","alarmType":"2","channelId":"34020000001310000001","createTime":"2023-11-01 11:47:00","deviceId":"34020000001320000001","latitude":0.0,"longitude":0.0}

**Comment by 648540858** [comment]
说反了，不是报警设备只支持NVR，而是可能的设备不支持国标报警，wvp不区分设备类型，统一处理
