### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by jialiang-tan** [648540858/wvp-GB28181-pro#1131]
**环境信息:**

 - 1. 部署方式 : wvp-prp + zlm都是docker编译部署，zlm和assist是在一台docker容器中，wvp在独立的容器中
 - 2. 部署环境 : ubuntu2204 
 - 3. 端口开放情况 
     0.0.0.0:3000->3000/tcp, :::3000->3000/tcp, 0.0.0.0:5060->5060/tcp, 0.0.0.0:5060->5060/udp, :::5060->5060/tcp, :::5060->5060/udp, 
     0.0.0.0:21078->21078/tcp, :::21078->21078/tcp, 0.0.0.0:21078->21078/udp, :::21078->21078/udp
 - 4. 是否是公网部署 ：否
 - 5. 是否使用https: 否
 - 6. 方便的话提供下使用的设备品牌或平台：ffmpeg推流本地MP4文件，摄像头海康
 - 7. 你做过哪些尝试： 单独部署zlmediakit
 - 8. 代码更新时间：最新

**内容描述:**
将本地MP4文件（格式为H264，30帧）通过FFMPEG推流至服务器后，播放不流畅，感觉像掉帧的样子，但是单独部署zlm后，就没有这个问题，播放很流畅，我原本使用的是docker镜像站上的老版本，老版本也是能够正常播放的，所以不知道是不是我的使用姿势不太对
**截图**  
单独部署zlm的情况
https://github.com/648540858/wvp-GB28181-pro/assets/134464446/f7bd3f43-09b2-46a5-b6f6-4f771fe8df7f

部署了wvp的情况
https://github.com/648540858/wvp-GB28181-pro/assets/134464446/75f66b5c-33c4-4ada-91d6-141408c58b29
**抓包文件**

  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
wvp不会影响你的播放流畅程度

**Comment by 648540858** [comment]
还是直接编译最新的测试吧

**Comment by jialiang-tan** [comment]
找到原因了，zlm的github仓库中的config.ini文件不能直接使用的。是我的问题。
