### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by JQYXQ** [648540858/wvp-GB28181-pro#1133]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - wvp-prp + zlm都是编译部署
 - 2. 部署环境 windows / ubuntu/ centos ...
 - centos 8
 - 3. 端口开放情况
 - 全部开放
 - 4. 是否是公网部署 
 - 是
 - 5. 是否使用https
 - 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 海康
 - 7. 你做过哪些尝试
 - 关闭无人观看
 - 8. 代码更新时间
最新

**内容描述:**
接入设备成功后，有时候一点就能直接播放，有时候点击一直黑屏转圈，需要刷新再次点击播放才行，大佬您知道啥原因吗
**截图**  
![64e98c5ee774b0827ed36ef81cf7c69](https://github.com/648540858/wvp-GB28181-pro/assets/34978472/f4234e5e-854a-49e0-8fb3-c230240e00f1)
![5e78ca7ac50d614d7f5070aa8dc975f](https://github.com/648540858/wvp-GB28181-pro/assets/34978472/c655a001-1c3b-4c6e-ac6c-8e1771871923)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by JQYXQ** [comment]
> **环境信息:**
> 
> * 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
> * wvp-prp + zlm都是编译部署
> * 2. 部署环境 windows / ubuntu/ centos ...
> * centos 8
> * 3. 端口开放情况
> * 全部开放
> * 4. 是否是公网部署
> * 是
> * 5. 是否使用https
> * 否
> * 6. 方便的话提供下使用的设备品牌或平台
> * 海康
> * 7. 你做过哪些尝试
> * 关闭无人观看
> * 8. 代码更新时间
>      最新
> 
> **内容描述:** 接入设备成功后，有时候一点就能直接播放，有时候点击一直黑屏转圈，需要刷新再次点击播放才行，大佬您知道啥原因吗 **截图** ![64e98c5ee774b0827ed36ef81cf7c69](https://user-images.githubusercontent.com/34978472/278697246-f4234e5e-854a-49e0-8fb3-c230240e00f1.png) ![5e78ca7ac50d614d7f5070aa8dc975f](https://user-images.githubusercontent.com/34978472/278697247-c655a001-1c3b-4c6e-ac6c-8e1771871923.png)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/34978472/1d499b85-56f1-446e-a89a-66785a88782d)

> 
> **抓包文件**
> 
> **日志**
> 
> ```
> 日志内容放这里， 文件的话请直接上传
> ```

**Comment by mengxing2017** [comment]
降低码流和分辨率试试，是不是带宽不够

**Comment by aidelingyu** [comment]
抓包看一下播放请求流程有没有走完。我线上就遇到播放sip请求流程没有走完。

**Comment by JQYXQ** [comment]
大佬，那这个sip流程没走完的话怎么解决的呢

の&amp;nbsp;伴你ゞ余生＂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月29日(星期天) 晚上9:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro] 技术咨询 (Issue #1133)





 
抓包看一下播放请求流程有没有走完。我线上就遇到播放sip请求流程没有走完。

**Comment by aidelingyu** [comment]
@JQYXQ 如果抓包发现sip流程没有走完，看一下是设备没有响应 还是 wvp没有响应。

**Comment by yaoxiaojian-liuxiaojun** [comment]
要么设备有问题要么网络有问题

**Comment by 648540858** [comment]
配置下stream-ip和sdp-ip为公网ip

**Comment by 648540858** [comment]
类似点播时收流超时的问题很多，我先关了你在issue里搜索下

**Comment by mengxing2017** [comment]
不能，这个需要2022版国标支持

**Comment by JQYXQ** [comment]
> 不能，这个需要2022版国标支持

奥奥，那摄像头支持的话，wvp这边您知道支持不，我只找到了以下的代码，但是是被注释掉了。放开就可以吗？        
// f字段:f= v/编码格式/分辨率/帧率/码率类型/码率大小a/编码格式/码率大小/采样率
//			content.append("f=v/2/5/25/1/4000a/1/8/1" + "\r\n"); // 未发现支持此特性的设备
