### ISSUE TITLE
技术咨询: 麻烦大佬们给我看看什么问题行吗？我是按照wiki这样去推的，还是会报错：

### ISSUE THREAD

**Issue by NSBSS** [648540858/wvp-GB28181-pro#1134]
ffmpeg推流退不上去，麻烦大佬们给我看看什么问题行吗？我是按照wiki这样去推的，还是会报错：
--------报错信息:  
[rtsp @ 0x7fa5729060c0] method ANNOUNCE failed: 401 Unauthorized
[out#0/rtsp @ 0x7fa572906000] Could not write header (incorrect codec parameters ?): Server returned 401 Unauthorized (authorization failed)
Error while filtering: Server returned 401 Unauthorized (authorization failed)
[out#0/rtsp @ 0x7fa572906000] Nothing was written into output file, because at least one of its streams received no packets.
------------------

用了一下两个推流方式都不行，一样报错401：
1.   /ffmpeg -re -i "/Users/sl/Downloads/test/1.mp4" -vcodec h264 -acodec aac -f rtsp -rtsp_transport tcp "rtsp://admin:admin@127.0.0.1/live/345?sign=416b35390ddad33f83944f4468b75ded"
2.   ./ffmpeg -re -i "/Users/sl/Downloads/test/1.mp4" -vcodec h264 -acodec aac -f rtsp -rtsp_transport tcp "rtsp://127.0.0.1/live/345?sign=416b35390ddad33f83944f4468b75ded"*

**Comment by aidelingyu** [comment]
确认下 sign是否和zlm中配置的相同

**Comment by NSBSS** [comment]
> 确认下 sign是否和zlm中配置的相同

一样的，我现在改成zlm跟wvp部署在同一台服务器就行了
