### ISSUE TITLE
开源版本功能上支持点播，云台控制，国标级联点播，自动点播吗？

### ISSUE THREAD

**Issue by linkewei0580** [648540858/wvp-GB28181-pro#1135]
ONVIF设备的接入，支持点播，云台控制，国标级联点播，自动点播。在[知识星球](https://t.zsxq.com/10WAnH2MP)放了试用安装包以及使用教程，没有使用时间限制，需要源码可以星球私信我或者邮箱联系。
```

**Comment by 648540858** [comment]
支持

**Comment by xiayongkang111** [comment]
@linkewei0580 如何联系您 我想要自动点播的

**Comment by linkewei0580** [comment]
> @linkewei0580 如何联系您 我想要自动点播的

什么是自动点播？
