### ISSUE TITLE
内网穿透场景，公网wvp服务器重启后，无法向前端发送推流指令

### ISSUE THREAD

**Issue by penghd** [648540858/wvp-GB28181-pro#114]
wvp服务器部署在公网，海康nvr在内网，先启动wvp，海康配置28181接入(前端只支持udp方式)后，一切正常
当wvp服务器关闭后，隔几分钟重启，前端nvr可以正常注册，wvp平台也能正常看到设备和通道，但无法播放。
看日志向前端发送ACK后无发应，ZLM服务器日志能看到发布的rtp接收端口，但无反应。
前端nvr如果不修改sip本地端口号，则重启也不能播放，前端只要更改本地sip端口号如改成5062，则就正常了。
忘了在哪个日志看到过报错（Java Pipe Broken），估计问题是前端防火墙释放了前端5060公网映射端口，而wvp没有重建？
本以为22日修改的删除启动后redis配置能解决，但问题还是存在。

**Comment by 648540858** [comment]
作为国标上级的wvp不会主动连接设备端，所以其实内网穿透的通道是由设备向wvp发起注册后建立的，所以只要的你的设备重新注册了，就不应该有这些问题。wvp记录的实际到达时的ip与端口，回复也是针对这个端口回复的。所以你说的
```
前端防火墙释放了前端5060公网映射端口
```
是对的，但是重建的过程不是wvp所负责的，应该是设备重新注册后重新建立。

**Comment by penghd** [comment]
> 
> 
> 所以只要的你的设备重新注册了，就不应该有这些问题。

设备注册正常，注册日志正常，设备列表进入通道列表、播放都可以点动，但播放不出来。
日志显示向前端发送ACK信号

**Comment by 648540858** [comment]
如果在zlm没看到流注册。那说明设备没有发流。可以抓包看设备收到ack
