### ISSUE TITLE
技术咨询: 麻烦大佬们给我看看什么问题行吗？

### ISSUE THREAD

**Issue by qimingkunnanzheng** [648540858/wvp-GB28181-pro#1141]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
两个zlm节点时，子节点无法播放，点击没有响应，过会点播超时,与主节点不是一台机器，但是两台机器内网通的，我这里配置的信息都是子节点的公网ip，想请教下那里的问题导致的
![1698913610802](https://github.com/648540858/wvp-GB28181-pro/assets/144506949/fe954844-e80e-469c-ac44-f30cafb58be3)

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传

**Comment by linkewei0580** [comment]
先试试配置内网地址正常吗？

**Comment by yaoxiaojian-liuxiaojun** [comment]
telnet 端口是否正常

**Comment by qimingkunnanzheng** [comment]
端口都时正常的，我配置的这些信息对吗，大佬们，上面的分别是子节点的内网ip，还有公网ip

**Comment by mengxing2017** [comment]
hookip应该是填错了，hookip填wvp的地址
