### ISSUE TITLE
集群部署:WVP-PRO现在支持集群部署了没？我大致看了下代码貌似是没有支持的，希望可以得到一个确认的答复！

### ISSUE THREAD

**Issue by wangguodong8602** [648540858/wvp-GB28181-pro#1143]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by aidelingyu** [comment]
我感觉不支持的，我们现在也在做改造集群的工作

**Comment by 648540858** [comment]
不支持的，国标28181-2016版本的协议就是不支持集群的，你可以通过级联的方式保证项目的健壮

**Comment by yaoxiaojian-liuxiaojun** [comment]
> 我感觉不支持的，我们现在也在做改造集群的工作

你们目前的方案是什么,是通过网关,做类似于分库的模拟操作嘛

**Comment by aidelingyu** [comment]
@yaoxiaojian-liuxiaojun 开始是想把很多存到本地jvm的东西改到redis里面存储的，但是改动有点多。最后就想试一下直接用nginx转发端口的流量，用ip hash的方式，把一个ip的流量都转到一台服务器上。

**Comment by VincentYuan-hub** [comment]
> @yaoxiaojian-liuxiaojun 开始是想把很多存到本地jvm的东西改到redis里面存储的，但是改动有点多。最后就想试一下直接用nginx转发端口的流量，用ip hash的方式，把一个ip的流量都转到一台服务器上。

请问你们后面这样成功了吗？ 能支持多少SIP的链接？另外这样应该公网是不行的把？

**Comment by aidelingyu** [comment]
@VincentYuan-hub ip_hash的转发我没试，但想了一下也会有问题。sip使用tcp连接的话，服务器和摄像头需要保持tcp连接的，如果用ip_hash的方式，增加了服务器的话，hash的结果就变了，被转发到别的服务器，连接就找不到了。因为tcp的方式需要保存连接，试有状态的，所以应该做不了集群。
