### ISSUE TITLE
技术咨询：可以拉取两个通道，一个主码流，一个子码流吗？怎么做？

### ISSUE THREAD

**Issue by paddy0615** [648540858/wvp-GB28181-pro#1149]
我想一个设备提供两个 rtsp或者flv 流，一个是主码流，一个是子码流。
目前测试使用SIP协议发送s=Play点播带f字段（f= v/编码格式/分辨率/帧率/码率类型/码率大小a/编码格式/码率大小/采样率），设置无效；
求大佬解答？
如果请求不了设备，默认拉取主码流，那么可以在zlm流媒体 ，再转一个子码流出来吗？

**Comment by paddy0615** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/43235179/fc8f3d90-60e8-488b-b5ae-a05832d8394d)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/43235179/6ab9c976-ac31-44e0-b282-78811a57d58e)


为什么没生效呢？

**Comment by anglamei** [comment]
大部分摄像机这块不支持的

**Comment by anglamei** [comment]
邮箱已收到！
