### ISSUE TITLE
除rtsp流，其他的都没有声音

### ISSUE THREAD

**Issue by xinsendi** [648540858/wvp-GB28181-pro#1150]
**环境信息:**

 - 1. 编译wvp-pro zlm自动安装
 - 2. 部署环境 centos7.5
 - 3. 端口开放情况 全开放
 - 4. 内网部署
 - 5. 没有启动https
 - 6. 华为C2150
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 10月份代码，应该挺新的

内容描述:
摄像头使用gb28181接入，视频流选择了复合流。
使用VLC播放，发现除了rtsp流以外，其他的视频流均是没有音频输出的。
是我摄像头gb配置出问题了？

![image](https://github.com/648540858/wvp-GB28181-pro/assets/130046179/52c4a34a-49e7-4d0c-8866-6f3e04ea48ca)

**Comment by xiaoQQya** [comment]
> **环境信息:**
> 
> * 1. 编译wvp-pro zlm自动安装
> * 2. 部署环境 centos7.5
> * 3. 端口开放情况 全开放
> * 4. 内网部署
> * 5. 没有启动https
> * 6. 华为C2150
> * 7. 你做过哪些尝试
> * 8. 代码更新时间 10月份代码，应该挺新的
> 
> 内容描述: 摄像头使用gb28181接入，视频流选择了复合流。 使用VLC播放，发现除了rtsp流以外，其他的视频流均是没有音频输出的。 是我摄像头gb配置出问题了？
> 
> ![image](https://user-images.githubusercontent.com/130046179/281670877-52c4a34a-49e7-4d0c-8866-6f3e04ea48ca.png)

1. 首先确认摄像机是否支持音频，如果 rtsp 流存在音频应该是支持；
2. 确认 wvp 点播时是否开启了音频；
    ![image](https://github.com/648540858/wvp-GB28181-pro/assets/46475319/898dac2c-a8e4-4dbf-9180-e1dd7956a0ca)
3. 查看 zlm 日志设备是否推送了音频轨道；
    ![image](https://github.com/648540858/wvp-GB28181-pro/assets/46475319/7bc8c582-a1fc-4ee0-9b23-e624fd4903d6)

**Comment by xinsendi** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/130046179/5f7f08d3-cd2d-48df-9e45-d2324049e4a4)
看到zlm的日志里面是有音轨的

![image](https://github.com/648540858/wvp-GB28181-pro/assets/130046179/3b61970d-c235-444f-9c38-f9139979d5fe)
音频也是开启的

**Comment by 648540858** [comment]
看看你的音频格式

**Comment by xinsendi** [comment]
摄像头的吗？
![image](https://github.com/648540858/wvp-GB28181-pro/assets/130046179/1d6d873b-0802-4daa-9b2f-787816fb2d5e)

**Comment by 648540858** [comment]
改成aac试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月13日(周一) 上午9:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] 除rtsp流，其他的都没有声音 (Issue #1150)




 
摄像头的吗？

**Comment by xinsendi** [comment]
改成AAC后音轨是有了，但是没有声音出来。

rtsp流的声音也没有了

**Comment by 648540858** [comment]
你直接拿一下设备本身的rtsp流播放试试，或者设备自己的网页播放试试，看看声音怎么样
