### ISSUE TITLE
点击实时视频-播放，一直黑窗口loading的问题

### ISSUE THREAD

**Issue by cohobo** [648540858/wvp-GB28181-pro#1151]
**环境信息:**

 - 1. 部署方式 docker
 - 2. 部署环境 windows
 - 3. 端口开放情况
 - 4. 是否是公网部署 否（服务部署和摄像头在同一内网网段）
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 无
 - 7. 你做过哪些尝试 更换浏览器，无效
 - 8. 代码更新时间 拉取的648540858/wvp_pro docker镜像，通过下面命令启动的
 ```
docker run --env WVP_IP="192.168.0.124" -it -p 6080:80 -p 10443:443 -p 10935:1935 -p 19351:19350 -p 10554:554 -p 10554:554/udp -p 10332:332 -p 10332:332/udp -p 10010:10000 -p 10010:10000/udp -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp panjjo/zlmediakit
```

**内容描述:**
通过docker部署启动了包含wvp和zlm的容器后，打开页面，并添加了两个设备，两个设备也都注册进来了，但是点【实时视频】-【播放】无法播放，一直是黑窗口loading，但录像里能查看到一些录制的画面
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/50228103/0ba22712-db29-443e-a78f-09384f439ac6)

**抓包文件**
  无
**日志**
```
wvp运行日志和zlm日志文件见附件
```
[wvp.log](https://github.com/648540858/wvp-GB28181-pro/files/13314823/wvp.log)
[zlm.log](https://github.com/648540858/wvp-GB28181-pro/files/13314826/zlm.log)

**Comment by cohobo** [comment]
更正一下问题描述：docker启动命令，是这个
```
docker run --name wvp --env WVP_IP=192.168.0.124 -it -p 18080:18080 -p 6579:6379 -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp -p 80:80 -p 5060:5060 -p 5060:5060/udp 648540858/wvp_pro
```

**Comment by mengxing2017** [comment]
80端口udp没开，另外docker也不维护了

**Comment by 648540858** [comment]
直接编译运行吧，那个docker镜像版本已经差异很大了
