### ISSUE TITLE
技术咨询-{"code":401,"msg":"请登录后重新请求"}

### ISSUE THREAD

**Issue by jiang2586** [648540858/wvp-GB28181-pro#1152]
部署方式：编译 wvp-pro-2.6.9 + 编译wvp-pro-assist-2.6.8 + zlmediakit都是编译部署
部署环境： ubuntu22.04
端口开放情况：端口无任何限制
是否是公网部署 ：纯内网环境
是否使用https：否
方便的话提供下使用的设备品牌或平台
你做过哪些尝试
代码更新时间：11月10日

**内容描述:**
今天重新搭建了wvp-pro+ZLMediaKit+wvp-pro-assist，所有功能都调通了。于是将搭建好的系统制作成模板并创建了一台新虚拟机，在登录时出现{"code":401,"msg":"请登录后重新请求"}的错误提示，登录页面直接无法加载。翻看了之前相关的issue，说是需要添加请求头 'access-token'或者放在参数里。本人代码小白，不清楚如何操作，是需要在登录地址后面加具体的参数吗？如果是，具体的格式是什么？还是说需要修改某个文件？能否请老师指点一下，谢谢！
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/134902132/57c23873-3a29-41c1-992d-fa4131ca6e2c)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
前端没编译

**Comment by jiang2586** [comment]
> 前端没编译

不是在wvp-GB28181-pro/目录下，执行mvn package就可以了吗？会生成一个target目录，里面有个可执行的jar包，而且在最开始编译完成后，直接通过网址+端口的方式是可以访问的，后来就不行了。
老师所说的前端没编译是指什么呢？能否详细告知，小弟在此多谢了！

**Comment by 648540858** [comment]
仔细看下doc.wvp-pro.cn的编译步骤吧，编译java项目前需要先编译前端的

**Comment by jiang2586** [comment]
> 仔细看下doc.wvp-pro.cn的编译步骤吧，编译java项目前需要先编译前端的

非常感谢，问题已经解决，使用npm编译前端后就可以了！
