### ISSUE TITLE
多端口收流，九千个端口，三十个摄像头出现播放频繁串流情况，A摄像头播放B摄像头

### ISSUE THREAD

**Issue by qimingkunnanzheng** [648540858/wvp-GB28181-pro#1153]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...          centos
 - 3. 端口开放情况 全开
 - 4. 是否是公网部署 是
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台 海康和大华
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 最新

**描述错误**
描述下您遇到的问题
多端口收流，九千个端口，三十个摄像头出现播放频繁串流情况，A摄像头播放B摄像头
**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
1. 你分配了多少端口
2. 设备是宽带连接还是4G连接

**Comment by qimingkunnanzheng** [comment]
50000-59000的端口，属于宽带连接

**Comment by qimingkunnanzheng** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/144506949/caa4125c-5d7d-4e05-8ec6-3cbf240787a0)

**Comment by 648540858** [comment]
每次串流是串到同一个还是完全随机的。建议尝试找一下规律，这问题我不好复现。

**Comment by qimingkunnanzheng** [comment]
完全随机的，几次都是随机的，没有特别固定的，这种情况是端口冲突了吗

**Comment by 648540858** [comment]
我觉得不是，你把完整的日志发我邮箱一份，我研究下。648540858@qq.com

**Comment by qimingkunnanzheng** [comment]
好的，我截取一下，这会不会跟我只重启了wvp有关系

**Comment by 648540858** [comment]
有关系，最好重启的时候zlm也一起重启了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月13日(周一) 中午11:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] 多端口收流，九千个端口，三十个摄像头出现播放频繁串流情况，A摄像头播放B摄像头 (Issue #1153)




 
好的，我截取一下，这会不会跟我只重启了wvp有关系

**Comment by qimingkunnanzheng** [comment]
ok，那就先关了，有问题了在反馈

**Comment by qimingkunnanzheng** [comment]
.
