### ISSUE TITLE
日志一直打印redis创建关闭连接

### ISSUE THREAD

**Issue by yebo-luo** [648540858/wvp-GB28181-pro#1155]
**环境信息:**

 - 1. 部署方式  编译wvp-pro + zlm都是编译部署/
 - 2. 部署环境  ubuntu
 - 3. 端口开放情况
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
启动wvp-pro项目时，日志打印很多图中信息

**如何复现**
有明确复现步骤的问题会很容易被解决
最新版代码打包就会出现这个问题

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by yebo-luo** [comment]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=5704236222746912791 skey=@crypt_7f692689_a68780596fb405c74118f36051ea208e mmweb_appid=wx_webfilehelper](https://github.com/648540858/wvp-GB28181-pro/assets/85433337/75bd21c9-3d14-468e-a2cf-6da581a7f6af)

**Comment by xiaoQQya** [comment]
> ![cgi-bin_mmwebwx-bin_webwxgetmsgimg_ MsgID=5704236222746912791 skey=@crypt_7f692689_a68780596fb405c74118f36051ea208e mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/85433337/282640331-75bd21c9-3d14-468e-a2cf-6da581a7f6af.jpg)

这是因为您将日志级别设置为了 debug 级别，导致打印了很多 debug 信息，将日志级别改为 info 级别即可。

**Comment by yebo-luo** [comment]
那请问配置中如何设置日志打印的级别呢？我这个日志是nohup后台启动时自增的文件日志，自动生成的logs文件
中的日志很正常。我以为是redis报错了，旧版的服务启动就没有这个问题


My&nbsp;&nbsp;Sunshine
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 中午12:44
***@***.***&gt;;
抄送:&nbsp;"My  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro] 日志一直打印redis创建关闭连接 (Issue #1155)





  

  
这是因为您将日志级别设置为了 debug 级别，导致打印了很多 debug 信息，将日志级别改为 info 级别即可。

**Comment by xiaoQQya** [comment]
> 那请问配置中如何设置日志打印的级别呢？我这个日志是nohup后台启动时自增的文件日志，自动生成的logs文件 中的日志很正常。我以为是redis报错了，旧版的服务启动就没有这个问题 My&nbsp;&nbsp;Sunshine ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "648540858/wvp-GB28181-pro" ***@***.***&gt;; 发送时间:&nbsp;2023年11月14日(星期二) 中午12:44 ***@***.***&gt;; 抄送:&nbsp;"My ***@***.******@***.***&gt;; 主题:&nbsp;Re: [648540858/wvp-GB28181-pro] 日志一直打印redis创建关闭连接 (Issue #1155) 这是因为您将日志级别设置为了 debug 级别，导致打印了很多 debug 信息，将日志级别改为 info 级别即可。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

修改 `src/main/resources/logback-spring.xml` 文件，将 root 的日志级别改为 INFO。

![image](https://github.com/648540858/wvp-GB28181-pro/assets/46475319/af9da06f-27c2-4f16-82a3-2b6b721b076e)
