### ISSUE TITLE
启动报错 Could not connect to /192.168.1.21:5062

### ISSUE THREAD

**Issue by zhazha109** [648540858/wvp-GB28181-pro#1161]
**环境信息:**

 - 1. jar包部署
 - 2. centos 7
 - 3. 5060,30000-30500
 - 4. 是公网部署 
 - 5. 没有使用https
 - 6. 海康
 - 7. 重启报错
 - 8. wvp-pro-2.3.2

**内容描述:**
系统停止后再次运行启动失败。
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/30107152/6788859b-8cf5-43c9-86e2-d1e20754418b)

**抓包文件**
  
**日志**
```
[nohup.log](https://github.com/648540858/wvp-GB28181-pro/files/13389338/nohup.log)

```

**Comment by mengxing2017** [comment]
装最新的吧，作者只维护最新版

**Comment by 648540858** [comment]
很老的版本了。不维护了
