### ISSUE TITLE
wvp-pro无法与zlmediakit建立连接

### ISSUE THREAD

**Issue by DarkHorse-YU** [648540858/wvp-GB28181-pro#1162]
**环境信息:**

 - 1. 部署方式：wvp-pro（windows11） / zlm(docker)
 - 2. 部署环境：windows11
 - 3. 端口开放情况：都开放
 - 4. 是否是公网部署：局域网同台机器
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：海康只能球形摄像机
 - 7. 你做过哪些尝试：配置文件都已修改对应内容
 - 8. 代码更新时间：2023.11.17

**内容描述:目前是本机windows11，使用idea启动wvp-pro，zlmediakit使用docker启动，但是wvp-pro无法与zlmediakit建立连接

**截图**  
![1700210613614](https://github.com/648540858/wvp-GB28181-pro/assets/82326966/f53b32c5-ce93-403a-b80a-a38147919205)
![1700210687485](https://github.com/648540858/wvp-GB28181-pro/assets/82326966/c34e6480-292a-40a4-8347-ad79987f244a)

**Comment by DarkHorse-YU** [comment]
> hookip 是你本机ip,id和secret要配置正确
感谢您的回复，目前media.id与zlm的mediaServerId已经对应，media.ip配置的是本机局域网ip，hook-ip不填写默认使用sip.ip与media.ip一致；secret是可选的我看，并且zlm的[hook]中没有admin_params这个配置，enable这个配置项也是0，secret要配置到zlm的[hook]里吗

**Comment by mengxing2017** [comment]
hook-ip填你wvp的ip地址就行，wvp会自动修改zlm的配置的，media.ip是能访问zlm的ip

**Comment by DarkHorse-YU** [comment]
感谢，没问题了，我的secret设置错了，应该配置zlm配置文件中的secret
![image](https://github.com/648540858/wvp-GB28181-pro/assets/82326966/8c8cab46-1b02-4750-b9e1-48f44c31cc32)
