### ISSUE TITLE
BUG：历史视频回放中streamId参数不存在

### ISSUE THREAD

**Issue by bigbeef** [648540858/wvp-GB28181-pro#1163]
历史视频回放中streamId参数不存在
![image](https://github.com/648540858/wvp-GB28181-pro/assets/17740213/d72843d1-1ad7-4c95-b217-f6d5816b0ec9)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/17740213/ab4c0bc4-dea7-455b-befe-69da658b76dd)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/17740213/9bebf0e5-edf0-4976-aca5-30397c460596)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/17740213/5c0fd2d3-f75b-4365-b233-f76975f73ae0)

**Comment by 648540858** [comment]
具体遇到什么问题

**Comment by bigbeef** [comment]
历史视频无法播放
