### ISSUE TITLE
wvp-pro后台收不到设备报警

### ISSUE THREAD

**Issue by DarkHorse-YU** [648540858/wvp-GB28181-pro#1164]
**环境信息:**

 - 1. 部署方式：wvp-pro(windows)、zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境：windows11
 - 3. 端口开放情况：已经开放
 - 4. 是否是公网部署：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：海康4G球形摄像机
 - 7. 你做过哪些尝试：设备重启，配置修改
 - 8. 代码更新时间：2023.11.19

**内容描述:**
目前设备已接入，可以实时预览和云台控制，但是设备侦测告警无法收到消息，sip.port端口已经开放，心跳检测正常，报警接收还需要其他什么配置吗

**Comment by mengxing2017** [comment]
抓包看看下级有没有上报

**Comment by zishuai-hao** [comment]
可能需要给设备发SetGuard指令，不行的话就给设备发Query type:Alarm指令

**Comment by DarkHorse-YU** [comment]
> 可能需要给设备发SetGuard指令，不行的话就给设备发Query type:Alarm指令

好哒感谢，调用接口设置一下SetGuard可以接收到了
