### ISSUE TITLE
请问为啥dockerfile不更新了？

### ISSUE THREAD

**Issue by beck-8** [648540858/wvp-GB28181-pro#1168]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
https://github.com/SaltFish001/wvp_pro_compose ，你可以把这个维护起来，自己动手，丰衣足食

**Comment by 648540858** [comment]
没精力
