### ISSUE TITLE
BUG-关于树结构查询or条件连接异常的问题描述

### ISSUE THREAD

**Issue by yaoxiaojian-liuxiaojun** [648540858/wvp-GB28181-pro#1169]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境  centos ...

**描述错误**
关于树结构查询or条件连接异常的问题描述

**如何复现**
sql分析

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/59216715/191fdf53-feeb-4567-b043-5c9fc40891cb)

```

**Comment by yaoxiaojian-liuxiaojun** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/59216715/6b272eed-bdf7-42d2-a7fd-c3723d1999e6)

**Comment by yaoxiaojian-liuxiaojun** [comment]
下级推上来的数据parentid为空导致

**Comment by 648540858** [comment]
会在新版本解决这个问题

**Comment by 648540858** [comment]
新版本已经发布,可以测试了
