### ISSUE TITLE
摄像头突然无法播放 配置都没改动过

### ISSUE THREAD

**Issue by zhanpc** [648540858/wvp-GB28181-pro#1170]
**环境信息:**

 - 1. 部署方式  编译wvp-pro + zlm都是编译部署/
 - 2. 部署环境 windows11
 - 3. 端口开放情况 全开放
 - 4. 是否是公网部署  是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康威视
 - 7. 你做过哪些尝试 重新启动wvp和zlm
 - 8. 代码更新时间

**内容描述:**
有一个注册好的摄像头 昨天播放一直正常 但是今天再次点开播放 提示400点播失败 400 bad request
**截图**  
![设备在线](https://github.com/648540858/wvp-GB28181-pro/assets/86341644/630f65b6-9a8c-4b26-bada-504aceb317c3)
![无法播放](https://github.com/648540858/wvp-GB28181-pro/assets/86341644/9ab07b04-703d-4f0a-b928-b7dcf80fbe12)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
400,是摄像头掉线了吧

**Comment by zhanpc** [comment]
> 400,是摄像头掉线了吧

这个我回头看下现场的摄像头 还有个问题想咨询一下 http的视频访问正常 但是https的无法播放 
![image](https://github.com/648540858/wvp-GB28181-pro/assets/86341644/94264694-27b0-4c6e-bcdd-5b617ba578d6)

**Comment by mengxing2017** [comment]
> > 400,是摄像头掉线了吧
> 
> 这个我回头看下现场的摄像头 还有个问题想咨询一下 http的视频访问正常 但是https的无法播放 ![image](https://user-images.githubusercontent.com/86341644/284444342-94264694-27b0-4c6e-bcdd-5b617ba578d6.png)

需要配置证书

**Comment by zhanpc** [comment]
> > > 400,是摄像头掉线了吧
> > 
> > 
> > 这个我回头看下现场的摄像头 还有个问题想咨询一下 http的视频访问正常 但是https的无法播放 ![image](https://user-images.githubusercontent.com/86341644/284444342-94264694-27b0-4c6e-bcdd-5b617ba578d6.png)
> 
> 需要配置证书

配置证书这块  有相关文档嘛

**Comment by mengxing2017** [comment]
> > > > 400,是摄像头掉线了吧
> > > 
> > > 
> > > 这个我回头看下现场的摄像头 还有个问题想咨询一下 http的视频访问正常 但是https的无法播放 ![image](https://user-images.githubusercontent.com/86341644/284444342-94264694-27b0-4c6e-bcdd-5b617ba578d6.png)
> > 
> > 
> > 需要配置证书
> 
> 配置证书这块 有相关文档嘛

zlm的见zlm的wiki,wvp的你去作者的文档找找

**Comment by zhanpc** [comment]
> 400,是摄像头掉线了吧
不是设备离线  今天又出现了这个情况  原先播放正常 突然部分摄像头无法播放  配置没有修改过  wvp显示设备均在线
![image](https://github.com/648540858/wvp-GB28181-pro/assets/86341644/262936c9-d17e-4892-95e8-4976594ff727)

**Comment by zhanpc** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/86341644/d0d78d96-3553-4805-b502-6001c251dec8)
