### ISSUE TITLE
wvp启动时并未主动去连接ZlM

### ISSUE THREAD

**Issue by qimingkunnanzheng** [648540858/wvp-GB28181-pro#1171]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 最新

**描述错误**
描述下您遇到的问题
wvp启动然后后面也没去连接zlm
![image](https://github.com/648540858/wvp-GB28181-pro/assets/144506949/7d48b781-7638-4e23-8ef8-11b37f0b5f60)

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by qimingkunnanzheng** [comment]
并没有去连接zlm，我的media配置的没问题

**Comment by mengxing2017** [comment]
zlm的端口、id、secret检查一下，要两边一致
