### ISSUE TITLE
技术咨询 关于级联TCP主动模式

### ISSUE THREAD

**Issue by szy833** [648540858/wvp-GB28181-pro#1175]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
看了一下级联点播 TCP主动 模式的代码，有个疑问，为什么只有开启了ssrc校验之后，才支持TCP主动模式？
**截图**  
![企业微信截图_17006415492278](https://github.com/648540858/wvp-GB28181-pro/assets/31844882/19412d08-572f-4e81-9f78-55b503764327)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
这是更新ssrc，和国标级联的无关的。也可能代码截图很老了。
