### ISSUE TITLE
运行一段时间  就无法请求zlm的api接口了  但是zlm服务是启动的 【zlm的80端口映射了 8117端口】    查看端口占用有很多连接在 但是监控视频在界面都关闭了

### ISSUE THREAD

**Issue by duhaoranc** [648540858/wvp-GB28181-pro#1176]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - zlm(docker) + idea启动wvp-pro
 - 2. 部署环境 windows / ubuntu/ centos ...
 - windows
 - 3. 端口开放情况
 - 开启了必要的端口
 - 4. 是否是公网部署 
 - 否
 - 5. 是否使用https
 - 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 大华设备
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
23-11-20

**内容描述:**
  TCP    0.0.0.0:8117           0.0.0.0:0              LISTENING       47780
  TCP    192.168.0.213:8117     192.168.0.213:60784    CLOSE_WAIT      47780
  TCP    192.168.0.213:8117     192.168.0.213:60786    CLOSE_WAIT      47780
  TCP    192.168.0.213:8117     192.168.0.213:60787    ESTABLISHED     47780
  TCP    192.168.0.213:8117     192.168.0.213:60793    CLOSE_WAIT      47780
  TCP    192.168.0.213:8117     192.168.0.213:60812    CLOSE_WAIT      47780
  TCP    192.168.0.213:8117     192.168.0.213:60819    CLOSE_WAIT      47780
  TCP    192.168.0.213:8117     192.168.0.213:60846    CLOSE_WAIT      47780
  TCP    192.168.0.213:8117     192.168.0.213:60986    ESTABLISHED     47780
  TCP    192.168.0.213:60784    192.168.0.213:8117     FIN_WAIT_2      31248
  TCP    192.168.0.213:60786    192.168.0.213:8117     FIN_WAIT_2      35532
  TCP    192.168.0.213:60787    192.168.0.213:8117     ESTABLISHED     35532
  TCP    192.168.0.213:60793    192.168.0.213:8117     FIN_WAIT_2      31248
  TCP    192.168.0.213:60812    192.168.0.213:8117     FIN_WAIT_2      31248
  TCP    192.168.0.213:60819    192.168.0.213:8117     FIN_WAIT_2      31248
  TCP    192.168.0.213:60846    192.168.0.213:8117     FIN_WAIT_2      31248
  TCP    192.168.0.213:60986    192.168.0.213:8117     ESTABLISHED     31248
  TCP    [::]:8117              [::]:0                 LISTENING       47780
  TCP    [::1]:8117             [::]:0                 LISTENING       15776
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37980297/a3d23624-8043-4ca6-bcac-50053ad210cb)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by duhaoranc** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37980297/83740b49-c940-466c-9dcd-89545c995d58)
看监控是可以看的  但是过段时间  zlm接口就不通了

**Comment by mengxing2017** [comment]
干嘛不用8117:8117,配置文件在你手上，那不是随便改

**Comment by 648540858** [comment]
端口需要一一对应
