### ISSUE TITLE
技术咨询-点播端口分配异常

### ISSUE THREAD

**Issue by jbztech** [648540858/wvp-GB28181-pro#1178]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) 
 - 2. 部署环境 ubuntu/ 
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
点播端口分配异常

**截图**  

<img width="1662" alt="图片" src="https://github.com/648540858/wvp-GB28181-pro/assets/40271209/3a0e7850-a21b-46b6-b044-15ba5775233e">

  
**日志**
```
<img width="1662" alt="图片" src="https://github.com/648540858/wvp-GB28181-pro/assets/40271209/7f2f3682-9894-4e36-bc27-f35f2c87dd35">

```

**Comment by mengxing2017** [comment]
提示都这么明确了，多开点端口不就完了
