### ISSUE TITLE
[BUG] 启动前端报错

### ISSUE THREAD

**Issue by abcwuhang** [648540858/wvp-GB28181-pro#1180]
**环境信息:**

 - 1. 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows
 - 3. 端口开放情况：本地机器
 - 4. 是否是公网部署： 否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
启动前端时报错

**如何复现**
有明确复现步骤的问题会很容易被解决

![image](https://github.com/648540858/wvp-GB28181-pro/assets/4589066/8c1f0fc2-c891-4e5d-a823-dbf5fba4d569)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
使用node 16就行了

**Comment by abcwuhang** [comment]
换成nodejs16后，启动前端成功，但还是进不去
![image](https://github.com/648540858/wvp-GB28181-pro/assets/4589066/8dbcb690-6b05-4924-94ab-4eb342c28323)
