### ISSUE TITLE
wvp视频状态不准确 在线 但无法播放  zlm会丢失 播放几个小时后 找不到zlm

### ISSUE THREAD

**Issue by zhanpc** [648540858/wvp-GB28181-pro#1181]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows11
 - 3. 端口开放情况 都开放
 - 4. 是否是公网部署  是
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台 海康威视
 - 7. 你做过哪些尝试 重启zlm和wvp 
 - 8. 代码更新时间 

**描述错误**
一开始视频播放 和状态显示都是正确  后来 视频掉线  wvp显示在线 点击播放无法播放一直黑屏   过较长一段时间后  视频才可以播放

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
[wvp-2023-11-28.0.log](https://github.com/648540858/wvp-GB28181-pro/files/13482534/wvp-2023-11-28.0.log)
[wvp-2023-11-29.1.log](https://github.com/648540858/wvp-GB28181-pro/files/13497351/wvp-2023-11-29.1.log)

```

**Comment by 648540858** [comment]
重启服务后需要设备重新注册上线后状态才可以正常，如果是局域网接入的，设备地址可达，那么状态不对也可以直接点播的
