### ISSUE TITLE
BUG 添加新流报错

### ISSUE THREAD

**Issue by abcwuhang** [648540858/wvp-GB28181-pro#1182]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/4589066/afe70b7c-a00d-4f25-ac6c-74c55fad493d)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/4589066/8af8376d-257d-4801-be33-e5bde6b40c19)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by abcwuhang** [comment]
修改了mysql的sdp_ip字段长度，还是无法拉取虎牙数据流
![image](https://github.com/648540858/wvp-GB28181-pro/assets/4589066/085eaff1-a343-4488-9115-cf3a7b9aa89e)

**Comment by 648540858** [comment]
"修改了mysql的sdp_ip字段长度"是什么意思
