### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by ERAIT** [648540858/wvp-GB28181-pro#1184]
**环境信息:**

 - 1. 部署方式 编译部署
 - 2. 部署环境 windows 
 - 3. 端口开放情况 全开放
 - 4. 是否是公网部署  内网
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康威视
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 2.6.8

**内容描述:**
使用
ffmpeg -rtsp_transport tcp -i rtsp://admin:@/steam -vcodec copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/stream
ffplay rtsp://127.0.0.1/live/stream -rtsp_transport tcp
可以读取流
同一个流
在wvp-pro上点播，提示超时，ZLMediaKit提示超时

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/32009330/935ec926-ed79-48c8-9699-c6c9279b6873)
![Uploading image.png…]()

**抓包文件**
  wireshark抓包存在丢包现象
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by ERAIT** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/32009330/3793606d-13aa-41e1-82f9-451d4d2cec56)
通道设置的是tcp被动，ffmpeg是可以播放，点播不行

**Comment by ERAIT** [comment]
在国标设备上 NVR自动注册上的

**Comment by ERAIT** [comment]
同步之后进入通道，32通道个别点播可以打开，多数显示收流超时，ZLMediaKit显示丢包

**Comment by ERAIT** [comment]
> 你点播是设置到国标级联了？在上级播放的？

同步之后进入通道，32通道个别点播可以打开，多数显示收流超时，ZLMediaKit显示丢包
没有设置国标级联

**Comment by ERAIT** [comment]
> 你点播是设置到国标级联了？在上级播放的？

ffmpeg -rtsp_transport tcp -i rtsp://admin:@/steam -vcodec copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/stream
ffplay rtsp://127.0.0.1/live/stream -rtsp_transport tcp
同一个NVR通道，用以上推流播放，没有问题，用的同一个ZLMediaKit

**Comment by 648540858** [comment]
设备列表使用tcp被动试试
