### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by zyd0322** [648540858/wvp-GB28181-pro#1186]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 是
 - 5. 是否使用https否
 - 6. 方便的话提供下使用的设备品牌或平台 无
 - 7. 你做过哪些尝试 部署至其他服务器
 - 8. 代码更新时间

**内容描述:**
  拉起代码下来 进行相应的修改 如我修改了登录页面的文字本地运行文字被修改了，但是我打包在线上后文字没有改变， 其他被注释掉的文字也显示出来了，打包的时候应该注意什么 我把打包配置也进行了修改。
**截图**  
![微信图片_20231129172312](https://github.com/648540858/wvp-GB28181-pro/assets/65068854/36c0fa78-b184-4796-ab97-0c3d5859d162)
![微信图片1](https://github.com/648540858/wvp-GB28181-pro/assets/65068854/55848d44-c328-487c-b02b-be61246e5a1f)

![微信图片23](https://github.com/648540858/wvp-GB28181-pro/assets/65068854/b3b773bc-ede5-4e07-9167-d15d6e958478)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
不清楚你具体修改了什么，正常你需要改个登录页就可以了，重新打包即可。
