### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by seven54** [648540858/wvp-GB28181-pro#1189]
外网摄像头加入数字中心服务器，由于数字中心不允许公网IP回环，我把sdp-ip和hook-ip改成域名，域名做好本地hosts,摄像头可以正常注册，但是无法播放。日志显示播放超时。

![1701398782498](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/d83cbe71-af5f-4dd4-9339-b523eeea7d02)
![1701398955209](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/ab96017b-d6e4-488f-8de9-6fe00ddb0be1)

**Comment by 648540858** [comment]
sdp 必须使用ip，不能使用域名，国标协议不支持
