### ISSUE TITLE
前端页面登录后接口请求报错？Full authentication is required to access this resource

### ISSUE THREAD

**Issue by TongBig** [648540858/wvp-GB28181-pro#119]
code: "-1"
msg: "Full authentication is required to access this resource"

**Comment by 648540858** [comment]
你编译前端页面了吗

**Comment by TongBig** [comment]
编译好了，登录也成功了，调其他接口报的错，跳回登录页，是不是有安全验证，请求头要加cookies？

**Comment by 648540858** [comment]
你是自己调用的接口， 肯定需要把cookie带上的，参考web页面发起的请求
