### ISSUE TITLE
[BUG] 向上级国标平台上报目录和通道时，通道CivilCode值不对

### ISSUE THREAD

**Issue by shuxiaoyuan** [648540858/wvp-GB28181-pro#1190]
**环境信息:**

 - 1. 部署方式： wvp-pro docker / zlm(docker) 
 - 2. 部署环境：ubuntu
 - 3. 端口开放情况：没有限制
 - 4. 是否是公网部署：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：海康摄像头
 - 7. 你做过哪些尝试
 - 8. 代码更新时间：2023/11/3 at 17:32

**描述错误**
wvp 向上级国标平台上报目录和通道时，通道的 CivilCode 值被设置成了对应目录的 CivilCode 值。导致上级平台若按区划方式处理设备树，会将通道挂载到对应目录的上一级。

**如何复现**
在下级平台我将“海康枪机”挂载到了青岛（区划3702）节点下，如下图所示：
![T6IQO_BE2@5S`Y(TI$4RI(N](https://github.com/648540858/wvp-GB28181-pro/assets/40308681/85576be8-6e16-40ec-bd15-bc52b579db21)

但是上级的wvp_device_channel表中，海康枪机的 CivilCode 值变成了 37（山东省），如下图所示：
![3{$K ZJ@7%9~`L3%YRVBL12](https://github.com/648540858/wvp-GB28181-pro/assets/40308681/8f166801-d091-48f7-b295-a2a0facec4a4)

**截图**  
定位到对应的代码截图：
![V 4M}6YF}K9%QM2T4L_4ZE5](https://github.com/648540858/wvp-GB28181-pro/assets/40308681/007186f4-cae7-48f2-b96d-3277d5eff4c1)
![ZAW4PNA2GD)_2N P)9HAQ)S](https://github.com/648540858/wvp-GB28181-pro/assets/40308681/90b0138a-a05b-457e-9b7f-c5abeb5f1e35)

另外，若按业务分组+虚拟组织方式上报设备树时，是否应该将通道的 CivilCode 字段设置为空？否则，上级应如何确定是按区划方式处理设备树还是按业务分组+虚拟组织方式处理设备树呢？

**抓包文件**
 
**日志**

**Comment by 648540858** [comment]
这个问题会在新版得到彻底解决

**Comment by 648540858** [comment]
新版本已经发布,可以测试了
