### ISSUE TITLE
[技术咨询] 预置位查询超时

### ISSUE THREAD

**Issue by xiaohuiL** [648540858/wvp-GB28181-pro#1193]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker)
 - 2. 部署环境 centos
 - 3. 端口开放情况 开放
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康球机
 - 7. 你做过哪些尝试  设置超时时长
 - 8. 代码更新时间 

**内容描述:**
点播等接口都正常，只有获取预置位时提示超时。查看抓包发现没有response
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/26140533/d0995b23-4076-423d-b1c0-8f5b22f5c3a4)

**抓包文件**
  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/26140533/7a34d9d1-9196-4e00-89d3-a8b131bfb8e3)

**日志**
![image](https://github.com/648540858/wvp-GB28181-pro/assets/26140533/eea5a4ff-18fd-491b-9c03-27701097e74b)
日志内容放这里， 文件的话请直接上传
```

**Comment by xiaohuiL** [comment]
@648540858 作者大大，有空可以回复一下吗？

**Comment by 648540858** [comment]
有可能是设备不支持预置位查询，你需要抓包确认下

**Comment by xiaohuiL** [comment]
> 有可能是设备不支持预置位查询，你需要抓包确认下

抓包查看没有response返回。但是我把球机挂载到硬盘录像机时候就可以查询到了。

**Comment by 648540858** [comment]
那就你的设备不支持国标的查询，但是与nvr链接使用了onvif或者私有协议是支持的，所有通过nvr查询可以查询到。

**Comment by xiaohuiL** [comment]
> 但是与nvr链接使用了onvif或者私有协议是支持的

好的，多谢回复

**Comment by criver31** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/54142345/a72ac16b-20ef-42c1-a9b6-ade48cedbab8)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/54142345/69cf43b8-bfa5-4ee8-8951-8cac0da69c3e)

信令正常，但是日志回复超时；在resultHolder.invokeResult时发生全局异常，请问是为什么
