### ISSUE TITLE
BUG 请求头带token， SecurityUtils 获取用户id 一直为0

### ISSUE THREAD

**Issue by luhengyu1** [648540858/wvp-GB28181-pro#1195]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/c8fe8491-8d86-437e-940e-dc6a4fc262d9)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/1e9fcb39-bc21-4213-919d-418802771697)

虽然登录的时候正确设置了SecurityContextHolder.getContext().setAuthentication(token);
但是每次经过过滤器都会再设置一遍，没看出来是为什么这么处理，这边只处理了username，password（置空）以及roleId，其他字段就丢失了，包括userId

**Comment by luhengyu1** [comment]
不清楚是否有别的token策略

**Comment by 648540858** [comment]
没有，你可以提pr完善一下。做的比较粗糙
