### ISSUE TITLE
BUG 更新最新代码后启动zlm一个小时会频繁掉线，内外网两套都是，重启wvp才行

### ISSUE THREAD

**Issue by qimingkunnanzheng** [648540858/wvp-GB28181-pro#1197]
**环境信息:**

 - 1. 部署方式  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境  centos ...
 - 3. 端口开放情况 全部开放
 - 4. 是否是公网部署  内网公网都部署了一套
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
 - 最新代码

**描述错误**
描述下您遇到的问题
启动后一个小时不到就会zlm掉线，然后重启wvp就可以了，然后就过段时间又会掉线
![image](https://github.com/648540858/wvp-GB28181-pro/assets/144506949/9ee15190-747c-40fb-8ca5-f59e74882675)

**如何复现**
更新最新代码

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
注意下你的部署方式，目前看日志是收到zlm的心跳hook
