### ISSUE TITLE
[技术咨询]  国标录像 视频无法暂停 点击暂停没有效果

### ISSUE THREAD

**Issue by WalkerPlus** [648540858/wvp-GB28181-pro#1199]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 > wvp-pro 编译 zlm docker 
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 > 否
 - 5. 是否使用https
> 否
 - 6. 方便的话提供下使用的设备品牌或平台
 > 海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
 > 最新

**描述错误**
描述下您遇到的问题
> 国标录像 视频无法暂停 点击暂停没有效果

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

![image](https://github.com/648540858/wvp-GB28181-pro/assets/16448447/52c73a64-9684-4d3c-998f-8ffc97aafd63)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
如果暂停无效，那么有可能是你的设备不支持

**Comment by WalkerPlus** [comment]
> 如果暂停无效，那么有可能是你的设备不支持
我用其他国标平台可以暂停播放

**Comment by 648540858** [comment]
抓个其他平台的包和wvp对比下

**Comment by 648540858** [comment]
另外你确定你点击的是暂停的按钮？你页面那不是点击的播放吗

**Comment by 648540858** [comment]
播放器的播放和暂停和国标的播放暂停是两回事，别搞错了了

**Comment by WalkerPlus** [comment]
> 播放器的播放和暂停和国标的播放暂停是两回事，别搞错了了

这个有区别吗，那几个按钮我都试了么就是暂停不了

**Comment by 648540858** [comment]
当然有区别，播放和暂停怎么会一样，下面的播放暂停是给设备发消息让设备暂停发流来实现暂停，上面是播放器本身的暂停，设备发流是不停止的

**Comment by WalkerPlus** [comment]
> 当然有区别，播放和暂停怎么会一样，下面的播放暂停是给设备发消息让设备暂停发流来实现暂停，上面是播放器本身的暂停，设备发流是不停止的

我连个按钮都是了，都暂停不了，是什么原因

**Comment by 648540858** [comment]
你得设备不支持暂停发流。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月18日(周一) 上午10:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] [技术咨询]  国标录像 视频无法暂停 点击暂停没有效果 (Issue #1199)




  
当然有区别，播放和暂停怎么会一样，下面的播放暂停是给设备发消息让设备暂停发流来实现暂停，上面是播放器本身的暂停，设备发流是不停止的
  
我连个按钮都是了，都暂停不了，是什么原因

**Comment by 648540858** [comment]
如果你自己都不愿意梳理思路和逻辑，那么你得问题我没办法回答你。你不要想着直接丢问题给我，我来帮你解决，解决问题是需要咱们一起去找原因一步步来的。这里就只能帮你到这里了，如果扔有问题，请清晰完整的描述你的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月18日(周一) 上午10:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] [技术咨询]  国标录像 视频无法暂停 点击暂停没有效果 (Issue #1199)




  
当然有区别，播放和暂停怎么会一样，下面的播放暂停是给设备发消息让设备暂停发流来实现暂停，上面是播放器本身的暂停，设备发流是不停止的
  
我连个按钮都是了，都暂停不了，是什么原因
