### ISSUE TITLE
开启音频按钮是否能默认开启

### ISSUE THREAD

**Issue by cwy1996** [648540858/wvp-GB28181-pro#1201]
**环境信息:**

 - 1. 部署方式：wvp-pro docker / zlm(docker)
 - 2. 部署环境：ubuntu
 - 3. 端口开放情况：开放
 - 4. 是否是公网部署：公网
 - 5. 是否使用https：使用
 - 6. 方便的话提供下使用的设备品牌或平台：海康

**内容描述:**
平台通道内，开启音频按钮能否设置为设备接入即开启，而不是接入一个需要人为点击开启

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/76695859/a7de759c-e9d8-46ab-aa27-106da6073d9b)

**Comment by 648540858** [comment]
没有这个打算，实际项目中不使用音频的居多，需要的自己手动开启
