### ISSUE TITLE
[技术咨询] 按需推流stream-on-demand:false 没有效果

### ISSUE THREAD

**Issue by WalkerPlus** [648540858/wvp-GB28181-pro#1203]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 > wvp-pro 编译 zlm(docker)
 - 2. 部署环境 windows / ubuntu/ centos ...
 > ubuntu
 - 3. 端口开放情况
 > 全部
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
 > 最新

**内容描述:**
stream-on-demand 设置成false, 视频实时预览的时候还是会过一段时间就转圈  看了zlm日志
34020000001320000201_34020000001320000201(192.168.20.201:15060) RTP推流器(__defaultVhost__/rtp/34020000001320000201_34020000001320000201)断开,耗时(s):79
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/16448447/447dcc34-3e89-4fb7-a3c3-eab48be4e1a7)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by WalkerPlus** [comment]
连接的NVR

**Comment by 648540858** [comment]
你的截图和你说的按需播放没有关系吧，播放器播放不了，你可以测试下 
1. 把rtsp流复制出来用vlc或者ffplay播放下，看看能不能播放
2. 看看摄像机的配置了视频分辨率配置是否太高了导致网页播放器解析不了
