### ISSUE TITLE
[BUG] 前端状态展示错误

### ISSUE THREAD

**Issue by GQ-Y** [648540858/wvp-GB28181-pro#1204]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
用前端单独运行，在config/index.js中填的服务器上的API地址，登陆、获取数据、很多接口调用都一切正常。
但设备的在线状态异常，全部都显示离线状态(实际为在线)
调用刷新报500错误
{"code":500,"msg":"Request method 'GET' not supported"}

**如何复现**
本地调用后端的API服务地址就会出现这个情况
使用非分离部署的方式则正常
**截图**  
<img width="1006" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/26402141/3d83157f-377e-4990-b898-7a6c64d86fae">
<img width="1271" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/26402141/b5c30a22-d1a6-431a-b64a-bc5573ef2d8b">

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by GQ-Y** [comment]
1

**Comment by GQ-Y** [comment]
`<div slot="reference" class="name-wrapper">
            <el-tag size="medium" v-if="scope.row.onLine">在线</el-tag>
            <el-tag size="medium" type="info" v-if="!scope.row.onLine">离线</el-tag>`
上面的字段错了，应该是online，作者大大有时间可以修复下，最新版2.8.9的前端文件中

**Comment by 648540858** [comment]
你直接提个pr吧，以后也可以一起参与进来
