### ISSUE TITLE
是否有计划新增sqlite的数据源支持

### ISSUE THREAD

**Issue by iwanlebron** [648540858/wvp-GB28181-pro#1206]
**项目的详细需求**
新增sqlite的数据源支持

**这样的实现什么作用**
实现轻量化部署

**Comment by iwanlebron** [comment]
或者支持多数据源支持的计划，如mongodb

**Comment by 648540858** [comment]
暂时不打算了，以前支持后来去掉了，并发写入有问题。以后如果可以解决这个问题会考虑再加回来



---原始邮件---
发件人: "Iwan ***@***.***&gt;
发送时间: 2023年12月13日(周三) 上午9:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [648540858/wvp-GB28181-pro] 是否有计划新增sqlite的数据源支持 (Issue #1206)




 
项目的详细需求
 新增sqlite的数据源支持
 
这样的实现什么作用
 实现轻量化部署

**Comment by iwanlebron** [comment]
是否支持GaussDB？

**Comment by 648540858** [comment]
不支持



---原始邮件---
发件人: "Iwan ***@***.***&gt;
发送时间: 2023年12月13日(周三) 上午9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] 是否有计划新增sqlite的数据源支持 (Issue #1206)




 
是否支持GaussDB？

**Comment by 648540858** [comment]
第一次听说，以后有需求可以了加



---原始邮件---
发件人: "Iwan ***@***.***&gt;
发送时间: 2023年12月13日(周三) 上午9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] 是否有计划新增sqlite的数据源支持 (Issue #1206)




 
是否支持GaussDB？

**Comment by iwanlebron** [comment]
从mysql改到sqlite成本大吗 是否可以

**Comment by iwanlebron** [comment]
国产化项目 需要用到GaussDB

**Comment by 648540858** [comment]
> 从mysql改到sqlite成本大吗 是否可以

并发写入有问题

**Comment by iwanlebron** [comment]
mongodb的改造是否可以

**Comment by 648540858** [comment]
你能提供数据库服务器的话，那么可以加一下。着急的话可以定制。不着急就提供服务器我找时间加一下

**Comment by iwanlebron** [comment]
服务器倒是有 都在公司内网环境  有点着急 需要交付  定制需要怎么做

**Comment by iwanlebron** [comment]
可以提供mongo服务器 怎么发给您呢

**Comment by 648540858** [comment]
留个微信我加你。



---原始邮件---
发件人: "Iwan ***@***.***&gt;
发送时间: 2023年12月13日(周三) 上午10:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] 是否有计划新增sqlite的数据源支持 (Issue #1206)




 
服务器倒是有 都在公司内网环境  有点着急 需要交付  定制需要怎么做

**Comment by iwanlebron** [comment]
iwanlebron

**Comment by 648540858** [comment]
加你了

**Comment by iwanlebron** [comment]
没收到啊 要不试试这个 19818978641

**Comment by 648540858** [comment]
你再看看



---原始邮件---
发件人: "Iwan ***@***.***&gt;
发送时间: 2023年12月13日(周三) 下午5:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] 是否有计划新增sqlite的数据源支持 (Issue #1206)




 
没收到啊 要不试试这个 19818978641
