### ISSUE TITLE
BUG 拉流代理启用状态下调用启用接口的返回错误

### ISSUE THREAD

**Issue by DavidSche** [648540858/wvp-GB28181-pro#1208]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 -     编译部署
 - 2. 部署环境 windows / ubuntu/ centos ...
 -      centos
 - 3. 端口开放情况
 - 
 - 4. 是否是公网部署 
 -    否
 - 5. 是否使用https
 -  是
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题

   添加拉流代理并启用后，调用 /api/proxy/start 接口 ，返回 {
  "code": 100,
  "msg": "失败"
} 

该接口代码没有处理拉流代理为启用状态的情况，参见截图

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/99fee855-5fed-4f88-9039-6441a6a9c3f3)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
多谢PR
