### ISSUE TITLE
在多端口模式下，如何复用端口？

### ISSUE THREAD

**Issue by qiaoshubin** [648540858/wvp-GB28181-pro#121]
我在配置文件里面启用了多端口模式，范围是30000-30500。然后在使用中发现，每打开一次摄像头视频，端口会加2，然后一直到30490以上，就可能报错。请问下，这种情况下如何复用端口，毕竟端口数量有限，不可能一直增加。

**Comment by 648540858** [comment]
多端口模式本身的作用就是使用端口作为区分一路流的依据，如果一个端口多路流，也就失去了多端口的意义了，
再者：到了30490以上，那就说明的你配置的并发到上限了。你该多开端口了，不用的端口会自动释放的。
如果你的流足够标准，你可以使用单端口模式，就没有你说的限制了。
