### ISSUE TITLE
[技术咨询] 返回的rtsp流，经常性的打不开，偶尔是正常的，通过http可以正常播放，

### ISSUE THREAD

**Issue by xiaofeixuan** [648540858/wvp-GB28181-pro#1213]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
通过返回的rtsp流，使用播放器播放，经常会出现打不开的情况，提示该流无法访问，偶尔又是正常的，不稳定，
通过http   flv格式的是可以正常播放的，

**如何复现**
播放过程中时好时坏

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/25632963/b26c9a68-4348-44db-8ebf-af9e797587aa)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你这是用什么播放的，用ffplay播放时时，zlm很稳定的
