### ISSUE TITLE
[技术咨询] 7*24小时录像

### ISSUE THREAD

**Issue by xun-feng** [648540858/wvp-GB28181-pro#1215]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ... centos7
 - 3. 端口开放情况 全部开放
 - 4. 是否是公网部署  是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台  海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 最新代码

问题：
     你好，我想咨询一下，7*24录像，他的录像是每过几十秒就生成一个MP4文件吗，还是和宽带有关系，我目前就是几十秒就生成了一个文件，播放还是断断续续的，延时比较严重

<img width="166" alt="1702607209543" src="https://github.com/648540858/wvp-GB28181-pro/assets/76140275/dbe8935a-e8e7-4890-872b-f8e3d73d28dc">

**Comment by mengxing2017** [comment]
这是nvr的录像吧

**Comment by 648540858** [comment]
截图全一点，国标录像与wvp无关，如果是云端录像那么你需要zlm日志是因为什么断开的流
