### ISSUE TITLE
BUG 海康nvr注册成功但是通道数为0

### ISSUE THREAD

**Issue by kangxiaojia0** [648540858/wvp-GB28181-pro#1220]
**环境信息:**

 - 1. 部署方式 docker部署
 - 2. 部署环境 windows 
 - 3. 端口开放情况 全部开放
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 最新代码

**描述错误**
海康nvr接入后注册成功但是通道数为0,同网络下摄像头可正常注册及播放。点击刷新时摄像头可正常刷新。但是nvr刷新失败

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![4d76eb5c181cb3a626b4342be69c918](https://github.com/648540858/wvp-GB28181-pro/assets/59348536/3ef86e4d-f224-4992-b05b-0cb65de24b36)
![6c680c3804277e8cb584278d38aded3](https://github.com/648540858/wvp-GB28181-pro/assets/59348536/3b659ae9-618f-44e0-aed9-7b4263f1ee47)
![126053deffa3861fde75b82a2c7386c](https://github.com/648540858/wvp-GB28181-pro/assets/59348536/6365b1e2-6a7d-414b-a8ce-386b3a02b510)
![a8ab530eb9c0fca73a091368dab66d4](https://github.com/648540858/wvp-GB28181-pro/assets/59348536/5371bc6d-66e3-446c-b83a-1cc2b44549a7)
![f564c6ba3afcb1b935d298b76f5ad83](https://github.com/648540858/wvp-GB28181-pro/assets/59348536/55f7efe0-e22f-4f04-8874-4646ec7e9a02)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
docker部署的，是自己打包的还是用的作者的？作者的是两三年前的已经不维护了

**Comment by kangxiaojia0** [comment]
> docker部署的，是自己打包的还是用的作者的？作者的是两三年前的已经不维护了

自己打包的

**Comment by kangxiaojia0** [comment]
现在把wvp移除出来了,sip.ip填写为0.0.0.0时nvr可以注册，但是没有通道。把sip.ip改成内网ip的时候可以正常获取通道了。但是外网部署的时候sip.ip填写0.0.0.0 和 内网ip都获取不到通道，改成外网ip无法启动

**Comment by 648540858** [comment]
docker使用host模式试过吗
