### ISSUE TITLE
ZLM节点不能重连

### ISSUE THREAD

**Issue by asd123wto** [648540858/wvp-GB28181-pro#1221]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 正常
 - 4. 是否是公网部署  是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 11月

**描述错误**
过段时间 wvp里ZLM的节点就变成离线，可能是网络问题，但是它不能重新连接吗？只有手动重启了wvp就正常了

**Comment by 648540858** [comment]
目前掉线后需要再次收到zlm的心跳或者上线hook后上线

**Comment by asd123wto** [comment]
那我是不是应该在zml的timeoutSec增大hook超时时间呢？

**Comment by asd123wto** [comment]
![QQ截图20231228191533](https://github.com/648540858/wvp-GB28181-pro/assets/31847062/09a2f42b-3370-4c4c-84b1-93b706d98cec)
我看zlm还在试图连接wvp，但wvp没有打印日志，管理页面只显示离线。重启wvp服务就好了，这是咋回事呢？

**Comment by criver31** [comment]
> 目前掉线后需要再次收到zlm的心跳或者上线hook后上线
模拟wvp与zlm之间网络断开，恢复后zlm依旧是离线：
阻止zlm向wvp keepalive

```shell
iptables -I INPUT -s `zlm.ip` -ptcp --dport `wvp.port` -j DROP
```

阻止wvp向zlm getServerConfig

```shell
iptables -I INPUT -s `wvp.ip` -ptcp --dport `zlm.port` -j DROP
```

恢复连接：-D参数

**Comment by criver31** [comment]
可能找到原因了，重新发送心跳后，在updateMediaServerKeepalive方法中未对redis中key为MEDIA_SERVERS_ONLINE_PREFIX的set添加该zlm，需要添加resetOnlineServerItem方法。

> 目前掉线后需要再次收到zlm的心跳或者上线hook后上线
