### ISSUE TITLE
技术咨询：是否可以使用docker部署wvp+zlm？

### ISSUE THREAD

**Issue by iwanlebron** [648540858/wvp-GB28181-pro#1222]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
可以，自己打包就行

**Comment by iwanlebron** [comment]
是否有案例可以提供一下

**Comment by mengxing2017** [comment]
https://github.com/SaltFish001/wvp_pro_compose  把这个维护起来

**Comment by iwanlebron** [comment]
是否可以使用k8s部署

**Comment by iwanlebron** [comment]
主要涉及到一个rtp端口范围的问题

**Comment by xu-bin-bin** [comment]
可以使用k8s部署，不过我们目前使用的是单端口方式
