### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by 9loki** [648540858/wvp-GB28181-pro#1223]
**环境信息:**
ZLMediaKit CentOS7 3.10.0-1160.el7.x86_64
WVP-GB28181-PRO Windows10
 - 1. 部署方式 均为编译部署
 - 2. 部署环境 centos7 和 windows10
 - 3. 端口开放情况 防火墙关闭
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 大华
 - 7. 你做过哪些尝试 开放端口，根据wiki，issues修改配置

**内容描述:**
摄像头能够自动注册到wvp中，并且也能够刷新，但是点播会出现收流超时的错误
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/117706410/2ab12039-4717-4a47-8425-6e7ae7defbf7)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/117706410/5daece34-ed3a-4e84-8b28-8b33ef4f3afa)

**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
sdp-ip是 zlm的地址吗？虚拟机的话，网络是不是桥接网络？

**Comment by 9loki** [comment]
> sdp-ip是 zlm的地址吗？虚拟机的话，网络是不是桥接网络？

我的wvp是部署在windows上，直接用idea启动的，是本机的ip，虚拟机是NAT网络

**Comment by mengxing2017** [comment]
nat网络，你的摄像头怎么访问的zlm？

**Comment by mengxing2017** [comment]
想推流也推不到流

**Comment by 9loki** [comment]
> nat网络，你的摄像头怎么访问的zlm？

但是在idea的日志打印了流媒体服务器上线了，然后摄像头也都注册到wvp上了

**Comment by mengxing2017** [comment]
你这个跟我说的有关系吗？wvp可不管流媒体的活，wvp是信令服务器，摄像头推流是推给zlm的，不是推给wvp的

**Comment by 9loki** [comment]
> 你这个跟我说的有关系吗？wvp可不管流媒体的活，wvp是信令服务器，摄像头推流是推给zlm的，不是推给wvp的
换成桥接的了，根据固定地址是可以看的，但是用国标就不行了

**Comment by mengxing2017** [comment]
sdp-ip,stream-ip地址是zlm的地址吗，hook-ip是wvp的地址吗？固定地址是拉流吧。拉流的工作机制跟国标不一样的，国标是推流

**Comment by 9loki** [comment]
> sdp-ip,stream-ip地址是zlm的地址吗，hook-ip是wvp的地址吗？固定地址是拉流吧。拉流的工作机制跟国标不一样的，国标是推流

都是zlm的地址，不过ZLM进行gb28181的推流的话，ffmpeg的命令行需要改吗，我查阅了网上的资料，看到的只是对zlk的一些端口进行更改以及MediaServerId的修改

**Comment by mengxing2017** [comment]
ffmpeg只是影响截图而已，不影响播放视频

**Comment by 9loki** [comment]
> ffmpeg只是影响截图而已，不影响播放视频

兄弟，感谢你，终于弄出来了，我的hookip没写对，然后改了hookip，发现rtp的收流端口又没开够，终于调通了

**Comment by 5488464aini** [comment]
> > ffmpeg只是影响截图而已，不影响播放视频
> 
> 兄弟，感谢你，终于弄出来了，我的hookip没写对，然后改了hookip，发现rtp的收流端口又没开够，终于调通了

兄弟，我也是这个问题，我的收流超时。。。所有的ip我都是写的本机ip，zlm在docker运行的，wvp在idea运行的

**Comment by 5488464aini** [comment]
> > > ffmpeg只是影响截图而已，不影响播放视频
> > 
> > 
> > 兄弟，感谢你，终于弄出来了，我的hookip没写对，然后改了hookip，发现rtp的收流端口又没开够，终于调通了
> 
> 兄弟，我也是这个问题，我的收流超时。。。所有的ip我都是写的本机ip，zlm在docker运行的，wvp在idea运行的

怎么解决啊

**Comment by 9loki** [comment]
> > > > ffmpeg只是影响截图而已，不影响播放视频
> > > 
> > > 
> > > 兄弟，感谢你，终于弄出来了，我的hookip没写对，然后改了hookip，发现rtp的收流端口又没开够，终于调通了
> > 
> > 
> > 兄弟，我也是这个问题，我的收流超时。。。所有的ip我都是写的本机ip，zlm在docker运行的，wvp在idea运行的
> 
> 怎么解决啊

我是这样的，wvp监听的ip要为本地ip地址，不能为0.0.0.0，然后windows的防火墙关闭了，然后linux上防火墙开启对应的端口，如果你是docker上部署的zlm，那应该要映射出来，本地的docker我不确定摄像头的流能推过来，你可以抓下sip包，看看设备有没有注册，然后抓rtp包，看看摄像头有没有推流到zlk上

**Comment by 5488464aini** [comment]
> > > > > ffmpeg只是影响截图而已，不影响播放视频
> > > > 
> > > > 
> > > > 兄弟，感谢你，终于弄出来了，我的hookip没写对，然后改了hookip，发现rtp的收流端口又没开够，终于调通了
> > > 
> > > 
> > > 兄弟，我也是这个问题，我的收流超时。。。所有的ip我都是写的本机ip，zlm在docker运行的，wvp在idea运行的
> > 
> > 
> > 怎么解决啊
> 
> 我是这样的，wvp监听的ip要为本地ip地址，不能为0.0.0.0，然后windows的防火墙关闭了，然后linux上防火墙开启对应的端口，如果你是docker上部署的zlm，那应该要映射出来，本地的docker我不确定摄像头的流能推过来，你可以抓下sip包，看看设备有没有注册，然后抓rtp包，看看摄像头有没有推流到zlk上
这种怎么看呢？本机ip是192.168.0.244，设备是大华的nvr，ip是192.168.0.2

![image](https://github.com/648540858/wvp-GB28181-pro/assets/105351340/db4955d3-d0e4-46c6-be04-d0fa76364c79)

**Comment by 9loki** [comment]
> > > > > > ffmpeg只是影响截图而已，不影响播放视频
> > > > > 
> > > > > 
> > > > > 兄弟，感谢你，终于弄出来了，我的hookip没写对，然后改了hookip，发现rtp的收流端口又没开够，终于调通了
> > > > 
> > > > 
> > > > 兄弟，我也是这个问题，我的收流超时。。。所有的ip我都是写的本机ip，zlm在docker运行的，wvp在idea运行的
> > > 
> > > 
> > > 怎么解决啊
> > 
> > 
> > 我是这样的，wvp监听的ip要为本地ip地址，不能为0.0.0.0，然后windows的防火墙关闭了，然后linux上防火墙开启对应的端口，如果你是docker上部署的zlm，那应该要映射出来，本地的docker我不确定摄像头的流能推过来，你可以抓下sip包，看看设备有没有注册，然后抓rtp包，看看摄像头有没有推流到zlk上
> > 这种怎么看呢？本机ip是192.168.0.244，设备是大华的nvr，ip是192.168.0.2
> 
> ![image](https://private-user-images.githubusercontent.com/105351340/295857389-db4955d3-d0e4-46c6-be04-d0fa76364c79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjQ5MzgsIm5iZiI6MTcwNDk2NDYzOCwicGF0aCI6Ii8xMDUzNTEzNDAvMjk1ODU3Mzg5LWRiNDk1NWQzLWQwZTQtNDZjNi1iZTA0LWQwZmE3NjM2NGM3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwOTE3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTk1YmE3ZWY3ODg0ZjViZDExNDY2OGUwMDAxNjAzNmNmMDljZGM4OWJmZTZkYTBlYWU1MDI1ZDBlNjFkNmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fHlmKRJ1v52_FrbDPsvnrwnQBzZp2xOBWxauyzvNGH4)

收流超时应该就是摄像头没办法把流送到zlk那边，估计是网络问题，你可以尝试找台公网服务器，或者桥接模式的虚拟机在布个zlm，我不确定本地装的docker能不能接收到摄像头传来的包

**Comment by 5488464aini** [comment]
> > > > > > > ffmpeg只是影响截图而已，不影响播放视频
> > > > > > 
> > > > > > 
> > > > > > 兄弟，感谢你，终于弄出来了，我的hookip没写对，然后改了hookip，发现rtp的收流端口又没开够，终于调通了
> > > > > 
> > > > > 
> > > > > 兄弟，我也是这个问题，我的收流超时。。。所有的ip我都是写的本机ip，zlm在docker运行的，wvp在idea运行的
> > > > 
> > > > 
> > > > 怎么解决啊
> > > 
> > > 
> > > 我是这样的，wvp监听的ip要为本地ip地址，不能为0.0.0.0，然后windows的防火墙关闭了，然后linux上防火墙开启对应的端口，如果你是docker上部署的zlm，那应该要映射出来，本地的docker我不确定摄像头的流能推过来，你可以抓下sip包，看看设备有没有注册，然后抓rtp包，看看摄像头有没有推流到zlk上
> > > 这种怎么看呢？本机ip是192.168.0.244，设备是大华的nvr，ip是192.168.0.2
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/105351340/295857389-db4955d3-d0e4-46c6-be04-d0fa76364c79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjQ5MzgsIm5iZiI6MTcwNDk2NDYzOCwicGF0aCI6Ii8xMDUzNTEzNDAvMjk1ODU3Mzg5LWRiNDk1NWQzLWQwZTQtNDZjNi1iZTA0LWQwZmE3NjM2NGM3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwOTE3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTk1YmE3ZWY3ODg0ZjViZDExNDY2OGUwMDAxNjAzNmNmMDljZGM4OWJmZTZkYTBlYWU1MDI1ZDBlNjFkNmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fHlmKRJ1v52_FrbDPsvnrwnQBzZp2xOBWxauyzvNGH4)
> 
> 收流超时应该就是摄像头没办法把流送到zlk那边，估计是网络问题，你可以尝试找台公网服务器，或者桥接模式的虚拟机在布个zlm，我不确定本地装的docker能不能接收到摄像头传来的包

兄弟，我现在换了一个zlm，然后没有出现收流超时了，播放框也能弹出来了，但是现在出现了流未找到是什么原因呢？
![1705030369391](https://github.com/648540858/wvp-GB28181-pro/assets/105351340/1cbee6a2-d166-401b-9800-5647400d097d)

**Comment by 9loki** [comment]
> > > > > > > > ffmpeg只是影响截图而已，不影响播放视频
> > > > > > > 
> > > > > > > 
> > > > > > > 兄弟，感谢你，终于弄出来了，我的hookip没写对，然后改了hookip，发现rtp的收流端口又没开够，终于调通了
> > > > > > 
> > > > > > 
> > > > > > 兄弟，我也是这个问题，我的收流超时。。。所有的ip我都是写的本机ip，zlm在docker运行的，wvp在idea运行的
> > > > > 
> > > > > 
> > > > > 怎么解决啊
> > > > 
> > > > 
> > > > 我是这样的，wvp监听的ip要为本地ip地址，不能为0.0.0.0，然后windows的防火墙关闭了，然后linux上防火墙开启对应的端口，如果你是docker上部署的zlm，那应该要映射出来，本地的docker我不确定摄像头的流能推过来，你可以抓下sip包，看看设备有没有注册，然后抓rtp包，看看摄像头有没有推流到zlk上
> > > > 这种怎么看呢？本机ip是192.168.0.244，设备是大华的nvr，ip是192.168.0.2
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/105351340/295857389-db4955d3-d0e4-46c6-be04-d0fa76364c79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjQ5MzgsIm5iZiI6MTcwNDk2NDYzOCwicGF0aCI6Ii8xMDUzNTEzNDAvMjk1ODU3Mzg5LWRiNDk1NWQzLWQwZTQtNDZjNi1iZTA0LWQwZmE3NjM2NGM3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwOTE3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTk1YmE3ZWY3ODg0ZjViZDExNDY2OGUwMDAxNjAzNmNmMDljZGM4OWJmZTZkYTBlYWU1MDI1ZDBlNjFkNmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fHlmKRJ1v52_FrbDPsvnrwnQBzZp2xOBWxauyzvNGH4)
> > 
> > 
> > 收流超时应该就是摄像头没办法把流送到zlk那边，估计是网络问题，你可以尝试找台公网服务器，或者桥接模式的虚拟机在布个zlm，我不确定本地装的docker能不能接收到摄像头传来的包
> 
> 兄弟，我现在换了一个zlm，然后没有出现收流超时了，播放框也能弹出来了，但是现在出现了流未找到是什么原因呢？ ![1705030369391](https://private-user-images.githubusercontent.com/105351340/296118987-1cbee6a2-d166-401b-9800-5647400d097d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDAyMTYsIm5iZiI6MTcwNTAzOTkxNiwicGF0aCI6Ii8xMDUzNTEzNDAvMjk2MTE4OTg3LTFjYmVlNmEyLWQxNjYtNDAxYi05ODAwLTU2NDc0MDBkMDk3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNjExNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTg3YjAzN2JmOGRhN2UzNmFhZTIzMDRiMWI4NzJkYWRjMmQ4NWUwOGE0NjA1MTIxMDRjOGIyODg1NzE0YmI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JuhBg0ocKLCpTs5pXE4WLV9EWCXTg03vNPaw3nMPyZY)

这我也不知道了，一般流注册了就能播了，我也是新手，这个问题我没遇到过，不好意思

**Comment by gaowei0217** [comment]
> > > > > > > > ffmpeg只是影响截图而已，不影响播放视频
> > > > > > > 
> > > > > > > 
> > > > > > > 兄弟，感谢你，终于弄出来了，我的hookip没写对，然后改了hookip，发现rtp的收流端口又没开够，终于调通了
> > > > > > 
> > > > > > 
> > > > > > 兄弟，我也是这个问题，我的收流超时。。。所有的ip我都是写的本机ip，zlm在docker运行的，wvp在idea运行的
> > > > > 
> > > > > 
> > > > > 怎么解决啊
> > > > 
> > > > 
> > > > 我是这样的，wvp监听的ip要为本地ip地址，不能为0.0.0.0，然后windows的防火墙关闭了，然后linux上防火墙开启对应的端口，如果你是docker上部署的zlm，那应该要映射出来，本地的docker我不确定摄像头的流能推过来，你可以抓下sip包，看看设备有没有注册，然后抓rtp包，看看摄像头有没有推流到zlk上
> > > > 这种怎么看呢？本机ip是192.168.0.244，设备是大华的nvr，ip是192.168.0.2
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/105351340/295857389-db4955d3-d0e4-46c6-be04-d0fa76364c79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjQ5MzgsIm5iZiI6MTcwNDk2NDYzOCwicGF0aCI6Ii8xMDUzNTEzNDAvMjk1ODU3Mzg5LWRiNDk1NWQzLWQwZTQtNDZjNi1iZTA0LWQwZmE3NjM2NGM3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwOTE3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTk1YmE3ZWY3ODg0ZjViZDExNDY2OGUwMDAxNjAzNmNmMDljZGM4OWJmZTZkYTBlYWU1MDI1ZDBlNjFkNmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fHlmKRJ1v52_FrbDPsvnrwnQBzZp2xOBWxauyzvNGH4)
> > 
> > 
> > 收流超时应该就是摄像头没办法把流送到zlk那边，估计是网络问题，你可以尝试找台公网服务器，或者桥接模式的虚拟机在布个zlm，我不确定本地装的docker能不能接收到摄像头传来的包
> 
> 兄弟，我现在换了一个zlm，然后没有出现收流超时了，播放框也能弹出来了，但是现在出现了流未找到是什么原因呢？ ![1705030369391](https://private-user-images.githubusercontent.com/105351340/296118987-1cbee6a2-d166-401b-9800-5647400d097d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDg1MjcsIm5iZiI6MTcwNTA0ODIyNywicGF0aCI6Ii8xMDUzNTEzNDAvMjk2MTE4OTg3LTFjYmVlNmEyLWQxNjYtNDAxYi05ODAwLTU2NDc0MDBkMDk3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwODMwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWVjZTc5MDMxYzVkZDA4Zjc5NDdlY2QwNTlmNTIyZGIyMTg2NzRjNjE3OTFmNGE0ZjJkMjExMzc4MTA0NmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yu6ma79FIm9AyeIeHgI-UZtgfY1-B1Y-edl8YANw9u0)

兄弟，能看下你的application.yaml 配置吗

**Comment by 5488464aini** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月12日(周五) 下午4:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] 技术咨询 (Issue #1223)




         
ffmpeg只是影响截图而已，不影响播放视频
  
兄弟，感谢你，终于弄出来了，我的hookip没写对，然后改了hookip，发现rtp的收流端口又没开够，终于调通了
  
兄弟，我也是这个问题，我的收流超时。。。所有的ip我都是写的本机ip，zlm在docker运行的，wvp在idea运行的
  
怎么解决啊
  
我是这样的，wvp监听的ip要为本地ip地址，不能为0.0.0.0，然后windows的防火墙关闭了，然后linux上防火墙开启对应的端口，如果你是docker上部署的zlm，那应该要映射出来，本地的docker我不确定摄像头的流能推过来，你可以抓下sip包，看看设备有没有注册，然后抓rtp包，看看摄像头有没有推流到zlk上
 这种怎么看呢？本机ip是192.168.0.244，设备是大华的nvr，ip是192.168.0.2
  

  
收流超时应该就是摄像头没办法把流送到zlk那边，估计是网络问题，你可以尝试找台公网服务器，或者桥接模式的虚拟机在布个zlm，我不确定本地装的docker能不能接收到摄像头传来的包
  
兄弟，我现在换了一个zlm，然后没有出现收流超时了，播放框也能弹出来了，但是现在出现了流未找到是什么原因呢？ 
  
兄弟，能看下你的application.yaml 配置吗
