### ISSUE TITLE
希望wVP实现的新功能，此功能应与你的具体业务无关

### ISSUE THREAD

**Issue by pkxutao** [648540858/wvp-GB28181-pro#1225]
**项目的详细需求**
兄弟，可以更新下docker镜像么？
**这样的实现什么作用**
https://hub.docker.com/r/648540858/wvp_pro

**Comment by mengxing2017** [comment]
作者没有精力维护，你可以把这个维护起来  https://github.com/SaltFish001/wvp_pro_compose
