### ISSUE TITLE
技术咨询-点播报错误

### ISSUE THREAD

**Issue by paddy0615** [648540858/wvp-GB28181-pro#1228]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

这是什么错误？？？

![image](https://github.com/648540858/wvp-GB28181-pro/assets/43235179/8abe44c4-43f5-42da-8038-bfa43e53d0f6)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/43235179/a672c4c0-db60-435f-9411-fa6021748b02)

**Comment by aidelingyu** [comment]
抓包看下sip报文，可能是消息体格式有问题，解析不了

**Comment by paddy0615** [comment]
是的，发现设备没有回复通道信息。

另一个问题，怎么能一直点播？




庞德志
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月26日(星期二) 下午3:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro] 技术咨询-点播报错误 (Issue #1228)





 
抓包看下sip报文，可能是消息体格式有问题，解析不了

**Comment by aidelingyu** [comment]
设备注册后可以主动去查询设备的通道信息。一直点播是说明意思？就是一直看？点播了就可以一直看的吧
