### ISSUE TITLE
技术咨询  请问抓包后如何播放

### ISSUE THREAD

**Issue by Marhoosh** [648540858/wvp-GB28181-pro#1229]
**内容描述:**
在tcp被动模式下，tcpdump抓包后的视频文件不知道该如何播放。

**你做过哪些尝试**
1.若是使用udp，抓下来的包wireshark还能识别出rtp包，并通过老版本的wireshark另存为raw格式后，可以使用ffplay播放
2.但是使用tcp被动模式时，抓下来的包wireshark便识别不出哪些是rtp包了，播放不了。

**Comment by 648540858** [comment]
你可以使用tcp.port==sdp中的端口来过滤抓包，然后在抓包上右键，使用decode as ，然后当前下面选择rtp，确定后就可以识别到rtp包了

**Comment by bobo-chi** [comment]
老师好，请问sdp中的端口怎么看呢(*^▽^*)
