### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by pkxutao** [648540858/wvp-GB28181-pro#1231]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 编译wvp-pro
 - 2. 部署环境 windows / ubuntu/ centos ...
 - windows
 - 3. 端口开放情况
 - 全开放
 - 4. 是否是公网部署 
 - 否
 - 5. 是否使用https
 -  否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 修改各权限地方
 - 8. 代码更新时间

**描述错误**
配置好环境后，不改代码，直接在IDEA里运行，打开在线文档提示“Knife4j文档请求异常”，F12查看提示401，在代码里对v3/api-docs/swagger-config接口进行跳过授权依然不能成功

**如何复现**
不改代码直接运行，或docker运行都会报此错误

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/4133942/f22687aa-47bb-46cb-9555-04b4efbdf372)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
更新代码再试试，最近刚修复了

**Comment by pkxutao** [comment]
谢谢，已解决
