### ISSUE TITLE
国标级联时支持自定义通道ID

### ISSUE THREAD

**Issue by a24211317** [648540858/wvp-GB28181-pro#1232]
国标设备接入时 设备ID不同，但是存在相同通道ID时 在国标级联不能区分导致推送到上级时相同通道ID的会被覆盖掉。所以希望在国标级联时可以自定义通道ID以区分相同的通道。
<img width="715" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/49759199/9e21fc6b-31e3-4985-b734-917a4e4c2e96">
<img width="591" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/49759199/f8fe0006-93a5-467a-a511-bc022876966f">

**Comment by mengxing2017** [comment]
这个是规划的问题，通过行政手段解决吧

**Comment by xiaoQQya** [comment]
> 国标设备接入时 设备ID不同，但是存在相同通道ID时 在国标级联不能区分导致推送到上级时相同通道ID的会被覆盖掉。所以希望在国标级联时可以自定义通道ID以区分相同的通道。 <img alt="image" width="715" src="https://private-user-images.githubusercontent.com/49759199/293123343-9e21fc6b-31e3-4985-b734-917a4e4c2e96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDQyNjUsIm5iZiI6MTcwMzkwMzk2NSwicGF0aCI6Ii80OTc1OTE5OS8yOTMxMjMzNDMtOWUyMWZjNmItMzFlMy00OTg1LWI3MzQtOTE3YTRlNGMyZTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAyMzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNzRiZDFlNmM1ODhhOWQ3ZDU4NzZjYzQ3ODIwMzUwM2VmMDcxMTQ2ZTkzYTgyNGRhNDZhNTljN2Q2OTc1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uQUUw7aubUXT5vyL5WG-MJNUbK0_kbmUZ4JGpTMjjKw"> <img alt="image" width="591" src="https://private-user-images.githubusercontent.com/49759199/293123350-f8fe0006-93a5-467a-a511-bc022876966f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDQyNjUsIm5iZiI6MTcwMzkwMzk2NSwicGF0aCI6Ii80OTc1OTE5OS8yOTMxMjMzNTAtZjhmZTAwMDYtOTNhNS00NjdhLWE1MTEtYmMwMjI4NzY5NjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAyMzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxN2U0NjVjNmI1MGU1N2RmYTY3ZDNjMDA2ZWJmMzE0NDQyZDQ1ODZiMTJiNzU0Yzc1NzlmYWM1ZDVmOGI4MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F7R7DANGnZPmYEWqWReT4NlikWJxGp8kWQ0kwONKEKA">

我也遇到过同样的问题 #1118 ，最后只能修改通道号解决

**Comment by 648540858** [comment]
等待wvp重构后的新版吧，会支持这个
