### ISSUE TITLE
关于级联NVR的问题

### ISSUE THREAD

**Issue by OMG59E** [648540858/wvp-GB28181-pro#1233]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
 
咨询个问题，wvp作为上级，海康平台作为下级，下级的NVR在上级无法查看NVR的通道和录像，可能是什么问题

**Comment by mengxing2017** [comment]
提供更多的信息才能判断什么问题，大概率是配置填写错误的问题

**Comment by OMG59E** [comment]
> 提供更多的信息才能判断什么问题，大概率是配置填写错误的问题

![image](https://github.com/648540858/wvp-GB28181-pro/assets/16315529/a49f3b4e-a0ce-4cb5-a27a-188d6eddd585)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/16315529/0e183b25-54f3-4879-9868-1ffec252714c)
通道信息如图

查询通道录像，日志显示如下
![image](https://github.com/648540858/wvp-GB28181-pro/assets/16315529/1ca03b75-55b2-4e4c-b4dd-decbc62c9319)

**Comment by mengxing2017** [comment]
老老实实按国标填信息

**Comment by OMG59E** [comment]
已经老老实实填了，按理解应该没填错，晚点上个截图在 2024年1月2日，17:48，mengxing2017 ***@***.***> 写道：﻿
老老实实按国标填信息

**Comment by OMG59E** [comment]
这是平台及联在 2024年1月2日，17:50，mengxing2017 ***@***.***> 写道：﻿
都看不出你这些是什么设备，是nvr还是摄像头还是什么其他玩意？

**Comment by mengxing2017** [comment]
通道号，设备号都有严格的规范的，你这个一看就是瞎填的
