### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by 960243800** [648540858/wvp-GB28181-pro#1236]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境  centos 
 - 3. 端口开放情况
 - 4. 是否是公网部署  否
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
 内网部署后要映射到公网 都需要开放哪些端口以及开放的端口分别对应什么？谢谢
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 960243800** [comment]
> 30000-30500/udp,80tcp/udp,5060tcp/udp，18080tcp，默认端口是这些

30000-30500/udp 是zlm 接收视频流的端口  80 是zlm 的http端口吗   5060  18080 端口分别做什么用的  对应的哪些配置？实际部署的时候可能会有端口调整

**Comment by mengxing2017** [comment]
配置文件有详细的说明

**Comment by 960243800** [comment]
我的意思是哪些端口需要映射到公网？ 哪些不用映射

**Comment by mengxing2017** [comment]
我不是已经说了吗？默认情况下是 30000-30500/udp,80tcp/udp,5060tcp/udp，18080tcp

**Comment by 960243800** [comment]
懂了  谢谢
