### ISSUE TITLE
FTP Response: 500 Ilegal PORT command.

### ISSUE THREAD

**Issue by qimingkunnanzheng** [648540858/wvp-GB28181-pro#1237]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/   wvp-pro/ wvp-prp + zlm都是编译部署
 - 2. 部署环境 windows / ubuntu/ centos ...     centos
 - 3. 端口开放情况   全部开放
 - 4. 是否是公网部署  是
 - 5. 是否使用https  是
 - 6. 方便的话提供下使用的设备品牌或平台  海康大华
 - 7. 你做过哪些尝试  更新代码
 - 8. 代码更新时间  最新

**描述错误**
描述下您遇到的问题
视频无法播放，抓包发现向服务器发送请求被拒绝
![1704262062761](https://github.com/648540858/wvp-GB28181-pro/assets/144506949/86cb6782-f896-4220-9a4d-717cd96b4491)

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你的ftp请求跟wvp没有关系，wvp不支持ftp请求的
