### ISSUE TITLE
[技术咨询]前端登录提示mysql数据库字符集不匹配或不支持，导致登录不了

### ISSUE THREAD

**Issue by ken626014896** [648540858/wvp-GB28181-pro#1238]
**环境信息:**

 - 1. 部署方式  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
  前端登录提示mysql出错
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/38373469/c7bf3dd1-1fde-42cb-a696-2cf883cf862f)

提示数据库字符集不匹配或不支持 修改数据库字符集为utf-8 还是一样

**Comment by ken626014896** [comment]
数据库的表使用sql文件夹里面的 初始化.sql 生成的

**Comment by mengxing2017** [comment]
创建数据库时指定编码，编码是utf8mb4，
