### ISSUE TITLE
通道数据量大了，后台卡死

### ISSUE THREAD

**Issue by microsofter** [648540858/wvp-GB28181-pro#124]
最近对接海康平台，推过来15万多个通道信息，前端页面查看时api接口一直pending，查看后台代码发现以下几个问题：
1、mapper里直接全量查询通道数据
2、分页插件对全量数据进行分页处理
以上两个问题导致程序卡死。
如果大家在生产环境下，接入的通道数据量较大，有下面2个建议：
1、优化分页查询，sql里用limit，去掉分页插件，前端只需要3个东西应该就够了：总条数、页大小、当页数据
2、device_channel表引擎设置为MyISAM

**Comment by 648540858** [comment]
我模拟测试下
