### ISSUE TITLE
BUG 推流到wvp再将直播流加入国标级联，设备在线状态不对

### ISSUE THREAD

**Issue by github4529** [648540858/wvp-GB28181-pro#1240]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题
将rtmp流推流到wvp平台之后，加入国标，进行国标级联
上级平台收到该设备的状态为离线/OFF

查看mysql数据库，表wvp_stream_push，其中status和push_ing都为0
尝试通过using-push-as-status设置为false，同时将数据库中的status手动改为1，重启之后数据库status仍然变成0
**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
use-pushing-as-status 设置true
