### ISSUE TITLE
BUG 历史回放暂停不了

### ISSUE THREAD

**Issue by criver31** [648540858/wvp-GB28181-pro#1244]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
单端口会修改流ID，历史回放后暂停，调用zlm的pauseRtpCheck，使用的streamId是deviceId_channelId；zlm返回-500；使用ssrc作为流ID则正常返回0

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
更新代码测测，最近解决了
