### ISSUE TITLE
技术咨询 海康摄像头 webrtc不显示视频

### ISSUE THREAD

**Issue by ytlibin** [648540858/wvp-GB28181-pro#1246]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows 
 - 3. 端口开放情况 
 - 4. 内网部署 
 - 5. 不使用https
 - 6. 方便的话提供下使用的设备品牌或平台
       海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 :最新代码

**内容描述:**
webrtc不显示视频内容
**截图**  
<img width="736" alt="1b84ab98dfa1f21a16ff1ce724feb8a" src="https://github.com/648540858/wvp-GB28181-pro/assets/33979703/a235d423-279f-4f00-98f7-25f44b08d4ac">
<img width="960" alt="02d5d0ba8c8131eb865b76a7824a3f6" src="https://github.com/648540858/wvp-GB28181-pro/assets/33979703/fd11bf84-17f4-4caa-b9aa-a15660914f6e">

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by ytlibin** [comment]
解决

**Comment by Leexiaobei** [comment]
大佬 如何解决的
