### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by huiliyisakura** [648540858/wvp-GB28181-pro#1249]
**环境信息:**   wvp-GB28181-pro

 - 1. 创建国标设备时报错

**内容描述:**

![image](https://github.com/648540858/wvp-GB28181-pro/assets/38311538/1c3dbe77-4831-4a89-a341-4cf1e2ba6dc7)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/38311538/758ce74c-5453-4a8f-8f3d-47ddd86b0d03)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/38311538/c84cef7b-3eec-4b45-8cec-646a57626fe9)
请问页面上创建国标设备   收流IP  配置什么啊
**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
不需要手动添加，设置直接注册上来就可以
