### ISSUE TITLE
wvp配置动态端口，zml要怎么配置

### ISSUE THREAD

**Issue by socyli** [648540858/wvp-GB28181-pro#125]
wvp开启了动态端口模式，我用docker启动不起来，zml的配置文件要修改吗？
docker run -it -p 8000:80 -p 1935:1935 -p 554:554 -p 554:554/udp -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp panjjo/zlmediakit

**Comment by 648540858** [comment]
不需要，wvp会自动修改
