### ISSUE TITLE
2.6.9更新代码后，mvn打包编译错误

### ISSUE THREAD

**Issue by duankeke** [648540858/wvp-GB28181-pro#1251]
**环境信息:**

 - 1. 部署方式 wvp-pro 编译 / zlm(docker) 
 - 2. 部署环境 centos 
 - 3. 端口开放情况：内网，防火墙全部关闭
 - 4. 是否是公网部署 ：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
2.6.9更新代码后，mvn打包编译错误，截图如下：

![截屏2024-01-12 14 48 07](https://github.com/648540858/wvp-GB28181-pro/assets/9245593/f22374ea-9f1e-4473-a003-1a23d6bc7050)

**Comment by 648540858** [comment]
更新代码再试试

**Comment by duankeke** [comment]
编译没问题，谢谢
