### ISSUE TITLE
技术咨询 点播端口分配异常

### ISSUE THREAD

**Issue by DingKun7** [648540858/wvp-GB28181-pro#1252]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**Comment by 648540858** [comment]
哪个分支

**Comment by Jason5592** [comment]
这个一般是docker部署服务的时候rtc的8000端口未开放
