### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by huiliyisakura** [648540858/wvp-GB28181-pro#1253]
**环境信息:**

 - 1. 部署方式 wvp-pro 本地 / zlm(docker) 内网服务器
 - 2. 部署环境 windows / ubuntu/ centos ...

![image](https://github.com/648540858/wvp-GB28181-pro/assets/38311538/0725c747-bebf-498f-aa7f-38d49163086f)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/38311538/a241d5ae-bfb6-4c0d-a5ad-b0380907dad8)

具体问题在图上，主要是日志分析，作者大大可以帮忙看看吗

**Comment by 648540858** [comment]
你服务器是不是开启防火墙了
