### ISSUE TITLE
技术咨询：请问如何增加分屏个数，默认最多只有9个

### ISSUE THREAD

**Issue by yxzsh** [648540858/wvp-GB28181-pro#1254]
**环境信息:**

 - 1. 部署方式 ：编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ： ubuntu22.04内网部署
 - 3. 端口开放情况：全开放
 - 4. 是否是公网部署 ：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台： 海康录像机
 - 7. 你做过哪些尝试：找不到修改代码的地方
 - 8. 代码更新时间

**内容描述:**
想要增加分屏个数，不知道从哪下手

**截图**  
![fenping](https://github.com/648540858/wvp-GB28181-pro/assets/30100389/700dde76-4b78-49ae-9ca9-14047f8ca914)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
需要你自己开发

**Comment by scdn** [comment]
web_src/src/components/live.vue
<img width="589" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/43884938/51befefe-a8db-422c-a5b5-fb48259b343f">

**Comment by scdn** [comment]
<img width="1402" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/43884938/e22c425b-29e0-4b85-9f58-4490a81802df">
16分屏
