### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by Q393584665** [648540858/wvp-GB28181-pro#1256]
**环境信息:**

 - 1. 部署方式 编译wvp-pro + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
使用内网IP获取位置正常，但是部署到公网后，获取不到了
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/39716917/4adb64e6-73ac-4013-b36f-92e46eda1b0f)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by scdn** [comment]
stream-ip改为公网ip
