### ISSUE TITLE
BUG  代理拉流状态错误

### ISSUE THREAD

**Issue by iwanlebron** [648540858/wvp-GB28181-pro#1257]
**环境信息:**

 - 1. 部署方式  wvp-prp + zlm都是编译部署
 - 2. 部署环境 openEuler-linux 
 - 3. 端口开放情况 都开放
 - 4. 是否是公网部署  否
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台  代理拉流
 - 7. 你做过哪些尝试  查看日志没有发现异常
 - 8. 代码更新时间   git版本 ff1e9f7�
**描述错误**
代理拉流状态错误
![image](https://github.com/648540858/wvp-GB28181-pro/assets/105045937/6a846331-9439-473a-92c2-139bb758fa29)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/105045937/719a7493-01d4-4d31-86e8-444ae6e6715a)

**如何复现**
未能复现

**抓包文件**
  
**日志**

![image](https://github.com/648540858/wvp-GB28181-pro/assets/105045937/e454a4a0-c80f-461e-be0d-5adc20563812)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/105045937/4cebb423-3702-4cdb-884c-854f9daecb0a)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/105045937/61d16cf2-6746-448a-a7f4-47f2ece7a428)

**Comment by 648540858** [comment]
后续到代码解决这个问题，你更新测试吧。你的代码版本很老了
