### ISSUE TITLE
录像下载功能报错

### ISSUE THREAD

**Issue by zmctk** [648540858/wvp-GB28181-pro#1259]
**环境信息:**

 - 1. 部署方式 wvp-pro 编译 / zlm(docker) 
 - 2. 部署环境 centos ...
 - 3. 端口开放情况
 - 4. 不是公网部署 
 - 5. 未使用https

**内容描述:**录像下载功能报错

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/126141936/b9a5d54d-217c-4d88-bbae-d001f7eec62a)

  **配置文件**
![image](https://github.com/648540858/wvp-GB28181-pro/assets/126141936/1f7068d0-64e1-4948-8b9a-81bd4ccb5d6f)

**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by zmctk** [comment]
第一张图贴错了

**Comment by 648540858** [comment]
是最新的代码。更新代码后记得重新编译前端

**Comment by bigff-0527** [comment]
老哥解决了吗？我也是遇到了这个问题
