### ISSUE TITLE
页面一直访问不到资源 

### ISSUE THREAD

**Issue by ht111111** [648540858/wvp-GB28181-pro#126]
![image](https://user-images.githubusercontent.com/75420803/125442987-3a1cea27-c152-468a-b8a0-7b5b22c083a1.png)
 一直报这个错误 但是页面一直访问不到资源

**Comment by 648540858** [comment]
你这是什么时候的代码

**Comment by ht111111** [comment]
就是下的代码 然后视频资源请求不了，在vlc都能播放，在播放页面一直缓冲，不出来画面。

**Comment by 648540858** [comment]
更新代码试试， 刚更新了播放器

**Comment by ht111111** [comment]
这个摄像头是不是就只能联网才可以注册上去  不联网的话是不是注册不上去的

**Comment by 648540858** [comment]
如果的服务器没在公网那么是不需要链接到公网的，但是基本的局域网你得给他连上
