### ISSUE TITLE
技术咨询：部分地址拉流慢的问题

### ISSUE THREAD

**Issue by MightyTiger98** [648540858/wvp-GB28181-pro#1260]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
wvp视频服务生成出来的部分视频地址拉流慢（单独服务器 使用了域名）在当前使用拉流速度是正常的
场景：其他web应用使用wvp视频服务地址拉流速度有的快有的慢
目前对比测试flv地址 （web使用播放器是jessibuca）
http/https的flv地址 拉流慢在web浏览器和app下测试拉流速度很慢 大概5-10s才能显示画面 有时还会触发失败重试
ws/wss的flv地址 拉流速度基本和在wvp视频服务一致 画面秒开 在web上使用正常
也使用过jessibuca在线的播放器 效果基本和上述效果差不多
请问这种问题如何排查和优化
**截图**  
测试在jessibuca在线播放器
使用https-flv流地址
![e80679664ddcc1514c80ed1dde3256d](https://github.com/648540858/wvp-GB28181-pro/assets/49520296/75993629-cbf9-4dde-93d2-c0ba851e2998)
![72a9274c02a9660d6efff14371bdd78](https://github.com/648540858/wvp-GB28181-pro/assets/49520296/5d38dae1-4c85-4121-a0d1-1b277c913c79)
使用wss-flv流地址
![385d13ab981c24ebfb43b4eac6ebb35](https://github.com/648540858/wvp-GB28181-pro/assets/49520296/acbef133-de1d-4acb-86ea-60f8286c3a8d)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
wvp视频服务生成出来的部分视频地址 这个地址你是怎么生成的，通过什么方式加入的wvp

**Comment by MightyTiger98** [comment]
> wvp视频服务生成出来的部分视频地址 这个地址你是怎么生成的，通过什么方式加入的wvp
配置文件zlm配置了域名
使用了nginx代理
![1707995088750](https://github.com/648540858/wvp-GB28181-pro/assets/49520296/32795c23-3107-49e3-87cc-7c3ba2f16304)

**Comment by MightyTiger98** [comment]
> wvp视频服务生成出来的部分视频地址 这个地址你是怎么生成的，通过什么方式加入的wvp

![1707995201713](https://github.com/648540858/wvp-GB28181-pro/assets/49520296/3483c17a-422d-4588-b131-c7b55b9f76c3)
配置了这个属性 属性上是自己的域名
nginx对该域名进行了转发

**Comment by 648540858** [comment]
不使用nginx，直接拉去wvp的流速度如何

**Comment by MightyTiger98** [comment]
> 不使用nginx，直接拉去wvp的流速度如何

试了一下 关闭了nginx https的地址拉流是一部分快一部分慢 使用有线接入网络的打开快 使用4G的会慢很多
测试在jessibuca在线播放器 使用https-flv流地址（wvp平台是秒开）
使用有线连接
![ad034e1fd8a36d4bcbff56c40b5dff9](https://github.com/648540858/wvp-GB28181-pro/assets/49520296/3a545e5e-1c12-41f0-836b-a8b0e2353407)
4G
![37a3a2177dcc93ea4fb736405dca256](https://github.com/648540858/wvp-GB28181-pro/assets/49520296/ece67af1-acec-474a-aa57-f52c6c1adadb)

**Comment by 648540858** [comment]
你可以尝试上级下wvp的jessibuca，如果还是一样的问题，那就是基本可以确定是播放器的问题，在线版本可能修复了这个问题，但是可能没有开源

**Comment by MightyTiger98** [comment]
> 你可以尝试上级下wvp的jessibuca，如果还是一样的问题，那就是基本可以确定是播放器的问题，在线版本可能修复了这个问题，但是可能没有开源

我的项目也用了jessibuca 文件和代码基本和wvp差不多 效果上面和在线的播放器差不多

**Comment by 648540858** [comment]
所以你说的慢的还是一个4G设备，那是不是设备上流慢呢，需要i提供一份抓包和zlm日志确认下

**Comment by MightyTiger98** [comment]
> 所以你说的慢的还是一个4G设备，那是不是设备上流慢呢，需要i提供一份抓包和zlm日志确认下

最近接了一批4G设备 没啥影响 还是https和wss的比较 http/https就是拉流慢而且有大概率第一个请求失效 第二个请求才有可能拉到流 
 wss基本就是秒开 最多大概2-3秒也能拉到流

**Comment by MightyTiger98** [comment]
> 请问你解决了吗？

没有 移动端用rtmp web端用wss 视频加载速度尚可接受
