### ISSUE TITLE
技术咨询-收流超时zlm 提示 禁止RTP推流:[bad http status code]:500

### ISSUE THREAD

**Issue by liutao199191** [648540858/wvp-GB28181-pro#1262]
**环境信息:**

 - 1. 部署方式 
 -  wvp-prp + zlm都是编译部署
 - 2. 部署环境 
 - ubuntu
 - 3. 端口开放情况
![1705544410922](https://github.com/648540858/wvp-GB28181-pro/assets/12408722/feafd1c1-d6c3-46d3-b708-ab269f491d04)
 - 4. 是否是公网部署 
 - 是
 - 5. 是否使用https
 - 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:*
 收流超时
**截图**  
wvp错误信息
![image](https://github.com/648540858/wvp-GB28181-pro/assets/12408722/6a376b71-80cd-4658-ba4a-4a6737835dbb)

zlm错误信息
![1705544558841](https://github.com/648540858/wvp-GB28181-pro/assets/12408722/97d187c2-c11f-4b7e-80c2-a2de869f9ded)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by liutao199191** [comment]
spring:
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: smartbim.hzj
    timeout: 10000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: root
    password: Smartbim.hzj123
    hikari:
      connection-timeout: 20000           
      initialSize: 10                      
      maximum-pool-size: 200                
      minimum-idle: 5                      
      idle-timeout: 300000                 
      max-lifetime: 1200000               
server:
  port: 7001
  ssl:
    enabled: false
    key-store: classpath:test.monitor.89iot.cn.jks
    key-store-password: gpf64qmw
    key-store-type: JKS

sip:
  ip: 外网ip
  port: 6666
  domain: 3101100000
  id: 31011000006600000001
  password: smdfd
  alarm: false

media:
  id: smartbimhzjzlm
  ip: 192.168.6.29
  http-port: 8001
  stream-ip: 外网ip
  sdp-ip: 外网ip
  hook-ip: 外网ip
  http-ssl-port: 
  secret: 62170a48-37f5-bb5c-423c-62b0124c49df
  rtp:
    enable: true
    port-range: 30000,30500 
    send-port-range: 50000,50500 
  record-assist-port: 0
user-settings:
  play-timeout: 10000
  push-authority: false
  auto-apply-play: true
  sip-log: true
  device-status-notify: true
  register-again-after-time: 60
  allowed-origins:
    - http://localhost:8000
    - http://127.0.0.1:8000
    wvp 配置文件

**Comment by scdn** [comment]
hook-ip填内网ip
