### ISSUE TITLE
技术咨询  WVP是否支持查看CVR本地硬盘存储的录像

### ISSUE THREAD

**Issue by zlqcoder** [648540858/wvp-GB28181-pro#1265]
**内容描述:**
您好，我想咨询一下，WVP支持查看CVR本地硬盘存储的录像吗

**Comment by 648540858** [comment]
cvr支持国标吗，支持国标就可以



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月19日(周五) 上午10:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [648540858/wvp-GB28181-pro] 技术咨询 (Issue #1265)




 
内容描述:
 您好，我想咨询一下，WVP支持查看CVR本地硬盘存储的录像吗

**Comment by zlqcoder** [comment]
设备是支持国标的，那请问有示例或者思路吗？

**Comment by zlqcoder** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/80229542/2c753463-dc97-4a0d-a888-490f5b42d9e0)
将硬盘录像机接入WVP之后是不是就可以直接在这查看录像了
PS: 因为我现在还没有测试的硬盘录像机,只连接了摄像头,所以想询问一下

**Comment by 648540858** [comment]
可以
