### ISSUE TITLE
技术咨询，设备注册一直401

### ISSUE THREAD

**Issue by willianfu** [648540858/wvp-GB28181-pro#1267]
**环境信息:**
1、部署在公网服务器环境，编译wvp-pro/ wvp-prp + zlm都是编译部署
2、部署在ubuntu
3、防火墙端口 udp和tcp全部开放
5、未使用https
6、海康普通枪机
7、代码是目前最新版

**内容描述:**
请问下大佬，我在本地局域网环境把摄像头调通了，正常可以在平台打开播放，但是把它切换到公网后，能收到摄像头注册信息，就是一直回复 401 ，摄像头没法注册，页面上显示不了摄像头，请问可能会是什么原因呢，我使用腾讯云轻量级服务器，防火墙端口的UDP和TCP全开

为了防止本地和服务器不一致，ZLMediaKit 和 wvp的配置文件都是用的同一份，然后配置文件里面把端口改成服务器外网端口了，ZLMediaKit 也连接到了wvp，就是这个摄像头注册一直401，方便的话可以给我提供一些可能的帮助信息，万分感谢！！！

> 2024-01-19 15:50:22.747 [wvp-2]  INFO --- c.g.i.v.g.t.e.r.impl.RegisterRequestProcessor: 104 [注册请求]设备：41010500001320000002, 开始处理: 117.61.185.175:56609

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/25615627/06ac257a-fac1-40ed-afff-63fb37cad180)

**Comment by criver31** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/54142345/c95f45e6-a140-4af9-8e27-a8d75371232e)
抓包看报文是否符合这个流程；

**Comment by Lmx1220** [comment]
可以远程帮我跑通本地？

**Comment by 648540858** [comment]
media下的配置改成这样
```
ip:  127.0.0.1
sdp-ip 公网ip
stream-ip： 127.0.0.1
hook-ip: 127.0.0.1
```

**Comment by willianfu** [comment]
> media下的配置改成这样
> 
> ```
> ip:  127.0.0.1
> sdp-ip 公网ip
> stream-ip： 127.0.0.1
> hook-ip: 127.0.0.1
> ```
感谢回复，配置改了还是一样401，我的配置是这样的，大佬方便的时候您帮忙看下，感谢！
![image](https://github.com/648540858/wvp-GB28181-pro/assets/25615627/be1dd94f-6dbd-43c5-af28-b3eaa0315285)

**Comment by 648540858** [comment]
抓包看下我觉得消息回发给设备可能失败了

**Comment by willianfu** [comment]
> 抓包看下我觉得消息回发给设备可能失败了

wireshak在局域网抓包试了下，抓不到sip注册包信息。我用java的远程调试，开启了服务器上debug，控制台返回了

![image](https://github.com/648540858/wvp-GB28181-pro/assets/25615627/251ba058-351c-41b2-b7ef-30e801978b5c)

**Comment by 648540858** [comment]
如果有异常IP，又可能是被人扫描的，建议不要用sip默认端口。

**Comment by willianfu** [comment]
> 如果有异常IP，又可能是被人扫描的，建议不要用sip默认端口。

不是的，这个日志的IP是设备注册失败401打印出来注册的IP，我端口号都改过，应该就是设备IP，但是设备在局域网和外网出口ip不是这个，不知道为何打出来是117.61.184.xx这种的

然后我在局域网测试是正常的，这个ip打出来是设备局域网内ip，如下图
![image](https://github.com/648540858/wvp-GB28181-pro/assets/25615627/556ae9de-2971-4ab1-abf0-36b65c009ae2)

部署到服务器上设备第一次注册401后，不会发起第二次注册，且IP不对，本地在南昌，ip归属地为北京
![image](https://github.com/648540858/wvp-GB28181-pro/assets/25615627/76cf4fce-8373-4625-8fcf-38894e82d058)

**Comment by willianfu** [comment]
####感谢各位的回复，问题已经解决了，原因是使用了海康的4g枪机，4g卡没有拔下来，导致网络在4G注册成功后被切换到了4G，设备直接下线了，注意大家如果使用了4G网络又插了网线就会出现我这种情况，可以尝试如下方法：

1、将网络切换为DHCP，不设置固定内网ip
2、在插网线的情况下，禁用4G网络

这个问题由于没经验，弄了很久，感谢作者及各位回复，希望能帮到后来人

**Comment by ahhyong** [comment]
> #### 感谢各位的回复，问题已经解决了，原因是使用了海康的4g枪机，4g卡没有拔下来，导致网络在4G注册成功后被切换到了4G，设备直接下线了，注意大家如果使用了4G网络又插了网线就会出现我这种情况，可以尝试如下方法：
> 1、将网络切换为DHCP，不设置固定内网ip
> 
> 这个问题由于没经验，弄了很久，感谢作者及各位回复，希望能帮到后来人

请问这个“不设置固定内网ip”，是指什么？ 是“网络 - 基本配置”里面的“自动获取”要勾选吗？
