### ISSUE TITLE
技术咨询 云端录像时间异常

### ISSUE THREAD

**Issue by arvinhan** [648540858/wvp-GB28181-pro#1269]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 / ubuntu/
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

**截图**  
![QQ图片20240119224907](https://github.com/648540858/wvp-GB28181-pro/assets/31042264/a4c897dc-4e0d-43ea-bf35-41415a93c9fb)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by scdn** [comment]
这个问题我也发现了,经测试,是时间戳的问题,正常应该是十位,后面多了三位0

**Comment by arvinhan** [comment]
> 这个问题我也发现了,经测试,是时间戳的问题,正常应该是十位,后面多了三位0

这个怎么解决，是仓库代码有问题吗

**Comment by scdn** [comment]
> > 这个问题我也发现了,经测试,是时间戳的问题,正常应该是十位,后面多了三位0
> 
> 这个怎么解决，是仓库代码有问题吗

没有

**Comment by 648540858** [comment]
前端时间格式化的问题，我修复下

**Comment by 648540858** [comment]
已修复
