### ISSUE TITLE
级联点播时响应的stream id与原始id不一致的问题

### ISSUE THREAD

**Issue by xuhanbing** [648540858/wvp-GB28181-pro#127]
INVITE部分：
a=rtpmap:97 MPEG4/90000
y=0200006657

响应部分：
a=sendonly
a=filesize:-1
y=0703036487

**Comment by 648540858** [comment]
你说的响应部分不是wvp响应的吧 wvp的sdp没有a=filesize:

**Comment by xuhanbing** [comment]
海康的响应

完整消息交互如下
INVITE sip:*** SIP/2.0
Call-ID: 364c67300ff5064bf5c7fc5ee8807f83@0.0.0.0
CSeq: 1 INVITE
From: ***;tag=FromInvt1627544481274
To: ***
Via: SIP/2.0/UDP ***;rport
Max-Forwards: 70
Contact: ***
Subject: ***
Content-Type: APPLICATION/SDP
Content-Length: 205

v=0
o=00000 0 0 IN IP4 ***
s=Play
c=IN IP4 ***
t=0 0
m=video 10000 RTP/AVP 96 98 97
a=recvonly
a=rtpmap:96 PS/90000
a=rtpmap:98 H264/90000
a=rtpmap:97 MPEG4/90000
y=0200009319

SIP/2.0 200 OK
Via: SIP/2.0/UDP ***
From: ***
To: ***;tag=645721C8-A1F3-4641-9991-97C9EC841A2F
Call-ID: 364c67300ff5064bf5c7fc5ee8807f83@0.0.0.0
CSeq: 1 INVITE
Contact: ***
User-Agent: NCG V3.3.6.768441
Content-Type: Application/SDP
Content-Length: 176

v=0
o=*** 0 0 IN IP4 ***
s=Play
c=IN IP4 ***
t=0 0
m=video 5490 RTP/AVP 96
a=rtpmap:96 PS/90000
a=sendonly
a=filesize:-1
y=0703001718

**Comment by 648540858** [comment]
为什么要跟海康的一致呢， 可以必须的呀，你只要保证你的发的SDP的SSRC与你的PS流的SSRC一致即可

**Comment by xuhanbing** [comment]
不太懂你说的必须是什么意思，对这个不太熟，是通过设置某个值吗？
现在的情况是海康用一个其他的ssrc来推流，比如上面的0703001718，导致hook有回调，但是两个ssrc不一致，点播超时了。
能否做一个映射关系，比如将0703001718->0200009319？

**Comment by 648540858** [comment]
不能，你使用了单端口吧，这种情况可以使用多端口方式解决，一个端口对应一路流，忽略ssrc不一致的问题
