### ISSUE TITLE
技术咨询 如何区分设备通道是级联上来的

### ISSUE THREAD

**Issue by WalkerPlus** [648540858/wvp-GB28181-pro#1274]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 -  wvp-pro 编译 zlm(docker)
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
 如何区分设备通道是级联上来的
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
区分不出来，都是一样的
