### ISSUE TITLE
BUG  错误: 字段 "gbStreamId" 不存在

### ISSUE THREAD

**Issue by oulover** [648540858/wvp-GB28181-pro#1275]
**环境信息:**
代码分支：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/61042846/9b03f7e7-9d25-43b6-88a0-f755421dc76c)

 
**描述错误**
描述下您遇到的问题
![image](https://github.com/648540858/wvp-GB28181-pro/assets/61042846/ce9dd22e-80eb-40bc-a53b-fe5f49b5e6ce)

 
![image](https://github.com/648540858/wvp-GB28181-pro/assets/61042846/46c599a8-36ce-4a5a-b7d4-a0420e296d80)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/61042846/7f087350-31f0-4eb2-8515-09db87036223)

**Comment by oulover** [comment]
小问题，我改了下意识的都push了一下，才注意到不是成员 ，

**Comment by 648540858** [comment]
提个pr吧

**Comment by oulover** [comment]
> 提个pr吧
https://github.com/648540858/wvp-GB28181-pro/pull/1289
