### ISSUE TITLE
技术咨询 关于Hook /on_stream_none_reader 无人观看事件失效问题

### ISSUE THREAD

**Issue by WalkerPlus** [648540858/wvp-GB28181-pro#1279]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 wvp-pro  编译 +zlm(docker)
 - 2. 部署环境 windows / ubuntu/ centos ...
  windows
 - 3. 端口开放情况

 - 4. 是否是公网部署 
 否
 - 5. 是否使用https
 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
  最新代码

**内容描述:**
虽然代码中回复的状态是根据ret.put("close", userSetting.getStreamOnDemand());来选择是否关闭无人看的流
但是后面代码
```
// 多查询一次防止已经被处理了
  InviteInfo info = inviteStreamService.getInviteInfo(inviteInfo.getType(),
                                inviteInfo.getDeviceId(), inviteInfo.getChannelId(), inviteInfo.getStream());
                        if (info != null) {
                            cmder.streamByeCmd(device, inviteInfo.getChannelId(),
                                    inviteInfo.getStream(), null);
                        }


```
这段代码都会去关闭流，是否有问题

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
有什么问题，你遇到了什么问题呢，单纯不理解逻辑？来星球问吧，这里只解决BUG
