### ISSUE TITLE
技术咨询 通道快照不更新

### ISSUE THREAD

**Issue by jelly-jilli** [648540858/wvp-GB28181-pro#1281]
为什么我的通道快照不更新，只是一个默认的zlm图片呢？困惑很久了，是因为没装什么插件吗？
提示[ZLM HOOK] 流未找到:media_server_118->rtmp->rtp/34020000001180000001_3402000
但是这个通道是可以正常播放的，查看了zlm的www文件夹，并没有snap（存放截图）文件夹

**Comment by 648540858** [comment]
点播了吗，ffmpeg安装了吗

**Comment by jelly-jilli** [comment]
最后找到是zlm的ffmpeg配置有问题，修改后就解决了

**Comment by xb578940562** [comment]
> 最后找到是zlm的ffmpeg配置有问题，修改后就解决了

请问最后是怎么解决的呢
