### ISSUE TITLE
国标录像下载提示资源未找到，日志报空指针异常

### ISSUE THREAD

**Issue by DarkHorse-YU** [648540858/wvp-GB28181-pro#1283]
**环境信息:**

 - 1. 部署方式：wvp-pro(本机) +zlm(本机docker)
 - 2. 部署环境：银河麒麟v10
 - 3. 端口开放情况：已开放
 - 4. 是否是公网部署：是
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间：最新

**描述错误**
国标录像点击下载进度条未到100%提示资源未找到

**截图**
![cbc6f498ec5ff3e7172e6cf3d6e661a](https://github.com/648540858/wvp-GB28181-pro/assets/82326966/18c69556-8e0f-41e6-8d7f-36d5033946ab)
![3248a5de44398366f4b1bce0efe23b4](https://github.com/648540858/wvp-GB28181-pro/assets/82326966/26ab788b-b536-479c-b955-3e7a6441d988)

**日志**
![3735712d47345864bb8a43399679b4e](https://github.com/648540858/wvp-GB28181-pro/assets/82326966/a8ef3d4c-8f2e-489c-b20c-4ae0bcc76b8d)

**Comment by 648540858** [comment]
这个异常似乎不影响下载

**Comment by DarkHorse-YU** [comment]
> 这个异常似乎不影响下载

那目前就是下载一半就提示资源未找到，缓存事务信息未找到，是我这边配置有什么呢问题吗

**Comment by 648540858** [comment]
代码是最新的吗，新代码已经不用assist应该没有这个错误了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月31日(周三) 中午11:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] 国标录像下载提示资源未找到，日志报空指针异常 (Issue #1283)




  
这个异常似乎不影响下载
  
那目前就是下载一半就提示资源未找到，缓存事务信息未找到，是我这边配置有什么呢问题吗

**Comment by DarkHorse-YU** [comment]
![1706671674107](https://github.com/648540858/wvp-GB28181-pro/assets/82326966/a977bcff-48ee-419d-ab80-f6ad5bf86eb2)
![1706671687940](https://github.com/648540858/wvp-GB28181-pro/assets/82326966/984d6163-9578-46cb-b682-2245000e341b)
后端刚刚更新的代码部署的，分支是wvp-28181-2.0，还是提示这个

**Comment by DarkHorse-YU** [comment]
> 代码是最新的吗，新代码已经不用assist应该没有这个错误了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年1月31日(周三) 中午11:17 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [648540858/wvp-GB28181-pro] 国标录像下载提示资源未找到，日志报空指针异常 (Issue #1283) 这个异常似乎不影响下载 那目前就是下载一半就提示资源未找到，缓存事务信息未找到，是我这边配置有什么呢问题吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

![image](https://github.com/648540858/wvp-GB28181-pro/assets/82326966/a496f0ff-10ea-4119-9ed3-ee140060b2ba)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/82326966/2d766cc6-c287-44dd-86c2-f26ced8cae98)
后端刚刚更新的代码部署的，分支是wvp-28181-2.0，还是提示这个

**Comment by 648540858** [comment]
你是不是没有播放的情况下去控制倍速之类的操作了

**Comment by bigff-0527** [comment]
老哥解决了吗？我也遇到这个问题，下载到一半就报错：资源未找到
