### ISSUE TITLE
多路通道取不到通道数

### ISSUE THREAD

**Issue by sunsonzh** [648540858/wvp-GB28181-pro#1287]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos ...
 - 3. 端口开放情况 8116 ，30000-35000
 - 4. 是公网部署 
 - 5. 否使用https
 - 6. 海康AI设备
 - 7. 1,2路通道能正常获取通道数，3，4路获取不到通道数，内网正常，公网不正常
 - 8. 最新代码

**描述错误**
描述下您遇到的问题
1,2路通道能正常获取通道数，3，4路获取不到通道数，内网正常，公网不正常

**如何复现**
有明确复现步骤的问题会很容易被解决
添加3路以上通道数量

**截图**  
![844b5e887317e55ff2f2e86c2cf8034](https://github.com/648540858/wvp-GB28181-pro/assets/6812003/0d31be7c-2938-4d7b-b6e3-86861b4c5d2d)

**Comment by 648540858** [comment]
设备注册后马上去获取试试

**Comment by sunsonzh** [comment]
> 设备注册后马上去获取试试

测试过很多次了，包括删除设备列表重新注册，一开始都没找到原因，因为在局域网测试是正常的，在公网测试就出错了，一开始还以为是设备的问题，后面在设备抓包发现数据包是有发送的，只是服务端收不到。最后是删除了通道ID，只保留一路，发现能正常获取到通道数，经过多次测试，保留两路能正常获取 通道数，3路就获取不到通道数了。

**Comment by sunsonzh** [comment]
> 设备注册后马上去获取试试

附一张两路正常的图：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/6812003/654cc499-d4c7-4109-8744-e298a15f4e5a)

**Comment by sunsonzh** [comment]
[设备端tcp.zip](https://github.com/648540858/wvp-GB28181-pro/files/14094167/tcp.zip)
[wvp端.zip](https://github.com/648540858/wvp-GB28181-pro/files/14094180/wvp.zip)

**Comment by 648540858** [comment]
你压根没有查询呀，如果走订阅。确定代码是我最近一周内的

**Comment by sunsonzh** [comment]
> 你压根没有查询呀，如果走订阅。确定代码是我最近一周内的

你说的查询是什么？检索指令  <CmdType>Catalog</CmdType>\r\n，有这个指令，是最新的2.6.9版本
刚刚重新更新了一个版本,2.7.0，启动不了，附2.7.0的错误图：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/6812003/c5cd86de-5ee7-4f53-9138-d01d798fd13d)

**Comment by 648540858** [comment]
> > 你压根没有查询呀，如果走订阅。确定代码是我最近一周内的
> 
> 你说的查询是什么？检索指令 Catalog\r\n，有这个指令，是最新的2.6.9版本 刚刚重新更新了一个版本,2.7.0，启动不了，附2.7.0的错误图： ![image](https://private-user-images.githubusercontent.com/6812003/301102090-c5cd86de-5ee7-4f53-9138-d01d798fd13d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzU0NjIsIm5iZiI6MTcwOTUzNTE2MiwicGF0aCI6Ii82ODEyMDAzLzMwMTEwMjA5MC1jNWNkODZkZS01ZWU3LTRmNTMtOTEzOC1kMDFkNzk4ZmQxM2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMDY1MjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmNlYjNhNThiNTFmYjZkNDcyMDI4Njk4ZjVkMWMyMGFiZjIyNDYxMjZmMmJjMDY5MDZiYzZjMGYwY2Q4NjNkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.W2NmV4vy7cfF5bNz6L7u6B-xrixVwBAWj3WRxkmG6Kk)

数据库连接配置没更新，更新下再测试，开启抓包然后点击刷新通道，得到结果后停止抓包，等你有抓包再打开，我先关闭了
