### ISSUE TITLE
云端录像的地方,年月日显示不正常BUG

### ISSUE THREAD

**Issue by jack361** [648540858/wvp-GB28181-pro#1290]
**环境信息:**

 - 1. 部署方式  zlm都是编译部署
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况  全开放,关闭了防火墙
 - 4. 是否是公网部署 公网部署
 - 5. 是否使用https  没使用https
 - 6. 方便的话提供下使用的设备品牌或平台 tp-link半球机,支持28181
 - 7. 你做过哪些尝试 重新编译数次,我朋友也遇到同样的问题
 - 8. 代码更新时间  最新代码

**描述错误**
描述下您遇到的问题

**如何复现**
直接编译就有问题

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37525249/d5b48a73-edda-4c3b-b81d-acfa10b9268d)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
更新代码

**Comment by jack361** [comment]
用的是最新的哦
