### ISSUE TITLE
无法修改地址坐标和主子码流开关

### ISSUE THREAD

**Issue by jack361** [648540858/wvp-GB28181-pro#1291]
**环境信息:**

部署方式 zlm都是编译部署
部署环境 ubuntu
端口开放情况 全开放,关闭了防火墙
是否是公网部署 公网部署
是否使用https 没使用https
方便的话提供下使用的设备品牌或平台 tp-link半球机,支持28181
你做过哪些尝试 重新编译数次,我朋友也遇到同样的问题
代码更新时间2024年1月30编译的最新代码

**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37525249/a846cad2-11d3-447e-99d3-07d880b37478)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/37525249/abee969f-33a9-41b9-96f6-5bb1f6ba0913)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
更新代码，已经支持了

**Comment by jack361** [comment]
什么时候更新的是支持的呢
