### ISSUE TITLE
[BUG] 国标设备-通道-播放 jessibuca播放器尺寸不正常,升级最近版本之前是正常的.

### ISSUE THREAD

**Issue by jack361** [648540858/wvp-GB28181-pro#1292]
**环境信息:**
部署方式 zlm都是编译部署
部署环境 ubuntu
端口开放情况 全开放,关闭了防火墙
是否是公网部署 公网部署
是否使用https 没使用https
方便的话提供下使用的设备品牌或平台 tp-link半球机,支持28181
你做过哪些尝试 重新编译数次,我朋友也遇到同样的问题
代码更新时间2024年1月30编译的最新代码

**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37525249/33685095-178d-457c-a164-d8d5fdb36491)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by jack361** [comment]
我朋友也有这个问题.我们两个是一起倒腾的

**Comment by Steven0621** [comment]
我编译的2.6.9也存在这个问题，估计是前端代码写的有问题。

**Comment by DarkHorse-YU** [comment]
![1706670175162](https://github.com/648540858/wvp-GB28181-pro/assets/82326966/277194b8-05a4-42d4-a587-35d2a3b57bf0)
我把这改了好使了，但是这里改了以后，分屏展示九宫格那也被拉长了，感觉两边用的是一个样式

**Comment by 648540858** [comment]
更新代码测试下，正常是应该自动计算合适的宽高，但是你的代码似乎没有计算。你换了种写法，测试试试

**Comment by DarkHorse-YU** [comment]
> 更新代码测试下，正常是应该自动计算合适的宽高，但是你的代码似乎没有计算。你换了种写法，测试试试

![1706679904885](https://github.com/648540858/wvp-GB28181-pro/assets/82326966/37d23179-f021-4406-be81-9d6818c9cfb7)
刚更新了您的代码，设备通道那播放没问题了，但是分屏展示九宫格这里样式变了，应该是受影响了

**Comment by jack361** [comment]
请教下,是不是每次更新都要重新编译和部署.我不太了解这些,前端可以像wordpress那样不编译成jar直接升级吗

**Comment by zc640618** [comment]
更新之后，视频压扁了，看代码是固定了高度，之前是自适应的

**Comment by scdn** [comment]
> 请教下,是不是每次更新都要重新编译和部署.我不太了解这些,前端可以像wordpress那样不编译成jar直接升级吗

可以前后端分开部署

**Comment by jack361** [comment]
> > 请教下,是不是每次更新都要重新编译和部署.我不太了解这些,前端可以像wordpress那样不编译成jar直接升级吗
> 
> 可以前后端分开部署

具体怎么操作呢

**Comment by scdn** [comment]
> > > 请教下,是不是每次更新都要重新编译和部署.我不太了解这些,前端可以像wordpress那样不编译成jar直接升级吗
> > 
> > 
> > 可以前后端分开部署
> 
> 具体怎么操作呢

文档里有写的哦

**Comment by pecmd** [comment]
遇到了同样的问题，如果把web_src\src\components\common\jessibuca.vue文件中改成的height改成100%，删除掉min-height，分屏预览中会正常，但是国标设备的播放jessibuca播放器会消失。
![image](https://github.com/648540858/wvp-GB28181-pro/assets/17865631/29a466c8-67ac-4ea1-990f-dc16958a2eb9)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/17865631/3e188355-6dee-4f28-9e07-08b06a5b74e4)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/17865631/600ac49a-301b-4446-8b0b-4faadd9071fe)

**Comment by miaofeifu** [comment]
这个问题大神们完美解决了么？

**Comment by miaofeifu** [comment]
> 遇到了同样的问题，如果把web_src\src\components\common\jessibuca.vue文件中改成的height改成100%，删除掉min-height，分屏预览中会正常，但是国标设备的播放jessibuca播放器会消失,不过在拖动浏览器大小时播放窗口会出现，但很快会消失。 ![image](https://private-user-images.githubusercontent.com/17865631/303895621-29a466c8-67ac-4ea1-990f-dc16958a2eb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTUzMDYsIm5iZiI6MTcwODUxNTAwNiwicGF0aCI6Ii8xNzg2NTYzMS8zMDM4OTU2MjEtMjlhNDY2YzgtNjdhYy00ZWExLTk5MGYtZGMxNjk1OGEyZWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDExMzAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZTc1MWM0ZmE4NjI4MTNlODkwMmY0YTI0ZGQ4OGMxYTlmMTNkMzRkMDYzMGE4Y2Q5ZWQ5M2IzODU4ZTAwY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z5o3qQF-krwIcaCGENqSV-atrNGKm3AYnWwYSR3zP_k) ![image](https://private-user-images.githubusercontent.com/17865631/303895655-3e188355-6dee-4f28-9e07-08b06a5b74e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTUzMDYsIm5iZiI6MTcwODUxNTAwNiwicGF0aCI6Ii8xNzg2NTYzMS8zMDM4OTU2NTUtM2UxODgzNTUtNmRlZS00ZjI4LTllMDctMDhiMDZhNWI3NGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDExMzAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YTI3OTQxYzIwNGZkNWViMzZlOTUwMDczMWQ5NTYzMzFlMTRlNjNlMTkyYTZjNGUxZjcwZGYwZmNjM2FjYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iir1KDlhQbQjF93MyHrVEclUIzPy1qfyF-8ZXi8Gs_U) ![image](https://private-user-images.githubusercontent.com/17865631/303895365-600ac49a-301b-4446-8b0b-4faadd9071fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTUzMDYsIm5iZiI6MTcwODUxNTAwNiwicGF0aCI6Ii8xNzg2NTYzMS8zMDM4OTUzNjUtNjAwYWM0OWEtMzAxYi00NDQ2LThiMGItNGZhYWRkOTA3MWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDExMzAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMTU2MGY1MDE4MzE1ZWUxOWY1N2M2OGQwZTVlNmZkNWEyNGExMThlNDEzZTU3ZmQ0NmNjMzk2NTkzMzVhZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wyJA5tyvhJzSHtMRoH15jTgnkLBUz_Ex3IVLWCMEc-0)

大哥您的这个问题解决了么？

**Comment by sichenghe110** [comment]
这样改，就可以了：在 updatePlayerDomSize() 方法下 
![20240223162142](https://github.com/648540858/wvp-GB28181-pro/assets/133625951/572d0595-3379-4444-99c5-aaeb61f629e2)

**Comment by 648540858** [comment]
已修复
