### ISSUE TITLE
BUG wvp的token不固定（10分钟就过期了，有时甚至5分钟就过期了）

### ISSUE THREAD

**Issue by 189xiaobo** [648540858/wvp-GB28181-pro#1293]
**环境信息:**

 - 1. 部署方式： wvp-prp + zlm + assist，这3个都是编译部署
 - 2. 部署环境： ubuntu
 - 3. 端口开放情况：local使用telnet命令验证过，所有端口都没问题
 - 4. 是否是公网部署：局域网
 - 7. 你做过哪些尝试：修改token的过期时间为1天（作者您原来是30天），也是一样的效果
 - 8. 代码更新时间：已经更新到2024年1月份最新代码

**描述错误**
        wvp的token过期快（10分钟就过期了，有时甚至5分钟就过期了）。

**截图**  
      系统接口401异常
      
![image](https://github.com/648540858/wvp-GB28181-pro/assets/158151142/35534bce-c058-4c9e-a610-3d5d6c1a385a)

      
![iss](https://github.com/648540858/wvp-GB28181-pro/assets/158151142/f5126c56-1e01-43d0-ae2a-93044e149f04)

![iss2](https://github.com/648540858/wvp-GB28181-pro/assets/158151142/91030ae0-36a6-4b4b-8feb-692df4e9571e)

**Comment by 648540858** [comment]
你是怎么测试的，我怎么复现你说的问题

**Comment by 189xiaobo** [comment]
可能是环境问题，我在另一套环境下就没有这种事情了。




小波escargot
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月20日(星期二) 上午9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro] BUG wvp的token不固定（10分钟就过期了，有时甚至5分钟就过期了） (Issue #1293)





 
你是怎么测试的，我怎么复现你说的问题

**Comment by 648540858** [comment]
好的，那我关闭了

**Comment by 189xiaobo** [comment]
嗯嗯，好的




小波escargot
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月20日(星期二) 上午9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro] BUG wvp的token不固定（10分钟就过期了，有时甚至5分钟就过期了） (Issue #1293)





 
好的，那我关闭了
