### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by DingKun7** [648540858/wvp-GB28181-pro#1295]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/142068264/260d806f-1745-424e-869a-07e91ed08343)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by DingKun7** [comment]
前段时间正常启动，近期没启动过项目，更新代码后再启动就报错了

**Comment by a24211317** [comment]
你配置文件没有设置主数据源，改下你的配置文件吧

**Comment by DingKun7** [comment]
已解决，是因为作者更新了新的数据源配置文件，没有更新，感谢！
