### ISSUE TITLE
我需要接入几万台摄像机，使用的是TCP被动模式，感觉到了单台服务的性能瓶颈，能不能给个集群的解决方案

### ISSUE THREAD

**Issue by 626484534** [648540858/wvp-GB28181-pro#1298]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你说的瓶颈是点播并发数量吗，这个可以接入多台zlm添加多个节点来解决。
如果是信令瓶颈可以拆分下设备，分布到不同的wvp节点下。
