### ISSUE TITLE
wvp长时间运行会有两个bug

### ISSUE THREAD

**Issue by 626484534** [648540858/wvp-GB28181-pro#1299]
**环境信息:**

 - 1. java -jar启动
 - 2. 麒麟系统
 - 3. 单端口开放
 - 4. 否
 - 5. 否

**描述错误**
1、wvp运行一段时间会有所有的设备无法刷新通道的现象，等个一两天又重新好了，我看了服务，没有重启
2、wvp中的redis到底是如何使用的，哪些数据会大量进入redis，出现过一次redis内存耗尽情况，重启服务，发现wvp使用的redis内存量稳步提升，一天0.2g左右，希望提供解决方案

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
1. 设备心跳间隔设置尽量短点
2. redis问题具体登录进去看看哪些key很多，这个问题没有其他提过，具体看看你的redis和你的使用流程
