### ISSUE TITLE
docker部署 播放超时

### ISSUE THREAD

**Issue by lolkt** [648540858/wvp-GB28181-pro#130]
**zlm 10.0.0.18**

`root@3f0afa3f510d:/zlmediakit# cat config.ini
; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[ffmpeg]
bin=/usr/local/bin/ffmpeg
cmd=%s -fflags nobuffer -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264  -f flv %s
log=./ffmpeg/ffmpeg.log
snap=%s -i %s -y -f mjpeg -t 0.001 %s

[general]
addMuteAudio=1
enableVhost=0
enable_audio=1
flowThreshold=1024
fmp4_demand=0
hls_demand=0
maxStreamWaitMS=15000
mediaServerId=8IDTjV7Kq0nPNBp5
mergeWriteMS=0
modifyStamp=0
publishToHls=1
publishToMP4=0
resetWhenRePlay=1
rtmp_demand=0
rtsp_demand=0
streamNoneReaderDelayMS=18000
ts_demand=0

[hls]
broadcastRecordTs=0
deleteDelaySec=0
fileBufSize=65536
filePath=./www
segDur=2
segNum=3
segRetain=5

[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
enable=1
on_flow_report=
on_http_access=
on_play=http://10.0.0.205:18080/index/hook/on_play
on_publish=http://10.0.0.205:18080/index/hook/on_publish
on_record_mp4=
on_record_ts=
on_rtsp_auth=
on_rtsp_realm=
on_server_started=http://10.0.0.205:18080/index/hook/on_server_started
on_shell_login=http://10.0.0.205:18080/index/hook/on_shell_login
on_stream_changed=http://10.0.0.205:18080/index/hook/on_stream_changed
on_stream_none_reader=http://10.0.0.205:18080/index/hook/on_stream_none_reader
on_stream_not_found=http://10.0.0.205:18080/index/hook/on_stream_not_found
timeoutSec=20

[http]
charSet=utf-8
dirMenu=1
keepAliveSecond=15
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:8548753,branch:master,build time:Jul 16 2021 06:31:36)</center></body></html>
port=8080
rootPath=./www
sendBufSize=65536
sslport=443

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[record]
appName=record
fastStart=0
fileBufSize=65536
filePath=./www
fileRepeat=0
fileSecond=3600
sampleMS=500

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=1935
sslport=19350

[rtp]
audioMtuSize=600
videoMtuSize=1400

[rtp_proxy]
dumpDir=
port=10000
timeoutSec=15

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
port=554
sslport=332

[shell]
maxReqSize=1024
port=9000

; } ---`

**Comment by lolkt** [comment]
端口映射
`0.0.0.0:10000  10000/tcp
0.0.0.0:10000  10000/udp
0.0.0.0:10100  10100/tcp
0.0.0.0:10100  10100/udp
0.0.0.0:10101  10101/tcp
0.0.0.0:10101  10101/udp
0.0.0.0:10102  10102/tcp
0.0.0.0:10102  10102/udp
0.0.0.0:10103  10103/tcp
0.0.0.0:10103  10103/udp
0.0.0.0:10104  10104/tcp
0.0.0.0:10104  10104/udp
0.0.0.0:10105  10105/tcp
0.0.0.0:10105  10105/udp
0.0.0.0:10106  10106/tcp
0.0.0.0:10106  10106/udp
0.0.0.0:10107  10107/tcp
0.0.0.0:10107  10107/udp
0.0.0.0:10108  10108/tcp
0.0.0.0:10108  10108/udp
0.0.0.0:10109  10109/tcp
0.0.0.0:10109  10109/udp
0.0.0.0:10110  10110/tcp
0.0.0.0:10110  10110/udp
0.0.0.0:10111  10111/tcp
0.0.0.0:10111  10111/udp
0.0.0.0:10112  10112/tcp
0.0.0.0:10112  10112/udp
0.0.0.0:10113  10113/tcp
0.0.0.0:10113  10113/udp
0.0.0.0:10114  10114/tcp
0.0.0.0:10114  10114/udp
0.0.0.0:10115  10115/tcp
0.0.0.0:10115  10115/udp
0.0.0.0:10116  10116/tcp
0.0.0.0:10116  10116/udp
0.0.0.0:10117  10117/tcp
0.0.0.0:10117  10117/udp
0.0.0.0:10118  10118/tcp
0.0.0.0:10118  10118/udp
0.0.0.0:10119  10119/tcp
0.0.0.0:10119  10119/udp
0.0.0.0:10120  10120/tcp
0.0.0.0:10120  10120/udp
0.0.0.0:10121  10121/tcp
0.0.0.0:10121  10121/udp
0.0.0.0:10122  10122/tcp
0.0.0.0:10122  10122/udp
0.0.0.0:10123  10123/tcp
0.0.0.0:10123  10123/udp
0.0.0.0:10124  10124/tcp
0.0.0.0:10124  10124/udp
0.0.0.0:10125  10125/tcp
0.0.0.0:10125  10125/udp
0.0.0.0:10126  10126/tcp
0.0.0.0:10126  10126/udp
0.0.0.0:10127  10127/tcp
0.0.0.0:10127  10127/udp
0.0.0.0:10128  10128/tcp
0.0.0.0:10128  10128/udp
0.0.0.0:10129  10129/tcp
0.0.0.0:10129  10129/udp
0.0.0.0:10130  10130/tcp
0.0.0.0:10130  10130/udp
0.0.0.0:10131  10131/tcp
0.0.0.0:10131  10131/udp
0.0.0.0:10132  10132/tcp
0.0.0.0:10132  10132/udp
0.0.0.0:10133  10133/tcp
0.0.0.0:10133  10133/udp
0.0.0.0:10134  10134/tcp
0.0.0.0:10134  10134/udp
0.0.0.0:10135  10135/tcp
0.0.0.0:10135  10135/udp
0.0.0.0:10136  10136/tcp
0.0.0.0:10136  10136/udp
0.0.0.0:10137  10137/tcp
0.0.0.0:10137  10137/udp
0.0.0.0:10138  10138/tcp
0.0.0.0:10138  10138/udp
0.0.0.0:10139  10139/tcp
0.0.0.0:10139  10139/udp
0.0.0.0:10140  10140/tcp
0.0.0.0:10140  10140/udp
0.0.0.0:10141  10141/tcp
0.0.0.0:10141  10141/udp
0.0.0.0:10142  10142/tcp
0.0.0.0:10142  10142/udp
0.0.0.0:10143  10143/tcp
0.0.0.0:10143  10143/udp
0.0.0.0:10144  10144/tcp
0.0.0.0:10144  10144/udp
0.0.0.0:10145  10145/tcp
0.0.0.0:10145  10145/udp
0.0.0.0:10146  10146/tcp
0.0.0.0:10146  10146/udp
0.0.0.0:10147  10147/tcp
0.0.0.0:10147  10147/udp
0.0.0.0:10148  10148/tcp
0.0.0.0:10148  10148/udp
0.0.0.0:10149  10149/tcp
0.0.0.0:10149  10149/udp
0.0.0.0:10150  10150/tcp
0.0.0.0:10150  10150/udp
0.0.0.0:10151  10151/tcp
0.0.0.0:10151  10151/udp
0.0.0.0:10152  10152/tcp
0.0.0.0:10152  10152/udp
0.0.0.0:10153  10153/tcp
0.0.0.0:10153  10153/udp
0.0.0.0:10154  10154/tcp
0.0.0.0:10154  10154/udp
0.0.0.0:10155  10155/tcp
0.0.0.0:10155  10155/udp
0.0.0.0:10156  10156/tcp
0.0.0.0:10156  10156/udp
0.0.0.0:10157  10157/tcp
0.0.0.0:10157  10157/udp
0.0.0.0:10158  10158/tcp
0.0.0.0:10158  10158/udp
0.0.0.0:10159  10159/tcp
0.0.0.0:10159  10159/udp
0.0.0.0:10160  10160/tcp
0.0.0.0:10160  10160/udp
0.0.0.0:10161  10161/tcp
0.0.0.0:10161  10161/udp
0.0.0.0:10162  10162/tcp
0.0.0.0:10162  10162/udp
0.0.0.0:10163  10163/tcp
0.0.0.0:10163  10163/udp
0.0.0.0:10164  10164/tcp
0.0.0.0:10164  10164/udp
0.0.0.0:10165  10165/tcp
0.0.0.0:10165  10165/udp
0.0.0.0:10166  10166/tcp
0.0.0.0:10166  10166/udp
0.0.0.0:10167  10167/tcp
0.0.0.0:10167  10167/udp
0.0.0.0:10168  10168/tcp
0.0.0.0:10168  10168/udp
0.0.0.0:10169  10169/tcp
0.0.0.0:10169  10169/udp
0.0.0.0:10170  10170/tcp
0.0.0.0:10170  10170/udp
0.0.0.0:10171  10171/tcp
0.0.0.0:10171  10171/udp
0.0.0.0:10172  10172/tcp
0.0.0.0:10172  10172/udp
0.0.0.0:10173  10173/tcp
0.0.0.0:10173  10173/udp
0.0.0.0:10174  10174/tcp
0.0.0.0:10174  10174/udp
0.0.0.0:10175  10175/tcp
0.0.0.0:10175  10175/udp
0.0.0.0:10176  10176/tcp
0.0.0.0:10176  10176/udp
0.0.0.0:10177  10177/tcp
0.0.0.0:10177  10177/udp
0.0.0.0:10178  10178/tcp
0.0.0.0:10178  10178/udp
0.0.0.0:10179  10179/tcp
0.0.0.0:10179  10179/udp
0.0.0.0:10180  10180/tcp
0.0.0.0:10180  10180/udp
0.0.0.0:10181  10181/tcp
0.0.0.0:10181  10181/udp
0.0.0.0:10182  10182/tcp
0.0.0.0:10182  10182/udp
0.0.0.0:10183  10183/tcp
0.0.0.0:10183  10183/udp
0.0.0.0:10184  10184/tcp
0.0.0.0:10184  10184/udp
0.0.0.0:10185  10185/tcp
0.0.0.0:10185  10185/udp
0.0.0.0:10186  10186/tcp
0.0.0.0:10186  10186/udp
0.0.0.0:10187  10187/tcp
0.0.0.0:10187  10187/udp
0.0.0.0:10188  10188/tcp
0.0.0.0:10188  10188/udp
0.0.0.0:10189  10189/tcp
0.0.0.0:10189  10189/udp
0.0.0.0:10190  10190/tcp
0.0.0.0:10190  10190/udp
0.0.0.0:10191  10191/tcp
0.0.0.0:10191  10191/udp
0.0.0.0:10192  10192/tcp
0.0.0.0:10192  10192/udp
0.0.0.0:10193  10193/tcp
0.0.0.0:10193  10193/udp
0.0.0.0:10194  10194/tcp
0.0.0.0:10194  10194/udp
0.0.0.0:10195  10195/tcp
0.0.0.0:10195  10195/udp
0.0.0.0:10196  10196/tcp
0.0.0.0:10196  10196/udp
0.0.0.0:10197  10197/tcp
0.0.0.0:10197  10197/udp
0.0.0.0:10198  10198/tcp
0.0.0.0:10198  10198/udp
0.0.0.0:10199  10199/tcp
0.0.0.0:10199  10199/udp
0.0.0.0:10200  10200/tcp
0.0.0.0:10200  10200/udp
0.0.0.0:1935  1935/tcp
0.0.0.0:19350  19350/tcp
0.0.0.0:332  332/tcp
0.0.0.0:332  332/udp
0.0.0.0:443  443/tcp
0.0.0.0:443  443/udp
0.0.0.0:554  554/tcp
0.0.0.0:554  554/udp
0.0.0.0:32878  80/tcp
0.0.0.0:8080  8080/tcp
0.0.0.0:8080  8080/udp`

**Comment by lolkt** [comment]
**wvp 10.0.0.205**

`spring:
    # REDIS数据库配置
    redis:
        # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
        host: 10.0.0.18
        # [必须修改] 端口号
        port: 6379
        # [可选] 数据库 DB
        database: 6
        # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        password:
        # [可选] 超时时间
        timeout: 10000
    # [可选] jdbc数据库配置, 项目使用sqlite作为数据库，一般不需要配置
    datasource:
        # 使用mysql 打开23-28行注释， 删除29-36行
         name: wvp
         url: jdbc:mysql://10.0.0.77:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true
         username: telSalesLottery
         password: e%kqkCa1VWSLvLu9
         type: com.alibaba.druid.pool.DruidDataSource
         driver-class-name: com.mysql.cj.jdbc.Driver
#        name: eiot
#        url: jdbc:sqlite::resource:wvp.sqlite
#        username:
#        password:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name:  org.sqlite.JDBC
#        max-active: 1
#        min-idle: 1

# [可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 18080

# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: 10.0.0.205
    # [可选] 28181服务监听的端口
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 6501000100
    # [可选]
    id: 65010001002000000001
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: vizhuo2008

#zlm 默认服务器配置
media:
    # [必须修改] zlm服务器的内网IP
    ip: 10.0.0.18
    # [可选] 返回流地址时的ip，置空使用 media.ip
    stream-ip: 10.0.0.18
    # [可选] wvp在国标信令中使用的ip，此ip为摄像机可以访问到的ip， 置空使用 media.ip
    sdp-ip: 10.0.0.18
    # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip
    hook-ip: 10.0.0.205
    # [必须修改] zlm服务器的http.port
    http-port: 8080
    # [可选] zlm服务器的http.sslport, 置空使用zlm配置文件配置
    http-ssl-port: 443
    # [可选] zlm服务器的rtmp.port, 置空使用zlm配置文件配置
    rtmp-port: 1935
    # [可选] zlm服务器的rtmp.sslport, 置空使用zlm配置文件配置
    rtmp-ssl-port: 19350
    # [可选] zlm服务器的 rtp_proxy.port, 置空使用zlm配置文件配置
    rtp-proxy-port: 10000
    # [可选] zlm服务器的 rtsp.port, 置空使用zlm配置文件配置
    rtsp-port: 554
    # [可选] zlm服务器的 rtsp.sslport, 置空使用zlm配置文件配置
    rtsp-ssl-port: 332
    # [可选] 是否自动配置ZLM, 如果希望手动配置ZLM, 可以设为false, 不建议新接触的用户修改
    auto-config: true
    # [可选] zlm服务器的hook.admin_params=secret
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    # [可选] zlm服务器的general.streamNoneReaderDelayMS
    stream-none-reader-delay-ms:  18000  # 无人观看多久自动关闭流, -1表示永不自动关闭,即 关闭按需拉流
    # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
    rtp:
        # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
        enable: true
        # [可选] 在此范围内选择端口用于媒体流传输,
        port-range: 10100,10200 # 端口范围
    # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
    record-assist-port: 0


# [可选] 日志配置, 一般不需要改
logging:
    file:
        name: logs/wvp.log
        max-history: 30
        max-size: 10MB
        total-size-cap: 300MB
    level:
        com.genersoft.iot: debug
        com.genersoft.iot.vmp.storager.dao: info
# [根据业务需求配置]
user-settings:
    # 推流直播是否录制
    record-push-live: true

# 在线文档： swagger-ui（生产环境建议关闭）
springfox:
    documentation:
        swagger-ui:
            enabled: true`

**Comment by lolkt** [comment]
**wvp  10.0.0.205**


spring:
    # REDIS数据库配置
    redis:
        # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
        host: 10.0.0.18
        # [必须修改] 端口号
        port: 6379
        # [可选] 数据库 DB
        database: 6
        # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        password:
        # [可选] 超时时间
        timeout: 10000
    # [可选] jdbc数据库配置, 项目使用sqlite作为数据库，一般不需要配置
    datasource:
        # 使用mysql 打开23-28行注释， 删除29-36行
         name: wvp
         url: jdbc:mysql://10.0.0.77:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true
         username: telSalesLottery
         password: e%kqkCa1VWSLvLu9
         type: com.alibaba.druid.pool.DruidDataSource
         driver-class-name: com.mysql.cj.jdbc.Driver
#        name: eiot
#        url: jdbc:sqlite::resource:wvp.sqlite
#        username:
#        password:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name:  org.sqlite.JDBC
#        max-active: 1
#        min-idle: 1

# [可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 18080

# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: 10.0.0.205
    # [可选] 28181服务监听的端口
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 6501000100
    # [可选]
    id: 65010001002000000001
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: vizhuo2008

#zlm 默认服务器配置
media:
    # [必须修改] zlm服务器的内网IP
    ip: 10.0.0.18
    # [可选] 返回流地址时的ip，置空使用 media.ip
    stream-ip: 10.0.0.18
    # [可选] wvp在国标信令中使用的ip，此ip为摄像机可以访问到的ip， 置空使用 media.ip
    sdp-ip: 10.0.0.18
    # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip
    hook-ip: 10.0.0.205
    # [必须修改] zlm服务器的http.port
    http-port: 8080
    # [可选] zlm服务器的http.sslport, 置空使用zlm配置文件配置
    http-ssl-port: 443
    # [可选] zlm服务器的rtmp.port, 置空使用zlm配置文件配置
    rtmp-port: 1935
    # [可选] zlm服务器的rtmp.sslport, 置空使用zlm配置文件配置
    rtmp-ssl-port: 19350
    # [可选] zlm服务器的 rtp_proxy.port, 置空使用zlm配置文件配置
    rtp-proxy-port: 10000
    # [可选] zlm服务器的 rtsp.port, 置空使用zlm配置文件配置
    rtsp-port: 554
    # [可选] zlm服务器的 rtsp.sslport, 置空使用zlm配置文件配置
    rtsp-ssl-port: 332
    # [可选] 是否自动配置ZLM, 如果希望手动配置ZLM, 可以设为false, 不建议新接触的用户修改
    auto-config: true
    # [可选] zlm服务器的hook.admin_params=secret
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    # [可选] zlm服务器的general.streamNoneReaderDelayMS
    stream-none-reader-delay-ms:  18000  # 无人观看多久自动关闭流, -1表示永不自动关闭,即 关闭按需拉流
    # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
    rtp:
        # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
        enable: true
        # [可选] 在此范围内选择端口用于媒体流传输,
        port-range: 10100,10200 # 端口范围
    # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
    record-assist-port: 0


# [可选] 日志配置, 一般不需要改
logging:
    file:
        name: logs/wvp.log
        max-history: 30
        max-size: 10MB
        total-size-cap: 300MB
    level:
        com.genersoft.iot: debug
        com.genersoft.iot.vmp.storager.dao: info
# [根据业务需求配置]
user-settings:
    # 推流直播是否录制
    record-push-live: true

# 在线文档： swagger-ui（生产环境建议关闭）
springfox:
    documentation:
        swagger-ui:
            enabled: true

**Comment by lolkt** [comment]
zlm日志 

`2021-07-26 11:31:21.040 I MediaServer[1-event poller 0] GB28181Process.cpp:194 onRtpDecode | gb_play_34020000001110000003_65010001001320000001 judged to be PS
2021-07-26 11:31:21.048 I MediaServer[1-event poller 0] MediaSource.cpp:383 emitEvent | 媒体注册:hls __defaultVhost__ rtp gb_play_34020000001110000003_65010001001320000001
2021-07-26 11:31:21.048 I MediaServer[1-event poller 0] RtpProcess.cpp:244 operator() | gb_play_34020000001110000003_65010001001320000001(10.0.0.40:62012) 允许RTP推流
2021-07-26 11:31:23.222 I MediaServer[1-event poller 0] Decoder.cpp:224 onTrack | got track: H264
2021-07-26 11:31:23.222 I MediaServer[1-event poller 0] Decoder.cpp:224 onTrack | got track: mpeg4-generic
2021-07-26 11:31:23.222 I MediaServer[1-event poller 0] Decoder.cpp:142 onStream | add track finished
2021-07-26 11:31:23.401 D MediaServer[1-event poller 0] MediaSink.cpp:137 emitAllTrackReady | all track ready use 179ms
2021-07-26 11:31:23.401 I MediaServer[1-event poller 0] MultiMediaSourceMuxer.cpp:286 onAllTrackReady | stream: __defaultVhost__ rtp gb_play_34020000001110000003_65010001001320000001 , codec info: mpeg4-generic[16000/1/16] H264[1280/720/40]
2021-07-26 11:31:23.402 I MediaServer[1-event poller 0] MediaSource.cpp:383 emitEvent | 媒体注册:rtmp __defaultVhost__ rtp gb_play_34020000001110000003_65010001001320000001
2021-07-26 11:31:23.403 I MediaServer[1-event poller 0] MediaSource.cpp:383 emitEvent | 媒体注册:rtsp __defaultVhost__ rtp gb_play_34020000001110000003_65010001001320000001
2021-07-26 11:31:23.404 I MediaServer[1-event poller 0] MediaSource.cpp:383 emitEvent | 媒体注册:ts __defaultVhost__ rtp gb_play_34020000001110000003_65010001001320000001
2021-07-26 11:31:23.511 I MediaServer[1-event poller 0] MediaSource.cpp:383 emitEvent | 媒体注册:fmp4 __defaultVhost__ rtp gb_play_34020000001110000003_65010001001320000001
2021-07-26 11:31:37.032 W MediaServer[1-event poller 0] HttpSession.cpp:124 onError | 140702591773296(10.0.0.205:63476) session timeouted
2021-07-26 11:31:37.032 T MediaServer[1-event poller 0] HttpSession.cpp:31 ~HttpSession | 140702591773296(10.0.0.205:63476)
2021-07-26 11:31:41.511 W MediaServer[1-event poller 0] MediaSource.cpp:540 operator() | 无人观看事件:fmp4/__defaultVhost__/rtp/gb_play_34020000001110000003_65010001001320000001
2021-07-26 11:31:41.538 I MediaServer[1-event poller 0] TcpServer.cpp:36 ~TcpServer | close tcp server 0.0.0.0:10112
2021-07-26 11:31:41.538 W MediaServer[1-event poller 0] RtpSelector.cpp:149 close | close media:fmp4/__defaultVhost__/rtp/gb_play_34020000001110000003_65010001001320000001 0
2021-07-26 11:31:41.538 W MediaServer[1-event poller 0] RtpProcess.cpp:51 ~RtpProcess | gb_play_34020000001110000003_65010001001320000001(10.0.0.40:62012) RTP推流器(__defaultVhost__/rtp/gb_play_34020000001110000003_65010001001320000001)断开,耗时(s):20
2021-07-26 11:31:41.539 I MediaServer[1-event poller 0] MediaSource.cpp:383 emitEvent | 媒体注销:ts __defaultVhost__ rtp gb_play_34020000001110000003_65010001001320000001
2021-07-26 11:31:41.546 I MediaServer[1-event poller 0] MediaSource.cpp:383 emitEvent | 媒体注销:hls __defaultVhost__ rtp gb_play_34020000001110000003_65010001001320000001
2021-07-26 11:31:41.547 I MediaServer[1-event poller 0] MediaSource.cpp:383 emitEvent | 媒体注销:rtsp __defaultVhost__ rtp gb_play_34020000001110000003_65010001001320000001
2021-07-26 11:31:41.547 I MediaServer[1-event poller 0] MediaSource.cpp:383 emitEvent | 媒体注销:rtmp __defaultVhost__ rtp gb_play_34020000001110000003_65010001001320000001
2021-07-26 11:31:41.548 I MediaServer[1-event poller 0] MediaSource.cpp:383 emitEvent | 媒体注销:fmp4 __defaultVhost__ rtp gb_play_34020000001110000003_65010001001320000001`

**Comment by 648540858** [comment]
自行查找配置的问题，你的信息太多我我没时间一点看，启动命令参考wiki

**Comment by lolkt** [comment]
[](url)

**Comment by lolkt** [comment]
![QQ截图20210726115154](https://user-images.githubusercontent.com/3078737/126931153-03d78040-76c6-4ef3-a786-e165872acc1c.png)

**Comment by 648540858** [comment]
建议使用docker 1.1.9版本测试，最新版使用的最新主线可能有问题。

**Comment by lolkt** [comment]
@648540858 测试不行

**Comment by 648540858** [comment]
具体，分析，抓个包看下。

**Comment by 648540858** [comment]
我暂时关闭了，这不是代码问题，应该是你的配置问题。仍有问题你再打开。
