### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by arvinhan** [648540858/wvp-GB28181-pro#1300]
ubantu20
-desktop:~/Documents/wvp-GB28181-pro$ **sudo mvn package**
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.genersoft:wvp-pro:jar:2.7.0
[WARNING] 'dependencies.dependency.systemPath' for com.kingbase:kingbase8:jar should not point at files within the project directory, ${basedir}/libs/jdbc-aarch/kingbase8-8.6.0.jar will be unresolvable by dependent projects @ line 155, column 16
[WARNING] 'dependencies.dependency.systemPath' for com.kingbase:kingbase8:jar should not point at files within the project directory, ${basedir}/libs/jdbc-x86/kingbase8-8.6.0.jar will be unresolvable by dependent projects @ line 162, column 16
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.kingbase:kingbase8:jar -> duplicate declaration of version 8.6.0 @ line 157, column 15
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.springdoc:springdoc-openapi-ui:jar -> duplicate declaration of version 1.6.10 @ line 193, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] -----------------------< com.genersoft:wvp-pro >------------------------
[INFO] Building web video platform 2.7.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from nexus-aliyun: https://maven.aliyun.com/repository/public/com/baomidou/dynamic-datasource-spring-boot-starter/3.6.1/dynamic-datasource-spring-boot-starter-3.6.1.pom
Downloading from alimaven: http://maven.aliyun.com/nexus/content/groups/public/com/baomidou/dynamic-datasource-spring-boot-starter/3.6.1/dynamic-datasource-spring-boot-starter-3.6.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.692 s
[INFO] Finished at: 2024-01-31T20:43:26+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wvp-pro: Could not resolve dependencies for project com.genersoft:wvp-pro:jar:2.7.0: Failed to collect dependencies at com.baomidou:dynamic-datasource-spring-boot-starter:jar:3.6.1: Failed to read artifact descriptor for com.baomidou:dynamic-datasource-spring-boot-starter:jar:3.6.1: Could not transfer artifact com.baomidou:dynamic-datasource-spring-boot-starter:pom:3.6.1 from/to nexus-aliyun (https://maven.aliyun.com/repository/public): Transfer failed for https://maven.aliyun.com/repository/public/com/baomidou/dynamic-datasource-spring-boot-starter/3.6.1/dynamic-datasource-spring-boot-starter-3.6.1.pom: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by mengxing2017** [comment]
你的maven版本和jdk版本说一下

**Comment by arvinhan** [comment]
> mengxing2017

desktop:~$ mvn -v
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.21, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-91-generic", arch: "amd64", family: "unix"

desktop:~$ java -version
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

**Comment by 648540858** [comment]
检查网络情况，可能是依赖包没下载下来。

**Comment by arvinhan** [comment]
> 检查网络情况，可能是依赖包没下载下来。

网络 ping google.com也是通的

**Comment by 648540858** [comment]
我说的依赖是npm仓库的内容，你可以把 package-lock.json删除重新执行npm i
