### ISSUE TITLE
端口开放

### ISSUE THREAD

**Issue by 960243800** [648540858/wvp-GB28181-pro#1301]
**环境信息:**

 - 1. 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
我现在wvp zlm都部署在内网，摄像头在公网，查看视频视频监控只要在内网查看，需要把哪些端口映射到公网？哪些端口要内网要放开？ip要怎么配置？
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
默认情况下，映射5060tcp/udp、30000-30500tcp/udp，sdp-ip配置公网ip

**Comment by 960243800** [comment]
sip-ip 配置内网ip吗？还有个问题sip-ip如果不配本机的ip项目无法启动是正常的吗

**Comment by DingKun7** [comment]
sip-ip应该是配置内网IP，我这边现在也是摄像头在公网，项目都在内网，sdp-ip是配置摄像头的IP？还是映射5060的那个IP？

**Comment by mengxing2017** [comment]
sip-ip是本机ip,sdp-ip是公网ip

**Comment by DingKun7** [comment]
摄像头那边的"SIP服务器地址"你是怎么配置的？

**Comment by mengxing2017** [comment]
填公网ip

**Comment by DingKun7** [comment]
方便加个V吗？共同交流。Yes15996932533

**Comment by 960243800** [comment]
谢谢/抱拳

**Comment by 960243800** [comment]
wvp 所部署的服务器需要能访问公网吗

**Comment by mengxing2017** [comment]
这个问题问得........你自己试一下咯

**Comment by LiaoXH** [comment]
> sip-ip是本机ip,sdp-ip是公网ip

由于服务器架构网络问题，wvp+ZLM是在内网部署，设备需要公网接入，通过一个公网ip映射到内网服务器的端口，因为限制了内网无法访问公网ip，那此时的sdp-ip要如何配置？配置公网ip的话无法发送sdp信令，内网ip的话摄像头无法拿到sdp

**Comment by mengxing2017** [comment]
> > sip-ip是本机ip,sdp-ip是公网ip
> 
> 由于服务器架构网络问题，wvp+ZLM是在内网部署，设备需要公网接入，通过一个公网ip映射到内网服务器的端口，因为限制了内网无法访问公网ip，那此时的sdp-ip要如何配置？配置公网ip的话无法发送sdp信令，内网ip的话摄像头无法拿到sdp

sdp-ip使用公网ip,sdp-ip只是配置的zlm的收流ip

**Comment by LiaoXH** [comment]
内网架构使用公网ip，无法发送点播的sdp信令，内网服务器无法访问公网ip

**Comment by mengxing2017** [comment]
> 内网架构使用公网ip，无法发送点播的sdp信令，内网服务器无法访问公网ip

你这个是别的问题

**Comment by LiaoXH** [comment]
是，所以想问下解决方案，目前没使用国标了，转rtmp推流注册了 ，这个issue先关闭了；网络问题还是无法处理
