### ISSUE TITLE
BUG--云端录像时间破版,录像没有画面只有声音

### ISSUE THREAD

**Issue by jack361** [648540858/wvp-GB28181-pro#1302]
**环境信息:**
部署方式 zlm都是编译部署
部署环境 ubuntu
端口开放情况 全开放,关闭了防火墙
是否是公网部署 公网部署
是否使用https 没使用https
方便的话提供下使用的设备品牌或平台 tp-link半球机,支持28181
你做过哪些尝试 重新编译数次,我朋友也遇到同样的问题
代码更新时间2024年1月30编译的最新代码

**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![QQ截图20240201142454](https://github.com/648540858/wvp-GB28181-pro/assets/37525249/94a157fd-8737-4d9a-9ef6-b0df30fa8b5d)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
什么是破版，不理解。先关闭了。

**Comment by jack361** [comment]
图片上传失败,我重新上传下
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37525249/96214a8b-5757-4483-ba9a-e50ebdc8370d)

**Comment by jack361** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37525249/96ddbad6-dcab-4211-9de6-03ed7b40c089)

**Comment by jack361** [comment]
@648540858  648540858 您看下上面的图哦
