### ISSUE TITLE
技术咨询  请问可以主码流和辅码流同时接入平台吗

### ISSUE THREAD

**Issue by luhengyu1** [648540858/wvp-GB28181-pro#1304]
**内容描述:**
如题，请问是否支持一个摄像头的主码流和辅码流同时接入平台进行点播？

**Comment by 648540858** [comment]
不支持的，一般的设备就一个视频通道，只能选择其中一个。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月2日(周五) 上午9:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [648540858/wvp-GB28181-pro] 技术咨询  请问可以主码流和辅码流同时接入平台吗 (Issue #1304)




 
内容描述:
 如题，请问是否支持一个摄像头的主码流和辅码流同时接入平台进行点播？

**Comment by luhengyu1** [comment]
> 不支持的，一般的设备就一个视频通道，只能选择其中一个。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年2月2日(周五) 上午9:37 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [648540858/wvp-GB28181-pro] 技术咨询 请问可以主码流和辅码流同时接入平台吗 (Issue #1304) 内容描述: 如题，请问是否支持一个摄像头的主码流和辅码流同时接入平台进行点播？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

也就是说，主码流和子码流不管如何切换，都是走的唯一的通道吗？
那是否可以控制点播哪个流？
我在海康摄像头本身的预览界面观看，如果卡顿他会切换子码流，请问wvp这边是否能切换或者控制？

**Comment by 648540858** [comment]
国标没办法这么控制。
