### ISSUE TITLE
bug-报警信息没有详情

### ISSUE THREAD

**Issue by jack361** [648540858/wvp-GB28181-pro#1305]
**环境信息:**

部署方式 zlm都是编译部署
部署环境 ubuntu
端口开放情况 全开放,关闭了防火墙
是否是公网部署 公网部署
是否使用https 没使用https
方便的话提供下使用的设备品牌或平台 tp-link半球机,支持28181
你做过哪些尝试 重新编译数次,我朋友也遇到同样的问题
代码更新时间2024年1月30编译的最新代码

**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![QQ截图20240202115201](https://github.com/648540858/wvp-GB28181-pro/assets/37525249/ed2f477b-c937-4d5a-8657-05fcf1931b80)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
消息内容是设备上报的，没有就可能是设备没上报，可以抓个包确认下
