### ISSUE TITLE
希望wVP实现的新功能，需要支持语音对讲功能

### ISSUE THREAD

**Issue by thylxl** [648540858/wvp-GB28181-pro#1306]
**项目的详细需求**
音频接入，语音对讲功能
**这样的实现什么作用**
方便操作

**Comment by 648540858** [comment]
已支持提前付费提供，有需要可以发邮件给我



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月2日(周五) 下午3:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [648540858/wvp-GB28181-pro] 希望wVP实现的新功能，需要支持语音对讲功能 (Issue #1306)




 
项目的详细需求
 音频接入，语音对讲功能
 这样的实现什么作用
 方便操作

**Comment by mrluoqiang** [comment]
> 已支持提前付费提供，有需要可以发邮件给我
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年2月2日(周五) 下午3:29 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [648540858/wvp-GB28181-pro] 希望wVP实现的新功能，需要支持语音对讲功能 (Issue #1306) 项目的详细需求 音频接入，语音对讲功能 这样的实现什么作用 方便操作 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

这个语音对讲现在还是付费的嘛
