### ISSUE TITLE
技术咨询-关于海康NVR报资源不足

### ISSUE THREAD

**Issue by zeawayC** [648540858/wvp-GB28181-pro#1309]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 centos
 - 3. 端口开放情况 防火墙关闭
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 设备NVR IPC 品牌 大华、海康

**内容描述:**
目前发现平台+海康NVR 运行时间超过2周左右的时间，无论发起点播还是回放，海康NVR会返回
start playback or download failed: maybe net resource is not enough or rtp session false

实际上把所有的流都停止了（ZLM调用getMediaList接口查看 已经没有流信息了）还是会报这个错误
尝试登录NVR 查看网络资源统计输出带宽已经占满，而且感觉输出带宽会随着使用时间一直增长，最终到阈值后报上面的错误
下面这张图是使用了一周左右的输出带宽情况，目前不太清楚是什么导致的输出带宽一直增长不释放
**截图**  
<img width="1648" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/49052011/ede00e03-7519-4426-b42e-d43b5b679cf1">

**Comment by 648540858** [comment]
这个错误是设备报的，你可以把设备重启再测试下。

**Comment by zeawayC** [comment]
尝试过重启NVR设备后，恢复正常。过一段时间带宽就又占满了。
也尝试过拔掉NVR的网线，发现网线拔掉后，相应的输出带宽也后减少很多。
目前还不清楚是不是NVR本身的问题。

**Comment by zeawayC** [comment]
> 这个错误是设备报的，你可以把设备重启再测试下。

尝试过重启NVR设备后，恢复正常。过一段时间带宽就又占满了。
也尝试过拔掉NVR的网线，发现网线拔掉后，相应的输出带宽也后减少很多。
目前还不清楚是不是NVR本身的问题。

**Comment by 648540858** [comment]
那就是nvr占用了太多带宽，多半是负载太高了

**Comment by kumv-net** [comment]
有查到原因吗 我最近出现 nvr5个摄像头 2m*5 总上传带宽10m左右，12小时左右zlm服务器带宽20-30m，大概是摄像头重复推流了，只能暂时每12小时重启一次nvr但是视频业务会中断5分钟很不好。
