### ISSUE TITLE
官网进不去,看不了技术文档BUG

### ISSUE THREAD

**Issue by luwenteng** [648540858/wvp-GB28181-pro#1311]
![S_2024-02-05_18-23-37](https://github.com/648540858/wvp-GB28181-pro/assets/100819955/52aaf79e-92da-4f6e-b647-dcca184dbd56)
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by scdn** [comment]
https://wvp-gb-28181-pro.vercel.app/#/  这个链接可以访问

**Comment by 648540858** [comment]
已经恢复了。gitee pages好像出问题了

**Comment by 648540858** [comment]
> https://wvp-gb-28181-pro.vercel.app/#/ 这个链接可以访问

这是什么神仙网站，之前还没见过

**Comment by scdn** [comment]
> > https://wvp-gb-28181-pro.vercel.app/#/ 这个链接可以访问
> 
> 这是什么神仙网站，之前还没见过

<img width="397" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/43884938/92611484-41c1-4c9b-8870-f2c1d7fb0e73">

**Comment by 648540858** [comment]
好的，不知道啥时候部署到那里去了
