### ISSUE TITLE
BUG 大华的人像抓拍设备，添加到平台后，视频画面是倒转的。

### ISSUE THREAD

**Issue by snowy0375** [648540858/wvp-GB28181-pro#1312]
**环境信息:**

 - 1. 部署方式编译wvp-pro + zlm都是编译部署/
 - 2. 部署环境  centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题

BUG 大华的人像抓拍设备，添加到平台后，默认的视频画面是倒转的（实际摄像头正常安装的）。摄像头配置画面翻转后，平台上的画面翻转正常了，但是视频中的通道名称和时间仍然未翻转正常。

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![Uploading 微信图片_20240216113457.png…]()
![Uploading 微信图片_20240216113457.png…]()

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
在摄像机的管理页面上播放下视频看看是不是也是倒置的，半球机如果直接放在桌子上，默认的配置会使看到的画面倒置，需要自己在视频管理里设置一下。
