### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by miaofeifu** [648540858/wvp-GB28181-pro#1313]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos
 - 3. 端口开放情况 全部开放
 - 4. 是否是公网部署  公网部署
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 大华
 - 7. 你做过哪些尝试 局域网部署成功
 - 8. 代码更新时间 最新

**内容描述:**
局域网部署成功，公网部署登录一直转圈
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
播放转圈圈？

**Comment by miaofeifu** [comment]
> 播放转圈圈？

登录的时候转圈，已经解决了，是mysql编码导致的。目前还有一个问题 就是分屏播放的时候尺寸不对，至今没找到解决方法
