### ISSUE TITLE
上级平台如何看到下级的云端录像，以及倍数播放

### ISSUE THREAD

**Issue by WalkerPlus** [648540858/wvp-GB28181-pro#1314]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 wvp-pro编译 + zlm(docker)
 - 2. 部署环境 windows / ubuntu/ centos ...
 ubuntu
 - 3. 端口开放情况
 全开放
 - 4. 是否是公网部署 
否
 - 5. 是否使用https
 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
 - 最新代码

**内容描述:**
上级平台如何看到下级的云端录像，以及倍数播放
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
上级可以通过国标级联查看下级所属设备的国标录像，不支持查看下级的云端录像
