### ISSUE TITLE
技术咨询- 公网 多端口模式 收流 无法开放 30000 - 30500 这么多端口的问题

### ISSUE THREAD

**Issue by snowy0375** [648540858/wvp-GB28181-pro#1316]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
公网部署下，rtp收流的多端口模式， 公网IP无法开放 30000 - 30500 这么多端口，我看还无法设置 10个端口随机收流，好像要设置最低36个端口随机，这个有什么特殊处理吗，公网开放10个端口还行，开放几百个网络安全不允许啊。有什么办法解决吗。 单端口的情况下，我看经常出现点播超时。

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by xu-bin-bin** [comment]
单端口，同时200个设备点播都是没有问题的，点播超时也可能是设备端网络不好导致的。可以把设备设置成变码率，码率上限设置小一点试试。

**Comment by snowy0375** [comment]
> 单端口，同时200个设备点播都是没有问题的，点播超时也可能是设备端网络不好导致的。可以把设备设置成变码率，码率上限设置小一点试试。

你好，多谢回复，单端口我看大概30分钟左右就被强制断开了。 另外多端口模式，能否支持比如10个端口的多端口，现在我看设置10个多端口会报错，说是要求最低得36个端口才行，这个有办法突破吗，公网IP不让开这么多。

**Comment by 648540858** [comment]
zlm的限制，目前没有办法，你需要自行修改zlm或者寻求zlm作者的解答
