### ISSUE TITLE
技术咨询 [更新ZLM 保活信息]尝试链接zml

### ISSUE THREAD

**Issue by z-yulong** [648540858/wvp-GB28181-pro#1317]
**环境信息:**

 - 1. 部署方式 全部编译部署
 - 2. 部署环境  centos 
 - 3. 端口开放情况
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间

**内容描述:**
 启动项目后一直 [更新ZLM 保活信息]尝试链接zml，ip, zml 的server_id，secret均设置正确
**截图**  
![1](https://github.com/648540858/wvp-GB28181-pro/assets/93183094/386e40ae-d318-4c25-809d-a556d2147214)
![2](https://github.com/648540858/wvp-GB28181-pro/assets/93183094/2261550b-a36e-45a6-ab41-9bfa1bbd3195)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by z-yulong** [comment]
2024-02-20 02:44:49.290 W [MediaServer] [4508-event poller 3] WebHook.cpp:194 operator() | hook http://192.168.110.95:8900/index/hook/on_server_keepalive 0ms,failed[network err]:3(connection refused):{
        "data" : 
        {
                "Buffer" : 1163,
                "BufferLikeString" : 139,
                "BufferList" : 0,
                "BufferRaw" : 689,
                "Frame" : 145,
                "FrameImp" : 69,
                "MediaSource" : 7,
                "MultiMediaSourceMuxer" : 1,
                "RtmpPacket" : 66,
                "RtpPacket" : 555,
                "Socket" : 32,
                "TcpClient" : 2,
                "TcpServer" : 23,
                "TcpSession" : 2,
                "UdpServer" : 8,
                "UdpSession" : 0
        },
        "hook_index" : 366,
        "mediaServerId" : "your_server_id"
}

**Comment by z-yulong** [comment]
已解决，redis原因

**Comment by 648540858** [comment]
你是使用了默认的配置文件，建议删除默认配置文件，使用重新生成的配置文件
