### ISSUE TITLE
技术咨询 - 关于对CPU和内存的硬件资源使用问题

### ISSUE THREAD

**Issue by snowy0375** [648540858/wvp-GB28181-pro#1318]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
咨询下，单台主机跑完整的服务，对CPU和内存有最低要求吗，8路1080P 1024码流的视频实时点播，需要多大的硬件配置，更吃CPU还是内存？请指教

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
wvp对内存和cpu的要求都不高
