### ISSUE TITLE
wvp不提供类似NVR的功能吗

### ISSUE THREAD

**Issue by sincebyte** [648540858/wvp-GB28181-pro#1321]
提个问题，如果连接的是ipc设备，wvp不提供类似NVR的功能吗？就是可以直接后台静默写到磁盘内，

**Comment by scdn** [comment]
不是有云端录像吗

**Comment by sincebyte** [comment]
> 不是有云端录像吗
听说：只有在主动点播视频的情况下才会触发云端录像功能

**Comment by mengxing2017** [comment]
配置一下拉流就能实现类似功能了，文档里面有，用wvp实现nvr的功能，成本要比直接买nvr贵多了，老老实实买吧
