### ISSUE TITLE
设备主动注销的时候，设备状态应该从在线更新为离线状态，目前更新成了在线状态

### ISSUE THREAD

**Issue by victor21508103** [648540858/wvp-GB28181-pro#1322]
**环境信息:**
docker容器部署

**描述错误**
设备主动注销的时候，设备状态应该从在线更新为离线状态，目前更新成了在线状态，代码存在bug

**如何复现**
摄像头切换平台或是修改配置信息后保存
**截图**  
![1708670935201](https://github.com/648540858/wvp-GB28181-pro/assets/25023407/c5fd3247-1e55-4202-8169-692408bc8fe5)
![1708671026079](https://github.com/648540858/wvp-GB28181-pro/assets/25023407/174825e2-f7a5-49d2-8cf8-53afe40f6f49)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你的代码不够新，1月18号的提交解决了这个问题
