### ISSUE TITLE
[技术咨询] 搭配录像程序使用时 播放云端录像时 提示You can not download files outside the root directory

### ISSUE THREAD

**Issue by CNPolaris** [648540858/wvp-GB28181-pro#1323]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos 7
 - 3. 端口开放情况 防火墙关闭
 - 4. 是否是公网部署 内网公网都有
 - 5. 是否使用https http
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试 重新部署
 - 8. 代码更新时间

**内容描述:**
wvp-pro+wvp-assist+ZLM都运行再 /root目录下 录像保存到/home/record下 使用云端录像报错 You can not download files outside the root directory
**截图**  
![image.png](https://s2.loli.net/2024/02/23/D9iw4LkBoEzvTbM.png)
**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
不清楚原因，看提示像是你的文件夹没有写入权限

**Comment by xiaohuiL** [comment]
@648540858 新版的云端录像播放和下载，需要修改zlm相关的配置吗？

**Comment by 648540858** [comment]
不需要



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月4日(周一) 下午5:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] [技术咨询] 搭配录像程序使用时 播放云端录像时 提示You can not download files outside the root directory (Issue #1323)




 
@648540858 新版的云端录像播放和下载，需要修改zlm相关的配置吗？

**Comment by xiayongkang111** [comment]
@648540858 我的有写入权限还是报错 
点开地址显示这个报错
You can not download files outside the root directory

**Comment by CNPolaris** [comment]
> @648540858 我的有写入权限还是报错 点开地址显示这个报错 You can not download files outside the root directory

同样，权限都给了的情况下也是无法读取，后面就把录像功能关闭了

**Comment by CNPolaris** [comment]
使用wvp配合的录像程序时，需要在zlm的配置文件里面添加一下录像的存储路径才行
![image.png](https://s2.loli.net/2024/05/07/5wgtcfdjCYSs7Qy.png)

**Comment by Oushinan** [comment]
> 使用wvp配合的录像程序时，需要在zlm的配置文件里面添加一下录像的存储路径才行 ![image.png](https://camo.githubusercontent.com/133d2431afa6e93a3580dc1ff3ee2f8b054ea70de32608b5675b890ba6c3ff4a/68747470733a2f2f73322e6c6f6c692e6e65742f323032342f30352f30372f357767746366646a435953733751792e706e67)

搜索了半天，终于找到正解了，不仅解决了下载问题，还解决了录像不能播放的问题，特意登录上来感谢~
