### ISSUE TITLE
媒体流注册成功，但页面播放一直收流失败

### ISSUE THREAD

**Issue by elegentFrog** [648540858/wvp-GB28181-pro#1328]
![c2ff3a812aaffd241dd9fff67da2024](https://github.com/648540858/wvp-GB28181-pro/assets/45689910/35a9ba2a-5fdf-42d8-bca2-ab247c840430)
![2003ddbc9265a2e3f681e991ee14bce](https://github.com/648540858/wvp-GB28181-pro/assets/45689910/c98269e7-9c74-45a9-beeb-da7dbecf02fa)
直接拉取视频流地址是可以播放的

**Comment by mengxing2017** [comment]
zlm的http端口，udp放通了没

**Comment by elegentFrog** [comment]
云上的服务器，端口全部都放开了

**Comment by elegentFrog** [comment]
![1709127699546](https://github.com/648540858/wvp-GB28181-pro/assets/45689910/a676d1af-f8ff-4b4c-9d71-a9abde39d97c)

**Comment by mengxing2017** [comment]
steam-ip和sdp-ip的ip地址是公网ip地址吗

**Comment by elegentFrog** [comment]
都是公网ip地址，部分配置如下：
media:
  id: hlUqClEo3pex2tAp
  # [必须修改] zlm服务器的内网IP
  ip: 172.16.0.6
  # [必须修改] zlm服务器的http.port
  http-port: 80
  # [可选] 返回流地址时的ip，置空使用 media.ip
  stream-ip: 159.75.140.108
  # [可选] wvp在国标信令中使用的ip，此ip为摄像机可以访问到的ip， 置空使用 media.ip
  sdp-ip: 159.75.140.108
  # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip
  hook-ip: 172.16.0.6
  # [可选] zlm服务器的http.sslport, 置空使用zlm配置文件配置
  http-ssl-port: 443
  # [可选] zlm服务器的hook.admin_params=secret
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc

**Comment by elegentFrog** [comment]
还有哪个地方的配置会影响收流吗

**Comment by mengxing2017** [comment]
启用双网卡也会影响，你这个得了解具体的情况才知道什么原因了

**Comment by mengxing2017** [comment]
你这里应该推流是成功了，应该只是播放那里有问题 ，你 80端口单独配置一下udp:80放通看看，或者检查系统的防火墙有没有关闭

**Comment by elegentFrog** [comment]
80端口已经放开了，防火墙那些都检查了，还是不行

**Comment by elegentFrog** [comment]
![1709263928479](https://github.com/648540858/wvp-GB28181-pro/assets/45689910/8da6cbb9-792e-42f9-b13f-bd97a562ad7a)

**Comment by mengxing2017** [comment]
可以私信我远程看一下

**Comment by elegentFrog** [comment]
如何加您呢？

**Comment by mengxing2017** [comment]
qq 497692831

**Comment by elegentFrog** [comment]
加您了

**Comment by 648540858** [comment]
注意下是不是编码或者码率问题导致这个播放器无法播放，这个播放器不支持太高的码率

**Comment by LiaoXH** [comment]
解决了吗？我这边也遇到这个问题了，udp的流传输拉流播放失败

**Comment by LiaoXH** [comment]
大佬是否可以提供一下稳定使用的两个版本，wvp 以及zlm

**Comment by mengxing2017** [comment]
这个没有，自己测试咯，我还在用2022年五月的版本

**Comment by LiaoXH** [comment]
好的，谢谢
