### ISSUE TITLE
上级平台删除以后，后端仍残留平台信息且定时去注册

### ISSUE THREAD

**Issue by yuansonghui** [648540858/wvp-GB28181-pro#1329]
测试wvp代码版本： 更新至2024-02-20
问题描述：
wvp 平台添加上级国标平台，测试视频点播等功能； 在页面删除上级平台以后， 概率出现上级平台信息残留的情况，导致后端定期得去注册上级平台，产生报错，如下图

![微信图片_20240227164913](https://github.com/648540858/wvp-GB28181-pro/assets/13591186/7233ce1d-e619-4c5e-a3b0-a672f85f6798)

**Comment by 648540858** [comment]
已修复
