### ISSUE TITLE
处理上级订阅时，有一个小bug，请处理下。

### ISSUE THREAD

**Issue by qiaoshubin** [648540858/wvp-GB28181-pro#133]
具体位置在com.genersoft.iot.vmp.gb28181.transmit包下面的SIPProcessorFactory.java中的147-150行，变量processor在注入时，没有注入tcpSipProvider和udpSipProvider，导致后面的类在回复订阅消息时会报出null的错误。

**Comment by 648540858** [comment]
好的，我看下

**Comment by 648540858** [comment]
在144-145行已经注入了呀

**Comment by qiaoshubin** [comment]
@648540858   最新的代码里没有，这是代码的地址：https://github.com/648540858/wvp-GB28181-pro/blob/wvp-28181-2.0/src/main/java/com/genersoft/iot/vmp/gb28181/transmit/SIPProcessorFactory.java
里面的147-150行。我不知道怎么上传图片，看图会方便很多。

**Comment by 648540858** [comment]
明白了

**Comment by 648540858** [comment]
已修复
