### ISSUE TITLE
技术咨询：拉流代理，复制播放地址在谷歌浏览器打开，一直转圈，ZLM报错

### ISSUE THREAD

**Issue by aron030** [648540858/wvp-GB28181-pro#1332]
**环境信息:**

 - 1. 部署方式 编译wvp-pro（2.6.9分支）+zlm
 - 2. 部署环境 windows
 - 3. 端口开放情况
 - 4. 是否是公网部署  否
 - 5. 是否使用https 无
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试 无
 - 8. 代码更新时间

**内容描述:**
拉流代理，复制播放地址在谷歌浏览器打开，一直转圈，ZLM报错
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/52901961/9352f2d9-110d-4723-8927-482b3468e59a)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/52901961/59993d54-cdfb-43d3-9d12-459b80c011f9)
**抓包文件**
  
**日志**
![image](https://github.com/648540858/wvp-GB28181-pro/assets/52901961/59993d54-cdfb-43d3-9d12-459b80c011f9)

**Comment by aron030** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/52901961/93bca159-ed41-4b87-970d-658d759e161d)

**Comment by 648540858** [comment]
确定下你的在网页播放时你的通道还处于点播的状态
