### ISSUE TITLE
BUG 下级内网服务器公网出口地址变化导致离线

### ISSUE THREAD

**Issue by iwanlebron** [648540858/wvp-GB28181-pro#1333]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 centos 
 - 3. 端口开放情况 全部开发
 - 4. 是否是公网部署 上级节点公网部署，下级内网部署
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试  检查公网出口
 - 8. 代码更新时间  20240131

**描述错误**
描述下您遇到的问题
下级和上级通讯时，下级的公网出口会变化，导致下级频繁离线

**如何复现**
有明确复现步骤的问题会很容易被解决
脚本检测到如果下级服务器公网出口离线，则重启wvp，则重新在线

**截图**  

![image](https://github.com/648540858/wvp-GB28181-pro/assets/105045937/ee67cd0c-188c-4853-be70-5c5e11d6d674)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by iwanlebron** [comment]
内网服务器访问公网服务器，内网服务器的公网ip出口变化

**Comment by iwanlebron** [comment]
是否可以优化

**Comment by 648540858** [comment]
你的ip变化了你的设备怎么访问你的服务器，肯定只能离线呀，没有别的办法，国标28181不支持域名。所以只能配置ip

**Comment by iwanlebron** [comment]
下级的wvp 公网出口变了

**Comment by answer666** [comment]
> 你的ip变化了你的设备怎么访问你的服务器，肯定只能离线呀，没有别的办法，国标28181不支持域名。所以只能配置ip

老大你好， 也就是说 不支持 https 协议是吗？
