### ISSUE TITLE
新功能 主码流子码流切换功能不起作用

### ISSUE THREAD

**Issue by luhengyu1** [648540858/wvp-GB28181-pro#1334]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/e60ac352-394e-4047-9648-2d717764c93a)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/e073d3d9-85b7-4a14-9599-1cf57779d765)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/46190d06-f3a6-4e1b-9c50-691c130f9cb1)
根据日志和数据库来看，已经更新过了，但是播放之后看起来似乎没有效果
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/bb7ff092-9fa4-4019-9554-96e91c544626)

**Comment by mengxing2017** [comment]
这个功能应该是给 GB28181-2022版使用的，GB28181-2016不支持子码流切换

**Comment by mengxing2017** [comment]
摄像头的平台配置上看，他有选项的

**Comment by luhengyu1** [comment]
> 摄像头的平台配置上看，他有选项的

明白了，看了下我的海康摄像头只有2016版，谢谢
