### ISSUE TITLE
Unknown column 'channelId' in 'field list'

### ISSUE THREAD

**Issue by ygr757326** [648540858/wvp-GB28181-pro#1335]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
数据位置信息格式处理 接口：/api/position/transform/{deviceId}

{
  "code": 500,
  "msg": "\r\n### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'channelId' in 'field list'\r\n### The error may exist in com/genersoft/iot/vmp/storager/dao/DeviceChannelMapper.java (best guess)\r\n### The error may involve com.genersoft.iot.vmp.storager.dao.DeviceChannelMapper.getChannelsWithoutTransform-Inline\r\n### The error occurred while setting parameters\r\n### SQL: select channelId, device_id, latitude, longitude,latitude_wgs84,longitude_wgs84,latitude_gcj02,longitude_gcj02from wvp_device_channel where device_id = ? and latitude != 0 and  longitude != 0 and(latitude_gcj02=0 or latitude_wgs84=0 or longitude_wgs84= 0 or longitude_gcj02 = 0)\r\n### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'channelId' in 'field list'\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'channelId' in 'field list'"
}

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by scdn** [comment]
查询语句中的通道字段应为"channel_id"

**Comment by scdn** [comment]
另外,实测发现有坐标信息时,latitude  longitude 这两个参数是0的,不为0的是custom_longitude ,custom_longitude ,所以查询时应为 custom_longitude != 0 and  custom_longitude != 0 ,另外from 前需要加一个空格

**Comment by scdn** [comment]
```
   @Select("select channel_id" +
            ", device_id" +
            ", custom_latitude" +
            ", custom_longitude"+
            ",latitude_wgs84"+
            ",longitude_wgs84"+
            ",latitude_gcj02"+
            ",longitude_gcj02 "+
            "from wvp_device_channel where device_id = #{deviceId} " +
            "and custom_latitude != 0 " +
            "and  custom_longitude != 0 " +
            "and(latitude_gcj02=0 or latitude_wgs84=0 or longitude_wgs84= 0 or longitude_gcj02 = 0)")
```

**Comment by ygr757326** [comment]
> 查询语句中的通道字段应为"channel_id"

上面的错误是源码的错误

**Comment by scdn** [comment]
> > 查询语句中的通道字段应为"channel_id"
> 
> 上面的错误是源码的错误

我说的就是源码，这是bug，不是你的原因

**Comment by 648540858** [comment]
更新代码再测试下，很早以前就修复这个问题了

**Comment by scdn** [comment]
<img width="1420" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/43884938/88d2a5e4-520d-42e5-9694-03f39b16faa8">
最新的代码还是channelId
