### ISSUE TITLE
请问有没有实现角色权限功能的计划

### ISSUE THREAD

**Issue by zhengweitang** [648540858/wvp-GB28181-pro#1338]
摄像头可以进行分组，满足不同的角色查看不同的摄像头。

**Comment by yangfeng65** [comment]
我修改了下，实现了这个功能，可以自定义分组，角色可以分配查看不同的分组摄像头，在监控大屏根据角色渲染查看自己所属权限的摄像头。角色还可以分配菜单。

**Comment by zhengweitang** [comment]
怎么联系哥们

**Comment by yangfeng65** [comment]
> 怎么联系哥们

发给你，你加我吧：yfwzhl

**Comment by luogbcn** [comment]
> > 怎么联系哥们
> 
> 发给你，你加我吧：yfwzhl

兄台，给我是微信吗？能也发我一份吗？邮箱：luogbcn@qq.com
