### ISSUE TITLE
录像回放功能咨询

### ISSUE THREAD

**Issue by quxiaohui-debug** [648540858/wvp-GB28181-pro#1339]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
作者您好，录像回放时需要指定开始时间和结束时间，然后返回流地址。但如果中间某个时间段不存在录像文件，请问是怎么处理的呢？还是说在回放之前需要通过录像文件查询接口拿到录像文件列表呢？
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by gl794262724** [comment]
同问
