### ISSUE TITLE
wvp咨询，同步海康设备生僻字显示乱码

### ISSUE THREAD

**Issue by wqhyx** [648540858/wvp-GB28181-pro#1341]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
![企业微信截图_1709544475430](https://github.com/648540858/wvp-GB28181-pro/assets/35256441/47d2d428-fbcf-43e2-bf20-7906b3652d34)
海康上面的生僻字能够正常显示、数据注册到wvp后显示乱码
![企业微信截图_17095445748052](https://github.com/648540858/wvp-GB28181-pro/assets/35256441/38cf45d4-4491-472f-b5b8-d15c77227c3f)

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by wqhyx** [comment]
各位大佬帮忙解答下，谢谢

**Comment by wqhyx** [comment]
日志打印 ，进行编码也是乱码   
![企业微信截图_17095424861874](https://github.com/648540858/wvp-GB28181-pro/assets/35256441/00146457-b330-460a-b830-827c9e73c996)

**Comment by 648540858** [comment]
设备编辑，使用utf8编码，然后刷新通道
