### ISSUE TITLE
【技术咨询】GB28181监控视频点播提示收流超时

### ISSUE THREAD

**Issue by Farrahchen** [648540858/wvp-GB28181-pro#1347]
**环境信息:**

 - 1. 部署方式 ：编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ：centos 
 - 3. 端口开放情况：防火墙已关闭
 - 4. 是否是公网部署 ：是
 - 5. 是否使用https：是
 - 6. 方便的话提供下使用的设备品牌或平台：海康
 - 7. 你做过哪些尝试：检查监控设备状态，检查网络，重启两台服务，重新部署流媒体服务，抓包
 - 8. 代码更新时间：wvp 版本2.6.9

**内容描述:**
问题详情，在zlm讨论区也提交过。但无答复。
https://github.com/ZLMediaKit/ZLMediaKit/issues/3330

**Comment by DistanceTwo** [comment]
我的也是海康录像机，偶现同一个通道播放提示收流超时问题

**Comment by Farrahchen** [comment]
> 我的也是海康录像机，偶现同一个通道播放提示收流超时问题

方便加个微信交流一下吗？我的WeChat：Farrah_666
