### ISSUE TITLE
技术咨询：内网部署，映射到公网视频流地址如何配置

### ISSUE THREAD

**Issue by yebo-luo** [648540858/wvp-GB28181-pro#1350]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
页面返回的视频流地址想改为公网的，ip改掉后，对应映射的端口【例如81映射到1810】怎么改配置，使得从页面上复制的视频流地址可以直接播放。
**截图**  
![Snipaste_2024-03-06_11-02-04](https://github.com/648540858/wvp-GB28181-pro/assets/85433337/f56a4b7f-3765-4c19-b0dd-95137379baeb)
**抓包文件**
  
**日志**
```

日志内容放这里， 文件的话请直接上传
```

**Comment by raffaf** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/124870420/710d0645-fa8c-4aa8-91b2-fac61a8110ce)rutu
如图，先去修改/ZLMediaKit/release/linux/Debug/config.ini中http的端口，直接改成1810这种端口就行了

**Comment by raffaf** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/124870420/f3a058f3-ab6e-482e-913e-989408584b64)
再去修改下application.yml中zlm配置就行了。内网IP改成公网地址。再重启zlm和WVP就行了
