### ISSUE TITLE
技术咨询:重启wvp后录像被重命名导致云端录像播放不了，找不到文件

### ISSUE THREAD

**Issue by 935560217** [648540858/wvp-GB28181-pro#1351]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
重启wvp后录像被重命名导致云端录像播入找不到文件
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/43714633/78a382d3-1f02-491b-a604-a27586db800f)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/43714633/05f27867-b260-487c-a45e-11fb6515dc55)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
现在版本已经不会重命名录像文件了，你用的什么版本的代码
