### ISSUE TITLE
技术咨询:拉流代理开启录像后，如何在之后关闭录像功能

### ISSUE THREAD

**Issue by yebo-luo** [648540858/wvp-GB28181-pro#1352]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况
 - 4. 是否是公网部署 否
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 2.6.8分支 2023-08-28版本

**内容描述:**
拉流代理添加代理时，开启录制功能，当点击播放后，有开始录制；但是之后直接删除这个代理后，录制仍有在进行，云端录制也存在最近录制文件。
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
目前只能删除重建
