### ISSUE TITLE
【技术咨询】GB28181监控设备与WVP建立连接发送者和接收者IP一致

### ISSUE THREAD

**Issue by Farrahchen** [648540858/wvp-GB28181-pro#1353]
**内容描述:**
监控设备与平台建立连接时，报文显示发送者和接收者IP一致正常吗？？？
**截图**  
点播抓包截图：
<img width="521" alt="8e10828dab33e3379a2f5585f1a2685" src="https://github.com/648540858/wvp-GB28181-pro/assets/49346335/ae1cd2ba-a2cc-47ff-affc-d091d1b38408">

录像机设置截图：
![b208d58cfe8eeab83498369ca787bdb](https://github.com/648540858/wvp-GB28181-pro/assets/49346335/52518cf6-8ff7-47e0-a241-d41208add5a4)

**Comment by mengxing2017** [comment]
你用户id和服务器id是不是配置成有一样的了？

**Comment by Farrahchen** [comment]
> 你用户id和服务器id是不是配置成有一样的了？

改成不一样的，也不行呀？？？

**Comment by mengxing2017** [comment]
然后现在是什么问题吗？视频没通道？视频通道你添加了没？
