### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by zhuibudao** [648540858/wvp-GB28181-pro#1354]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
代码都是今天刚更新的，wvp平台设备录像中，下载指定时间段的录像时，经常会出现没下载完成，却有下载地址的情况，且下载地址并不是该通道的录像内容，后续有继续用postman调progress接口，发现progress的一直在增长，最后变成1了，downLoadFilePath字段值却没发生改变。
**截图**  
![47F4E8E5-EF18-4a3e-98CC-7598B30FB20E](https://github.com/648540858/wvp-GB28181-pro/assets/46883891/6bc188ee-dd9c-49ac-819b-e27403d2baba)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/46883891/e34f3f3b-930d-4bc2-b6f7-c77c3edef22c)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/46883891/f422ce59-1423-40be-a6e4-2635a1e181ff)

**抓包文件**
  
**日志**
[zlm.log](https://github.com/648540858/wvp-GB28181-pro/files/14522245/zlm.log)
[wvp.txt](https://github.com/648540858/wvp-GB28181-pro/files/14522260/wvp.txt)

[wvp配置.txt](https://github.com/648540858/wvp-GB28181-pro/files/14532242/wvp.txt)
[zlm配置.txt](https://github.com/648540858/wvp-GB28181-pro/files/14522105/zlm.txt)

日志内容放这里， 文件的话请直接上传
```

**Comment by zhuibudao** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/46883891/f6439173-9539-41b1-a47a-f9e0df1eda14)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/46883891/551cca19-86d8-4757-a9a1-15745e7df6dd)
[zlm.log](https://github.com/648540858/wvp-GB28181-pro/files/14531962/zlm.log)
[wvp.txt](https://github.com/648540858/wvp-GB28181-pro/files/14531963/wvp.txt)
又试了很多次，progress是1，但没有下载路径

**Comment by zhuibudao** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/46883891/2e13663f-c336-4da1-9df8-49b6d505f460)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/46883891/040c8a85-08c7-4180-afa9-32cddafa8dde)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/46883891/0187fb10-fcd4-4fec-afbd-53f0bbc24403)
下了一个一小时内的，服务器上也有文件，但还是没有下载路径

**Comment by zhuibudao** [comment]
十几分钟以内都能下，再久就不行了

**Comment by zhuibudao** [comment]
> 十几分钟以内都能下，再久就不行了

有时候能行，有时候不行

**Comment by 648540858** [comment]
使用用的旧版本的吧，新版本已经不会分片了，不需要assist服务，直接部署wvp+zlm测试就行了

**Comment by zhuibudao** [comment]
> 使用用的旧版本的吧，新版本已经不会分片了，不需要assist服务，直接部署wvp+zlm测试就行了

是新版本，没有assist服务

**Comment by 648540858** [comment]
不能下载的情况需要提供下日志文件以及抓包文件我看下

**Comment by 648540858** [comment]
downLoadFilePath没有结果多半是没收到录像文件结果，只能看日志确定了

**Comment by Duktig-Jay** [comment]
> 使用用的旧版本的吧，新版本已经不会分片了，不需要assist服务，直接部署wvp+zlm测试就行了

大佬，我这边使用最新版本的录像下载功能，设置了开始结束时间，文件正常生成了，但是在云端录像查看，一个流上有多个文件,
代码昨天更新过 3cd3e97

**Comment by 648540858** [comment]
更新下代码
