### ISSUE TITLE
BUG 无人观看的流关闭后，重新打开视频流URL，没有自动拉流

### ISSUE THREAD

**Issue by jerry16851** [648540858/wvp-GB28181-pro#1355]
**环境信息:**

 - 1. 部署方式  wvp-prp + zlm都是编译部署
 - 2. 部署环境 centos 7.9
 - 3. 端口开放情况 关闭防火墙
 - 4. 是否是公网部署 内网部署
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台 海康摄像头
 - 7. 你做过哪些尝试 修改了源码后，重新编译正常拉流
 - 8. 代码更新时间 2024-03-07

**描述错误**
描述下您遇到的问题
ZLM启用了自动关流配置项，wvp在收到“未找到流”事件后，重新拉流失败。

拉流前获取的数据库wvp_stream_proxy:enable=1,status=0

![image](https://github.com/648540858/wvp-GB28181-pro/assets/185319/175c7616-aa28-4c28-a8df-4bcb9b4c2c2a)

**如何复现**

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/185319/620f3548-3d57-4fac-9e34-ad8bc7d63897)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/185319/707b8cce-f9a9-4125-8fea-e9425cb15092)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
你有这个需求的话，就开启自动点播，否则就需要在wvp上发起点播请求

**Comment by mengxing2017** [comment]
你想要url直接播放的话，就需要开启自动点播，自动点播也是没人观看的时候，会自动关闭流的

**Comment by mengxing2017** [comment]
看你这个走的不是国标？

**Comment by jerry16851** [comment]
不是国标，rtsp的拉流代理

**Comment by jerry16851** [comment]
自动点播会存储视频文件吗？存储的视频文件如何很好的清理呢

**Comment by mengxing2017** [comment]
拉流这个我就不清楚了，按需拉流这个走国编不是会更靠谱，有人观看就拉流，无人观看就断开

**Comment by mengxing2017** [comment]
视频录像你在wvp配置文件关闭录制不就行了

**Comment by mengxing2017** [comment]
zlm录像默认是 7天自动删除 ，你可以配置时间

**Comment by jerry16851** [comment]
国标的按需拉流是正常的

**Comment by mengxing2017** [comment]
rtsp拉流我就不清楚了

**Comment by jerry16851** [comment]
我记得之前的版本是这样的，rtsp关流后可以按需拉起来，测试都没问题。不行我按照自己的需求来修改吧。
![image](https://github.com/648540858/wvp-GB28181-pro/assets/185319/99d4f432-5b8a-4b3d-aea4-a6fe6a0ce1b9)

**Comment by jerry16851** [comment]
而且在wvp的前端操作时，也很变扭。当视频流关闭后，在重新打开拉流列表播放视频时是失败的，给用户的感受也不好。

![image](https://github.com/648540858/wvp-GB28181-pro/assets/185319/f71f0c2e-5053-4100-955b-98dba80a8de4)

**Comment by bigff-0527** [comment]
老哥，你说的那个需求实现了吗？我也想要这种功能
