### ISSUE TITLE
BUG  通道状态不正确

### ISSUE THREAD

**Issue by lihaogis** [648540858/wvp-GB28181-pro#1356]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 ubuntu

**描述错误**
通道状态不对，有离线的但是现实在线，有的实际在线但显示的离线

**截图**  
![微信截图_20240311084035](https://github.com/648540858/wvp-GB28181-pro/assets/31950631/3b84ab49-6643-4928-a313-22b5edaec712)
![微信截图_20240311084209](https://github.com/648540858/wvp-GB28181-pro/assets/31950631/bc5b1317-32a2-4c95-b468-de252a0db364)
![微信截图_20240311084247](https://github.com/648540858/wvp-GB28181-pro/assets/31950631/36415294-9c2a-4975-82a6-395ceb6a28d6)

**Comment by ananix** [comment]
请问解决了吗？，我也有这个问题

**Comment by 648540858** [comment]
通道状态来自下级推送，你可以选择自己手动刷新也可以开启目录订阅，下级支持目录订阅的话会在有变化是通知上级
