### ISSUE TITLE
使用的在线文档knife4j 没办法加锁或者将其关闭,换了别的版本,加上配置好像也没有生效,对上线服务器存在安全性

### ISSUE THREAD

**Issue by luwenteng** [648540858/wvp-GB28181-pro#1357]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
使用nginx重新部署前端，然后屏蔽文档访问地址，你可以这样试试。我看下怎么彻底关闭文档



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月11日(周一) 下午3:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [648540858/wvp-GB28181-pro] 使用的在线文档knife4j 没办法加锁或者将其关闭,换了别的版本,加上配置好像也没有生效,对上线服务器存在安全性 (Issue #1357)




 
环境信息:
  
  
部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
  
 
  
部署环境 windows / ubuntu/ centos ...
  
 
  
端口开放情况
  
 
  
是否是公网部署
  
 
  
是否使用https
  
 
  
方便的话提供下使用的设备品牌或平台
  
 
  
你做过哪些尝试
  
 
  
代码更新时间
  
  
描述错误
 描述下您遇到的问题
 
如何复现
 有明确复现步骤的问题会很容易被解决
 
截图
 
抓包文件
 
日志
 日志内容放这里， 文件的话请直接上传

**Comment by luwenteng** [comment]
谢谢 收到,可能是我加的方式不对,我用的是knife4j 增强的配置
