### ISSUE TITLE
为啥我一直报401和403

### ISSUE THREAD

**Issue by jyy1990** [648540858/wvp-GB28181-pro#1358]
我拉master和2.6.9分支都试了，程序启动后，配 了摄像头的参数，程序就一直无限报401和403，启动后链接ZLM没问题。
我已经反复确认摄像头页面那几个参数是对的。
[注册请求]设备：41010500002000000002, 开始处理: 10.101.59.244:8116
[注册请求] 设备：41010500002000000002, 回复401: 10.101.59.244:8116
[注册请求]设备：41010500002000000002, 开始处理: 10.101.59.244:8116
[注册请求] 设备：41010500002000000002, 密码/SIP服务器ID错误, 回复403: 10.101.59.244:8116
配置的sip端口和本地端口都是8116，服务器id  sip域  密码都是用的代码里的没有改，摄像头是华为的，是华为的不能用还是咋了，搞了一天了也没解决

**Comment by 648540858** [comment]
你看看你得设备编辑里有没有填写了一个密码，有的话删掉设备重新注册试试。还不行的话抓个包看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月11日(周一) 下午3:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [648540858/wvp-GB28181-pro] 为啥我一直报401和403 (Issue #1358)




 
我拉master和2.6.9分支都试了，程序启动后，配 了摄像头的参数，程序就一直无限报401和403，启动后链接ZLM没问题。
 我已经反复确认摄像头页面那几个参数是对的。
 [注册请求]设备：41010500002000000002, 开始处理: 10.101.59.244:8116
 [注册请求] 设备：41010500002000000002, 回复401: 10.101.59.244:8116
 [注册请求]设备：41010500002000000002, 开始处理: 10.101.59.244:8116
 [注册请求] 设备：41010500002000000002, 密码/SIP服务器ID错误, 回复403: 10.101.59.244:8116
 配置的sip端口和本地端口都是8116，服务器id  sip域  密码都是用的代码里的没有改，摄像头是华为的，是华为的不能用还是咋了，搞了一天了也没解决

**Comment by jyy1990** [comment]
> 你看看你得设备编辑里有没有填写了一个密码，有的话删掉设备重新注册试试。还不行的话抓个包看看
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月11日(周一) 下午3:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [648540858/wvp-GB28181-pro] 为啥我一直报401和403 (Issue #1358) 我拉master和2.6.9分支都试了，程序启动后，配 了摄像头的参数，程序就一直无限报401和403，启动后链接ZLM没问题。 我已经反复确认摄像头页面那几个参数是对的。 [注册请求]设备：41010500002000000002, 开始处理: 10.101.59.244:8116 [注册请求] 设备：41010500002000000002, 回复401: 10.101.59.244:8116 [注册请求]设备：41010500002000000002, 开始处理: 10.101.59.244:8116 [注册请求] 设备：41010500002000000002, 密码/SIP服务器ID错误, 回复403: 10.101.59.244:8116 配置的sip端口和本地端口都是8116，服务器id sip域 密码都是用的代码里的没有改，摄像头是华为的，是华为的不能用还是咋了，搞了一天了也没解决 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

还真跟这个有关，我把application配置文件里sip下面的password注释掉了，目前设备可以注册上来了，谢谢
