### ISSUE TITLE
BUG：普通播放正常，WebRTC播放报错：Assertion failed: (have_active_media, 必须确保最少有一个活跃的track), functi

### ISSUE THREAD

**Issue by oulover** [648540858/wvp-GB28181-pro#1360]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
普通播放正常，
接口：/index/api/webrtc?app=rtp&stream=CD001_CD001&type=play
WebRTC播放报错：**Assertion failed: (have_active_media, 必须确保最少有一个活跃的track), function checkValid, file /data/installs/ZLMediaKit/webrtc/Sdp.cpp, line 1343.**

ZLM 已经rtc编译，且配置了
[rtc]
externIP=公网IP

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/61042846/f3f79534-3bb6-4eca-ba9d-0ced7519c6eb)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/61042846/62de3f1c-f69d-4083-8762-41b54062e795)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by CNPolaris** [comment]
遇到了同样的问题，请问有没有解决😭

**Comment by guzijian123** [comment]
我的h264的话播放就没有问题h265使用webrtc的话就会出现同样的问题

**Comment by 648540858** [comment]
webrtc不支持h265

**Comment by TT210V** [comment]
兄弟们解决了吗，我也是这个问题，zlm上配置了h256转h264也不行
