### ISSUE TITLE
部署多个zlm节点，收流超时

### ISSUE THREAD

**Issue by scdn** [648540858/wvp-GB28181-pro#1362]
**环境信息:**

 - 1. 部署方式 、wvp-pro + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 全部
 - 4. 是否是公网部署  是
 - 5. 是否使用https　是
 - 6. 方便的话提供下使用的设备品牌或平台　海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间　最新

wvp和zlm在不同的公网服务器，查阅wiki
https://github.com/648540858/wvp-GB28181-pro/wiki/%E4%B8%8EZLMediaKit%E8%81%94%E8%B0%83#zlm%E5%92%8Cwvp%E9%83%A8%E7%BD%B2%E5%9C%A8%E5%90%8C%E4%B8%80%E5%8F%B0%E5%85%AC%E7%BD%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B8%8A
```
[wvp]:   
sip.ip设置wvp所在服务器的网卡IP(win: cmd下使用ipconfig查看, Linux: shell下使用ifcongi或ip addr查看),  
media.ip 设置为ZLM所在服务器的公网IP,   
media.stream-ip 设置为ZLM所在服务器的公网IP,   
media.hook-ip 设置为wvp所在服务器的公网IP.
```

点播提示收流超时，部署在同一个服务器的节点，可正常播放

**内容描述:**

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
media.sdp-ip需要设置成公网ip

**Comment by scdn** [comment]
sdp-ip是公网ip的

mengxing2017 ***@***.***>于2024年3月14日 周四22:47写道：

**Comment by mengxing2017** [comment]
收流端口udp放通了吗

**Comment by scdn** [comment]
30000-30500udp放行了的

mengxing2017 ***@***.***>于2024年3月14日 周四22:50写道：

**Comment by mengxing2017** [comment]
那只能具体原因具体分析了，我这边就猜不出什么问题了，你抓个包上传一下看看作者有空给你看不

**Comment by scdn** [comment]
好的，谢谢，我抓包看看

mengxing2017 ***@***.***>于2024年3月14日 周四22:54写道：
