### ISSUE TITLE
分屏监控，前端BUG

### ISSUE THREAD

**Issue by sincebyte** [648540858/wvp-GB28181-pro#1363]
**环境信息:**
 1. 部署方式 wvp-pro docker / zlm(docker) 
 2. 部署环境 ubuntu
 3. 代码更新时间: 7055c531 
 4. 代码分支：wvp-28181-2.0

**描述错误**
分屏监控，4宫格，有部分突出

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/7248023/28afc3ed-9691-49e8-b412-a57abe7dceef)

代码已经合并至master分支的最新版本了
请问这是已知BUG吗？还是流数据本身有问题？

**Comment by scdn** [comment]
[](https://github.com/648540858/wvp-GB28181-pro/issues/1292)　这个可以解决

**Comment by sincebyte** [comment]
重新编译后解决了。
