### ISSUE TITLE
最新原始版，前后端打成jar，提示{"code":401,"msg":"请登录后重新请求"}

### ISSUE THREAD

**Issue by best4s** [648540858/wvp-GB28181-pro#1364]
大佬：打成jar包，

最新的wvp，前后端打成jar ，登录提示 
提示{"code":401,"msg":"请登录后重新请求"}

<img width="564" alt="1710236370117" src="https://github.com/648540858/wvp-GB28181-pro/assets/3435474/6c86d90b-b136-415a-b451-f5a507b0f668">

**Comment by mengxing2017** [comment]
看文档把前端编译了

**Comment by best4s** [comment]
OK le,谢谢大佬

**Comment by stillywud** [comment]
cd wvp-GB28181-pro/web_src/
npm --registry=https://registry.npmmirror.com install
npm run build


很棒
