### ISSUE TITLE
国标对讲噪音很大

### ISSUE THREAD

**Issue by Duktig-Jay** [648540858/wvp-GB28181-pro#1366]
**环境信息:**

 - 1. 部署方式
> wvp-pro + zlm都是编译部署
 - 2. 部署环境 

> windows

 - 3. 端口开放情况 

> 端口已开放

 - 4. 是否是公网部署 

> 本地测试与公网部署都是同样情况

 - 5. 是否使用https 

> 否

 - 6. 方便的话提供下使用的设备品牌或平台

> 水星 MIPC328PW-4 1.0

 - 7. 你做过哪些尝试

> 使用ffmpeg进行推送音频文件以及采集麦克风推送到zlm效果正常
> 界面推流 使用rtsp/rtmp播放流媒体地址效果正常
> 使用zlm测试地址播放wvp推送的的流效果也正常

- 8. 代码更新时间

> 最新代码 2024-03-13 10:03  git hash: cb5afce
> zlmediakit git hash: f49aed7a32d19b5e556ebbf2b31d61033f620103

**内容描述:**
通过界面进行语音对讲 发送音频流噪音很大

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/58797859/4da57757-d2c2-4604-85f5-c5fc85386900)

**抓包文件**
[抓包.zip](https://github.com/648540858/wvp-GB28181-pro/files/14584234/default.zip)

**日志**
![image](https://github.com/648540858/wvp-GB28181-pro/assets/58797859/27e99dbb-343a-4971-9836-4556f14588a2)
[日志.zip](https://github.com/648540858/wvp-GB28181-pro/files/14584373/default.zip)

**Comment by Duktig-Jay** [comment]
调整zlm配置preferredCodecA中的PCMA到第一位之后 效果正常

**Comment by guzijian123** [comment]
> 调整zlm配置preferredCodecA中的PCMA到第一位之后 效果正常

![image](https://github.com/648540858/wvp-GB28181-pro/assets/103352688/a787de0a-e46a-4081-89e6-4fb8c2dd0416)
我这个也是设置的第一位，噪音还是特别大，请问还需要还有什么配置吗，我是使用的docker进行的部署
这个是我的配置文件
[config.txt](https://github.com/648540858/wvp-GB28181-pro/files/14818660/config.txt)

**Comment by Duktig-Jay** [comment]
> > 调整zlm配置preferredCodecA中的PCMA到第一位之后 效果正常
> 
> ![image](https://private-user-images.githubusercontent.com/103352688/318320615-a787de0a-e46a-4081-89e6-4fb8c2dd0416.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjI0NTEsIm5iZiI6MTcxMTk2MjE1MSwicGF0aCI6Ii8xMDMzNTI2ODgvMzE4MzIwNjE1LWE3ODdkZTBhLWU0NmEtNDA4MS04OWU2LTRmYjhjMmRkMDQxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwOTAyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzM2MjY3ZjMwZDBkODAxMmFmZTY4MjhmZmFiZWI1ZTBhMDdlNjI2N2FjYjg1YzhmN2Y0NjVkZDdmY2YxMTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NUtFkYLL5k6c_i0bOI0utY6fRCG2FElKrsMy5L9il1U) 我这个也是设置的第一位，噪音还是特别大，请问还需要还有什么配置吗，我是使用的docker进行的部署 这个是我的配置文件 [config.txt](https://github.com/648540858/wvp-GB28181-pro/files/14818660/config.txt)

这个一般是音频编码的问题，你可以看一下你的设备发送的音频编码还有摄像头支持的是什么格式的，按照实际格式来调整，建议可以先用ffmpeg测试一下，参考作者写的流程 https://doc.wvp-pro.cn/#/_content/ability/continuous_broadcast?id=%e4%bd%bf%e7%94%a8ffmpeg%e5%bf%ab%e9%80%9f%e6%b5%8b%e8%af%95
