### ISSUE TITLE
BUG：平台级联注册后重新点保存又把注册的上级平台注销了

### ISSUE THREAD

**Issue by Yanjiachan** [648540858/wvp-GB28181-pro#1369]
**如何复现**
添加了一个上级平台，然后过一会对它进行编辑，但是没有修改任何数据直接保存。

**截图**  
![企业微信截图_17103250178067](https://github.com/648540858/wvp-GB28181-pro/assets/25785265/806f85aa-ca61-4269-84cb-b9bb85394cda)

![企业微信截图_17103252843769](https://github.com/648540858/wvp-GB28181-pro/assets/25785265/5cad72d1-0d87-4d1a-8010-43d5f35511b2)

**Comment by Yanjiachan** [comment]
还有一个问题，平台收到下级平台的心跳，但是过几秒却发现日志打印三次心跳失败
![企业微信截图_17103977443055](https://github.com/648540858/wvp-GB28181-pro/assets/25785265/52c4ade5-9002-416d-a8a3-ba280cec6c30)

**Comment by 648540858** [comment]
默认保存时注销重新注册
