### ISSUE TITLE
页面播放视频卡得根本都不动有什么办法可解决，视频新手

### ISSUE THREAD

**Issue by jyy1990** [648540858/wvp-GB28181-pro#1370]
我是把wvp和zlm都安装在同一虚机上，摄像头和电脑是通过物理网线连接的。
jessibuca卡的要死，半天才会动一帧，但是把播放地址里面的rtsp地址粘到VLC播放，可以流畅播放。
请问这该怎么解决呢
![image](https://github.com/648540858/wvp-GB28181-pro/assets/35125132/ebb749e8-b577-4619-ad32-814b80e68348)

**Comment by jyy1990** [comment]
还有一个问题，我启动的zlm是个满血版的，是包含webRTC的，但是wvp里面的webRTC窗口为啥是黑的，一点反应没有
![image](https://github.com/648540858/wvp-GB28181-pro/assets/35125132/43546295-62e2-4fed-bfe6-a373d3c106fc)

**Comment by mengxing2017** [comment]
买jessibuca pro版，或者调低分辨率、码率，换h264编码

**Comment by jyy1990** [comment]
> 买jessibuca pro版，或者调低分辨率、码率，换h264编码

我的摄像头配置页有个框可以勾H265，但是我勾不勾都卡死不动，有延迟能理解，一动不动就感觉很奇怪
