### ISSUE TITLE
技术咨询  点播失败, 错误码: 481, Call/Transaction Does Not Exist

### ISSUE THREAD

**Issue by 442577358** [648540858/wvp-GB28181-pro#1372]
**环境信息:**

 - 1. 部署方式  wvp-prp + zlm都是编译部署
 - 2. 部署环境  centos ...
 - 3. 端口开放情况 全部
 - 4. 是否是公网部署  是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台     宇视球机  IPC633I-R-X23U-DT
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间   版本2.7

**内容描述:**

点播失败, 错误码: 481, Call/Transaction Does Not Exist

**截图**  

![image](https://github.com/648540858/wvp-GB28181-pro/assets/98003661/7277a598-f9a8-4cb5-9e6c-4b89e2b78df1)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
看日志报什么错误

**Comment by bendanGit** [comment]
我也遇到这种情况，没报什么错，就提示481, Call/Transaction Does Not Exist

**Comment by 648540858** [comment]
更新到最新代码测试下
