### ISSUE TITLE
技术咨询 编译2.7.0 今天发布的最新版本无法正常运行，麻烦看下问题。。

### ISSUE THREAD

**Issue by YesHarlem** [648540858/wvp-GB28181-pro#1374]
**环境信息:**

 - 1. 部署方式 ：wvp-prp + zlm都是使用SaltFish001 docker脚本编译部署
 - 2. 部署环境： ubuntu
 - 3. 端口开放情况：全部
 - 4. 是否是公网部署 ：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试： 在arm和x86 环境下都不能正常运行
 - 8. 代码更新时间：3-15 最新版本，045f2334d0f0259bf0a4e03b11669fe54815aed0   

**内容描述:**
在x86和arm平台下部署，运行时都提示错误，无法正常运行（数据库也导入最新版本）。 同样的环境，脚本打包 2.6.8版本（314423bd011cffcbf8201047c76cc8e9127e86f2） 是可以正常运行的。

日志：
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: com.baomidou.dynamic.datasource.exception.CannotFindDataSourceException: dynamic-datasource can not find primary datasource
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
  
**日志**
[log.txt](https://github.com/648540858/wvp-GB28181-pro/files/14614278/log.txt)

日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
这看着像是数据库都没连上

**Comment by mengxing2017** [comment]
33306,33060，是同一个端口吗，看清楚点

**Comment by mengxing2017** [comment]
报错信息截图全一点嘛，靠猜猜不出问题

**Comment by zc640618** [comment]
2.6.8版本和2.7.0版本的配置文件数据库部分有改动的，你看看是不是这里的问题？
[https://github.com/648540858/wvp-GB28181-pro/blob/f4e41659d8ea91db1c3ec5a584270a7b3ef8ce65/src/main/resources/all-application.yml#L35C1-L72C1](url)

**Comment by mengxing2017** [comment]
你docker之间是不是互联互通的？看你redis也有问题

**Comment by mengxing2017** [comment]
已经好久没弄过docker版的，可以加我 QQ 407692831 看一眼
