### ISSUE TITLE
新版本 webrtc无法正常播放

### ISSUE THREAD

**Issue by cwy1996** [648540858/wvp-GB28181-pro#1378]
**环境信息:**

 - 1. 部署方式         wvp-pro docker / zlm(docker) 
 - 2. 部署环境         ubuntu
 - 3. 端口开放情况    均正常开放
 - 4. 是否是公网部署       公网
 - 5. 是否使用https       未使用两者https，走的代理
 - 6. 方便的话提供下使用的设备品牌或平台       接入设备海康
 - 7. 你做过哪些尝试     zlm禁用   rtc udp    使用 tcpport
 - 8. 代码更新时间    wvp：20240314       zlm：20240313

**描述错误**
{
“code”：-400，
“msg”：“断言失败：（！media.empty（）），函数checkValid，文件/opt/media/ZLMediaKit/webrtc/Sdp.cpp，第1326行。”，
“sdp” ： 无效的
}

这个报错，wvp那边是灰屏报上述错误，但是复制对应的rtcs链接，但是zlm是可以播放的，请问这可能是哪方面的错误呢，

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/76695859/7b37add9-712b-4b1f-9049-62c60e3a6035)

webrtc播放器灰屏
![image](https://github.com/648540858/wvp-GB28181-pro/assets/76695859/5cd194b0-93e7-4826-820e-d7375072526a)

复制对应的rtcs地址，zlm播放器可以正常播放，但不能等过长时间
![image](https://github.com/648540858/wvp-GB28181-pro/assets/76695859/02e03700-4e48-4fce-9070-613f97e79830)

**抓包文件**
  

**日志**
```
[zlm.txt](https://github.com/648540858/wvp-GB28181-pro/files/14630807/zlm.txt)
[wvp.txt](https://github.com/648540858/wvp-GB28181-pro/files/14630810/wvp.txt)
```

**Comment by hexq** [comment]
针对rtcPlayer.vue文件，这两个参数配置成true，重新编译，打包发布，应该就好了。
![image](https://github.com/648540858/wvp-GB28181-pro/assets/1995173/def8cfec-a143-466a-9bc7-0e64a9cfbbe8)

**Comment by cwy1996** [comment]
> 针对rtcPlayer.vue文件，这两个参数配置成true，重新编译，打包发布，应该就好了。 ![image](https://private-user-images.githubusercontent.com/1995173/313559430-def8cfec-a143-466a-9bc7-0e64a9cfbbe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDAwOTgsIm5iZiI6MTcxMDczOTc5OCwicGF0aCI6Ii8xOTk1MTczLzMxMzU1OTQzMC1kZWY4Y2ZlYy1hMTQzLTQ2NmEtOWJjNy0wZTY0YTljZmJiZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMDUyOTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjE0OThkZjczYjdhZjEwMzQ4NWM3MTMzMzQxNzQ0ZTVmZDczMDY2NDcwYjFkZTRlNDQ1ZGY0NTFmODViMzcyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8oiRCy8oWqXtbWTpQeZgDTDkfFAvGLYWX0GWJLcjg1k)

好的我试一下

**Comment by cwy1996** [comment]
> 针对rtcPlayer.vue文件，这两个参数配置成true，重新编译，打包发布，应该就好了。 ![image](https://private-user-images.githubusercontent.com/1995173/313559430-def8cfec-a143-466a-9bc7-0e64a9cfbbe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTAzMzksIm5iZiI6MTcxMDc1MDAzOSwicGF0aCI6Ii8xOTk1MTczLzMxMzU1OTQzMC1kZWY4Y2ZlYy1hMTQzLTQ2NmEtOWJjNy0wZTY0YTljZmJiZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMDgyMDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjY2YTlmODUxZDBlMmM3ZmE3NDY4MWQzZmU3YzMyOTE3ODMyZDUxZjQxODA2YzJhODA3ZDUzMWNmNjdmYzY0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BLVadde4d_9-aW2qHaRU0BY2TGlMeS3Jhgu0o5-2CDo)

可以解决，谢谢

**Comment by cwy1996** [comment]
@648540858 可以更新一下 rtcPlayer.vue 文件中的对应配置么，zlm那边也有反馈的，感觉没必要提pr，期待您的更改

**Comment by cwy1996** [comment]
same issue #1365

**Comment by oulover** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/61042846/85d6b75e-8faf-4c0f-95e0-50695914ebfe)

**Comment by bigff-0527** [comment]
老哥，我的rtcs地址 请求是404请问是什么原因？
