### ISSUE TITLE
录像回放倍速播放指令下发报400

### ISSUE THREAD

**Issue by yanglegeyang666666666** [648540858/wvp-GB28181-pro#1379]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
录像回放倍速播放无法正常使用，代码已更新到最新

**如何复现**

**截图**  
![企业微信截图_17107536803738](https://github.com/648540858/wvp-GB28181-pro/assets/161577065/e853d95b-d4eb-4e29-bf8a-eb7a5d0d7c9c)

![企业微信截图_17107536994856](https://github.com/648540858/wvp-GB28181-pro/assets/161577065/b57371f5-7f6e-4a28-bb09-b82be9495bb2)

**抓包文件**
  
**日志**

日志内容放这里， 文件的话请直接上传
```

**Comment by luhengyu1** [comment]
我也遇到了同样的问题，请问你是怎么解决的
