### ISSUE TITLE
更新代码后自动点播无效

### ISSUE THREAD

**Issue by orderfoxsurf** [648540858/wvp-GB28181-pro#138]
src/main/java/com/genersoft/iot/vmp/media/zlm/ZLMHttpHookListener.java，379行String[] s = streamId.split("_");中用了split(“_")，但点播流的字符串格式已经从gb_play_%s_%s改成了%s/%s，所以代码无效，自动点播也就无效了。

**Comment by 648540858** [comment]
我测试下

**Comment by 648540858** [comment]
自动点播已修复
