### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by llliusss** [648540858/wvp-GB28181-pro#1385]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
添加设备之后视频播放一直很卡，掉包很严重是什么原因？
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by markjack9** [comment]
环境信息:

部署方式 wvp-pro脚本部署
部署环境  centos7
端口开放情况 所有
是否是公网部署 否
是否使用https 否
方便的话提供下使用的设备品牌或平台 海康摄像头


添加拉流代理中的其他选项，无人观看停止拉流这个选项是必选项，无法取消，停止拉流之后，云端录像功能中的录像就会停止，想实现通过拉流进行不间断的录像

**Comment by mengxing2017** [comment]
文档中有24小时方案录像方案，录像直接买nvr成本要比用wvp实现低的多
