### ISSUE TITLE
求问强制获取关键帧命令怎么获取不到流

### ISSUE THREAD

**Issue by Liudaocong** [648540858/wvp-GB28181-pro#139]
使用IFameCmd命令向摄像机发送命令后，没有推流过来上怎么回事

**Comment by 648540858** [comment]
抓包看一下，有可能是设备不支持

**Comment by Liudaocong** [comment]
设备是支持28181协议的。请问一下，关键帧的流是不是也会发送到流媒体服务器上

**Comment by 648540858** [comment]
是的，和发普通的流一样，有的设备会支持关键帧信令，收到关键帧信令就发送关键帧了，有的设备还是按照自己关键帧间隔发送。
