### ISSUE TITLE
关于接入国标设备，同时开启了音频和视频，会导致无法播放，关闭音频可以播放，但是没有声音的

### ISSUE THREAD

**Issue by liuzhenya2019** [648540858/wvp-GB28181-pro#1390]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
国标设备，使用Jessibuca播放没有问题，webRTC播放时，如果打开了音频会无法播放，关闭音频可以播放，但是没有声音，前端控制台报错
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/48957486/62ed1a4b-2331-4b5a-b9e4-1b00c3b9ca77)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/48957486/a2c0ad43-46e5-40b1-864d-dc1549259f65)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by liuzhenya2019** [comment]
"v=0
o=- 7377945365691351760 2 IN IP4 192.168.1.175
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS
m=video 8000 UDP/TLS/RTP/SAVPF 102 103
c=IN IP4 192.168.1.175
a=rtcp:8000 IN IP4 192.168.1.175
a=ice-ufrag:zlm_34
a=ice-pwd:g6tT0QWEyXutEE50YvXKLSSP
a=ice-options:trickle
a=fingerprint:sha-256 B5:5B:42:68:0E:FC:D7:71:16:6D:A4:01:EE:E4:ED:16:77:1A:71:17:22:23:A7:45:90:2E:9E:92:C4:E3:82:B7
a=setup:passive
a=mid:0
a=ice-lite
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=rtcp-mux
a=rtpmap:102 H264/90000
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=rtcp-fb:102 transport-cc
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=102
a=msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:1 cname:zlmediakit-rtp
a=ssrc:1 msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:1 mslabel:zlmediakit-mslabel
a=ssrc:1 label:zlmediakit-label
a=ssrc:3 cname:zlmediakit-rtp
a=ssrc:3 msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:3 mslabel:zlmediakit-mslabel
a=ssrc:3 label:zlmediakit-label
a=ssrc-group:FID 1 3
a=candidate:udpcandidate 1 udp 110 192.168.1.175 8000 typ host
m=audio 8000 UDP/TLS/RTP/SAVPF 8
c=IN IP4 192.168.1.175
a=rtcp:8000 IN IP4 192.168.1.175
a=ice-ufrag:zlm_34
a=ice-pwd:g6tT0QWEyXutEE50YvXKLSSP
a=ice-options:trickle
a=fingerprint:sha-256 B5:5B:42:68:0E:FC:D7:71:16:6D:A4:01:EE:E4:ED:16:77:1A:71:17:22:23:A7:45:90:2E:9E:92:C4:E3:82:B7
a=setup:passive
a=mid:1
a=ice-lite
a=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendonly
a=rtcp-mux
a=rtpmap:8 PCMA/8000/1
a=ssrc:2 cname:zlmediakit-rtp
a=ssrc:2 msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:2 mslabel:zlmediakit-mslabel
a=ssrc:2 label:zlmediakit-label
a=candidate:udpcandidate 1 udp 110 192.168.1.175 8000 typ host
"

**Comment by 648540858** [comment]
音频是什么格式的，可能是webrtc不支持的音频格式

**Comment by liuzhenya2019** [comment]
拉取最新版本的zlmediakit已经修复了，事zlm的bug
