### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by zc640618** [648540858/wvp-GB28181-pro#1396]
**环境信息:**

 - 1. 部署方式 wvp-pro + zlm编译部署/
 - 2. 部署环境 debian
 - 3. 端口开放情况
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 20240327

**描述错误**
许是因为网络质量问题导致设备页面的截图大概率出现花屏

**如何复现**
设备页面点击播放后会自动生成截图

**截图**  
![1](https://github.com/648540858/wvp-GB28181-pro/assets/8822067/3bf72292-7062-4d0d-a589-74c85870fdd7)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```
看zlm自动配置的snap参数是拉流就开始抓图为缩略图，可能我这边的网络质量问题导致，修改zlm自动配置参数为第5秒抓图就正常了。
具体修改：
https://github.com/648540858/wvp-GB28181-pro/blob/e886aa483373ccb85d964675b118ca9f0e27ee9c/src/main/java/com/genersoft/iot/vmp/service/impl/MediaServerServiceImpl.java#L573

`            param.put("ffmpeg.snap", "%s -rtsp_transport tcp -i %s -y -ss 00:00:05 -f mjpeg -frames:v 1 %s");`

**Comment by 648540858** [comment]
好的，抓图是需要解码视频流的，就用修改的方式解决就可以了，也没有更好的办法。
