### ISSUE TITLE
海康布控球不能开端口接收数据流

### ISSUE THREAD

**Issue by SitInAndWatchSky** [648540858/wvp-GB28181-pro#1398]
**环境信息:**

 - 1. 部署方式  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows 
 - 3. 端口开放情况  信令和数据端口都开
 - 4. 是否是公网部署  公网
 - 5. 是否使用https  没有
 - 6. 方便的话提供下使用的设备品牌或平台  海康布控球
 - 
![image](https://github.com/648540858/wvp-GB28181-pro/assets/39214201/4c537551-d1af-45ec-b8b2-8c8d9ebc7ded)

 - 7. 你做过哪些尝试  可以控制云台，视频流回不来，在点播后，平台端口没有开放，设备端已经推流，但是服务端没开端口，为啥会这样
 - 8. 代码更新时间
2023年

**内容描述:**

**截图**  

**抓包
[1234.pcapng.txt](https://github.com/648540858/wvp-GB28181-pro/files/14797872/1234.pcapng.txt)
文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
看看你的收流端口和mediao的sdp ip是否是你的设备可达的
