### ISSUE TITLE
录像回放问题

### ISSUE THREAD

**Issue by fmy2017** [648540858/wvp-GB28181-pro#1401]
/api/playback/start/{deviceId}/{channelId} 这个接口 如果同一个设备开始时间和结束时间是一样的话,只能同时一个人观看录像,第二个人去请求的时候会超时, 但是只要开始或者结束时间不一样,哪怕随便改下秒数,都可以重复请求,多个人可以同时观看,

**Comment by 648540858** [comment]
目前就是这样设计的，后面再考虑修改吧
