### ISSUE TITLE
BUG-新版本SDP设置不对

### ISSUE THREAD

**Issue by Jason5592** [648540858/wvp-GB28181-pro#1402]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/16130857/07b5a10d-790b-40bc-b102-fc3c4c3e4e16)
上个版本还是对的，上周升级了一下最新代码，就不对了

**Comment by Jason5592** [comment]
导致会报错，webrtc播放不出来
![image](https://github.com/648540858/wvp-GB28181-pro/assets/16130857/1bedc232-0620-4921-b51d-530eb5263855)

**Comment by Wss-20170929** [comment]
SDP IP在动态域名环境下发生变动，SDP IP不会随DDNS-GO解析至新的IP地址，导致国标点播提示收流失败，需要手动重启下服务更新IP地址。我遇到了这个问题，您这边也是这样吗

**Comment by 648540858** [comment]
更新zlm再试试，最近浏览器更新有一些变化

**Comment by 648540858** [comment]
更新到最新代码测试下
