### ISSUE TITLE
使用docker-compose.yml部署之后  数据库连不上  容器一直重启 是不是配置问题

### ISSUE THREAD

**Issue by miraclethooo** [648540858/wvp-GB28181-pro#1405]
**环境信息:**

 - 1. 部署方式 docker-compose
 - 2. 部署环境 centos7
 - 3. 端口开放情况 全部开放
 - 4. 是否是公网部署  是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
克隆下代码  用docker-compose  构建镜像和启容器  一直报错  容器重启 服务无法访问
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/30763590/c1b19529-5759-4969-bbbb-ad7f68cdbc80)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
数据库连接失败啊，程序都没起来

**Comment by v5star** [comment]
同样的问题，你们得到解决了吗？
![Uploading 微信截图_20240712093618.png…]()
