### ISSUE TITLE
BUG 国标设备设备是离线状态，但是通道有几个一直在线是什么情况了？

### ISSUE THREAD

**Issue by bendanGit** [648540858/wvp-GB28181-pro#1406]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20177801/3fc4583f-e6ec-4dfe-9615-748ace1cfa18)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
这个问题和1417是一样的 先关闭了
