### ISSUE TITLE
经常不能正常播放

### ISSUE THREAD

**Issue by kson34** [648540858/wvp-GB28181-pro#141]
重现是：页面首次播放后关闭（非点停止），放一段时候(前提user session没有过期)，再点击播放就会这样。
代码就是当天最新的了。

ZLMedia有注册媒体消息。

都是同一内网。10+年程序员，不会犯低级错误。
![BL2ZV {8F0_5_MSTSMPV3MI](https://user-images.githubusercontent.com/17976520/128671167-c3b637e9-ef15-4a07-ab0c-bf0b8d82222a.png)
![`1A73C)10LY27PB`7T78NQQ](https://user-images.githubusercontent.com/17976520/128671177-5b8aa34d-ceaa-4f5f-8d1e-e8a4a1f40992.png)

**Comment by 648540858** [comment]
好的我测试下

**Comment by kernelj** [comment]
我也发现这个情况，查看redis会发现  VMP_MEDIA_ONLINE_SERVER 被清掉了

**Comment by 648540858** [comment]
我无法复现这个问题，

**Comment by 648540858** [comment]
> 我也发现这个情况，查看redis会发现 VMP_MEDIA_ONLINE_SERVER 被清掉了

你有时间帮我找一下复现步骤吧

**Comment by 648540858** [comment]
我先关了，我无法复现，如果你使用最新代码能复现这个问题在反馈给我吧
