### ISSUE TITLE
新增代理为啥代理存在的话要先删掉呢

### ISSUE THREAD

**Issue by Jason5592** [648540858/wvp-GB28181-pro#1413]
![c1375eca666f0691c7318cf829ea727](https://github.com/648540858/wvp-GB28181-pro/assets/16130857/9632aa7a-9eb3-4403-b0e8-1f7382721651)
新增代理为啥代理存在的话要先删掉呢

**Comment by Jason5592** [comment]
可以改为不删掉，然后直接返回麽？

**Comment by 648540858** [comment]
目前是这么设计的，新增时理论就认为不应该存在相同的，存在就做了覆盖处理了
