### ISSUE TITLE
国标设备--云端录像的观看回放黑屏，无法观看，录像时间段有问题，不成段; 但是云端录像的rtp可播放

### ISSUE THREAD

**Issue by koroluo** [648540858/wvp-GB28181-pro#1415]
![国标设备--云端录像](https://github.com/648540858/wvp-GB28181-pro/assets/96862194/9300abe4-a7c1-4afc-9dae-a6213bdaeafa)

![云端录像可播放](https://github.com/648540858/wvp-GB28181-pro/assets/96862194/31150f72-e4bc-4ff7-8302-a50b71804c38)

**Comment by yanglegeyang666666666** [comment]
目前我也是这个问题

**Comment by SCUT-chenjia** [comment]
一样有这个问题，云端录像那里可以直接播放，通过国标设备转云端录像，发现时间都不对且无法播放。
话说新版本的云端录像页面改了好多啊，以前都是只能看到流列表，需要点击查看才能进入录像列表，现在直接看到录像列表了，我觉得新版本展示不如老版本的

**Comment by 648540858** [comment]
更新代码试试，最近修复了
