### ISSUE TITLE
BUG gb28181推流摄像头先半边黑屏后花屏

### ISSUE THREAD

**Issue by xsmyqf** [648540858/wvp-GB28181-pro#1418]
**环境信息:**

 - 1. 部署方式 
     wvp-pro 自编译 docker环境 
     zlm(docker)  zlmediakit/zlmediakit:master
 - 2. 部署环境 centos
 - 3. 端口开放情况 
       wvp-pro使用host模式
       zlm是开放了80和30000-30010
    
 - 4. 是否是公网部署 ：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：未知设备，一个红外线摄像头包含一个红外线流和正常摄像头流
 - 7. 你做过哪些尝试，增加udp_recv_socket_buffer为14194304
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题
摄像头出现半边花边。
**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/6007829/f5a9de7f-ddc4-4548-b0d7-3fa58648b500)

**抓包文件**
  
**日志**
```
日志未显示出错
```

**Comment by zc640618** [comment]
改成tcp试试看

**Comment by xsmyqf** [comment]
使用tcp和增大udp的包都无反应

**Comment by 648540858** [comment]
下级是设备还是平台。平台的话考虑是平台发送的流有问题，可以播放下录像文件看看是否花屏，如果录像也花屏，那么就可以确实是流质量有问题了
