### ISSUE TITLE
技术咨询：正常编译部署后，页面监听服务启动异常

### ISSUE THREAD

**Issue by DingKun7** [648540858/wvp-GB28181-pro#1419]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/ 
 - 2. 部署环境 windows / ubuntu/ centos ...  ubuntu
 - 3. 端口开放情况 正常
 - 4. 是否是公网部署 是
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试 删除项目、重现部署、编译等
 - 8. 代码更新时间 最新master分支代码

**内容描述:**
编译打包正常（全绿），部署后，WVP网页监听端口无法正常运行，28181服务监听端口正常运行，前端页面现在无法访问，查询运行端口也是查不到页面监听端口。
之前一直正常运行，2024-04-13更新代码后无法正常运行，出现页面无法访问的情况了，望作者大大给予帮助！

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/142068264/5e4ff298-3adc-4f30-9919-a8af44fe6dfe)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/142068264/c28c01e1-1072-4e44-836a-b03d43b45131)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/142068264/0706958e-a002-4163-958f-b9b21318816d)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by CNPolaris** [comment]
现在的不是前后端分开部署了吗

**Comment by DingKun7** [comment]
> 现在的不是前后端分开部署了吗

是最近更新的版本吗？之前都是一体化的服务启动就可以了...

**Comment by CNPolaris** [comment]
> > 现在的不是前后端分开部署了吗
> 
> 是最近更新的版本吗？之前都是一体化的服务启动就可以了...

作者的文档里面的部署教程中有前后端分离部署的教程，前端文件编译后用nginx代理一下就好

**Comment by DingKun7** [comment]
> > > 现在的不是前后端分开部署了吗
> > 
> > 
> > 是最近更新的版本吗？之前都是一体化的服务启动就可以了...
> 
> 作者的文档里面的部署教程中有前后端分离部署的教程，前端文件编译后用nginx代理一下就好

我的application.yml里的server ：port：18080   启动不起来，而sip：port：5060   启动确正常，老哥知道为什么吗？

**Comment by DingKun7** [comment]
> > > > > 现在的不是前后端分开部署了吗
> > > > 
> > > > 
> > > > 是最近更新的版本吗？之前都是一体化的服务启动就可以了...
> > > 
> > > 
> > > 作者的文档里面的部署教程中有前后端分离部署的教程，前端文件编译后用nginx代理一下就好
> > 
> > 
> > 我的application.yml里的server ：port：18080 启动不起来，而sip：port：5060 启动确正常，老哥知道为什么吗？
> 
> 报错信息是什么呢 ？按理说不应该的 你之前已经成功运行了，端口被占用了？

端口没有被占用  就是启用查不到任何关于18080的端口
