### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by 1343228975** [648540858/wvp-GB28181-pro#1423]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况 开放
 - 4. 是否是公网部署  是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
请问怎么开启视频播放鉴权，现在的情况是，复制链接，如mp4，hls，可以直接播放,可以加个token鉴权吗
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
只有推流支持播放鉴权，其他的不支持。
