### ISSUE TITLE
BUG 国标级联RTP推流频繁报错端口被占用

### ISSUE THREAD

**Issue by iwanlebron** [648540858/wvp-GB28181-pro#1426]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 centos 
 - 3. 端口开放情况 全部放开
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 推流
 - 7. 你做过哪些尝试 修改端口重启
 - 8. 代码更新时间 最新master

**描述错误**
国标级联RTP推流频繁报错端口被占用

**截图**  
<img width="1127" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/105045937/e834294a-16bf-48fd-b4f7-6a7c857d3714">

**Comment by 648540858** [comment]
你的发流端口和收流端口是不是冲突了，或者收流端口段和别的程序共用了，收流段口段就是wvp下的media.send-port-range

**Comment by iwanlebron** [comment]
没有共用 看端口占用是zlm还没有释放这个端口

**Comment by 648540858** [comment]
你配置了多少端口，什么版本的wvp

**Comment by iwanlebron** [comment]
50000-50300  wvp是2.7.1

**Comment by 648540858** [comment]
你的发流端口和你的日志对应不上呀，你的send-rtp-port-range配置到是50000-50300？

**Comment by iwanlebron** [comment]
sorry 发错了 是60000-65000

**Comment by 648540858** [comment]
更新到最新代码测试下, 如果可以复现,提供下复现步骤以及对应的日志文件
