### ISSUE TITLE
技术咨询-直播正常，回放一直错误

### ISSUE THREAD

**Issue by bian1721** [648540858/wvp-GB28181-pro#1428]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况 
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
直播可以，回放超时
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/58017051/dc20ec91-4c4c-41b6-82b6-2dcf9e30a277)

**抓包文件**
  
**日志**

![image](https://github.com/648540858/wvp-GB28181-pro/assets/58017051/abe1a545-10ea-457d-909a-fa5c5eb07d3c)

**Comment by 648540858** [comment]
把收流时间加大再试试，play-timeout
