### ISSUE TITLE
使用最新版本，并且开启了https，部分https地址为null

### ISSUE THREAD

**Issue by git-403** [648540858/wvp-GB28181-pro#1429]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker)
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 都开放了
 - 4. 是否是公网部署 是
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台 
 - 7. 你做过哪些尝试 打断点，百度，issue
 - 8. 代码更新时间

**内容描述:**
按照文档开启了https，点播的时候返回的url地址有https_fmp4、https_ts、https_ts就是没有https_flv,但是在测试工具里将http_flv地址改成https端口改成https的端口能播放视频，麻烦问题下是那块配置的不对吗？，已经issue并且百度也查找了
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by answer666** [comment]
我也是这个问题，在找资料。。。 不知道怎么操作

**Comment by git-403** [comment]
> 我也是这个问题，在找资料。。。不知道怎么操作

麻烦找到了给我说一声，我看了wvp和ZLM的issue，看别人的返回都有https_flv

**Comment by git-403** [comment]
是wvp_media_server表中flvSSLPort为0造成的，看StreamInfo类中setFlv代码段

**Comment by answer666** [comment]
> 是wvp_media_server表中flvSSLPort为0造成的，看StreamInfo类中setFlv代码段

感谢， 我也排查下。 我以为是我的 https 配置的问题。。

**Comment by git-403** [comment]
在配置文件里zlm配置那块加一个flv-ssl-port等于你的端口号就行

**Comment by answer666** [comment]
> 在配置文件里zlm配置那块加一个flv-ssl-port等于你的端口号就行

hello   你又没有遇到，升级到https后，设备有一半离线了，或者是部分通道离线，部分通道在线的情况？

**Comment by bigff-0527** [comment]
老哥，我设置了flv_ssl_port后 好像相比于之前的版本，很不稳定啊

**Comment by 648540858** [comment]
把zlm配置里的https端口添加上就可以了
