### ISSUE TITLE
公网级联

### ISSUE THREAD

**Issue by zhuibudao** [648540858/wvp-GB28181-pro#1430]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
   我是在内网部署了zlm+wvp，通过nginx转发到公网
  
    stream-ip； sdp-ip:

    如果这两个字段如果填内网ip，那么内网的摄像机流可以观看，公网的摄像机流显示收流超时；如果这两个字段如果填公网ip，那么内网和公网的摄像机流都显示收流超时。
    想问问这是为啥

**Comment by zhuibudao** [comment]
想问一下，这两个字段到底怎么用，在公网访问流的时候

**Comment by mengxing2017** [comment]
部署公网填公网ip,部署内网填内网ip

**Comment by 648540858** [comment]
建议使用国标级联代替nginx转发
