### ISSUE TITLE
通过WVP级联推送至海康ISC平台，在海康平台播放频繁出现花屏情况

### ISSUE THREAD

**Issue by lihaogis** [648540858/wvp-GB28181-pro#1433]
**环境信息:**

 - 1. 部署方式  wvp-prp + zlm都是编译部署
 - 2. 部署环境 centos
 - 3. 端口对外开放了
 - 4. 公网部署 
 - 5. 没有使用https
 - 6. 代码更新时间（2024.4.20）

**内容描述:**
通过WVP级联推送至海康ISC平台，在海康平台播放频繁出现花屏情况，在WVP平台播放正常。
尝试修改了流传输模式，目前用的UDP，改成了TCP就没办法查看视频了。
**截图**  
平台查看（正常）：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/31950631/e335de98-f4a2-45ff-8da9-5586ac1d315a)
海康ISC查看（花屏）：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/31950631/0b410be2-d79e-4ed4-8fdb-65c69ee3b0ae)

**Comment by ttgzs** [comment]
海康ISC平台部署不是可以直接管理吗？你这样做的意义是什么？ISC平台花屏，有可能是码率不对导致，ISC的版本是多少？

**Comment by lihaogis** [comment]
isc是1.5版本，本来是想把设备都接入wvp平台，但有两个设备是4g的信号很差，一直接不上来，只能在海康平台看，但客户要求在一个平台看，所以又把wvp的推到海康平台上。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月29日(周一) 晚上8:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] 通过WVP级联推送至海康ISC平台，在海康平台播放频繁出现花屏情况 (Issue #1433)




 
海康ISC平台部署不是可以直接管理吗？你这样做的意义是什么？ISC平台花屏，有可能是码率不对导致，ISC的版本是多少？

**Comment by 648540858** [comment]
国标接入4G设备时，心跳间隔一定要设置的短一些，比如20秒

**Comment by lucasp35** [comment]
你好，问下是怎么接入海康ISC平台的，我这边一直接不上去，抓包能看到这边有发注册的信令，但是海康ISC平台没有收到任何注册信令包。  给海康平台提供了我的公网IP（阿里云服务器）和端口号以及编码。 想问下你是怎么接入的，有没有遇到类似的情况。
