### ISSUE TITLE
录像下载到一半出现报错:资源未找到

### ISSUE THREAD

**Issue by bigff-0527** [648540858/wvp-GB28181-pro#1434]
**环境信息:**

 centos服务器上部署了wvp-pro、wvp-assist、zlm
 都是最新版本

**内容描述:**
录像下载到一半就报错
不存在设备的问题，换了别人的wvp可以下载
实在没辙了，不知道哪里漏配了还是怎么

![QR JP9~BFSMY8B4}SN3X](https://github.com/648540858/wvp-GB28181-pro/assets/58465932/3c800826-4065-46ba-afbf-c67a0ec0766b)
![J{Q58QT3BSU$3C%LJI3`6W7](https://github.com/648540858/wvp-GB28181-pro/assets/58465932/3618e051-b3fa-48b0-8aa0-c4c6f1ff9881)

**Comment by 648540858** [comment]
补充下iissue模板的信息

**Comment by bigff-0527** [comment]
> 补充下iissue模板的信息

更新了最新的zlm就可以了，但是进度到100%时，不会自动下载或者提供下载按钮，看了api返回的filedownloadpath是null
