### ISSUE TITLE
播放设备录像时，有时候正常，有时候异常，异常时报503错误

### ISSUE THREAD

**Issue by lihaogis** [648540858/wvp-GB28181-pro#1436]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 centos
 - 3. 端口开放情况  端口对外开放了
 - 4. 是否是公网部署  公网部署
 - 5. 是否使用https 否
 - 6. 代码更新时间 2024-04-20

**描述错误**
播放设备录像时，有时候正常，有时候异常，异常时报503错误，出现这个问题后什么也不处理过一段时间后又能正常播放历史视频（异常时也会影响到实时视频的点播，也报同样的错误）

**截图**  
![微信图片_20240430100122](https://github.com/648540858/wvp-GB28181-pro/assets/31950631/1c4c1406-6b3a-4aaa-93a9-fe2c54458790)

**Comment by mengxing2017** [comment]
设备限制了拉流数量，你咨询一下设备提供商

**Comment by scdn** [comment]
这个解决了吗？因为设备限制无关，我尝试了多品牌设备，都是这样

> 设备限制了拉流数量，你咨询一下设备提供商

**Comment by 648540858** [comment]
你测试nvr了，一般的设备都不会有太多的并发，不支持多个人同时看录像，
