### ISSUE TITLE
自己对wvp和zlm分别打镜像，在wvp页面中摄像机通道为0，但摄像机是在线状态

### ISSUE THREAD

**Issue by jianjunchang** [648540858/wvp-GB28181-pro#1437]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况 都已开放
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间

**内容描述:**
如题，摄像机通过gb28181接入后，无法获取到通道，但是把摄像机挂到nvr上，然后通过nvr接入平台，一切正常（既能获取到通道，又能正常播放，抓包发现似乎摄像机没有回应平台发出的查询通道的sip命令），用的wvp-28181-2.0分支版本
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by jianjunchang** [comment]
您好，不好意思，因为这两天没法连设备，所以没法复现截图（后边能连了我补充一下信息），其实我上边说的内容里最大的信息是，ipc挂到nvr上接平台就没问题，ipc单独接就不行，通道信息都无法获取到，设备端对sip服务的配置，在nvr和ipc上是完全相同的（除了设备id，通道id），所以，我怀疑咱们平台对ipc和nvr的处理上有哪里不一致导致的。

**Comment by mengxing2017** [comment]
国标区分下级什么是什么设备，只能通过sip.id,去过sip.id乱编码的话，wvp貌似并没有办法去区分下级是什么类型的设备，所以你要检查你的ipc是不是行业设备，设备允不允许公网接入Gb28181，而不是上来去怀疑wvp的问题

**Comment by jianjunchang** [comment]
嗯嗯，感谢您的回复，之前忽略了sip.id合规性的检测（我后边调整一下这块儿），不过如果是sip.id有问题，还有个现象解释不通，同样的设备端配置，我如果wvp和zlm都直接在宿主机启动（不采用容器部署），ipc在wvp页面也是完全正常的，只有docker部署时才会出现上述问题。
另外，docker部署时，还有个现象，wvp页面中显示的设备地址是docker网络的网关（我的docker用的自定义网络，网关172.18.0.1），端口是一个随机分配的端口，类似（172.18.0.1:43216）这种，如果不用docker部署，则显示的是设备的正常地址和5060端口，类似（192.168.1.110:5060）这种（我宿主机是192.168.1.*网段），不清楚这个现象是否是个线索能推测ipc不通但nvr能通的原因。
目前，同样的配置，不用docker部署的话，是完全没有问题的，我尝试docker部署，是为了方便在其他环境快速部署，两种方式应该最大的区别就是网络环境不同，我在尝试消除两种部署方式的网络差异，看看是否能解决。

**Comment by mengxing2017** [comment]
这是你自己的问题，如果你仅仅是为了方便部署的话，直接用host网络就行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月2日(周四) 上午7:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] 自己对wvp和zlm分别打镜像，在wvp页面中摄像机通道为0，但摄像机是在线状态 (Issue #1437)




 
嗯嗯，感谢您的回复，之前忽略了sip.id合规性的检测（我后边调整一下这块儿），不过如果是sip.id有问题，还有个现象解释不通，同样的设备端配置，我如果wvp和zlm都直接在宿主机启动（不采用容器部署），ipc在wvp页面也是完全正常的，只有docker部署时才会出现上述问题。
 另外，docker部署时，还有个现象，wvp页面中显示的设备地址是docker网络的网关（我的docker用的自定义网络，网关172.18.0.1），端口是一个随机分配的端口，类似（172.18.0.1:43216）这种，如果不用docker部署，则显示的是设备的正常地址和5060端口，类似（192.168.1.110:5060）这种（我宿主机是192.168.1.*网段），不清楚这个现象是否是个线索能推测ipc不通但nvr能通的原因。
 目前，同样的配置，不用docker部署的话，是完全没有问题的，我尝试docker部署，是为了方便在其他环境快速部署，两种方式应该最大的区别就是网络环境不同，我在尝试消除两种部署方式的网络差异，看看是否能解决。
