### ISSUE TITLE
请问下视频播放端口CORS跨域资源共享漏洞怎么解决

### ISSUE THREAD

**Issue by 1343228975** [648540858/wvp-GB28181-pro#1438]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
请问下视频播放端口CORS跨域资源共享漏洞怎么解决，有配置吗
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/93633113/6e19fbb6-3a3b-41c4-ba62-83c748e8892a)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
参考这个配置
```
    # 跨域配置，不配置此项则允许所有跨域请求，配置后则只允许配置的页面的地址请求， 可以配置多个
    allowed-origins:
        - http://localhost:8008
        - http://192.168.1.3:8008
```
只有开启的才可以访问
