### ISSUE TITLE
chrome浏览器播放有流但黑屏的问题

### ISSUE THREAD

**Issue by zhengdaguang** [648540858/wvp-GB28181-pro#144]
作者你好，我使用最新的前后端代码版本，使用火狐浏览器播放没有问题，但使用chrome浏览器播放有流但会黑屏。
同时流媒体服务器Zlmediakit会日志打印报错信息，显示如下图，请问需要如何解决？谢谢。
![1](https://user-images.githubusercontent.com/40955943/129324538-1ec9e62a-73ca-4d71-a109-47d8013d96f5.png)

**Comment by Wanik666** [comment]
你好，请问这个是怎么解决的，我也是这个问题
