### ISSUE TITLE
技术咨询：wvp播放时会串流，这个怎么解？

### ISSUE THREAD

**Issue by 474873060** [648540858/wvp-GB28181-pro#1440]
运行一段时间后，关闭播放A视频，也正常推送了关闭指令，返回也正常，但是在播放其他视频时会串流到A视频，或者串流到其他的视频

wvp和zlmediakit都是最新的版本
设备是通过GB28281接入的
设备的编码格式是H.265X

**Comment by 474873060** [comment]
> ssrc校验开了吗

没开

**Comment by flylee85** [comment]
ssrc在哪里开启？是设备列表--编辑里面么？

**Comment by 474873060** [comment]
是的

**Comment by bigff-0527** [comment]
你好，问题解决了吗
