### ISSUE TITLE
wvp文档网页无法打开

### ISSUE THREAD

**Issue by shazhida** [648540858/wvp-GB28181-pro#1441]
https://doc.wvp-pro.cn 网页无法打开
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20414259/34851478-f4e4-4341-ba78-b6835c9f004e)

**Comment by CNPolaris** [comment]
> https://doc.wvp-pro.cn 网页无法打开 ![image](https://private-user-images.githubusercontent.com/20414259/328145330-34851478-f4e4-4341-ba78-b6835c9f004e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDMyODEsIm5iZiI6MTcxNTA0Mjk4MSwicGF0aCI6Ii8yMDQxNDI1OS8zMjgxNDUzMzAtMzQ4NTE0NzgtZjRlNC00MzQxLWJhNzgtYjY4MzVjOWYwMDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAwNDk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZjgxYjY1ZDM4Njc0ZTUyMDZkNTJiYzFmN2U1ZjMzODBjMWYwZGNkZGMwMjFjMTYwODViNzI1YTNjMzI5MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PdpEWzU9I2VDKN1Wx5djr1CwvjGKaYXcBrI92tykcHM)

源码里面有作者的文档 可以离线查看的

**Comment by 648540858** [comment]
gitee pages停止服务了，暂时还没找到合适部署的地方，耐心等待一段时间吧，可以打开doc目录，里面就是官网的文档

**Comment by 648540858** [comment]
可以使用了
