### ISSUE TITLE
技术咨询-设备大面积离线

### ISSUE THREAD

**Issue by answer666** [648540858/wvp-GB28181-pro#1442]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 编辑安装
 - 2. 部署环境 windows / ubuntu/ centos ...
 宝塔 centos
 - 3. 端口开放情况
<img width="522" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/82018243/b113a221-559b-4ad7-b55d-3baa8bb05010">
 - 4. 是否是公网部署 
 是
 - 5. 是否使用https
 是 https
 - 6. 方便的话提供下使用的设备品牌或平台
 海康
 - 7. 你做过哪些尝试
 查看redis key scan 是否造成影响。 重启 zlm 和 java 以及服务器。 查看 java 服务器。 修改 sip.ip配置等。
 - 8. 代码更新时间
2.7.0
<img width="760" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/82018243/0f3c2799-5c04-41db-a38b-2092d1869e97">

**内容描述:**
设备大面积离线， 前一天看还有 48 个设备在线， 今天就25个， 48也只是一小部分。 
<img width="610" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/82018243/5649e70e-0023-437e-8415-b84c5a578439">

**截图**  
<img width="610" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/82018243/4683734e-f94e-496d-9f59-f52cd3bdda35">

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
离线的设备是不是分属在同一个局域网下

**Comment by answer666** [comment]
> 离线的设备是不是分属在同一个局域网下

不是局域网。 内置的是定向网络的物联网卡。配置了域名和ip的白名单。
设备刚开始是可以上线的，但是后面又掉线了。 检查，信号是满格的。网络可以访问的。
配置的是蒲公英的路由器。

**Comment by answer666** [comment]
> 离线的设备是不是分属在同一个局域网下

同一个区域的设备，昨天又突然掉线了。之前持续在线没问题的，可以确定的时候，摄像头配置肯定是没动的。 网络是一样的。
<img width="1396" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/82018243/21452645-351f-4eca-8408-19fa2576c252">

**Comment by answer666** [comment]
> > 离线的设备是不是分属在同一个局域网下

没想到我重启了下 java服务，又重启上线了。 看服务器压力也不大。

**Comment by leoxjm** [comment]
我也遇到同样的问题，最近集体离线出现了2次，每次重启就解决了。
目前做了个脚本，检测在线率低于2%就重启

集体离线的时候，用新设备连国标，日志会报错这个
2024-06-18 07:00:04.749 [wvp-15]  INFO --- c.g.i.v.g.t.e.r.impl.RegisterRequestProcessor: 135 [注册请求] 设备：xxxxxxx, 回复401: x.x.x.x:xx
重启后就能正常连接

**Comment by floatinghua** [comment]
> > 离线的设备是不是分属在同一个局域网下
> 
> 不是局域网。 内置的是定向网络的物联网卡。配置了域名和ip的白名单。 设备刚开始是可以上线的，但是后面又掉线了。 检查，信号是满格的。网络可以访问的。 配置的是蒲公英的路由器。

请问一下，这种定向的物联网卡，需要做其他的什么配置吗？我们加了定向，但是一直注册不了

**Comment by 7hxx** [comment]
> 我也遇到同样的问题，最近集体离线出现了2次，每次重启就解决了。
> 
> 1. 集体离线的时候，用新设备连wvp国标sip，日志会报错这个（wvp 2.7.1版本）
>    2024-06-18 07:00:04.749 [wvp-15]  INFO --- c.g.i.v.g.t.e.r.impl.RegisterRequestProcessor: 135 [注册请求] 设备：xxxxxxx, 回复401: x.x.x.x:xx
>    重启后就能正常连接
> 2. 可能是内存太小导致的，120台设备在线，运维-Xmx1024m只给了1G内存。
>    因为之前设备少的时候没出现这个问题，已经把内存调大了，再观察几天看看

您好，问题解决了？我也是设备大面积离线，重启WVP后就好了，您调大内存后问题解决了？
