### ISSUE TITLE
技术咨询-开启国标录像，不让实时预览生成云端录像

### ISSUE THREAD

**Issue by bigff-0527** [648540858/wvp-GB28181-pro#1443]
开启国际录像后，如何不让实时预览生成云端录像？
我目前只想要 我调用下载录像时下载录像到服务器上，不希望实时预览时 也产生云端录像
![image](https://github.com/648540858/wvp-GB28181-pro/assets/58465932/ffa6b5f9-b7b9-46ad-a38d-b78dbc885384)

**Comment by 648540858** [comment]
就这样设置就可以。

**Comment by bigff-0527** [comment]
> 就这样设置就可以。

这样设置可以录制，但是实时预览时也会产生云端录像，我只希望保存：手动去调用下载国标录像时产生的云端录像，而不是实时预览时也会产生录像。
