### ISSUE TITLE
docker-compose 文件编译运行不起来

### ISSUE THREAD

**Issue by HandsomeBoy01** [648540858/wvp-GB28181-pro#1445]
看情况，默认的是mysql数据库，但是wvpDockerfile中没有mysql，导致运行不起来
![image](https://github.com/648540858/wvp-GB28181-pro/assets/40994318/498778df-ba37-418e-8b9a-5ec5ad1ac89a)

**Comment by colorado666** [comment]
检查下数据库连接问题，记得初始化一下数据库表

**Comment by HandsomeBoy01** [comment]
> 检查下数据库连接问题，记得初始化一下数据库表

配置好了，但是ZLM连接不上，貌似都没测试 
https://github.com/ZLMediaKit/ZLMediaKit/issues/3268
