### ISSUE TITLE
技术咨询-ZLM快照图片是破损图片

### ISSUE THREAD

**Issue by shiningtalent** [648540858/wvp-GB28181-pro#1446]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

**截图**  
进入zlm为何生成的快照是破损图片
![image](https://github.com/648540858/wvp-GB28181-pro/assets/21002314/152f3a48-59f4-434e-a60d-a31fcadcab42)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/21002314/2a253cc7-5d0f-4178-94b3-c1df67288598)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
调整zlm的ffmpeg截图命令试试。
