### ISSUE TITLE
关于CSEQ码的技术咨询

### ISSUE THREAD

**Issue by BigFaceWei** [648540858/wvp-GB28181-pro#1449]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
如下图的获取cseq码和重置cseq码的key不一致，重置的key多了一个下划线，用scan好像扫不出来，是否可以跳过scan，直接用key设置
**截图**  
![1761661cc46a91d9af022236bc991c5](https://github.com/648540858/wvp-GB28181-pro/assets/36758828/a47e23fe-64a2-4a63-83fa-ccec9fde034c)

![315e720245e4acc7008af329ce3097b](https://github.com/648540858/wvp-GB28181-pro/assets/36758828/fa1e806f-0f12-4ca5-9c77-28643a015988)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by BigFaceWei** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/36758828/15f6e0e3-a2d1-406f-8335-44f6bee00a4f)

还有一个，这里的星号前面是不是少了一个下划线

**Comment by 648540858** [comment]
是个BUG，修复了
