### ISSUE TITLE
大华摄像头点播收流超时的问题

### ISSUE THREAD

**Issue by bbdlg** [648540858/wvp-GB28181-pro#1451]
具体现象：大华摄像头（型号DH-SD3A405-ADG-PV-1）上电后吊舱转动时，wvp后台可点播成功，也可稳定运行一两个小时；但关闭流后，或启动时等待摄像头停止转动吊舱后，再次点播，将无法点播成功，提示点播超时。

经反复测试，将大华摄像头的本地SIP服务器端口，由默认的 5060 端口，改为 5065端口后，即可正常点播，无论如何反复关闭重启点播，均正常。

具体原因未知，上述经验供有缘人参考。

**Comment by 648540858** [comment]
设备是不是用了自动获取IP了，这个问题可以明确是网络或者设备问题。

**Comment by scdn** [comment]
mark
