### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by guipi01** [648540858/wvp-GB28181-pro#1456]
**如果您想报告错误，请提供以下信息 If you want to report a bug, please provide the following information:**
### **可复现问题的步骤 The steps to reproduce.**
The latest version of wvp GB28181 pro is 2.0. Let's first take a look at the effect of a normal page loading platform:
![WechatIMG599](https://github.com/648540858/wvp-GB28181-pro/assets/102499073/6dae44c9-0a0a-4845-a344-9c830c37a4d1)
When ordinary users delete their own accounts, for example:
![WechatIMG602](https://github.com/648540858/wvp-GB28181-pro/assets/102499073/bd75de7c-7b6f-40e0-9579-a2916965fa38)
![WechatIMG603](https://github.com/648540858/wvp-GB28181-pro/assets/102499073/a4d6f808-a680-4dec-9a44-c995ef8f2d1b)
This will result in non-existent users still being able to view platform resources, leading to platform information leakage
<img width="1316" alt="截屏2024-05-17 03 02 38" src="https://github.com/648540858/wvp-GB28181-pro/assets/102499073/f0a3ef53-3954-412b-8ee1-81d18533f13f">
可复现问题的网页地址 Reproducible webpage address
[http://123.60.26.178:18080/#/login](url)
This website uses the latest version of wvp-GB28181 pro, and there are no users who can view any platform resources
受影响的Valine版本、操作系统，以及浏览器信息
Affected Valve versions, operating systems, and browser information

- wvp-GB28181-pro 2.0
- OS：Windows/Linux/macOS
- Browser: Chrome、Firefox、Safair
总的来说就是 如果有用户被删除，只要他不注销账号，就一直可以访问平台的任何资源，导致信息泄漏，希望作者大大后面可以修复这个问题
In general, if a user is deleted, as long as they do not log out of their account, they can always access any resources on the platform, leading to information leakage. I hope the author can fix this problem in the future

**Comment by luwenteng** [comment]
请问下这个代码是最新拉取下来的吗，我创建用户那边报空指针,能否借鉴下代码
