### ISSUE TITLE
编辑坐标保存,提示" 位置信息格式有误，例：117.234,36.378"

### ISSUE THREAD

**Issue by scdn** [648540858/wvp-GB28181-pro#1463]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/ 
 均为编译
 - 2. 部署环境 windows / ubuntu/ centos ...
 ubuntu
 - 3. 端口开放情况
 -
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 下载最新代码重新编译,仍提示此错误
坐标通过高德坐标获取,也尝试使用提示的"117.234,36.378"输入,仍报错
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题
<img width="879" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/43884938/f49406ef-74a9-4c9b-8241-6b968454abb2">

**如何复现**
通道点击编译,输入坐标

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by shuisemuou** [comment]
![d689d922be9aaefb36ad437930ac188d](https://github.com/648540858/wvp-GB28181-pro/assets/64575384/a22466d3-e585-4128-aa8a-5ccd0ca34a64)

**Comment by scdn** [comment]
> ![d689d922be9aaefb36ad437930ac188d](https://private-user-images.githubusercontent.com/64575384/332665615-a22466d3-e585-4128-aa8a-5ccd0ca34a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODQ4MzIsIm5iZiI6MTcxNzM4NDUzMiwicGF0aCI6Ii82NDU3NTM4NC8zMzI2NjU2MTUtYTIyNDY2ZDMtZTU4NS00MTI4LWFhOGEtNWNjZDBjYTM0YTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDAzMTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlN2UzYzU0MWEwNTQzM2ZkZjUyODA2ZjcxMjBmZTg3NmI2NmUxOWY0MjRjNzkxOWI2MTg4ODA3Njk4YjE0MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MIDaz8rGkPggL-o6AF6qausDTaR5DoK0umOPaVKY1c4)

没明白你想表达的意思

**Comment by scdn** [comment]
经多次测试,2.7.0正常,2.72会报这个错
