### ISSUE TITLE
【国标级联的疑问】

### ISSUE THREAD

**Issue by lucasp35** [648540858/wvp-GB28181-pro#1464]
国标级联海康平台失败，显示离线，抓包看到报404 上级平台编码未找到，上级平台编码抓包看到的与平台给的不一致

**Comment by lucasp35** [comment]
> 国标级联如何推送分组信息，目前推送设备都在一个国标编号的分组里

可以试下添加多个平台级联，每次添加时选择分组，然后推送各自分组的通道

**Comment by tashiwo1984** [comment]
同问  ”作为上级平台，海康下级平台级联时，需要用wvp 内注册下级平台信息“。wvp 内似乎没有找到对应下级平台的注册方式。求教如何处理。

**Comment by jtfeng** [comment]
向上级平台（海康）级联失败，但是海康的录像机却可以成功级联到上级平台

**Comment by DXnima** [comment]
> > 国标级联如何推送分组信息，目前推送设备都在一个国标编号的分组里
> 
> 可以试下添加多个平台级联，每次添加时选择分组，然后推送各自分组的通道

我是想自定义分组再分享给国标平台，应该如何处理

**Comment by lucasp35** [comment]
> 向上级平台（海康）级联失败，但是海康的录像机却可以成功级联到上级平台

我的解决办法是，通过抓包可以发现，海康上级平台的平台编码和他们给出的不一样，下级平台回复404not found，在平台级联这里将编码修改为这个404的编码就可以注册上去了，要不然上级平台收到404就会认为未注册上。

**Comment by lucasp35** [comment]
> 向上级平台（海康）级联失败，但是海康的录像机却可以成功级联到上级平台

我的解决办法是，通过抓包可以发现，海康上级平台的平台编码和他们给出的不一样，下级平台回复404not found，在平台级联这里将编码修改为这个404的编码就可以注册上去了，要不然上级平台收到404就会认为未注册上。

**Comment by lucasp35** [comment]
> > > 国标级联如何推送分组信息，目前推送设备都在一个国标编号的分组里
> > 
> > 
> > 可以试下添加多个平台级联，每次添加时选择分组，然后推送各自分组的通道
> 
> 我是想自定义分组再分享给国标平台，应该如何处理

这个还没处理过，我是全部分享过去了，摄像头也不多
