### ISSUE TITLE
BUG  wvp运行一段时间之后，服务端口有大量 CLOSE_WAIT，导致服务不能正常访问

### ISSUE THREAD

**Issue by iwanlebron** [648540858/wvp-GB28181-pro#1470]
**环境信息:**

 - 1. 部署方式  wvp-prp + zlm都是编译部署
 - 2. 部署环境 centos 
 - 3. 端口开放情况 全部开放
 - 4. 是否是公网部署  是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试  重启wvp
 - 8. 代码更新时间 2.7.1

**描述错误**
描述下您遇到的问题

ava    14184 root  291u  IPv6 150703      0t0  TCP ecs-999f:11592->ecs-999f:63327 (CLOSE_WAIT)
java    14184 root  292u  IPv6 119546      0t0  TCP ecs-999f:11592->ecs-999f:63329 (CLOSE_WAIT)
java    14184 root  293u  IPv6 119547      0t0  TCP ecs-999f:11592->ecs-999f:63331 (CLOSE_WAIT)
java    14184 root  294u  IPv6 119548      0t0  TCP ecs-999f:11592->ecs-999f:63333 (CLOSE_WAIT)
java    14184 root  295u  IPv6 119549      0t0  TCP ecs-999f:11592->ecs-999f:63335 (CLOSE_WAIT)
java    14184 root  296u  IPv6 148662      0t0  TCP ecs-999f:11592->ecs-999f:63337 (CLOSE_WAIT)
java    14184 root  297u  IPv6 133417      0t0  TCP ecs-999f:11592->ecs-999f:63339 (CLOSE_WAIT)
java    14184 root  298u  IPv6 119551      0t0  TCP ecs-999f:11592->ecs-999f:63341 (CLOSE_WAIT)
java    14184 root  299u  IPv6 132778      0t0  TCP ecs-999f:11592->ecs-999f:63343 (CLOSE_WAIT)
java    14184 root  300u  IPv6 132779      0t0  TCP ecs-999f:11592->ecs-999f:63345 (CLOSE_WAIT)
java    14184 root  301u  IPv6 132780      0t0  TCP ecs-999f:11592->ecs-999f:63347 (CLOSE_WAIT)
java    14184 root  302u  IPv6 132781      0t0  TCP ecs-999f:11592->ecs-999f:63349 (CLOSE_WAIT)
java    14184 root  303u  IPv6 132782      0t0  TCP ecs-999f:11592->ecs-999f:63351 (CLOSE_WAIT)
java    14184 root  304u  IPv6 132783      0t0  TCP ecs-999f:11592->ecs-999f:63353 (CLOSE_WAIT)
java    14184 root  305u  IPv6 128730      0t0  TCP ecs-999f:11592->ecs-999f:63355 (CLOSE_WAIT)
java    14184 root  306u  IPv6 128731      0t0  TCP ecs-999f:11592->ecs-999f:63357 (CLOSE_WAIT)
java    14184 root  307u  IPv6 128732      0t0  TCP ecs-999f:11592->ecs-999f:63359 (CLOSE_WAIT)
java    14184 root  308u  IPv6 128733      0t0  TCP ecs-999f:11592->ecs-999f:63361 (CLOSE_WAIT)
java    14184 root  309u  IPv6 148663      0t0  TCP ecs-999f:11592->ecs-999f:63363 (CLOSE_WAIT)
java    14184 root  310u  IPv6 150706      0t0  TCP ecs-999f:11592->ecs-999f:63365 (CLOSE_WAIT)
java    14184 root  311u  IPv6 129894      0t0  TCP ecs-999f:11592->ecs-999f:63367 (CLOSE_WAIT)
java    14184 root  312u  IPv6 129895      0t0  TCP ecs-999f:11592->ecs-999f:63369 (CLOSE_WAIT)
java    14184 root  313u  IPv6 129897      0t0  TCP ecs-999f:11592->ecs-999f:63371 (CLOSE_WAIT)

**Comment by iwanlebron** [comment]
为什么会11592连wvp服务的端口呢

**Comment by iwanlebron** [comment]
11592是wvp的server端口

**Comment by iwanlebron** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/105045937/9797b9be-8fad-4a0b-8b1a-c434714019d5)
一直在增加

**Comment by 648540858** [comment]
优化服务器连接数

**Comment by iwanlebron** [comment]
wvp的server端口访问本地端口是什么功能

**Comment by iwanlebron** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/105045937/7c5188cc-da22-4a46-834f-67c401d00c44)
已经优化，但还是没有作用

**Comment by iwanlebron** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/105045937/924503c1-ff0c-45c8-9e9f-2806cb33a616)
f服务器连接数也是最大的

**Comment by iwanlebron** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/105045937/51cc84ea-f5fa-4994-a5ce-b7d41cf70ee6)
