### ISSUE TITLE
合并2.7.1分支后，SQL建表语句好像不匹配

### ISSUE THREAD

**Issue by penghd** [648540858/wvp-GB28181-pro#1471]
**描述错误**
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'

缺flv_port，ws_port，type等多个字段，手工按报错加上5个字段后启动成功
但前端页面登录又报：
### Cause: java.sql.SQLException: Incorrect string value: '\xE7\x99\xBB\xE5\xBD\x95' for column 'name' at row 1

**如何复现**
重新git clone项目，使用code中“数据库”中的代码建表，启动报错

```

**Comment by 648540858** [comment]
已修复
