### ISSUE TITLE
技术咨询,请问项目中的广播支持一对多吗

### ISSUE THREAD

**Issue by RebelTinker** [648540858/wvp-GB28181-pro#1472]
请问项目中的语音广播支持一对多吗,就是一个页面同时打开多个视频然后统一下发语音指令,类似本项目的视频监控页面,打开多个设备的视频,由平台统一调度,实现多个设备同时听见语音,并回复的功能,(执法记录仪统一语音调度)

**Comment by 648540858** [comment]
目前不支持，强业务的功能，可能会以后做

**Comment by RebelTinker** [comment]
好
