### ISSUE TITLE
设备支持对讲功能，对讲功能报错

### ISSUE THREAD

**Issue by lihaogis** [648540858/wvp-GB28181-pro#1473]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 centos 
 - 3. 端口开放情况  端口正常开放
 - 4. 是否是公网部署  互联网部署
 - 5. 是否使用https  没有使用https
 - 6. 方便的话提供下使用的设备品牌或平台  海康设备
 - 7. 代码更新时间  2024年4月份拉的代码

**描述错误**
设备支持对讲功能，对讲功能报错
![微信图片_20240528184555](https://github.com/648540858/wvp-GB28181-pro/assets/31950631/f4820656-4a39-40d0-899a-0080b449fb72)

**Comment by ws1065** [comment]
追踪前端后端代码看一下点击话筒的时候后台怎么调用的？

**Comment by BigFaceWei** [comment]
要使用https登录
