### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by liuhuanssg** [648540858/wvp-GB28181-pro#1474]
**环境信息:**

 - 1. 部署方式编译wvp-pro + zlm都是编译部署/
 - 2. 部署环境  centos ...
 - 3. 端口开放情况 都已开放
 - 4. 是否是公网部署  是
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台 dahua
 - 7. 你做过哪些尝试 修改了yml与https相关的配置
 - 8. 代码更新时间

**内容描述:**
原本用IP使用的平台，后来按需求配置完https，重启之后，进入前端页面，发现视频无法播放了，按F12查看报错信息，发现是4433端口的websocket无法连上，确认端口都是已经开放了的
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/42669665/56db80e9-280c-4417-9fc2-5808eeb6fdac)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
确认zlm和wvp使用的是同一套证书
