### ISSUE TITLE
技术咨询 部署 wvp+zlm 。局域网内，设备（海浪摄像头）可以注册，公网（华为云openEuler）注册不上

### ISSUE THREAD

**Issue by qingfengtaizi** [648540858/wvp-GB28181-pro#1475]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
      openEuler
 - 3. 端口开放情况
   以开放 23101 tcp和 udp
 - 4. 是否是公网部署 
   是
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
    tcpdump 没有收到注册请求。本地局域网 使用 Wireshark可以收到
 - 8. 代码更新时间

**内容描述:**

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/24245864/3ccbc31f-f22d-4254-a59f-d82ebbd2290e)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
你的海康摄像头配置网关能上网不？你的海康摄像头是否支持公网注册？

**Comment by qingfengtaizi** [comment]
> 你的海康摄像头配置网关能上网不？你的海康摄像头是否支持公网注册？

摄像头配置的问题已解决，谢谢 此贴关闭
