### ISSUE TITLE
BUG  点播后的流 rtmp正常播放 rtsp无法播放  有点异常

### ISSUE THREAD

**Issue by thylxl** [648540858/wvp-GB28181-pro#1476]
程序
![微信图片_20240529175726](https://github.com/648540858/wvp-GB28181-pro/assets/75240800/b4f49ede-6498-4d17-9df6-642b6cff42a6)
![微信图片_20240529175735](https://github.com/648540858/wvp-GB28181-pro/assets/75240800/2e7db021-1f2e-400f-b395-917d004364c2)
都是成功部署的

已成功 端口被占用了 默认的 das_media

**Comment by 648540858** [comment]
不符合提问规范
