### ISSUE TITLE
技术咨询 4G网  枪机  无法 注册设备，网线可以

### ISSUE THREAD

**Issue by qingfengtaizi** [648540858/wvp-GB28181-pro#1478]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 编译
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 欧拉操作系统
 - 3. 端口开放情况
 - 以开放
 - 4. 是否是公网部署
 - 是 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 网线摄像头可以
 - 8. 代码更新时间

**内容描述:**

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/24245864/1f040e54-bfff-43d9-b46d-2017ac6470b1)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/24245864/fc7c874b-aa42-40f2-a89d-417b263a84b6)

**抓包文件**
  
**日志**
![image](https://github.com/648540858/wvp-GB28181-pro/assets/24245864/5ed287f4-8aa6-4055-a2f8-fe00999d3660)
日志内容放这里， 文件的话请直接上传
```

**Comment by scdn** [comment]
https://github.com/648540858/wvp-GB28181-pro/issues/1267 
可以看看这个
