### ISSUE TITLE
技术咨询  录像回放时倍速播放频繁报错 streamId 不存在

### ISSUE THREAD

**Issue by luhengyu1** [648540858/wvp-GB28181-pro#1483]
复现如下
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/2f601837-1c44-4207-8a30-7dcd2a29870e)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/edffea97-9540-42e2-94f8-1389824af4d6)

代码和日志如下
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/0e1f1f31-7cf9-433b-8660-8f0530843914)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/fa1ec0f6-d1c2-4a09-ba9d-a245b15469e9)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/87296715/5b8267ea-6d21-4991-bac4-e4d344eb5c34)

这里inviteInfo中的streamInfo为null走到了if判断里面，而inviteInfo是从redis获取的，不太清楚何时会存redis或者更新redis

**Comment by 648540858** [comment]
不符合提问规范
