### ISSUE TITLE
海康交通摄像头无法解析问题

### ISSUE THREAD

**Issue by tangsky001** [648540858/wvp-GB28181-pro#1485]

**Comment by tangsky001** [comment]
![Uploading 微信图片_20240603230331.png…]()

**Comment by tangsky001** [comment]
![微信图片_20240603230623](https://github.com/648540858/wvp-GB28181-pro/assets/89033937/e861825b-acbc-46cf-abb5-4cf7cadb29ac)

**Comment by tangsky001** [comment]
![微信图片_20240603230345](https://github.com/648540858/wvp-GB28181-pro/assets/89033937/b15ee44d-df23-4cd5-b44a-050c777bb613)

**Comment by tangsky001** [comment]
![微信图片_20240603230331](https://github.com/648540858/wvp-GB28181-pro/assets/89033937/5dc44c13-3c15-43d3-abdb-58874eb7d0f2)

**Comment by gdsaize** [comment]
海康摄像机国标端口5060不要改试试，我修改后，也是收不到流。

**Comment by tangsky001** [comment]
> 海康摄像机国标端口5060不要改试试，我修改后，也是收不到流。

我试过了，效果是一样的。默认用5060 还是失败的。

**Comment by seven54** [comment]
我这边也是这样，前面还好好的。突然收不到流了。大华的就没有问题

**Comment by seven54** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37871862/19534f3b-05a9-4edf-a97e-b47b81342b4c)

**Comment by 648540858** [comment]
不清楚这样的设备与普通设备有什么区别。如果需要适配，可以联系我邮寄设备适配。不然我也没办法，联系方式 648540858@qq.com
