### ISSUE TITLE
平台能实现支持 GB/T28181-2022协议吗

### ISSUE THREAD

**Issue by shuaigelsy** [648540858/wvp-GB28181-pro#1487]
**项目的详细需求**
目前采购的新摄像头，协助都是支持 GB/T28181-2022的协议。导致注册平台不进去，公网不能点播预览
**这样的实现什么作用**

**Comment by 648540858** [comment]
目前2022付费提供，但是理论上应该是兼容2016的，除非设备不兼容2016的平台那就没办法了，可以把日志提供下看看。
需要2022的可以发送邮件给我，648540858@qq.com

**Comment by shuaigelsy** [comment]
> 目前2022付费提供，但是理论上应该是兼容2016的，除非设备不兼容2016的平台那就没办法了，可以把日志提供下看看。 需要2022的可以发送邮件给我，[648540858@qq.com](mailto:648540858@qq.com)

内网环境下，完全没有问题。只有在公网环境下会出现这个问题。

**Comment by Rocky-Hu** [comment]
> > 目前2022付费提供，但是理论上应该是兼容2016的，除非设备不兼容2016的平台那就没办法了，可以把日志提供下看看。 需要2022的可以发送邮件给我，[648540858@qq.com](mailto:648540858@qq.com)
> 
> 内网环境下，完全没有问题。只有在公网环境下会出现这个问题。

内网没问题，公网有问题？没太明白，是说用2022的内网没问题吗？我这边测试用海康的，2022的，配置了保存，抓包，摄像头SIP协议的数据都没有

**Comment by 648540858** [comment]
> > > 目前2022付费提供，但是理论上应该是兼容2016的，除非设备不兼容2016的平台那就没办法了，可以把日志提供下看看。 需要2022的可以发送邮件给我，[648540858@qq.com](mailto:648540858@qq.com)
> > 
> > 
> > 内网环境下，完全没有问题。只有在公网环境下会出现这个问题。
> 
> 内网没问题，公网有问题？没太明白，是说用2022的内网没问题吗？我这边测试用海康的，2022的，配置了保存，抓包，摄像头SIP协议的数据都没有

你可以问下克服，你的设备是不是不支持国标2016
