### ISSUE TITLE
下载的历史录像找不到位置

### ISSUE THREAD

**Issue by lihaogis** [648540858/wvp-GB28181-pro#1488]
**环境信息:**

部署方式 wvp-prp + zlm都是编译部署
部署环境 centos
端口开放情况 端口对外开放了
是否是公网部署 公网部署
是否使用https 否
代码更新时间 2024-04-20

**描述错误**
下载的录像找不到位置，看请求地址是分片下载的

![微信截图_20240606175930](https://github.com/648540858/wvp-GB28181-pro/assets/31950631/7993d1b5-79e7-4afb-b2f9-3fc2a630720c)

**Comment by 648540858** [comment]
现在下载录像不分片 等进度到100 直接下载就行了
