### ISSUE TITLE
技术咨询-串流问题

### ISSUE THREAD

**Issue by MightyTiger98** [648540858/wvp-GB28181-pro#1490]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm
版本是wvp-GB28181-2.0 version 2.3.1
遇到一个串流问题 情况是有两台摄像头 一台摄像头A通电国标上线 一台摄像头B没通电国标离线 使用生成的地址点播摄像头A是正常出摄像头A的画面 但是点播摄像头B会出现摄像头A的画面（生成的地址是两台都在线的时候获取的 录入到自己的应用中）这个有办法处理吗 还是说只能通过判断设备是否在线才运行点播

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
那么老的版本，已经不维护了

**Comment by 1579890249** [comment]
请问2.6.9版本还在维护吗    2.6.9我也出现了这个问题    我以为是zlm的问题   然后夏总说是 wvp调度的问题  https://github.com/ZLMediaKit/ZLMediaKit/issues/3623

**Comment by 648540858** [comment]
默认开启ssrcCheck可能导致有的设备不能点播,不是所有设备都那么规范的.
