### ISSUE TITLE
[技术咨询]前端用的Jessibuca是否支持播放hls格式视频

### ISSUE THREAD

**Issue by Oushinan** [648540858/wvp-GB28181-pro#1495]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境  centos ...
 - 3. 端口开放情况  服务器设备均在内网
 - 4. 是否是公网部署  否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间  2024/5/31

**内容描述:**
使用自带前端Jessibuca播放器，无法播放hls格式视频；经查阅发现Jessibuca开源版不支持hls，pro版本才支持。所以确认下项目集成的Jessibuca是否支持hls。如果不支持，大佬有推荐的前端播放器吗？支持hls，支持h265
这里改了下前端代码，如下：
devicePlayer.vue  增加了hls格式
      player: {
        jessibuca: ["hls", "ws_flv", "wss_flv"],
        webRTC: ["rtc", "rtcs"],
      },

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
在Jessibuca项目询问吧
