### ISSUE TITLE
技术咨询-关于监控OSD的支持

### ISSUE THREAD

**Issue by yuekun188** [648540858/wvp-GB28181-pro#1497]
**内容描述:**

请问GB28181-2016标准中OSD配置有明确的协议格式内容吗，大神能否下提供OSD的协议格式。

**Comment by 648540858** [comment]
没有，协议没有这方面内容，osd配置在国标GB28181-2022中有。需要升级wvp以及使用支持GB28181-2022的设备。

**Comment by yuekun188** [comment]
> 没有，协议没有这方面内容，osd配置在国标GB28181-2022中有。需要升级wvp以及使用支持GB28181-2022的设备。

感谢回复
