### ISSUE TITLE
BUG jessibuca播放器设备录像回放2倍速和4倍速播放时不能正常使用

### ISSUE THREAD

**Issue by yuekun188** [648540858/wvp-GB28181-pro#1498]
描述下您遇到的问题
jessibuca播放器设备录像回放2倍速和4倍速功能不能正常使用

**Comment by 648540858** [comment]
播放器不支持

**Comment by yuekun188** [comment]
好的，多谢发自我的手机-------- 原始邮件 --------发件人： 648540858 ***@***.***>日期： 2024年6月20日周四 晚上7:32收件人： 648540858/wvp-GB28181-pro ***@***.***>抄送： yuekun188 ***@***.***>, Author ***@***.***>主    题： Re: [648540858/wvp-GB28181-pro] BUG jessibuca播放器设备录像回放2倍速和4倍速播放时不能正常使用 (Issue #1498)
Closed #1498 as completed.

**Comment by bigff-0527** [comment]
> 播放器不支持

为什么我认识个人，能在wvp平台上也能播放倍速的录像回放呢？
