### ISSUE TITLE
国标级联目前发现的bug 和疑惑 

### ISSUE THREAD

**Issue by leo-qun** [648540858/wvp-GB28181-pro#150]
1 **InviteRequestProcessor**类 220行左右 content.append("m=video "+ sendRtpItem.getLocalPort()+" RTP/AVP 96\r\n"); 这个代码不对  按照国标来说 这块应该填写推流端口 而不是 媒体服务器的收流端口 这会导致服务器收流超时
2、**AckRequestProcessor**    类刚开始 Dialog dialog = evt.getDialog(); 这块 获取始终是null 导致后面逻辑无法继续  导致没有流

**Comment by 648540858** [comment]
1 是使用收流测试本地端口是否可以空闲可用，测试完会释放。后续会使用这个端口来推流
2 已修复
