### ISSUE TITLE
对接海康威视  点击播放提示 命令发送失败

### ISSUE THREAD

**Issue by ange12w** [648540858/wvp-GB28181-pro#1502]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/139559965/45ad1e6b-03f5-4487-9643-bbaa6491acc3)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```
[命令发送失败] 点播消息: JAIN-SIP Exception, some parameters are missing, unable to create the request

**Comment by 648540858** [comment]
不符合提问规范，请补充信息
