### ISSUE TITLE
海康摄像头对接—技术咨询

### ISSUE THREAD

**Issue by ange12w** [648540858/wvp-GB28181-pro#1505]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署 在同一台服务器
 - 2. 部署环境 centos  
 - 3. 端口开放情况 开放
 - 4. 是否是公网部署 否
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 海康威视
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
页面伤点击播放 提示命令发送失败
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/139559965/40ec81aa-3d50-4bf5-a3ae-f8e11aae6d0d)
ip=10.10.61.17 是海康摄像头IP地址  应该从哪个方向排查问题
![image](https://github.com/648540858/wvp-GB28181-pro/assets/139559965/7724dab1-d267-4df8-89e9-1b1e16eb934e)
**抓包文件**
  
**日志**
```
日志到这个地方   

日志内容放这里， 文件的话请直接上传
```

**Comment by ange12w** [comment]
![Uploading QQ截图20240621131502.png…]()

**Comment by ange12w** [comment]
![QQ截图20240621131502](https://github.com/648540858/wvp-GB28181-pro/assets/139559965/4241b086-a07c-4f07-95bb-d27f7dcf609c)

**Comment by scdn** [comment]
5060端口提示占用了

**Comment by asd123wto** [comment]
我也是，客户摄像头对接过播放来命令发送失败。都在公网，怀疑是客户的端口防火墙没开udp，或者路由复杂没有内穿
![image](https://github.com/648540858/wvp-GB28181-pro/assets/31847062/bf7f7ec7-ebfa-487a-b28f-391bc00f5a14)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/31847062/bf7f7ec7-ebfa-487a-b28f-391bc00f5a14)

**Comment by asd123wto** [comment]
> 我也是，客户摄像头对接过播放来命令发送失败。都在公网，怀疑是客户的端口防火墙没开udp，或者路由复杂没有内穿 ![图像](https://private-user-images.githubusercontent.com/31847062/342554565-bf7f7ec7-ebfa-487a-b28f-391bc00f5a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODIwNzMsIm5iZiI6MTcxOTM4MTc3MywicGF0aCI6Ii8zMTg0NzA2Mi8zNDI1NTQ1NjUtYmY3ZjdlYzctZWJmYS00ODdhLWIyOGYtMzkxYmMwMGY1YTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA2MDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZjljYTU2YTcxMGIyZmI0ODE5YmRjMWEzNGFkOWE4YjMxMjBlN2M4M2MxMzEyMzhmZjc2NGI2NTU3NjE3MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Wompj5hxqsaY0v4Ea550upg4FMm6z6q1ejfAv_x_c0)

降回2.7.1版本就好了

**Comment by 648540858** [comment]
完整日志发一下，可能跟默认不配置sip.ip自动监听有关
