### ISSUE TITLE
语音对讲功能,zlm接口调用是错误的吗?

### ISSUE THREAD

**Issue by ralax123** [648540858/wvp-GB28181-pro#1506]
1. 描述,用wvp点击语音对讲一直报错

2.通过查看接口,前端会调用接口
http://127.0.0.1/index/api/webrtc?app=broadcast
&stream=34020000002000005066_34020000001320000201
&type=push
&sign=41db35390ddad33f83944f44b8b75ded
会报404 NOT find错误

3.但是通过zlm的swagger,根本就没有/index/api/webrtc这个接口啊

ps:我本地截图的图片一致无法上传

**Comment by 648540858** [comment]
编译zlm时加上zlm支持
