### ISSUE TITLE
视频通道点播时提示“命令发送失败”

### ISSUE THREAD

**Issue by aiwatcher** [648540858/wvp-GB28181-pro#1510]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - wvp最新源码编译部署，版本号：2.7.2
 - 2. 部署环境 windows / ubuntu/ centos ...
 - ubuntu
 - 3. 端口开放情况
 - 局域网内，无任何端口限制
 - 4. 是否是公网部署 
 - 否
 - 5. 是否使用https
 - 否
 - 6. 接入设备/平台品牌
 - 海康威视，第三方品牌
 - 7. 你做过哪些尝试
 - 跟踪日志
 - 8. 代码更新时间
 - 9. 是否是4G设备接入
否
**描述错误**
git下载最新版本代码，按照编译说明编译打包，部署到测试环境测试，配置海康摄像头GB/T 28181-2016平台指向测试服务器，服务器上国标设备及通道列表能正常查看到，但进行视频点播是提示”命令发送失败“。

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/84110437/da9c71e4-9f97-4a42-8bec-8ea8af878e74)

**抓包文件**
  
**日志**
```
2024-06-26 11:30:21.953 [http-nio-180-exec-8] WARN  com.genersoft.iot.vmp.gb28181.transmit.SIPSender:128 - [新建CallIdHeader失败]， ip=192.168.2.47, transport=UDP
2024-06-26 11:30:21.955 [http-nio-180-exec-8] ERROR com.genersoft.iot.vmp.service.impl.PlayServiceImpl:571 - [命令发送失败] 点播消息: JAIN-SIP Exception, some parameters are missing, unable to create the request

```

**Comment by aiwatcher** [comment]
点播时始终提示此错误且无法正常播放视频，无其他分支现象

**Comment by aiwatcher** [comment]
在国标设备界面点”刷新“时也提示类似的错误
![image](https://github.com/648540858/wvp-GB28181-pro/assets/84110437/d93f80ac-1f4e-4f0f-9d89-6b085d95883e)

**Comment by aq491002055** [comment]
我也是这种情况

**Comment by leyankon** [comment]
sip.ip 指定一个ip,不要使用自动获取功能。

**Comment by asd123wto** [comment]
降回2.7.1版本就好了

**Comment by 648540858** [comment]
linux下用 'ip addr', windows在cmd执行‘ipconfig’，截图看一下

**Comment by aiwatcher** [comment]
dev配置文件里少了下面这项
# 作为28181服务器的配置
sip:
  ip: 0.0.0.0

补充进去就可以正常使用了

**Comment by YoungCoding** [comment]
> dev配置文件里少了下面这项
> 
> # 作为28181服务器的配置
> sip: ip: 0.0.0.0
> 
> 补充进去就可以正常使用了

感谢，照这个方法已解决
