### ISSUE TITLE
点播时SDP package中 o 选项代码不是本地SIP ID而是请求资源的ID

### ISSUE THREAD

**Issue by zhengxingmao** [648540858/wvp-GB28181-pro#1513]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 Linux 宿主机部署
 - 2. 部署环境 windows / ubuntu/ centos ...
 Ubuntu
 - 3. 端口开放情况
 端口全部开放
 - 4. 是否是公网部署 
 否
 - 5. 是否使用https
 否
 - 6. 接入设备/平台品牌
 宇视科技
 - 7. 你做过哪些尝试
 抓包
 - 8. 代码更新时间
 2024-06-20
 - 9. 是否是4G设备接入

**描述错误**
描述下您遇到的问题
页面可以看到下级平台及通道，点播对应通道时报错500 Server Internal error.
如下图所示：o 后面紧跟的应该是我本地的SIP id 而不应该是我请求资源的ID
**如何复现**
无

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/40750002/86c2ed33-c337-442e-8f14-bb07ed1d1e28)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
已修复
