### ISSUE TITLE
执法记录仪tcp主动模式进行广播时，设备tcp连接不到平台收不到声音

### ISSUE THREAD

**Issue by mrluoqiang** [648540858/wvp-GB28181-pro#1515]
**环境信息:**

 - 1. 部署方式 wvp-pro + zlm都是编译部署/  
 - 2. 部署环境    ubuntu
 - 3. 端口开放情况 防火墙没开，端口都开放
 - 4. 是否是公网部署  执法记录仪设备和wvp+zlm 都公司内网
 - 5. 是否使用https 否
 - 6. 接入设备/平台品牌  执法记录仪设备
 - 7. 你做过哪些尝试  抓包
 - 8. 代码更新时间  2024-05-22
 - 9. 是否是4G设备接入

**描述错误**
描述下您遇到的问题
想wvp+zlm 实现和执法记录仪得 语音对讲功能，走广播模式。广播模式时执法记录仪是tcp主动模式。设备和wvp平台得sip指令都交互完了，设备下发了ack指令，wvp调用 startSendRtpPassive失败，显示 tcp wait time 超时，修改了close_delay_ms这个参数 为20秒后还是显示这个错误。同时在 zlm上抓包，设备有 向zlm上发起tcp连接，但被拒绝了(端口超时被回收了)。这边有什么方法或通知  startSendRtpPassive接口后，再让设备tcp连接，保证连接上 嘛

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/42961866/ce11ad7d-3fa5-4c47-89ab-8b2cce7d89ab)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/42961866/2a516c10-000e-4907-a545-ce327eeffc85)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/42961866/94674d2b-4bbc-4c40-aedb-f956e5421e17)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```
启动监听TCP被动推流失败: wait tcp connection timeout, 参数：{"app":"broadcast","src_port":22200,"vhost":"__defaultVhost__","use_ps":"0","is_udp":"0","pt":8,"stream":"34020000001329000008_34020000001329000001","ssrc":"0102005455","only_audio":"1"}

**Comment by 648540858** [comment]
看你的描述就是设备的问题呀，设备没有在等待时间内进行连接。
