### ISSUE TITLE
[BUG + 技术咨询]  点播，录像播放和api接口（3D缩放拉框）问题

### ISSUE THREAD

**Issue by Austin20221314** [648540858/wvp-GB28181-pro#1516]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
**测试版本：2.6.9**

**1. 播放问题：**
设备注册上线后，页面国标设备栏流传输模式如果选UDP模式，ZL单端口模式，点播会出现收流超时提示，目前流传输模式只有用TCP被动模式可以正常播放。如果ZL多端口模式，无论流传输模式是UDP还是TCP被动模式，都会出现端口分配异常报错（  rtp.portrange:30000,30010），相关配置已按照很多issue里提到的公网/内网配置，端口等排查，配置确认没有问题，请问传输模式如果选UDP模式收流异常/超时还有别的原因导致吗？ZL多端口模式端口分配异常报错是否多开放些端口可以解决？
![image](https://github.com/648540858/wvp-GB28181-pro/assets/107042167/7067f198-6e60-4946-af82-bab91e8e383c)

**2. 录像播放问题**
云端录像点击播放黑屏问题，录像文件在服务器上存在，gb页面无法播放，从服务器上下载的录像是正常的，用播放器可以放的
![image](https://github.com/648540858/wvp-GB28181-pro/assets/107042167/92a19f26-6b23-4be2-b3ea-c7ad40c37298)

**3. api接口文档问题**
/api/device/control/drag_zoom/zoom_out和/api/device/control/drag_zoom/zoom_in两个接口（对应摄像头的3D功能），
根据接口文档参数填写后测试调用，海康的摄像头有缩放效果，但是不准确，大华设备调用接口没有效果
接口入参前处理如下：页面传递拉宽后的起始坐标和播放画框长款（对应length和width），midpointx/midpointy对应拉宽的中心点坐标，lengthx/lengthy为拉宽长宽（坐标原点：播放窗口左上角为原点），请问这两个接口应该怎么确定参数得到准确效果（和摄像头后台3D效果相同）？为啥大华设备这个接口没效果？
![image](https://github.com/648540858/wvp-GB28181-pro/assets/107042167/4fbb0a52-e6fe-4d95-bcb8-633ae1175259)

**配置文件如下：**
![企业微信截图_17199931332246](https://github.com/648540858/wvp-GB28181-pro/assets/107042167/f84865c9-fcde-4779-9a1c-5f1fcecc118e)

**Comment by Austin20221314** [comment]
????

**Comment by Austin20221314** [comment]
没人遇到相同或类似的问题么

**Comment by 648540858** [comment]
1. tcp可以 udp失败有两个可能原因, 1是udp端口为开放；2 是UDP丢包严重导致无法解析. 可以通过抓包确认
2.  更新最新代码测试
3. 有的设备可能不支持这个api, 很多API是需要设备硬件以及软件实现同时支持才可以的

**Comment by shuzihao** [comment]
第三个问题解决了吗，好哥哥
