### ISSUE TITLE
技术咨询：设备收流IP有时候要填内网IP才能正常

### ISSUE THREAD

**Issue by BuiltProcess** [648540858/wvp-GB28181-pro#1517]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows
 - 3. 端口开放情况
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
对接了几台海康nvr，其中一台注册上来后无法正常预览，修改设备收流IP为内网IP后才正常，不明白为什么

**截图**  
![微信截图_20240703165202](https://github.com/648540858/wvp-GB28181-pro/assets/174596626/47f3b5c9-1bef-4bf9-a580-9b4ad19af46c)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
其他IP无法收流，说明设备无法通过其他IP连接到服务器

**Comment by BuiltProcess** [comment]
> 其他IP无法收流，说明设备无法通过其他IP连接到服务器

平台是公网部署的，设备也是公网的按理应该公网IP才能访问到，但是设置成服务器内网IP才能收到流感觉有点奇怪

**Comment by 648540858** [comment]
你的公网是不是内网映射的

**Comment by BuiltProcess** [comment]
> 你的公网是不是内网映射的

  是的，之前2.7.0现升级2.7.2好像不会有这个问题了

**Comment by bigff-0527** [comment]
老哥，加个联系方式，交流一下我也是对接海康nvr
