### ISSUE TITLE
海康设备可以接入,宇视设备接入无法起流

### ISSUE THREAD

**Issue by liangfj** [648540858/wvp-GB28181-pro#1518]
**环境信息:**

 - 1. 部署方式 zlm(docker) + 编译wvp-pro
 - 2. 部署环境 centos ...
 - 3. 端口开放情况 全开
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康和宇视
 - 7. 你做过哪些尝试 TCP和UDP 切换都无法让宇视的播放

**内容描述:**
搭建的平台,海康设备通过gb20181接入播放.但是宇视烟火云台无法播放,设备可以注册进来,点播超时,宇视开发排查说平台少发一个ACK
192.168.1.130 是服务器
192.168.1.24 是海康摄像机
192.168.1.102 是宇视烟火摄像机
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/41361831/2a2c46e7-222b-4702-b5f5-69617ab6781d)

**抓包文件**
 
[tcpdump30.zip](https://github.com/user-attachments/files/16085331/tcpdump30.zip)

**日志**
```
日志内容放这里， 文件的话请直接上传
```
[wvp-2024-07-03.0.zip](https://github.com/user-attachments/files/16085380/wvp-2024-07-03.0.zip)

**Comment by scdn** [comment]
mark

**Comment by 648540858** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/18274453/18664d24-a9ad-4962-8a01-a5e46fa14781)
设备回复100后没有回复200ok。所以不会有ack

**Comment by liangfj** [comment]
我找设备端抓包,设备又发送了200ok,在服务端抓包却又没有,很奇怪,麻烦大佬再看下
设备端报文:
[设备端.zip](https://github.com/user-attachments/files/16140555/default.zip)
服务器端报文:
[服务端.zip](https://github.com/user-attachments/files/16140564/default.zip)

**Comment by 648540858** [comment]
你的服务端是怎么部署的,感觉不是固定的ip端口似的,设备发送的消息没有到服务端
