### ISSUE TITLE
WVP需要优化的功能建议，麻烦请改下

### ISSUE THREAD

**Issue by ligang891** [648540858/wvp-GB28181-pro#1521]
我刚刚试了下，用liveGBS就不会出现这三个问题，问题如下：
1、WVP-PRO->国际设备->点击“刷新”(原先边缘网关有3台通道，已上报到wvp。然后我手动关闭2台，剩下1台，再点击刷新还是3台，是BUG)
2、设备心跳不上报了，在wvp-pro上面看到设备是离线，然后进去看里面的通道还是在线，是BUG。
3、针对这次wvp项目，建议就是边缘网关每次发起注册（不管是在线或者离线），wvp都要发起更新通道同步请求，这样才能保证通道数据统一。

**Comment by 648540858** [comment]
1. 你刷新出来三个通道的话,考虑是你的设备本身就上报了三个.
2. 这个目前没做出来,通道状态不会跟随设备状态离线而离线
3. 如果下级有几十万通道,每次更新需要花费一天甚至更长时间的.这个问题其实考虑过,但是不能这么简单粗暴的处理.后续我会想办法优化这个的

**Comment by 648540858** [comment]
有欢迎一起讨论下,群策群力.
