### ISSUE TITLE
【技术咨询】无法点播，摄像头主动发送了BYE，收流超时

### ISSUE THREAD

**Issue by Rocky-Hu** [648540858/wvp-GB28181-pro#1522]
**环境信息:**

1. 部署方式：
- wvp-pro本机windows部署
- zlm docker虚拟机部署
2. 端口开发情况
都开放了，就是做本地的测试
3. IP网段情况
摄像头和wvp-pro是在同一个网段，分别是169.254.18.4和169.254.18.141，zlm在虚拟机中ip为192.168.16.3。互相是可以ping通的。

**内容描述:**
点播超时，抓包看，摄像图主动发送了BYE。

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/9419069/7eb155f2-87d8-4da1-8039-e24ef1dd39ed)

4. 疑问
Invite告诉摄像头流服务zlm的地址和端口后，摄像头就开始进行推流，但是我没抓到摄像头到虚拟机zlm的包（监听RTP协议，是的吧？），摄像头是根据什么来发送BYE的？

5. 抓包文件
[调试.zip](https://github.com/user-attachments/files/16120044/default.zip)

**Comment by tuyourui** [comment]
老哥，请问您解决了嘛？我也是相同的问题，相同的环境配置

**Comment by Rocky-Hu** [comment]
> 老哥，请问您解决了嘛？我也是相同的问题，相同的环境配置

没有，主要是Invite之后，ACK都有了，然后摄像头过了几秒钟就发送了Bye，抓包也没抓到，我猜测摄像头拿到wvp告诉它的流媒体服务和端口后，它应该是去尝试请求了，请求不到才会发Bye，但是抓包没抓到数据，这就奇怪了（也可能会抓得不对）。我觉得可能不是同网段的原因，但是我没有证据。

**Comment by Rocky-Hu** [comment]
记录：换了一个摄像头测试，不发送Bye了，同时抓包，也出现了通过RTP协议推送数据到zlmedia所在的服务器，但是就是最后提示收流超时

**Comment by huangwen-long** [comment]
![c9e4d0cf84554bd8b3545c4a7ad39fd8](https://github.com/user-attachments/assets/7b7bd2ea-2100-4c2f-9189-1c9cacf56108)
我也是收流超时，最后把wvp中media.id改成和zlm中config文件的mediaServerId一样解决了问题

**Comment by Rocky-Hu** [comment]
记录：线上进行调试了，流媒体服务所在的服务器通过抓包也看到RTP的数据包，还是收流超时

**Comment by xsdlmlrdhh** [comment]
你这种现象可能是zlmediakit端口不通，你看看invite中sdp协商的zlm收流端口通不通。端口映射对不对。

**Comment by bigff-0527** [comment]
老哥我也遇到了，不过我的是nvr，4个nvr 每个64个摄像头，都出现设备主动发送bye导致rtp超时中断了
