### ISSUE TITLE
技术咨询：将启动命令写入.sh文件，执行sh文件正常启动，但是用系统自启动则报 [线程休眠失败] : sleep interrupted

### ISSUE THREAD

**Issue by yebo-luo** [648540858/wvp-GB28181-pro#1523]
**环境信息:**

 - 1. 部署方式 编译wvp-pro + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 都开放
 - 4. 是否是公网部署  否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 2.6.9

**内容描述:**
sh文件命令：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/85433337/346f380d-96c3-438c-8e22-9d3ecc1a60e1)

Zlm和assist程序启动正常，wvp-pro服务器自启动则报错，手动执行.sh则启动正常
![image](https://github.com/648540858/wvp-GB28181-pro/assets/85433337/f1c9ac3b-af00-4005-9ea5-fa3d71c7a112)

**Comment by yebo-luo** [comment]
程序进程号存在，但是日志停在线程休眠失败，且18080访问失败

**Comment by 648540858** [comment]
自己研究下脚本的写法了,wvp不提供相关的功能, 线程休眠失败错误一般是主动ctrl+c 停止服务时会出现.希望对你有帮助
