### ISSUE TITLE
国标设备本地录像不点播，怎么把国标本地录像同步到云端录像？

### ISSUE THREAD

**Issue by Kender0221** [648540858/wvp-GB28181-pro#1525]
【技术咨询】：因为不是环境搭建问题，所以issue格式就不管了。
【前提】：
现在的国标设备录像都是需要观看（点播）一下，云端录像那边才能同步对应的国标录像文件。
【问题】：
怎么让国标设备录像每产生一个录像文件，就往云端录像那边同步一下，而不是需要手动观看（点播）才能实现。.

**Comment by Kender0221** [comment]
1

**Comment by 648540858** [comment]
没办法，国标不支持这样的操作
