### ISSUE TITLE
技术咨询-流传输模式只有tcp主动模型才能播放视频 其他模式接口1分钟后404

### ISSUE THREAD

**Issue by hanzhichao110** [648540858/wvp-GB28181-pro#1528]
环境内网服务器
  wvp           dockers部署  网络模式-host
  zlmediakit docker 部署   网络模式-bridge 
![image](https://github.com/648540858/wvp-GB28181-pro/assets/51806965/4d9078c5-d1d3-499e-bd9f-de45d6e8e3db)
相同的商汤摄像机 流传输模式 
   tcp主动模式 可以播放视频 
   udp模式 或tcp被动模式 点击播放 页面转圈 /api/play/start/xx/xx接口过了1分钟 直接404  这是怎么回事

**Comment by 648540858** [comment]
不符合提问标准
