### ISSUE TITLE
[BUG]拉流代理中添加直播地址可以正常播放，在国标中添加通道推送至上级一直无法播放

### ISSUE THREAD

**Issue by voliwee** [648540858/wvp-GB28181-pro#1529]
**环境信息:**

 - 1. 部署方式 wvp-pro  / zlm  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 wvp_pro在windows上源码启动 / ubuntu安装ZLM
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https 未启用
 - 6. 接入设备/平台品牌
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
 - 9. 是否是4G设备接入

**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
不符合提问标准,补充日志, 并且填写对应的内容

**Comment by colin354** [comment]
请问下最后解决了么？我也遇到了相同的问题
