### ISSUE TITLE
【技术咨询】sip服务器是如何向流媒体服务器推流的？

### ISSUE THREAD

**Issue by taojin1122** [648540858/wvp-GB28181-pro#1530]
**内容描述:**
在国标设备，通道列表中，点击播放时，sip服务器向设备发送了INVITE 请求
那之后向zlm流媒体服务器推流的那部分代码在哪里？如何向流媒体服务器推流的？
还是会话请求结束后，摄像机直接向流媒体服务器推流？
那么推流地址中的app为rtp可以进行修改吗？

**Comment by 648540858** [comment]
推流是设备直接向zlm推流，wvp不收流
