### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by 9loki** [648540858/wvp-GB28181-pro#1531]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
通过拉流代理的流，不关闭流进行云端录像，是只有当流关闭或者录制时长达到zlmediakit设置的mp4切片大小才会显示出一个录像文件吗？
**截图**  
![image](https://github.com/user-attachments/assets/9aa08b21-8512-4336-a5be-406f653b880a)
**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
是的
