### ISSUE TITLE
BUG 关于录像回放导致的通道列表播放状态异常的问题描述

### ISSUE THREAD

**Issue by yaoxiaojian-liuxiaojun** [648540858/wvp-GB28181-pro#1535]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境  centos 

**描述错误**
通道列表,通道播放状态异常,点击停止返回 "点播未找到"

**如何复现**
两个网页,一个播放进行录像回放,一个进行对应的通道列表查看. 通道列表,通道播放状态异常,点击停止返回 "点播未找到"

**截图**  
![image](https://github.com/user-attachments/assets/386bc09e-b844-4115-b020-1cccfd40617d)
列表请求的是/api/play/stop
![image](https://github.com/user-attachments/assets/fd3bb29c-e803-4975-82e1-687881bc7701)

解决方案:
修改 PlayServiceImpl.onPublishHandlerForPlayback
方法里的  storager.startPlay(deviceId, channelId, streamInfo.getStream()) 为 storager.startPlay(deviceId, channelId, null)

**Comment by yaoxiaojian-liuxiaojun** [comment]
调整结局方案为 删除PlayServiceImpl.onPublishHandlerForPlayback 方法里对应的  DeviceChannel deviceChannel = storager.queryChannel(deviceId, channelId);
            if (deviceChannel != null) {
                deviceChannel.setStreamId(streamInfo.getStream());
                storager.startPlay(deviceId, channelId, streamInfo.getStream());
            }

**Comment by 648540858** [comment]
不符合提问规范
