### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by cxy-sj** [648540858/wvp-GB28181-pro#1537]
**环境信息:**

 1、 部署环境 ubuntu

**内容描述:**
客户端推流推的流是H264+AAC。但是看zlm的打印got track是H264和PCMU，因为音频track没有初始化，等待10s之后超时，忽略未初始化的track。用Vlc拉流看编解码器信息是H264+AAC。
1）当前问题是10s时间超时有些长，需要2s出图，但track不准确，是流推上来的不规范吗？
**截图**  
![image](https://github.com/user-attachments/assets/354a03ab-8082-4505-87b9-d192d7f4b93a)
![image](https://github.com/user-attachments/assets/f7c37d18-95e9-4776-9515-0e9d9731be34)
![image](https://github.com/user-attachments/assets/e9e54822-66c9-4c20-8f68-696ff336a64c)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
不符合提问闺房
