### ISSUE TITLE
技术咨询-登录成功后，访问看板，提示看板数据接口需要重新登录

### ISSUE THREAD

**Issue by ranmao** [648540858/wvp-GB28181-pro#1539]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境  centos ...
 

**内容描述:**
全部编译安装独立服务器，登录成功，访问看板的监控信息返回401，提示重新登录

**截图**  
![image](https://github.com/user-attachments/assets/13777b7f-e0d9-4d32-9bec-af5c4bc20461)
![image](https://github.com/user-attachments/assets/e4b6941b-3663-4bf8-b58c-a5bf0cb56dcd)
![image](https://github.com/user-attachments/assets/97a566dc-21a7-4e38-bae0-19fd13861e42)
 
```

**Comment by ranmao** [comment]
redis 的userapikey 截图
![image](https://github.com/user-attachments/assets/e10cccaa-4156-4277-ab98-f20aea85addf)

**Comment by 648540858** [comment]
代码和前端文件是对应的，前端文件是自己编译的吗
