### ISSUE TITLE
BUG 语音喊话显示正在接通中后无反应

### ISSUE THREAD

**Issue by LLLLLhy127** [648540858/wvp-GB28181-pro#1540]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 -  wvp-prp + zlm都是编译部署
 - 2. 部署环境 windows / ubuntu/ centos ...
 - centos
 - 3. 端口开放情况
 - 已开放wvp信令端口与ZLM的rtp端口、8000端口的TCP与UDP
 - 4. 是否是公网部署 
 - 公网部署
 - 5. 是否使用https
 - 是
 - 6. 接入设备/平台品牌
 - 海康、TP-link
 - 7. 你做过哪些尝试
 - 关闭页面重试喊话
 - 8. 代码更新时间
 - 9. 是否是4G设备接入
 - 否

**描述错误**
描述下您遇到的问题
使用国标语音喊话时，偶现显示正在接通中后无反应，无法喊话成功，浏览器控制台可显示connected failed，关闭播放器断开webrtc后重试若干次后可喊话成功
**如何复现**
有明确复现步骤的问题会很容易被解决
使用国标语音喊话，一定概率出现
**截图**  
![平台截图](https://github.com/user-attachments/assets/de513f1d-0891-479b-8135-f74bbea56217)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```
SIP服务器截图：
![SIP](https://github.com/user-attachments/assets/4f218f7c-bf73-4ff7-99ae-6d47f0abcaf5)

ZLM服务器截图：
![服务器1](https://github.com/user-attachments/assets/819b382c-0616-4e9e-8918-55b243b5c064)
![服务器2](https://github.com/user-attachments/assets/f380d73c-8014-4eaa-a146-bf266604b5ad)

浏览器截图：
![浏览器](https://github.com/user-attachments/assets/7bd61fb5-387f-4c63-90a0-e7fae443a429)

**Comment by 648540858** [comment]
确定下zlm的证书和wvp使用的证书是同一套证书，不然无法完成网页推流
