### ISSUE TITLE
【技术咨询】设备录像下载_公网环境下收不到设备的MediaStatus消息

### ISSUE THREAD

**Issue by Duktig-Jay** [648540858/wvp-GB28181-pro#1541]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
  wvp+zlm都是编译部署
 - 2. 部署环境 windows / ubuntu/ centos ...
 ubuntu
 - 3. 端口开放情况
 全开
 - 4. 是否是公网部署 
 是
 - 5. 是否使用https
 是
 - 6. 方便的话提供下使用的设备品牌或平台
我测试所用的是 大华NVR1108HC-HDS4，但是公网部署的环境没有MediaStatus的日志输出，目前大概有三十多个设备
 - 7. 你做过哪些尝试
 使用同设备分别在局域网内和公网测试
 - 8. 代码更新时间
da4ac962d05194d59bb93684b7aa049b70053ee4

**内容描述:**
如题，请问是有什么配置会影响吗，我目前对比下来两边的配置基本相同
**截图**  

**抓包文件**
  [抓包文件.zip](https://github.com/user-attachments/files/16369637/default.zip)
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你的意思是局域网可以收到录像推送结束通知，部署在公网就不行了是吗。设备是同一个设备？

**Comment by Duktig-Jay** [comment]
> 你的意思是局域网可以收到录像推送结束通知，部署在公网就不行了是吗。设备是同一个设备？

是的

**Comment by 648540858** [comment]
提供下公网下载过程的日志

**Comment by Duktig-Jay** [comment]
> 提供下公网下载过程的日志

[1.log](https://github.com/user-attachments/files/16596296/1.log)
抱歉，之前忙其他事情去了，原来那个设备暂时用不了，这是另一个设备的日志 通道编号 31011200491181000101，流Id 4247E68E

**Comment by 648540858** [comment]
看日志没什么问题，感觉确实是设备没法送，原因不确定。设备可以正常下载吗

**Comment by Duktig-Jay** [comment]
> 看日志没什么问题，感觉确实是设备没法送，原因不确定。设备可以正常下载吗

可以正常下载 之前局域网测试是可以正常收到的
[2.log](https://github.com/user-attachments/files/16654512/2.log)

**Comment by 648540858** [comment]
目前不清楚原因，不过没有发送消息，这个可以确定是设备原因，只是不知道设备根据什么做的判断
