### ISSUE TITLE
串流、点击设备刷新里面某些通道会变化（名称、画面）

### ISSUE THREAD

**Issue by bigff-0527** [648540858/wvp-GB28181-pro#1542]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 编译部署
 - 2. 部署环境 windows / ubuntu/ centos ...
 - ubuntu
 - 3. 端口开放情况
 - 已正常开放，收流端口是30000-35000
 - 4. 是否是公网部署  
 - 内网、但是有映射出外网
 - 5. 是否使用https
 - 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 海康威视
 - 7. 你做过哪些尝试
 - 30000-30500端口 更改 30000-35000
 - 8. 代码更新时间
 - 2.7.1

**内容描述:**
海康NVR注册wvp，目前注册了4个NVR，正常来说每个nvr里只有64支摄像头，但是注册wvp上来有80个通道，后面有很多通道名称为“34xxxx”编号开头的，有时会发生串流（比如WVP上A设备（指nvr），点击里面的通道名称为“测试通道”播放，实际画面有时候是正常的“测试通道”的画面，过个35秒会发生自动切换其它摄像头）、有时点击刷新设备按钮会发生通道莫名的消失或者更改（比如刚才提到的通道名称为“测试通道”的通道，在通道编码不变的情况下变成了其它通道的名称，快照里的水印名称 跟通道名称不是统一的）

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你说的这些不是wvp可以控制，这是NVR设置的，你需要咨询下你的设备厂商
