### ISSUE TITLE
请问REDIS的ALARM通知是在哪里能够触发的

### ISSUE THREAD

**Issue by zhouchenxing** [648540858/wvp-GB28181-pro#1544]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
reids这边有个监听设置，我想触发一下进去debug，但是没找到在哪能够触发，所以能告知一下在哪能够触发吗？
**截图**  
![image](https://github.com/user-attachments/assets/50c07e2c-bdf9-45a4-a6e2-f7f359e2f506)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
第三方对接使用，由第三方系统触发
