### ISSUE TITLE
国标设备录像下载到100%没有响应

### ISSUE THREAD

**Issue by mervin0122** [648540858/wvp-GB28181-pro#1545]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 接入设备/平台品牌
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
 - 9. 是否是4G设备接入

**描述错误**
国标设备里面的视频录像，对录像的倍速进行调整，好像没有起作用，还有下载录像，下载到100%没有什么提示，是否没有完善，因为调用了下载接口和进度接口

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/user-attachments/assets/80c632e0-f895-4f6a-b2fc-adb916bb1884)
![1721899752631](https://github.com/user-attachments/assets/34eb2f23-8405-428a-b610-2a55b1fd1dbf)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
正常下载录像有两个前提，设备发送录像推送结束命令，或者设备中停止推流。如果设备发送100%后依然持续发送，那么就会造成无法下载，设备是什么品牌的。可以发个抓包上来
