### ISSUE TITLE
目录订阅上级平台启动定时任务

### ISSUE THREAD

**Issue by zhouchenxing** [648540858/wvp-GB28181-pro#1546]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 接入设备/平台品牌
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
 - 9. 是否是4G设备接入

**描述错误**
前端调用的是目录订阅，参数里有订阅个时间20，我的理解是向下级平台说，我只要20秒内你的目录订阅，超过20秒我就不要了，不要给我发了。所以我是觉得下发一次就够。但是代码里是起一个定时任务，定时任务的周期是这个数值和30做比较，小于30就用30，大于30就用前端的数值，感觉和我了解的目录订阅不是一个意思。是不是担心过期了，然后一直续周期。

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
目录订阅本身就是需要到期重新订阅了，类似国标的注册是有有效期的。如果你的下级要求你之发一次，那就他们的问题。折中的解决办法就是把这个订阅值设置的极大
