### ISSUE TITLE
wvp和zlmedikit按照指导配置好了，都运行起来了，不会推流，具体怎么推流的，有指令嘛？我的是大华摄像头。

### ISSUE THREAD

**Issue by zhuqiyun** [648540858/wvp-GB28181-pro#155]

**Comment by zhuqiyun** [comment]
> _No description provided._

运行起来了，但是编译部署的时候提示server.port找不到

**Comment by 648540858** [comment]
在配置里找28181配置，然后将配置信息填写与sip配置一致，网上找了个图
![大华28181](https://img-blog.csdnimg.cn/20200902104925388.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L01hcnZpbjEzMTE=,size_16,color_FFFFFF,t_70#pic_center)

**Comment by zhuqiyun** [comment]
> 在配置里找28181配置，然后将配置信息填写与sip配置一致，网上找了个图
> ![大华28181](https://camo.githubusercontent.com/84e06cf6c5fb89ee5a15c6d9f4c095ebc5ea01d0efad27a62969e8876e540f15/68747470733a2f2f696d672d626c6f672e6373646e696d672e636e2f32303230303930323130343932353338382e706e673f782d6f73732d70726f636573733d696d6167652f77617465726d61726b2c747970655f5a6d46755a33706f5a57356e6147567064476b2c736861646f775f31302c746578745f6148523063484d364c7939696247396e4c6d4e7a5a473475626d56304c303168636e5a70626a457a4d54453d2c73697a655f31362c636f6c6f725f4646464646462c745f3730237069635f63656e746572)

不是这个意思，是@value{server.port}找不到，而且配置文件中的sip host无效，实际上读到的是数据库中的值。

**Comment by 648540858** [comment]
贴一下你的配置文件
