### ISSUE TITLE
ZLMediaKit 增加了 udp被动模式，使用最新的ZLM有问题

### ISSUE THREAD

**Issue by zhqfdn** [648540858/wvp-GB28181-pro#1550]
**项目的详细需求**
https://github.com/ZLMediaKit/ZLMediaKit/commit/81aef25583514a8fa91fb79c6bfdb0e857143247
 * @param con_type 0: tcp主动，1：udp主动，2：tcp被动，3：udp被动

目前WVP我看代码里的设置是
 * @param tcpMode 0/null udp 模式，1 tcp 被动模式, 2 tcp 主动模式。
 * 使用最新的ZLM会有问题。

**Comment by zhqfdn** [comment]
同一局域网下 采用  tcp 主动模式 无法正常工作。
UDP和TCP被动正常

**Comment by xia-chu** [comment]
zlm的c api和 http api在修改或增强时不会破坏原有接口的兼容性的

**Comment by zhqfdn** [comment]
> zlm的c api和 http api在修改或增强时不会破坏原有接口的兼容性的

**Comment by 648540858** [comment]
tcp主动是服务器主动连接设备ID，除非你是就在一个局域网，不然不建议使用
