### ISSUE TITLE
推流成功了但是推流列表不显示问题

### ISSUE THREAD

**Issue by lkkljjknkui** [648540858/wvp-GB28181-pro#1552]
**环境信息:**

 - 1. 部署方式  wvp-prp + zlm都是编译部署/
 - 2. 部署环境  centos ...
 - 3. 端口开放情况 
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否

![image](https://github.com/user-attachments/assets/0b4a1acf-4fe7-46b5-a0af-a97f0d12288a)

```

**Comment by 648540858** [comment]
没看到流注册的日志
