### ISSUE TITLE
下级海康平台级联的设备正常播放10秒左右出现黑屏

### ISSUE THREAD

**Issue by MetSystem** [648540858/wvp-GB28181-pro#1556]
**环境信息:**

 - 1. 部署方式  （编译wvp-pro + zlm官方下载）
 - 2. 部署环境 （windows）
 - 3. 端口开放情况     （内网）
 - 4. 是否是公网部署  （否）
 - 5. 是否使用https     （否）
 - 6. 接入设备/平台品牌  （级联海康平台下级平台）
 - 7. 你做过哪些尝试 （ 测试不同版本的zlm ）
 - 8. 代码更新时间 
 - 9. 是否是4G设备接入 （否）

**描述错误**
播放一段时间后视频黑屏
前端报:WebSocket is closed before the connection is established.
ws://10.211.114.21:8000/rtp/55112300002000000009_55112300001310103000.live.flv
**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![87e9a5725419650df2b2e2b723438266](https://github.com/user-attachments/assets/16936e8d-0a5d-4548-8334-f2ce306f999d)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
看看wvp日志是不是触发无人观看了

**Comment by MetSystem** [comment]
您好，感谢大佬，我看了下这个日志，发现这里有点问题
![image](https://github.com/user-attachments/assets/bd7ee13d-7c81-430a-8ef5-877156475cb3)
[wvp-2024-08-05.0 - 副本.log](https://github.com/user-attachments/files/16494597/wvp-2024-08-05.0.-.log)

**Comment by 648540858** [comment]
你的日志是设备主动停止了，你换tcp被动点播试试，有可能是rtcp不通导致的

**Comment by bigff-0527** [comment]
老哥解决了吗，我的也是海康设备发了个bye过来 导致通信中断的
