### ISSUE TITLE
通道串流

### ISSUE THREAD

**Issue by SitInAndWatchSky** [648540858/wvp-GB28181-pro#156]
拉取的是一个视频流，但是播放的是另外一个，不知道怎么回事，博主给个建议。

**Comment by penghd** [comment]
流ID用了一样的，改个流ID，ID是ZLM的流ID，可以随便设很长的数字。

**Comment by Mrwengang** [comment]
流ID?怎么配置

**Comment by penghd** [comment]
你是在拉流代理里面设的流，还是前端设备国标推上来的流？
如果是拉流代理，添加代理时直接填写流ID，随便填一串，但不能跟以前的重复。
如果是国标推上来的流，那估计就是前端设备设置28181参数时，两个流的设备id和通道id完全一致了

**Comment by SitInAndWatchSky** [comment]
我也是蒙圈了，不知道怎么回事，有解决的大神，给支个招。

**Comment by penghd** [comment]
应该是今天我用gb_play_旧地址自动点播不成功后，更改ZLM配置修改rtmp_ondemand为1造成的，改这个配置ZLM就不会每个流自动生成flv，改回0后，重启ZLM和WVP后正常

**Comment by SitInAndWatchSky** [comment]
有解决方法吗？

**Comment by 648540858** [comment]
重启并不会释放已经播放的流，设备可能再推也可能已经停止了
