### ISSUE TITLE
内网部署使用UDP无法访问

### ISSUE THREAD

**Issue by mylvlin** [648540858/wvp-GB28181-pro#1561]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 通过路由器映射指定端口
 - 4. 是否是公网部署  否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台   海康NVR
 - 7. 你做过哪些尝试  TCP注册切换
 - 8. 代码更新时间

**内容描述:**
  WVP/ZL处于内网环境，该服务器无法访问外网，通过前端的网关设备做的端口映射对外提供服务

  目前问题是：外部NVR通过TCP协议注册上来可以正常播放，外部NVR通过UDP协议可以注册上来 但是无法刷新同步 ，无法播放，如海康NVR，海康无法切换协议

请问这种情况怎么处理

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
从你的描述我觉得是你的网关设备的问题，发送消息时设备的NAT映射已经失效，建议把设备的心跳间隔设置短一些测试下。
可以尝试下设备列表心跳时间一变化，就刷新同步，如果此时可以，那就是这个原因了。
