### ISSUE TITLE
国标录像下载bug

### ISSUE THREAD

**Issue by 9loki** [648540858/wvp-GB28181-pro#1562]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 接入设备/平台品牌
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
 - 9. 是否是4G设备接入

**描述错误**
描述下您遇到的问题
国标录像到100的时候，控制台会报空指针，并且不会下载，进度条就停在100%

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/user-attachments/assets/96982b75-f073-4867-876a-90e754cf16b3)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
补充下基本信息

**Comment by 9loki** [comment]
> 补充下基本信息

找到问题了，好像是国标录像置为false了，国标录像必须设置为true才能下载国标视频吗

**Comment by 9loki** [comment]
> > 补充下基本信息
> 
> 找到问题了，好像是国标录像置为false了，国标录像必须设置为true才能下载国标视频吗

看到您的另一条回答了，没有问题了，谢谢

**Comment by 648540858** [comment]
好的，那我关了

**Comment by zhouchenxing** [comment]
> > > 补充下基本信息
> > 
> > 
> > 找到问题了，好像是国标录像置为false了，国标录像必须设置为true才能下载国标视频吗
> 
> 看到您的另一条回答了，没有问题了，谢谢

能说下是怎么解决的吗，我也遇到了这个问题。

**Comment by 9loki** [comment]
> > > > 补充下基本信息
> > > 
> > > 
> > > 找到问题了，好像是国标录像置为false了，国标录像必须设置为true才能下载国标视频吗
> > 
> > 
> > 看到您的另一条回答了，没有问题了，谢谢
> 
> 能说下是怎么解决的吗，我也遇到了这个问题。

是目前项目中的逻辑有问题，后面应该会被修改
