### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by zrbg153359** [648540858/wvp-GB28181-pro#1563]
为啥只有rtmp://127.0.0.1:1935/jjj/jjj 这个地址可以播放、wvp自带的Jessibuca播放不了啊？
![XV 9(B(8ZQ9BWT~XFTZD(1L](https://github.com/user-attachments/assets/ef9091a8-c812-4d8f-b84c-69a77c4b7760)
![MRQ3I_PP6XK0JMXB$8(`XUY](https://github.com/user-attachments/assets/7c9c72c0-6613-4568-9b9f-3b1c1abce12f)

我是自己用obs推的
![45BRD__Z1IX6U~3}%A_30{9](https://github.com/user-attachments/assets/68c2e786-3f57-44fc-a790-a596faf18b29)

只有rtmp的这个地址可以在VLC播放
![8)`LB2AC}7GZLVKW7K448V2](https://github.com/user-attachments/assets/d83bf983-16ed-4b36-bf67-4ac43a35216e)

**Comment by 648540858** [comment]
提供下wvp的日志文件

**Comment by zrbg153359** [comment]
![image](https://github.com/user-attachments/assets/b3a70337-fbfd-4204-8a6f-e63d9579bdd1)

@Insert("INSERT INTO wvp_device (" +
            "device_id,"+
            "custom_name,"+
            "password,"+
            "sdp_ip,"+
            "create_time,"+
            "update_time,"+
            "charset,"+
            "ssrc_check,"+
            "as_message_channel,"+
            "broadcast_push_after_ack,"+
            "geo_coord_sys,"+
            "on_line,"+
            "media_server_id"+
            ") VALUES (" +
            "#{deviceId}," +
            "#{name}," +
            "#{password}," +
            "#{sdpIp}," +
            "#{createTime}," +
            "#{updateTime}," +
            "#{charset}," +
            "#{ssrcCheck}," +
            "#{asMessageChannel}," +
            "#{broadcastPushAfterAck}," +
            "#{geoCoordSys}," +
            "#{onLine}," +
            "#{mediaServerId}" +
            ")")

createMessageRequest 刷新国标设备缺少很多参数、新增设备的时候这些参数也没入库

**Comment by 648540858** [comment]
设备直接注册进来不要手动添加，手动添加目前有问题，一直没好好解决

**Comment by zrbg153359** [comment]
这个设备录像查询怎么查不到数据啊、只能是NVR的硬盘存储方式才能查到吗？









------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月4日(星期三) 上午9:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [648540858/wvp-GB28181-pro] 技术咨询 (Issue #1563)














 
设备直接注册进来不要手动添加，手动添加目前有问题，一直没好好解决

**Comment by 648540858** [comment]
设备录像查询就是走的国标方式查询设备自身的录像

**Comment by zrbg153359** [comment]
你好、有数据库所有表字段的注释吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月4日(星期三) 上午10:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [648540858/wvp-GB28181-pro] 技术咨询 (Issue #1563)














 
设备录像查询就是走的国标方式查询设备自身的录像
