### ISSUE TITLE
[BUG] 必须开启record-sip，才能进行国标录像的下载

### ISSUE THREAD

**Issue by 9loki** [648540858/wvp-GB28181-pro#1564]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:
开了record-sip才能进行国标录像的下载，但是开启了这个开关，当进行预览的时候也会录制，这个是不可避免的吗

**Comment by 648540858** [comment]
目前是的，后续会修改这个逻辑

**Comment by ken626014896** [comment]
请问最新版本修改这个逻辑了吗
