### ISSUE TITLE
信令发送失败

### ISSUE THREAD

**Issue by aAss12dfdd** [648540858/wvp-GB28181-pro#1567]
**环境信息:**
部署方式：zlm部署在一台ubuntu，wvp在本机idea运行，视像头，三者共通局域网，防火墙关闭，端口开放

**描述错误**
设备刷新，以及设备播放提示 “信令发送失败”

**截图**  
![1723016476660](https://github.com/user-attachments/assets/ce181056-2ef6-48c9-8d81-47a584dcf657)

![1723016501651](https://github.com/user-attachments/assets/b72b6113-fbe2-44e3-a09b-77912693f610)

**抓包文件**
  
**日志**

```2024-08-07 15:35:54.195 [http-nio-8080-exec-7]  INFO --- c.g.iot.vmp.vmanager.gb28181.play.PlayController: 87 [开始点播] deviceId：34020000001320000001, channelId：34020000001320000001, 
2024-08-07 15:35:54.298 [http-nio-8080-exec-7]  INFO --- ZLMServerFactory: 46 {"code":0,"exist":false}
2024-08-07 15:35:54.301 [http-nio-8080-exec-7]  INFO --- ZLMServerFactory: 94 {"code":0,"port":50190}
2024-08-07 15:35:54.301 [http-nio-8080-exec-7]  INFO --- com.genersoft.iot.vmp.service.impl.PlayServiceImpl: 469 [点播开始] deviceId: 34020000001320000001, channelId: 34020000001320000001,码流类型：stream:0, 收流端口： 50190, 码流：34020000001320000001_34020000001320000001, 收流模式：UDP, SSRC: 0115005082, SSRC校验：false
2024-08-07 15:35:54.311 [http-nio-8080-exec-7]  INFO --- c.g.iot.vmp.gb28181.transmit.cmd.impl.SIPCommander: 276 34020000001320000001_34020000001320000001 分配的ZLM为: FQ3TF8yT83wh5Wvzb [192.168.101.32:50190]
2024-08-07 15:35:54.311 [http-nio-8080-exec-7]  WARN --- com.genersoft.iot.vmp.gb28181.transmit.SIPSender: 128 [新建CallIdHeader失败]， ip=192.168.101.41, transport=UDP
2024-08-07 15:35:54.321 [http-nio-8080-exec-7] ERROR --- com.genersoft.iot.vmp.service.impl.PlayServiceImpl: 581 [命令发送失败] 点播消息: JAIN-SIP Exception, some parameters are missing, unable to create the request
2024-08-07 15:35:54.324 [http-nio-8080-exec-7]  INFO --- ZLMServerFactory: 114 关闭RTP Server {"code":0,"hit":1}
2024-08-07 15:35:55.313 [wvp-3]  INFO --- c.g.iot.vmp.media.zlm.ZLMMediaServerStatusManger: 110 [ZLM-HOOK事件-心跳] ID：FQ3TF8yT83wh5Wvzb
2024-08-07 15:36:05.311 [wvp-4]  INFO --- c.g.iot.vmp.media.zlm.ZLMMediaServerStatusManger: 110 [ZLM-HOOK事件-心跳] ID：FQ3TF8yT83wh5Wvzb

**#配置文件**
###  作为28181服务器的配置
sip:
  ###  [可选] 28181服务监听的端口
  port: 8116
  ###  根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  ###  后两位为行业编码，定义参照附录D.3
  ###  3701020049标识山东济南历下区 信息行业接入
  ###  [可选]
  domain: 4401150049
  ###  [可选]
  id: 44010200492000000001
  ###  [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  password: admin123
  ###  是否存储alarm信息
  alarm: false

### zlm 默认服务器配置
media:
  id: FQ3TF8yT83wh5Wvzb
  ###  [必须修改] zlm服务器的内网IP
  ip: 192.168.101.32
  ###  [可选] 有公网IP就配置公网IP, 不可用域名
  wan_ip:
  ###  [必须修改] zlm服务器的http.port
  http-port: 8021
  ###  [可选] zlm服务器访问WVP所使用的IP, 默认使用127.0.0.1，zlm和wvp没有部署在同一台服务器时必须配置
  hook-ip: 192.168.100.202
  ###  [必选选] zlm服务器的hook.admin_params=secret
  secret: 0xAvNeIj4X8QojoHyNhbeEyY7vyiKnDa
  ###  启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
  rtp:
    ###  [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
    enable: true
    ###  [可选] 在此范围内选择端口用于媒体流传输, 必须提前在zlm上配置该属性，不然自动配置此属性可能不成功
    port-range: 50000,50300 # 端口范围
    ###  [可选] 国标级联在此范围内选择端口发送媒体流,
    send-port-range: 50000,50300 # 端口范围
###  [根据业务需求配置]
user-settings:
  ###  点播/录像回放 等待超时时间,单位：毫秒
  play-timeout: 180000
  ###  [可选] 自动点播， 使用固定流地址进行播放时，如果未点播则自动进行点播, 需要rtp.enable=true
  auto-apply-play: true
  ###  推流直播是否录制
  record-push-live: false
  ###  国标是否录制
  record-sip: false
  ### 国标点播 按需拉流, true：有人观看拉流，无人观看释放， false：拉起后不自动释放
  stream-on-demand: true

**Comment by aAss12dfdd** [comment]
配置文件：
 spring:
  # 设置接口超时时间
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  # [可选]上传文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  cache:
    type: redis
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: r-7xvuzd9r4zqpxd88pjpd.redis.rds.aliyuncs.com
    # [必须修改] 端口号
    port: 6379
    # [可选] 数据库 DB
    database: 7
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password: cy832575#
    # [可选] 超时时间
    timeout: 10000
    # mysql数据源
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://rm-7xvd1541a71138r17fo.mysql.rds.aliyuncs.com:3306/wvp2?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
          username: cyroot
          password: ty89897#
          hikari:
            connection-timeout: 20000             # 是客户端等待连接池连接的最大毫秒数
            initialSize: 50                       # 连接池初始化连接数
            maximum-pool-size: 200                # 连接池最大连接数
            minimum-idle: 10                       # 连接池最小空闲连接数
            idle-timeout: 300000                  # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
            max-lifetime: 1200000                 # 是池中连接关闭后的最长生命周期（以毫秒为单位)
#[可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
  port: 8080
  # [可选] HTTPS配置， 默认不开启
  ssl:
    # [可选] 是否开启HTTPS访问
    enabled: false
    # [可选] 证书文件路径，放置在resource/目录下即可，修改xxx为文件名
    key-store: classpath:test.monitor.89iot.cn.jks
    # [可选] 证书密码
    key-store-password: gpf64qmw
    # [可选] 证书类型， 默认为jks，根据实际修改
    key-store-type: JKS

# 作为28181服务器的配置
sip:
  # [可选] 28181服务监听的端口
  port: 8116
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  # [可选]
  domain: 4401150049
  # [可选]
  id: 44010200492000000001
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  password: admin123
  # 是否存储alarm信息
  alarm: false

#zlm 默认服务器配置
media:
  id: FQ3TF8yT83wh5Wvzb
  # [必须修改] zlm服务器的内网IP
  ip: 192.168.101.32
  # [可选] 有公网IP就配置公网IP, 不可用域名
  wan_ip:
  # [必须修改] zlm服务器的http.port
  http-port: 8021
  # [可选] zlm服务器访问WVP所使用的IP, 默认使用127.0.0.1，zlm和wvp没有部署在同一台服务器时必须配置
  hook-ip: 192.168.100.202
  # [必选选] zlm服务器的hook.admin_params=secret
  secret: 0xAvNeIj4X8QojoHyNhbeEyY7vyiKnDa
  # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
  rtp:
    # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
    enable: true
    # [可选] 在此范围内选择端口用于媒体流传输, 必须提前在zlm上配置该属性，不然自动配置此属性可能不成功
    port-range: 50000,50300 # 端口范围
    # [可选] 国标级联在此范围内选择端口发送媒体流,
    send-port-range: 50000,50300 # 端口范围
# [根据业务需求配置]
user-settings:
  # 点播/录像回放 等待超时时间,单位：毫秒
  play-timeout: 180000
  # [可选] 自动点播， 使用固定流地址进行播放时，如果未点播则自动进行点播, 需要rtp.enable=true
  auto-apply-play: true
  # 推流直播是否录制
  record-push-live: false
  # 国标是否录制
  record-sip: false
  # 国标点播 按需拉流, true：有人观看拉流，无人观看释放， false：拉起后不自动释放
  stream-on-demand: true

**Comment by aAss12dfdd** [comment]
需要指定sip 的ip地址
sip:
  # [必须修改] 本机的IP，对应你的网卡，监听什么ip就是使用什么网卡，
  ip: 192.168.100.202

**Comment by TuonE** [comment]
我也遇到了同样的问题，偶尔可以正常播放。

**Comment by 648540858** [comment]
目前一些物理机上的自动识别IP存在问题，遇到问题可以指定具体的SIP.IP解决
