### ISSUE TITLE
请问wvp接入国标性能指标有吗

### ISSUE THREAD

**Issue by thelastwizardofthecentury** [648540858/wvp-GB28181-pro#1568]
比如同时注册1万、10万个国标设备，是否能处理心跳状态？
以及点播是否会导致端口不够用？这种情况下应该怎么处理

**Comment by 648540858** [comment]
没有，需要自己测试

**Comment by yw0701** [comment]
> 跑25000路，10分钟，就各种问题出来了。IO异常，redis异常，mysql异常，设备离线，请求没反应，各种超时。头大，玩几百路还行。多了，就抓狂了。16CPU，32G内存。也这样。 前端也报错：[HPM] Error occurred while trying to proxy request //api/server/system/info from 172.18.139.207:8081 to http://172.18.139.207:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

大佬，你是怎么压测的？有什么工具没
