### ISSUE TITLE
BUG：被移除的流仍然被处理

### ISSUE THREAD

**Issue by yebo-luo** [648540858/wvp-GB28181-pro#1571]
**环境信息:**

 - 1. 部署方式 wvp-pro + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 全开
 - 4. 是否是公网部署 内网
 - 5. 是否使用https 是
 - 6. 接入设备/平台品牌 海康
 - 7. 你做过哪些尝试 清除redis
 - 8. 代码更新时间 2.6.9 2024年3月
 - 9. 是否是4G设备接入

**描述错误**
1、wvp日志一直打印 [ZLM HOOK] 流注册和流注销一个被移除的流；
2、并且这个拉流之前开启了云端录像，移除后仍一直有录像文件

**Comment by 648540858** [comment]
这个日志是来自zlm发的消息，你的移除是怎么做的。是不是没有从zlm里移除，另外代码更新到最新版本测试下
