### ISSUE TITLE
技术咨询-自动负载最小

### ISSUE THREAD

**Issue by gaoweizi** [648540858/wvp-GB28181-pro#1574]
我想咨询一下，设备编辑的时候，可以选择自动负载最小。 
这个是选择负载最小的节点是整个设备通道都选择负载最小的节点，还是说通道里面的所有摄像头会自动分发到不同的节点来实现自动负载平衡？ 
我现在是有7k路监控都在一个通道里面，我如何实现多节点的负载均衡？

**Comment by 648540858** [comment]
每次点播选择负载最小的节点
