### ISSUE TITLE
如何做到在某一个时刻获取摄像头截图

### ISSUE THREAD

**Issue by zhouchenxing** [648540858/wvp-GB28181-pro#1576]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
业务场景：摄像头告警的时候，立即捕获截图，需要非常及时捕获。我的思路是告警的时候摄像头会给后台一个告警的时间，然后我拿着这个告警的时间去获取截图。不知道我的思路在wvp的代码里能否实现，或者有没有其他的解决思路。
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
目前截图只能是根据当前的流直接截图，如果想接历史的，需要全程录像。目前wvp不支持全程录像
