### ISSUE TITLE
国标设备同步到一半失败

### ISSUE THREAD

**Issue by aiiterproject** [648540858/wvp-GB28181-pro#1577]
**环境信息:**

 - 1. 部署方式：编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境   centos 
 - 3. 端口开放情况：内网本地
 - 4. 是否是公网部署 ：内网
 - 5. 是否使用https ：否
 - 6. 方便的话提供下使用的设备品牌或平台 ：海康
 - 7. 你做过哪些尝试：同步
 - 8. 代码更新时间

**内容描述:**

国标设备更新的时候到2000就停止了
**截图**  
![微信图片_20240814165612](https://github.com/user-attachments/assets/68c29864-6d88-473f-a9d6-483c6818e65f)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
看看日志是不是超时，设备没发送后续的信息
