### ISSUE TITLE
[BUG] redisMsg里的MessageListener高并发下需要优化

### ISSUE THREAD

**Issue by TiMiWang** [648540858/wvp-GB28181-pro#1578]
**描述错误**
redisMsg里的MessageListener在一些并发大的场景都有可能出现死循环，导致消息永远不被处理。
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![WX20240816-094412@2x](https://github.com/user-attachments/assets/32072c03-3bfd-4a91-a7f7-29b3cfeb1ec7)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
没明白，你具体说下

**Comment by 648540858** [comment]
已优化,欢迎大佬继续对项目提出指导意见
