### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by longzifan** [648540858/wvp-GB28181-pro#1584]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 接入设备/平台品牌
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
 - 9. 是否是4G设备接入

**描述错误**
描述下您遇到的问题
内网部署：我的问题如下表，正常来讲ip应该是公网ip，但是这个里面显示的ip是我网关的ip，但是我有深信服防火墙可以映射到互联网中，

阿里云服务器：我尝试在阿里云服务器上部署，因为是docker部署迁移很方便，同样的配置，在阿里云服务器是可以正常访问的，并且ip识别也是正常的

两套环境唯一不同的就是我在内网使用了深信服防火墙做了映射。请问这个问题我如果解决

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/user-attachments/assets/8a121817-77fa-4389-9346-e1af53cd6bee)
**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
这里的ip 端口是自动识别到的直接连接wvp的路由的IP端口
