### ISSUE TITLE
【技术咨询】怎么删除设备录像或者云端录像？

### ISSUE THREAD

**Issue by thhbbx** [648540858/wvp-GB28181-pro#1585]
我想把某个记录或者某日的设备录像（图1-1）和云端录像（图1-2）都删除，应该怎么做？Mysql中应该操作哪个表，linux中应该找哪个目录，另外拉流代理中的云端录像和国标设备通道中的云端录像（图1-3）是一个东西吗？如果需要删除应该怎么操作？图1-4的云端录像应该怎么删除？如果需要删除上述的内容，是否涉及关联表？
![1724122272439](https://github.com/user-attachments/assets/9f1acf3e-ce24-4089-8da8-07d85fafe03e)
图1-1
![1724122285336](https://github.com/user-attachments/assets/4e7ac168-75fb-44a6-bf51-2123263a27f5)
图1-2
![1724122337402](https://github.com/user-attachments/assets/39ceab63-baa1-47eb-b0cb-f8fc48e885fb)
图1-3
![1724122349264](https://github.com/user-attachments/assets/3b739a59-6c2a-473f-84eb-6bcbcdcf5335)
图1-4

**Comment by 648540858** [comment]
国标录像没有删除的功能，设备自行管理录像的存储，国标上级只能查看
