### ISSUE TITLE
【技术咨询】拉流代理中的参数应该怎么设置？

### ISSUE THREAD

**Issue by thhbbx** [648540858/wvp-GB28181-pro#1586]
请问如果想配置不间断录制，应该怎么配置拉流代理？这几个参数的用处是什么应该怎么天写，像是流应用名，流ID，无人观看的选项含义，其他选项中选项的含义，如果不选择录制难道就不能不间断录制了吗？
![image](https://github.com/user-attachments/assets/c64d7ba7-5120-4839-a71d-ba0596f96c11)

**Comment by 648540858** [comment]
不清楚可以保持默认值，具体含义可以查看zlm的文档，addproxy
