### ISSUE TITLE
点播问题

### ISSUE THREAD

**Issue by longegit** [648540858/wvp-GB28181-pro#159]
1. 点播超时，ssrc无法释放。
2. 点播成功后，由于设备端异常，导致流中断调用了on_stream_changed，ssrc无法释放
3. 开启auto-apply-play，点播发现ssrc创建了多次

**Comment by penghd** [comment]
我也遇到这个问题，即使清空了Redis，打开WVP界面看前端通道还都是在播放状态，其实根本没有，那为什么是播放状态呢？应该是前端设备返回的信息。
这个时候点播放，前端设备推上来的ssrc和ZLM不一致，ZLM日志可以看到rtp ssrc不符合，丢弃。
原因大概就是调试时重启wvp，前端设备没有更新。
现在的办法是搞成新的一样：设置数据库用mysql，关闭wvp，删除里面的所有device，重启，看是否正常。
如果不正常，再来一遍，等待1个小时（前端设备摄像机的登录有效时间3600秒，海康大华都是），重启，就正常了。

**Comment by 648540858** [comment]
ssrc现在应该没有了 ，你可以测试下
