### ISSUE TITLE
技术咨询 WVP-PRO上下级级联中，不支持自身平台的历史回放

### ISSUE THREAD

**Issue by meiwencheng** [648540858/wvp-GB28181-pro#1592]
**环境信息:**

 - 1.  编译wvp-pro/ wvp-prp + zlm都是编译部署
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 全开放
 - 4. 是否是公网部署  是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 WVP
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 2024-08-01

**内容描述:**
1、在局域网内容部署wvp-pro + zlm【简称下级WVP】,用ffmpeg把本地连续抓拍的图片用rstp推流到wvp平台，平台可以正常看直播和历史内容
2、在公网环境下部署wvp-pro + zlm【简称上级WVP】
3、把下级WVP的推流通过国际级联练配置到上级WVP
4、上级WVP的国际设备可以看到下级设备，可以正常看直播内容，但是历史画面不行，显示异常：
查询录像失败, status: 501, message: Not implemented

日志上下级都已经收到RecordInfo协议内容，但是下级好像没有完成对RecordInfo协议请求的内容做返回
是否是WVP上下架直接没有实现RecordInfo协议内容呢？
**截图**  
问题截图
![微信截图_20240826095405](https://github.com/user-attachments/assets/206cc492-2a9f-4073-89fd-61d907d49cdb)
下级日志内容
![QQ截图20240826095517](https://github.com/user-attachments/assets/99efd283-8463-4b79-8ec7-9d0791e750bf)
上级日志
![QQ截图20240826095603](https://github.com/user-attachments/assets/10c03eaa-38fd-4136-a2ed-21b37bb96c41)
](url)
**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
云端录像不支持国标级联
