### ISSUE TITLE
【技术咨询】 点播超时，局域网可以播放，公网超时

### ISSUE THREAD

**Issue by 851451394** [648540858/wvp-GB28181-pro#1593]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 -  编译部署
 - 2. 部署环境 windows / ubuntu/ centos ...         
 - centos 
 - 3. 端口开放情况
 -  开放
 - 4. 是否是公网部署 
 - 是的
 - 5. 是否使用https
 - 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 大华
 - 7. 你做过哪些尝试
 - 局域网可以用，公网不能
 - 8. 代码更新时间
 - 2.7.2版本

**内容描述:**
 公网点播超时， 局域网可以播放，公网和局域网部署了二套只有stream-ip和sdp-ip 配置不一样
**截图**  
![8f99c3f1a93b4ea667a742abf58f162](https://github.com/user-attachments/assets/b1e0159a-24e6-4918-8020-2dc49a789fcb)

**抓包文件**
  
![d48cfa1be09038a74a43c180b95d487](https://github.com/user-attachments/assets/4dfff040-2cc2-4f82-a9e8-4d9af1a2204b)

**日志**
```
![8f5cb2d0c05fb29bb9d9d12aedf6d53](https://github.com/user-attachments/assets/90095d71-60f0-4904-af2f-7225279d3a1d)

日志内容放这里， 文件的话请直接上传
```

**Comment by 851451394** [comment]
![Uploading 8f5cb2d0c05fb29bb9d9d12aedf6d53.png…]()

**Comment by 851451394** [comment]
![微信图片_20240826170530](https://github.com/user-attachments/assets/aa619f59-5642-4a7e-8aee-1acf4b567c28)
zlm日志输出
![微信图片_20240826170427](https://github.com/user-attachments/assets/4070a931-7d2f-42a9-be4f-3cd0bf480f8d)
wvp日志输出

**Comment by 648540858** [comment]
有很多类似帖子也有置顶帖，先看看
