### ISSUE TITLE
技术咨询 录像回放列表只能获取到少部分数据

### ISSUE THREAD

**Issue by 851451394** [648540858/wvp-GB28181-pro#1597]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

![企业微信截图_20240830092632](https://github.com/user-attachments/assets/354ffcfc-dddd-4eba-b7a4-e9b17b9c23ef)
![企业微信截图_20240830092616](https://github.com/user-attachments/assets/633bd8b7-507f-4d29-990d-eb9ac5e8fec3)

为什么只能获取到二条回放信息，

**Comment by 648540858** [comment]
咨询设备厂商，这是设备的实现的。
