### ISSUE TITLE
多个wvp可以连接同一个ZLM吗

### ISSUE THREAD

**Issue by zhuangQingGuang** [648540858/wvp-GB28181-pro#1598]
请问多个wvp可以连接同一个ZLM吗
试了一下启动第二个wvp连接的时候报错

**Comment by rongzedong** [comment]
不可以。 每个wvp会更新 zlm的config.ini通知网址，多个 wvp会出现混乱。但是可以通过 其他方式对 wvp进行加速。或者负载均衡
