### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by abing0610** [648540858/wvp-GB28181-pro#1599]
我们自己对于代码进行了二次开发。但是SIP协议这一部分没有还是用的WVP的。

我们是封装的WVP代码是23年9月份的代码。

问题描述：
目前所有的点播流程都是正常的。

偶发性问题：
有的时候无法进行点播，ZLM收流收不到。抓包协议发现，心跳探测也没有了。在WVP服务器抓包没有看到SIP的心跳协议。或者只有几次的心跳协议。

当前问题解决方案：
1.只重启服务，前几个摄像头可以点播，过一会还是上面问题。
2.重启服务 + 删除所有的redis缓存。然后就可以恢复正常的点播。

下一步应该从那个方向排查问题？

**Comment by rongzedong** [comment]
新的 wvp 有定期清理 redis缓存sip注册的过程。 不知道你手里的代码是否有同样的过程。 另外 ，wvp提供付费技术咨询群，如果是商业应用建议可以考虑加入以下子。

**Comment by abing0610** [comment]
> 新的 wvp 有定期清理 redis缓存sip注册的过程。 不知道你手里的代码是否有同样的过程。 另外 ，wvp提供付费技术咨询群，如果是商业应用建议可以考虑加入以下子。

能帮忙说一下是哪个清理任务么？或者哪个实现类？

我找到了这个SipSubscribe类，但是发现这里面没有删除redis缓存的地方。

**Comment by rongzedong** [comment]
可以看一下新版本代码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月6日(周五) 下午4:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] 技术咨询 (Issue #1599)




  
新的 wvp 有定期清理 redis缓存sip注册的过程。 不知道你手里的代码是否有同样的过程。 另外 ，wvp提供付费技术咨询群，如果是商业应用建议可以考虑加入以下子。
  
能帮忙说一下是哪个清理任务么？或者哪个实现类？
 
我找到了这个SipSubscribe类，但是发现这里面没有删除redis缓存的地方。
