### ISSUE TITLE
海康的NVR无法获取到摄像头列表

### ISSUE THREAD

**Issue by motlhuhu** [648540858/wvp-GB28181-pro#16]
能获得设备，但是无法获得子设备

**Comment by motlhuhu** [comment]
![image](https://user-images.githubusercontent.com/5844270/102732619-2a4fb200-4376-11eb-90db-7259d149e038.png)

**Comment by 648540858** [comment]
确定确实存在子目录? 你是如何确定的

**Comment by xuanhuangkeji** [comment]
我这边也有同样的问题，点击通道进去没有设备，有时候有有时候没有

**Comment by 648540858** [comment]
抓包看下，看不到通道信息，一般是设备不回复catlog消息

**Comment by 648540858** [comment]
因为没收到你的信息，这个问题我先关闭了
