### ISSUE TITLE
chrome播放黑屏，firefox可以

### ISSUE THREAD

**Issue by zouxiaodong** [648540858/wvp-GB28181-pro#160]
chrome:
![image](https://user-images.githubusercontent.com/46236818/133538812-c01d789d-51a0-47e5-8b2a-c7739d7ddf3c.png)
firefox:
![image](https://user-images.githubusercontent.com/46236818/133538841-75156466-50bf-46db-8f18-ae96ad31c555.png)

**Comment by Lus-WTC** [comment]
开了 浏览器硬件加速好像就可以了

**Comment by zouxiaodong** [comment]
> 开了 浏览器硬件加速好像就可以了

试了下开不开硬件回事都不行

**Comment by 648540858** [comment]
我先关闭了，解决了欢迎你回复下消息。播放器目前的问题，因为是集成其他开源项目的，只能等原作者修复

**Comment by August1023** [comment]
@wenhongquan 你好！是在这里设置的吗？
![image](https://user-images.githubusercontent.com/45287355/205569876-9f754987-69a0-449c-8731-ced50d80c0d7.png)

**Comment by August1023** [comment]
@wenhongquan 有效果，但是实时监控的延迟会越来越大，这个有办法处理吗？
