### ISSUE TITLE
翻遍了整个项目和文档，就是长不到网页的默认登陆的用户名和密码，大家都不好奇 ，咋登陆进系统的

### ISSUE THREAD

**Issue by yanpengfei-git** [648540858/wvp-GB28181-pro#1600]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by rongzedong** [comment]
admin/admin

**Comment by LeiYangGH** [comment]
数据库脚本
```sql
INSERT INTO wvp_user
VALUES (1, 'admin', '21232f297a57a5a743894a0e4a801fc3', ...);
```
其中`21232f297a57a5a743894a0e4a801fc3`是`admin`的md5.

**Comment by rongzedong** [comment]
加到文档里吧？别让人猜了



---原始邮件---
发件人: "Yang ***@***.***&gt;
发送时间: 2025年6月4日(周三) 下午3:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] 翻遍了整个项目和文档，就是长不到网页的默认登陆的用户名和密码，大家都不好奇 ，咋登陆进系统的 (Issue #1600)


LeiYangGH left a comment (648540858/wvp-GB28181-pro#1600)
 
数据库脚本
 INSERT INTO wvp_user VALUES (1, 'admin', '21232f297a57a5a743894a0e4a801fc3', 1,...,         '3e80d1762a324d5b0ff636e0bd16f1e3');
 
其中21232f297a57a5a743894a0e4a801fc3是admin的md5.
