### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by LiaoXH** [648540858/wvp-GB28181-pro#1604]
**环境信息:**

 - 1. 部署方式/    wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos
 - 3. 端口开放情况 10000，8000，8116端口公网映射开放。
 - 4. 是否是公网部署  内网+公网ip映射部署
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
2024.02

**内容描述:**
由于服务器架构网络问题，wvp+ZLM是在内网部署，设备需要公网接入，通过一个公网ip映射到内网服务器的端口，因为限制了内网无法访问公网ip，那此时的sdp-ip要如何配置？配置公网ip的话无法发送sdp信令，内网ip的话摄像头无法拿到sdp；这个网络情况需要如何来解决？
1、国标注册正常，正常收到国标设备注册、心跳信息
2、点播超时
![c1d0aa8741536ca3d5fbc80d6b969a9](https://github.com/user-attachments/assets/a1ac200a-1fac-4cb1-b2b7-217b2b1f0580)

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by LiaoXH** [comment]
本地局域网已同步模拟部署测试成功，端口开放情况也保持一致，生产环境的网络架构问题导致无法点播，寻求大大帮忙

**Comment by rongzedong** [comment]
外网做一个相同的系统，内网再做一个。 作为国标级联到内网。 参考 文档中的，网闸配置。
另外，请教一下你这个是怎么配置成功的？我用最新的mater分支测试了一下，总是无法播放注册上来的国标通道。

**Comment by LiaoXH** [comment]
ok.我没看到网闸配置相关配置，如果可以的话发一下对应的文档。
这个是wvp的配置，zlm没有其他额外配置
spring:
  # 设置接口超时时间
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  # [可选]上传文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: 127.0.0.1
    # [必须修改] 端口号
    port: 6379
    # [可选] 数据库 DB
    database: 7
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password:
    # [可选] 超时时间
    timeout: 10000
    # mysql数据源
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ip:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
          username: root
          password: xxx
          hikari:
            connection-timeout: 20000             # 是客户端等待连接池连接的最大毫秒数
            initialSize: 50                       # 连接池初始化连接数
            maximum-pool-size: 200                # 连接池最大连接数
            minimum-idle: 10                       # 连接池最小空闲连接数
            idle-timeout: 300000                  # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
            max-lifetime: 1200000                 # 是池中连接关闭后的最长生命周期（以毫秒为单位)
#[可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
  port: 18080
  # [可选] HTTPS配置， 默认不开启
  ssl:
    # [可选] 是否开启HTTPS访问
    enabled: false
    # [可选] 证书文件路径，放置在resource/目录下即可，修改xxx为文件名
    key-store: classpath:test.monitor.89iot.cn.jks
    # [可选] 证书密码
    key-store-password: gpf64qmw
    # [可选] 证书类型， 默认为jks，根据实际修改
    key-store-type: JKS

# 作为28181服务器的配置
sip:
  # [必须修改] 本机的IP，对应你的网卡，监听什么ip就是使用什么网卡，
  # 如果要监听多张网卡，可以使用逗号分隔多个IP， 例如： 192.168.1.4,10.0.0.4
  # 如果不明白，就使用0.0.0.0，大部分情况都是可以的
  # 请不要使用127.0.0.1，任何包括localhost在内的域名都是不可以的。
  ip: 内网
  # [可选] 28181服务监听的端口
  port: 8116
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  # [可选]
  domain: 3402000000
  # [可选]
  id: 34020000002110000001
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  password: bajiuwulian1006
  # 是否存储alarm信息
  alarm: true
  record: true
  showIp: 外网

#zlm 默认服务器配置
media:
  id: xxx
  # [必须修改] zlm服务器的内网IP
  ip: 内网
  # [必须修改] zlm服务器的http.port
  http-port: 804
  # [可选] 返回流地址时的ip，置空使用 media.ip
  stream-ip: 内网
  # [可选] wvp在国标信令中使用的ip，此ip为摄像机可以访问到的ip， 置空使用 media.ip
  sdp-ip: 外网
  # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip
  hook-ip: 内网
  # [可选] zlm服务器的http.sslport, 置空使用zlm配置文件配置
  http-ssl-port: 1443
  # [可选] zlm服务器的hook.admin_params=secret
  secret: UCqUZIpJAAxcFMVYDKf6YzSLGV9bVGte
  # 录像保存时长
  record-day: 30
  # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
  rtp:
    # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
    enable: false
    # [可选] 在此范围内选择端口用于媒体流传输, 必须提前在zlm上配置该属性，不然自动配置此属性可能不成功
    port-range: 50000,50300 # 端口范围
    # [可选] 国标级联在此范围内选择端口发送媒体流,
    send-port-range: 50000,50300 # 端口范围
  # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
  record-assist-port: 18081
# [根据业务需求配置]
user-settings:
  # 点播/录像回放 等待超时时间,单位：毫秒
  play-timeout: 10000
  # [可选] 自动点播， 使用固定流地址进行播放时，如果未点播则自动进行点播, 需要rtp.enable=true
  auto-apply-play: false
  # 设备/通道状态变化时发送消息
  device-status-notify: true
  # 推流直播是否录制
  record-push-live: true
  # 国标是否录制
  record-sip: true
  # 是否开启sip日志
  sip-log: false
  # 是否开启sql日志
  sql-log: false
  # 国标点播 按需拉流, true：有人观看拉流，无人观看释放， false：拉起后不自动释放
  stream-on-demand: false
# [可选] 日志配置, 一般不需要改
logging:
  config: classpath:logback-spring-local.xml

**Comment by rongzedong** [comment]
发一下 zlm的 config.ini中的 hook 段看一下

**Comment by LiaoXH** [comment]
![image](https://github.com/user-attachments/assets/8a96ccef-eef2-43cc-a5bd-4942c42152a9)

**Comment by 648540858** [comment]
sdp.ip配置为公网IP,但是不支持设备同是处于内网和外网,双网都有设备做国标级联解决
