### ISSUE TITLE
希望wVP实现的新功能，此功能应与你的具体业务无关

### ISSUE THREAD

**Issue by rongzedong** [648540858/wvp-GB28181-pro#1607]
**项目的详细需求**

目前的通道编辑功能不会自动完善通道信息的 gps 三种类型数据。在地图展示功能的时候，就无法显示正确的位置。希望在修改通道信息的时候会根据设备定位类型 来通过算法完善三种gps信息并保存到 wvp_device_channel表内。

**这样的实现什么作用**

具体的实现可以通过js的方式或者 IDeviceChannelService 类下面的
updateGps
updateChannel
具体实现的时候进行实现。

**Comment by 648540858** [comment]
新版本会支持的
