### ISSUE TITLE
技术咨询--TCP主动后续处理

### ISSUE THREAD

**Issue by 191474639** [648540858/wvp-GB28181-pro#1608]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
zlm（docker） wvp编译
 - 2. 部署环境 windows / ubuntu/ centos ...
 centos 7
 - 3. 端口开放情况
 全开
 - 4. 是否是公网部署 
 是
 - 5. 是否使用https
 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 -ffmpeg 推音频文件
 - 8. 代码更新时间
最新

**内容描述:**
  ffmpeg -re -i test.wav -acodec pcm_alaw -ar 8000 -ac 1 -f rtsp rtsp://x.1.8.11:8554/broadcast/41010500002000000001_41010500002000000001?sign=e10adc3949ba59abbe56e057f20f883e
进行公网语音对讲失败，设备是接入到国标平台了
**截图**  
![image](https://github.com/user-attachments/assets/531b53e7-ed98-4bf0-b858-61b13b814281)
![image](https://github.com/user-attachments/assets/723a002b-b2e0-46b0-a949-9ca33a3be5d3)
![image](https://github.com/user-attachments/assets/ed35c625-780a-4e43-a0b4-37a525686a52)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
![5ae566ed1f0c391fff94e1b648b0680](https://github.com/user-attachments/assets/77fded6c-29b9-4746-89f3-2a518fdec6e1)

**Comment by 191474639** [comment]
日志
![5ae566ed1f0c391fff94e1b648b0680](https://github.com/user-attachments/assets/4f4b7097-7b33-4063-af64-2a1dad8f10b2)

**Comment by 648540858** [comment]
此日志是正常日志
