### ISSUE TITLE
技术咨询-海康nvr莫名其妙掉线了

### ISSUE THREAD

**Issue by bigff-0527** [648540858/wvp-GB28181-pro#1609]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
有通道62个，不知道为什么设备列表显示离线，心跳时间是前一天的，不清楚是海康设备的问题，还是wvp，遇到好几次了，重启完后好像就会恢复正常
**截图**  
![image](https://github.com/user-attachments/assets/216637dd-6133-4f26-8b74-e2538656e150)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by tao-jin** [comment]
我也遇到了 导致回放显示RTPServer超时 重启了NVR就好了

**Comment by bigff-0527** [comment]
> 我也遇到了 导致回放显示RTPServer超时 重启了NVR就好了

奇了怪咯，我看nvr的网络资源又没有吃满，交换机是千兆的，我是内网 映射出外网的，难道是路由器承受不了？还有个问题就是，我一个一个点击监控点位播放，播放十几个没问题，但是我写个循环遍历某个区域，区域内有十几个监控，遍历请求wvp，返回给我播放地址后，总是有个别几个播放不了的，ws播放地址请求不到，不知道是不是网络的问题

**Comment by 648540858** [comment]
代码什么时候的

**Comment by bigff-0527** [comment]
> 代码什么时候的

2.7.1

**Comment by 648540858** [comment]
更新代码 测试，太老了
