### ISSUE TITLE
用户名与密码不能修改

### ISSUE THREAD

**Issue by kylinth** [648540858/wvp-GB28181-pro#161]
用户名与密码不能修改, RTMP推流不上去，以前没有更新的可以推流上去

**Comment by SitInAndWatchSky** [comment]
可以修改，在数据库里面修改，然后启动应用生效。

**Comment by penghd** [comment]
昨天改MediaServer 端口，wvp配置改了没用，都得靠改数据库，现在BUG比较多，大佬们赶紧改完重发个Docker吧。

**Comment by 648540858** [comment]
已修复
