### ISSUE TITLE
开始点播正常，过段时间无法播放视频显示收流超时

### ISSUE THREAD

**Issue by abing0610** [648540858/wvp-GB28181-pro#1615]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 wvp编译部署。zlm是docker部署
 - 2. 部署环境 windows / ubuntu/ centos ...
 - ubuntu
 - 3. 端口开放情况
 - 开放
 - 4. 是否是公网部署 
 - 内网部署
 - 5. 是否使用https
 - 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 各个品牌都有
 - 7. 你做过哪些尝试
 - 梳理过源码，SIP协议也抓包过，添加日志也分析过。没有找到根本原因
 - 8. 代码更新时间
 - 2023年9月代码。

**内容描述:**
目前所有的点播流程都是正常的。

偶发性问题：
有的时候无法进行点播，ZLM收流收不到。抓包协议发现，心跳探测也没有了。在WVP服务器抓包没有看到SIP的心跳协议。或者只有几次的心跳协议。

当前问题解决方案：
1.只重启服务，前几个摄像头可以点播，过一会还是上面问题。
2.重启服务 + 删除所有的redis缓存。然后就可以恢复正常的点播。

下一步应该从那个方向排查问题？

**Comment by bigff-0527** [comment]
我也差不多遇到这样，但是我的是rtp超时了，抓包发现是设备主动发送bye停止推流导致的，不知道为什么会这样

**Comment by abing0610** [comment]
> 我也差不多遇到这样，但是我的是rtp超时了，抓包发现是设备主动发送bye停止推流导致的，不知道为什么会这样

我的是全部摄像头都这样。有很多的NVR，同时出现这种情况。我的抓包没有看到bye。

他们有回复说是有清理SIP注册缓存就可以，我没有找到相关的实现。你这边有找到相关的实现么？

**Comment by bigff-0527** [comment]
应该是redis吧，我清理了也一样不行

**Comment by 648540858** [comment]
代码更新下 你的代码很老了

**Comment by abing0610** [comment]
> 代码更新下 你的代码很老了


应该是跟 代码没有关系。我前天把UDP切换成了TCP被动协议，目前这两天没有复现上面的问题。

**Comment by abing0610** [comment]
> 我也差不多遇到这样，但是我的是rtp超时了，抓包发现是设备主动发送bye停止推流导致的，不知道为什么会这样

切换成TCP被动协议试一下，我的这几天可以了。没有出现点播超时的情况了。
