### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by qq1729849384** [648540858/wvp-GB28181-pro#1618]
**环境信息:**

 - 1. 部署方式  wvp-prp + zlm都是编译部署
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 全开放
 - 4. 是否是公网部署 内网部署
 - 5. 是否使用https 否
 - 6. 接入设备/平台品牌 海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 2024/9/2
 - 9. 是否是4G设备接入 否

**描述错误**
拉流代理中，新增拉流代理并且启动，可以正常播放，但是重启zlm之后就不能播放了

**如何复现**
拉流代理中，新增拉流代理并且启动，可以正常播放，但是重启zlm之后就不能播放了

**截图**  
![image](https://github.com/user-attachments/assets/6012ded1-8b69-481a-9a5b-ee607797cefa)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
更新到最新代码测试下
