### ISSUE TITLE
BUG /api/proxy/list 增加query实际不可用

### ISSUE THREAD

**Issue by Maozw** [648540858/wvp-GB28181-pro#1619]
我看了下接口声明中参数做了声明，但是实际中并没有约到，看看作者能否增加必要的几个参数过滤，比如app，stream等参数进行过滤查询。
@Operation(summary = "分页查询流代理", security = @SecurityRequirement(name = JwtUtils.HEADER))
    @Parameter(name = "page", description = "当前页")
    @Parameter(name = "count", description = "每页查询数量")
    @Parameter(name = "query", description = "查询内容")
    @Parameter(name = "online", description = "是否在线")
    @GetMapping(value = "/list")
    @ResponseBody
    public PageInfo<StreamProxyItem> list(@RequestParam(required = false)Integer page,
                                          @RequestParam(required = false)Integer count,
                                          @RequestParam(required = false)String query,
                                          @RequestParam(required = false)Boolean online ){

        return streamProxyService.getAll(page, count);
    }

**Comment by 648540858** [comment]
更新到最新代码测试下
