### ISSUE TITLE
[技术咨询] 多zlm节点时默认节点点播失败

### ISSUE THREAD

**Issue by thelastwizardofthecentury** [648540858/wvp-GB28181-pro#1623]
**环境信息:**

 - 1. 部署方式  编译wvp-pro+ zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 所有
 - 4. 是否是公网部署   否
 - 5. 是否使用https  否

我在同一台服务器上部署了4个节点(1,2,3,4)，除端口不同外，其他配置一样。
使用wvp接入国标设备后，主节点1 ，无法点播视频，直接提示通道停止推流，其他节点可以正常播放
如果把节点2设为主节点，则节点2也无法点播了

**Comment by 648540858** [comment]
更新到最新代码测试下
