### ISSUE TITLE
技术咨询 设备录像无法播放，怎么排查？

### ISSUE THREAD

**Issue by ruiboot** [648540858/wvp-GB28181-pro#1629]
**环境信息:**

 - 1. 部署方式  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos ...
 - 3. 端口开放情况 端口已开放
 - 4. 是公网部署 
 - 5. 没有使用https
 
```

**Comment by 648540858** [comment]
欢迎来星球咨询
