### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by loupXing** [648540858/wvp-GB28181-pro#1631]
**环境信息:**

 - 1. 部署方式 编译wvp-pro / zlm(docker) 
 - 2. 部署环境 centos8
 - 3. 端口开放情况：端口已开放
 - 4. 是否是公网部署：是 
 - 5. 是否使用https：没有使用

**内容描述:**
监控使用的是4G流量卡，一个月40G流量，但是在没有点播的情况下，40G流量一周内被用完

**Comment by 648540858** [comment]
自行查询做了什么操作
