### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by xiaolinrui** [648540858/wvp-GB28181-pro#1635]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/  是编译部署/
 - 2. 部署环境 centos ...
 - 3. 端口开放情况 能开通的都开通了
 - 4. 是否是公网部署  否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康摄像头
 - 7. 你做过哪些尝试
 - 8. 代码更新时间（旧版本请更新最新版本代码测试）刚下的代码master
 -

**内容描述:**
预置位设置可以，巡航也可以，但是预置位查询报 “获取设备预置位超时”错误
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
可能是设备不支持预置位查询
