### ISSUE TITLE
收流超时问题

### ISSUE THREAD

**Issue by beesboy** [648540858/wvp-GB28181-pro#1636]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu22，WVP+Redis一台服务器，Mysql一台服务器，ZLM一台服务器
 - 3. 端口开放情况：内网环境，防火墙全关
 - 4. 是否是公网部署 ：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台，摄像头为海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间（旧版本请更新最新版本代码测试）20240927

**内容描述:**
摄像头正常注册在线，通道也能显示出来，尝试了UDP，TCP主动，TCP被动三个模式进行播放
调用：/api/play/start/44031100491320000001/44031100491320000002的时候一直转圈圈，然后响应{"code":-2,"msg":"收流超时","data":null}
抓包和日志显示摄像头已经推流，且用VLC组装流地址能够正常播放
给我感觉是卡在了下图第7步的位置
![image](https://github.com/user-attachments/assets/b93ac5b7-76de-4edb-8aba-895a96952551)

**截图**  
![image](https://github.com/user-attachments/assets/e654c0a9-fd62-47dd-952f-c2535a052f48)
![image](https://github.com/user-attachments/assets/96a1fe6c-be15-403d-a59a-8c13ad58a5f5)

**抓包文件**
  
[wvp.zip](https://github.com/user-attachments/files/17161639/wvp.zip)

**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by MouseSun846** [comment]
请问你解决了吗？

**Comment by beesboy** [comment]
> 请问你解决了吗？

我这边另外部署环境从新编译之后没有问题，应该还是配置哪里有问题，具体没搞清楚

**Comment by MouseSun846** [comment]
![image](https://github.com/user-attachments/assets/af911d7f-227e-4f95-9867-4842cf0debf5)
整个模板下载你能下载吗？我部署完成无法下载

**Comment by beesboy** [comment]
> ![image](https://private-user-images.githubusercontent.com/46400044/375932409-af911d7f-227e-4f95-9867-4842cf0debf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTU3ODMsIm5iZiI6MTcyODcxNTQ4MywicGF0aCI6Ii80NjQwMDA0NC8zNzU5MzI0MDktYWY5MTFkN2YtMjI3ZS00Zjk1LTk4NjctNDg0MmNmMGRlYmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2NDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYWFhMDRlNmVmMTg3Yzg0ZjFhYmQyZGMwYjVlMGI4MDFkYWI3NGNkNWUzNzc4YjQxMWEwNjEyMjZjNjAyOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._8bHLHgZ8aNH_uubjRWSLUTlUmPcjuAUK9SKLupC3Dg) 整个模板下载你能下载吗？我部署完成无法下载

可以下载，检查下你的WEB目录是不是完全，模板好像是在web目录下的

**Comment by MouseSun846** [comment]
好的谢谢！

**Comment by tangtangll** [comment]
yml 配置文件里面的 media.id要和 zml配置文件中 gerenal.mediaServerId 一致 否则回点播失败
  
![image](https://github.com/user-attachments/assets/af4f0eae-abe4-4d17-8bea-bebdf32851e5)
![image](https://github.com/user-attachments/assets/c3677d8c-d48d-4826-88ff-7850bc03662e)
