### ISSUE TITLE
[技术咨询] https时. 获取默认播放地址失败

### ISSUE THREAD

**Issue by Rhys2020** [648540858/wvp-GB28181-pro#1639]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境  ubuntu 22.04
 - 3. 端口以开放
 - 4. 公网部署
 - 5. 使用https

**内容描述:**
使用http协议时，设备通道下的Jessibuca播放时可以正常播放，转换成https协议后Jessibuca播放器下的播放地址为空
**截图**  
![微信图片_20240929152530](https://github.com/user-attachments/assets/23a28ac9-8f1a-45d9-b1cb-cae8cadbb3d4)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by Rhys2020** [comment]
配置文件如下：
![10bbc2934599d92ee9fe100457a176b](https://github.com/user-attachments/assets/42a40711-a12f-486d-b1f0-61e9da7ef1a3)
![b1aa4068fedd55d5844321ae7c2a2aa](https://github.com/user-attachments/assets/59e3a61f-a4f2-4946-8bcd-ff77dbd84b3a)
![30bbc7f81f9143bb3e6fb6d45bc1354](https://github.com/user-attachments/assets/f1339ca4-00f4-439e-b90c-b2fef5bdcc1b)

**Comment by 648540858** [comment]
更新最新代码测试,
