### ISSUE TITLE
role表sql脚本有TAB造成问题。

### ISSUE THREAD

**Issue by penghd** [648540858/wvp-GB28181-pro#164]
脚本看起来是这样：
create table role (
        id          int auto_increment
              primary key,
        name	TEXT NOT NULL,
        authority	TEXT NOT NULL,
        createTime varchar(50)  not null,
        updateTime varchar(50)  not null
);
mysql运行报错：
 create table role (
    ->         id          int auto_increment
    ->               primary key,
    ->         nameTEXT NOT NULL,
    ->         authorityTEXT NOT NULL,
    ->         createTime varchar(50)  not null,
    ->         updateTime varchar(50)  not null
    -> );
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOT NULL,
        authorityTEXT NOT NULL,
        createTime varchar(50)  not nu' at line 4

name和authority后面用了TAB，mysql解析错误，其他表都是空格，更改为空格后成功。

**Comment by 648540858** [comment]
已修复
