### ISSUE TITLE
是否可以完善28181协议里面图像抓拍功能

### ISSUE THREAD

**Issue by 1579890249** [648540858/wvp-GB28181-pro#1640]
**项目的详细需求**
需要对某一些摄像头进行定时的抓拍，然后对抓拍的图片进行分析。
**这样的实现什么作用**
1、完善28181协议功能
2、对图片重点分析案件或告警，不用业务系统重复开发相同的抽帧逻辑。

**Comment by 648540858** [comment]
28181-2016没有图像抓拍功能,28181-2022支持图像抓拍.,开源主线wvp只能使用ffmpeg自己拉流截图
