### ISSUE TITLE
BUG MobilePosition的更新问题

### ISSUE THREAD

**Issue by kairlec** [648540858/wvp-GB28181-pro#1643]
在此处要求DeviceId与ChannelId不一致时才会去获取channel的Id并设置到MobilePostion里
https://github.com/648540858/wvp-GB28181-pro/blob/a59854e244afd68ea7522307c8de0adc90b9b5cb/src/main/java/com/genersoft/iot/vmp/gb28181/transmit/event/request/impl/NotifyRequestForMobilePositionProcessor.java#L105-L112
而在此处要求获取channelId
https://github.com/648540858/wvp-GB28181-pro/blob/a59854e244afd68ea7522307c8de0adc90b9b5cb/src/main/java/com/genersoft/iot/vmp/service/impl/MobilePositionServiceImpl.java#L117
会导致
```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.genersoft.iot.vmp.gb28181.bean.MobilePosition.getChannelId()" is null
```

**Comment by 648540858** [comment]
已修复
