### ISSUE TITLE
[新功能] 支持为不同的拉流代理设置不同的录制时长

### ISSUE THREAD

**Issue by tiktiktatasmallrainshoes** [648540858/wvp-GB28181-pro#1646]
**内容描述:**

在使用 ZLMediaKit 时，可以通过接口 /index/api/addStreamProxy 添加拉流代理，并可以传入参数 mp4_max_second 来控制每个拉流代理的 MP4 文件切片时长。
然而，在使用 WVP时，似乎在添加拉流代理的过程中没有类似的选项。
翻阅相关问题时，提到可以在 ZLMediaKit 的配置文件中设置 mp4_max_second，但这是一个全局配置，无法满足针对每个拉流代理进行个性化配置的需求。
我想确认：
- WVP 是否支持为每个拉流代理单独设置录制时长？
- 如果目前不支持，是否有计划在未来版本中添加这个功能？或者是否有其他建议的解决方案？

**截图**  
WVP添加拉流代理的时候无法设置mp4_max_second
![image](https://github.com/user-attachments/assets/b4ab5d8f-ae0b-47f9-83d4-2de87526325a)

**Comment by 648540858** [comment]
目前不支持, 感觉意义不大
