### ISSUE TITLE
BUG postgresql 数据库报错

### ISSUE THREAD

**Issue by gopower** [648540858/wvp-GB28181-pro#1649]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 代码更新时间： 2024-10-16

**描述错误**
postgresql 数据库报错

![image](https://github.com/user-attachments/assets/a79354e9-f696-4135-bef4-016c2740414d)

**Comment by 648540858** [comment]
数据库是使用 `数据库/2.7.3/初始化-postgresql-kingbase-2.7.3.sql` 重新创建的数据库吗

**Comment by gopower** [comment]
是的

**Comment by 648540858** [comment]
你的postgresql什么版本,似乎不支持bool类型

**Comment by gopower** [comment]
> 你的postgresql什么版本,似乎不支持bool类型

postgres:14.12

**Comment by 648540858** [comment]
我这边测试了 没有问题你那边不是默认配置吗

**Comment by SunXuan90** [comment]
我也碰到一样的问题，postgres 15。这个问题好像还挺常见的，mysql可以进行int和bool的隐式转换，不知道从哪个版本开始postgres不允许了。https://stackoverflow.com/questions/66085915/on-data-migration-getting-error-operator-does-not-exist-boolean-integer-hin

**Comment by SunXuan90** [comment]
> 我这边测试了 没有问题你那边不是默认配置吗

测试了一下，把数据库初始化sql中[324行](https://github.com/648540858/wvp-GB28181-pro/blob/7e9af0bee8bb32c4ee203ad6291c40d2a75637c6/%E6%95%B0%E6%8D%AE%E5%BA%93/2.7.3/%E5%88%9D%E5%A7%8B%E5%8C%96-postgresql-kingbase-2.7.3.sql#L324)
`    pulling                    bool default false,`
改为
`    pulling                    integer default 0,`
后不再报错

**Comment by gopower** [comment]
@648540858
