### ISSUE TITLE
外网部署 海康ipc注册不上

### ISSUE THREAD

**Issue by shellhuang1227** [648540858/wvp-GB28181-pro#165]
外网部署 海康ipc注册不上 使用的tcp协议 在wvp前端页面看不到设备 配置应该没问题 抓包情况如下
<img width="1114" alt="wvp tcp抓包" src="https://user-images.githubusercontent.com/38980453/134281078-299f4299-fac8-425e-9454-14d3121d7458.png">

**Comment by microsofter** [comment]
我这边跟海康平台对接是正常的呢。
我是上级，把ip端口号给海康配置一下就行；如果你是下级，需要将海康的ip和端口号添加到你的wvp中，别整反了。

**Comment by 648540858** [comment]
你的抓报没看到sip包， 过滤条件写，sip 看一下

**Comment by shellhuang1227** [comment]
我应该也是上级 海康摄像头是下级 在海康摄像头页面配置了服务的地址和端口 内网下可以 但是外网不行

**Comment by shellhuang1227** [comment]
这就是所有的抓包结果了 只抓到这些 没有sip包

**Comment by 648540858** [comment]
打开抓包在开启关闭下海康摄像头就可以抓包了，确定你公网的端口开放了，入站规则和防火墙

**Comment by penghd** [comment]
这两个都要用公网地址。 
       # [可选] 返回流地址时的ip，置空使用 media.ip
    stream-ip:
    # [可选] wvp在国标信令中使用的ip，此ip为摄像机可以访问到的ip， 置空使用 media.ip
    sdp-ip:

**Comment by 648540858** [comment]
时间过久关闭

**Comment by ZhuiMeiZhe** [comment]
内网下级海康球机注册不上是什么原因呢
![image](https://user-images.githubusercontent.com/31027150/236754065-d71338a0-e1f1-46cd-ad83-03100e363cb2.png)

**Comment by microsofter** [comment]
已经收到您的来信，我会尽快回复。
