### ISSUE TITLE
技术咨询,由于项目中使用dom4j依赖，目前存在安全问题。想问有没有什么推荐的替换方案啊？

### ISSUE THREAD

**Issue by lishuai9584** [648540858/wvp-GB28181-pro#1659]

**Comment by 648540858** [comment]
具体什么问题呢，漏洞吗，你可以尝试升级版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月24日(周四) 下午2:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [648540858/wvp-GB28181-pro] 技术咨询,由于项目中使用dom4j依赖，目前存在安全问题。想问有没有什么推荐的替换方案啊？ (Issue #1659)

**Comment by lishuai9584** [comment]
> 具体什么问题呢，漏洞吗，你可以尝试升级版本
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年10月24日(周四) 下午2:52 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [648540858/wvp-GB28181-pro] 技术咨询,由于项目中使用dom4j依赖，目前存在安全问题。想问有没有什么推荐的替换方案啊？ (Issue #1659) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
![image](https://github.com/user-attachments/assets/349b7c5d-1fd4-4f83-b171-4b91c991f745)

是的，漏洞。   目前已经是最新版本，但是dom4j已经不进行更新维护。
