### ISSUE TITLE
MediaConfig问题

### ISSUE THREAD

**Issue by longegit** [648540858/wvp-GB28181-pro#166]
函数getMediaSerItem中
mediaServerItem.setSdpIp(getSdpIp());
mediaServerItem.setStreamIp(getStreamIp());

**Comment by 648540858** [comment]
有什么问题，请详细描述下

**Comment by longegit** [comment]
> 有什么问题，请详细描述下
现在代码里是这么写的
        mediaServerItem.setSdpIp(sdpIp);
        mediaServerItem.setStreamIp(streamIp);

如果不用get函数，配置文件里SdpIp和streamIp都不写的情况下，没有使用默认的ip地址，造成推流的时候，没有把ip地址发送给摄像头，推流失败

**Comment by 648540858** [comment]
已修复
