### ISSUE TITLE
docker部署wvp和zlm，zlm配置种的secret自动随机生成，导致wvp服务报错创建RTP Server 失败 Incorrect secret

### ISSUE THREAD

**Issue by wangbaiqi355920251** [648540858/wvp-GB28181-pro#1660]
**环境信息:**

 - 1. 部署方式 
 - 根据dockerFile文件进行编译镜像部署，wvp和ZLM在同一镜像
 - 2. 部署环境
 - ubuntu
 - 3. 端口开放情况
 - 开放了所有端口
 - 4. 是否是公网部署 
 - 阿里云部署
 - 5. 是否使用https
 - 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - docker 启动时将zlm配置映射到宿主主机
 - 8. 代码更新时间（旧版本请更新最新版本代码测试）
 - 使用最新版本代码

**内容描述:**
使用如下命令启动docker
`docker run  --env WVP_IP="39.108.177.79" --env WVP_ID="34020000002000000001" --env WVP_DOMAIN="3402000000" --env WVP_PWD="easycvr123"  -itd -p 18080:18080 -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp -p 80:80 -p 15060:5060 -p 15060:5060/udp  -v /root/wvp-pro/application.yml:/opt/wvp/config/application.yml wvp-cos:latest sh run.sh`

ZLM报错
<img width="812" alt="微信图片_20241024165253" src="https://github.com/user-attachments/assets/32e7d394-69ac-4a11-9a51-5ab42f6d443c">

进入容器查看zlm配置文件如下
[config.txt](https://github.com/user-attachments/files/17504362/config.txt)

在宿主主机创建配置config.ini进行映射，配置文件如下
[config.txt](https://github.com/user-attachments/files/17504397/config.txt)
启动命令如下：
`docker run  --env WVP_IP="39.108.177.79" --env WVP_ID="34020000002000000001" --env WVP_DOMAIN="3402000000" --env WVP_PWD="easycvr123"  -itd -p 18080:18080 -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp -p 80:80 -p 15060:5060 -p 15060:5060/udp  -v /root/wvp-pro/application.yml:/opt/wvp/config/application.yml  -v /root/zlmediakit/config.ini:/opt/media/config.ini wvp-cos:latest sh run.sh`
登录平台对进行点播，报错如下
<img width="950" alt="微信图片_20241024171236" src="https://github.com/user-attachments/assets/8a3d3ae0-f019-43d2-ba35-01aacbf49f50">
再次进入容器/opt/media查看config.ini配置文件，api配置项的secret发生了改变
<img width="335" alt="微信图片_20241024171600" src="https://github.com/user-attachments/assets/241908b0-a763-4feb-a1b2-45c58e2ced3e">

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by wangbaiqi355920251** [comment]
我去看了zlm的Issues，大家也碰到了类似的问题，我的解决方法了修改源码，将每次启动更新secret的代码注释掉

**Comment by LeiYangGH** [comment]
`-v host的config.ini:/opt/media/conf/config.ini`
