### ISSUE TITLE
技术咨询：新的版本目前缺少大部分API接口，比如国标设备点播，请问后面会补上2.7.2版本中的所有API接口吗？

### ISSUE THREAD

**Issue by abc67ok** [648540858/wvp-GB28181-pro#1661]
新的版本目前缺少大部分API接口，比如国标设备点播，请问后面会补上2.7.2版本中的所有API接口吗？

**Comment by 648540858** [comment]
重构后接口不会回退兼容，需要旧版本接口请使用旧版本。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月25日(周五) 中午11:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [648540858/wvp-GB28181-pro] 技术咨询：新的版本目前缺少大部分API接口，比如国标设备点播，请问后面会补上2.7.2版本中的所有API接口吗？ (Issue #1661)




 
新的版本目前缺少大部分API接口，比如国标设备点播，请问后面会补上2.7.2版本中的所有API接口吗？
