### ISSUE TITLE
BUG java.lang.NumberFormatException: empty String

### ISSUE THREAD

**Issue by xap1992** [648540858/wvp-GB28181-pro#1663]
在注册解析xml文件时，可能存在一些问题。
例如
<?xml version="1.0"?>
<Response>
<CmdType>Catalog</CmdType>
<SN>995524</SN>
<DeviceID>34020000001320000003</DeviceID>
<SumNum>1</SumNum>
<DeviceList Num="1">
<Item>
<DeviceID>34020000001320000003</DeviceID>
<Name>IPC</Name>
<Manufacturer>ABCD</Manufacturer>
<Model>TEST001</Model>
<Owner>Owner1</Owner>
<CivilCode>CivilCode1</CivilCode>
<Block>Block1</Block>
<Address>Address1</Address>
<Parental>0</Parental>
<ParentID>34020000001320000003</ParentID>
<SafetyWay>0</SafetyWay>
<RegisterWay>1</RegisterWay>
<CertNum>CertNum1</CertNum>
<Certifiable>0</Certifiable>
<ErrCode>400</ErrCode>
<EndTime>2050-12-31T23:59:59</EndTime>
<Secrecy>0</Secrecy>
<IPAddress>192.168.0.109</IPAddress>
<Port>5063</Port>
<Password>Password1</Password>
<Status>OK</Status>
<Longitude></Longitude>
<Latitude></Latitude>
</Item>
</DeviceList>
</Response>

Longitude和Latitude值为空，导致 java.lang.NumberFormatException: empty String错误
以下是我的解决方案
在com.genersoft.iot.vmp.gb28181.utils.XmlUtil.simpleTypeDeal中，Double.valueOf加入try，也可以加入判断
        if (tClass.equals(Double.class)) {
            try {
                return Double.valueOf(val.toString());
            } catch (Exception e) {
                // 捕获任何异常并返回0.0
                return 0.0;
          }
        }

**Comment by xap1992** [comment]
抱歉，不知道为什么提交的xml，标签全没了

**Comment by 648540858** [comment]
什么时候更新的代码，重新更新测试ixia。最近提交很频繁
