### ISSUE TITLE
wvp是否支持集群

### ISSUE THREAD

**Issue by iwanlebron** [648540858/wvp-GB28181-pro#1664]
**项目的详细需求**
wvp是否支持集群
**这样的实现什么作用**
有几千个下级节点，单台服务器支撑不住

**Comment by 648540858** [comment]
目前没有 你可以试试新版本，目前性能已经提升很多了

**Comment by iwanlebron** [comment]
有计划支持吗

**Comment by 648540858** [comment]
有，但是不能在国标2016上做因为国标是2016不支持，会在国标2022的代码上实现。



---原始邮件---
发件人: "Iwan ***@***.***&gt;
发送时间: 2024年10月28日(周一) 上午9:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] wvp是否支持集群 (Issue #1664)




 
有计划支持吗

**Comment by iwanlebron** [comment]
2022的代码在星球可以领取吗

**Comment by 648540858** [comment]
付费提供的



---原始邮件---
发件人: "Iwan ***@***.***&gt;
发送时间: 2024年10月28日(周一) 上午9:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] wvp是否支持集群 (Issue #1664)




 
2022的代码在星球可以领取吗

**Comment by XiaoQiTong** [comment]
作者您好，现在wvp是支持2016信令集群了吗，我看主页readme中有写
