### ISSUE TITLE
一个下级平台对应多个上级平台的播放错误

### ISSUE THREAD

**Issue by zhouchenxing** [648540858/wvp-GB28181-pro#1666]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) 
 - 2. 部署环境  ubuntu
 - 3. 端口开放情况 30000-30500
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
一个下级平台，接入了2个级联的上级平台，2个上级平台有各自的流媒体zlm。我看到的现象是如果一个上级平台正在播放视频，此时另一个上级平台也在此时观看的话，那么第一个上级平台就停止播放了，再点播放就报端口分配异常了。这两个上级平台因为对应2个各自的流媒体，所以只能有一个播放吗。还是说可以支持多个不同的上级同时播放，我遇到的是个bug呢。

**截图**  
![image](https://github.com/user-attachments/assets/59663aef-bec6-48ad-aff4-82291a758fdd)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
代码什么时候的更新的.

**Comment by zhouchenxing** [comment]
> 代码什么时候的更新的.

最新一次更新是8月末的代码

**Comment by zhouchenxing** [comment]
> 更新master分支代码，最近变化很大

好的，更新了，多个上级平台可以同时对同一个下级平台的摄像头进行播放了。感谢。
