### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by XyhBill** [648540858/wvp-GB28181-pro#1667]
**环境信息:**

 - 1. wvp-prp + zlm都是编译部署/
 - 2. 腾讯云 centos 7.6
 - 3. 端口开放情况
 - 4. 是公网部署 
 - 5. 不使用https
 - 6. 接入海康nvr设备
 - 7. 你做过哪些尝试
 - 8. 代码更新时间20241023 版本是wvp版本是2.7.3 git版本号是222c9ea
 - 9. 网线直连

**描述错误**
描述下您遇到的问题
设备画面已经可以在国标设备页面点击通道播放画面，但是在分屏监控下显示无信号
**如何复现**
不是偶发问题直接点击即可复现

**截图**  
![image](https://github.com/user-attachments/assets/6f0fb0bc-a71a-4e8e-95e5-8e49042886a9)
![image](https://github.com/user-attachments/assets/49c9805a-ed0a-4703-b90d-cd653818d4e5)

**Comment by 648540858** [comment]
你在这个页面压根没有发起点播,通道管理分配下行政区划
