### ISSUE TITLE
前端页面点击在线文档跳转到控制台

### ISSUE THREAD

**Issue by XyhBill** [648540858/wvp-GB28181-pro#1668]
**环境信息:**

 - 1. wvp-pro + zlm都是编译部署
 - 2. 腾讯云centos 7.6
 - 3. 端口开放情况 相关端口都已开放
 - 4. 公网部署 
 - 5. 不使用https
 - 6. 接入海康nvr设备
 - 7. 你做过哪些尝试
      点击跳转 直接修改url
 - 8. 代码更新时间
 - 20241024 wvp版本2.7.3 git版号 222c9ea
 - 9. 设备通过网线直连

**描述错误**
描述下您遇到的问题
   点击在线文档无反应，主要想看swagger api
**如何复现**
直接点击在线文档还是跳转到console页面，修改url地址也是一样

**Comment by 648540858** [comment]
测试没有问题,记得编译后再访问, npm run start下是无法访问的

**Comment by Oushinan** [comment]
@XyhBill 解决了吗？我也遇到相同的问题
