### ISSUE TITLE
BUG 新版本接口文档不全

### ISSUE THREAD

**Issue by Yonn0818** [648540858/wvp-GB28181-pro#1673]
**环境信息:**

 - 1. 部署方式 都是编译部署
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 正常开放
 - 4. 是否是公网部署 是
 - 5. 是否使用https 是
 - 6. 接入设备/平台品牌 TP-LINK
 - 7. 你做过哪些尝试 重新部署，开启配置文件中doc-enable: true

**描述错误**
接口文档显示不全，gb28181查询设备，控制云台等等 这些接口不在了
之前老版本是有这些接口文档的

**截图**  
![EcoPaste_SnpZL5VKl-7qUoCP58GoD](https://github.com/user-attachments/assets/7e690d24-5c2f-4f27-97bc-6f3eb156e329)

**Comment by 648540858** [comment]
已修复
