### ISSUE TITLE
BUG 升级到2024年11月1日更新的代码后，使用拉流代理的视频录制，录制第一个视频文件成功后，随后的每个文件切片长度默认为2秒

### ISSUE THREAD

**Issue by Yonn0818** [648540858/wvp-GB28181-pro#1676]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 Y
 - 4. 是否是公网部署  Y
 - 5. 是否使用https Y
 - 6. 接入设备/平台品牌 TPLINK
 - 7. 你做过哪些尝试 回退老版本
 - 8. 代码更新时间 2024年11月4日
 - 9. 是否是4G设备接入 Y

**描述错误**
升级到2024年11月1日更新的代码后
1.使用拉流代理的视频录制，录制第一个视频文件成功后，随后的每个文件切片长度默认为2秒
2.新版本录制的MP4视频打开非常慢，15分钟100MB的视频打开大约要15-20秒，老版本录制的视频基本上是秒开

**如何复现**
使用RTSP添加拉流代理，切片文件设置为900秒，启动代理后录制完成第一个文件后，后续每个视频文件会默认为2秒一个

**Comment by Yonn0818** [comment]
为方便测试，可以将视频切片时间修改为30秒或者1分钟，只要第一个视频完成录制后，之后的每个视频都会自动默认为2秒

**Comment by BuiltProcess** [comment]
推流也有这个问题
![微信截图_20241121162346](https://github.com/user-attachments/assets/824d4c09-f0e1-464c-9128-a59863581db7)
