### ISSUE TITLE
BUG 语音对讲功能port拆箱错误

### ISSUE THREAD

**Issue by kairlec** [648540858/wvp-GB28181-pro#1678]
这里传入`String ip`和`Integer port`都是null
https://github.com/648540858/wvp-GB28181-pro/blob/6dc0c3ebd79b96f3caaa9436f2cd001992f9261b/src/main/java/com/genersoft/iot/vmp/gb28181/service/impl/PlayServiceImpl.java#L485-L486

这里在构造SendRtpInfo时要求`String ip`和`int port`
https://github.com/648540858/wvp-GB28181-pro/blob/6dc0c3ebd79b96f3caaa9436f2cd001992f9261b/src/main/java/com/genersoft/iot/vmp/service/impl/SendRtpServerServiceImpl.java#L52-L53

https://github.com/648540858/wvp-GB28181-pro/blob/6dc0c3ebd79b96f3caaa9436f2cd001992f9261b/src/main/java/com/genersoft/iot/vmp/gb28181/bean/SendRtpInfo.java#L178-L180
会造成
```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "port" is null
```

**Comment by 648540858** [comment]
这里的talk模式时适用的tcp被动模式,设备连接时再给设备发流,所以一开始是没有ip 端口的, 你的空指针具体哪里出来的

**Comment by kairlec** [comment]
> 这里的talk模式时适用的tcp被动模式,设备连接时再给设备发流,所以一开始是没有ip 端口的, 你的空指针具体哪里出来的

talk里在调用createSendRtpInfo时传入的port: `(Integer) null`,createSendRtpInfo在调用SendRtpInfo.getInstance时是`(int) null`,SendRtpInfo类的字段定义和相关方法要求port都是int, (Integer) null到(int) null就出现这个了

**Comment by 648540858** [comment]
已修复
