### ISSUE TITLE
技术咨询 是否支持国标级联，视频通讯模式为：TCP

### ISSUE THREAD

**Issue by AbelSu001** [648540858/wvp-GB28181-pro#1679]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 -     编译wvp-pro，
 - 2. 部署环境 windows / ubuntu/ centos ...
 -      ubuntu 22.02
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间（旧版本请更新最新版本代码测试）

**内容描述:**

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
![image](https://github.com/user-attachments/assets/9821cde4-8cb7-4991-beb4-9bb8bd676595)
