### ISSUE TITLE
2.0版本国标点播报错：status：400,message:Bad Request

### ISSUE THREAD

**Issue by RlonLL11FE** [648540858/wvp-GB28181-pro#168]
master分支点播正常，切换到2.0分支，按照说明修改配置后，设备正常连接服务，状态为在线，点播报错
![image](https://user-images.githubusercontent.com/12453254/134317097-13e81e36-554c-4aaf-915c-2fa78c27b342.png)
![image](https://user-images.githubusercontent.com/12453254/134317564-20d8c8e6-f28f-41cd-90f8-dc6b0b1ac539.png)

**Comment by microsofter** [comment]
我是播放超时，让下级海康平台的研发帮忙抓包看了wvp发过去的数据，缺少收流地址导致点播失败。

另外，你的图片怎么上传的啊？

**Comment by RlonLL11FE** [comment]
复制图片，直接在文本框里Ctril+V就行了。我看ZML的日志，打开了收流端口，但是没有收到推流，你的问题解决了吗？
![image](https://user-images.githubusercontent.com/12453254/134601149-2cf37b28-a58a-4bae-8a14-89edebf67002.png)

**Comment by 648540858** [comment]
> 我是播放超时，让下级海康平台的研发帮忙抓包看了wvp发过去的数据，缺少收流地址导致点播失败。
> 
> 另外，你的图片怎么上传的啊？

sdp里没有你的ip信息，多半是你配置问题

**Comment by 648540858** [comment]
> 复制图片，直接在文本框里Ctril+V就行了。我看ZML的日志，打开了收流端口，但是没有收到推流，你的问题解决了吗？
> ![image](https://user-images.githubusercontent.com/12453254/134601149-2cf37b28-a58a-4bae-8a14-89edebf67002.png)
看下sdp消息，回复的收流ip有没有问题

**Comment by RlonLL11FE** [comment]
点击点播Sip的日志是这样的
![image](https://user-images.githubusercontent.com/12453254/134795347-57261cc9-dc12-4bdb-8445-66363586a654.png)
这是我SIP的配置，IP地址我也改成我的了啊，老版的我也是一样配的点播没问题，这个版本不行。。。
![image](https://user-images.githubusercontent.com/12453254/134795489-06ebf42b-86f6-4d8b-8e34-4feb0e40b12b.png)

**Comment by 648540858** [comment]
修复了一个会导致我们点播400的问题， 你试试

**Comment by 648540858** [comment]
看下你的数据库media_server表

**Comment by RlonLL11FE** [comment]
问题解决了，拉了最新的代码解决了，给大佬点赞
