### ISSUE TITLE
BUG 7*24小时录像中断

### ISSUE THREAD

**Issue by gouwuwo** [648540858/wvp-GB28181-pro#1688]
**环境信息:**

 - 1. 部署方式编译 wvp-pro/ zlm(docker)
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况（需要开放的端口都进行了开放）
 - 4. 是否是公网部署 （否）
 - 5. 是否使用https（否）
 - 6. 接入设备/平台品牌（大华网络摄像头）
 - 7. 你做过哪些尝试（看日志）
 - 8. 代码更新时间（11.5）
 - 9. 是否是4G设备接入（否）

**描述错误**
描述下您遇到的问题
国标接入，然后使用生成的RTSP地址，添加拉流代理并录像，开启7*24小时录像配置，目前发现录像1-2天后，就停止录像了。需要登录平台，进度通道后，点击播放按钮后，才能恢复代理正常拉流和录像。

**如何复现**
有明确复现步骤的问题会很容易被解决
必现，每连续录像1-2天后，即停止录像。

**截图**  
开始录像时间：
![image](https://github.com/user-attachments/assets/e40c806d-2f3a-4ddc-88e2-7816ea71eda4)
停止录像时间：
![image](https://github.com/user-attachments/assets/a983a2dd-3d47-4356-a480-9d8c83a12ede)
配置参数
![image](https://github.com/user-attachments/assets/afc02da9-11e5-42c5-9cd3-e531c78b1376)
![image](https://github.com/user-attachments/assets/5173d1a3-a162-4376-ac73-32163e1a84c5)

**抓包文件**
  
**日志**
![image](https://github.com/user-attachments/assets/901b4ad0-f530-460c-af43-32e7a8f6d4cb)
![image](https://github.com/user-attachments/assets/8a4d8fb6-688e-40bc-8ed6-4016a7a582b6)
![image](https://github.com/user-attachments/assets/e1232c0d-7e5f-479b-8c6f-4cd41bcdbcb9)

zlm日志：
![image](https://github.com/user-attachments/assets/ca85d0a8-afcb-42f9-a362-97da5cdf9db7)
![image](https://github.com/user-attachments/assets/fcd2ee14-3409-4dc4-8a4f-405e651ebfe1)
![image](https://github.com/user-attachments/assets/58ea8a5d-0a4f-440c-a82e-878fe25c200c)
![image](https://github.com/user-attachments/assets/e8f402c3-2e05-4946-a1b2-c21b1dceb136)

```
日志内容放这里， 文件的话请直接上传
```
[wvp-2024-11-09.0.log](https://github.com/user-attachments/files/17694722/wvp-2024-11-09.0.log)

zlm日志：
[2024-11-09_00.log](https://github.com/user-attachments/files/17694853/2024-11-09_00.log)

**Comment by chenpingan5** [comment]
最后怎么解决的呢？

**Comment by chenpingan5** [comment]
我也出现这个问题了

**Comment by gouwuwo** [comment]
目前还未找到解决方案

**Comment by 648540858** [comment]
dev/录制计划 分支已完成24小时录像支持, 可以测试了. 后续会合并的master分支. 测试如果有问题欢迎开新的提问. 打包已经上传的知识星球.
