### ISSUE TITLE
录像功能，录像完成提示环境错误，如何解决

### ISSUE THREAD

**Issue by pwnyxz** [648540858/wvp-GB28181-pro#169]
录像完成提示环境错误，如何解决，This binary '/usr/local/bin/ffprobe' is not a supported version of ffprobe
麻烦问一下，应该使用ffprobe哪个版本

ervlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: This binary '/usr/local/bin/ffprobe' is not a supported version of ffprobe] with root cause

java.lang.IllegalArgumentException: This binary '/usr/local/bin/ffprobe' is not a supported version of ffprobe

ffprobe -version
FFprobe version SVN-r26402, Copyright (c) 2007-2011 the FFmpeg developers
built on Apr 8 2021 13:49:38 with gcc 4.8.5 20150623 (Red Hat 4.8.5-39)
configuration: --disable-yasm
libavutil 50.36. 0 / 50.36. 0
libavcore 0.16. 1 / 0.16. 1
libavcodec 52.108. 0 / 52.108. 0
libavformat 52.93. 0 / 52.93. 0
libavdevice 52. 2. 3 / 52. 2. 3
libavfilter 1.74. 0 / 1.74. 0
libswscale 0.12. 0 / 0.12. 0
FFprobe SVN-r26402
libavutil 50.36. 0 / 50.36. 0
libavcore 0.16. 1 / 0.16. 1
libavcodec 52.108. 0 / 52.108. 0
libavformat 52.93. 0 / 52.93. 0
libavdevice 52. 2. 3 / 52. 2. 3
libavfilter 1.74. 0 / 1.74. 0
libswscale 0.12. 0 / 0.12. 0

**Comment by 648540858** [comment]
版本不限制你把路径配置对就可以
