### ISSUE TITLE
技术咨询关于收到响应时401的处理时机

### ISSUE THREAD

**Issue by a24211317** [648540858/wvp-GB28181-pro#1696]
我在SIPProcessorObserver发现processResponse中的一段代码对于401的响应没有做出处理，请问是在哪个地方对401回复处理的。现在遇到了信令回复的401Unauthorized 但是在keepalive的定时中发现响应的是200ok导致上级离线了也没有重新注册
 // Success
        if (((status >= Response.OK) && (status < Response.MULTIPLE_CHOICES)) || status == Response.UNAUTHORIZED) {
            if (status != Response.UNAUTHORIZED && responseEvent.getResponse() != null && !sipSubscribe.isEmpty() ) {
                CallIdHeader callIdHeader = response.getCallIdHeader();
                if (callIdHeader != null) {
                    SipEvent sipEvent = sipSubscribe.getSubscribe(callIdHeader.getCallId());
                    if (sipEvent != null) {
                        if (sipEvent.getOkEvent() != null) {
                            SipSubscribe.EventResult<ResponseEvent> eventResult = new SipSubscribe.EventResult<>(responseEvent);
                            sipEvent.getOkEvent().response(eventResult);
                        }
                        sipSubscribe.removeSubscribe(callIdHeader.getCallId());
                    }
                }
            }
            ISIPResponseProcessor sipRequestProcessor = responseProcessorMap.get(response.getCSeqHeader().getMethod());
            if (sipRequestProcessor != null) {
                sipRequestProcessor.process(responseEvent);
            }

**Comment by 648540858** [comment]
不符合提问规范,未提供相关信息
