### ISSUE TITLE
国标级联问题，wvp作为上级平台，wvp向下级级联不可以

### ISSUE THREAD

**Issue by xueguangyang** [648540858/wvp-GB28181-pro#1698]
wvp作为上级平台，wvp向下级级联不可以

**Comment by lunasaw** [comment]
上下文都没有的垃圾问题

**Comment by xueguangyang** [comment]
这需要什么上下文，wvp有没有作为上级的功能，这不就一句话的事吗




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月21日 15:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [648540858/wvp-GB28181-pro] 国标级联问题，wvp作为上级平台，wvp向下级级联不可以 (Issue #1698) |

上下文都没有的垃圾问题

**Comment by xueguangyang** [comment]
但是我用wvp推到别的没问题，但是别的平台推到wvp一直显示上级域不在线，所以不知道什么问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月22日 11:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [648540858/wvp-GB28181-pro] 国标级联问题，wvp作为上级平台，wvp向下级级联不可以 (Issue #1698) |

这需要什么上下文，wvp有没有作为上级的功能，这不就一句话的事吗
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年11月21日 15:23 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [648540858/wvp-GB28181-pro] 国标级联问题，wvp作为上级平台，wvp向下级级联不可以 (Issue #1698) | 上下文都没有的垃圾问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

wvp本身不就是一个上级平台嘛，接收 gb注册，所以没理解你说的向下及联是什么意思

**Comment by lunasaw** [comment]
> 但是我用wvp推到别的没问题，但是别的平台推到wvp一直显示上级域不在线，所以不知道什么问题
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年11月22日 11:37 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [648540858/wvp-GB28181-pro] 国标级联问题，wvp作为上级平台，wvp向下级级联不可以 (Issue #1698) | 这需要什么上下文，wvp有没有作为上级的功能，这不就一句话的事吗 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年11月21日 15:23 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [648540858/wvp-GB28181-pro] 国标级联问题，wvp作为上级平台，wvp向下级级联不可以 (Issue #1698) | 上下文都没有的垃圾问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***> wvp本身不就是一个上级平台嘛，接收 gb注册，所以没理解你说的向下及联是什么意思 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

所以你需要贴上下文才能帮你排查

**Comment by xueguangyang** [comment]
老哥，我没明白您的意思，我给您说我的操作，我现在有两个平台，一个wvp，还有另一个平台，然后现在把wvp作为下级注册到第二个平台没问题，第二个平台也可以观看wvp，但是反之，把第二个平台注册到wvp，第二个平台显示上级域（也就是wvp）不在线，这是我目前的操作



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月22日 15:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [648540858/wvp-GB28181-pro] 国标级联问题，wvp作为上级平台，wvp向下级级联不可以 (Issue #1698) |

但是我用wvp推到别的没问题，但是别的平台推到wvp一直显示上级域不在线，所以不知道什么问题
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年11月22日 11:37 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [648540858/wvp-GB28181-pro] 国标级联问题，wvp作为上级平台，wvp向下级级联不可以 (Issue #1698) | 这需要什么上下文，wvp有没有作为上级的功能，这不就一句话的事吗 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年11月21日 15:23 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [648540858/wvp-GB28181-pro] 国标级联问题，wvp作为上级平台，wvp向下级级联不可以 (Issue #1698) | 上下文都没有的垃圾问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> wvp本身不就是一个上级平台嘛，接收 gb注册，所以没理解你说的向下及联是什么意思 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

所以你需要贴上下文才能帮你排查

**Comment by 648540858** [comment]
不符合提问规范
