### ISSUE TITLE
重启程序后端口与配置文件不符

### ISSUE THREAD

**Issue by zjt003** [648540858/wvp-GB28181-pro#1701]
**环境信息：**
- 1.部署方式 wvp-prp+ zlm都是编译部署
- 2.部署环境 centos.
- 3.端口开放情况 后端:18080 前端:18081
- 4.是否是公网部署 是
- 5.是否使用https 否
- 6.接入设备/平台品牌 GB28181
- 7.你做过哪些尝试 重新运行程序
- 8.代码更新时间
- 9．是否是4G设备接入 是

**内容描述:**
重启程序发现端口从设置的18080变成了8080
**截图**  
![图片](https://github.com/user-attachments/assets/ecef450b-ac10-4e18-a8f4-3d0686c610df)
![图片](https://github.com/user-attachments/assets/0462f736-be50-416d-822a-349a158a2535)

**Comment by zjt003** [comment]
No active profile set, falling back to 1 default profile: "default"
![图片](https://github.com/user-attachments/assets/4d8765a0-5a84-4d63-82b0-85d4817fef92)

**Comment by 648540858** [comment]
大概率配置文件没加载上,检查下配置文件
