### ISSUE TITLE
加两个级联国标系统，第一个可以选择通道，第二个选择通道界面，里面是空的，需要配置哪里

### ISSUE THREAD

**Issue by hantwain** [648540858/wvp-GB28181-pro#1702]
**环境信息:**

 - 1. 部署方式  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows 
 - 3. 端口开放情况  5060
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间（旧版本请更新最新版本代码测试）

版本2.7.3 | 编译时间20241024 | GIT版本8d9e19c
GIT最后提交时间20240911

**内容描述:**
 加两个级联国标系统，第一个可以选择通道，第二个选择通道界面，里面是空的，需要配置哪里

**Comment by 648540858** [comment]
截图看下
