### ISSUE TITLE
关于视频点播时主子码流切换的问题

### ISSUE THREAD

**Issue by chengXuYuan358** [648540858/wvp-GB28181-pro#1704]
**环境信息:**
点播设备是海康威视的硬盘录像机 DS-7808NB-K2

**内容描述:**
点播时发送了子码流的信令，但是没有效果。播放的视频依然是主码流的
**截图**  

**日志**
v=0
o=34020000001110000111 0 0 IN IP4 [192.168.1.113](http://192.168.1.113/)
s=Play
c=IN IP4 [192.168.1.113](http://192.168.1.113/)
t=0 0
m=video 40250 RTP/AVP 96 97 98 99
a=recvonly
a=rtpmap:96 PS/90000
a=rtpmap:98 H264/90000
a=rtpmap:97 MPEG4/90000
a=rtpmap:99 H265/90000
a=stream:1
y=0102007711

```
日志内容放这里， 文件的话请直接上传
```

**Comment by chengXuYuan358** [comment]
v=0
o=34020000001110000111 0 0 IN IP4 [192.168.37.113](http://192.168.37.113/)
s=Play
c=IN IP4 [192.168.37.113](http://192.168.37.113/)
t=0 0
m=video 40284 RTP/AVP 96 97 98 99
a=recvonly
a=rtpmap:96 PS/90000
a=rtpmap:98 H264/90000
a=rtpmap:97 MPEG4/90000
a=rtpmap:99 H265/90000
a=streamnumber:1
y=0102000203
f=v/2/5/25/1/4000a/1/8/1

**Comment by chengXuYuan358** [comment]
v=0
o=34020000001110000111 0 0 IN IP4 [192.168.1.113](http://192.168.1.113/)
s=Play
c=IN IP4 [192.168.37.113](http://192.168.1.113/)
t=0 0
m=video 40284 RTP/AVP 96 97 98 99
a=recvonly
a=rtpmap:96 PS/90000
a=rtpmap:98 H264/90000
a=rtpmap:97 MPEG4/90000
a=rtpmap:99 H265/90000
a=streamnumber:1
y=0102000203
f=v/2/5/25/1/4000a/1/8/1

**Comment by ndwzy** [comment]
海康的国标协议需要2022的，检查固件版本还有配置是否支持

**Comment by 648540858** [comment]
> 海康的国标协议需要2022的，检查固件版本还有配置是否支持

2022目前未开源, 付费提供,支持固件版本查询还有配置. 2022试用包可以在知识星球内下载
