### ISSUE TITLE
国标级联允许同一平台使用不同国标设备编码进行对接

### ISSUE THREAD

**Issue by KnightYu** [648540858/wvp-GB28181-pro#1706]
**项目的详细需求**
国标级联允许同一平台使用不同设备编码进行对接

**这样的实现什么作用**
不同部门对接上来使用的是不同的国标设备编码，希望国标级联上去不改变国标设备编码。

**Comment by 648540858** [comment]
现在也不会改变通道编号,设备编号没办法不改变,下级注册到上级,携带的设备编号代表了下级本身,而不是设备
