### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by zq-crypto** [648540858/wvp-GB28181-pro#1707]
**环境信息:**

 - 1. 部署方式wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos
 - 3. 端口开放情况 全部放开
 - 4. 是否是公网部署  是
 - 5. 是否使用https 是
 - 6. 接入设备/平台品牌 海康
 - 7. 你做过哪些尝试 更新代码
 - 8. 代码更新时间  最新
 - 9. 是否是4G设备接入  否

**描述错误**
nvr使用国标接入后，进行录像，以一分钟一个，那十分钟后就报错：点播失败， 错误码： 486, 399:399:<101>[Component]Session number has reached the upper limit '10'

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
设备支持的并发数不够, 开新的记得把旧的关了

**Comment by ningtu** [comment]
> 设备支持的并发数不够，开新的记得把旧的关了

我们也是录像，当设备流注销的时候，会重新点播，也是报这个错
开新的记得把旧的关了是什么意思呢？
