### ISSUE TITLE
2.0点播出现问题的可以试试

### ISSUE THREAD

**Issue by penghd** [648540858/wvp-GB28181-pro#171]
原因是WVP的数据库记录和前端设备对不上。
需要操作数据库，如果大家是在调试状态，那就直接操作sqlite。
如果是打包成jar，那我也不知道sqlite文件在哪里。：（
我的办法就是在设置文件里改用mysql，mysql创建wvp数据库，用源码sql目录下的脚本，注意最后的role表创建时脚本有tab，要改成空格。
一般来说你新建数据库就好了，前端不注册的话可以等过期，也可以在前端设备取消28181，再启用28181.
如果是在用了mysql之后还出现问题，那就删除数据库里device表和device_channel表对应该设备的条目。
等待前端注册，不注册照前面讲的等过期或重新启用28181.

**Comment by penghd** [comment]
用数据库还可以解决改不了密码的问题，手工生成MD5密码，改user表。

**Comment by 648540858** [comment]
改密码问题修复了，有些前端设备与wvp不对应时，确实容易有问题
