### ISSUE TITLE
增加丢包率显示

### ISSUE THREAD

**Issue by wuyb66** [648540858/wvp-GB28181-pro#1710]
**项目的详细需求**
在视频直播的时候，经常会花屏，可以像LiveGBS显示丢包率。
![image](https://github.com/user-attachments/assets/081f94d0-bc00-43a7-9871-5669d1bc24a3)

**这样的实现什么作用**
有丢包率信息可以直观地反映视频质量，避免经常需要抓包来排查问题。

**Comment by 648540858** [comment]
现在就支持，在编码信息里



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月4日(周三) 下午3:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [648540858/wvp-GB28181-pro] 增加丢包率显示 (Issue #1710)




 
项目的详细需求
 在视频直播的时候，经常会花屏，可以像LiveGBS显示丢包率。
 image.png (view on web)
 
这样的实现什么作用
 有丢包率信息可以直观地反映视频质量，避免经常需要抓包来排查问题。

**Comment by wuyb66** [comment]
是最近加的吗？我这个版本没有丢包率信息
![image](https://github.com/user-attachments/assets/6d295051-99e5-4e16-974f-c4fa75783efd)

**Comment by 648540858** [comment]
master分支更新到最新
