### ISSUE TITLE
接口文档如何登录

### ISSUE THREAD

**Issue by YaoYuanZheng** [648540858/wvp-GB28181-pro#1717]
在调用其他功能之前得登录拿到AccessToken,我用mysql里wvp_user表里的账密试了下不行,网上关于API文档的内容基本没有；应该怎么登录，有大神能回复一下吗，感谢
![微信图片_20241216145350](https://github.com/user-attachments/assets/d40070cd-3a2f-4411-a81d-c97422f3ac42)
![微信图片_20241216145358](https://github.com/user-attachments/assets/3c192d95-0bbd-4f45-9854-eab942d63399)

**Comment by 648540858** [comment]
这里添上你的token
![image](https://github.com/user-attachments/assets/9c3cfe99-08fb-4218-899e-b307112ac412)
