### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by tuying** [648540858/wvp-GB28181-pro#1718]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos
 - 3. 端口开放情况18080
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 接入设备/平台品牌 否
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间 2024-12-17
 - 9. 是否是4G设备接入 否

**描述错误**
配置【拉流代理】，类型【FFmpeg】，模板输出使用-f flv时，输出协议会变成flv协议；

**如何复现**
配置【拉流代理】时，类型【FFmpeg】，模板输出使用-f flv；

**截图**  
![image](https://github.com/user-attachments/assets/4d89787f-02c0-413e-8c11-43947b71308d)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
已修复
