### ISSUE TITLE
【BUG】高并发下，MediaServerItem数据问题

### ISSUE THREAD

**Issue by longegit** [648540858/wvp-GB28181-pro#172]
MediaServerItem每次都是从redis里读取，修改ssrc然后再存到redis，高并发下，会造成ssrc数据不一致的问题，比如说一个线程已经读取成功了但是还没写，另一个线程读取并修改了ssrc并写入成功，第一个线程再写入时，数据还是老的。

**Comment by 648540858** [comment]
有道理，我想想怎么改

**Comment by SitInAndWatchSky** [comment]
我的redis里面怎么只有用户数据？

**Comment by 648540858** [comment]
已修复，可以更新最新代码测一下
