### ISSUE TITLE
云服务带宽问题

### ISSUE THREAD

**Issue by zhj153** [648540858/wvp-GB28181-pro#1720]
**环境信息:**

 - 1. 部署方式wvp-prp + zlm都是编译部署
 - 2. 部署环境 centos 
 - 3. 运行所需要的端口已经全部开放
 - 4. 公网部署，云服务部署
 - 5. 未使用https
 - 6. 接入的是海康的nvr录像机
 - 7. 使用的是最新的master分支的代码

**内容描述:**
我们平台现在接入的录像机比较多摄像头也比较多，摄像头现在一共有60多个，平台是在云服务器上部署的，目前云服务的带宽是10Mb，这个带宽是否合适。就是10Mb的带宽能支持开多少个监控视频正常播放

**截图**  
![image](https://github.com/user-attachments/assets/e2112b43-ebed-4d3d-90c1-8b05459fb576)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by qczrzl** [comment]
这个主要看你摄像头视频通道的配置，分辨率、视频编码啥的，可以参考计算下 [海康的计算器](https://m.hikmall.com/mobileVideoCal/mobileVideoCal/pages/bandwidth)
