### ISSUE TITLE
技术咨询/BUG 使用拉流代理录像默认只能保存7天

### ISSUE THREAD

**Issue by Yonn0818** [648540858/wvp-GB28181-pro#1722]
**环境信息:**

 - 1. 部署方式 wvp-GB28181-pro + zlm + wvp-pro-assist都是编译部署
 - 2. 部署环境 ubuntu22.04
 - 3. 端口开放情况 Y
 - 4. 是否是公网部署 Y
 - 5. 是否使用https Y
 - 6. 方便的话提供下使用的设备品牌或平台 TPLINK球机
 - 7. 你做过哪些尝试 修改配置，重启服务，重启服务器
 - 8. 代码更新时间 版本2.7.2

**内容描述:**
以下是wvp-pro-assist/target/application.yml配置文件中录像保存时长
userSettings:
    # [必选 ] 服务ID
    id: 334533
    # [可选 ] 录像保存时长（单位： 天）每天晚12点自动对过期文件执行清理
    recordDay: 90
    # [可选 ] 录像下载合成临时文件保存时长， 不配置默认取值recordDay（单位： 天）每天晚12>点自动对过期文件执行清理
    recordTempDay: 90
    # [必选 ] ffmpeg路径
    ffmpeg: /usr/bin/ffmpeg
    # [必选 ] ffprobe路径， 一般安装ffmpeg就会自带， 一般跟ffmpeg在同一目录,用于查询文件的
信息
    ffprobe: /usr/bin/ffprobe
    # [可选 ] 限制 ffmpeg 合并文件使用的线程数，间接限制cpu使用率， 默认2 限制到50%
    threads: 4

使用的拉流代理进行录像保存，修改完recordDay: 90后尝试重启了服务，但录像默认还是只保存了7天，7天以前的录像被清空了

**截图**  
<img width="265" alt="image" src="https://github.com/user-attachments/assets/ebe9891d-f079-4c39-aa7c-6c1a1f5d9281" />

**Comment by Yonn0818** [comment]
@648540858 麻烦帮我看看 拜托🙏

**Comment by 648540858** [comment]
media.record-day（录像保存时长） 默认为7 修改就可以了

**Comment by Yonn0818** [comment]
> media.record-day（录像保存时长） 默认为7 修改就可以了

我修改了wvp-GB28181-pro/target/application.yml下面的media.record-day: 90
重启服务后还是没有生效 还是默认7天
