### ISSUE TITLE
技术咨询-gb28181-2022版本的注册不了在wvp上吗

### ISSUE THREAD

**Issue by hzk16811** [648540858/wvp-GB28181-pro#1726]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/ 是的
 - 2. 部署环境 windows / ubuntu/ centos ... centos
 - 3. 端口开放情况 均以开发
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 设备是海康
 - 7. 你做过哪些尝试 使用旧版本的2016版本可以注册上
 - 8. 代码更新时间（旧版本请更新最新版本代码测试）

主要是咨询一下wvp是否支持gb28181-2022协议版本

**Comment by 648540858** [comment]
平台不禁止，主要看设备是否兼容

**Comment by hzk16811** [comment]
现在可以注册上来了，但是我切换流传输模式为tcp被动时，提示了这个报错
![b54c39cc50fb9f8cda3ea542be6aa0f](https://github.com/user-attachments/assets/c6829ab2-de18-4ac4-bca9-b4df4344bf92)

**Comment by hzk16811** [comment]
谢谢作者，问题找到了，由于设备当时没有访问外网的能力，导致注册不上平台，已经解决了
