### ISSUE TITLE
国标级联注册失败，400:Bad Request

### ISSUE THREAD

**Issue by RebelTinker** [648540858/wvp-GB28181-pro#1727]
**环境信息:**

 - 部署方式.wvp-pro docker 部署 wvpjar包部署
 - 安装环境. centos
 - 开放端口 5080 sip端口 5080开放公网nat映射 
 - 没有使用https
 - 接入设备/平台品牌: 海康上级平台
 - 你做过哪些尝试  尝试过手动在SIPRequestHeaderPlarformProvider中设置received为 公网ip setPort(5080);
 - 更新时间 : 最新版本 master分支
 - 是否是4G设备接入:  拉流代理通过国标级联的方式接入上级平台

**描述错误**
在测试环境部署中 正常 ,正式环境中 因为正式环境网络互联网出口存在多个nat的情况 sip请求发送时,向上级平台推送的错误的设备地址导致一直收不到上级平台的请求

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**

**日志**
```
REGISTER sip:50010000002000110001@119.84.246.74:7100 SIP/2.0
Call-ID: 2b08604a19ccf8120a31000f0840547f@192.168.76.9
CSeq: 3 REGISTER
From: <sip:41010500003000000001@4101050000>;tag=76ee8b790290451d83024543533dfbaf
To: <sip:41010500003000000001@4101050000>
Via: SIP/2.0/UDP 192.168.76.9:8116;branch=z9hG4bK9983043447;rport
Max-Forwards: 70
Contact: <sip:41010500003000000001@192.168.76.9:8116>
Expires: 3600
User-Agent: Wvp-Pro v2.7.3.20241219
Content-Length: 0
```

**Comment by 648540858** [comment]
请补充基本信息

**Comment by RebelTinker** [comment]
注册上了 上级平台无法检索下级平台信息

**Comment by RebelTinker** [comment]
[wvp-2024-12-24.0.log](https://github.com/user-attachments/files/18243605/wvp-2024-12-24.0.log)

**Comment by RebelTinker** [comment]
![image](https://github.com/user-attachments/assets/af218f90-1947-43a7-9d36-e274ea7f185c)

**Comment by RebelTinker** [comment]
在nat环境种 sip 发送的 rport和;received不是期望的 ip和端口

**Comment by RebelTinker** [comment]
[wvp.log.txt](https://github.com/user-attachments/files/18243805/wvp.log.txt)

**Comment by RebelTinker** [comment]
[wvp.log.txt](https://github.com/user-attachments/files/18243819/wvp.log.txt)
