### ISSUE TITLE
技术咨询-多个wvp平台不能同时播放同一个实时视频吗

### ISSUE THREAD

**Issue by hzk16811** [648540858/wvp-GB28181-pro#1728]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/ 部署都是docker
 - 2. 部署环境 windows / ubuntu/ centos ... centos
 - 3. 端口开放情况 均以开放
 - 4. 是否是公网部署  是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试 部署多个zlm
 - 8. 代码更新时间（旧版本请更新最新版本代码测试）

现在问题是只要一个平台播放了监控视频，其他平台进行播放就会出现响应超时，这个有什么办法解决吗

**Comment by 648540858** [comment]
更新代码测试
