### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by liyuanyuan200** [648540858/wvp-GB28181-pro#1729]
**环境信息:**

 - 1. 部署方式 ：编译wvp-pro/ wvp-prp + zlm都是编译部署
 - 2. 部署环境：  centos 
 - 3. 端口开放情况：全开放
 - 4. 是否是公网部署：专网部署 
 - 5. 是否使用https：否
 - 6. 接入设备/平台品牌：叙简设备
 - 7. 你做过哪些尝试
 - 8. 代码更新时间：2024.12.16
 - 9. 是否是4G设备接入：是

**描述错误**
198和196 均为服务器
198-->196级联,同是196不向198级联。在196发起点播 对讲 回放都ok。
198-->196级联,同时196向198级联。在196发起点播ok,对讲和回放都不行。
**复现问题以及抓包内容**
[最新修正版wvp198向196级联.docx](https://github.com/user-attachments/files/18237340/wvp198.196.docx)

**Comment by 648540858** [comment]
你是两个平台互为上下级了， 国标级联的时候设备国标编号不要使用默认的试试

**Comment by liyuanyuan200** [comment]
测试的时候两个wvp平台的国标编号不同。196：31010600492000000003 198：31010600492000000002。
下图是平台信息：
![Uploading 196.jpg…]()
![Uploading 198.jpg…]()

**Comment by 648540858** [comment]
我说的国标级联里填写设备编号，默认是平台自己的编号，你需要修改一下， 让平台认为是另一个平台注册过来的，不会和设备发来的请求冲突

**Comment by liyuanyuan200** [comment]
是的，现在可以了 。谢谢~
