### ISSUE TITLE
报警信息获取不到

### ISSUE THREAD

**Issue by IOTOSPaaS** [648540858/wvp-GB28181-pro#173]
请问报警信息推送打开了，但是调用接口获取报警信息获取不到

**Comment by 648540858** [comment]
配置你的设备，让他发报警，多半是设备没发

**Comment by IOTOSPaaS** [comment]
发了，日志也打印了：
<?xml version="1.0" encoding="GB2312" standalone="yes" ?><Notify><CmdType>Alarm</CmdType><SN>102</SN><DeviceID>34020000001310000002</DeviceID><AlarmPriority>1</AlarmPriority><AlarmMethod>5</AlarmMethod><AlarmTime>2021-09-26T17:26:16</AlarmTime><AlarmDescription>��Ƶ�ڵ�</AlarmDescription><AlarmInfo>10</AlarmInfo></Notify>
2021-09-26 17:26:18.215 DEBUG 3404 --- [ool-1-thread-11] c.g.i.v.g.t.r.i.MessageRequestProcessor  : 接收到Alarm消息

**Comment by 648540858** [comment]
你是调试模式还是打包运行的。前端文件调试模式无法收到报警

**Comment by IOTOSPaaS** [comment]
打包运行的java -jar wvp-pro-2.0-09260922.jar --spring.config.location=application-dev.yml

用的mysql数据库

**Comment by IOTOSPaaS** [comment]
<?xml version="1.0" encoding="GB2312" standalone="yes" ?><Notify><CmdType>Alarm</CmdType><SN>110</SN><DeviceID>34020000001310000002</DeviceID><AlarmPriority>1</AlarmPriority><AlarmMethod>5</AlarmMethod><AlarmTime>2021-09-26T17:53:12</AlarmTime><AlarmDescription>��Ƶ�ڵ�</AlarmDescription><AlarmInfo>10</AlarmInfo></Notify>
收到的DeviceID是34020000001310000002（看了下是摄像头的通道编号），但是mysql数据库中device表存的deviceid是34020000001320000002（看了下是设备编号），所以查询不到记录，直接return，程序没有继续往下走保存

**Comment by IOTOSPaaS** [comment]
现在只能在后台配置页面将通道好改为设备编号，大佬你看是否需要修改下代码
processMessageAlarm类里面Device device = storager.queryVideoDevice(deviceId);，不去device表中查找

**Comment by 648540858** [comment]
给我发一个你抓包的报警包

**Comment by 648540858** [comment]
已修复，你测试下

**Comment by IOTOSPaaS** [comment]
ok，很强
