### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by tsing-dong** [648540858/wvp-GB28181-pro#1732]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 全开放了
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 自己研发的
 - 7. 你做过哪些尝试
 - 8. 代码更新时间（旧版本请更新最新版本代码测试）今天

**内容描述:**
后端部署项目时配置 sip.ip 为公网ip是报 ip和端口占用 使用 0.0.0.0 就不会这种情况。

**截图**  
![image](https://github.com/user-attachments/assets/77cbde1b-cab1-4282-8528-27748fbdadc4)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by tsing-dong** [comment]
已解决

**Comment by lin-jj-engine** [comment]
咋解决的
