### ISSUE TITLE
流传输模式改成 tcp被动 拉流一直超时 

### ISSUE THREAD

**Issue by rsxieliang** [648540858/wvp-GB28181-pro#176]

**Comment by 648540858** [comment]
你的设备支持tcp被动吗

**Comment by rsxieliang** [comment]
支持的发自我的华为手机-------- 原始邮件 --------发件人： 648540858 ***@***.***>日期： 2021年9月26日周日 17:12收件人： 648540858/wvp-GB28181-pro ***@***.***>抄送： rsxieliang ***@***.***>, Author ***@***.***>主    题： Re: [648540858/wvp-GB28181-pro] 流传输模式改成 tcp被动 拉流一直超时  (#176)

你的设备支持tcp被动吗

**Comment by rsxieliang** [comment]
支持的  我测试过 往另外一个平台上推的时候就可以用tcp拉流的方式,但是我注册到这个平台的时候 就智能udp 用tcp就一直超时 senior-sdp这个配置也设置成true

**Comment by xianghu1314** [comment]
@rsxieliang 如何解决这个问题的呢？
