### ISSUE TITLE
Ubuntu 20 下按linux编译下操作无法完成

### ISSUE THREAD

**Issue by wjtNo2** [648540858/wvp-GB28181-pro#18]
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! gb_web@1.0.0 build: `node build/build.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the gb_web@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-23T02_03_15_401Z-debug.log
报错信息 会是哪里的问题？

**Comment by wjtNo2** [comment]
内存1G编译失败；调到4G 就OK了

**Comment by 648540858** [comment]
那我关闭了，1G内存确实太少了，需要在低内存下运行，请先编译好直接部署。
