### ISSUE TITLE
wvp云端录像下载url缺少mediaServerId导致下载失败

### ISSUE THREAD

**Issue by yuklcool** [648540858/wvp-GB28181-pro#181]
对云端录像进行下载时候下载地址url中缺少mediaServerId，导致后台获取mediaServerId错误下载提示找不到文件
![image](https://user-images.githubusercontent.com/15844128/136653562-cb9e87ab-c69a-4bdb-bc42-b857ba2df08c.png)

**Comment by 648540858** [comment]
好的 我修复下

**Comment by 648540858** [comment]
已修复
