### ISSUE TITLE
 sipSubscribe.addErrorSubscribe使用引出的隐患

### ISSUE THREAD

**Issue by seamende** [648540858/wvp-GB28181-pro#187]
sipSubscribe.addErrorSubscribe(callIdHeader.getCallId(), errorEvent);
这行代码以callid为键，每发起一个sip请求就往map里面插入一条记录，但是一直没清除
运行久了后，可能造成map过大而引起程序异常

**Comment by 648540858** [comment]
好的，我查一下

**Comment by seamende** [comment]
还发现一个问题：KeepaliveTimeoutListenerForPlatform的OnMessage函数开头有以下判断：
if(!expiredKey.startsWith(VideoManagerConstants.PLATFORM_KEEPLIVEKEY_PREFIX)){
        	logger.debug("收到redis过期监听，但开头不是"+VideoManagerConstants.PLATFORM_KEEPLIVEKEY_PREFIX+"，忽略");
        	return;
}
会导致下面其他的redis值(如PLATFORM_REGISTER_PREFIX)过期事件无法处理，有以上级平台会检测这个时间，如果超过这个时间没有重新注册，上级平台会以为下级掉线（不看Keepalive）直接清除会话，导致正在传输的流中断

**Comment by seamende** [comment]
还发现一个问题：KeepaliveTimeoutListenerForPlatform的OnMessage函数开头有以下判断：
if(!expiredKey.startsWith(VideoManagerConstants.PLATFORM_KEEPLIVEKEY_PREFIX)){
logger.debug("收到redis过期监听，但开头不是"+VideoManagerConstants.PLATFORM_KEEPLIVEKEY_PREFIX+"，忽略");
return;
}
会导致下面其他的redis值(如PLATFORM_REGISTER_PREFIX)过期事件无法处理，有些上级平台会检测这个时间，如果超过这个时间没有重新注册，上级平台会以为下级掉线（不看Keepalive）直接清除会话，导致正在传输的流中断

**Comment by 648540858** [comment]
两个问题都修复了，你有时间测试下。

**Comment by 648540858** [comment]
你的建议非常棒，多谢。欢迎一起参与开发。

**Comment by seamende** [comment]
嗯，感谢大佬的项目
