### ISSUE TITLE
摄像头sip通讯异常

### ISSUE THREAD

**Issue by ydddx** [648540858/wvp-GB28181-pro#188]
bug 现象
刷新 通道时 提示 timeout
偶尔获取到通道，但是无法点播

在centos7运行
无法点播，通过抓包发现 Port unreachable 
配置文件配置sip port 5060 排查没有端口占用

window 正常

抓包截图 查看抓包看数据只有部分
![20211016190410](https://user-images.githubusercontent.com/58802847/137584804-e021a7c0-7909-4906-9875-765d6cbcc794.png)

**Comment by penghd** [comment]
是有通道不能刷新，还是看不见通道，刷新也刷不出？
正常情况应该注册就能看见通道。
大部分前端是注册到UDP端口，看centos 防火墙udp 5060开了没有，包括网络防火墙。

**Comment by chenparty** [comment]
> > 好像确实不能点播了，前端时间还正常点播的，更新后就不能点播了，设备端确认没问题，因为之前配置了一直没变过。 下面是最新版本的点播sip请求： ![image](https://user-images.githubusercontent.com/16755257/137680328-eec37d28-ed00-4bb7-afaa-217ec179bf0e.png)
> 
> 你这个看着是ip 错了 192的ip和你的124的ip应该是不通的。 注意sip 124.71.144.201 这一条。 注意下你的mediaserver ip 的配置 和数据库中内容
有道理，我忽略了这个，我明天再换个局域网地址试试。

**Comment by 648540858** [comment]
有的设备不支持catlog消息，这个是用来查询通道信息的，部分设备只支持使用订阅的方式，目前订阅当时还没整合到代码流程里。你可以抓个包看看。

**Comment by 648540858** [comment]
我先关了你可以使用最新的代码测试下
