### ISSUE TITLE
节点添加BUG

### ISSUE THREAD

**Issue by chenparty** [648540858/wvp-GB28181-pro#189]
1. 节点添加时，开启多端口，保存成功后，数据库的节点表enableRtp和sendRtpRangePort值未保存进去。
2. 再点击节点编辑时也无法修改，且再保存sendRtpRangePort值会变成  ",undefined"。
3. 另外就是有个优化点：DeferredResultHolder类中CALLBACK_CMD_PlAY，PlAY应该为PLAY。

**Comment by 648540858** [comment]
好的我看一下

**Comment by 648540858** [comment]
已修复
