### ISSUE TITLE
播放视频提示找不到zlm节点

### ISSUE THREAD

**Issue by RaymanTao** [648540858/wvp-GB28181-pro#195]
部署在一个公网服务器上，第一次播放没有问题但关掉过一段时间再去播放提示图片所示，查看redis里面应该zlm的id被清空了，这是什么原因
![1634875133(1)](https://user-images.githubusercontent.com/23013326/138391553-464ebc78-7139-4d21-89ab-2347c2b7ea33.png)

**Comment by 648540858** [comment]
使用的是最新的代码吗？

**Comment by RaymanTao** [comment]
> 使用的是最新的代码吗？

不是，几个月前的了。

**Comment by 648540858** [comment]
使用最新代码测试，或者使用docker版本。我先关了

**Comment by chenkunet** [comment]
我也出现了这个问题

**Comment by chenkunet** [comment]
我也出现了这个问题，zml使用的docker，也是最新的代码
