### ISSUE TITLE
并发点播出现的问题

### ISSUE THREAD

**Issue by godlike10** [648540858/wvp-GB28181-pro#196]
应用场景是都是通过zlm的未找到流事件来点播的。
这时遇到的并发点播的问题，同一路视频会开多个不同的端口来接收。
但是redis里面保存的key都是设备id和通道id来命名的，导致结束的时候只关闭了一个端口的流，
另外几个端口的就没有发送bye命令。
我这边暂时解决方案是在点播事件开始又加了个缓存，每次都验证下有没有点播过，如果点播过就return掉。
点播失败或者视频结束的时候将这个缓存清除掉。

**Comment by 648540858** [comment]
提交了代码,解决并发点播问题的，你可以试试。
