### ISSUE TITLE
节点管理模块问题

### ISSUE THREAD

**Issue by szy833** [648540858/wvp-GB28181-pro#199]
新增节点是以ZLM已有的节点配置为准

但是，更新的时候为什么只是修改了数据库和redis里的配置，ZLM里的配置都没有做修改？

**Comment by 648540858** [comment]
因为如果zlm使用的是docker部署，我修改了内部端口会导致映射失效，所以现在不对zlm进行更新，需要自己手动修改，就是说你修改了wvp的zlm端口，zlm对应内容也需要改成一致的。
