### ISSUE TITLE
windows 环境编译 第四步 wvp-2.3.5.RELEASE.jar 没有生成不知道哪里原因？

### ISSUE THREAD

**Issue by zhishiqu** [648540858/wvp-GB28181-pro#201]
我按着windows编译步骤，到第四步，mvn package 打包后没有生成  wvp-2.3.5.RELEASE.jar  只有两个其他的jar包  不知道哪里存在问题

我没有 没有什么java开发经验 所以没有用 java  的  idea

![image](https://user-images.githubusercontent.com/22735110/139591108-68d79a4f-831e-4435-b1a3-a5dccd33639f.png)

我觉得好像这里有问题似的。

多谢，指点。

**Comment by 648540858** [comment]
文档更新可能有延时，看下你的jar包截图。
