### ISSUE TITLE
wvp-pro2.0最新代码加入证书的问题

### ISSUE THREAD

**Issue by Ningzetao** [648540858/wvp-GB28181-pro#202]
**wvp这边加入JKS证书，配置文件也修改为true**
```
ssl:
    # [可选] 是否开启HTTPS访问
    enabled: true
```
**wvp平台这边的https访问正常，播放视频会一直加载，控制台报错**
```
WebSocket connection to 'wss://x.x.151.197:10443/rtp/34020000001320000004_34020000001320000004.flv' failed: 
play @ index.js:1
```
> zlm使用的docker.io最新的镜像panjjo/zlmediakit
有人遇到吗怎么解决的？

**Comment by 648540858** [comment]
zlm的设置参考这个，可能需要定制镜像才可以，我自己没给zlm docker镜像添加过ssl，你可以测试下。另外确认https端口开放了。
