### ISSUE TITLE
【新功能】支持两台设备同时看nvr录象

### ISSUE THREAD

**Issue by helloCZZ** [648540858/wvp-GB28181-pro#203]
两台设备同时看nvr录象，只能有一台可以播放，另一台会断掉

**Comment by 648540858** [comment]
是的， 目前不支持同时观看

**Comment by chenzhen1996** [comment]
![X3L}54SDS$7I$NJ$7E L2VS](https://user-images.githubusercontent.com/35329753/140013117-ee36d726-d632-48cf-a250-2c77f2d665e6.jpg)
作者你好，今天拉了最新的代码，重新编译后还是发现一台设备观看NVR录象时，另一台还是会断，如上图所示。目前需求是多台设备可以同时观看，如何实现这是现在所面临的困惑。

**Comment by 648540858** [comment]
这是新功能issue，不是已经实现的功能。目前不支持

**Comment by 648540858** [comment]
已经支持
