### ISSUE TITLE
华为NVR 28181连接后通道数量为0

### ISSUE THREAD

**Issue by KevinLJJ** [648540858/wvp-GB28181-pro#204]
- 部署环境：华为NVR在内网，下挂两个IPC。WVP使用docker部署在公有云（公有云安全组已放开）

<img width="1438" alt="WX20211102-171307@2x" src="https://user-images.githubusercontent.com/25399359/139819097-2cad4c1b-1c39-475c-a896-67131e983169.png">

![image](https://user-images.githubusercontent.com/25399359/139819184-03ed2510-4be8-4d02-b303-41a3e82a7df2.png)

烦请协助看看是怎么回事，感谢！

**Comment by KevinLJJ** [comment]
NVR侧配置
![image](https://user-images.githubusercontent.com/25399359/139819625-c8499443-c083-4bf4-9aca-67a513d7e719.png)

**Comment by 648540858** [comment]
会抓包吗，开启抓包，然后点击通道刷新，等20秒，停止抓包，把抓包文件发送到648540858@qq.com

**Comment by KevinLJJ** [comment]
或许是我NVR在局域网内，WVP在公有云，WVP无法和NVR建立连接的原因（contactIP）？

**Comment by 648540858** [comment]
刚注册可以更新吗

**Comment by 648540858** [comment]
我需要把消息发回给设备，如果你的局域网路由是只出不进的，那确实不可以

**Comment by KevinLJJ** [comment]
![image](https://user-images.githubusercontent.com/25399359/139824862-09e997db-5859-4859-925d-b4373a76974d.png)
注册后反馈的局域网地址，那看来就是这个原因了，谢谢。
