### ISSUE TITLE
【优化】录像下载接口优化

### ISSUE THREAD

**Issue by jackyHJ** [648540858/wvp-GB28181-pro#205]
![图片](https://user-images.githubusercontent.com/32256773/140023484-10918248-6271-48a0-93db-a8c467362734.png)

录像下载接口一直timeout，录像回放能用, 但有时候会报错误码： 486, Busy Here

**Comment by alexjeo** [comment]
下载功能基本不好使

**Comment by 648540858** [comment]
这个只是测试使用，没做什么优化，确实不好用等我更新一下你再用吧

**Comment by jackyHJ** [comment]
@648540858  录像回放有问题，刚开始都还可以回放过一段时间后再次请求全部都会timeout

**Comment by RockWillams** [comment]
这个开始回放接口确实会超时，用不了，希望老大空了尽快上新

**Comment by 648540858** [comment]
已经优化
