### ISSUE TITLE
高并发持续调直播流wvp崩溃报错

### ISSUE THREAD

**Issue by gujianghua** [648540858/wvp-GB28181-pro#207]
程序启动15个小时左右，循环调用多个设备的直播，程序崩溃，日志显示以下报错
![2021-11-04 09-22-07 的屏幕截图](https://user-images.githubusercontent.com/82638990/140245084-050e00a3-e34c-4a7a-8f6e-6e91eb7ba383.png)
![2021-11-04 09-22-07 的屏幕截图](https://user-images.githubusercontent.com/82638990/140245097-eb5328b6-6040-44f1-9824-029006e3bf85.png)
![2021-11-04 09-21-28 的屏幕截图](https://user-images.githubusercontent.com/82638990/140245119-7571a1a5-410f-457b-802b-9a01b51a239f.png)
[wvp.log](https://github.com/648540858/wvp-GB28181-pro/files/7471777/wvp.log)

**Comment by 648540858** [comment]
你有其他程序读取sqlite数据库了，数据库只能一个程序写入，wvp使用的时候不要用其他程序写入，其他程序使用的时候请设置只读，最好不要使用，看数据可以把SQLite文件复制一份查看

**Comment by gujianghua** [comment]
我整个程序的部署就是在docker容器里面的，没有其他程序读取。容器里只有流媒体和redis服务。我们是6路并发持续取流，从昨天上午10点运行到下午六点左右，wvp就进不去了。

**Comment by gujianghua** [comment]
我现在换成mysql数据库了，运行一段时间，持续点播的话，报的是现在这个错误了。请问有遇到这个问题吗
![2021-11-09 10-01-17 的屏幕截图](https://user-images.githubusercontent.com/82638990/140848676-01f39fbb-c107-44fd-aad8-0aad565ba576.png)

**Comment by 648540858** [comment]
你是最新的代码吗，以前解决过类似的问题

**Comment by gujianghua** [comment]
是最新的

**Comment by 648540858** [comment]
![image](https://user-images.githubusercontent.com/18274453/140851160-1d75587b-8692-410a-bfed-7ebf31779248.png)
看看这个位置，是不是这样的

**Comment by gujianghua** [comment]
是这样的
![2021-11-09 10-44-46 的屏幕截图](https://user-images.githubusercontent.com/82638990/140852532-136e1a0c-6433-4cb3-8649-54ee6e967635.png)

**Comment by 648540858** [comment]
好的，目前还不知道什么原因，你发一个wvp的日志的文件给我吧，648540858@qq.com

**Comment by gujianghua** [comment]
日志昨天发给您了，请问有发现什么原因吗？

**Comment by 648540858** [comment]
不好意思，日志收到了还没来得及看

**Comment by gujianghua** [comment]
您好，我昨天看日志，发现有报错连接redis超时，然后在配置文件里面修改了时间，但是今天发现有新的堆栈溢出的错误，请问您有解决方法吗。
![2021-11-11 10-00-25 的屏幕截图](https://user-images.githubusercontent.com/82638990/141223669-beb101b8-99ee-4814-b74c-4939ac918120.png)
![2021-11-11 10-03-04 的屏幕截图](https://user-images.githubusercontent.com/82638990/141223944-e61f03a6-b4ef-444f-8f51-ad9e54c5ed20.png)

**Comment by gujianghua** [comment]
这是今天的日志文件
[wvp.log](https://github.com/648540858/wvp-GB28181-pro/files/7517110/wvp.log)

**Comment by gujianghua** [comment]
您好，请问这个内存问题解决了吗？ 我们开了六路设备的取流，运行15个小时左右，就会报java.lang.OutOfMemoryError: Java heap space错误。今天早上平台还是down掉了。

**Comment by apachefarmer** [comment]
> 您好，请问这个内存问题解决了吗？ 我们开了六路设备的取流，运行15个小时左右，就会报java.lang.OutOfMemoryError: Java heap space错误。今天早上平台还是down掉了。

我的建议是你可以jmap分析下jvm的堆情况，看下是什么对象占满了堆空间。再从代码里找一下看看。

**Comment by gujianghua** [comment]
您好，这是我们用内存检测工具分析的内存。
![图片](https://user-images.githubusercontent.com/82638990/147720337-5d5c8c06-cbc5-452a-8996-21ac2e802b0f.jpeg)
![webwxgetmsgimg](https://user-images.githubusercontent.com/82638990/147720345-a788e672-1ea6-4d32-88c4-2946aff61205.jpeg)

**Comment by Zeke-S** [comment]
遇到同样问题，现在有解决方案么 @648540858

**Comment by yaoxiaojian-liuxiaojun** [comment]
目前可以考虑在大量设备请求进来的时候导致的内存溢出情况,多个设备节点(级联下级)存在超过1w+设备容易浮现这个问题,单个设备节点(或级联下级)存在超过2w+通道也容易浮现这个问题.

**Comment by hxgqh** [comment]
我这里600来个设备，基本上几天就出现了

**Comment by 648540858** [comment]
使用新版本测试下
