### ISSUE TITLE
出现"inputRtp | ssrc不匹配,rtp已丢弃"

### ISSUE THREAD

**Issue by jackyHJ** [648540858/wvp-GB28181-pro#208]
![图片](https://user-images.githubusercontent.com/32256773/140454563-5d3ab857-9abc-4d6d-81e8-23b9e21bf637.png)

ZLM那边说sip调度紊乱，多个摄像头调用一个端口导致的！我看了，确实出现了不同通道视频是一样的结果！

**Comment by 648540858** [comment]
你重启了wvp没有重启设备吧，如果设备之前再推流就可能有问题

**Comment by jackyHJ** [comment]
@648540858 好的我试试，需不需要清理redis呀

**Comment by 648540858** [comment]
不用，如果中间停止的时间短，是不会有影响的，必须是最新的代码，旧的不支持这个离线存储事务的特性。
