### ISSUE TITLE
通道数量错误

### ISSUE THREAD

**Issue by longegit** [648540858/wvp-GB28181-pro#21]
我的设备是海康的摄像头，catalog信息如下，ParentID值是sip服务器的域id，导致通道数量多加了一个
<img width="318" alt="WX20201229-121440@2x" src="https://user-images.githubusercontent.com/2749775/103258135-ea6c7880-49ce-11eb-921a-4bcd6c138aac.png">

**Comment by 648540858** [comment]
好的， 我看一下

**Comment by 648540858** [comment]
已修复， 更新代码测试吗
