### ISSUE TITLE
关于redis的选择

### ISSUE THREAD

**Issue by seamende** [648540858/wvp-GB28181-pro#211]
版主，你好。通过分析代码，wvp使用redis缓存了一些数据，并利用它的键超时通知机制来做一些心跳或者注册方面的处理。使用redis，增加了部署的工作量，可否跳过redis，wvp自己缓存数据，并利用springboot的定时器来处理心跳或者注册相关的事务?

**Comment by 648540858** [comment]
如你所说，目前redis确实只是用来缓存以及事件过期通知，但是后续可能作为一个对接与命令通知的渠道使用。所以暂时不打算去掉他，很早之前考虑过，后来又加回来了。
