### ISSUE TITLE
设备自动更新为离线问题

### ISSUE THREAD

**Issue by jackyHJ** [648540858/wvp-GB28181-pro#214]
![图片](https://user-images.githubusercontent.com/32256773/141077026-38a89140-57c0-4ef4-be37-046d3a90bb47.png)
![图片](https://user-images.githubusercontent.com/32256773/141077056-53190221-ac7e-4f96-aee5-27a6673a9642.png)

过一会儿设备会自动更新为离线，而且也没有心跳响应，重启设备又会正常但持续不了多久！ 我拉的是最新代码！

**Comment by jackyHJ** [comment]
我刚看了，有些设备会过一段时间自动重新注册一下来更新在线状态，有些设备就不会重新注册！这和注册有效期有关吗

**Comment by 648540858** [comment]
和注册有效期以及心跳间隔有关
