### ISSUE TITLE
首次切换到mysql设备不会注册到数据库，导致查询不到设备列表

### ISSUE THREAD

**Issue by chenparty** [648540858/wvp-GB28181-pro#215]
之前一直用的sqlite，首次切换到mysql，连接成功，能登陆，但是一直无设备列表，注册成功也没有，看代码发现只添加到了redis，好像没有添加到mysql。

**Comment by chenparty** [comment]
由于subscribeCycleForCatalog字段在mysql.sql文件存在，插入设备时因sql语句不包含subscribeCycleForCatalog字段，且该字段无默认值，从而导致插入设备失败。而sqlite里面无此字段，故能正常插入设备。

**Comment by keepgoingxjw** [comment]
我在数据中对 subscribeCycleForCatalog 设置了 default 0，这样就可以了
