### ISSUE TITLE
on_record_mp4中IP跟media.ip配置不一致

### ISSUE THREAD

**Issue by JacksonTu** [648540858/wvp-GB28181-pro#216]
在配置文件中配置media.ip和record-assist-port
zlm config.ini中内容如下：
on_play=http://192.168.6.150:48080/index/hook/on_play
on_publish=http://192.168.6.150:48080/index/hook/on_publish
on_record_mp4=http://127.0.0.1:48081/api/record/on_record_mp4
on_record_mp4为127.0.0.1而不是192.168.6.150，希望修改成192.168.6.150

**Comment by Karrys** [comment]
多看看wiki, https://github.com/648540858/wvp-GB28181-pro/wiki/云端录像功能部署与使用。

你配置文件中192.168.6.150是wvp服务的ip, 127.0.0.1是zlm服务的ip(也即是云端录像服务的ip)。

**Comment by 648540858** [comment]
on_record_mp4 是给assit用的
