### ISSUE TITLE
http-flv 无法播放

### ISSUE THREAD

**Issue by keepgoingxjw** [648540858/wvp-GB28181-pro#219]
下面视频链接：http-flv 无法播放，其它格式均可以播放，不知道什么原因
flv: "http://172.27.5.217:86/rtp/061468B2.flv"
fmp4: "http://172.27.5.217:86/rtp/061468B2.live.mp4"
hls: "http://172.27.5.217:86/rtp/061468B2/hls.m3u8"
ws_flv: "ws://172.27.5.217:86/rtp/061468B2.flv"

zlmediakit 提示如下：
 HttpSession.cpp:361 operator() | 140236051546112(117.89.129.136:2274) flv播放器一般只支持H264和AAC编码,该编码格式可能不被播放器支持:PCMU

**Comment by oldR** [comment]
源视频编码应该是H265，改成H264再推流就好了

**Comment by 648540858** [comment]
看下浏览器控制台有没有报错
