### ISSUE TITLE
设备注册没有插入到数据库里面

### ISSUE THREAD

**Issue by jackyHJ** [648540858/wvp-GB28181-pro#220]
![图片](https://user-images.githubusercontent.com/32256773/141399717-6938d55b-5512-48b2-b769-d27a6f5606cd.png)
![图片](https://user-images.githubusercontent.com/32256773/141399733-68722430-d703-44c2-9847-74fc2e91a13c.png)
![图片](https://user-images.githubusercontent.com/32256773/141399754-61a03dc2-683c-4497-8746-fbe02ab89368.png)
拉的最新代码，设备注册成功没有插入到数据库里

**Comment by keepgoingxjw** [comment]
https://github.com/648540858/wvp-GB28181-pro/issues/215 应该是这个问题

**Comment by jackyHJ** [comment]
@keepgoingxjw 果然，太感谢了
