### ISSUE TITLE
上级平台心跳状态更新的bug

### ISSUE THREAD

**Issue by jingyuzhu** [648540858/wvp-GB28181-pro#221]
触发条件：wvp成功注册上级平台，然后关闭上级平台，wvp会持续发送3次心跳，然后触发重新注册。此时恢复上级平台，wvp成功注册上级平台。但到下个心跳周期不会发送心跳，仍然会触发重新注册

排查发现，在心跳处理上，触发重注册之后未重置心跳计数器的redis缓存。

![image](https://user-images.githubusercontent.com/8636506/141403228-6bf6993a-4534-46f4-a4c8-c5d2f5b4e623.png)

**Comment by 648540858** [comment]
已修复
