### ISSUE TITLE
docker部署获取不了通道数

### ISSUE THREAD

**Issue by jackyHJ** [648540858/wvp-GB28181-pro#224]
![图片](https://user-images.githubusercontent.com/32256773/141448362-b2c5fc2e-cfc5-4e01-8380-a63ce64ece9b.png)
![图片](https://user-images.githubusercontent.com/32256773/141448402-dfc33142-1a5c-4cce-a09b-a7f504b3d24a.png)
各种重启都还是无法获取到通道

**Comment by jackyHJ** [comment]
我打成jar运行就能获取到

**Comment by 648540858** [comment]
docker使用host模式试试，需要linux环境。

**Comment by 648540858** [comment]
> 我打成jar运行就能获取到

是用的docker hub的版本吗，我局域网测试没问题，你是公网服务器吗

**Comment by 648540858** [comment]
新版的测试没问题你更新试试
