### ISSUE TITLE
重构Message结构后的问题

### ISSUE THREAD

**Issue by Karrys** [648540858/wvp-GB28181-pro#227]
![image](https://user-images.githubusercontent.com/19201279/141719177-adb54a5e-ef05-4e34-a434-6ed139c3cc0e.png)
cmdType是会重复的(不同的messageType有相同的cmdType)

**Comment by 648540858** [comment]
是的，所以之前使用树形结构重构代码是不完全正确的，可以需要换一下模式，cmdtype与message做成通用可组合会更好些。
