### ISSUE TITLE
程序运行一段时间后会异常挂掉， 有以下错误

### ISSUE THREAD

**Issue by khw934** [648540858/wvp-GB28181-pro#228]
![XD@2}K`LDXGB9YIM3_V4HA6](https://user-images.githubusercontent.com/35864027/141896064-d18f6d66-0c4f-4144-96c9-556a484eb517.png)

**Comment by qjw2bqn** [comment]
我在ubuntu 16.04 采用docker部署也出现同样的问题！

**Comment by 648540858** [comment]
我后续更新下docker镜像你们再试试。

**Comment by 648540858** [comment]
diocker更新了你们试试
