### ISSUE TITLE
级联播放报错

### ISSUE THREAD

**Issue by zlklink** [648540858/wvp-GB28181-pro#235]
![image](https://user-images.githubusercontent.com/39792244/142408821-36d5e97d-ce88-4852-8155-ddbd1875acd4.png)
级联方式：大华相机 -> wvp1 -> wvp2 
wvp2端播放大华相机，wvp2的zlmedierkt较高概率出现如上错误

**Comment by 648540858** [comment]
wvp1 上有什么问题吗，可以正常播放吗？ 把wvp的播放超时时间设置的长一些

**Comment by 648540858** [comment]
看你也没关注，我先关了。

**Comment by zlklink** [comment]
我关注了啊，github和gitee都关注了，忠实粉丝，非常希望这个项目能推进




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月22日(星期一) 上午9:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [648540858/wvp-GB28181-pro] 级联播放报错 (Issue #235)





 
看你也没关注，我先关了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zlklink** [comment]
好的，我没注意看到这个邮件



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月19日(星期五) 上午9:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [648540858/wvp-GB28181-pro] 级联播放报错 (Issue #235)





 
wvp1 上有什么问题吗，可以正常播放吗？ 把wvp的播放超时时间设置的长一些
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
