### ISSUE TITLE
海康IVMS8700（2.7）平台，播放视频返回400 Bad Request

### ISSUE THREAD

**Issue by sdsyt** [648540858/wvp-GB28181-pro#236]
海康IVMS8700（2.7）平台，可以正常获取到通道信息，但是点击“播放”按钮，就会弹出“点播失败， 错误码： 400, Bad Request”。
控制台打印的日志：
`
2021-11-18 23:15:34.178 DEBUG 3024 --- [vp-sip-handle-1] c.g.i.v.g.transmit.SIPProcessorObserver  : SIP/2.0 100 Trying
Via: SIP/2.0/UDP 192.168.1.198:5060;rport=5060;branch=z9hG4bK-3539-c692822bcebe79e1b4cdeed345be87bd
From: <sip:37060000462000000001@3706000046>;tag=FromInvt1637248534132
To: <sip:37068500005010000061@3706000046>
Call-ID: 3d1dbc4498f4c49b456e430d29effbc4@0.0.0.0
CSeq: 1 INVITE
User-Agent: NCG V2.6.0.360033
Content-Length: 0

2021-11-18 23:15:34.193 DEBUG 3024 --- [vp-sip-handle-3] c.g.i.v.g.transmit.SIPProcessorObserver  : SIP/2.0 400 Bad Request
Via: SIP/2.0/UDP 192.168.1.198:5060;rport=5060;branch=z9hG4bK-3539-c692822bcebe79e1b4cdeed345be87bd
From: <sip:37060000462000000001@3706000046>;tag=FromInvt1637248534132
To: <sip:37068500005010000061@3706000046>;tag=749673207
Call-ID: 3d1dbc4498f4c49b456e430d29effbc4@0.0.0.0
CSeq: 1 INVITE
Content-Type: Application/SDP
User-Agent: NCG V2.6.0.360033
Content-Length: 125

<?xml version="1.0"?>
<ErrorInfo>
<ErrorCode>2207</ErrorCode>
<ErrorDescripe>192.168.10.251</ErrorDescripe>
</ErrorInfo>
`

**Comment by 648540858** [comment]
抓个包看一下，或者更海康的人员沟通下为什么返回400，只有这个日志确定不了问题

**Comment by 648540858** [comment]
看你也没关注，我先关了。

**Comment by sdsyt** [comment]
> 看你也没关注，我先关了。

您先关掉问题吧。 我联系海康的技术了，他们说这个版本太老了，他们已经不维护了。 现在也提供不了什么信息。

**Comment by 648540858** [comment]
OK 有什么后续，你再打开
