### ISSUE TITLE
wvp 2.0 windows 平台播放超时

### ISSUE THREAD

**Issue by xiaoxiao-asss** [648540858/wvp-GB28181-pro#237]
windows 抓包信息
[result.zip](https://github.com/648540858/wvp-GB28181-pro/files/7567132/result.zip)

wvp配置

`spring:
    # REDIS数据库配置
    redis:
        # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
        host: ${REDIS_HOST:127.0.0.1}
        # [必须修改] 端口号
        port: ${REDIS_PORT:6379}
        # [可选] 数据库 DB
        database: ${REDIS_DB:7}
        # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        password: ${REDIS_PWD:}
        # [可选] 超时时间
        timeout: 10000
    # [可选] jdbc数据库配置, 项目使用sqlite作为数据库，一般不需要配置

    datasource:
        name: wvp
        url: jdbc:mysql://192.168.137.129:3308/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        max-active: 1
        min-idle: 1

# [可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 18080

WVP_HOST: 192.168.5.241

# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: ${WVP_HOST}
    # [可选] 28181服务监听的端口
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: ${WVP_DOMAIN:4401020049}
    # [可选]
    id: ${WVP_ID:44010200492000000001}
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: ${WVP_PWD:admin123}

#zlm 默认服务器配置
media:
    # [必须修改] zlm服务器的内网IP
    ip: 127.0.0.1
    # [必须修改] zlm服务器的http.port
    http-port: 8089
    # [可选] zlm服务器的hook.admin_params=secret
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
    rtp:
        # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
        enable: false
        # [可选] 在此范围内选择端口用于媒体流传输,
        port-range: 30000,30500 # 端口范围
        # [可选] 国标级联在此范围内选择端口发送媒体流,
        send-port-range: 30000,30500 # 端口范围
    # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
    record-assist-port: 18081
    sdp-ip: ${WVP_HOST}
    stream-ip: ${WVP_HOST}
# [可选] 日志配置, 一般不需要改
logging:
    file:
        name: logs/wvp.log
        max-history: 30
        max-size: 10MB
        total-size-cap: 300MB
    level:
        com.genersoft.iot: debug
        com.genersoft.iot.vmp.storager.dao: info
        com.genersoft.iot.vmp.gb28181: debug
        com.genersoft.iot.vmp.media.zlm: debug

# [根据业务需求配置]
user-settings:
    # 推流直播是否录制
    record-push-live: true
    auto-apply-play: false
    play-timeout: 18000

# 在线文档： swagger-ui（生产环境建议关闭）
swagger-ui:
    enabled: true

# 版本信息， 不需修改
version:
    version: "@project.version@"
    description: "@project.description@"
    artifact-id: "@project.artifactId@"`

zlm MediaServer流服务配置
`; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[ffmpeg]
bin=C:\Windows\System32\ffmpeg.exe
cmd=%s -fflags nobuffer -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264  -f flv %s
log=./ffmpeg/ffmpeg.log
snap=%s -i %s -y -f mjpeg -t 0.001 %s

[general]
addMuteAudio=1
enableVhost=0
flowThreshold=1024
fmp4_demand=0
hls_demand=0
maxStreamWaitMS=15000
mediaServerId=ADGKNQTX036adgjn
mergeWriteMS=0
modifyStamp=0
publishToHls=1
publishToMP4=0
resetWhenRePlay=1
rtmp_demand=0
rtsp_demand=0
streamNoneReaderDelayMS=18000
ts_demand=0

[hls]
broadcastRecordTs=0
fileBufSize=65536
filePath=./www
segDur=2
segNum=3
segRetain=5

[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
enable=1
on_flow_report=
on_http_access=
on_play=http://192.168.5.241:18080/index/hook/on_play
on_publish=http://192.168.5.241:18080/index/hook/on_publish
on_record_mp4=http://127.0.0.1:18081/api/record/on_record_mp4
on_record_ts=
on_rtsp_auth=
on_rtsp_realm=
on_server_started=http://192.168.5.241:18080/index/hook/on_server_started
on_shell_login=http://192.168.5.241:18080/index/hook/on_shell_login
on_stream_changed=http://192.168.5.241:18080/index/hook/on_stream_changed
on_stream_none_reader=http://192.168.5.241:18080/index/hook/on_stream_none_reader
on_stream_not_found=http://192.168.5.241:18080/index/hook/on_stream_not_found
timeoutSec=20

[http]
charSet=gb2312
dirMenu=1
keepAliveSecond=15
maxReqSize=4096
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit-5.0(build in Mar 18 2021 17:07:55)</center></body></html>
port=8089
rootPath=./www
sendBufSize=65536
sslport=8085

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[record]
appName=record
fastStart=0
fileBufSize=65536
filePath=./www
fileRepeat=0
fileSecond=3600
sampleMS=500

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=1935
sslport=19350

[rtp]
audioMtuSize=600
clearCount=10
maxRtpCount=50
videoMtuSize=1400

[rtp_proxy]
dumpDir=
port=10002
timeoutSec=15

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
port=555
sslport=332

[shell]
maxReqSize=1024
port=9001
; } ---`

摄像头配置
![image](https://user-images.githubusercontent.com/47917178/142538766-d21d5e17-9249-4dbf-a029-f8cc5400e46e.png)

数据库设备信息
![image](https://user-images.githubusercontent.com/47917178/142536651-387ab98f-8023-4496-9ccd-6684cb896516.png)

![image](https://user-images.githubusercontent.com/47917178/142536465-cf2ffc11-b8ca-4d38-9591-504e198217cd.png)
数据库设备通道
![image](https://user-images.githubusercontent.com/47917178/142537248-fa8b8cb3-594d-4261-a4eb-b4e1cc751147.png)

**Comment by 648540858** [comment]
关闭的win的防火墙，自己确认下zlm配置，多半都是这些问题。
下次不要贴这个大段配置了。我不会看的。

**Comment by 648540858** [comment]
你的设备需要发流到 192.168.5.241：10002 udp上，确认下你的设备可以连到这里

**Comment by xiaoxiao-asss** [comment]
> 你的设备需要发流到 192.168.5.241：10002 udp上，确认下你的设备可以连到这里
怎么确认呢？

**Comment by xiaoxiao-asss** [comment]
> 关闭的win的防火墙，自己确认下zlm配置，多半都是这些问题。 下次不要贴这个大段配置了。我不会看的。

好的，防火墙是关闭的
