### ISSUE TITLE
华为nvr注册时一直提示未携带授权信息

### ISSUE THREAD

**Issue by xiaoweipeng** [648540858/wvp-GB28181-pro#238]
![69098VV0(S$BXLV9}L%K%V4](https://user-images.githubusercontent.com/54565603/142575418-cadb2f1b-bdb2-4824-9ce6-c534e2de5641.jpg)

如图：
![image](https://user-images.githubusercontent.com/54565603/142575368-01bef934-4e55-4b1d-ae90-50cbc0e3d040.png)

**Comment by 648540858** [comment]
确认你的服务器id配置正确
确认密码正确
如果仍然不行，抓包发出来看一下

**Comment by 648540858** [comment]
看你也没关注，我先关了。
