### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'sip.ip' in value "${sip.ip}"

### ISSUE THREAD

**Issue by Funny-dot** [648540858/wvp-GB28181-pro#24]
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'sip.ip' in value "${sip.ip}"
我谷歌说是java代码配置文件问题，但是我不会JAVA。。。

**Comment by Funny-dot** [comment]
![image](https://user-images.githubusercontent.com/27287970/103497228-d8318500-4e7b-11eb-9346-29b12cf7f6f0.png)

**Comment by 648540858** [comment]
确认你使用了正确的配置文件，你可以直接使用dev也可以两个一起使用。

**Comment by Funny-dot** [comment]
> 确认你使用了正确的配置文件，你可以直接使用dev也可以两个一起使用。

这个配置文件是哪里不对啊，网卡IP没错的

**Comment by Funny-dot** [comment]
![image](https://user-images.githubusercontent.com/27287970/103498651-84756a80-4e80-11eb-8d04-42ce76435123.png)

![image](https://user-images.githubusercontent.com/27287970/103498715-a40c9300-4e80-11eb-9cdd-00fcf222d287.png)

**Comment by 648540858** [comment]
你的启动命令发一下

**Comment by Funny-dot** [comment]
已解决，启动命令要绝对路径
