### ISSUE TITLE
docker部署的界面和源码编译部署的界面不一样？

### ISSUE THREAD

**Issue by cs1991** [648540858/wvp-GB28181-pro#240]
![image](https://user-images.githubusercontent.com/19600602/142723760-452aeef2-faef-4198-8709-4f8d142e980f.png)
用docker快速部署的，这个界面有开源吗？

**Comment by 648540858** [comment]
不知道你用了什么界面，项目目前只维护了一套界面，在web_src目录，wiki有写

**Comment by cs1991** [comment]
嗯，我把web_src拿出来跑了一下，没问题了。
