### ISSUE TITLE
视频录像回调地址问题

### ISSUE THREAD

**Issue by yuklcool** [648540858/wvp-GB28181-pro#242]
当使用docker分别部署zlk和wvp时，wvp注册到zlk的视频录像的回调地址一直是127.0.0.1，导致录像完成时不能获取到录像完成回调事件
![$W{~0BC6KY3O((R TZRQ DM](https://user-images.githubusercontent.com/15844128/142988197-32a67227-4206-4228-bb3d-302278facf45.png)

**Comment by 648540858** [comment]
这个地址时给部署在docker内的assist用的，所以固定时127，wvp-pro里不关注这个hook，assist用来管理录像文件才会关注这个
