### ISSUE TITLE
本人新手，提一个比较简单的问题。我还需要单独启动zlm服务吗？

### ISSUE THREAD

**Issue by qingfengtaizi** [648540858/wvp-GB28181-pro#244]
git下代码之后，启动VManageBootstrap类，这个类我看着已经内置zlm服务了，好像还是保连接不上。请求大佬帮助
我是idea启动

**Comment by chenparty** [comment]
最好另外安装zlm并启动

**Comment by qingfengtaizi** [comment]
> 

谢谢朋友的回答。我看wiki的意思是，已经把zlm服务集成进去了吗？

**Comment by qingfengtaizi** [comment]
> 谢谢朋友的回答。我看wiki的意思是，已经把zlm服务集成进去了吗？



> 最好另外安装zlm并启动

谢谢朋友的回答。我看wiki的意思是，已经把zlm服务集成进去了吗？

**Comment by yujingwei2017** [comment]
zlm程序需单独开，wvp工程里封装的是与zlm的交互操作
