### ISSUE TITLE
开启录像后所有的流都进行录像，这样不合常理，大佬请区分

### ISSUE THREAD

**Issue by sxh-netizen** [648540858/wvp-GB28181-pro#246]
当开启录制后，不论是直播和回放，以及推流和拉流代理，还有下载只要推的流都会进行录制，请大佬进行 分别改写这三种模式的不同app应用名，便于区分

**Comment by sxh-netizen** [comment]
还有nvr录像下载的时候会受无人观看事件，关闭

**Comment by 648540858** [comment]
好的 我处理下

**Comment by cs1991** [comment]
现在的下载是通过录制mp4的方式实现的吗？ 是不是录像下载的耗时和视频长度的一样？

**Comment by 648540858** [comment]
是的，开启下载->设备推流->zlm录像

**Comment by 648540858** [comment]
> 当开启录制后，不论是直播和回放，以及推流和拉流代理，还有下载只要推的流都会进行录制，请大佬进行 分别改写这三种模式的不同app应用名，便于区分

app名不能区分，这是来自zlm的规则，目前对录像进行了记录保证录像不被中断，并在推流hook中做了判断，回放则不录像

**Comment by sxh-netizen** [comment]
好的

**Comment by dangzhenjiuhao** [comment]
怎样关闭非国标设备的推流录像，目前设置了record-push-live: false，好像不管用

**Comment by 648540858** [comment]
record-push-live: false

**Comment by dangzhenjiuhao** [comment]
已经设置了record-push-live: false，但是还是出现了录像
![image](https://github.com/648540858/wvp-GB28181-pro/assets/22176271/24fc38fc-f604-4ac7-936c-8c552511524e)

**Comment by 648540858** [comment]
关闭国标录像是&nbsp;&nbsp;record-sip: false

**Comment by dangzhenjiuhao** [comment]
想开启国标推流录像，关闭非国标设备的推流录像，但是设置了record-push-live: false后不管用，非国标设备的推流还是录像了

**Comment by 648540858** [comment]
你截图的都是国标的，app 为rtp都是国标的

**Comment by dangzhenjiuhao** [comment]
rtp都归类为国标？那非国标的用什么名称？
