### ISSUE TITLE
预置位查询接口报超时错误

### ISSUE THREAD

**Issue by yuklcool** [648540858/wvp-GB28181-pro#247]
描述错误
最新版本代码，查询预置位时报超时

如何复现
调用预置位查询接口

预期行为
能够查询预置位

问题排查
排查中发现
问题1：接口“/preset/query/{deviceId}/{channelId}”中，始终走不到发送指令接口中，请看截图2中的代码逻辑貌似有问题。
问题2：当修改平台代码使其能够正常发送查询预置位指令到设备并且设备能够回复查询预置位的数据，但是wvp中缺少了对回复消息类型PresetQuery的解析，上个版本中有对此消息类型解析，还请大佬添加。

截图1
![image](https://user-images.githubusercontent.com/15844128/143546130-d707c61e-d202-45e6-b2d5-5180b8b61529.png)
截图2
![image](https://user-images.githubusercontent.com/15844128/144011907-2241f8ad-1b71-4b3a-82ab-0b8affda99b2.png)
截图3
![image](https://user-images.githubusercontent.com/15844128/144007363-4c3ebb0a-d40b-468d-8fd9-df27ee79648f.png)

**Comment by szy833** [comment]
put应该放在下面

**Comment by 648540858** [comment]
已修复
