### ISSUE TITLE
请问如何使用历史媒体下载API下载我需要的一段视频

### ISSUE THREAD

**Issue by lichuangcheng** [648540858/wvp-GB28181-pro#248]
我正在尝试通过下载历史媒体的API `/api/download/start/{deviceId}/{channelId}` 下载某一段时间内的视频，但他总是给我返回错误或失败
我确定通道ID及设备ID是存在的，并且尝试过大部分可点播且有云端录像的通道，他们无一例外都失败了
我不确定开始时间及结束时间的格式是否正确

以及，我是否还有其他没注意到的地方吗

这是其中一种报错截图，另一个经常返回的错误是“回放失败， 错误码： 400, Bad Request”
![image](https://user-images.githubusercontent.com/54461363/143551750-97632f23-642a-453c-b1c8-dce57e46e40e.png)

我使用的版本是 dockerhub 上目前的最新版本

感谢！！！

**Comment by 648540858** [comment]
docker镜像尚未更新，建议你使用代码编译测试
