### ISSUE TITLE
28181设备注册平台后无法获取通道

### ISSUE THREAD

**Issue by MirrorCY** [648540858/wvp-GB28181-pro#251]
2021-11-29 15:23:17.441  INFO 10020 --- [vp-sip-handle-2] c.g.i.v.g.auth.RegisterLogicHandler      : [34020000001320000009] 首次注册，查询设备信息以及通道信息
java.text.ParseException: sip:44010200492000000001@:5060: Missing host name

**Comment by MirrorCY** [comment]
2021-11-29 15:30:45.553 DEBUG 10020 --- [io-18080-exec-8] c.g.i.v.v.gb28181.device.DeviceQuery     : 设备通道信息同步API调用，deviceId：34020000001320000009
java.text.ParseException: sip:44010200492000000001@:5060: Missing host name
......
2021-11-29 15:31:01.440  WARN 10020 --- [io-18080-exec-1] c.g.i.v.v.gb28181.device.DeviceQuery     : 设备通道信息同步超时

摄像机注册和刷新通道数时报错如上，可以看到摄像头注册成功但是通道数显示0，windows平台公网部署，已关闭防火墙并开放安全组。

**Comment by MirrorCY** [comment]
部署方式 wvp-pro + zlm都是编译部署
部署环境 windows
端口开放情况 全端口开放
是否是公网部署 是
是否使用https 否
方便的话提供下使用的设备品牌或平台 海康威视
你做过哪些尝试：
已更新至最新代码，完全重置摄像头，创建全新云服务器部署，均未能解决

**Comment by 648540858** [comment]
贴一下你的sip配置信息

**Comment by MirrorCY** [comment]
感谢回复

sip:
    # [必须修改] 本机的IP
    ip: （此处隐去公网IP）
    # [可选] 28181服务监听的端口
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 4401020049
    # [可选]
    id: 44010200492000000001
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: admin123

**Comment by 648540858** [comment]
请发送cap/pcap的抓包，一般使用wirshark/tcpdump抓包

**Comment by MirrorCY** [comment]
已抓取pcap格式包




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro] 28181设备注册平台后无法获取通道 (Issue #251)





 
请发送cap/pcap的抓包，一般使用wirshark/tcpdump抓包
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiaxiaolong** [comment]
同学你好 你的问题解决没，我下载下来编译部署也是报同样的问题 ，报“Missing host name” 通道数为0，不知道哪里配置有问题。可否指导指导

**Comment by pz1026** [comment]
我们也出现了同样的问题，最后发现是服务器端口仅开放了TCP，没开放UDP造成的。供参考

**Comment by MirrorCY** [comment]
我这边应该都打开了，因为是开发环境没有关键资料嘛，所以没有任何限制防火墙也关了安全组也全部放通，看报错感觉是内部解析的问题，我换到上个月的Commits编译后不报这个错误了，可以看见通道，但是取流失败。主要是不会Java没法做出什么贡献，实属惭愧。

**Comment by pz1026** [comment]
我们之前取流失败，是因为流媒体服务器配置成了127.0.0.1，应该配置为内网IP。可以使用wireshark抓包工具看一下摄像机与wvp服务之前的请求。

**Comment by 648540858** [comment]
> 已抓取pcap格式包
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "648540858/wvp-GB28181-pro" ***@***.***&gt;; 发送时间:&nbsp;2021年11月30日(星期二) 上午10:29 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [648540858/wvp-GB28181-pro] 28181设备注册平台后无法获取通道 (Issue #251) 请发送cap/pcap的抓包，一般使用wirshark/tcpdump抓包 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你的包发送了吗我没收到呀

**Comment by winip1230** [comment]
@MirrorCY 我这边遇到了同样的问题，漏掉了配置文件中的sip ip配置

**Comment by winip1230** [comment]
@MirrorCY 我这边遇到了同样的问题，漏掉了配置文件中的sip ip配置我这边用的是92.168.124.74，添加后就可以了，可以试下是否能解决你的问题。sip:
# [必须修改] 本机的IP
ip: 192.168.124.74
# [可选] 28181服务监听的端口
port: 5060

**Comment by MirrorCY** [comment]
修改media.ip为公网IP解决了
