### ISSUE TITLE
nvr录像回放 功能放置几分钟后进度条无法拖拽

### ISSUE THREAD

**Issue by maxxiao** [648540858/wvp-GB28181-pro#252]
部署方式： wvp-pro  编译 +  zlm(docker) 
部署环境：  centos 
端口开放情况： http开放
是否是公网部署： 是
是否使用https“： 否
设备品牌： 大华NVR
尝试： 反复测试均出现，为git上最新代码

debug信息如下
![image](https://user-images.githubusercontent.com/16176464/143856027-48c3af55-5d7a-493e-953d-7014746fb8e1.png)

后台有报错信息如下
![image](https://user-images.githubusercontent.com/16176464/143827383-3d3a1f03-2522-483b-ba84-65a2c861824d.png)

**Comment by 648540858** [comment]
好的 我排查下

**Comment by 648540858** [comment]
你放置后视频还在播放吗

**Comment by maxxiao** [comment]
正常播放的

**Comment by 648540858** [comment]
你可以再测试试试，我添加了对空指针的处理。
