### ISSUE TITLE
更新最新的代码后，设备信息和状态正常，点播超时

### ISSUE THREAD

**Issue by RlonLL11FE** [648540858/wvp-GB28181-pro#253]
![image](https://user-images.githubusercontent.com/12453254/143836998-bb04420e-e71d-4288-b43e-d465bbc7ebf5.png)
以前的版本正常，更新了最新的代码以后，试了海康和大华的摄像机，都能正常注册上来，单是都点播超时
关键的配置都是正常的，sip.ip也正确配置了

**Comment by RlonLL11FE** [comment]
点播创建的RTP接收端口试了试也能正常访问，但是没收到摄像机推流，等了一会儿就超时了
![image](https://user-images.githubusercontent.com/12453254/143838565-93de9504-4552-44fb-b719-bdb5a40ab45b.png)

**Comment by 648540858** [comment]
请根据提问规范，补充下信息，我先关了

**Comment by bigff-0527** [comment]
请问解决了吗，我也遇到这个问题
