### ISSUE TITLE
windows 部署编译的wvp-pro和ZLM，摄像机信息能正常注册，点播提示“收流超时，请稍候重试”

### ISSUE THREAD

**Issue by RlonLL11FE** [648540858/wvp-GB28181-pro#255]
**描述错误**
最新版本代码，项目配置正常，摄像机信息也都正常注册到了平台上，但是点击点播一直转圈圈，过了一会儿提示“收流超时，请稍候重试。”
**如何复现**
我的环境多次重启也不行，清了重新编译，依然有问题
**预期行为**
点击点播能正常播放

**截图**
这是从点击点播到返回超时的两段日志
![image](https://user-images.githubusercontent.com/12453254/143849887-ad3870dc-226e-4203-b47c-0dec18fbbb17.png)

**环境信息:**
 - 1. 编译wvp-pro/ wvp-prp + zlm都是编译部署
 - 2. 部署环境 windows
 - 3. 用到的端口都是开放的，防火墙也关闭了
 - 4. 内网部署在同一台WindowPC上
 - 5. 没有用https
 - 6. 摄像机品牌：大华，都试了海康
 - 7. 开始以为是设备的问题，换了设备依然不行。清了redis和mysql数据库重试也不行。

**Comment by 648540858** [comment]
节点管理打开编辑界面截个图看看

**Comment by RlonLL11FE** [comment]
节点配置的截图
![image](https://user-images.githubusercontent.com/12453254/143975062-b78a9a78-f1c3-4c01-9412-d881ab0d3208.png)

**Comment by pz1026** [comment]
同问，麻烦有解决方案了同步一下，非常感谢。邮箱：pz_1026@163.com

**Comment by RlonLL11FE** [comment]
> 同问，麻烦有解决方案了同步一下，非常感谢。邮箱：[pz_1026@163.com](mailto:pz_1026@163.com)

尝试了几次，还没找到问题出在哪儿，目前还没有找到办法。。。

**Comment by pz1026** [comment]
我们的问题解决了，zlm的服务ip不能写127.0.0.1，应该使用内网IP，如果配置的是内网IP，也可能是代码不是从配置文件获取的，而是从库里获取的，wireshark抓包工具看一下摄像机与wvp服务之前的请求。

**Comment by 648540858** [comment]
> > 同问，麻烦有解决方案了同步一下，非常感谢。邮箱：[pz_1026@163.com](mailto:pz_1026@163.com)
> 
> 尝试了几次，还没找到问题出在哪儿，目前还没有找到办法。。。

我没看出有什么问题，可以抓个包看一下

**Comment by RlonLL11FE** [comment]
今天试了试，点播推流了，但是只推了十几秒就停了，播放接口也没掉成功，抓包看了一下，看数据发送数据也没什么异常。
![image](https://user-images.githubusercontent.com/12453254/145008183-38d2a13a-59e0-4734-8280-4227b079629c.png)

**Comment by 648540858** [comment]
> 今天试了试，点播推流了，但是只推了十几秒就停了，播放接口也没掉成功，抓包看了一下，看数据发送数据也没什么异常。 ![image](https://user-images.githubusercontent.com/12453254/145008183-38d2a13a-59e0-4734-8280-4227b079629c.png)

你是30000-30500端口都打开了。一般一段时间就停的多半是rtcp没通，设备主动听了流

**Comment by dute7liang** [comment]
没后续了么？

**Comment by 648540858** [comment]
先关了，有问题再打开吧

**Comment by 351768593** [comment]
> 我们的问题解决了，zlm的服务ip不能写127.0.0.1，应该使用内网IP，如果配置的是内网IP，也可能是代码不是从配置文件获取的，而是从库里获取的，wireshark抓包工具看一下摄像机与wvp服务之前的请求。

解决方案可用, 将 `media.ip` 配置项从 `localhost` 改为内网 IP 之后可以在 wvp-pro 内正常查看摄像头实时画面了.
