### ISSUE TITLE
程序无法获取WVP_CONFIG变量问题

### ISSUE THREAD

**Issue by lnr9483** [648540858/wvp-GB28181-pro#256]
**描述错误**
容器内已经得到WVP_CONFIG变量，程序web页面显示还是以前的参数

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 部署方式 (docker) 
 - 2. 部署环境  centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
好的 我排查下

**Comment by 648540858** [comment]
你可以使用新的代码试试

**Comment by tjz101** [comment]
我也有这个问题，是run.sh脚本不兼容。我这样解决的：进入docker容器，将/opt/wvp/run.sh 复制出来，放到本地，修改run.sh后从本地挂载这个文件。

**Comment by SaltFish001** [comment]
> 我也有这个问题，是run.sh脚本不兼容。我这样解决的：进入docker容器，将/opt/wvp/run.sh 复制出来，放到本地，修改run.sh后从本地挂载这个文件。

@tjz101 能麻烦你说下怎么处理run.sh吗, 我现在也是这问题, WVP_CONFIG不生效, 我使用的Docker Hub的镜像

**Comment by tjz101** [comment]
> 



> > 我也有这个问题，是run.sh脚本不兼容。我这样解决的：进入docker容器，将/opt/wvp/run.sh 复制出来，放到本地，修改run.sh后从本地挂载这个文件。
> 
> @tjz101 能麻烦你说下怎么处理run.sh吗, 我现在也是这问题, WVP_CONFIG不生效, 我使用的Docker Hub的镜像

我将run.sh复制到了外部，然后映射到容器里面去。 然后run.sh做了精简。就保留了java -jar 这一句。你可以参考下
`#!/bin/bash
java -jar wvp-pro-2.0.jar --spring.config.location=./config/application.yml --media.record-assist-port=18081 --media.ip=${MEDIA_HOST} --media.http-port=6080 --media.hook-ip=${MEDIA_HOST} --media.sdp-ip=${MEDIA_HOST} --sip.ip=${WVP_HOST} --media.stream-ip=${WVP_HOST} --sip.password=${SIP_PASSWORD}`

**Comment by SaltFish001** [comment]
> > 
> 
> > > 我也有这个问题，是run.sh脚本不兼容。我这样解决的：进入docker容器，将/opt/wvp/run.sh 复制出来，放到本地，修改run.sh后从本地挂载这个文件。
> > 
> > 
> > @tjz101 能麻烦你说下怎么处理run.sh吗, 我现在也是这问题, WVP_CONFIG不生效, 我使用的Docker Hub的镜像
> 
> 我将run.sh复制到了外部，然后映射到容器里面去。 然后run.sh做了精简。就保留了java -jar 这一句。你可以参考下
> 
> ```
> #!/bin/bash
> java -jar wvp-pro-2.0.jar --spring.config.location=./config/application.yml --media.record-assist-port=18081 --media.ip=${MEDIA_HOST} --media.http-port=6080 --media.hook-ip=${MEDIA_HOST} --media.sdp-ip=${MEDIA_HOST} --sip.ip=${WVP_HOST} --media.stream-ip=${WVP_HOST} --sip.password=${SIP_PASSWORD}
> ```

谢谢
