### ISSUE TITLE
【国标级联】模块无法使用【拉流代理】的RTMP视频流，上级平台反馈「只有通道信息，没有设备信息」

### ISSUE THREAD

**Issue by aslily1234** [648540858/wvp-GB28181-pro#257]
**描述错误**
将WVP-pro在公网服务器A通过docker方式部署之后，在同一台服务器A上门搭建了RTMP服务，并且配置了【拉流代理】，成功播放
![image](https://user-images.githubusercontent.com/8610207/143980342-e154d8af-8b27-433a-a4dc-0600b8797384.png)
![image](https://user-images.githubusercontent.com/8610207/143980384-6bf15ac7-a62b-4dcf-9584-0e4fe62df05a.png)

但是【国标级联】模块无法使用【拉流代理】的RTMP视频流，上级平台反馈「只有通道信息，没有设备信息」
![image](https://user-images.githubusercontent.com/8610207/143980442-7dba83bc-167b-48bf-8093-b6559c073709.png)

**如何复现**
1、搭建RTMP服务器
这里我直接使用 tiangolo/nginx-rtmp 来搭建 rtmp 服务器。
sudo docker pull tiangolo/nginx-rtmp
等下载完成之后就可以启动这个镜像
sudo docker run -d -p 1935:1935 --name nginx-rtmp tiangolo/nginx-rtmp
然后就可以直接使用 OBS 推流了。在推流的地址上填写 rtmp://你电脑的 ip 地址/live，密钥随便填写。然后可以开始传流了。

2、在【拉流代理】上配置RTMP视频流
![image](https://user-images.githubusercontent.com/8610207/143980880-12bbb4a3-62e4-4b14-8088-0539c2f2d62c.png)

3、在【国标级联】上选择通道，勾选【拉流代理】对应的视频流
![image](https://user-images.githubusercontent.com/8610207/143980926-6cd91dad-e4ee-45c3-b7ee-a1e0ff2798f4.png)

4、在上级平台查看是否收到视频流

**预期行为**
能够在上级平台查看对应的视频流

**截图**

**环境信息:**
 - 1. 部署方式  参考 https://hub.docker.com/r/648540858/wvp_pro  直接用docker部署的
 - 2. 部署环境  centos
 - 3. 端口开放情况 （对应端口全部开放了）
 -
![image](https://user-images.githubusercontent.com/8610207/143981149-6edf134a-0e1a-44e7-8ff3-54c307476bce.png)
 - 4. 是否是公网部署（阿里云上部署）

 - 5. 是否使用https（否）
 - 6. 方便的话提供下使用的设备品牌或平台（上级平台是电信视觉智联平台）
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
只有设备信息，没有通道我理解，反过来我就不懂了。你添加的级联平台就是设备，rtmp流就是通道

**Comment by 648540858** [comment]
我先关了，你跟他们沟通好了再继续沟通
