### ISSUE TITLE
国标级联上下级状态不一致问题。

### ISSUE THREAD

**Issue by szy833** [648540858/wvp-GB28181-pro#261]
**描述错误**
用的11月底的版本。国标级联后，如果下级平台有设备离线。上级平台的设备状态不会改变。依然在线

**如何复现**
添加上级节点后，下级平台设备离线。刷新显示设备已离线。上级平台刷新后。依然在线。

**预期行为**
上级平台也应该离线

**问题原因**
设备离线时，OfflineEventListener里只对device表中离线状态进行了修改。device_channel表中未修改。导致上级平台获取设备信息时，状态依然是离线。

**尝试**
离线时。更新了device中的online字段的同时，更新device_channel表中status状态

**Comment by 648540858** [comment]
请更新版本测试

**Comment by 648540858** [comment]
不对旧的版本进行排查，忙不过来。
