### ISSUE TITLE
国标级联，上级平台重复添加问题

### ISSUE THREAD

**Issue by szy833** [648540858/wvp-GB28181-pro#262]
**描述错误**
可以重复添加相同上级平台，添加后，导致无法删除

**如何复现**
进入国标级联，添加上级平台。输入相同的平台信息。出现两条相同的上级平台，删除。无法删除

**预期行为**
相同上级平台只能添加一条，并且正常删除

**原因**
platformController的savePlatform方法中没有对已存在的平台id进行判断。导致重复添加。

**修改**
![image](https://user-images.githubusercontent.com/31844882/144948402-218f8c35-dfa6-4a07-a7e6-e8a6eb467a05.png)

**Comment by 648540858** [comment]
ok，我处理下

**Comment by 648540858** [comment]
已修复
