### ISSUE TITLE
注册时。国标平台id没有校验

### ISSUE THREAD

**Issue by szy833** [648540858/wvp-GB28181-pro#265]
**描述错误**
偶然发现的问题。注册平台的时候，没有比对sip的id。这样就导致，只要ip端口一致。那么随便的平台id都可以注册上。这样导致parentId不一致。不知道是不是本身就这样设计的。

**如何复现**
1. 假设上级平台id是1，ip: 1.2.3.4:5060。
2. 下级摄像头平台对接的时候把SIP服务器id设置为2。ip:1.2.3.4:5060
3. 注册后。上级channel表里parentId 就变成2。
**预期行为**
parentId 是不是应该是1？

**截图**
![image](https://user-images.githubusercontent.com/31844882/145208116-c1cec9f9-e0d9-4b66-9627-0770a103c70a.png)

**Comment by 648540858** [comment]
是的，确实没有，IP端口也是可以作为一个唯一性的东西去理解的，所以这块就没有过多的限制，除非是ip频繁变化的设备，不然是不需要考虑这个。
