### ISSUE TITLE
能执行刷新操作(提示成功)，但是一点播就超时，卡在回复ack上

### ISSUE THREAD

**Issue by xiaoweipeng** [648540858/wvp-GB28181-pro#267]
**描述错误**
能执行刷新操作(提示成功)，但是一点播就超时，卡在回复ack上

**如何复现**
服务器是内容通过映射出来的，按道理能够注册证明已经映射成功

**预期行为**
可以正常点播

**截图**
![image](https://user-images.githubusercontent.com/54565603/145338672-69b27be2-fbc5-437a-ae09-e7cc02348e4b.png)

**docker 启动命令**
docker run  --env WVP_IP="39.170.*.*" --env WVP_DOMAIN="3301000000" --env WVP_PWD="csoi.vip"  --env WVP_DOMAIN="33010000000000000001" -it -p 18080:18080 -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp -p 8088:8088 -p 80:80 -p 5060:5060 -p 5060:5060/udp 648540858/wvp_pro

**抓包信息**
[m.zip](https://github.com/648540858/wvp-GB28181-pro/files/7682434/m.zip)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) 
 - 2. 部署环境  ubuntu
 - 3. 端口开放情况：均已完全映射
 - 4. 是否是公网部署：是（路由器映射出来）
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台  海康
 - 7. 你做过哪些尝试
 -  自己编译，或者在docker内改变参数 结果都是一致的

**Comment by xiaoweipeng** [comment]
感谢大佬抽空看一下

**Comment by 648540858** [comment]
你是自己有动筒公网IP吗，还是通过类似花生壳类型的东西实现的。

**Comment by 648540858** [comment]
zlm与wvp没在一台主机吗， 我看sdp ip是39.170.36.219，你的设备可以连上这个IP吗,可以在这个服务器抓包看下有没有rtp包。

**Comment by 648540858** [comment]
我先关了，你有新的信息再打开
