### ISSUE TITLE
获取开流rtp端口号跳跃

### ISSUE THREAD

**Issue by King-Run** [648540858/wvp-GB28181-pro#268]
`        int currentPort = mediaServerItem.getCurrentPort();
        if (currentPort == 0) {
            String[] portRangeStrArray = mediaServerItem.getRtpPortRange().split(",");
            portRangeArray[0] = Integer.parseInt(portRangeStrArray[0]);
            portRangeArray[1] = Integer.parseInt(portRangeStrArray[1]);
        }

        if (currentPort == 0 || currentPort++ > portRangeArray[1]) {
            currentPort = portRangeArray[0];
            mediaServerItem.setCurrentPort(currentPort);
            return portRangeArray[0];
        } else {

//            if (currentPort % 2 == 1) {
//                currentPort++;
//            }
//            currentPort++;
            mediaServerItem.setCurrentPort(currentPort);
            return currentPort;
        }`

注释掉的代码会使端口号从30001跳到30003

**Comment by 648540858** [comment]
有意为之。30002是用来给rtcp保活的，建议你还原代码。
