### ISSUE TITLE
录像合并之后下载链接错误

### ISSUE THREAD

**Issue by brokge** [648540858/wvp-GB28181-pro#269]
**描述错误**
录像合并下载路径找不到，

应该是后端生成 download.html文件路径的逻辑 和 前端没有对应上。

**如何复现**
选择视频合并下载，然后下载合并完成的视频

**预期行为**

您访问的资源不存在！download.html 不在 record 目录下。

**截图**

![image](https://user-images.githubusercontent.com/3824000/145557829-8d8d66e1-44e5-4e0a-8312-b358f2504c44.png)

cloudRecordDetail.vue

![image](https://user-images.githubusercontent.com/3824000/145558855-cb8bc56a-0919-47d8-8045-ed087083d243.png)

mvp-pro-assist 项目 VideoFileService.java
![image](https://user-images.githubusercontent.com/3824000/145558812-1c0088a6-04c8-4483-93f4-afbd17a97d90.png)

**环境信息:**

**Comment by 648540858** [comment]
好的 我修改下

**Comment by 648540858** [comment]
已修复
