### ISSUE TITLE
timeout，抓包已上传

### ISSUE THREAD

**Issue by reachzxsframe** [648540858/wvp-GB28181-pro#27]
[timeout.zip](https://github.com/648540858/wvp-GB28181-pro/files/5774299/timeout.zip)

**Comment by reachzxsframe** [comment]
代码是上周更新过的，请问大佬最近有修复这个问题吗？

**Comment by Erically** [comment]
播放timeout？

**Comment by 648540858** [comment]
更新下代码， 最新的代码解决了一个问题和这个有关。 同时确认你的wvp可以链接到zlm。

**Comment by 648540858** [comment]
```
o=11010254001310005403 0 0 IN IP4 null 
```
sdp里最后应该是一个zlm的ip，而不应该是null

**Comment by 648540858** [comment]
我先关闭了， 你有问题再打开。
