### ISSUE TITLE
点播和录像文件播放一段时间出现跳帧

### ISSUE THREAD

**Issue by XinZhiLing** [648540858/wvp-GB28181-pro#270]
部署信息：
1.wvp-pro/ wvp-prp + zlm都是编译部署。
2.部署环境：Ubuntu18.04
3.端口开放情况是采用的默认值。
4.局域网部署的。
5.测试的设备是nvr，是我自己开发的，目前处于开发阶段。

问题详细描述：
点播和录像文件，在播放一段时间，大概10分钟以内，就会出现跳帧现象，我的nvr推的视频流是带时间水印的，从跳的时间看刚好是2s，也就是播放几分钟之后，从播放的视频上的时间水印看，就2s跳一下，再结合我nvr编码信息，GOP是40，fps是20，所以我认为是播放一段时间之后，就只播放 I帧 了，不知道猜测的对不对。
出现跳帧之后，以点播为例，出现问题之后，点击暂停播放（nvr设备国标推流部分没有收到信息，所以认为这个暂停，只是服务端的处理，并没有将命令发给我的nvr设备进行一些处理），然后再次点播放，就又播放正常了，当然还是播放一会再次出现问题。这里的播放和暂停都不是通道列表那的播放，下面是截图：
![image](https://user-images.githubusercontent.com/6697072/145926487-f2dcffef-8e58-4e09-860c-c3fecc5483f3.png)
如上图，出现跳帧问题，点截图左下角的按钮，然后再点一次会正常播放。

一些尝试和分析：
1.我的nvr目前处理是将ipc拉到的视频流进行了解码和重新编码的处理，所以我进行了对比测试，就是将ipc拉到的视频流不进行解码和再次编码，而是用我国标接口直接推流出去，这个时候不会出现跳帧问题。并且在出现问题的时候抓包看了，推的流并不只是I帧。 -----   分析：我的重新编码部分有某个参数配置的不对，导致推流之后，播放一会出现问题，具体地方暂时也没查到。

2.我的nvr对ipc拉到的视频流进行解码和重新编码的处理，但是国标推流不是推到wvp，而是推到livegbs（一个国标试用软件），这个时候，发现点播播放很久都没事。

麻烦大佬指点一下。谢谢

**Comment by 648540858** [comment]
是的，你的猜测之前有人说过，这个播放器为保证播放效率，会出现只播放I帧的情况，目前没有很好的办法，只能等待升级播放器了。

**Comment by 648540858** [comment]
liveGBS用的是他们的播放器LIVEPLAYER，这个不支持H265，所以咱们没有使用。你如果只使用h264，那你也可以使用这个播放器，会稳定很多。需要修改代码

**Comment by XinZhiLing** [comment]
> 是的，你的猜测之前有人说过，这个播放器为保证播放效率，会出现只播放I帧的情况，目前没有很好的办法，只能等待升级播放器了。

感谢回复。请问这种情况是什么原因导致播放器会只播放I帧呢？不知道我的编码部分是否配置某个参数，可以让播放器不触发这种情况？因为原始视频流如果我不解码然后编码的情况下，用同样的国标推流代码推到zlm+wvp是可以正常播放的。而且我出现问题的情况，也是正常播放一段时间之后才会出现，不是从一开始就出现的。所以怀疑我的编码部分有不规范的地方，只是目前没啥头绪。

**Comment by 648540858** [comment]
你可以把zlm的覆盖时间戳功能打开试试，其他的我也没什么头绪

**Comment by XinZhiLing** [comment]
多谢解答，我去试一下，然后再研究下我的编码部分
