### ISSUE TITLE
海康NVR回放无法拖动和倍速

### ISSUE THREAD

**Issue by zlklink** [648540858/wvp-GB28181-pro#277]
**描述错误**
海康NVR回放无法拖动和倍速

**如何复现**
接入海康NVR，视频回放

**预期行为**
可以倍速播放，可以拖动播放

![image](https://user-images.githubusercontent.com/39792244/146363169-28f25438-1b2f-402f-a30b-60978c76461d.png)

**环境信息:**
 - 1. 部署方式  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows
 - 3. 端口开放情况  内网都开放
 - 4. 是否是公网部署  否
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台  海康NVR: DS-8860NBS
 - 7. 你做过哪些尝试  没有

**Comment by 648540858** [comment]
不是所有设备都把国标实现的很完整的，具体的还得看设备，你可以咨询设备厂家

**Comment by 648540858** [comment]
我先关了，你跟厂家确认了再沟通
