### ISSUE TITLE
[技术咨询]  级联问题

### ISSUE THREAD

**Issue by ypy31393936** [648540858/wvp-GB28181-pro#279]
部署方式    ZL+WVP  编译

部署环境    windows 

端口开放情况  正常

是否是公网部署  否

是否使用https  否 

方便的话提供下使用的设备品牌或平台  海康   大华

级联添加平台成功后，找不到已经注册上来的摄像头。设备列表中有海康ipc和大华ipc，且可以正常观看。但级联添加成功后上级平台

里没有通道。请问是还要配置哪里吗，或者说我的操作在哪里出了问题。

**Comment by ypy31393936** [comment]
找到原因了  测试的设备太少   而且查找通道默认的currentPage是0   导致底下切换不了  出现了这个问题

**Comment by 648540858** [comment]
已经修复
