### ISSUE TITLE
拉流代理一直在加载，不播放

### ISSUE THREAD

**Issue by ernao2** [648540858/wvp-GB28181-pro#283]
<img width="938" alt="问题" src="https://user-images.githubusercontent.com/85091905/147221656-322b7488-8c45-46a9-aa40-de17460eac36.png">
<img width="958" alt="问题1" src="https://user-images.githubusercontent.com/85091905/147221683-6f7322f9-df10-4a6d-88d3-5ff9a7d6fe0a.png">

**Comment by 648540858** [comment]
不符合提问规范
