### ISSUE TITLE
录像查询回放功能 尝试2个回放之后可以正常回放  在进行尝试回放之后便没办法无法回放

### ISSUE THREAD

**Issue by ernao2** [648540858/wvp-GB28181-pro#285]
**描述错误**
录像查询回放功能 尝试2个回放之后可以正常回放  在进行尝试回放之后便没办法无法回放

**如何复现**
录像查询进行几次回放  在进行回放 就没办法回放

**预期行为**
正常回放

**截图**
<img width="954" alt="日志" src="https://user-images.githubusercontent.com/85091905/147326285-af60ae8f-f444-4cb4-afaa-49af5ca19a77.png">

<img width="952" alt="zlm日志" src="https://user-images.githubusercontent.com/85091905/147326288-ba3835da-9e56-439e-b9ed-8e3e2d6d3fb0.png">

**环境信息:**
 - 1. 部署方式 wvp-pro编译 / zlm(docker) 
 - 2. 部署环境 windows 
 - 3. 开放
 - 4. 是公网部署
 - 5. 使用https
 - 6. 海康
 - 7. 重启几次项目遇见同样问题

**Comment by 648540858** [comment]
建议你重启项目前关闭回放再重启，要不就重启你的nvr

**Comment by ernao2** [comment]
嗯嗯好的谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月27日(星期一) 上午9:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [648540858/wvp-GB28181-pro] 录像查询回放功能 尝试2个回放之后可以正常回放  在进行尝试回放之后便没办法无法回放 (Issue #285)





 
建议你重启项目前关闭回放再重启，要不就重启你的nvr
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
