### ISSUE TITLE
【优化】拉流代理在ZLM服务重启后需要停用再启用才能有效

### ISSUE THREAD

**Issue by ydwxb** [648540858/wvp-GB28181-pro#288]
**描述错误**
使用拉流代理添加了视频流，正常预览。但重启ZLM服务器后，会在ZLM提示 连接超时，只有把拉流代理停用后再启用才能正常预览。

**如何复现**
添加拉流代理→重启ZLM服务→预览拉流视频。

**预期行为**
ZLM服务重启后，拉流可正常访问。或重启服务后，自动重新启用拉流代理。

**截图**

**环境信息:**
 - 1. 部署方式wvp-pro + zlm都是编译部署
 - 2. 部署环境 centos7.9
 - 3. 端口开放情况：全部开放
 - 4. 是否是公网部署：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：海康威视

**Comment by 648540858** [comment]
好的

**Comment by 648540858** [comment]
已实现
