### ISSUE TITLE
获取设备录像时xml解析错误

### ISSUE THREAD

**Issue by nocny-x** [648540858/wvp-GB28181-pro#291]
**描述错误**
海康摄像头在获取设备录像时间跨度超过12小时以上会出现xml解析错误，导致录像列表获取不全。

**如何复现**
postman请求录像查询接口/api/gb_record/query/{deviceId}/{channelId}，如下图：
![image](https://user-images.githubusercontent.com/2148796/147528530-31ca926c-7a79-4771-acb9-9a0f98d29cab.png)

**预期行为**
正确返回设备录像列表

**截图**
日志及抓包截图：
![MO~ 3IB8RC6(IGU6G5C}R}H](https://user-images.githubusercontent.com/2148796/147528665-344eb70c-4dad-45ca-af93-ff86d7a13ff4.png)
错误日志附件：
[gb_record_error.log](https://github.com/648540858/wvp-GB28181-pro/files/7782790/gb_record_error.log)
wireshark抓包附件：
[gb_record_wireshark_cap.zip](https://github.com/648540858/wvp-GB28181-pro/files/7782795/gb_record_wireshark_cap.zip)
摄像头接入配置：
![image](https://user-images.githubusercontent.com/2148796/147529129-8e4f9d5b-6c09-41a7-b3ac-076ea6e3e8a9.png)

**环境信息:**
 - 1. 部署方式
      wvp打包成jar运行，zlm编译部署。
 - 2. 部署环境
      wvp：windows+jre8
      zlm: CentOS 7.9
 - 3. 端口开放情况
       所有端口均为默认端口
 - 4. 是否是公网部署
       否
 - 5. 是否使用https
       否
 - 6. 方便的话提供下使用的设备品牌或平台
       设备品牌：海康威视
       型号：DS-2CD7027FWD/HFE-L
       主控版本：V5.5.81 build 180910
 - 7. 你做过哪些尝试
       国标协议版本2011和2016都试过，均会出现上述问题。

**Comment by 648540858** [comment]
设备xml格式有问题

**Comment by nocny-x** [comment]
@648540858 ![1da5b8f1176665f8671a3d7c407f450](https://user-images.githubusercontent.com/2148796/148538761-6e46dcb8-e9eb-4dc5-a414-e232328eb278.jpg)

**Comment by 648540858** [comment]
已修复为xml异常时回复400
