### ISSUE TITLE
docker 部署 获取不到sqlite

### ISSUE THREAD

**Issue by Apollo666** [648540858/wvp-GB28181-pro#292]
**描述错误**
我是用docker 启动的，数据已经获取到了。我想连接到sqlite,可是在docker 环境里找不到 wvp.sqlite文件

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by openmynet** [comment]
sqlite 文件已经被打包在jar文件里面了，部署时需要将sqlite文件取出，
```bash
# ./wvp.db 位于仓库中/src/main/resources/wvp.db
docker run  --env WVP_IP="你的IP" -e SPRING_DATASOURCE_URL="jdbc:sqlite:/sqlite/database.db" -v ./wvp.db:/sqlite/database.db -it -p 18080:18080 -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp -p 80:80 -p 5060:5060 -p 5060:5060/udp 648540858/wvp_pro
```

**Comment by 648540858** [comment]
有同时使用数据上的需要的话，建议使用mysql，sqlite的并发写能力很差，如果你的工具在写入会导致你的wvp服务无法写入，导致不可预知的后果。
