### ISSUE TITLE
海康nvr添加rtsp流摄像头黑屏

### ISSUE THREAD

**Issue by wangbinxu** [648540858/wvp-GB28181-pro#293]
海康nvr添加rtsp流摄像头，在平台上有信息，但是播放失败，一直黑屏

**环境信息:**
 - 1. 部署方式 wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows 
 - 3. 端口开放
 - 4. 否
 - 5. 未使用https
 - 6. 海康nvr和dlink的摄像头

**Comment by 648540858** [comment]
rtsp地址单独拿出来可以播放吗？如果可以就看看这个流的编码信息，可能网页播放器不支持这个编码信息，
编码信息可以在播放的时候打开vlc->工具->编解码器信息

**Comment by 648540858** [comment]
先关了，你有问题再打开
