### ISSUE TITLE
“收流超时”疑问 

### ISSUE THREAD

**Issue by shybrat** [648540858/wvp-GB28181-pro#296]
1、wvp-pro docker/ zlm docker
2、windows server 2019 内网IP 192.168.1.123 公网IP 114.64.251.39
3、服务器防火墙关闭，公网映射了18080,5060-5070,30000-30500（media/config.ini 的http port 改成了5061）
4、公网
5、未使用https
6、海康威视,摄像头连接的4G路由器，与服务器不在同一内网
7、media.stream-ip 设置为公网IP,   
  sip.ip media.ip media.hook-ip 设置为127.0.0.1 ，192.168.1.123，公网IP 都做过尝试 

问题：
1、设备正常在线，通道拉取没问题，播放提示 “收流超时，请稍候重试”
wvp日志 

> 2021-12-31 16:52:34.531 DEBUG 11 --- [io-18080-exec-5] c.g.i.v.v.gb28181.device.DeviceQuery     : 设备通道信息同步API调用，deviceId：34020000001320000001
> 2021-12-31 16:52:38.621  INFO 11 --- [o-18080-exec-10] c.g.i.v.g.t.cmd.impl.SIPCommander        : 34020000001320000001_34020000001320000001 分配的ZLM为: V3nB37VEhZPOGChf [114.64.251.39:30003]
> 2021-12-31 16:52:38.668  INFO 11 --- [vp-sip-handle-5] .g.i.v.g.t.e.r.i.InviteResponseProcessor : 向 172.17.0.1:59704回复ack
> 2021-12-31 16:52:38.762  INFO 11 --- [vp-sip-handle-2] c.g.i.v.g.t.e.r.i.ByeRequestProcessor    : 收到bye, [34020000001320000001/44010200492000000001]
> 2021-12-31 16:52:56.648  WARN 11 --- [io-18080-exec-7] c.g.i.vmp.service.impl.PlayServiceImpl   : 设备点播超时，deviceId：34020000001320000001 ，channelId：34020000001320000001
> javax.sip.SipException: Cannot find listening point for transport TCP
> at gov.nist.javax.sip.stack.SIPDialog.createRequest(SIPDialog.java:2472)
> 

zlm日志
>  request:
> POST /index/api/listRtpServer
>  header:
> Accept-Encoding : gzip
> Connection : Keep-Alive
> Content-Length : 43
> Content-Type : application/x-www-form-urlencoded
> Host : 114.64.251.39:5061
> User-Agent : okhttp/4.9.0
>  content:
> secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
> response:
> {
>    "code" : 0
> }
> 
> 
> 2021-12-31 16:57:29.532 T MediaServer[19-event poller 1] HttpSession.cpp:25 HttpSession | 139649318197024(172.17.0.1:63252)
> 2021-12-31 16:57:29.536 I MediaServer[19-event poller 1] TcpServer.cpp:195 start_l | TCP Server listening on 0.0.0.0:30005
> 2021-12-31 16:57:29.536 D MediaServer[19-event poller 1] WebApi.cpp:230 http api debug |
>  request:
> POST /index/api/openRtpServer
>  header:
> Accept-Encoding : gzip
> Connection : Keep-Alive
> Content-Length : 119
> Content-Type : application/x-www-form-urlencoded
> Host : 114.64.251.39:5061
> User-Agent : okhttp/4.9.0
>  content:
> secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&port=30005&stream_id=34020000001320000001_34020000001320000001&enable_tcp=1
> response:
> {
>    "code" : 0,
>    "port" : 30005
> }
> 
> 
> 2021-12-31 16:57:44.652 W MediaServer[19-event poller 1] RtpSelector.cpp:109 onManager | RtpProcess timeout:34020000001320000001_34020000001320000001
> 2021-12-31 16:57:44.652 I MediaServer[19-event poller 1] TcpServer.cpp:36 ~TcpServer | close tcp server 0.0.0.0:30005
> 2021-12-31 16:57:44.652 W MediaServer[19-event poller 1] RtpProcess.cpp:51 ~RtpProcess | 34020000001320000001_34020000001320000001(0.0.0.0:0) RTP推流器(__defaultVhost__/rtp/34020000001320000001_34020000001320000001)断开,耗时(s):0
> 2021-12-31 16:57:45.175 T MediaServer[19-event poller 1] HttpSession.cpp:119 onError | 139649318197024(172.17.0.1:63252) session timeout
> 2021-12-31 16:57:45.175 T MediaServer[19-event poller 1] HttpSession.cpp:119 onError | 139649318189056(172.17.0.1:63248) session timeout
> 2021-12-31 16:57:45.175 T MediaServer[19-event poller 1] HttpSession.cpp:31 ~HttpSession | 139649318197024(172.17.0.1:63252)
> 2021-12-31 16:57:45.175 T MediaServer[19-event poller 1] HttpSession.cpp:31 ~HttpSession | 139649318189056(172.17.0.1:63248)
> 2021-12-31 16:57:47.697 T MediaServer[19-event poller 1] HttpSession.cpp:25 HttpSession | 139649318197024(172.17.0.1:63258)
> 2021-12-31 16:57:47.700 D MediaServer[19-event poller 1] WebApi.cpp:230 http api debug |
>  request:
> POST /index/api/closeRtpServer
>  header:
> Accept-Encoding : gzip
> Connection : Keep-Alive
> Content-Length : 95
> Content-Type : application/x-www-form-urlencoded
> Host : 114.64.251.39:5061
> User-Agent : okhttp/4.9.0
>  content:
> secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&stream_id=34020000001320000001_34020000001320000001
>  response:
> {
>    "code" : 0,
>    "hit" : 0
> }

**Comment by 648540858** [comment]
media.sdp-ip 设置为公网IP试试

**Comment by 648540858** [comment]
先关了，有问题你再开
