### ISSUE TITLE
【新功能】支持多网卡/IP的绑定

### ISSUE THREAD

**Issue by tjz101** [648540858/wvp-GB28181-pro#298]
您好！
我有这样一个场景。部分摄像头是有固定公网IP的或者是可以访问互联网的，可以通过服务器公网IP访问。另外还有一批摄像头是通过内网与服务器连接的（类似城域网这种）。
我服务器是双网卡。 当我将 sip 绑定为公网IP的时候，公网接入的设备视频播放都是正常的。我的内网设备虽然可以通过内网IP注册到平台中来，但播放视频的时候就超时了。我认为是内网设备请求点播的时候，依然走了公网IP的通道，所以导致内网设备取流超时。

**Comment by 648540858** [comment]
后续可能会有，暂时没有时间做了。暂时在做级联相关的功能。

**Comment by 648540858** [comment]
已支持
