### ISSUE TITLE
分别在Windows10和CentOS8上编译运行、jar包均会报错，ZLMediaKit、Redis、NVR信息均已配置

### ISSUE THREAD

**Issue by t0015023659** [648540858/wvp-GB28181-pro#3]
防火墙均已放行，Spring报错信息见附件
[Windows 10.txt](https://github.com/648540858/wvp-GB28181-pro/files/5580853/Windows.10.txt)
[CentOS8.txt](https://github.com/648540858/wvp-GB28181-pro/files/5580855/CentOS8.txt)

**Comment by 648540858** [comment]
请检查你的sip.ip是否为正确的本机IP;
sip.port是否存在占用的情况

**Comment by 648540858** [comment]
如果仍然无法启动,请贴一下的WVP配置信息

**Comment by t0015023659** [comment]
> 如果仍然无法启动,请贴一下的WVP配置信息
sip.ip填写为本机ip后可以启动；Redis在没有设置密码时需要将保护模式关闭

**Comment by iclearwater** [comment]
怎么解决的，我跟你的问题一摸一样，报错信息一致，在eclipse和idear都正常允许，打成jar包就不行了
