### ISSUE TITLE
docker 安装 有错误

### ISSUE THREAD

**Issue by suzaichuan** [648540858/wvp-GB28181-pro#301]
Ubuntu 18.04.1 LTS
下执行 
docker pull 648540858/wvp_pro

docker run  --env WVP_IP="192.168.4.213" -it -p 18080:18080 -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp -p 80:80 -p 5060:5060 -p 5060:5060/udp 648540858/wvp_pro
出现如下错误：

Error response from daemon: driver failed programming external connectivity on endpoint quizzical_edison (4f63b61d10f2c0184e6c135cbacc40ae151b9ac9e755b8b8880b462de95abcde): Error starting userland proxy:

再次执行可能会报错误：
docker: Error response from daemon: driver failed programming external connectivity on endpoint nice_franklin (ae4610364013180942a6633c49d54343814d31ebe02071c244b0f80e4ea834f4): Error starting userland proxy:.

**Comment by 648540858** [comment]
确认你的docker环境安装成功

**Comment by suzaichuan** [comment]
hi
 非常感谢回答 docker的环境应该是ok的，因为其他的运行是ok的 
  docker ps -a

 显示果CONTAINER ID   IMAGE               COMMAND            CREATED        STATUS        PORTS                                                                                                          NAMES
e687a69f950f   **648540858/wvp_pro**   "sh run.sh"        23 hours ago   Created                                                                                                                      quizzical_edison
51080dfa8aa6   rttys3              "/usr/sbin/init"   28 hours ago   Up 28 hours   0.0.0.0:5912-5913->5912-5913/tcp, :::5912-5913->5912-5913/tcp, 0.0.0.0:40157->40157/tcp, :::40157->40157/tcp   rttys3c
bbb42a5da75c   ubuntu              "/bin/bash"        6 days ago     Up 6 days    
BR

**Comment by 648540858** [comment]
我百度下说是可能端口映射或者防火墙问题，你看看映射的端口里有没有被占用的

**Comment by suzaichuan** [comment]
hi ,

 重新安装系统docker环境，错误一样；查看端口 就22 53 68 三个端口占用。wvp 应该不涉及这三个端口。

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      538/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3065/sshd           
tcp        0    528 192.168.4.213:22        192.168.4.60:63203      ESTABLISHED 1545/sshd: mb [priv 
tcp6       0      0 :::22                   :::*                    LISTEN      3065/sshd           
udp     6912      0 127.0.0.53:53           0.0.0.0:*                           538/systemd-resolve 
udp        0      0 192.168.4.213:68        0.0.0.0:*                           499/systemd-network

**Comment by KenHaijun** [comment]
你好，请问解决了吗，我运行的时候也是出现这个问题

**Comment by 648540858** [comment]
你可以不加端口映射看看是否可以启动
