### ISSUE TITLE
录像查询 SimpleDateFormat解析失败

### ISSUE THREAD

**Issue by zhanghuamingmyself** [648540858/wvp-GB28181-pro#304]
**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos  java11
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

win7 java11环境查看云端录像列表SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); 报错
String fileStartTimeStr = dateFile.getName() + " " + timeArray[0] 无法解析
String fileStartTimeStr = dateFile.getName() + " " + timeArray[0]+":00:00"; 就可以了

**Comment by 648540858** [comment]
你的设备国标实现不标准
