### ISSUE TITLE
录像下载路径

### ISSUE THREAD

**Issue by zhanghuamingmyself** [648540858/wvp-GB28181-pro#305]
**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
网页下载播放录像路径404
that.mediaServerPath = location.protocol + "//" + that.mediaServerList[0].streamIp + ":" + port改为 that.mediaServerPath = location.protocol + "//" + that.mediaServerList[0].streamIp + ":" + port+"/record"就行了

**Comment by 648540858** [comment]
你是win环境吧，你可以参考pr修改下
