### ISSUE TITLE
播放端在centos7下，谷歌浏览器播放存在黑屏但是快照是正常的

### ISSUE THREAD

**Issue by zlklink** [648540858/wvp-GB28181-pro#309]
**描述错误**
无论系统部署什么操作系统下
播放端在centos7与ubuntu20下，谷歌浏览器播放存在黑屏但是快照是正常的，播放器下方有网络波动，同系统下火狐没问题
播放端在windows下谷歌也没问题

**如何复现**
任意操作系统下部署wvp，找一个centos7或者ubuntu20的客户端，安装最新谷歌浏览器，播放黑屏，但是快照是正常的

**预期行为**
应该可以正常观察

**截图**
![b45b86969fb632bef5aab2d9e065ef1](https://user-images.githubusercontent.com/39792244/149439419-329b1631-deb3-4878-84df-3e1fe8cdacdd.jpg)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows或者 centos7 
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 没有使用https
 - 6. 海康、大华相机与NVR都有，都是同样问题
 - 7. 你做过哪些尝试：重装浏览器，恢复配置，皆解决不了问题

**Comment by 648540858** [comment]
目前没有在centos下测试过，我自用的是linux mint 20.3内核版本5.13.0,没有这些问题，我觉得您可以关注下内核版本，以及驱动情况

**Comment by zlklink** [comment]
好的，我试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 648540858 ***@***.***&gt;
发送时间: 2022年1月25日 14:09
收件人: 648540858/wvp-GB28181-pro ***@***.***&gt;
抄送: zlklink ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [648540858/wvp-GB28181-pro] 播放端在centos7下，谷歌浏览器播放存在黑屏但是快照是正常的 (Issue #309)

**Comment by 648540858** [comment]
再给个提示，这个播放器使用的wasm方式播放h265,不支持wasm的播放器是无法播放的。可以关注下。

**Comment by 648540858** [comment]
你测试怎么样

**Comment by 648540858** [comment]
我先关了有问题再打开吧
