### ISSUE TITLE
[技术咨询]新代码查询设备问题

### ISSUE THREAD

**Issue by ypy31393936** [648540858/wvp-GB28181-pro#310]
部署方式 编译部署
部署环境 windows
全部开放
不是公网部署
不使用https

目前版本网页上设备列表有问题，应该是摄像头向平台注册后未写进数据库里导致的，可能对数据库的操作在更新代码时出现了问题
数据库sqlite和mysql都试过，使用mysql时，在网页上删除数据库里默认的设备，但数据库里仍有这些信息

![捕获](https://user-images.githubusercontent.com/58900740/149606184-3423aa87-d8be-4a6e-bc71-150184f41ba3.PNG)
![捕获](https://user-images.githubusercontent.com/58900740/149606220-d593363d-9c1a-44fa-b3c3-9e46945d2e40.PNG)

**Comment by 648540858** [comment]
你可以使用最新代码测试下。
