### ISSUE TITLE
当NVR上将通道减少时，查询了不会减少存储的通道信息。

### ISSUE THREAD

**Issue by Gowa2017** [648540858/wvp-GB28181-pro#313]
**描述错误**
在设备列表页面，设备的刷新按钮，通道信息不会减少。

**如何复现**
正常注册一个NVR，然后减少NVR上的通道信息。点击刷新，通道不会减少。

**预期行为**
预期通道信息，一旦刷新，应与NVR上一致。

**截图**

**环境信息:**
 - 1. 部署方式 完全编译
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况
 - 4. 是否是公网部署 是
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
先重启nvr再，抓包看一下，确认nvr发送的通道确实减少了。我知道一种情况，我手里的这个nvr即使没有通道它也默认发送一个通道。有一个这个是不能确认一定一致。

**Comment by Gowa2017** [comment]
> 先重启nvr再，抓包看一下，确认nvr发送的通道确实减少了。我知道一种情况，我手里的这个nvr即使没有通道它也默认发送一个通道。有一个这个是不能确认一定一致。

重启平台，或是删除库内信息，就会OK。

**Comment by 648540858** [comment]
抓包看一下吧
