### ISSUE TITLE
播放视频串流的问题

### ISSUE THREAD

**Issue by godlike10** [648540858/wvp-GB28181-pro#314]
centos7 部署的zlm和wvp-pro ，大概是2021年12月26日左右从github下载的代码编译的wvp-pro。
使用情况是在政务网里对接了一个下级平台，这个下级平台里大概有700多路视频。
我这边程序会长时间同时点播大概50-100路的视频，然后偶尔手动点播一路视频的时候会发现刚打开是A画面，看一会儿关掉后，隔几分钟再次打开这路视频，重复几次后，经常性画面就变了，变成其他路视频的画面了。
我正在排查这个问题，不知道作者有没有遇到过类似的问题

**Comment by godlike10** [comment]
后续我给推流端口范围扩大了，之前是30000-30500
我给改成30000-35000了，一下午时间没发现串流了

**Comment by 648540858** [comment]
明白了，我自己目前没有遇到，我找时间测试下，根据你的情况像是端口不够用造成的，理论上500个端口，应该可以支撑250路并发。

**Comment by godlike10** [comment]
其实zlmediakit的openrtpserver不是可以随机端口吗，建议wvp就不去管理这个端口，直接让zlmediakit去管理这个端口。

**Comment by sundongyu** [comment]
> 后续我给推流端口范围扩大了，之前是30000-30500 我给改成30000-35000了，一个下午的时间没发现串流了

请问您的问题解决了吗，通过增加端口能够解决串流问题吗，我现在也是串流，3个摄像头给了5个端口
