### ISSUE TITLE
公网部署端口号的问题

### ISSUE THREAD

**Issue by qingfengtaizi** [648540858/wvp-GB28181-pro#315]
我只需要 实时播放功能。
公网指南中，rtmp.port、rtsp.port不是必须开发的端口号，
是不是意味着，我只需要开放下面必须的端口就可以了？
![image](https://user-images.githubusercontent.com/24245864/150627575-057ee8c1-3f71-4c6d-bce0-39d74c5fb203.png)

**Comment by 648540858** [comment]
是的
