### ISSUE TITLE
上级平台没有没有专门注册任务，使用redis过期再去注册，而PlatformNotRegisterEventLister中又会中断推流。。。

### ISSUE THREAD

**Issue by nikmu** [648540858/wvp-GB28181-pro#316]
**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
明白了，我看看

**Comment by 648540858** [comment]
看到你的pr了，已经合并了。多谢。
