### ISSUE TITLE
录像服务启动报错

### ISSUE THREAD

**Issue by Keith-Sillylove** [648540858/wvp-GB28181-pro#320]
**描述错误**
录像服务启动报错 报错提示配置文件找不到 文档中没有提到有关配置文件的设置 所以不清楚配置文件具体怎么配置

**如何复现**
按文档一步一步走 到启动java -jar wvp-pro-assist-1.0.0-20210601100954.jar --spring.config.location=target/application.yml时就会报错

**预期行为**
录像服务部署成功 能录像

**截图**
![B U0NA0WYYQ LN8%S(IIO4X](https://user-images.githubusercontent.com/40781611/151118107-b7b1f9bd-eeff-4e88-9924-53f82927c0c7.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境CentOS 8.3.2011(Py3.7.9)　
 - 3. 端口开放情况
 - 4. 是公网部署
 - 5. 否使用https
 - 6. 阿里云服务器
 - 7. ①修改配置文件路径②注释掉相关报错的类③重新拉取代码部署

**Comment by hqishen** [comment]
需要创建数据库“wvp"和创建应用所需的表。
![image](https://user-images.githubusercontent.com/20750728/151135931-e2ba7e48-9332-4255-90a5-74776aa037fb.png)

**Comment by 648540858** [comment]
--spring.config.location=target/application.yml 替换为绝对路径试试

**Comment by 648540858** [comment]
看报错有两种可能，一种是找不到配置文件，一种是在配置文件中没有
```
swagger-ui:
    enabled: true
```
