### ISSUE TITLE
级联时下级平台有时停止推流失败

### ISSUE THREAD

**Issue by ypy31393936** [648540858/wvp-GB28181-pro#323]
部署方式：编译部署
部署环境：windows&centos 
端口开放情况：全开
是否是公网部署：否
是否使用https：否
方便的话提供下使用的设备品牌或平台：Nvr是天地伟业的
你做过哪些尝试：
当上级平台触发无人观看的条件时，会向下级平台发送bye请求，这个时候下级平台应该停止向上级平台发送rtp流，但有时通过redis获取的streamId为null，导致停止rtp推流失败，下级平台会一直向上级平台推流，用的是单端口模式，请问是不是redis要设置哪里
![捕获](https://user-images.githubusercontent.com/58900740/153139276-65be4753-ae74-4fa0-a858-a4d196536733.PNG)

**Comment by 648540858** [comment]
已经修复
