### ISSUE TITLE
[bug]播放推流列表中的媒体时颜色变为绿色

### ISSUE THREAD

**Issue by ZeratulBrale** [648540858/wvp-GB28181-pro#330]
播放推流列表中的媒体时颜色变为绿色

**如何复现**
使用obs向zlm 1935推rtmp流，推流后使用http方式播放正常，使用wvp页面播放时视频变为绿色

**预期行为**
视频正常展示

**截图**

**环境信息:**
 - 1. 部署方式 docker 部署 docker run --env WVP_IP="192.168.31.129" -it -p 18080:18080 -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp -p 80:80 -p 5060:5060 -p 5060:5060/udp -p 1935:1935  -p 6379:6379 648540858/wvp_pro
 - 2. 部署环境 ubuntu 20.04
 - 3. 端口开放情况 docker run --env WVP_IP="192.168.31.129" -it -p 18080:18080 -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp -p 80:80 -p 5060:5060 -p 5060:5060/udp -p 1935:1935  -p 6379:6379 648540858/wvp_pro
 - 4. 非公网部署
 - 5. 未使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 使用http-flv直接播放正常

**Comment by 648540858** [comment]
我没复现你的文体，设置下你的obs，推桌面，输出中开启高级，设置最大B帧为0,再次测试。

**Comment by ZeratulBrale** [comment]
obs中关键帧间隔为0
![image](https://user-images.githubusercontent.com/24913487/154180350-a12691fc-fb59-4f61-9ecf-6dd70450d233.png)
![image](https://user-images.githubusercontent.com/24913487/154180477-c583772f-2083-43b7-92f4-965bb9128f31.png)
![image](https://user-images.githubusercontent.com/24913487/154181000-29fe03f6-04da-4e2b-9926-7b3a10e78bc1.png)

**Comment by 648540858** [comment]
我说的是设置最大B帧为0,

**Comment by ZeratulBrale** [comment]
我的obs没有您所说的设置最大B帧的选项，以下为我的obs版本信息
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale/zh-CN.ini
Attempted path: /usr/share/obs/obs-studio/locale/zh-CN.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: == Profiler Results =============================
info: run_program_init: 5667.05 ms
info:  ┗OBSApp::AppInit: 5.177 ms
info:    ┗OBSApp::InitLocale: 1.862 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: =================================================
info: Number of memory leaks: 1

**Comment by 648540858** [comment]
![image](https://user-images.githubusercontent.com/18274453/154232074-727d351e-e1cb-43fc-9b1f-39bd3df6fc25.png)
这是我的设置，如果你没有我建议你换个版本测试下，或者换一台电脑安装obs测试。

**Comment by 648540858** [comment]
画面质量，wvp控制不了，恕我无能为力。
