### ISSUE TITLE
请更新docker，还是3个月前的

### ISSUE THREAD

**Issue by abcd19886** [648540858/wvp-GB28181-pro#331]
老大，请更新一下docker，有3个月没有更新了，感谢！

**Comment by 648540858** [comment]
好的

**Comment by 1157457050** [comment]
up

**Comment by imnicn** [comment]
刚刚编译的镜像
git clone https://github.com/imnicn/wvp-docker.git
cd wvp-docker
vim docker-compose.yml
docker-compose up -d
