### ISSUE TITLE
wvp-pro-assist云端录像功能无法播放视频

### ISSUE THREAD

**Issue by zhangtianshi123** [648540858/wvp-GB28181-pro#332]
**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by zhangtianshi123** [comment]
1、部署方式：zlm，wvp，wvp-pro-assist都是编译部署
2、部署环境：ubuntu 19.04
3、相关端口均已开放
4、内网部署
5、没有使用https
6、海康摄像头

描述错误：wvp-pro-assist部署运行成功，但是视频无法播放，请参见截图
![image](https://user-images.githubusercontent.com/74576721/154176684-7378abcc-f95b-4e1b-b5c7-325ccab271c2.png)
![image](https://user-images.githubusercontent.com/74576721/154176769-ffccb09f-8cf3-4b76-93be-ccc869dc6579.png)
这是我配置文件的zlm录像地址
![image](https://user-images.githubusercontent.com/74576721/154176987-9c3e77a6-0f97-400b-acfa-5875d6bd7a2e.png)

如何复现：按照wiki部署运行后查看云端录像
预期行为：云端录像功能可以正常使用，可以播放历史视频

**Comment by 648540858** [comment]
确认下你的视频格式，播放器不一定支持你的格式。

**Comment by 648540858** [comment]
可以发一个你的视频给我看下

**Comment by 705127079** [comment]
我的也是无法播放，我是centos7，我发现sftp无法get文件名带冒号视频，不知是不是这个影响

**Comment by xiayongkang111** [comment]
@648540858 我都报错是一直无法下载根目录以外的错误 我看云端录像的文件格式都是-rw-r--r--  这是什么问题
# response:
You can not download files outside the root directory
