### ISSUE TITLE
最新代码，通道号为0

### ISSUE THREAD

**Issue by qingfengtaizi** [648540858/wvp-GB28181-pro#335]
公共配置，设备列表 可以正常显示，但是 通道为0.
![image](https://user-images.githubusercontent.com/24245864/154405953-dfa721a8-5d51-4483-85c0-67ef92d946ca.png)
刷新后抓包如下；
![image](https://user-images.githubusercontent.com/24245864/154406068-26f2f96d-7c89-4976-ab4e-7f26208c6607.png)

**Comment by qingfengtaizi** [comment]
是海康的设备，为什么厂家 也没获取到呢

**Comment by 648540858** [comment]
提供下抓包数据，按issue格式提供下您的信息

**Comment by 648540858** [comment]
我先关了，你有抓包数据再打开
