### ISSUE TITLE
海康nvr频繁崩溃问题

### ISSUE THREAD

**Issue by hujian2018** [648540858/wvp-GB28181-pro#337]
二次开发推流接口，海康nvr 16路，同时（多线程）推流后过不了多久会造成女人奔溃，最后页面上会显示设备离线，每次出现这样问题后总要重启下nvr，想问下是啥原因引起的呢

**Comment by 648540858** [comment]
那是nvr有问题呀
无论如何nvr自己也不能崩溃呀

**Comment by shenhaihua002** [comment]
海康nvr是不是兼容性不怎么好，一段时间就要重启，不然页面黑屏

**Comment by 648540858** [comment]
你这么说我也不知道，我手里只有一个大华的nvr，没有你说的问题。
