### ISSUE TITLE
未找到可用的zlm

### ISSUE THREAD

**Issue by kongxiangrun** [648540858/wvp-GB28181-pro#338]
请问 播放提示"未找到可用的zlm" 该如何处理

**Comment by 648540858** [comment]
重启zlm测试，看看wvp日志是否有zlm已连接的提示。

**Comment by 648540858** [comment]
更新代码测试下，需要为media配置ID

**Comment by Krehizi** [comment]
> 

需要为media配置ID怎么配置呢

**Comment by icefree** [comment]
ZLM config.ini配置文件中 [general]部分对mediaServerId，要和application.yml中media.id一致

**Comment by Galaxy-Ding** [comment]
hello 我这边也是未找到可用zlm
![image](https://github.com/648540858/wvp-GB28181-pro/assets/54030287/b4a74629-1751-42a3-9b80-916060543beb)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/54030287/a7de2111-1e40-49ac-84a8-44082a47c025)
zlm config 配置文件 和  application.yml 已经对应上了是一样的。

**Comment by answer666** [comment]
请问你修复这个问题了吗？

**Comment by answer666** [comment]
> hello 我这边也是未找到可用zlm ![image](https://private-user-images.githubusercontent.com/54030287/280999269-b4a74629-1751-42a3-9b80-916060543beb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDIyNDAsIm5iZiI6MTcxNDEwMTk0MCwicGF0aCI6Ii81NDAzMDI4Ny8yODA5OTkyNjktYjRhNzQ2MjktMTc1MS00MmEzLTliODAtOTE2MDYwNTQzYmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAzMjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyY2M4MjAwNjRhMTQ0OWMzNTQwMjBkYWMyMWZhOTJjMjExYjgyYjllYWI4OWU5ZjBkNDY2MzQ2M2FmYmIxNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i-GKYRNTOtq2diaeTHZxSi2MUb8PxCvy_kOrmHWf2Fo) ![image](https://private-user-images.githubusercontent.com/54030287/280999304-a7de2111-1e40-49ac-84a8-44082a47c025.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDIyNDAsIm5iZiI6MTcxNDEwMTk0MCwicGF0aCI6Ii81NDAzMDI4Ny8yODA5OTkzMDQtYTdkZTIxMTEtMWU0MC00OWFjLTg0YTgtNDQwODJhNDdjMDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAzMjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxN2VlNTc1NjUyMWQ3NDA2N2NlMjc4MDg2MDlkMmU4M2Q1MGNjZDZiOTgzOTdhZTY4NDYyNzEyN2FhZDE1ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eBL03M9UT6AagMb60JaoToMuYYVtWsOLdhG5MyK-UPs) zlm config 配置文件 和 application.yml 已经对应上了是一样的。

你好 ，请问解决这个问题了吗？

**Comment by LeiYangGH** [comment]
如果wvp和zlm没在同一台机器，也有可能需要配置zlm允许的ip范围。
