### ISSUE TITLE
海康NVR接入WVP经常出现视频不能打开问题

### ISSUE THREAD

**Issue by gaoliugang** [648540858/wvp-GB28181-pro#340]
**描述错误**
描述下您遇到的问题
   接入海康NVR，并在其下面挂载监控，开启海康下面监控轮播一段时间后出现无法打开直播的情况。（有一次还出现串流的情况，即两个监控显示同样的画面）
保持轮播4小时以上（有时候会更长）会出现无法直播的情况。在WVP中直接通道中打开监控出现timeout。用大华NVR接入后，同样的监控不会出现问题。

**如何复现**
有明确复现步骤的问题会很容易被解决

    1、接入海康NVR，并在其下面挂载监控4个
    2、开启海康下面监控轮播4小时以上
    3、会出现无法打开直播的情况。（直接在WVP里面打开视频出现timeout提示）
    3、用大华NVR接入同样的监控并使用同样的方法测试，一切正常。

**预期行为**
清晰简洁的描述您期望发生的事情
     期望一直可以正常轮播下去，不出现
**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境: centos7.8
 - 3. 端口开放情况: 18080
 - 4. 是否是公网部署：是
 - 5. 是否使用https ： 否，是http
 - 6. 方便的话提供下使用的设备品牌或平台
    监控，NVR都是海康。平台可以提供，方便的话加我微信gaoliugang003
 - 7. 你做过哪些尝试
   重新启动wvp服务后问题消失

**Comment by gaoliugang** [comment]
如果需要测试，我可以提供海康NVR对你的WVP远程接入测试

**Comment by 648540858** [comment]
最近是否还在测试呢

**Comment by wpclyy** [comment]
我的海康NVR无法播放，media提示丢包

**Comment by 648540858** [comment]
遇到相同问题请使用最新代码另外开一个isssue吧
