### ISSUE TITLE
设备点播超时, 停止视频流的时候发现事务已丢失

### ISSUE THREAD

**Issue by skanger** [648540858/wvp-GB28181-pro#349]
**描述错误**
描述下您遇到的问题

播放一段时间后，播放中断

重新登陆后

重新点播失败

刷新通道后，通道数量为0 

设备的心跳时间一直在跟着刷新，但是没有通道

日志: 

设备点播超时，deviceId：34020000001310000100 ，channelId：3402000000200000109
2022-02-25 17:13:07.379  WARN 12 --- [io-18080-exec-2] c.g.i.v.g.t.cmd.impl.SIPCommander        : [ 34020000001310000100 -> 3402000000200000109]停止视频流的时候发现事务已丢失

**如何复现**
有明确复现步骤的问题会很容易被解决

无明确复现方案，都是挂着播放视频一两小时才出现

确定出现了三四次
确定下级设备在线

重启WVP，设备重新注册就正常

**预期行为**
清晰简洁的描述您期望发生的事情

播放失败后，希望重新点播能正常播放

**截图**

报错截图
![image](https://user-images.githubusercontent.com/18080860/155691250-79f897dd-c8d1-4a72-ac7e-6d8a386793c4.png)

通道丢失后截图

![image](https://user-images.githubusercontent.com/18080860/155691664-d73849d6-2dd5-4069-9a35-8be0be57d3ad.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
     wvp-pro docker 

 - 2. 部署环境 windows / ubuntu/ centos ...

   macos 11.6.3
 - 3. 端口开放情况

docker run  --env WVP_IP="192.168.1.157" -it -p 18080:18080 -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp -p 80:80 -p 5060:5060 -p 5060:5060/udp  -p 554:554  648540858/wvp_pro

 - 4. 是否是公网部署
   
    否 

 - 5. 是否使用https

   否

 - 6. 方便的话提供下使用的设备品牌或平台

  接入了两个28181设备
   华为NVR800
   海康IPC

 - 7. 你做过哪些尝试

尝试过刷新通道，但是通道就变成0个，无法继续点播了
确定不是单台设备问题，用两台设备测试过了
进入docker容器，发现都能ping 通，网络没中断

尝试重启wvp，重新接入设备就恢复了

**Comment by skanger** [comment]
尝试过让 NVR离线，再链接


点击同步通道还是超时


2022-02-25 17:54:14.417  WARN 12 --- [io-18080-exec-9] c.g.i.v.v.gb28181.device.DeviceQuery     : 设备通道信息同步超时
2022-02-25 17:54:14.418  WARN 12 --- [io-18080-exec-9] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.context.request.async.AsyncRequestTimeoutException]

**Comment by 648540858** [comment]
可以尝试吧心跳间隔设置的短一些，注册间隔也短一些，可以取之前的一半。

**Comment by 648540858** [comment]
这块已经优化你可以再试试
