### ISSUE TITLE
设备推流掉线，ZLM保活失败：未找到流媒体信息

### ISSUE THREAD

**Issue by LiangMinxing** [648540858/wvp-GB28181-pro#350]
**描述错误**
在使用过程中，摄像头离线停止推流之后，发现WVP控制台输出【更新ZLM 保活信息】失败，未找到流媒体信息！

**如何复现**
定时大概10分钟左右，即出现该问题（即使未注册摄像头）

通过代码发现，流媒体信息是被存储在Redis中且存储时过期策略为-1【永不过期】，但是错误出现之后回到Redis中
查看，发现ONLINE的ZLM信息被清除了。通过代码发现，ZLMRunner中会执行删除配置的操作，到这里我，我就想
是不是我的配置有问题或者我的操作有问题，于是我跟wiki中的配置进行对比，实在没找到什么问题。操作上双手离开
键盘不进行任何操作，WVP服务也会出现该提示。到这里我就找不到问题了，于是来此进行厚颜请教。

PS：当时想尝试在MediaServerServiceImpl.updateMediaServerKeepalive() 方法中修改，逻辑是既然Redis中没有了，就从数据库中找到default的ZLM进行重新连接。。
但是还没有付诸尝试。

**预期行为**
不知是WVP程序逻辑设计如此还是实实在在发生的问题，预计就是ZLM不掉线吧。

**截图**
![image](https://user-images.githubusercontent.com/94591655/155704211-c3e6fdd4-1504-49f4-82e6-d194185a1cc1.png)

**环境信息:**
 - 1. 部署方式 wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 全部开放
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台  杂牌。。没品牌名。
 - 7. 你做过哪些尝试  修改WVP配置文件、修改ZLM配置、重写保活逻辑（未实施，代码已编写）。

**Comment by 648540858** [comment]
保活到期的时候我会再一次连接zlm，确实连不上才会提示失败。所以出现这个问题的时候你可以试着连接zlm看看，看看你的zlm是不是无法连接了

**Comment by LiangMinxing** [comment]
试了下，连接ZLM的接口确实是可以的。 重启WVP也是可以让ZLM上线的，这就很诡异了。从我目前调试的情况来看，基本确定在Redis的key被删除了，保活key、onlinekey、server信息key全部都被删除了，只是不知道数据被删除是谁删的。。

![image](https://user-images.githubusercontent.com/94591655/155834299-698aa5b8-c755-4837-889b-3434c254d481.png)

因为key被删除了，getOne查不到数据，无法进行重连。

**Comment by 648540858** [comment]
最新代码也是这样吗，之前优化一次这个流程，你可以在试试

**Comment by LiangMinxing** [comment]
我看了下2.0分支里的代码，最新代码确实是这么写的.

**Comment by Zzt1993** [comment]
请问这个问题得到解决了吗，我也遇到了这个问题，重启wvp服务后，又可以继续使用了

**Comment by Zzt1993** [comment]
请问这个问题得到解决了吗，我也遇到了这个问题，重启wvp服务后，又可以继续使用了

**Comment by answer666** [comment]
> 请问这个问题得到解决了吗，我也遇到了这个问题，重启wvp服务后，又可以继续使用了

你们解决了吗？ 我现在设备掉线厉害，不知道什么问题。。。
