### ISSUE TITLE
选择子平台通道拉流会失败

### ISSUE THREAD

**Issue by chaodayu** [648540858/wvp-GB28181-pro#354]
**描述错误**
wvp-gb28181-2.0分支，父平台拉子平台的通道的视频流会失败

**如何复现**
拉取分支编译运行，使用mysql.sql初始化数据库，用wvp的平台与wvp的平台进行联级，父平台拉子平台通道的流拉不成功。

**环境信息:**
 - 1. 编译wvp-pro + zlm都是编译部署
 - 2. 通过mysql.sql初始化mysql数据库
 
 **问题原因**
- 1. mysql.sql中platform_gb_channel表中没有字段`channelId`
- 2. 添加上级平台选择通道的时候，没有往数据库中记录channelId
- 3. 父平台拉子平台的流的时候，会通过channelId在platform_gb_channel查询设备ID，查询的时候直接sql抛出异常导致拉流失败。

**解决办法**
- 1. mysql.sql中platform_gb_channel表中增加`channelId`字段
- 2. 添加上级平台选择通道的时候，往表platform_gb_channel中保存channelId字段。那么拉流就可以正常了。

**Comment by chaodayu** [comment]
![aaaaaaaa](https://user-images.githubusercontent.com/21050481/155961803-525ec9c2-a340-45a2-8d7d-606c726ea0e1.png)
![bbbbbbb](https://user-images.githubusercontent.com/21050481/155961843-e7fd1d4b-9550-4aa0-9229-5b967a629bdf.png)
![ccccccc](https://user-images.githubusercontent.com/21050481/155961858-8cecce46-bfb5-41a7-aa71-6e786263db7d.png)

**Comment by chaodayu** [comment]
**修复代码**
![dddddd](https://user-images.githubusercontent.com/21050481/155962669-75c58c1e-61c6-44f5-95d2-b74464b906bb.png)
![eeeee](https://user-images.githubusercontent.com/21050481/155962674-78f0c637-2f93-43db-ab26-52aa75977c3a.png)

**Comment by 648540858** [comment]
已经修复
