### ISSUE TITLE
问题1:重启服务器WVP+ZLM以后代理拉流需要停用在启用才能播放。

### ISSUE THREAD

**Issue by wang00850023** [648540858/wvp-GB28181-pro#355]
**描述错误**
描述下您遇到的问题
问题1:老问题重启服务器WVP+ZLM以后代理拉流需要停用在启用才能播放。
问题2:老问题 关闭自动断流 配置  stream-none-reader-delay-ms: -1 ZLM无法上流 修改为 正常时间就可以
**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**
![image](https://user-images.githubusercontent.com/8486291/156110270-8e53b933-0b36-4bcc-b1c3-717510959206.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 -    wvp-docker
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
已经修复
