### ISSUE TITLE
疑似任意字符用户名/密码登陆问题

### ISSUE THREAD

**Issue by firstfsx** [648540858/wvp-GB28181-pro#36]
原配置文件
auth: #登陆用户名和密码,密码为32位小写md5加密（默认密码为admin）
    username: admin
    password: 21232f297a57a5a743894a0e4a801fc3

修改为：
auth:
    # [可选] 用户名
    username: root
    # [可选] 密码, 默认为admin123
    password: 0192023a7bbd73250516f069df18b500

则可以任意字符登录 管理页面

**Comment by 648540858** [comment]
好的， 我看一下

**Comment by 648540858** [comment]
问题已修复， 更新代码测一下吧
