### ISSUE TITLE
No decoder  colud be  found for codec none

### ISSUE THREAD

**Issue by skanger** [648540858/wvp-GB28181-pro#361]
**描述错误**

从大华EVS 配置28181接入

视频流能加载，无法播放

发现 video code 是 none

**如何复现**

可以私聊推送公网流给你

**预期行为**
预期能正常播放

**截图**
![image](https://user-images.githubusercontent.com/18080860/156310684-7d416880-1a1a-4275-abc3-bbc2d4b7574b.png)

![image](https://user-images.githubusercontent.com/18080860/156310704-9646d25f-658f-454f-95a0-a68c498a0076.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker
 - 2. 部署环境  ubuntu 18

 - 3. 端口开放情况
docker run --env WVP_IP="192.168.1.157" -it -p 18080:18080 -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp -p 80:80 -p 5060:5060 -p 5060:5060/udp -p 554:554 648540858/wvp_pro

 - 4. 是否是公网部署
否
 - 5. 是否使用https
否
 - 6. 方便的话提供下使用的设备品牌或平台
大华EVS
 - 7. 你做过哪些尝试
尝试过 vlc , ffplay, jessibuca 都是有网络流，无法播放

**Comment by 648540858** [comment]
设备编码修改成h264,帧率25帧， i帧间隔10秒，试试
