### ISSUE TITLE
ZLM节点管理-默认节点-缺少主动连通测通

### ISSUE THREAD

**Issue by zhangxiaorui1995** [648540858/wvp-GB28181-pro#364]
**描述错误**
docker-compose 部署 分开了 wvp和zlmediakit 部署过程中 存在wvp部署后发现 zlm不在线，实则配置是完全可以的，也是可用的节点

**如何复现**
先构建wvp  配置默认节点  启动默认节点
**预期行为**
增加主动连通测试
**截图**
![image](https://user-images.githubusercontent.com/35321570/156335567-7b8edd9e-8093-4429-88a9-cd397b3c09eb.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况 
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
节点主动连接发生在服务启动的时候，中间没有主动检测，有心跳保活。如果你的zlm重启了，如果是连接过一次的zlm会发送上线的通知。不需要中通检测。

**Comment by zhangxiaorui1995** [comment]
>
docker-compose部署的情况下
