### ISSUE TITLE
WVP作为级联平台时信息同步不一致

### ISSUE THREAD

**Issue by zhangxiaorui1995** [648540858/wvp-GB28181-pro#371]
**描述错误**
国标级联服务存在信息不同步，设备离线 通道信息不刷新
**如何复现**
部署俩套wvp
一套作为另外一套的级联平台
**预期行为**
级联上级域平台能准确的同步下级域的信息
**截图**
WVP级联WVP
![级联](https://user-images.githubusercontent.com/35321570/156725625-a68a6d68-5346-405d-b888-6ce4cca0c401.png)
通道状态
![上级状态](https://user-images.githubusercontent.com/35321570/156725668-4ee6a637-39f6-4e5c-8866-ca05662ab52e.png)

实际的下级
![实际状态](https://user-images.githubusercontent.com/35321570/156725684-25b16aab-8dfb-4691-8ec2-098da732eb9c.png)

域设备状态（此时通道依然为开启）

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by zhangxiaorui1995** [comment]
![实际状态](https://user-images.githubusercontent.com/35321570/156725764-063a7e69-8d25-4aec-8a78-24dc43b0c964.png)
![上级状态](https://user-images.githubusercontent.com/35321570/156725781-388677d9-8c3a-46cd-b6d6-6e2c11abb8d6.png)
![级联](https://user-images.githubusercontent.com/35321570/156725788-c66942b1-93d2-40a8-80d3-4eec1a08b6f2.png)

**Comment by 648540858** [comment]
试试最新的代码，添加了订阅支持目前每测试出这些问题。我先关了，有问题你再打开
