### ISSUE TITLE
录像回放拖拽存在空指针

### ISSUE THREAD

**Issue by github1359930721** [648540858/wvp-GB28181-pro#373]
**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**
![image](https://user-images.githubusercontent.com/94958189/156864111-7b90289d-8a07-4eab-b56e-c641f7cec885.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
已解决
