### ISSUE TITLE
国标级联register请求不符合国标规范，via头的Branch值不符合RFC3261规范，导致注册时返回400

### ISSUE THREAD

**Issue by AtomweiGithub** [648540858/wvp-GB28181-pro#376]
**描述错误**
国标级联register请求不符合国标规范，via头的Branch值不符合RFC3261规范，导致注册时返回400

**截图**
![image](https://user-images.githubusercontent.com/32348023/156906683-020b026c-b34e-44b2-a15f-831e77cc342a.png)
![image](https://user-images.githubusercontent.com/32348023/156906692-c8c3b472-bdd6-4fe0-b416-6c4bba19e628.png)

**Comment by 648540858** [comment]
已修复
