### ISSUE TITLE
级联回放信令缺失

### ISSUE THREAD

**Issue by szy833** [648540858/wvp-GB28181-pro#377]
**描述错误**
级联回放时，按照国标要求，当视频播放完成后，下级平台回发送CmdType为MediaStatus的Message信令，告知上级平台流发送完。当前最新代码没有对上级平台发送该信令的处理。导致上级平台没有接收到121信令。无法释放链路。

**如何复现**
级联添加上级平台，通过上级平台抓包，开始回放，等待回放完成后。通过抓包未发现Message信令。

**预期行为**
添加Message信令

**截图**
![image](https://user-images.githubusercontent.com/31844882/156907321-60524e9e-6561-4172-adac-0596d549e0f4.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
已修复
