### ISSUE TITLE
建议实时监控和国标设备TAB使用不同的接口

### ISSUE THREAD

**Issue by LiangMinxing** [648540858/wvp-GB28181-pro#378]
![image](https://user-images.githubusercontent.com/94591655/156960234-5ca91787-f94a-47b2-8699-849952fc0509.png)

目前实时监控树形结构调用的接口和国标设备分页列表的接口调用的是同一个接口：/api/device/query/devices

该接口目前是查询所有的设备（包含在线/离线），个人认为实时监控只显示【在线】设备更好，因此建议多写一个接口供实时监控使用

**Comment by 648540858** [comment]
已经修复，只是没使用你的方案，离线也是要显示的，设计如此
