### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by ypy31393936** [648540858/wvp-GB28181-pro#382]

**Comment by ypy31393936** [comment]
新国标代码基连的问题

**Comment by ypy31393936** [comment]
[问题.docx](https://github.com/648540858/wvp-GB28181-pro/files/8204990/default.docx)
新国标代码级联的问题

**Comment by 648540858** [comment]
4、级联录像查询 具体报错不需要了，有人提供了一样的错误

**Comment by ypy31393936** [comment]
更新后的测试  单端口实时流和历史流都可以播放    多端口实时流播放失败  应该是逻辑的问题  还是由rtp默认端口收流   而不是新建端口  导致stream名不匹配  推流失败   好像这块代码改的挺多的  我找不到哪里的问题   帮忙看下吧
<img width="1202" alt="捕获" src="https://user-images.githubusercontent.com/58900740/158288105-f2df9af9-87ac-48d7-9642-8c531ec90c58.PNG">

**Comment by ypy31393936** [comment]
找到原因了  这里我这样修改可以观看实时流
<img width="1260" alt="捕获" src="https://user-images.githubusercontent.com/58900740/158294728-8e09fece-7730-48c8-b920-6b112a363fa3.PNG">
对java不是很熟悉   看下这样会不会有其他影响

**Comment by ypy31393936** [comment]
@648540858

**Comment by ypy31393936** [comment]
下载接口貌似也有问题 
<img width="1185" alt="捕获" src="https://user-images.githubusercontent.com/58900740/158301459-2e66a2d9-b2bd-485e-abfe-1a41d993e7f1.PNG">

**Comment by 648540858** [comment]
再更新试试最近修复过

**Comment by 648540858** [comment]
> 找到原因了 这里我这样修改可以观看实时流 <img alt="捕获" width="1260" src="https://user-images.githubusercontent.com/58900740/158294728-8e09fece-7730-48c8-b920-6b112a363fa3.PNG"> 对java不是很熟悉 看下这样会不会有其他影响

这个已经修复了

**Comment by ypy31393936** [comment]
感谢大佬   我先关了这个issue了  如果发现新的问题会在新的issue提出
