### ISSUE TITLE
Docker deploy ,通道为0

### ISSUE THREAD

**Issue by zhangschunfeng** [648540858/wvp-GB28181-pro#389]
**描述错误**
描述下您遇到的问题
         使用dockerhub上最新的镜像部署，使用的大华的摄像头，设备通道为0
**如何复现**
有明确复现步骤的问题会很容易被解决
      必现
**预期行为**
清晰简洁的描述您期望发生的事情
 
**截图**
  
![image](https://user-images.githubusercontent.com/12216085/157667481-7d9d3cab-ca4f-48e6-8930-51b43035b1b5.png)

![image](https://user-images.githubusercontent.com/12216085/157667288-7eb9a441-8dbc-405d-9571-b484eaccd2c6.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker 
 - 2. 部署环境   centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署  阿里云部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by SaltFish001** [comment]
不建议使用dockerhub的镜像, 哪个镜像有点老了. 有需要使用Docker部署可以看看Readme.MD里面的docker-compose方案
