### ISSUE TITLE
录像回放倍速快进

### ISSUE THREAD

**Issue by xuanhuangkeji** [648540858/wvp-GB28181-pro#39]
录像回放倍速快进这个有空也可以搞一下啊

**Comment by 648540858** [comment]
这个有时间我考虑下怎么实现

**Comment by banmajio** [comment]
> 录像回放倍速快进这个有空也可以搞一下啊

可以看一下我基于wvp项目添加的历史回放倍速播放的内容

**Comment by chenparty** [comment]
@648540858 你让我提醒一下你。haha

**Comment by 648540858** [comment]
ui与信令已经实现了，谢谢大家， @chenparty 谢谢你的pr。
