### ISSUE TITLE
[bug]注册时间

### ISSUE THREAD

**Issue by wsmGo** [648540858/wvp-GB28181-pro#390]
**描述错误**
描述下您遇到的问题
最新版本  首次注册 注册时间没有注入

**如何复现**
有明确复现步骤的问题会很容易被解决

删除数据重新注册

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**
![image](https://user-images.githubusercontent.com/57796920/157792061-a8c3e327-4592-4a4b-b1d1-345621de0df6.png)

**Comment by 648540858** [comment]
已修复
