### ISSUE TITLE
[bug] 设备同时注册导致消息丢失

### ISSUE THREAD

**Issue by wsmGo** [648540858/wvp-GB28181-pro#391]
**描述错误**
描述下您遇到的问题

当两个摄像头同时注册时 触发的首次注册的两个方法只会有第一个注册的设备会处理到deviceInfo补全设备信息以及通道信息

**如何复现**
有明确复现步骤的问题会很容易被解决
删除多个已注册的设备 再同时重新上线

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**
![image](https://user-images.githubusercontent.com/57796920/157826156-c04eeccf-b554-4df4-b99c-4e72815efb35.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by wsmGo** [comment]
最新版本

**Comment by wsmGo** [comment]
MESSAGE-Keepalive 会直接新增设备了

**Comment by wsmGo** [comment]
应该是修复了首次注册时间那边导致的问题

**Comment by 648540858** [comment]
信息丢失那个单独注册下，看看能不能拿到数据，部分设备不支持获取这些信息。
