### ISSUE TITLE
zlm的鉴权事件的bug

### ISSUE THREAD

**Issue by sxh-netizen** [648540858/wvp-GB28181-pro#396]
**描述错误**
1.wvp的zlm鉴权hook中，进行回放逻辑是否录制是，查询redis中的回放，查询不到，因为在zlm鉴权时，redis还没添加进去流信息，
2.wvp与最新的zlm的鉴权事件返回不支持驼峰命令法

**如何复现**
进行回放即可

**预期行为**
回放时不录制

**截图**
问题2：![image](https://user-images.githubusercontent.com/58098910/158292662-603a79a0-32c8-4774-aec7-4a9237aaf177.png)

**Comment by 648540858** [comment]
已修复
