### ISSUE TITLE
WVP无法支持对同一个设备开启两条流通道

### ISSUE THREAD

**Issue by LMiracle** [648540858/wvp-GB28181-pro#397]
**描述错误**
WVP无法支持对同一个设备开启两条流通道，不确定是否是设备的原因，我尝试了海康与宇视两款摄像头，都是同样的结果。

**如何复现**
在浏览器一个页面打开一个设备的点播或者录播，同时在另一个页面同样开启该设备的点播或者录播就会出现SIP 486异常。

**预期行为**
WVP能支持同一个设备开启多条流通道

**截图**
![1647310607(1)](https://user-images.githubusercontent.com/26618535/158293220-32d0ed77-ea13-48a8-97ad-0ca33f278df5.jpg)

**环境信息:**
 - 1. 部署方式 wvp-pro + zlm都是编译部署
 - 2. 部署环境 windows
 - 3. 端口开放情况 本地测试
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 DELL windows 电脑
 - 7. 你做过哪些尝试 尝试了海康与宇视的设备

**Comment by 648540858** [comment]
你确定你的设备支持同时点播和录像一起吗

**Comment by 648540858** [comment]
486是设备忙， 你的请求他无法做出回应，如果已经点播一路直播，那么再次点播这路设备，平台会直接返回播放地址，这是设备的问题。
