### ISSUE TITLE
播放H265视频时无界面

### ISSUE THREAD

**Issue by Haiping2018** [648540858/wvp-GB28181-pro#4]
播放H265视频时，前台界面一直闪烁，看起来好像前端的播放器不支持H265解析？播放H264正常。
运行环境：Windows

**Comment by 648540858** [comment]
网页不支持解码H265,可以尝试media.closeWaitRTPInfo设置为false,会提示你是否转码为h264播放

**Comment by 648540858** [comment]
我关闭了,你可以在尝试下
