### ISSUE TITLE
录像查询拉动进度条前端请求错误

### ISSUE THREAD

**Issue by taigege** [648540858/wvp-GB28181-pro#402]
**描述错误**
录像查询，拉动进度条，请求地址错误，多了一个反斜线

**如何复现**
录像查询，拉动进度条

**预期行为**
拉动进度条正常不报错

**截图**
![image](https://user-images.githubusercontent.com/36600558/158552156-d9cac5cc-3ca4-4e99-ae62-cdf5b2c056ff.png)

**Comment by 648540858** [comment]
怎么复现我这边测试最新代码没有这个问题，

**Comment by 648540858** [comment]
怎么复现我这边测试最新代码没有这个问题，

**Comment by 648540858** [comment]
这是对方返回的500,不是我这里的500,你需要咨询海康的技术。
