### ISSUE TITLE
录像回放正常播放完毕之后  没有给设备发送停流指令

### ISSUE THREAD

**Issue by github1359930721** [648540858/wvp-GB28181-pro#404]
**描述错误**
录像回放正常播放完毕之后  没有给设备发送停流指令

**如何复现**
让录像回放正常播放完毕

**截图**
播放完毕的时候会进入和这个里面 把redis的数据给删除 停流时 找不到这个信息 无法发送停流指令
![image](https://user-images.githubusercontent.com/94958189/158758531-05766436-e21f-4201-b273-5925907664d9.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ... 
 - 3. 端口开放情况 全开放
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
好的，我测试下
