### ISSUE TITLE
播放失败,点播失败

### ISSUE THREAD

**Issue by Luo-99** [648540858/wvp-GB28181-pro#406]
**描述错误**
可以注册,可以刷新通道,但是点播超时

<img width="1102" alt="3" src="https://user-images.githubusercontent.com/22796879/158826226-e70625f0-b943-40b0-bf8e-7776f2904172.png">

**如何复现**
 就没点播成功过,一直可以复现

**预期行为**
我希望点播成功,能看到摄像头画面

**截图**

<img width="925" alt="2" src="https://user-images.githubusercontent.com/22796879/158825885-32db202e-d233-4fd5-8aea-aa09f40d0845.png">

<img width="1001" alt="1" src="https://user-images.githubusercontent.com/22796879/158825422-877db809-8ffc-40cb-9abe-2a8a4ffe50a1.png">

**环境信息:**
 - 1. 部署方式 === (zlm 使用 docker) (wvp 使用 idea 直接跑)  启动无报错
 - 2. 部署环境  === ( wvp 在windows 的 idea  )  ( zlm 在 windows 的 VMware Linux Centos 7  下的 docker )
 - 3. 端口开放情况  === 已经关闭防火墙,通畅无阻
 - 4. 是否是公网部署  === 否,自己路由器局域网下测试
 - 5. 是否使用https === 否
 - 6. 方便的话提供下使用的设备品牌或平台 === 设备 http://www.founu.com/uploads/soft/deviceDemo.apk (安卓手机模拟摄像头和 901799015 群里的测试工具 (都是点播失败))
 - 7. 你做过哪些尝试 === 改idea yml 配置文件, 但是结果依旧

**Comment by 648540858** [comment]
看wiki，修改你的配置，确定你的media.ip是你的摄像机可以连接到的

**Comment by Luo-99** [comment]
已经解决了,要自己编译zlm,用了文档提供的docker的zlm.导致的问题

**Comment by 648540858** [comment]
好的
