### ISSUE TITLE
海康设备下载功能BUG

### ISSUE THREAD

**Issue by taigege** [648540858/wvp-GB28181-pro#407]
**描述错误**
海康设备第一次通电使用下载功能正常，下载多个文件后，设备会回复bye，不会发送历史媒体流，且之后历史视频回放功能也失效。
根据群友反馈，是wvp存在BUG下载流程未正确回复设备Bye，导致设备状态异常、

**如何复现**
连续依次下载多个文件后，接口就会返回设备响应超时

**预期行为**
连续下载文件均成功

**截图**
下发Invite请求后，设备正常返回SDP消息返回了文件大小参数，但是随后设备返回了BYE。
![69K(}G0HT$0IGW5(X~58H%3](https://user-images.githubusercontent.com/36600558/158979266-98ad9370-892b-452f-b595-51d612c4fc18.png)

![JX}N1F `KS}S$6TQM`3 2Z7](https://user-images.githubusercontent.com/36600558/158979328-7cbbaaaf-f7a5-48a5-88d8-eff15e67f5de.png)

**环境信息:**
 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署（均为22年3月18日最新版本）
 - 2. 部署环境 centos
 - 3. 端口开放情况 按照文档
 - 4. 是否是公网部署 设备、wvp、zlm均在内网环境
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试   根据群友反馈，是wvp存在BUG下载流程未正确回复设备Bye，导致设备状态异常。

**Comment by taigege** [comment]
根据海康技术回复，设备只支持两路回放，平台发送断开设备才会断开。

**Comment by 648540858** [comment]
目前设备下载尚有BUG，等我修复一版

**Comment by taigege** [comment]
更新了2022/3/25日的代码后，如果设备号与通道号一致，下载功能正常，SIP服务可以正常发Bye。但是当设备号与通道不一致时，海康设备在文件下载结束后Message发送的From是设备通道号，而非设备号，会导致代码报错提示设备未找到。

设备发送的Message：
![c02a8a70bf2859c5702718c6e9a6958](https://user-images.githubusercontent.com/36600558/160096423-5ca92140-8f68-4790-b1d4-a377470af692.png)

代码中是通过获取FromHeader获得的设备号，就会导致找不到设备
![image](https://user-images.githubusercontent.com/36600558/160096548-6f7a5ad4-c40f-4bf9-9f26-bf5817cb7fef.png)


设备发送keepalive包的from区是正常的
![image](https://user-images.githubusercontent.com/36600558/160096885-5ffc2c87-26b4-4a62-b6c6-1210af4c0ff8.png)

**Comment by 648540858** [comment]
所以这是海康的BUG呀，如果from里都是设备编号那我从哪里可以拿到呢，消息体里肯定是通道编号
我试着从会话呢获取，你试试，如果还不行我也没办法了
