### ISSUE TITLE
 wvp级联时作为下级平台，不支持上级平台的TCP主动模式流传输

### ISSUE THREAD

**Issue by wanghuahui** [648540858/wvp-GB28181-pro#410]
大佬好，目前测试发现 wvp级联时作为下级平台，不支持上级平台的TCP主动模式流传输(即上级tcp主动，下级tcp被动)，请问这个功能什么时候可以实现啊

**Comment by 648540858** [comment]
tcp主动是是要求上级主动来连wvp，wvp再推流，目前zlm只支持主动推流，不支持被动建立链接后再推流，所以这个实现不了。
如果未来zlm支持了，或许会去实现

**Comment by 648540858** [comment]
我先关了，这个只能未来再看
