### ISSUE TITLE
通道号同步好后过10秒左右被部分删除

### ISSUE THREAD

**Issue by yuanweisuannai** [648540858/wvp-GB28181-pro#411]
**描述错误**
最新版wvp，在国标设备列表点击刷新按钮后，可更新通道，为32个通道，但是过一会，会删掉部分通道号,删除的通道号是不固定的

**如何复现**
更新到最新版代码，在国标设备列表点击刷新按钮后

**预期行为**
不删除通道号

**截图**

**Comment by 648540858** [comment]
看下你不显示的通道是不是通道编号重复了

**Comment by yuanweisuannai** [comment]
我的通道编号是从1到32，不会设置重复，而且每次被删除不是规律的，有时候剩十几个，有时候只有两个

**Comment by yuanweisuannai** [comment]
后来我还原到之前的版本是没问题的

**Comment by 648540858** [comment]
wvp最新代码如果存储失败就全部不存了
，不会只存一部分

**Comment by 648540858** [comment]
你说的旧版本是哪个版本

**Comment by yuanweisuannai** [comment]
旧版本指的是3月11号之前的版本，我看日志值执行了delete语句，not in(‘设备号’)

**Comment by 648540858** [comment]
具体的执行的哪个类，哪个方法我看看

**Comment by yuanweisuannai** [comment]
VideoManagerStoragerImpl中的resetChannels方法，这一行代码int cleanChannelsResult = deviceChannelMapper.cleanChannelsNotInList(deviceId, channels);

**Comment by 648540858** [comment]
这是在一个事务的呀，除非重复了不然不会丢呀

**Comment by 648540858** [comment]
wvp有报错吗

**Comment by yuanweisuannai** [comment]
没有报错，日志都正常打印的，关键是第一次同步好了是全的，过了10来秒会部分删除

**Comment by 648540858** [comment]
我考虑不是addAll线程不安全，是因为使用的ArrayLisl线程不安全。
CatalogDataCatch 33行
```
catalogData.setChannelList(Collections.synchronizedList(new ArrayList<>()));
```
你试试，如果没问题我就提交了

**Comment by tastypinenut** [comment]
> 我考虑不是addAll线程不安全，是因为使用的ArrayLisl线程不安全。 CatalogDataCatch 33行
> 
> ```
> catalogData.setChannelList(Collections.synchronizedList(new ArrayList<>()));
> ```
> 
> 你试试，如果没问题我就提交了

49行也应该一起改

**Comment by 648540858** [comment]
已经提交了
