### ISSUE TITLE
我2022-3-08号编出来的jar包可以正常使用，点播等都可以；3-25号编译出来的包，点播设备一直没有推流。

### ISSUE THREAD

**Issue by dualven** [648540858/wvp-GB28181-pro#412]
**描述错误**
我2022-3-08号编出来的jar包可以正常使用，点播等都可以；3-25号编译出来的包，点播设备一直没有推流。

**如何复现**
3-25号打jar包

**预期行为**

**截图**
zlm 那边的截图为：
![image](https://user-images.githubusercontent.com/2209534/160093682-a9d102d0-7df3-4c5d-9d78-b2629112e159.png)

**环境信息:**
 - 1. 部署方式 wvp-pro jar + zlm(docker) 
 - 2. 部署环境 centos7
 - 3
 - 6. 方便的话提供下使用的设备品牌或平台 
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
升级zlm了吗

**Comment by dualven** [comment]
使用的是最新的： zlmediakit/zlmediakit:Release.last

**Comment by dualven** [comment]
@648540858  帮忙 看看

**Comment by dualven** [comment]
已经解决。zlm重新编译
