### ISSUE TITLE
我用了git上最新的版本，也检查了播放器文件（没有缺少），重新编译了项目，但是在实时监控页面还是无法播放

### ISSUE THREAD

**Issue by liumingxin798** [648540858/wvp-GB28181-pro#417]
**描述错误**
我用了git上最新的版本，也检查了播放器文件（没有缺少），重新编译了项目，但是在实时监控页面还是无法播放

**如何复现**
使用最新版本打包部署即可复现

**预期行为**
实时监控顺利播放

**截图**

**环境信息:**
 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境  centos 
 - 3. 端口开放情况  开放
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台  海康设备
 - 7. 你做过哪些尝试
 - 重新编译，查看源码，暂未发现哪里的问题，因为国标设备列表可以播放， 实时监控列表播放失败，查看源码，发现用的是同一个播放器，运行未发现任何错误，我将继续排查。

**Comment by 648540858** [comment]
实时监控使用的是什么编码

**Comment by 379839336** [comment]
我也是同样的问题 我的格式H264

**Comment by liumingxin798** [comment]
> 实时监控使用是什么编码

使用的是H.264

**Comment by liumingxin798** [comment]
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/18522173/160773656-18898ad9-d082-43c9-b770-53461337925e.png">
问题已解决，当前线上代码缺少:hasAudio="hasAudio"，这可能跟组件有关系，具体未深挖

**Comment by liumingxin798** [comment]
问题继续出现，修改刚才的代码后，可以播放，但过了一段时间后实时监控又无法播放，点击播放黑屏，看来问题还是存在

**Comment by 379839336** [comment]
根据图片修改这几个参数改为100%就可以了

![QQ图片20220331145407](https://user-images.githubusercontent.com/17818644/160995912-0f7a1f69-4d23-4c3b-9796-4d7f2b7a41c3.png)
![1111](https://user-images.githubusercontent.com/17818644/160995922-2a5e0674-67b8-4e06-b7a3-639622bd8b01.png)

**Comment by liumingxin798** [comment]
> 根据图片修改这几个参数改为100%就可以了
> 
> ![QQ图片20220331145407](https://user-images.githubusercontent.com/17818644/160995912-0f7a1f69-4d23-4c3b-9796-4d7f2b7a41c3.png) ![1111](https://user-images.githubusercontent.com/17818644/160995922-2a5e0674-67b8-4e06-b7a3-639622bd8b01.png)

你是用的是最新版的代码吗

**Comment by 379839336** [comment]
是的最新的代码

**Comment by liumingxin798** [comment]
> 是的最新的代码

感谢给予思路我现在去尝试看看

**Comment by liumingxin798** [comment]
> 
重新架构后发现新的问题，在切换分屏时样式错乱

**Comment by liumingxin798** [comment]
> 是的最新的代码

重新架构后发现新的问题，在切换分屏时样式错乱，请问你的样式是可以的吗

**Comment by liumingxin798** [comment]
![image](https://user-images.githubusercontent.com/18522173/161008594-0d1575a9-965a-4a8f-a0c7-5974ce3a83d5.png)
我去排查一下这个问题发生的原因

**Comment by liumingxin798** [comment]
已解决，我提交了新的rp需要可以去看看
