### ISSUE TITLE
media.auto-config设置成false后，仍然会修改zlm的config.ini中的on_record_mp4配置项

### ISSUE THREAD

**Issue by mengxing2017** [648540858/wvp-GB28181-pro#418]
**描述错误**
media.auto-config设置成false后，仍然会修改zlm的config.ini中的on_record_mp4配置项，将其ip地址设置成127.0.0.1

**如何复现**
media.auto-config设置成false后，修改config.ini中的on_record_mp4的ip地址设置成其他地址，然后重启相关服务

**预期行为**
不修改config.ini中的on_record_mp4的ip地址

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) / wvp-pro-assist(docker)
 - 2. 部署环境 linux
 - 3. 端口已全部开放情况
 - 4. 内网网部署

**Comment by 648540858** [comment]
没复现出来，你可以再最新代码下测试下
