### ISSUE TITLE
播放视频提示收流超时

### ISSUE THREAD

**Issue by littlefish19** [648540858/wvp-GB28181-pro#420]
**描述错误**
海康设备配置完成，正常上线后，播放通道视频流提示收流超时。

**如何复现**

**预期行为**
应能正常播放

**截图**
设备配置：
![image](https://user-images.githubusercontent.com/102707970/160960824-918e4936-d951-4395-8657-04278c6ed666.png)

平台配置：
![image](https://user-images.githubusercontent.com/102707970/160960784-acf7a6d1-31ea-4116-8b43-6f383621f613.png)

操作：
![image](https://user-images.githubusercontent.com/102707970/160960877-92b7ec53-ddc3-45de-b4c1-8960e2153847.png)
![image](https://user-images.githubusercontent.com/102707970/160960892-ce6d6189-6956-417e-adeb-e7f6d5cf8099.png)
![image](https://user-images.githubusercontent.com/102707970/160960912-7faee26d-853d-4ceb-b198-dcd8167d9d2f.png)

**环境信息:**
 - 1. 部署方式 ：编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境：  centos  
 - 3. 端口开放情况 30000~40000 5060
 - 4. 是否是公网部署： 公网
 - 5. 是否使用https ：未使用
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
media.ip是不是配置的127

**Comment by zhzhiwei8** [comment]
应该是zlm中的your_server_id没有改成和media.id一样

**Comment by littlefish19** [comment]
> media.ip是不是配置的127
两个装在同一台服务器上的，配的是127.0.0.1，不能配成127.0.0.1吗？
![image](https://user-images.githubusercontent.com/102707970/161175351-7bd53817-4a9b-4158-9e1a-a362516d7c41.png)
![image](https://user-images.githubusercontent.com/102707970/161175352-8a6ed4a5-ccfd-4c92-b25f-a82bdbfafd82.png)

**Comment by 648540858** [comment]
配置127,你需要同时配置sdp-ip, stream-ip ;不然就不要用127.
