### ISSUE TITLE
实时监控无法预览，f12查看报错

### ISSUE THREAD

**Issue by zhzhiwei8** [648540858/wvp-GB28181-pro#421]
**描述错误**
在实时监控预览无法播放，在设备里面的通道中可以预览、云台控制。
通过F12查看报错如下：
![2~L2CFXM9 XI`EF{N2$4`}4](https://user-images.githubusercontent.com/31091245/161096696-21d3a253-6000-4548-935b-08f6514510fd.png)

版本
![JXD9D R S~TW2CQ( 3`K$}N](https://user-images.githubusercontent.com/31091245/161096745-85a8b571-de55-49c3-b86d-0d130eb4d3e1.png)

**Comment by 648540858** [comment]
更新代码试试，之前提交少了播放器文件

**Comment by 648540858** [comment]
确认你的实时流的编码格式

**Comment by SkieLi** [comment]
版本：commit 2659f1055146597957820214ea5bc12bc49d20d4
在这个commit编译的版本，实时监控还是无法浏览，通道中是可以预览的，实时流编码格式h264 M

**Comment by liumingxin798** [comment]
> 版本：commit [2659f10](https://github.com/648540858/wvp-GB28181-pro/commit/2659f1055146597957820214ea5bc12bc49d20d4) 在这个commit编译的版本，实时监控还是无法浏览，通道中是可以预览的，实时流编码格式h264 M，F12没有报错了

我已经修复并移交了rp自己去找一下

**Comment by 648540858** [comment]
不好意思你修复那个把代码复制了一份，我觉得不太好，我把播放组件做了下适配，目前已经修复这个问题，你可以测试下。我先关了
