### ISSUE TITLE
rtsp/rtmp等推流转发到国标平台要怎么操作

### ISSUE THREAD

**Issue by winyluo** [648540858/wvp-GB28181-pro#422]
文档上面写的这两个功能要怎么操作，有没有操作文档？
1.支持rtsp/rtmp等视频流转发到国标平台。
2.支持rtsp/rtmp等推流转发到国标平台。

**Comment by 648540858** [comment]
添加拉流代理的时候添加上国标ID。添加完国标级联选择通道时点击右侧直播流通道，选择你添加的即可

**Comment by 648540858** [comment]
推流也是一样，点击加入国标为你的推流加一个国标ID
