### ISSUE TITLE
wvp服务启动后ZLMediaKit服务就停止

### ISSUE THREAD

**Issue by winyluo** [648540858/wvp-GB28181-pro#424]
**描述错误**
wvp服务启动后，提示“[未注册的zlm] 拒接接入：your_server_id来自192.168.50.156：6080”和“请检查ZLM的<general.mediaServerId>配置是否与WVP的<media.id>一致”，但是当我把your_server_id填进yml文件的media.id后启动服务，先是显示“ZLM上线事件触发，ID：your_server_id”，然后显示“连接ZLM失败: Connection refused...”，“请检查media配置并确认ZLM已启动...”，“ZLM离线事件触发，ID：your_server_id”，然后看ZLM的服务被停了

**如何复现**
正常按文档描述启动docker和Java项目服务

**预期行为**
希望尽快正常运行项目

**环境信息:**
 - 1. 部署方式 wvp-pro / zlm(docker) 
 - 2. 部署环境  centos ...
 - 3. 端口开放情况 本地服务器完全开放
 - 4. 是否是公网部署 否
 - 5. 是否使用https 没有使用
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
会调用zlm的重启接口，如果你启动方式不正确，就会停止而不是重启，详情查看zlm wiki

**Comment by boyup6** [comment]
docker run启动的zlm，wvp-pro启动后停止zlm不会重启
