### ISSUE TITLE
关于录像的问题

### ISSUE THREAD

**Issue by ypy31393936** [648540858/wvp-GB28181-pro#428]
目前  级联时  实时流支持单端口以及多端口   但是历史流仍然使用的是单端口  
是否能增加用多端口接收历史流   毕竟有些设备推送的不标准

**Comment by 648540858** [comment]
目前多端口和单端口都是支持的，但是向上级发送视频流只能是多端口，无法支持单端口，开启多端口收取实时流，那么历史流就也是端口。
