### ISSUE TITLE
国标级联查询问题

### ISSUE THREAD

**Issue by LMiracle** [648540858/wvp-GB28181-pro#429]
**描述错误**
（1）国标级联->选择通道->通道类型->选择子目录后再选择设备，无数据显示。
（2）查询时，会将没有关联到设备表数据的通道查询出来

**如何复现**
（1）国标级联->选择通道->通道类型->选择子目录后再选择设备。
（2）出现这个问题的原因是，通道没有找到对应的设备信息，无法判断是否在线也无法判断IP地址。

**预期行为**
（1）设备与子目录查询正常。
（2）没有关联到设备的通道信息不查询出来;
（3）以及想了解为什么会出现设备信息不存在，但是通道信息存在的情况，目前排除数据库直接手动删除设备信息的可能性。

**截图**
![image](https://user-images.githubusercontent.com/26618535/161881451-7598bd9f-46d9-463e-a880-e3ab500005dc.png)
![image](https://user-images.githubusercontent.com/26618535/161881541-769d8b36-2d21-4d10-8688-51ab88142bc6.png)

**环境信息:**
 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 windows
 - 3. 端口开放情况 开放
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 Dell
 - 7. 你做过哪些尝试

**Comment by jokbor** [comment]
这个好像直接调接口是可以获取级联的设备列表的

**Comment by lejny** [comment]
![wvp国标级联](https://user-images.githubusercontent.com/99492565/206415974-65680c0a-4148-4361-8b24-0c25de7095f9.png)
大神，请问一下：
1、wvp国标级联怎么能有子目录，子目录支不支持多级呢
2、wvp是否pc客户端或者手机客户端查看视频呢
期待您的回复！

**Comment by jokbor** [comment]
> ![wvp国标级联](https://user-images.githubusercontent.com/99492565/206415974-65680c0a-4148-4361-8b24-0c25de7095f9.png) 大神，请问一下： 1、wvp国标级联怎么能有子目录，子目录支不支持多级呢 2、wvp是否有pc客户端或者手机客户端支持查看视频呢 期待您的回复！


1、支持多级子目录的，你可以看下标准的GB28181协议
2、wvp主要还是作为信令用，你要PC客户端或者手机端看视频需要端上做播放，wvp已经提供了流地址了的
