### ISSUE TITLE
播放视频提示503

### ISSUE THREAD

**Issue by Ariza-ye** [648540858/wvp-GB28181-pro#430]
**描述错误**
同一个NVR下的设备,只能同时播放一个通道的视频,再次点击其他通道的视频,会返回503错误

**如何复现**

**预期行为**

**截图**
<img width="917" alt="image" src="https://user-images.githubusercontent.com/20201319/161883776-6eb7f6c6-db52-4b26-8c53-bbf7d0000ffd.png">

**环境信息:**
 - 1. 部署方式  
     编译wvp-pro / zlm(docker)
 - 2. 部署环境  
     centos 
 - 3. 端口开放情况 
     核查过需要的端口都开放了
 - 4. 是否是公网部署
     是
 - 5. 是否使用https
     否
 - 6. 方便的话提供下使用的设备品牌或平台
     TPSEE
 - 7. 你做过哪些尝试
 
看了下zlm的日志和wvp的日志
zlm日志:
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/20201319/161883875-d5262cd1-1d11-4ce2-9f11-fbb320ce0856.png">

wvp日志:
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/20201319/161883975-696a7951-d761-4b10-acc8-63a572a9c61c.png">

从日志看,zlm建立收流通道没有报错,但是wvp接受到的状态码是 503,想要确认下,这个503的状态码是NVR端返回的吗,还是zlm返回的呢?以及如何解决这个问题呢? 谢谢

定位到的代码:
com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver#processResponse

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/20201319/161884592-bd691637-37d0-48f6-bb9c-45be5d8258ad.png">

**Comment by 648540858** [comment]
你的设备不支持点播多路，点播下一个前把上一个关了就可以了
