### ISSUE TITLE
rtp端口不在配置范围内

### ISSUE THREAD

**Issue by 94su** [648540858/wvp-GB28181-pro#431]
**描述错误**
点播出现rtp端口不在设置范围内

**如何复现**
wvp后台设置rtp端口 ：
  port-range: 30000,30500 
zlm设置rtp端口：
  [rtp_proxy]
  port_range=30000-30500
重启两个服务，点播视频出现端口不在设置端口范围内

**预期行为**
配置范围内的端口推流

**截图**
![image](https://user-images.githubusercontent.com/48341727/162421789-472c5896-151e-444c-8132-f30d78099f5c.png)

**环境信息:**
 - 1. 部署方式  ：wvp-prp + zlm都是编译部署
 - 2. 部署环境 ：centos.
 - 3. 端口开放情况 ：3000-30500
 - 4. 是否是公网部署 ：是
 - 5. 是否使用https  ：否
 - 6. 方便的话提供下使用的设备品牌或平台  ：海康
 - 7. 你做过哪些尝试  ：设置zlm的rtp端口

**Comment by Smallwhitepig** [comment]
WVP+ZLM是否是最新版本,还有提供下ZLM的config.ini配置

**Comment by 94su** [comment]
> WVP+ZLM是否是最新版本，还有提供下ZLM的config.ini配置

WVP是最新版本，ZLM是2月左右安装的当时最新版
[config.txt](https://github.com/648540858/wvp-GB28181-pro/files/8458299/config.txt)
本

**Comment by 648540858** [comment]
2月左右不够新，换当前版本代码测试吧

**Comment by Ycong** [comment]
> 2月左右不够新，换当前版本代码测试吧

我这边wvp与zlm都使用新版本也出现端口不在指定范围内

**Comment by 94su** [comment]
> 

都更新了，可以了。

**Comment by Ycong** [comment]
> 



> > 
> 
> 都更新了，可以了。

我在更新一下看看
