### ISSUE TITLE
实时监控双屏展示浏览器崩溃

### ISSUE THREAD

**Issue by CBLCDG1018** [648540858/wvp-GB28181-pro#435]
**描述错误**
实时监控，分屏展示，1号和2号窗口同时显示画面，开始有卡顿，10s左右后，浏览器崩溃；单屏单通道，无问题，chrome浏览器
**如何复现**
实时监控，分屏展示多通道即复现

**预期行为**
实时监控，分屏展示多通道的情况下，画面流畅

**截图**
![浏览器崩溃](https://user-images.githubusercontent.com/16776845/163145742-52980d47-8cf0-444e-bd49-dda51d0e1365.png)

**环境信息:**
 - 1. 部署方式 wvp-pro 本地idea启动 / zlm(centos编译部署)
 - 2. 部署环境 windows + centos
 - 3. 18080
 - 4. 否
 - 5. 否
 - 6. Hikvision 摄像头
 - 7. 单双屏，反复尝试，单通道无问题，双屏的情况下浏览器崩溃问题持续复现

**Comment by 648540858** [comment]
看下视频的码率，web的播放器没有那么好的性能，

**Comment by zhysda** [comment]
目前使用的播放器性能比较差，只适合单个视频播放，多个视频会出现卡顿，黑屏等问题。可以考虑换一个播放器。

**Comment by zhysda** [comment]
推荐两个播放器，easyPlayer和aliPlayer
