### ISSUE TITLE
位置订阅时SIP报481

### ISSUE THREAD

**Issue by jokbor** [648540858/wvp-GB28181-pro#436]
描述错误
订阅移动位置信息时订阅成功，订阅信息已发到设备，但当设备端返回NOTIFY时SIP API直接返回481 Subscription does not exist

如何复现
调用订阅移动位置接口，抓去报文信息

预期行为
接受NOTIFY通知，解析消息内容，实现数据库写入和更新

SIP订阅报文信息
SUBSCRIBE sip:34020000001320000005@192.168.3.187:5888 SIP/2.0
Call-ID: 41ec691fabd7090460ef46b99031aa25@0.0.0.0
CSeq: 4 SUBSCRIBE
From: <sip:34020000002000000002@192.168.3.182:5060>;tag=fromTagPos1650004259330
To: <sip:34020000001320000005@3402000000>
Via: SIP/2.0/UDP 192.168.3.182:5060;branch=z9hG4bK-viaPos-1650004259330;rport
Max-Forwards: 70
Contact: <sip:34020000002000000002@192.168.3.182:5060>
Expires: 3600
Event: presence
Content-Type: Application/MANSCDP+xml
Content-Length: 179

<?xml version="1.0" encoding="GB2312"?>
<Query>
<CmdType>MobilePosition</CmdType>
<SN>955675</SN>
<DeviceID>34020000001320000005</DeviceID>
<Interval>5</Interval>
</Query>

SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.3.182:5060;branch=z9hG4bK-viaPos-1650004259330;rport=5060
To: <sip:34020000001320000005@3402000000>;tag=b93a8b7595340e64
From: <sip:34020000002000000002@192.168.3.182:5060>;tag=fromTagPos1650004259330
Call-ID: 41ec691fabd7090460ef46b99031aa25@0.0.0.0
CSeq: 4 SUBSCRIBE
Event: presence
Contact: <sip:34020000002000000002@192.168.3.182:5060>
User-Agent: Mi Note 3
Content-Length: 181
Content-Type: Application/MANSCDP+xml

<?xml version="1.0" encoding="utf-8"?>
<Response>
  <CmdType>MobilePosition</CmdType>
  <SN>955675</SN>
  <DeviceID>34020000001320000005</DeviceID>
  <Result>OK</Result>
</Response>

NOTIFY sip:34020000002000000002@192.168.3.182:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.3.187:5888;rport;branch=z9hG4bK15539
Max-Forwards: 70
To: <sip:34020000002000000002@192.168.3.182:5060>
From: <sip:34020000001320000005@3402000000>;tag=z9hG4bK08393721
Call-ID: 41ec691fabd7090460ef46b99031aa25@0.0.0.0
CSeq: 1 NOTIFY
Contact: <sip:34020000002000000002@192.168.3.182:5060>
User-Agent: Mi Note 3
Event: presence
Subscription-State: active
Content-Length: 317
Content-Type: Application/MANSCDP+xml

<?xml version="1.0" encoding="utf-8"?>
<Notify>
  <DeviceID>34020000001320000005</DeviceID>
  <CmdType>MobilePosition</CmdType>
  <SN>955675</SN>
  <Time>2022-04-15T14:31:00</Time>
  <Longitude>0.0</Longitude>
  <Latitude>0.0</Latitude>
  <Speed>0</Speed>
  <Direction>0</Direction>
  <Altitude>0</Altitude>
</Notify>

SIP/2.0 481 Subscription does not exist
CSeq: 1 NOTIFY
Call-ID: 41ec691fabd7090460ef46b99031aa25@0.0.0.0
From: <sip:34020000001320000005@3402000000>;tag=z9hG4bK08393721
To: <sip:34020000002000000002@192.168.3.182:5060>
Via: SIP/2.0/UDP 192.168.3.187:5888;rport=5888;branch=z9hG4bK15539;received=192.168.3.187
Content-Length: 0

**Comment by jokbor** [comment]
在createSipStack()中加入SIP配置，完美解决
properties.setProperty("javax.sip.AUTOMATIC_DIALOG_SUPPORT", "off");
properties.setProperty("gov.nist.javax.sip.DELIVER_UNSOLICITED_NOTIFY", "true");

**Comment by 648540858** [comment]
这个我知道，你会被自己坑的很惨的，这是关闭自动创建会话的意思，关闭之后你需要自己去维护会话，点播。订阅。不维护你后面的点播会有问题。奉劝，不加这个。
返回481的原因很简单，你的上级没有订阅。

**Comment by 648540858** [comment]
DELIVER_UNSOLICITED_NOTIFY你只打开这个试试， AUTOMATIC_DIALOG_SUPPORT还是保持原样吧

**Comment by 648540858** [comment]
你如果确定订阅成功了还是返回481,那就是设备的notify没有在这个事务里，是设备的问题。

**Comment by 648540858** [comment]
DELIVER_UNSOLICITED_NOTIFY 我测试了你只打开这个就可以了，代码我加上了，这个还是很有用的。

**Comment by jokbor** [comment]
> DELIVER_UNSOLICITED_NOTIFY你只打开这个试试， AUTOMATIC_DIALOG_SUPPORT还是保持原样吧

是的， AUTOMATIC_DIALOG_SUPPORT这个还是得打开，不然点播会有问题，忘记回这里来更新了

**Comment by jokbor** [comment]
> 这个我知道，你会被自己坑的很惨的，这是关闭自动创建会话的意思，关闭之后你需要自己去维护会话，点播。订阅。不维护你后面的点播会有问题。奉劝，不加这个。 返回481的原因很简单，你的上级没有订阅。

之前不加这个，你这边测试可以正常订阅接受NOTIFY消息吗

**Comment by YiLinBin** [comment]
按照国标文档的示例来看的话，上级下发Subscribe，from头域携带tag值，下级回复200OK中from头域的tag值为subscribe的from的tag，to是自己生成的，后续下级创建notify请求的时候，from头域的tag值应该使用200OK的to的tag，to头域的tag值应该使用subscribe的from的tag
![814f7285c71c0184b64563fdab5e98ad_](https://github.com/648540858/wvp-GB28181-pro/assets/97785764/06d49b76-149a-4e01-ae9f-2df727c71188)
