### ISSUE TITLE
docker 部署 zlm 超时问题

### ISSUE THREAD

**Issue by tingmag** [648540858/wvp-GB28181-pro#438]
在ZLM中设置了
[rtp_proxy]
port_range=30000-30500

但是在运行源码ZLMRTPServerFactory.java中zlmresTfulUtils.openRtpServer(mediaServerItem, param)返回的是{"code":0,"port":56298}

![image](https://user-images.githubusercontent.com/46146815/163797794-b19c626f-d1e8-401a-ad0c-4149008cf530.png)

这是不是说明ZLM中的rtp_proxy port_range设置无效？

**Comment by Smallwhitepig** [comment]
不推荐使用docker

**Comment by TravisMa1990** [comment]
zlm网络模式改成host
