### ISSUE TITLE
[新功能]语音对讲实现

### ISSUE THREAD

**Issue by ylixl** [648540858/wvp-GB28181-pro#44]

**Comment by 648540858** [comment]
这个还没有特别可行的方案，所以暂时不会实现。

**Comment by ylixl** [comment]
好的，谢谢

**Comment by ctiger001** [comment]
> 这个还没有特别可行的方案，所以暂时不会实现。

大神，我在csdn上看到一个帖子，能否看看按这个流程是否可以实现对讲
https://blog.csdn.net/qq_38795209/article/details/110953058

**Comment by itcareer** [comment]
语音对讲的实现，有计划了吗？我看现在的技术栈可以实现了噶

**Comment by 648540858** [comment]
有个小伙伴在尝试了，咱们等他好消息吧😄 648540858 ***@***.*** 签名由 网易邮箱大师 定制 在2021年04月13日 17:33，gwl 写道： 语音对讲的实现，有计划了吗？我看现在的技术栈可以实现了噶 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zouyaoji** [comment]
@648540858 
请问语音对讲这个目前有可以分享的东西吗？

**Comment by luolxb** [comment]
请问语音对讲的实现，有计划了吗

**Comment by 648540858** [comment]
着急的可以定制开发，目前还不能推送到主线。还不完善。

**Comment by xinsendi** [comment]
一年过去了，大佬，语音功能完善了没？

**Comment by 308207109** [comment]
语音对讲功能我这边已经实现了，但是海康的设备没办法跨网段对讲以及公网对讲，只能内网同网段对讲，公网对讲有没有什么可行的方案@648540858

**Comment by 648540858** [comment]
海康的没有，海康的新设备是支持tcp主动方式公网对讲的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月15日(周五) 晚上6:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] [新功能]语音对讲实现 (#44)




 
***@***.***

**Comment by 308207109** [comment]
> 海康的没有，海康的新设备支持tcp主动方式公网对讲的
> [……](#)
> ---原始邮件--- 发件人：***@***.***> 发送时间：2023年12月15日（周五）晚上6:40 食欲：***@***.***>; 抄送：***@***.******@***.***>; 主题: 回复: [648540858/wvp-GB28181-pro] [新功能]语音对讲实现 (#44) ***@***.*** — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。 您收到此消息是因为您被提及。消息 ID：***@***.***>

所有说这就比较蛋疼了，现在设备是支持双向对讲，但是国标这块没办法对讲，让官方给升级也不给固件包

**Comment by Tyi-13** [comment]
三年过去了，GB28181的对讲功能有眉目了吗？

**Comment by 308207109** [comment]
> 三年过去了，GB28181的对讲功能有眉目了吗？

自己开发！

**Comment by 648540858** [comment]
> 三年过去了，GB28181的对讲功能有眉目了吗？

已经开发，目前未开源。付费提供。

**Comment by alexspring123** [comment]
啥时候我们个人小白可以用上语音对讲啊 :(

**Comment by 308207109** [comment]
> 啥时候我们个人小白可以用上语音对讲啊 :(

已经开发完成了，没有开源。付费提供语音对讲！

**Comment by 648540858** [comment]
已合并默认支持。
