### ISSUE TITLE
请问我如果想要新增一些摄像头的控制操作应该怎么来做呢

### ISSUE THREAD

**Issue by CHparis** [648540858/wvp-GB28181-pro#445]
您好，我在com.genersoft.iot.vmp.vmanager.gb28181.device.DeviceControl这个类里面找到了一些控制摄像头的操作，如果我想再加上一些摄像头的【向左】、【向右】、【旋转】等操作我应该怎么来实现呢？

**Comment by 648540858** [comment]
目前就有你的说的功能呀
