### ISSUE TITLE
视频通道页面-按钮设备录象（错别字）改为设备录像

### ISSUE THREAD

**Issue by KelvinHuangGit** [648540858/wvp-GB28181-pro#453]
**描述错误**
我们是个严谨，规范的好平台，所以错别字不容忍哈哈

**如何复现**
国标设备-视频通道-通道列表页面-设备录象按钮

**预期行为**
设备录象应该为设备录像

**截图**
![image](https://user-images.githubusercontent.com/46700520/165420203-8ff886fb-3d31-4fe0-90ac-df374175bc87.png)

**环境信息:**
 - 1. 部署方式 zlm(docker) + 编译wvp-pro
 - 2. 部署环境 centos 
 - 3. 端口开放情况 均开放
 - 4. 是否是公网部署 内网部署
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试 测试

**Comment by 648540858** [comment]
谢谢
