### ISSUE TITLE
级联目录新建节点问题

### ISSUE THREAD

**Issue by ypy31393936** [648540858/wvp-GB28181-pro#454]
如图所示
<img width="1256" alt="捕获" src="https://user-images.githubusercontent.com/58900740/165423744-53d51759-5eb9-41ee-956f-7a98b080021a.PNG">
第一个节点新建成功后继续新建第二个节点
<img width="1258" alt="捕获2" src="https://user-images.githubusercontent.com/58900740/165423794-67af4f7a-15e4-4f57-8e30-ab5b40b70cdb.PNG">
即使我已经输入了id，节点编号那里还会提示请输入id，请问这是前端的一个小bug还是就是这样的设定呢？当我把选择通道界面关闭再打开又能继续新建节点，但每次只能建一个，建第二个又会报错，又要重新打开选择通道界面

**Comment by 648540858** [comment]
已修复
