### ISSUE TITLE
[BUG]“实时监控”页面内存没有释放

### ISSUE THREAD

**Issue by AbnerSC** [648540858/wvp-GB28181-pro#455]
**描述错误**
“实时监控”页面内存没有及时释放

**如何复现**
登录wvp，进入“实时监控”页面，展开左边的设备列表（此时浏览器内存占用大幅升高），再点击进入其他页面

**预期行为**
从实时监控页面切换到其他页面后，占用的内存应及时释放

**截图**
![image](https://user-images.githubusercontent.com/22092055/165430288-eaecbe02-c970-46af-914d-cf7e0ec7711e.png)

**环境信息:**
 - 1. 部署方式：wvp-prp + zlm都是编译部署
 - 2. 部署环境：centos 7 x64
 - 3. 端口开放情况：关闭防火墙
 - 4. 是否是公网部署：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：下级平台海康
 - 7. 你做过哪些尝试：多次测试

**Comment by TXJZQQBX** [comment]
通道设备如果量很大的话，采用前端递归分页查询所有设备就会导致电脑内存爆掉，这里应该是bug，建议使用channelId和parentId用懒加载的形式

**Comment by 648540858** [comment]
目前的主要问题一个目录下可能有几万的数据

**Comment by zoupinru** [comment]
请问此问题有没有其他变相解决方案？

**Comment by Daixingdeng** [comment]
> 目前的主要问题一个目录下可能有几万的数据

sse这种思路呢    可以考虑吗

**Comment by zoupinru** [comment]
您好，您发的邮件已收到，尽快给您回复。谢谢

**Comment by 648540858** [comment]
已经处理过了,可以再测试下

**Comment by zoupinru** [comment]
您好，您发的邮件已收到，尽快给您回复。谢谢
