### ISSUE TITLE
IPC首次注册未同步通道id和厂商信息

### ISSUE THREAD

**Issue by ilokin** [648540858/wvp-GB28181-pro#460]
**描述错误**
IPC首次注册未同步通道id和厂商信息，需要点击编辑按钮和刷新按钮才会同步信息。

**如何复现**
删除IPC设备重新注册

**预期行为**
IPC首次注册同步通道id

**截图**
![JAH03FMKR}_U`O9D}F}~{%T](https://user-images.githubusercontent.com/29363205/165562106-d83f4540-f511-455c-ad5a-4f68c79f06e5.jpg)

**环境信息:**
 - 1. 部署方式 都是编译部署/
 - 2. 部署环境 centos 7/8
 - 3. 端口开放情况 已关闭防火墙
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 手机模拟
 - 7. 你做过哪些尝试 抓包
[不更新通道.log](https://github.com/648540858/wvp-GB28181-pro/files/8573636/default.log)
[抓包.zip](https://github.com/648540858/wvp-GB28181-pro/files/8573641/default.zip)

**Comment by 648540858** [comment]
目前是存在这个bug，之前优化过一次但是在部分设备上仍有问题，目前原因不明。

**Comment by 648540858** [comment]
目前已经做过优化了，可以再测试下，我先关闭了。
