### ISSUE TITLE
看守位命令控制，NVR设备注册到平台通过看守位命令预置位编号没有变化

### ISSUE THREAD

**Issue by tangongming** [648540858/wvp-GB28181-pro#467]
**描述错误**
看守位命令控制，预置位编号没有变化，开启、等待时间都发生改变

**如何复现**
摄像头sip注册到平台，通过看守位命令控制，都可以改变
海康NVR设备注册到平台，通过看守位命令控制，开启和关闭、等待时间都可以改变，预置位编号不会编号
**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
海康的NVR一直问题遇到问题比较多，作者自己没有海康NVR,所以目前没办法进行修复。这个问题只能暂时搁置。多谢你的反馈。

**Comment by 648540858** [comment]
再测测试试
