### ISSUE TITLE
小Bug: wvp-GB28181-pro/blob/wvp-28181-2.0/web_src/src/components/control.vue 579行错误

### ISSUE THREAD

**Issue by dualven** [648540858/wvp-GB28181-pro#470]
**描述错误**
描述下您遇到的问题
wvp-GB28181-pro/blob/wvp-28181-2.0/web_src/src/components/control.vue
579行，应该修正 为:( kick_session后的&变成如下的？）
 url: '/zlm/' + that.mediaServerChoose + '/index/api/kick_session?id=' + id

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
好的我看看，谢谢

**Comment by 648540858** [comment]
已修复
