### ISSUE TITLE
wvp自带wsflv播放自动中断

### ISSUE THREAD

**Issue by baigenliang** [648540858/wvp-GB28181-pro#474]
使用GB推流wvp自带播放器播放或者原始播放器播放1分钟左右自动中断
 
GB推流的话播放器任意形式拉流一会就断，rtsp代理拉流前端rtsp拉流播放就不会断，但是自带wsflv播放器拉流也会断，希望能解决此问题 

![1](https://user-images.githubusercontent.com/32763140/168456108-d0b9ea8b-4147-492b-96bf-c2871be00025.png)

![2](https://user-images.githubusercontent.com/32763140/168456098-88140560-1de8-4669-936b-99e43ad25673.png)

代码调试环境下最新版的wvp+zlm

**Comment by Smallwhitepig** [comment]
建议更换谷歌浏览器

**Comment by 648540858** [comment]
不符合提问规范

**Comment by baigenliang** [comment]
是谷歌浏览器啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月15日 14:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [648540858/wvp-GB28181-pro] wvp自带wsflv播放自动中断 (Issue #474) |

建议更换谷歌浏览器
