### ISSUE TITLE
局域网IP映射到公网部署 设备一直注册不上

### ISSUE THREAD

**Issue by xue9957** [648540858/wvp-GB28181-pro#479]
**描述错误**
局域网映射到公网后 想实现公网部署 wvp-prp + zlm都是在局域网电脑部署 外部摄像头联网有公网ip 但就是注册不上

**如何复现**
是不是使用局域网映射公网这样行不通？

**预期行为**
能够成功注册上设备

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows  ...
 - 3. 端口开放情况 sip port media port 都开放
 - 4. 是否是公网部署 公网
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台 海康威视
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
我自己测试是可以的，检查的你的网络配置吧

**Comment by 648540858** [comment]
你可以发邮件给我约个时间我给你的公网映射地址。

**Comment by xue9957** [comment]
> 你可以发邮件给我约个时间我给你的公网映射地址。

感谢 已经在群里解决了

**Comment by wEnchanters** [comment]
@xue9957 你好，我也有这个问题，请教一下解决方法是什么呢
