### ISSUE TITLE
关于循环依赖问题，我解决了

### ISSUE THREAD

**Issue by itcareer** [648540858/wvp-GB28181-pro#48]
![image](https://user-images.githubusercontent.com/11265559/105974027-676f3880-60c8-11eb-87fb-93bf6bdcd909.png)

![image](https://user-images.githubusercontent.com/11265559/105974056-7229cd80-60c8-11eb-8a05-5872dee42f75.png)
![image](https://user-images.githubusercontent.com/11265559/105974114-840b7080-60c8-11eb-825a-a140e6a7febd.png)

**Comment by 648540858** [comment]
可以推pr上来吗？ pull request

**Comment by 648540858** [comment]
我看到了， 我先对比看下，你的pr修改的内容挺多的

**Comment by 648540858** [comment]
2.0分支已经解决
