### ISSUE TITLE
docker部署之后设备加到平台获取不到通道

### ISSUE THREAD

**Issue by shenrenlun** [648540858/wvp-GB28181-pro#482]
**描述错误**
海康的设备通过gb28181接入平台，通道都为0

**截图**
![image](https://user-images.githubusercontent.com/43904765/169240090-0d32c713-fd36-4d36-b021-bdd710a9cb51.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker)
 - 2. 部署环境 centos 7
 - 3. 设备用的是最普通的海康摄像头![image](https://user-images.githubusercontent.com/43904765/169240460-3fa365ee-0845-4923-880a-f7659d466049.png)

**Comment by 648540858** [comment]
1. 确定你的设备添加了通道
2. 手动点击刷新，看一下是否可以获取到
3. 建议使用最新代码，docker是很老的版本很久不更新了。
