### ISSUE TITLE
【新功能】支持报警订阅

### ISSUE THREAD

**Issue by Krehizi** [648540858/wvp-GB28181-pro#483]
**描述错误**
摄像头报警，wvp无收到报警信息。

**如何复现**
挂一个海康摄像头，触发报警时，平台看日志/界面无报警信息。

**预期行为**
能收到报警信息。

**截图**
![UTG%1T)EEI8CBD)T$ 241E5](https://user-images.githubusercontent.com/27603839/169241849-8c43f39e-f368-47ff-91cb-95f848ac0c4a.jpg)
![64)E03@UAZ$@9HY CB}I$5K](https://user-images.githubusercontent.com/27603839/169241868-d7d6070b-3445-4efe-aac7-d181753816c2.jpg)

**环境信息:**
 - 1. 原因
 大概看了一下源码，有报警订阅的相关功能代码，但是没有使用到。
尝试调用SIPCommander类的alarmSubscribe方法，没有效果。
将摄像头挂在其他平台，然后开启订阅，再挂回wvp，能正常收到报警信息。

**Comment by 648540858** [comment]
目前不支持报警订阅。只支持设备的报警主动推送，

**Comment by Krehizi** [comment]
> 目前不支持报警订阅。只支持设备的报警主动推送，

最近计划支持嘛

**Comment by 648540858** [comment]
目前没有计划

**Comment by Krehizi** [comment]
> 目前没有计划

这是调用SIPCommander类的alarmSubscribe方法发送的报警订阅，看着好像没毛病，就是设备报警时wvp还是无法收到消息：

![1653031294(1)](https://user-images.githubusercontent.com/27603839/169475297-59c965b1-72b6-4a4c-b176-ec6d23ed158f.png)
![1653031315(1)](https://user-images.githubusercontent.com/27603839/169475312-bc3669a1-e4ef-40c4-ac1c-cbde9a35c12a.png)

[capture package.zip](https://github.com/648540858/wvp-GB28181-pro/files/8737285/capture.package.zip)

**Comment by Krehizi** [comment]
找到问题了，还得调用SIPCommander的guardCmd开一下布防功能。

**Comment by bigff-0527** [comment]
怎么解决呀？我也没有收到报警日志

**Comment by guzijian123** [comment]
大哥  你现在有实现嘛  ，我目前也是需要这个事件订阅，测试了华为的设备推送事件推送了message 但是海康的没有任何反应

**Comment by bigff-0527** [comment]
> 大哥 你现在有实现嘛 ，我目前也是需要这个事件订阅，测试了华为的设备推送事件推送了message 但是海康的没有任何反应

设置布防，有api的 调用一下就好了

**Comment by guzijian123** [comment]
> > 大哥 你现在有实现嘛 ，我目前也是需要这个事件订阅，测试了华为的设备推送事件推送了message 但是海康的没有任何反应
> 
> 设置布防，有api的 调用一下就好了

![image](https://github.com/648540858/wvp-GB28181-pro/assets/103352688/cb6944be-a55d-4863-b44f-59c1de51f04a)
设置过布防  摄像头系统固件升级过支持报警服务器http通知 但是领导要求我调通国标的事件推送，头皮都大了

**Comment by bigff-0527** [comment]
> > > 大哥 你现在有实现嘛 ，我目前也是需要这个事件订阅，测试了华为的设备推送事件推送了message 但是海康的没有任何反应
> > 
> > 
> > 设置布防，有api的 调用一下就好了
> 
> ![image](https://private-user-images.githubusercontent.com/103352688/316373329-cb6944be-a55d-4863-b44f-59c1de51f04a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzU3OTEsIm5iZiI6MTcxMTMzNTQ5MSwicGF0aCI6Ii8xMDMzNTI2ODgvMzE2MzczMzI5LWNiNjk0NGJlLWE1NWQtNDg2My1iNDRmLTU5YzFkZTUxZjA0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMjU4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmZhYmZhZDhhOWNlZTgxMmI0ZTRmMmE0ZTAxNTkwZjczYTBhNzRhNWViODljODVjNjZlMmU1MDg1ZTY5ZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EbKLj0ghi1ut3ASnV-yRlTep904tKH8KGTX8f5DpZDY) 设置过布防 摄像头系统固件升级过支持报警服务器http通知 但是领导要求我调通国标的事件推送，头皮都大了

不是指这个布防，你看wvp的api文档，里面有个设置布防的接口 你调用就好了

**Comment by guzijian123** [comment]
> > > > 大哥 你现在有实现嘛 ，我目前也是需要这个事件订阅，测试了华为的设备推送事件推送了message 但是海康的没有任何反应
> > > 
> > > 
> > > 设置布防，有api的 调用一下就好了
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/103352688/316373329-cb6944be-a55d-4863-b44f-59c1de51f04a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzU3OTEsIm5iZiI6MTcxMTMzNTQ5MSwicGF0aCI6Ii8xMDMzNTI2ODgvMzE2MzczMzI5LWNiNjk0NGJlLWE1NWQtNDg2My1iNDRmLTU5YzFkZTUxZjA0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMjU4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmZhYmZhZDhhOWNlZTgxMmI0ZTRmMmE0ZTAxNTkwZjczYTBhNzRhNWViODljODVjNjZlMmU1MDg1ZTY5ZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EbKLj0ghi1ut3ASnV-yRlTep904tKH8KGTX8f5DpZDY) 设置过布防 摄像头系统固件升级过支持报警服务器http通知 但是领导要求我调通国标的事件推送，头皮都大了
> 
> 不是指这个布防，你看wvp的api文档，里面有个设置布防的接口 你调用就好了

哦哦哦  看到了   调用过后确实是能收到报警推送了，不过只限海康的摄像头，华为的推送报错了说设备没有回复确认指令，我看了抓包日志确实也没有回复，但是华为的事件订阅是通的，大佬有测试过哪些摄像头呢。

**Comment by bigff-0527** [comment]
> > > > > 大哥 你现在有实现嘛 ，我目前也是需要这个事件订阅，测试了华为的设备推送事件推送了message 但是海康的没有任何反应
> > > > 
> > > > 
> > > > 设置布防，有api的 调用一下就好了
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/103352688/316373329-cb6944be-a55d-4863-b44f-59c1de51f04a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzU3OTEsIm5iZiI6MTcxMTMzNTQ5MSwicGF0aCI6Ii8xMDMzNTI2ODgvMzE2MzczMzI5LWNiNjk0NGJlLWE1NWQtNDg2My1iNDRmLTU5YzFkZTUxZjA0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMjU4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmZhYmZhZDhhOWNlZTgxMmI0ZTRmMmE0ZTAxNTkwZjczYTBhNzRhNWViODljODVjNjZlMmU1MDg1ZTY5ZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EbKLj0ghi1ut3ASnV-yRlTep904tKH8KGTX8f5DpZDY) 设置过布防 摄像头系统固件升级过支持报警服务器http通知 但是领导要求我调通国标的事件推送，头皮都大了
> > 
> > 
> > 不是指这个布防，你看wvp的api文档，里面有个设置布防的接口 你调用就好了
> 
> 哦哦哦 看到了 调用过后确实是能收到报警推送了，不过只限海康的摄像头，华为的推送报错了说设备没有回复确认指令，我看了抓包日志确实也没有回复，但是华为的事件订阅是通的，大佬有测试过哪些摄像头呢。

华为的好像也试过，都可以的 方便加个qq 后续一起交流吗

**Comment by guzijian123** [comment]
> > > > > > 大哥 你现在有实现嘛 ，我目前也是需要这个事件订阅，测试了华为的设备推送事件推送了message 但是海康的没有任何反应
> > > > > 
> > > > > 
> > > > > 设置布防，有api的 调用一下就好了
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/103352688/316373329-cb6944be-a55d-4863-b44f-59c1de51f04a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzU3OTEsIm5iZiI6MTcxMTMzNTQ5MSwicGF0aCI6Ii8xMDMzNTI2ODgvMzE2MzczMzI5LWNiNjk0NGJlLWE1NWQtNDg2My1iNDRmLTU5YzFkZTUxZjA0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMjU4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmZhYmZhZDhhOWNlZTgxMmI0ZTRmMmE0ZTAxNTkwZjczYTBhNzRhNWViODljODVjNjZlMmU1MDg1ZTY5ZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EbKLj0ghi1ut3ASnV-yRlTep904tKH8KGTX8f5DpZDY) 设置过布防 摄像头系统固件升级过支持报警服务器http通知 但是领导要求我调通国标的事件推送，头皮都大了
> > > 
> > > 
> > > 不是指这个布防，你看wvp的api文档，里面有个设置布防的接口 你调用就好了
> > 
> > 
> > 哦哦哦 看到了 调用过后确实是能收到报警推送了，不过只限海康的摄像头，华为的推送报错了说设备没有回复确认指令，我看了抓包日志确实也没有回复，但是华为的事件订阅是通的，大佬有测试过哪些摄像头呢。
> 
> 华为的好像也试过，都可以的 方便加个qq 后续一起交流吗

可以的  我的在我profile里有写  大哥直接加我就好了
