### ISSUE TITLE
分页查询报警接口存在bug

### ISSUE THREAD

**Issue by xiaoyongcss** [648540858/wvp-GB28181-pro#488]
**描述错误**
/api/alarm/all接口通过时间段查询，查询结果不匹配查询时间范围

**如何复现**
不用复现，其实问题很简单，收到设备报警通知xml内容中AlarmTime节点的时间格式是：2022-05-23T09:05:30这种数据，直接入库到表device_alarm的alarmTime字段上，而通过接口查询的时候又使用“ DateUtil.format.parse(endTime);”这个验证，所以通过时间查询就存在bug了

**预期行为**
入库不做时间格式验证，那接口查询就不要做

**Comment by 648540858** [comment]
已修复

**Comment by 648540858** [comment]
我这没支持报警的设备,劳驾做个测试
