### ISSUE TITLE
国标级联-实时预览功能

### ISSUE THREAD

**Issue by SNGxx** [648540858/wvp-GB28181-pro#49]
请问wvp-28181-2.0分支，国标级联-实时预览功能完成了吗，能否分享一下级联预览的交互流程
@lawrencehj

**Comment by SNGxx** [comment]
![gb-cascade](https://user-images.githubusercontent.com/11484496/106220118-c4c4d000-6215-11eb-81da-2ca0bda8ae2b.png)

**Comment by lawrencehj** [comment]
@648540858大佬已经在进行中了，请耐心等待

**Comment by SNGxx** [comment]
> @648540858大佬已经在进行中了，请耐心等待

dalao可否帮忙看下上面的流程对不对，
上级平台invite下级平台时，下级SIP服务器先建立设备->下级媒体服务器的推流，然后下级SIP服务器收到上级SIP服务器ACK之后，下级媒体服务器->上级媒体服务器推流。

**Comment by lawrencehj** [comment]
是的，根据上级sdp给出的地址让zlm推流

**Comment by 648540858** [comment]
2.0分支已经实现，可以测试下
