### ISSUE TITLE
无法获取录像回放列表

### ISSUE THREAD

**Issue by Luo-99** [648540858/wvp-GB28181-pro#495]
**描述错误**
部署服务上后,查询设备录像前端页面会一直转圈,本地部署没有这个问题,本地一切正常

**如何复现** 
100% 复现: wvp-pro最新版本 部署公网服务器, 查询有录像的日期, 一直转圈直至超时
我使用postMan直接调接口等待很久后得到结果为:
{
    "code": -1,
    "msg": "timeout",
    "data": null
}
查询没录像的日期不会出现这种情况,正常响应结果为:
{
  "code": 0,
  "msg": "success",
  "data": {
    "deviceId": "42010200492000000002",
    "channelId": null,
    "sn": "255848",
    "name": null,
    "sumNum": 0,
    "lastTime": "2022-05-27T02:16:23.162068Z",
    "recordList": []
  }
}

**预期行为**
查询设备录像,查看某一时段的录像
这个图是本地测试的结果
<img width="785" alt="正常" src="https://user-images.githubusercontent.com/22796879/170621226-dde1ec2b-8311-4aa7-8337-4856ca1a6e92.png">
这个图是公网服务器的结果
<img width="564" alt="公网结果" src="https://user-images.githubusercontent.com/22796879/170621309-4e8d87fe-ee36-4e57-ae19-72b58b7643ad.png">

**环境信息:**
 - 1.  部署方式: 
     mysql,redis.zlm都是docker并且以--network=host运行,服务器防火墙已关, wvp-pro最新版本 是直接jar 运行
 - 2. 部署环境: 
     公网Centos7 , 本地使用Windows跑wvp.jar,和Linux虚拟机Centos7跑wvp.jar都没这个情况只有公网有
 - 3.端口开放情况: 
     防火墙已经关闭
 - 4. 是否公网部署: 
     是
 - 5. 是否https: 
     否
 - 6. 设备信息: 
   TP-Link TL-IPC 43AW, 如果要测试,我可以让设备注册到你指定的公网服务器,本地测试是没问题的
 - 7. 你做过哪些尝试
   经过多次重复测试. 反复确认防火墙端口情况是否开放, 换了两台云服务器部署均出现以上问题
  群里也问过群友,好像他们也有一样的问题,这是直接调接口的图
<img width="780" alt="调接口" src="https://user-images.githubusercontent.com/22796879/170622936-be156624-e48f-4b48-a1a9-844a66e390ab.png">

**Comment by TristingChen** [comment]
1.tcpdump抓包+看日志 才能定位你这个问题，否者是看不到原因的
2.今日复现你这个问题，重启设备后成功
结论：
怀疑是设备接收sip信令除了bug

**Comment by 648540858** [comment]
抓包数据有误或者使用的不是wvp平台
![image](https://user-images.githubusercontent.com/18274453/170725457-748f9c37-937e-4816-9238-8f93816a94f1.png)

**Comment by ehharo** [comment]
Duplicate of #
aa.pcapng

**Comment by ehharo** [comment]
[aa.pcapng.zip](https://github.com/648540858/wvp-GB28181-pro/files/8790666/aa.pcapng.zip)
这里是我的抓包文件，请您帮忙看一下，遇到的问题和上面的兄弟是一样的；
监控器ip号：192.168.10.188
跑程序的机器ip：192.168.10.38
后台debug之后，package com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.RecordInfoResponseMessageHandler发现是能得到国标录像的数据；但是在“package com.genersoft.iot.vmp.vmanager.gb28181.record.GBRecordController下reslut没有给前端进行响应;”
![debug](https://user-images.githubusercontent.com/28237705/170815003-bf37fed6-d18b-4dac-a159-447385029ed1.jpg)
[[超长消息]2022-05-27 .pdf](https://github.com/648540858/wvp-GB28181-pro/files/8790679/2022-05-27.pdf)

**Comment by 648540858** [comment]
1. 自行修改了代码请不要提ISSUE，自行解决
