### ISSUE TITLE
wvp级联wvp,上级播放录像,seek点播进度条,无效. 没有seek到指定的位置

### ISSUE THREAD

**Issue by threadroc** [648540858/wvp-GB28181-pro#500]
**描述错误**
wvp级联wvp,上级wvp平台播放录像,seek点播进度条,无效. 没有seek到指定的位置,
调用API也不好用,不是播放器问题.

**如何复现**
100复现.

**预期行为**
点击seek进度条,录像能调到指定的时间.

**截图**

**环境信息:**
端口全开,ubuntu,2022.5.30日编译的最新版zlm和wvp.

**Comment by 648540858** [comment]
1. 建议找个商用平台区确定你的设备支持seek
2. 如果商用平台确认支持，请提供两者的抓包数据
只是这么说我什么都做不了。

等你可以提供信息再打开这个issue吧

**Comment by TrapCai** [comment]
请问下，你们wvp作为上级平台是怎么弄得。因为看文档上说的是"国标28181不同平台之间支持两种连接方式，平级和上下级，WVP目前支持向上级级联。"
