### ISSUE TITLE
okhttp-digest的Maven仓库地址需要调整

### ISSUE THREAD

**Issue by guthrunzhao** [648540858/wvp-GB28181-pro#506]
**描述错误**
项目pom文件中的okhttp-digest
```
<dependency>
    <groupId>com.burgstaller</groupId>
    <artifactId>okhttp-digest</artifactId>
    <version>2.1</version>
</dependency>
```
目前okhttp-digest的仓库位置已经调整，需要配套调整。否则无法正常下载。
参照okhttp-digest项目重要说明：https://github.com/rburgst/okhttp-digest#important

**如何复现**
第一次编译项目

**预期行为**
项目能正常编译和运行

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro / zlm(docker) + 编译wvp-pro
 - 2. 部署环境 windows / centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署  否
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
        根据okhttp-digest项目的说明，调整okhttp-digest的依赖为如下，可以正常编译运行。
```
	<dependency>
			<groupId>io.github.rburgst</groupId>
			<artifactId>okhttp-digest</artifactId>
			<version>2.7</version>
		</dependency>
```

**Comment by 648540858** [comment]
已修复
