### ISSUE TITLE
使用回放功能出现ssrc不匹配

### ISSUE THREAD

**Issue by TXJZQQBX** [648540858/wvp-GB28181-pro#507]
**描述错误**
wvp-pro作为上级平台接入科达平台，科达平台配置接入方式为互联。调用下级平台回放录像出现ssrc不匹配

**如何复现**
wvp录像回放--> 选择时间查询录像-->播放录像

**预期行为**
正常播放下级平台的录像回放

**截图**
<img width="1006" alt="截屏2022-06-03 18 03 26" src="https://user-images.githubusercontent.com/41613320/171833789-4fb6aa1d-702c-4f84-89b7-11015693c4a4.png">

**环境信息:**
 - 1. 部署方式 
 wvp-pro docker / zlm(docker) 

 - 2. 部署环境 
 centos

 - 3. 端口开放情况 
 30000-30500

 - 4. 是否是公网部署 
 否

 - 5. 是否使用https
 否

 - 6. 方便的话提供下使用的设备品牌或平台
 科达平台，设备科达、海康、大华

 - 7. 你做过哪些尝试
 有看过关于ssrc的issue，无法重启监控设备进行尝试

**Comment by 648540858** [comment]
补充下抓包文件

**Comment by TXJZQQBX** [comment]
作者你好，zlmediakit作者回答说端口问题，我不太理解具体指的是我的wvpPro的rtp，port-range属性没配置正确吗

**Comment by TXJZQQBX** [comment]
我应该找到了具体问题，回放录像的时候下级平台自定义了ssrc

> 补充下抓包文件
