### ISSUE TITLE
DeviceChannelMapper queryChannels 方法sql错误

### ISSUE THREAD

**Issue by 845999248** [648540858/wvp-GB28181-pro#508]
@Select(value = {" <script>" +
            "SELECT " +
            "dc.* " +
            "from " +
            "device_channel dc " +
            "WHERE " +
            "dc.device_id = #{deviceId} " +
            " <if test='query != null'> AND (dc.channel_id LIKE '%${query}%' OR dc.name LIKE '%${query}%' OR dc.name LIKE '%${query}%')</if> " +
            " <if test='parentChannelId != null'> AND dc.parent_id=#{parentChannelId} </if> " +
            " <if test='online == true' > AND dc.status=1</if>" +
            " <if test='online == false' > AND dc.status=0</if>" +
            " <if test='hasSubChannel == true' >  AND dc.sub_count > 0 </if>" +
            " <if test='hasSubChannel == false' >  AND dc.sub_count = 0 </if>" +
            "GROUP BY dc.channel_id " +
            " </script>"})
    List<DeviceChannel> queryChannels(String deviceId, String parentChannelId, String query, Boolean hasSubChannel, Boolean online);

 "GROUP BY  错误

**Comment by 648540858** [comment]
你确定下你的代码版本，我在当前代码没找到你说的内容
queryChannels目前与描述的不同。

**Comment by 845999248** [comment]
https://github.com/648540858/wvp-GB28181-pro/blob/wvp-28181-2.0/src/main/java/com/genersoft/iot/vmp/storager/dao/DeviceChannelMapper.java. 70行，确认一下对不？

**Comment by 845999248** [comment]
https://github.com/648540858/wvp-GB28181-pro/blob/2.6.3/src/main/java/com/genersoft/iot/vmp/storager/dao/DeviceChannelMapper.java   这个也是70行  ，我不知道你说的当前版本是哪个分支
