### ISSUE TITLE
4G摄像头公网上云的推流地址无法播放

### ISSUE THREAD

**Issue by 15927566740** [648540858/wvp-GB28181-pro#514]
**描述错误**
4G摄像头阿里云接入，play/start/deviceid/channelid接口开始点播GET的url地址不是rtp/deviceid_channelid格式，而是如开始视频回放接口一样转出了一个ssrc，得到的url是rtp/ssrc格式。此时前端页面可以播放，但获取的url无法在本地端通过vlc等播放，尝试了rtp/ssrc和rtp/deviceid_channelid格式均不行。

**如何复现**
4G摄像头公网接入阿里云，开始点播获取推流url，本地端vlc播放。

**预期行为**
希望公网接入可以如本地端一般，推流地址为rtp/deviceid_channelid格式，且能vlc播放。或者作者大大告诉我应该如何在本地端播放。

**截图**
![c59d8b7d1b7562b43eccc7dc889fa1c](https://user-images.githubusercontent.com/48681680/173295454-921e008e-92a9-4f92-a788-4652fa6245db.png)

**环境信息:**
 - 1. 部署方式  wvp-prp + zlm都是编译部署/
 - 2. 部署环境   centos ...
 - 3. 端口开放情况  18080tcp、5060tcpudp、1180tcp、10000tcpudp
 - 4. 是否是公网部署  是
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台   海康摄像头
 - 7. 你做过哪些尝试   本地端接入无问题

**Comment by 15927566740** [comment]
> 
![1655103045(1)](https://user-images.githubusercontent.com/48681680/173296534-78086e69-a9e2-4ab9-837b-a302956f399f.jpg)

**Comment by 648540858** [comment]
出现不是固定地址那是因为你使用了单端口收流，自己阅读wiki配置吧

**Comment by 15927566740** [comment]
> 出现不是固定地址那是因为你使用了单端口收流，自己阅读wiki配置吧

好的。那再请问一下，单端口收流的情况需要哪种格式才能本地端vlc播放
