### ISSUE TITLE
media.id问题，打印的日志中的id和自己填写的不是同一个

### ISSUE THREAD

**Issue by duankeke** [648540858/wvp-GB28181-pro#515]
**描述错误**
我也有这个问题，就是我的media.id和zlm的ZLM的general.mediaServerId，是一样的，但是java启动程序的时候，查数据库总是是另一个id。导致连接不上zlm，
打印信息： 
executed. 1.522084 millis. SELECT * FROM media_server WHERE id='O5e7OSQWZuuNdwHU'
 [未注册的zlm] 拒接接入：O5e7OSQWZuuNdwHU来自192.168.10.217：6080
请检查ZLM的<general.mediaServerId>配置是否与WVP的<media.id>一致

这个不会是随机生成的吧：O5e7OSQWZuuNdwHU，代码中也没看到写死

**如何复现**
正常下拉最新代码，配置好参数

**预期行为**
正常运行，旧版本是是正常的，今天突然升级了一下，然后在media.id这里过不去了

**环境信息:**
 - 1. 部署方式  编译wvp-pro / zlm(docker)
 - 2. 部署环境 centos7
 - 3. 端口全开
 - 4. 内网部署
 - 5. http
 - 6. 海康摄像头
 - 7. 删除数据库、删除redis

**Comment by 648540858** [comment]
这个是以配置文件为准，启动时会从配置文件读取然后写入数据库，如果zlm你的配置文件没有写这个那么第一次启动zlm会为你自动生成

**Comment by 648540858** [comment]
你的问你原因是你使用了docker部署zlm但是不可能没有为zlm配置卷，导致zlm的配置文件无法存储在磁盘，你每次重启容器都相当于第一次启动zlm，每次的id自然就不同了

**Comment by duankeke** [comment]
这是我的zlm docker配置信息，我是有映射的，然后我在调试代码的时候，在ZLMRunner.java的connectZlmServer类里面打印mediaServerItem.getId()获取的是zlm里面的配置文件中的general.mediaServerId参数，但是继续执行，打印zlmServerConfigFirst里面的id的时候，就是随机的了，除非我加一行代码：zlmServerConfigFirst.setGeneralMediaServerId(mediaServerItem.getId())
zlm:
      image: panjjo/zlmediakit:latest
      container_name: iotos_zlm
      privileged: true
      restart: always
      command: bash -c './zlmediakit/MediaServer -c /zlmediakit/zlm/zlm_conf.ini'
      volumes:
        - /data/iotsay/_script/zlm:/zlmediakit/zlm
      ports:
        - 6080:80
        - 10443:443
        - 10935:1935
        - 10554:554
        - 10554:554/udp
        - 10332:332
        - 10332:332/udp
        - 10010:10000
        - 10010:10000/udp
        - 30000-30500:30000-30500/udp
        - 30000-30500:30000-30500/tcp

**Comment by 648540858** [comment]
zlmServerConfigFirst也是通过访问zlm接口来
