### ISSUE TITLE
多个摄像头重启后视频有窜流的问题

### ISSUE THREAD

**Issue by buer1988** [648540858/wvp-GB28181-pro#516]
**描述错误**
描述下您遇到的问题
多个摄像头重启后视频有窜流的问题

**如何复现**
有明确复现步骤的问题会很容易被解决
12个摄像头在局域网，wvp在公网，在正常接入后，对12个摄像头掉电上电重启，后面再进行播放，会出现窜流的问题

**预期行为**
清晰简洁的描述您期望发生的事情
期望接入的摄像头，在断电后，恢复来电后，可以正常的播放视频

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - wvp-pro docker
 - 2. 部署环境 windows / ubuntu/ centos ...
 - centos7.9
 - 3. 端口开放情况
 - 正常开放
 - 4. 是否是公网部署
 - 是公网部署
 - 5. 是否使用https
 - 有使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 海康
 - 7. 你做过哪些尝试
 - 主动断流，主动断流后可以点播正常

**Comment by 648540858** [comment]
使用的哪个版本的docker

**Comment by TristingChen** [comment]
一定要开启设备的ssrc校验，这个可以很好的解决，但是解决不了设备还在推的问题；  等作者优化好播放时候 bye指令发送的问题吧

**Comment by 648540858** [comment]
可以测试下了
