### ISSUE TITLE
录像回放、录像下载新增ssrc校验

### ISSUE THREAD

**Issue by TXJZQQBX** [648540858/wvp-GB28181-pro#518]
playback，download是否也可以考虑跟play一样进行ssrc校验呢，如果实时点播存在下级自定义ssrc，对于录像回放和录像下载也是可能存在的
![play](https://user-images.githubusercontent.com/41613320/173765565-5b8a5626-5671-4795-bbfa-cf9992bbf668.jpg)

**Comment by 648540858** [comment]
明白 我考虑下

**Comment by 648540858** [comment]
已解决，使用新代码测试下，我先关闭了
