### ISSUE TITLE
云端录像中，选择视频片段无法播放

### ISSUE THREAD

**Issue by hongcaohu** [648540858/wvp-GB28181-pro#519]
**描述错误**
云端录像成功，生成了MP4文件，但是在“云端录像”查看录像时，播放控件无法播放，浏览器console报错，请求mp4返回 206 Partial Content

**如何复现**
云端录像—选择日期—选择一个时间片段

**预期行为**
播放器可以播放所选择时间片段的 mp4视频

**截图**
![image](https://user-images.githubusercontent.com/15919714/173779414-0948f9df-4ff8-4c9c-abeb-44e1a4e7600d.png)
![image](https://user-images.githubusercontent.com/15919714/173777300-1befee93-575e-463b-b3ec-6dd06e71efb6.png)

**环境信息:**
 - 1. 部署方式  编译wvp-pro + zlm都是编译部署
 - 2. 部署环境  centos7
 - 3. 端口开放情况  
      zlmediakit http: 8080, rtp: 40000-40500, wvp-pro: 18081, record-asist: 18082
 - 4. 是否是公网部署
      是公网部署，其他功能都正常
 - 5. 是否使用https
      没有使用https

**Comment by 648540858** [comment]
使用的什么浏览器。播放的视频是什么便编码格式。

**Comment by hongcaohu** [comment]
用的chrome，看了下版本，最新版本 102.0.5005.115（正式版本） （64 位），相机端的编码设置 H264，试了H265也是一样
刚刚用firfox 试了下，报错如下，感觉好像是编码问题，难道是浏览器版本问题吗
![image](https://user-images.githubusercontent.com/15919714/174207976-f26a1905-9f2b-4d67-9bf6-9d500ad9b155.png)

**Comment by hongcaohu** [comment]
我刚刚下了一个360浏览器，可以正常播放，看来还是浏览器解码问题
