### ISSUE TITLE
无法获取视频的编码

### ISSUE THREAD

**Issue by kson34** [648540858/wvp-GB28181-pro#520]
**描述错误**
20220616下载官方最新源码，发现无法获取视频的编码
以前2022年1月份下载 的源码可以获取。
zlm也是今天下载的最新版本，在ubuntu下编译运行的。

**截图**
![image](https://user-images.githubusercontent.com/17976520/174026335-08f16145-ed93-4a67-91bf-d99d787f1cbc.png)

**环境信息:**
zlm也是今天下载的最新版本，在ubuntu下编译运行的。
WVP为20220616下载官方最新源码。

**Comment by 648540858** [comment]
等视频开始播放了再去看编码信息。
