### ISSUE TITLE
编译时候报错

### ISSUE THREAD

**Issue by Androad** [648540858/wvp-GB28181-pro#521]
**描述错误**
描述下您遇到的问题
root@ubuntu:/home/xman/wvp-GB28181-pro/web_src# npm --registry=https://registry.npm.taobao.org install
npm ERR! Cannot read property 'insert' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-16T10_59_51_679Z-debug-0.log
root@ubuntu:/home/xman/wvp-GB28181-pro/web_src# npm --registry=https://registry.npm.taobao.org install
npm ERR! Cannot read property 'insert' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-16T11_00_58_451Z-debug-0.log
root@ubuntu:/home/xman/wvp-GB28181-pro/web_src# npm --registry=https://registry.npm.taobao.org install
npm ERR! Cannot read property 'insert' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-16T11_01_07_390Z-debug-0.log
root@ubuntu:/home/xman/wvp-GB28181-pro/web_src# npm --registry=https://registry.npm.taobao.org install
npm ERR! Cannot read property 'insert' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-16T11_03_49_298Z-debug-0.log
root@ubuntu:/home/xman/wvp-GB28181-pro/web_src# vi /root/.npm/_logs/2022-06-16T11_03_49_298Z-debug-0.log

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 编译wvp-pro/
 - 2. ubuntu 22.04 lts
 - 3. 端口开放情况
 - 4. 是否是公网部署 no
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
确定你安装的是最新版本的npm
