### ISSUE TITLE
视频回放，录像推送结束，发送Bye摄像机无响应。

### ISSUE THREAD

**Issue by mk1990** [648540858/wvp-GB28181-pro#525]
**描述错误**
视频回放页面，点击视频播放按钮回放视频，视频播放结束MediaStatusNotifyMessageHandler接收到推流结束信令，调用89行                cmder.streamByeCmd(device.getDeviceId(), ssrcTransaction.getChannelId(), null, callIdHeader.getCallId()); 发送BYE信令结束此次会话，摄像机没有回复200 OK，超时。 多次回放视频后，摄像机收到ACK信令后直接返回BYE。摄像机品牌为海康。

**如何复现**
国标设备--> 设备录像 --> 录像查询 --> 播放列表 --> 点击播放按钮， 等待视频播放完成，会收到MediaStatus。

**预期行为**
1. 摄像机能正常响应BYE信令，返回200OK；
2. 多次播放能够正常播放。

**截图**
![视频回放](https://user-images.githubusercontent.com/37614016/174261353-7685a750-fefd-474e-a88c-f52ae2cdc4f7.PNG)
![视频回放1](https://user-images.githubusercontent.com/37614016/174261367-b6dc1dff-dcc0-4eba-a338-36948f710819.PNG)

**环境信息:**
 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 windows
 - 3. 端口开放情况
 - 4. 是否是公网部署（否）
 - 5. 是否使用https（否）
 - 6.  使用海康的摄像机
测试使用了虚拟机，所以抓包时有重复的包，可以忽略重复的包。

**Comment by mk1990** [comment]
切换倍速或者seek会出现上述问题，正常倍速播放不会出现上述问题。

**Comment by 648540858** [comment]
更新试试
