### ISSUE TITLE
国标回放 ：录像文件只能推一路回放流

### ISSUE THREAD

**Issue by sxh-netizen** [648540858/wvp-GB28181-pro#526]
**描述错误**
国标回放时录像文件只能推一路回放流

**如何复现**
查看回放录像即可

**预期行为**
国标回放 录像文件可以同时让多人访问

**截图**

**环境信息:**
 - 1. 编译wvp-pro + zlm都是编译部署
 - 2. 欧拉系统
 - 3. 端口都已开放
 - 4. 是公网部署
 - 5. 使用https
 - 6. 天视通IPC

**Comment by 648540858** [comment]
wvp 支持多人访问录像，但是一般的摄像头只能同时推一路，

**Comment by sxh-netizen** [comment]
好的，谢谢
