### ISSUE TITLE
RTP推流器断开是什么原因

### ISSUE THREAD

**Issue by liangliang996** [648540858/wvp-GB28181-pro#529]
1.将media.streamNoneReaderDelayMS参数设置为-1
2.点击国标设备，播放，然后关闭弹窗弹窗
正常应该是一直录像，每一个小时分割一个MP4文件。
现在现象是每次播放之后，第一个小时的视频是正常的，但是到录制第二个视频时，会在中间出现停止录制的情况，打印zlmediakit日志发现推流器断开，中间确定没有其他操作，不知道RTP推流器断开是哪些原因会引起
RtpSelector.cpp:109 onManager | RtpProcess timeout:21010100001320000005_21010400491320000099
TcpServer.cpp:36 ~TcpServer | close tcp server 0.0.0.0:30007
RtpProcess.cpp:51 ~RtpProcess | 21010100001320000005_21010400491320000099(175.164.86.138:15060)
 RTP推流器(__defaultVhost__/rtp/21010100001320000005_21010400491320000099)断开,耗时(s):5408
MediaSource.cpp:414 emitEvent | 媒体注销:hls __defaultVhost__ rtp 21010100001320000005_21010400491320000099
MediaSource.cpp:414 emitEvent | 媒体注销:ts __defaultVhost__ rtp 21010100001320000005_21010400491320000099
MediaSource.cpp:414 emitEvent | 媒体注销:rtsp __defaultVhost__ rtp 21010100001320000005_21010400491320000099
MediaSource.cpp:414 emitEvent | 媒体注销:rtmp __defaultVhost__ rtp 21010100001320000005_21010400491320000099
MediaSource.cpp:414 emitEvent | 媒体注销:fmp4 __defaultVhost__ rtp 21010100001320000005_21010400491320000099

**Comment by chdahuzi** [comment]
hi，请问下问题解决了，是什么原因造成的

**Comment by liangliang996** [comment]
> 

没解决，好像和网络有关系
