### ISSUE TITLE
安装提示Cannot read property 'insert' of undefined

### ISSUE THREAD

**Issue by goodcat111** [648540858/wvp-GB28181-pro#531]
**描述错误**
描述下您遇到的问题
编译到npm --registry=https://registry.npm.taobao.org install
出现提示
npm ERR! Cannot read property 'insert' of undefined

**如何复现**
操作系统，ubuntu20.04
:~/wvp-GB28181-pro/web_src$ npm --registry=https://registry.npmmirror.com install
npm WARN deprecated fingerprintjs2@2.1.2: Package has been renamed to @fingerprintjs/fingerprintjs. Install @fingerprintjs/fingerprintjs to get updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm ERR! Cannot read property 'insert' of undefined

npm ERR! A complete log of this run can be found in:

换了所有的npm镜像均为同样的问题

**预期行为**
清晰简洁的描述您期望发生的事情

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
vvp-GB28181-pro编译部署
 - 2. 部署环境 windows / ubuntu/ centos ...
 - ubuntu 20.04
maven 已经是最新版 (3.6.3-5)。
nodejs 已经是最新版 (12.22.9~dfsg-1ubuntu3)。
npm 已经是最新版 (8.5.1~ds-1)。
git 已经是最新版 (1:2.34.1-1ubuntu1.2)。
openjdk-11-jre 已经是最新版 (11.0.15+10-0ubuntu0.22.04.1)。

 - 3. 端口开放情况
 -防火墙已关闭
 - 4. 是否是公网部署
 - 内网电脑
 - 5. 是否使用https
 - 是
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
替换了所有npm源，无效
升级了node

**Comment by BradyXs** [comment]
使用yarn试试吧

**Comment by Azreulo** [comment]
同样的错误，请教如何解决。

**Comment by 648540858** [comment]
npm安装依赖一般都是网络问题，确定npm node为最新版的基础上，检查下网络环境吧
