### ISSUE TITLE
wvp作为下级推送设备的状态问题

### ISSUE THREAD

**Issue by KelvinHuangGit** [648540858/wvp-GB28181-pro#532]
**描述错误**
wvp作为下级平台往上级推送设备，设备离线在上级仍旧在线。

**如何复现**
1、在国标设备栏显示离线
![image](https://user-images.githubusercontent.com/46700520/175873460-7ccba28d-8e98-4a41-9b8f-6d4e439e74d0.png)
2、在国标平台推送设备通道的时候仍旧在线，上级看到的设备状态也是在线
![image](https://user-images.githubusercontent.com/46700520/175874016-26220bc3-85c9-4f9f-8167-91858e6f1c40.png)

**预期行为**
当下级设备离线的时候同步设备状态到上级平台

**截图**
在这块推送设备的时候，也显示为离线，上级也能看到设备离线
https://user-images.githubusercontent.com/46700520/175874016-26220bc3-85c9-4f9f-8167-91858e6f1c40.png

**环境信息:**
 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境ubuntu
 - 3. 端口开放情况 全开放
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 任意设备均可都有这个问题
 - 7. 你做过哪些尝试 设备上下线与wvp的设备状态目录对比，上级的设备在线情况查看

**Comment by 648540858** [comment]
确实存在这个问题，

**Comment by KelvinHuangGit** [comment]
那有时间修复一下喔，我也希望wvp能越来越好

**Comment by 648540858** [comment]
好的，有时间的话，一起来开发吧。

**Comment by KelvinHuangGit** [comment]
好嘞

**Comment by 648540858** [comment]
#1417
