### ISSUE TITLE
docker无法部署

### ISSUE THREAD

**Issue by liuhqsir** [648540858/wvp-GB28181-pro#534]
**描述错误**
在使用docker部署的时候会出现交互，无法进行

**如何复现**
git后在docker目录进行docker-compose up
**预期行为**
预期应该部署完成

**截图**
![image](https://user-images.githubusercontent.com/58692168/176140579-4bacc746-47d1-43f6-b98d-f2e7eedb74af.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker
 - 2. 部署环境centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署    否
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

使用容器就是为了方便部署，如果在每次都需要重新在容器进行编译安装，有背容器的使用理念吧！

**Comment by liuhqsir** [comment]
看issues列表的时候看有个648540858/wvp_pro镜像，就不管了

**Comment by Smallwhitepig** [comment]
建议自己编译部署,因为都是大块头,进QQ群什么资料都有了
