### ISSUE TITLE
queryChannelListInAll 方法sql错误

### ISSUE THREAD

**Issue by 845999248** [648540858/wvp-GB28181-pro#535]
catalogId == null 时 会有重复无数据产生

**Comment by 845999248** [comment]
![image](https://user-images.githubusercontent.com/23208554/176806546-7ec50267-bddc-467d-a465-7a87c1a8e7bf.png)

**Comment by 845999248** [comment]
![image](https://user-images.githubusercontent.com/23208554/176806655-3fe22f15-7b82-4519-94df-11b0be563239.png)

**Comment by 648540858** [comment]
好的 我看下
