### ISSUE TITLE
通用前端控制命令front_end_command接口里面的指令码、组合码、数据是什么含义哪里有说明吗？

### ISSUE THREAD

**Issue by 15927566740** [648540858/wvp-GB28181-pro#536]
**描述错误**
在测试预置位控制时发现front_end_command接口里面的指令码cmdCode、组合码combindCode、数据parameter1/2没有说明，翻遍wiki、群文件也没找到，请问有相关的对应参数说明吗？烦请大佬指个路。

**如何复现**
/api/ptz/front_end_command/{deviceId}/{channelId}

**预期行为**
此接口的相关参数说明

**截图**
![QQ图片20220701111752](https://user-images.githubusercontent.com/48681680/176816782-3cdb7ba8-70a7-4ad5-8b51-08c0395acd4c.jpg)

**环境信息:**
 - 1. 部署方式 wvp-prp + zlm都是编译部署/
 - 2. 部署环境 redhat
 - 3. 端口开放情况  全部
 - 4. 是否是公网部署  否
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台  海康
 - 7. 你做过哪些尝试    大概能确定cmdCode为129、130以及parameter2的含义，但仅此而已。。。

**Comment by 648540858** [comment]
国标文档有相关的说明，附录A 下的A.3 前端设备控制协议
