### ISSUE TITLE
ZLM保活失败：未找到流媒体信息

### ISSUE THREAD

**Issue by Zzt1993** [648540858/wvp-GB28181-pro#537]
描述错误
在使用过程中，摄像头离线停止推流之后，发现WVP控制台输出【更新ZLM 保活信息】失败，未找到流媒体信息！

如何复现
定时大概10分钟左右，即出现该问题（即使未注册摄像头）

通过代码发现，流媒体信息是被存储在Redis中且存储时过期策略为-1【永不过期】，但是错误出现之后回到Redis中
查看，发现ONLINE的ZLM信息被清除了。通过代码发现，ZLMRunner中会执行删除配置的操作，到这里我，我就想
是不是我的配置有问题或者我的操作有问题，于是我跟wiki中的配置进行对比，实在没找到什么问题。操作上双手离开
键盘不进行任何操作，WVP服务也会出现该提示。到这里我就找不到问题了，于是来此进行厚颜请教

重启WVP可以让ZLM上线

![image](https://user-images.githubusercontent.com/95836616/176856793-5706c9fc-ab0b-434f-bd0a-723d72e5bdb6.png)

**Comment by 648540858** [comment]
1. 先看一下提问规范
2. 是否是最新的代码，看下代码的修订号
