### ISSUE TITLE
运行java -jar wvp-pro-*.jar报错

### ISSUE THREAD

**Issue by TD-GC** [648540858/wvp-GB28181-pro#539]
# 配置环境：
系统：Ubuntu18.04

# 安装过程记录
#WVP-PRO+ZLMediaKit

1-- 安装依赖环境
apt-get install openjdk-11-jre git maven nodejs npm

2-- 编译WVP-PRO
#2-1 下载源码
git clone https://gitee.com/pan648540858/wvp-GB28181-pro.git

#2-2 编译静态页面
cd wvp-GB28181-pro/web_src/
npm --registry=https://registry.npm.taobao.org install
npm run build # 编译完成后在wvp-GB28181-pro/src/main/resources下出现static目录

#2-3 打包项目，生成可执行jar
cd wvp-GB28181-pro
mvn package  #时间较长，耐心等待
#编译完成后在target目录下出现wvp-pro-x.x-xxxxxxxx.jar

3-- 编译ZLMediaKit
已成功安装！

4-- 启动WVP项目
#4-1 先启动ZLM（以守护进程模式启动）
./MediaServer -d &

#4-2 启动WVP
mv wvp-GB28181-pro/src/main/resources/application-dev.yml wvp-GB28181-pro/target/application.yml 
cd wvp-GB28181-pro/target
java -jar wvp-pro-*.jar
”

# 参考wiki的安装步骤进行安装 [wiki安装步骤](https://github.com/648540858/wvp-GB28181-pro/wiki/%E7%BC%96%E8%AF%91%E8%BF%90%E8%A1%8C#%E7%BC%96%E8%AF%91wvp-pro)

# 报错截图
![image](https://user-images.githubusercontent.com/50939145/177314363-7f6d3ec1-e749-4a9f-aad4-7456c96a7e85.png)

# 配置文件截图
![image](https://user-images.githubusercontent.com/50939145/177314554-ba16fa9a-3870-4a1d-981c-0d6003e4f4dd.png)
![image](https://user-images.githubusercontent.com/50939145/177314593-05b92c1b-d8de-4ebc-8ce5-15c08d3cc7e3.png)

# ZLMediaKit能顺利启动
![image](https://user-images.githubusercontent.com/50939145/177314714-3a503be4-ddef-47e5-bdb9-df750908da07.png)

# 确保了配置文件的两部分内容
![image](https://user-images.githubusercontent.com/50939145/177314829-921cc640-7f4d-4e4e-8d2f-4ab25e0ef28d.png)

观看其它issue，怀疑是数据库mysql的配置问题，但不知道如何解决，望告知，万分感谢！！

**Comment by 648540858** [comment]
检查wvp中的数据库连接配置，这是一个极其基本的东西。看报错就已经很清楚了。下次还是先自查一下吧。
