### ISSUE TITLE
设备点播时出现被叫方返回bye导致sip481错误

### ISSUE THREAD

**Issue by wuxinfuchen** [648540858/wvp-GB28181-pro#540]
**描述错误**
设备点播时出现被叫方返回bye导致sip481错误

**如何复现**
设备注册上后，点播一直没有问题，时间长了，进行点播后台显示错误sip481

**预期行为**
暂无

**截图**
![QQ图片20220712100808](https://user-images.githubusercontent.com/109120899/178393266-e5dfd992-64b0-4fe5-9130-3b4cd4a85c4f.png)

![QQ图片20220712100945](https://user-images.githubusercontent.com/109120899/178393494-c8940349-e561-4d53-8da7-c6439dab0767.png)

![QQ图片20220712101141](https://user-images.githubusercontent.com/109120899/178393729-3f5edec1-35f8-4f96-9b16-30251f363003.png)

**环境信息:**
 - 1. 编译：wvp-pro/ wvp-prp + zlm部署
 - 2. 部署环境：centos
 - 3. 端口开放情况 ：按照文档都进行开放
 - 4. 是否是公网部署：是的
 - 5. 是否使用https ：否
 - 6. 方便的话提供下使用的设备品牌或平台 ：海康设备
 - 7. 你做过哪些尝试 ：进行设备重新注册，查询错误原因，被叫方返回bye导致sip错误码481

**Comment by 648540858** [comment]
应该不影响功能的
