### ISSUE TITLE
海康nvr 上报信息 address包含 0x01字符，导致xml解析失败

### ISSUE THREAD

**Issue by beiliubei** [648540858/wvp-GB28181-pro#541]
**描述错误**
描述下您遇到的问题

海康nvr 上报信息 address包含 0x01字符

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
在解析xml之前，是否可以对 result做一个过滤

**截图**

![image](https://user-images.githubusercontent.com/1127875/178436297-60bb4ab6-b996-4896-89f2-1d78ca56d803.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
添加判断调整
if (rawContent[i] > 8) {
    result.add(rawContent[i]);
}

**Comment by 648540858** [comment]
可否提供下抓包文件

**Comment by beiliubei** [comment]
[32.pcap.zip](https://github.com/648540858/wvp-GB28181-pro/files/9099150/32.pcap.zip)
抓包文件；
使用的 sngrep 抓包生成的

**Comment by 648540858** [comment]
我看下 谢谢

**Comment by 648540858** [comment]
这是海康的错误，不是wvp的，我不打算做这种兼容了，建议你找客服获取新的固件，如果仍有问题，建议你试试大华的，信令要好好很多。
