### ISSUE TITLE
ZLMHttpHookSubscribe内存溢出问题以及ssrc全量存储占用大量内存

### ISSUE THREAD

**Issue by tastypinenut** [648540858/wvp-GB28181-pro#546]
**描述错误**
ZLMHttpHookSubscribe似乎没有完全remove subscribe的event，导致运行一段时间后内存溢出
wvp打包版本CommitId为db865cc9 # 453

**如何复现**
反复进行摄像头播放

**预期行为**

**截图**
dump文件分析结果：
![lALPJwKtz-sXc93NAm3NA8s_971_621](https://user-images.githubusercontent.com/8178597/179142312-70af81ce-d91a-4f3a-a320-28ff10d56794.png)

addSubscribe方法发现有多处调用，但下图中removeSubscribe方法只有一处被调用，是造成map中的元素没有被清理的根本原因
![image](https://user-images.githubusercontent.com/8178597/179142369-2263b10e-0b50-4237-88ba-3f3e5a4b558f.png)
![image](https://user-images.githubusercontent.com/8178597/179143710-9e6f4198-5987-4f60-9e5f-a872f1407eaf.png)

最新源码中也没有解决这个问题

**环境信息:**
 - 1. 部署方式 wvp-pro / zlm 
 - 2. 部署环境 centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
好的 我考虑怎么解决它

**Comment by xiaoyongcss** [comment]
![image](https://user-images.githubusercontent.com/16200678/180160013-378a8920-bed7-46e0-a55d-8746e15e1d2a.png)
我们这有400多个摄像头，拉了下内存，发现这个ssrc有点问题

**Comment by 648540858** [comment]
hook订阅确实可能·存在问题，可能跟后面机制优化的时候一起优化；
ssrc因为默认把所有的都生成存起来了，所以确实比较大，这个后面也可以优化下。

**Comment by 648540858** [comment]
hook问题已经修复你可以测试下

**Comment by 648540858** [comment]
我先关闭了。

**Comment by XuXuebin** [comment]
这个问题还存在
![image](https://user-images.githubusercontent.com/863431/185274893-315cb5fe-48d0-4a31-a835-38a05ee937ab.png)
