### ISSUE TITLE
多网段无法同时点播

### ISSUE THREAD

**Issue by Rance-Zhang** [648540858/wvp-GB28181-pro#547]
**描述错误**
当存在多个不互通网络时，zlm仅可在对应一个网络，造成无法同时点播不同网段的视频

**如何复现**
在wvp所在设备启用多张网卡或是同一网卡配多个IP连接到不同网络，由于下级NVR、IPC等对应到zlm需要不同网段的地址，wvp在进行三方会话时并不会区分设备对应的网段，因此造成只有一个网段设备可正常收流。

**预期行为**
设备增加所属网域字段，wvp可根据此字段选择与之对应的zlm节点。这样一来就可以通过部署多个不同sdp_ip的zlm解决多网段同时取流的问题

**环境信息:**
 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 archlinux
 - 3. 端口无限无限制
 - 4. 非公网部署，但存在多个私网网段
 - 5. 是否使用https 未使用
 - 6. 使用海康NVR8600与9600、摄像头
 - 7. 偿试通过部署多个处于不同网段的zlm上wvp匹配使用，但偿试后发现wvp中设置多个节点更类似于负载均衡，而并非理解中的跨网络传输的网络结点

**Comment by 648540858** [comment]
目前返回的流地址只有一个，因为wvp和zlm支持分开部署所以无法根据你请求wvp的ip作为zlm的ip，也就无法根据请求的来源来支持多网段自适应了。你有更好的思路也可以提供给我。

**Comment by 648540858** [comment]
我无法把多个ip认为时一个网段的，比如192.168.1.4和192.168.2.3，或许他们是一个网段，但是我没有判断的依据，有的时候服务器是192.但是来源是10，但他们可能也是一个网段。

**Comment by Rance-Zhang** [comment]
我回复了邮件，但貌似我的邮件服务器没能通过伟大的墙到git。非常感谢您能在百忙之中回复，由于网络结构的复杂性，住住会使用多个路由进行网络的分割与组合，这使得无法通过请求者、媒体服务器、流发送者三人的IP来计算出网域的关系，既然无法自动匹配，何不通过人为指定流发送者与媒体服务器的关系，先通过这样的绑定关系解决三方（请求者、媒体服务器、流发送者）会话能正常的建立。之后可通过在部署媒体服务器的节点上通过指定路由使媒体服务可与请求者网络打通，如此可解决多网段不同zlm返回SDP_IP不同，无法将正确的SDP_IP通知给请求者问题。不知可否，仅供参考

**Comment by Rance-Zhang** [comment]
非常感谢，按建议进行了测试，zlm运行正常。

**Comment by keehub** [comment]
现在来看，wvp内有好的解决方法吗
