### ISSUE TITLE
前端项目打包部署问题

### ISSUE THREAD

**Issue by DinghengHao** [648540858/wvp-GB28181-pro#551]
想请问一下这个前端项目怎么打成dist包呢？我想部署在服务器上。

**Comment by 648540858** [comment]
resources/static 就是之前的dist

**Comment by DinghengHao** [comment]
嗯， 问题已解决 ， 因为我把前端项目独立出来了，造成打包好的dist文件找不到了。改下这个配置就好了 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/45813805/180342619-1912854e-35c7-4be3-8c76-306c618080d4.png">
