### ISSUE TITLE
关于设备目录订阅

### ISSUE THREAD

**Issue by sxh-netizen** [648540858/wvp-GB28181-pro#553]
**描述错误**
设备目录订阅经常失败，偶尔会成功一两次，但是当成功的时候还是无法感知设备通道的 上下线状态

**如何复现**
直接在设备修改中添加设备订阅即可

**预期行为**
希望wvp能够感知到设备通道的上下线状态

**截图**
![image](https://user-images.githubusercontent.com/58098910/180588157-ddaf4b5a-b843-4dfb-a9cc-769c9341c186.png)
![image](https://user-images.githubusercontent.com/58098910/180588176-064bfecb-ae80-43b1-8568-db5ad2227879.png)
![image](https://user-images.githubusercontent.com/58098910/180588196-d490ca0b-29b1-426c-95a6-7ba24729bb78.png)

**环境信息:**
 - 1. 部署方式  wvp-pro/ + zlm都是编译部署
 - 2. 部署环境 wvp是win，zlm是linux
 - 3. 端口都已开放
 - 4. 公网部署
 - 5. 使用https
 - 6. 设备品牌： 海康nvr(iDS-7908NX-K4/FA(B))

**Comment by 648540858** [comment]
目录订阅与设备上线下无关，与通道上下线有关

**Comment by sxh-netizen** [comment]
是的，现在的话，大多数机器都是 目录订阅失败，无法感知到 设备下的通道 上下线，有时候可能会10次成功一次，但是对于感知通道上下线 没有效果

**Comment by 648540858** [comment]
级联还是直接接入设备

**Comment by 648540858** [comment]
设备的话一般nvr的意义大一些，普通摄像机一般可是通过注册有效期以及主动调用状态查询实现的

**Comment by sxh-netizen** [comment]
接入NVR

**Comment by 648540858** [comment]
你那是什么品牌nvr，我自己测试过大华的是没有问题的，你可以
1. 开启抓包，
2.  开启目录订阅，
3. 添加摄像头，
4. 等十秒
5. 停止抓包，导出抓包文件
通过抓包可以确定问题原因

**Comment by sxh-netizen** [comment]
好的，我试试，多谢

**Comment by sxh-netizen** [comment]
海康的nvr

**Comment by sxh-netizen** [comment]
海康nvr(iDS-7908NX-K4/FA(B))

**Comment by sxh-netizen** [comment]
![image](https://user-images.githubusercontent.com/58098910/184055769-0e402a18-fdba-4db5-ba67-3492780e2868.png)
关于订阅的这一看，我看了一下 wvp发送的订阅信息，正确的报文和错误的报文，对比得出来 via和content不一样，不知道是不是是这个问题

**Comment by sxh-netizen** [comment]
他们两个都是在同一个报文下的，

**Comment by sxh-netizen** [comment]
我是按照您说的操作来的

**Comment by sxh-netizen** [comment]
![微信截图_20220815152137](https://user-images.githubusercontent.com/58098910/184593081-51705202-b2c8-402d-a4b5-6c005f884899.png)
关于目录订阅有bug，订阅失败的时候，参数值不对

**Comment by zhxlqd** [comment]
这个问题我也遇到了。IPC和NVR的通道（通道就是目录，含设备）上下线没有发送通知到wvp（已订阅目录的情况下）。wvp也没有自动监测通道上下线的功能。

IPC----只有一个通道
NVR----有限个数的通道

IPC在Keppalive通知时本身的状态可以认为也是通道的状态。
NVR在Keepalive通知时携带异常通道信息。也可以据此对比出通道的状态变化。

是否可以通过这个地方，封装成目录订阅通知，发给上级平台？

**Comment by shawn-tangsc** [comment]
![image](https://user-images.githubusercontent.com/24619820/199374757-f218b1a1-c69c-41dc-ba0e-b77a6563061a.png)
我在目录订阅的时候也出现了同样的问题，对接的也是大华的nvr，但是出现了如图的报错

**Comment by shawn-tangsc** [comment]
同样，我尝试了海康的nvr，问题也是一样的

**Comment by shawn-tangsc** [comment]
> ![微信截图_20220815152137](https://user-images.githubusercontent.com/58098910/184593081-51705202-b2c8-402d-a4b5-6c005f884899.png) 关于目录订阅有bug，订阅失败的时候，参数值不对

您好，这个问题您解决了么？

**Comment by sxh-netizen** [comment]
没有
