### ISSUE TITLE
wvp连接ZlmediaKit平台，一段时间后会连接不上

### ISSUE THREAD

**Issue by taxi886** [648540858/wvp-GB28181-pro#555]
**描述错误**
wvp连接ZlmediaKit平台，一段时间后会连接不上，重启wvp或者Zlmediakit又可以正常运行

**如何复现**
运行0-4小时不等，wvp就连接不上ZlmediaKit，重启wvp或者Zlmediakit又可以正常运行

**预期行为**
wvp连接ZlmediaKit后，保持连接状态

**截图**
![图片](https://user-images.githubusercontent.com/109326425/181192587-b5092b8c-3ca3-4bb2-b52a-1193fcaec996.png)
![图片](https://user-images.githubusercontent.com/109326425/181192733-0c6ce23a-810a-4c0e-af45-5575f493de7e.png)

**环境信息:**
 - 1. 部署方式     wvp-pro + zlm编译部署/
 - 2. 部署环境      centos 
 - 3. 端口开放情况      完全开放
 - 4. 是否是公网部署    是
 - 5. 是否使用https    否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试    修改wvp的配置文件ip，重装linux然后布署,修改ZLmediaKit[http.keepAliveSecond],修改/etc/sysctl.config 配置:
![图片](https://user-images.githubusercontent.com/109326425/181191540-5d46f4e2-e3cc-4889-ae3f-3dc9a574a667.png)

**Comment by 648540858** [comment]
代码是哪天更新的，然后把wvp日志发我一份

**Comment by taxi886** [comment]
代码从上周开始每天都更新
[wvp-2022-07-29.0.log](https://github.com/648540858/wvp-GB28181-pro/files/9218395/wvp-2022-07-29.0.log)
我看了一下内存，有下降的趋势
![418557e3a734d132](https://user-images.githubusercontent.com/109326425/181724907-bcca8e85-f8f8-4361-81c7-9a5302c8b8c7.jpg)
![企业微信截图_1659056896685](https://user-images.githubusercontent.com/109326425/181725008-473b45ed-7309-48ec-9273-ffb1e489dc05.png)

**Comment by 648540858** [comment]
你修改过代码？

**Comment by taxi886** [comment]
只修改过配置文件。直接从git上面拉下来，没有用docker。

**Comment by 648540858** [comment]
我发现的日志内容与我使用的不一致， [ZLM服务访问代理]，错误：处理url信息时未找到流媒体信息= 这个错误可以不用管，这因为页面没有拿到zlm信息导致的发送了错误的请求。

**Comment by 648540858** [comment]
你可以试试点播或者看看节点管理里

**Comment by 648540858** [comment]
更新下代码，应该就没有这个错误了

**Comment by taxi886** [comment]
更新完代码，问题仍然存在，点播中未找到可用zlm。
节点管理报错如下：
![企业微信截图_16593346552443](https://user-images.githubusercontent.com/109326425/182084613-001027e4-bfb5-4156-8a8a-4dc9967e1027.png)
本地报错日志：
![企业微信截图_16593344348296](https://user-images.githubusercontent.com/109326425/182084855-84135bc9-8b2e-493f-93f6-cc7b8067ece7.png)
线上报错日志：

[error-2022-08-01.0.log](https://github.com/648540858/wvp-GB28181-pro/files/9231432/error-2022-08-01.0.log)

**Comment by 648540858** [comment]
zlm访问不通，wvp连接不到zlm，
![image](https://user-images.githubusercontent.com/18274453/182085289-69345b54-18ac-4c05-8f26-a8987f9d7768.png)
你的网络或者配置有问题。

**Comment by taxi886** [comment]
重启wvp或者zlm,又正常了，过一段时间又连接不上
![企业微信截图_16593353111244](https://user-images.githubusercontent.com/109326425/182086040-08077419-9008-44be-ae5f-cb63fc6d0f1b.png)

**Comment by taxi886** [comment]
wvp和zlm是同一服务器，[media.ip]填127.0.0.1

**Comment by 648540858** [comment]
看你日志你配置的是120.27.154.69

**Comment by taxi886** [comment]
![企业微信截图_16593366023862](https://user-images.githubusercontent.com/109326425/182089318-96086d0a-9a6d-47da-bec5-80aaa82ae40e.png)
之前[hook.ip]改为127.0.0.1，也存在这个问题。主页的截图远端也是127.0.0.1

**Comment by 648540858** [comment]
你的media的配置没有问题，你的日志是旧的的吧，新的再来一份看看

**Comment by taxi886** [comment]
修改了配置文件，时间久了，仍然会有断开的现象。
配置文件如下：
![企业微信截图_1659408729525](https://user-images.githubusercontent.com/109326425/182282014-a36594b3-f5b5-4666-8dcd-895d1b2b0247.png)
报错日志如下：
[error-2022-08-01.0.log](https://github.com/648540858/wvp-GB28181-pro/files/9238711/error-2022-08-01.0.log)

**Comment by taxi886** [comment]
修改了配置文件，时间久了还是会有掉线的情况。
配置文件：
![企业微信截图_1659408729525](https://user-images.githubusercontent.com/109326425/182282406-843e9a45-16a6-4264-844f-f4cebe0bb969.png)
报错日志：
[error-2022-08-01.0.log](https://github.com/648540858/wvp-GB28181-pro/files/9238731/error-2022-08-01.0.log)

**Comment by 648540858** [comment]
你自己使用127访问下zlm的接口，看看wvp报错时是否可以访问通。

**Comment by taxi886** [comment]
本地起wvp连接线上的zlm能连通，也是一段时间后断开。
本地使用POSTMAN测接口有返回：
![企业微信截图_16594917792986](https://user-images.githubusercontent.com/109326425/182507627-c7ae42ca-8b23-4bc2-ad31-316053bddf88.png)
同时redis中media的数据没有了：
![企业微信截图_1659491823389](https://user-images.githubusercontent.com/109326425/182507700-26f1a2aa-d136-47a9-8017-d7d513e8a93e.png)

**Comment by taxi886** [comment]
线上wvp连不上的时候测试的

**Comment by 648540858** [comment]
wvp和zlm最好在一个系统，你线上的过一段时间必然连不上，因为zlm的保活是基于hook，是需要zlm向wvp发起请求的。

**Comment by 648540858** [comment]
不清楚你的网络，感觉你还是规范下的网络环境吧。

**Comment by taxi886** [comment]
bug已修复，建议优化代码如下：
![图片](https://user-images.githubusercontent.com/109326425/184077927-efdaf370-0d6d-4df9-94ce-f9ff2d88d4ec.png)

**Comment by SUNRise666s** [comment]
能解决吗，遇到同样的问题了

**Comment by zhanpc** [comment]
> bug已修复，建议优化代码如下： ![图片](https://user-images.githubusercontent.com/109326425/184077927-efdaf370-0d6d-4df9-94ce-f9ff2d88d4ec.png)

这边是你自己写的listener嘛  可以把代码发出来看下嘛

**Comment by zhanpc** [comment]
> bug已修复，建议优化代码如下： ![图片](https://user-images.githubusercontent.com/109326425/184077927-efdaf370-0d6d-4df9-94ce-f9ff2d88d4ec.png)

@taxi886 这个listener是您写的把 源码里我没找到 方便把这个文件发出来看看嘛
