### ISSUE TITLE
分支wvp-28181-2.0的wvp视频播放点击音量报错

### ISSUE THREAD

**Issue by WWTBNBWN** [648540858/wvp-GB28181-pro#557]
**描述错误**
描述下您遇到的问题
新版本的wvp视频播放点击音量报错
**如何复现**
有明确复现步骤的问题会很容易被解决
下载 最新版本的wvp分支信息
![image](https://user-images.githubusercontent.com/53170533/181671953-e5088137-4272-40ec-8416-3f5a416348f9.png)

**预期行为**
清晰简洁的描述您期望发生的事情
新版本的wvp视频播放点击音量报错
**截图**
点击播放按钮报错
![image](https://user-images.githubusercontent.com/53170533/181671605-7f31fbfa-ad12-4d4d-9f54-0f3e6b674798.png)

点击音量图标报错
![image](https://user-images.githubusercontent.com/53170533/181671246-57b348fa-98b1-43d7-a3a0-b9f32af8fabe.png)

**环境信息:**
直接下载最新版本的wvp maven编译后打包部署到linux中运行

**Comment by 648540858** [comment]
好的， 我看一下

**Comment by 648540858** [comment]
已修复

**Comment by WWTBNBWN** [comment]
多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月1日(星期一) 下午2:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [648540858/wvp-GB28181-pro] 分支wvp-28181-2.0的wvp视频播放点击音量报错 (Issue #557)





 
已修复

**Comment by WWTBNBWN** [comment]
修复之后按钮能点击，但是没声音。里面还有个play的异常。
