### ISSUE TITLE
将海康摄像头接入WVP平台播放不了

### ISSUE THREAD

**Issue by Gozly** [648540858/wvp-GB28181-pro#558]
部署环境
ZLMediaKit+wvp_pro
都是按照教程里下载部署的
海康配置
![image](https://user-images.githubusercontent.com/46513884/181719394-deb6ee63-aa77-44bc-8af8-69f36b1be802.png)

wvp页面
![image](https://user-images.githubusercontent.com/46513884/181721113-03571c4a-b132-4d0e-893f-d3e85f6fee15.png)
一直ing。。。。。
![image](https://user-images.githubusercontent.com/46513884/181721194-4d8d2f74-3a6b-41ad-9a79-3f6978be9c6c.png)

ZLM日志
![image](https://user-images.githubusercontent.com/46513884/181722535-59cebbca-7b5c-4d5d-87d9-ee52a083a7ec.png)

完整日志
[2022-07-29_00.log](https://github.com/648540858/wvp-GB28181-pro/files/9218271/2022-07-29_00.log)

**Comment by 648540858** [comment]
修改下摄像机的编码为固定码率，h264；再试试

**Comment by Gozly** [comment]
@648540858 抱歉  我没找到修改的文件  麻烦你能告诉我文件名是什么吗

**Comment by Gozly** [comment]
@648540858 我没找到修改的文件   麻烦你能告诉我文件名吗

**Comment by 648540858** [comment]
不是配置文件，是你的摄像机管理页面，找编码配置。

**Comment by Gozly** [comment]
![Snipaste_2022-08-01_09-34-52](https://user-images.githubusercontent.com/46513884/182056115-1f1c8263-b0de-4b3c-939e-333515156bc7.png)

我修改了   默认就是h264的   但是还是不行

**Comment by 648540858** [comment]
使用的是谷歌浏览器吗，
zlm所在的ip是多少，
zlm和wvp在一台服务器上吗

**Comment by Gozly** [comment]
@648540858 不是的  我是放在自己电脑的虚拟机上的   zlm和wvp都放在同一个虚拟机下  我docker上跑通过可以观看

**Comment by 648540858** [comment]
虚拟机防火墙关了吗

**Comment by Gozly** [comment]
![image](https://user-images.githubusercontent.com/46513884/182061141-e451d5a1-ef7b-4a71-aee3-a350dbd5cbfa.png)
已经关闭了

**Comment by 648540858** [comment]
在播放页面吧rtsp地址复制出来，用vlc播放试试

**Comment by Gozly** [comment]
![image](https://user-images.githubusercontent.com/46513884/182063021-c2dd421e-1cde-4701-bc67-ea3a5e8c851e.png)
有错误
[vlc-log.txt](https://github.com/648540858/wvp-GB28181-pro/files/9230524/vlc-log.txt)

**Comment by 648540858** [comment]
还是网络问题，连接不到你的zlm

**Comment by Gozly** [comment]
@648540858 可是在节点管理里  zlm是显示在线状态啊😂   在虚拟机内也能够ping通外网地址

**Comment by 648540858** [comment]
zlm日志发一下

**Comment by Gozly** [comment]
[2022-07-31_00.log](https://github.com/648540858/wvp-GB28181-pro/files/9231160/2022-07-31_00.log)
这是最新的  时间没订正

**Comment by 648540858** [comment]
start_main | 端口占用或无权限:listen on 0.0.0.0:554 failed:address already in use

**Comment by 648540858** [comment]
rtsp没有启动成功，你的zlm不正常

**Comment by Gozly** [comment]
[2022-07-31_00.log](https://github.com/648540858/wvp-GB28181-pro/files/9231192/2022-07-31_00.log)
这是重启之后再试的

**Comment by 648540858** [comment]
这次的日志没看到有什么问题了

**Comment by Gozly** [comment]
> 这次的日志没看到有什么问题
我之前是  在zlm启动的时候又执行了启动命令，所以就那样报错   重启之后还是没有解决

**Comment by 648540858** [comment]
目前日志正常流信息看着也正常，但是播放器无法播放你的视频流，你直接telnet zlmip 554，看看能不能通

**Comment by Gozly** [comment]
![image](https://user-images.githubusercontent.com/46513884/182088291-c4066322-3f5c-4367-886c-bcffa1ff421b.png)       
    telnet 没有问题吧

**Comment by 648540858** [comment]
看着正常，你把自动点播打开，然后把rtsp地址再用vlc播放试试。

**Comment by Gozly** [comment]
![image](https://user-images.githubusercontent.com/46513884/182092315-e9fb184b-98bd-437b-844a-fdb31c8da095.png)
可以看到画面了  但是wvp页面上没有

**Comment by 648540858** [comment]
那就是wvp播放不了你的这个流

**Comment by 648540858** [comment]
具体播放器的原因我不清楚

**Comment by Gozly** [comment]
> 具体播放器的原因我确定
好的 感谢大大的解答  主要是docker上的版本可以播放我这个摄像头的，使用新代码却不行了😀

**Comment by 648540858** [comment]
确实有些奇怪。

**Comment by yy0812** [comment]
> > 具体播放器的原因我确定
> > 好的 感谢大大的解答  主要是docker上的版本可以播放我这个摄像头的，使用新代码却不行了😀

最后解决了没有，兄弟，我也遇到和你一模一样的问题，开了自动点播后，vlc可以播了，但wvp还是播不了

**Comment by Gozly** [comment]
这是因为播放器的原因，它不支持你的播放

**Comment by Gozly** [comment]
跟设备也有关，部分摄像头的音频需要关闭，或者跟海康摄像头的型号
也有关，我有一种海康的摄像头就播放不出来
