### ISSUE TITLE
关于设备报警类型取值的问题

### ISSUE THREAD

**Issue by xiaoyongcss** [648540858/wvp-GB28181-pro#559]
**描述错误**
alarmMethod除了视频报警，其它报警类型都为空

**如何复现**
录像机设置了一个视频丢失报警事件

**预期行为**
报警类型应该是有值的，报警类型不应该根据报警方式进行过滤，记录就应该健全，原设备上报啥，记啥，不太理解目前代码逻辑为何只取视频报警方式的报警类型值

**截图**
![image](https://user-images.githubusercontent.com/16200678/182069520-16be49c2-9ba9-43b1-9587-70a11ebc1c83.png)
![image](https://user-images.githubusercontent.com/16200678/182069538-a7e43f62-e135-4cbd-a615-7538b61d1079.png)
![image](https://user-images.githubusercontent.com/16200678/182069623-9bc9a317-b422-434e-a8c2-4d9dc1f5e818.png)

**环境信息:**
 - 1. 部署方式  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境  centos  
 - 3. 端口开放情况  
 - 4. 是否是公网部署  内网
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台  海康
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
只是针对视频报警做了处理，不会为了完整实现国标28181而去做的，做完没人用，我不会去做的。有需求可以提ISSUE也可以提PR，国标里很多功能多是不常用的。
