### ISSUE TITLE
分支wvp-28181-2.0的wvp视频播放点击音量报错

### ISSUE THREAD

**Issue by WWTBNBWN** [648540858/wvp-GB28181-pro#560]
**描述错误**
描述下您遇到的问题
新版本的wvp视频播放点击音量报错
**如何复现**
有明确复现步骤的问题会很容易被解决
下载 最新版本的wvp分支信息
![image](https://user-images.githubusercontent.com/53170533/181671953-e5088137-4272-40ec-8416-3f5a416348f9.png)

**预期行为**
清晰简洁的描述您期望发生的事情
新版本的wvp视频播放点击音量报错
**截图**
点击控制台页面的媒体服务配置按钮报错
![image](https://user-images.githubusercontent.com/53170533/182108943-fa70811f-2a03-4b28-ac5b-a9d1ea5c0639.png)

点击播放按钮报错
![image](https://user-images.githubusercontent.com/53170533/181671605-7f31fbfa-ad12-4d4d-9f54-0f3e6b674798.png)

点击音量图标之前报错现在不报错，但是没有声音，我开启了音频
![image](https://user-images.githubusercontent.com/53170533/181671246-57b348fa-98b1-43d7-a3a0-b9f32af8fabe.png)

**环境信息:**
直接下载最新版本的wvp maven编译后打包部署到linux中运行

**Comment by 648540858** [comment]
更新代码
