### ISSUE TITLE
【求助贴】推流列表中始终没有摄像头推流数据，但是国标设备里面有，而且可以正常查看，请问如何让其在推流列表中显示？

### ISSUE THREAD

**Issue by liugt34** [648540858/wvp-GB28181-pro#561]
1：代码和ZLM都是最新的
2：部署方式 
wvp-pro 是windows   IP 192.168.1.64  
ZLM 是docker             IP 192.168.1.198
docker run --name=zlmediakit --restart=always -e TZ=Asia/Shanghai -id 
-p 1935:1935 
-p 8080:80 
-p 8443:443 
-p 8554:554 
-p 10000:10000 
-p 10000:10000/udp 
-p 8000:8000/udp 
-p 9000:9000/udp 
-p 30000-30500:30000-30500 
-p 30000-30500:30000-30500/udp 
-v /zlmediakit/conf/config.ini:/opt/media/conf/config.ini 
-v /zlmediakit/www/record:/opt/media/bin/www/record   zlmediakit/zlmediakit:master
3: 端口开放情况  
防火墙全部关闭
4：是否是公网部署  
否
5：是否使用https
否
方便的话提供下使用的设备品牌或平台
海康威视摄像头iDS-2DE6C240IW-D/GLT 系列

WVP配置文件

sip:
    ip: 192.168.1.69
    port: 5060
    domain: 3402000000
    id: 34020000002000000001
    password: P@ssw0rd
    ptz-speed: 50

media:
    id: FQ3TF8yT83wh5Wvz
    ip: 192.168.1.198
    http-port: 8080
    rtmp-port: 1935
    rtp-proxy-port: 10000
    rtsp-port: 8554
    auto-config: true
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    stream-none-reader-delay-ms: -1
    rtp:
        enable: false
        port-range: 30000,30500 # 端口范围
        send-port-range: 30000,30500 # 端口范围
    record-assist-port: 5011

user-settings:
    record-push-live: true
    auto-apply-play: true

摄像头配置
![image](https://user-images.githubusercontent.com/8056013/182312260-39e01bd2-72e6-4a19-ab3f-2f1d6bf87693.png)

最终效果
![image](https://user-images.githubusercontent.com/8056013/182312334-e34d52e8-f396-46e2-b005-0545b4fade54.png)
![image](https://user-images.githubusercontent.com/8056013/182312402-34561e27-b8f3-45de-9659-ccf8d96a7e15.png)
![image](https://user-images.githubusercontent.com/8056013/182312439-ae2f0dc4-52b2-4e03-a05b-4920ff42329e.png)

但是推流列表一直没有数据，想问下大神是我哪里的配置没有正确么，还是其他原因？
![image](https://user-images.githubusercontent.com/8056013/182312824-49358d44-3337-4d45-9d6b-9cee7605f532.png)

![image](https://user-images.githubusercontent.com/8056013/182312624-aebf2e15-280a-4278-aec4-1dd3f76dcb00.png)

**Comment by 648540858** [comment]
推流列表是直播接入的，跟国标无关。

**Comment by liugt34** [comment]
> 推流列表是直播接入的，跟国标无关。

感谢大神解悟, 之前一直以为海康摄像头的推流也会出现在这里，还搞了很久。现在明白了
麻烦再问下，如果国标级联其他平台，填好了信息之后，视频会自动推送吗？还是说要等上级平台点播之后才推流？

**Comment by 648540858** [comment]
点播推流

**Comment by 648540858** [comment]
有其他问题再开新的ISSUE吧
