### ISSUE TITLE
华为ivs播放一段时间自动断开

### ISSUE THREAD

**Issue by LilMDFJee** [648540858/wvp-GB28181-pro#563]
**描述错误**
对接平台上下线通知经常接收不到
抓包可以抓到 event里的off 和status里的on

**如何复现**
设备上线下线

**预期行为**
上下线通知可以感知到

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 内网
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
你的意思是抓包有notify消息是吗？抓包文件发一下。

**Comment by zhysda** [comment]
我这边也有同样的问题，设备离线的通知是可以收到的，但是设备上线无法收到。我这边对接的华为的IVS平台，我重启一台摄像头，WVP上面设备会立即显示离线，但是摄像头正常上线之后。WVP平台仍然显示离线，必须点击刷新通道才能正常显示在线状态。

**Comment by zhxlqd** [comment]
这个是因为wvp不自动更新通道的状态。默认是接收到下级平台目录订阅通知采取改变。而下级平台是IPC和NVR时不自动发送目录订阅通知。

**Comment by lanyunjie** [comment]
默默的问一下，就是现在对华为的ivs设备支持，是不是还不是很友好。我这边同时用nvr和ivs播放，ivs绑定的摄像头，30秒左右就自动断开了，流直接断了，再点开播放都不行。
![image](https://user-images.githubusercontent.com/44937545/220871609-102818f5-c785-4945-94fa-be8a4bc2a7b6.png)

**Comment by 648540858** [comment]
> 默默的问一下，就是现在对华为的ivs设备支持，是不是还不是很友好。我这边同时用nvr和ivs播放，ivs绑定的摄像头，30秒左右就自动断开了，流直接断了，再点开播放都不行。 ![image](https://user-images.githubusercontent.com/44937545/220876874-b24cd5e9-17b9-4fac-a465-cde176d1188b.png)

目前接触的华为国标设备实现的很不标准

**Comment by 648540858** [comment]
> > 默默的问一下，就是现在对华为的ivs设备支持，是不是还不是很友好。我这边同时用nvr和ivs播放，ivs绑定的摄像头，30秒左右就自动断开了，流直接断了，再点开播放都不行。 ![image](https://user-images.githubusercontent.com/44937545/220876874-b24cd5e9-17b9-4fac-a465-cde176d1188b.png)
> 
> 目前接触的华为国标设备实现的很不标准

具体的抓包文件可以发一下， 使用新代码测试下
