### ISSUE TITLE
拖动回放进度条后，回放不能使用

### ISSUE THREAD

**Issue by cutexiaokele** [648540858/wvp-GB28181-pro#564]
**描述错误**
拖动回放进度条后，关闭，再次点击任意时刻的回放均无法播放

**如何复现**
上述操作后，/api/playback/start 请求会超市，后台显示session timeout  

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro  + zlm都是编译部署
 - 2. 部署环境 windows 
 - 3. 端口开放情况 正常
 - 4. 是否是公网部署  同一服务器
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试 重启服务器后 ，恢复正常，一旦拖动回放 ， 回放就无法使用了

**Comment by 648540858** [comment]
重启设备可以恢复吗

**Comment by 648540858** [comment]
更新试试
