### ISSUE TITLE
点播失败， 错误码： 487, Request Terminated

### ISSUE THREAD

**Issue by zouyaoji** [648540858/wvp-GB28181-pro#565]
**描述错误**
点播失败， 错误码： 487, Request Terminated

**如何复现**
我这部署之后，新加了好几个设备都播放不起。

**预期行为**
希望能正常播放。

**截图**

![image](https://user-images.githubusercontent.com/24430116/182649534-31927cb3-7e51-4f44-970f-64f453b24a59.png)

**环境信息:**
 - 1. 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 阿里云 centos ...
 - 3. 端口开放情况  已通过安全组开放
 - 4. 是否是公网部署 是
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台 宇视
 - 7. 你做过哪些尝试

参考了 https://github.com/648540858/wvp-GB28181-pro/issues/434

并搜索相关错误码，暂未发现和我一样的情况。
请问作者大大知道报 “点播失败， 错误码： 487, Request Terminated”  是咋回事吗？

**Comment by zouyaoji** [comment]
![image](https://user-images.githubusercontent.com/24430116/182651058-39e6200f-a705-415b-a4f0-9152ea7cf81c.png)

![image](https://user-images.githubusercontent.com/24430116/182650984-7366015a-d359-4046-8d7e-87a74240f45d.png)

**Comment by 648540858** [comment]
抓个包看一下

**Comment by zouyaoji** [comment]
嗯  出来了 我甚至不知道咋好的 先关了 搞清楚是哪儿没搞对了 再来分享。

**Comment by zouyaoji** [comment]
@648540858 老大，我再请教一下。我是用阿里云服务器测试成功了。

我现在实际环境是这样的。
我要部署的机器A，是一台windows服务器，A自己没有公网ip，能访问互联网，而且通过有一个公网ip映射了几百个端口到A，相当于间接暴露在公网了吧。

我的wvp和zlmedaikit都部署在A上的。社保还是通过GB28181推的，列表能出来，但是就是播放不起，还是没折腾明白啥原因。

我目前测试发现的原因可能是 机器A本身不能访问映射到它自己的公网ip导致的。就部署好后前端页面在其他网络环境输入公网ip+端口能成功访问。在A机器上输入公网ip+端口反而访问不到。

请问作者大大有没有相关经验？

**Comment by zouyaoji** [comment]
zlm和wvp都要部署到公网才行吗？zlm部署到内网，wvp部署到公网可行吗？

**Comment by zouyaoji** [comment]
解决了，感谢作者大大。

https://github.com/ZLMediaKit/ZLMediaKit/issues/1857

**Comment by zouyaoji** [comment]
补充一下。宇视摄像头报错：

点播失败， 错误码： 487, Request Terminated。

很可能是设备原因，对摄像头就行云升级即可正常播放。
