### ISSUE TITLE
下级主动断流后，zlm触发on_stream_changed回调，wvp没有主动向下级发送bye

### ISSUE THREAD

**Issue by szy833** [648540858/wvp-GB28181-pro#566]
**描述错误**
如果下级流断开了，zlm会触发on_stream_changed这个回调，但是没有主动给下级发送bye断流。这样会导致，如果下级平台对资源做限制之后，再次拉流会出现资源未释放的问题。

**如何复现**
下级平台断流，抓包没有主动发送bye断流

**预期行为**
下级断流，vnp主动发送bye结束拉流

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
好的 我确认下

**Comment by godlike10** [comment]
> 

遇到同样的问题，之前没注意到zlm会触发on_stream_changed，所以困扰了好久，下级对资源做了限制。经常触发这个限制。
这个在on_stream_changed里发送bye结束拉流就可以了吧

**Comment by 648540858** [comment]
使用新代码测试下，我先关闭了
