### ISSUE TITLE
国标级联注册失败

### ISSUE THREAD

**Issue by liugt34** [648540858/wvp-GB28181-pro#572]
填完信息之后，注册成功

![image](https://user-images.githubusercontent.com/8056013/183839878-18e1bbbe-6472-407c-a47a-7e45ede19b02.png)

但是后面会每个一分钟左右持续发送注册请求，且都是400错误BadRequest
![image](https://user-images.githubusercontent.com/8056013/183841345-3f480ce5-f0ad-4e51-bb05-c6c488eb9f4b.png)

奇怪的是虽然后面一直失败，但是国标级联中的状态确是一直在线的
![image](https://user-images.githubusercontent.com/8056013/183841431-38724441-81fc-4166-8969-c23d1a7919e9.png)

请问下这是正常现象么，还是说是上级平台的问题？

**Comment by 648540858** [comment]
具体你需要更上级平台沟通下为什么回复400

**Comment by liugt34** [comment]
好的，感谢回复
