### ISSUE TITLE
视频播放失败

### ISSUE THREAD

**Issue by houge101** [648540858/wvp-GB28181-pro#574]
**描述错误**
![image](https://user-images.githubusercontent.com/3355923/184566649-e8c97c7a-1c79-4322-8f38-c59792d2c9ae.png)
![image](https://user-images.githubusercontent.com/3355923/184567655-6c94e884-2575-49de-b0c4-68ddd44e89f7.png)

Jessibuca页面播放海康GB28181视频错误

**如何复现**
Jessibuca页面播放海康GB28181视频正确。当切换到WebRTC页面，并且挨个点击  实时视频 录像查询  云台控制  和 编码信息选项卡之后（不要过快，每个选项卡停留大约半秒以上，且仅仅切换选项卡，未修改任何配置），在切换回Jessibuca页面，视频不能播放

**预期行为**
切换之后不影响视频播放

**截图**
![image](https://user-images.githubusercontent.com/3355923/184566602-2a67ea1d-5dad-442f-9f7c-fd41f2e5cf5c.png)
![image](https://user-images.githubusercontent.com/3355923/184566902-85ac690f-32a8-4a9c-b53f-a636c60730f6.png)

**环境信息:**
 - 1. 部署方式编译wvp-pro + zlm都是编译部署
 - 2. 部署环境wvp-pro部署到 windows10 /zlm部署到 centos
 - 3. 局域网（wvp-pro、zlm和海康摄像头在同一个路由器）
 - 4. 是否是公网部署（否）
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台（海康摄像头，惠普台式机）
 - 7. 你做过哪些尝试（仅仅部署了wvp-pro和zlm，未部署其它软件，另外两个页面h265web 和  wsPlayer 没有此现象）

**Comment by 648540858** [comment]
按你的步骤我测试不出来，你是否修改过代码

**Comment by houge101** [comment]
没有做任何改动，只修改了配置文件，这个按wiki应该没影响吧
![image](https://user-images.githubusercontent.com/3355923/185078206-72e8f1ca-b223-44d6-9e16-2db0fd159839.png)

**Comment by 648540858** [comment]
修改这个配置项目没影响，你F12打开控制台，看看有没有什么报错另外    auto-apply-play配置为true，在测试下

**Comment by houge101** [comment]
![image](https://user-images.githubusercontent.com/3355923/185278131-e0f0d27c-8656-407a-b19b-7d3815a32f6a.png)
![image](https://user-images.githubusercontent.com/3355923/185278166-bc85e875-35fa-4558-a1fb-9be572332d2c.png)
![image](https://user-images.githubusercontent.com/3355923/185278222-cce02303-75bc-4e2a-93b1-6d958dcc5010.png)
![image](https://user-images.githubusercontent.com/3355923/185278248-0f4c7686-c942-4638-9ee2-c08a63db56c7.png)
出现了这些错误。另外  auto-apply-play  在什么位置啊。yml文件没有呢

**Comment by houge101** [comment]
![image](https://user-images.githubusercontent.com/3355923/185279377-86ad89cf-f371-4b95-82e9-5527da319b8e.png)
加上 auto-apply-play 为 true 就可以了

**Comment by 648540858** [comment]
与你的操作无关，是因为无人观看一段时间自动关闭流了。我先关闭了，你可以调整无人观看的时间来优化这个问题。
