### ISSUE TITLE
添加大华NVR时后台报错

### ISSUE THREAD

**Issue by 75131056** [648540858/wvp-GB28181-pro#575]
**描述错误**
添加大华NVR时后台报错
Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)

**截图**
后台
![@G7P8F9C8)X47C~H%L)C4~H](https://user-images.githubusercontent.com/13864041/184801856-8b1c22ce-1514-4c0b-a60c-0fb704daf7be.png)

抓包
![image](https://user-images.githubusercontent.com/13864041/184802311-f944f834-e0d8-48c8-a74c-a9483b847926.png)

无法获取通道列表

**Comment by 648540858** [comment]
抓包文件给我一份，不会抓包可以参看文档网站，有教程。

**Comment by 75131056** [comment]
> 抓包文件给我一份，不会抓包可以参看文档网站，有教程。

已发

**Comment by 648540858** [comment]
消息头的消息提长度为0,导致无法读取到消息体，空指针已修复，但是设备的错误需要你寻求厂商修复。

**Comment by daabtech** [comment]
我也遇到了相同的报错，我用的海康威视摄像头，但是是springboot的回复消息体为0；
<img width="1280" alt="20230623110303" src="https://github.com/648540858/wvp-GB28181-pro/assets/37167339/ecc4b8b9-7c71-4212-9bd0-fa56abe8ce9e">
