### ISSUE TITLE
【API开始视频回放】接口调用失败，回放失败， 错误码： 415, Unsupported Media Type

### ISSUE THREAD

**Issue by liugt34** [648540858/wvp-GB28181-pro#576]
如图，API无法调通，其他的都正常
![image](https://user-images.githubusercontent.com/8056013/184873870-d39bae9f-2463-4223-be61-b92b3e3126e7.png)

**Comment by Smallwhitepig** [comment]
怎么通道ID跟设备ID是一致的 
1 首先你确认该通道可以播放
2 录像回放是NVR设备里面的录像

**Comment by liugt34** [comment]
> 

都是有的，
1：可以正常播放
2：存储卡里也有录像

**Comment by liugt34** [comment]
> 都是有的，
> 1：可以正常播放
> 2：存储卡里也有录像



> 怎么通道ID跟设备ID是一致的 1 首先你确认该通道可以播放 2 录像回放是NVR设备里面的录像

都是有的，
1：可以正常播放
2：存储卡里也有录像

**Comment by 648540858** [comment]
1. 先把设备编号和通道编号区分测试，一样的编号不是所有设备多支持的，有的设备兼容性不行；
2. 抓包看下这个错误，应该是设备返回的错错误，一般是因为sdp消息不识别，或者有错误，抓包不会可以参考文档网站。

**Comment by liugt34** [comment]
刚才试了一下，用POSTMAN是可以正常的，应该是那个swagger文档的调试有问题

**Comment by feiyiban** [comment]
api文档在哪看，swagger或者postman
