### ISSUE TITLE
启动wvp-pro-assist错误

### ISSUE THREAD

**Issue by Gozly** [648540858/wvp-GB28181-pro#579]
**描述错误**
启动wvp-pro-assist时报错
报错信息：
![image](https://user-images.githubusercontent.com/46513884/185731951-a3c55ab8-443d-44c5-b833-c3e649c4257a.png)

**如何复现**
安装部署按照文档实现，wvp部署成功启动，然后启动录像服务报错

<b>wvp配置截图</b>
![image](https://user-images.githubusercontent.com/46513884/185731990-1dea3f0f-5baf-42fa-99a2-8419cea73821.png)

------------------------------------------------------------------------------------------------------------------------------------

<b>assist录像功能配置文件</b>
![image](https://user-images.githubusercontent.com/46513884/185732031-4b1a12c0-4c23-49fd-8a16-496d7e68ec07.png)

**环境信息:**
 - 1. 部署方式 wvp-pro / zlm + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境  ubuntu
 - 3. 端口开放情况 防火墙已开放
 - 4. 是否是公网部署  否
 - 5. 是否使用https 无 本地测试
 - 6. 方便的话提供下使用的设备品牌或平台  海康摄像头
 - 7. 你做过哪些尝试   更换server.port端口后重试不行

**Comment by dodu2014** [comment]
@Gozly Hello, have you resolved the issue of startup error?
