### ISSUE TITLE
历史媒体下载到本地无法快进播放

### ISSUE THREAD

**Issue by tjz101** [648540858/wvp-GB28181-pro#583]
**描述错误**
从下载 NVR 录像到本地，使用系统自带播放器无法快进播放，目前测试只有 VLC 和 MAC 系统自带播放器可以快进。

**如何复现**
国标设备 - 通道 - 设备录像 - 下载

**预期行为**
下载到本地的 mp4 文件可以快进

**截图**

**环境信息:**
 - 1. 部署方式： 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境： ubuntu
 - 3. 端口开放情况： 全开
 - 4. 是否是公网部署： 否
 - 5. 是否使用https： 否
 - 6. 方便的话提供下使用的设备品牌或平台：  海康、大华
 - 7. 你做过哪些尝试：如描述，vlc 和 mac 系统自动播放器可以快进，其他播放器无法快进

**Comment by 648540858** [comment]
录像文件都到本地了，我也无能为力
