### ISSUE TITLE
询问下这个平台的预警信息怎么查看到 可以监听吗？

### ISSUE THREAD

**Issue by xinruan7** [648540858/wvp-GB28181-pro#585]

**Comment by 648540858** [comment]
获取报警信息首先你得确定设备是否支持发送报警，有的设备是主动发，wvp可以接收并存储，你可以查看报警相关的接口，有的是需要主动订阅才可以收到，目前wvp还不支持。

**Comment by eanfs** [comment]
订阅报警要怎么实现有没有相关文档，我们急需这个功能，想自己先开发一下。
