### ISSUE TITLE
摄像头预览播放方向是倒着的

### ISSUE THREAD

**Issue by Gozly** [648540858/wvp-GB28181-pro#587]
**描述错误**
播放预览的视频是倒过来的

**如何复现**
接入海康摄像头后出现的

**截图**
![1dd7acef9a4d29827c1a92ca27a5a03](https://user-images.githubusercontent.com/46513884/186346347-6a1d02be-1c2c-46fe-9db0-19ce3371ddac.jpg)
--------------------------------------------------------------------------------------------------------------------------------------
在摄像头预览里是正的
![cd265b5a84d925c9afa83d92d9f42ac](https://user-images.githubusercontent.com/46513884/186346894-62cd82e2-21bc-4a21-b0fa-5313c66d8543.jpg)

**环境信息:**
 - 1. 部署方式  编译 wvp-prp + zlm都是编译部署
 - 2. 部署环境  centos 
 - 3. 端口开放情况  防火墙已打开
 - 4. 是否是公网部署  否  内网部署
 - 5. 是否使用  无
 - 6. 方便的话提供下使用的设备品牌或平台  设备：海康
 - 7. 你做过哪些尝试  调配摄像头后台配置分辨率无果、刷新同步摄像头

**Comment by Gozly** [comment]
> **描述错误** 播放预览的视频是倒过来的
> 
> **如何复现** 接入海康摄像头后出现的
> 
> **截图** ![1dd7acef9a4d29827c1a92ca27a5a03](https://user-images.githubusercontent.com/46513884/186346347-6a1d02be-1c2c-46fe-9db0-19ce3371ddac.jpg)
> ------------------------------------------------------------------------------------------------------------------------------
在摄像头预览里是正方向的
> ![cd265b5a84d925c9afa83d92d9f42ac](https://user-images.githubusercontent.com/46513884/186346894-62cd82e2-21bc-4a21-b0fa-5313c66d8543.jpg)
> 
>
> 
> **环境信息:**
> 
> * 1. 部署方式  编译 wvp-prp + zlm都是编译部署
> * 2. 部署环境  centos
> * 3. 端口开放情况  防火墙已打开
> * 4. 是否是公网部署  否  内网部署
> * 5. 是否使用  无
> * 6. 方便的话提供下使用的设备品牌或平台  设备：海康
> * 7. 你做过哪些尝试  调配摄像头后台配置分辨率无果、刷新同步摄像头

**Comment by 648540858** [comment]
这个问题不是第一次间，可能的原因是播放器兼容性的问题，建议使用谷歌浏览器，或者尝试该版本浏览器的pro版本http://jessibuca.monibuca.com/player-pro.html，目前wvp集成的是开源免费的版本，不一定可以完全满足项目的需求。
