### ISSUE TITLE
[新功能]国标设备列表功能建议

### ISSUE THREAD

**Issue by leiyun1993** [648540858/wvp-GB28181-pro#589]
1、增加名称和设备编号搜索功能；
2、建议设备列表增加keep-alive功能，现在查看通道后返回页面会被重置到第一页；
3、云端录像页面查看录像组件打开后无法回到列表，建议增加返回功能。

**Comment by 648540858** [comment]
好的，我看一下

**Comment by 648540858** [comment]
建议3已支持，可以测试了

**Comment by 648540858** [comment]
使用新版本测试下
