### ISSUE TITLE
级联海康平台无法播放编码问题

### ISSUE THREAD

**Issue by dyc6513339644** [648540858/wvp-GB28181-pro#595]
**描述错误**
 inputRtp | rtp payload type未识别(40),已按ts或ps负载处理
 unsupported codec type:unknown codec 189

**预期行为**
正常播放

ZLM日志:
![image](https://user-images.githubusercontent.com/8286855/187203055-ae0b08ec-d9cb-46d8-bf25-caa34d951a05.png)
抓包截图
![image](https://user-images.githubusercontent.com/8286855/187203834-3bfe1e00-8c7c-45cd-a06f-0bcd452dc66e.png)

**环境信息:**
 - 1. 部署方式 wvp-pro jar部署   zlm(docker) 
 - 2. 部署环境centos7
 - 3. 端口开放情况 部分指定端口开放
 - 4. 公网部署
 - 5. 未使用https
 - 6. 设备海康设备,平台海康安全生产平台
 - 7. 目前自己对接设备可以正常播放

**Comment by dyc6513339644** [comment]
![image](https://user-images.githubusercontent.com/8286855/187338928-a39d3784-e37b-4693-8ba6-8ad93b68d98c.png)
已调整H264

**Comment by dyc6513339644** [comment]
目前海康平台又级联平台 同一个设备在不通平台上测试就可以  
![image](https://user-images.githubusercontent.com/8286855/187378519-b16dc475-9639-49b1-aa69-595ca5362049.png)
上面是可以的日志
对比日志就多了这个东西: MediaSink.cpp:50 operator() | cached frame of unready track(H264) is too much, now cleared

**Comment by 648540858** [comment]
你是把海康级联到吉他平台是可以的，但是级联到wvp不行是吗

**Comment by 75131056** [comment]
> 你是把海康级联到吉他平台是可以的，但是级联到wvp不行是吗

我也遇到这个问题，海康视频平台级联catalog目录无法加载，上次大华的NVR也是这样的我换了别的平台就可以，我有抓包，望作者麻烦排查排查。

**Comment by dyc6513339644** [comment]
我有2个WVP  同一个海康平台 级联到WVP 一个可以一个不行,很强怪,但是现在有可以了

**Comment by 648540858** [comment]
更新代码测试吧，最近这部分优化了有问题再打开。
