### ISSUE TITLE
拉流代理生成的代理后RTSP地址/国标接入再转出的RTSP地址,vlc无法播放

### ISSUE THREAD

**Issue by zionzheng** [648540858/wvp-GB28181-pro#597]
**描述错误**
拉流代理与国标接入,网页播放器都正常播放,说明流应该正常.但是代理后/转出后的RTSP地址vlc不可播放,抓包得知服务器不返回SDP或者返回401 Unauthorized,vlc无法播放或者需要输入账号密码.

播放视频无须鉴权,视频源也不是推流,没有callID,请问401 Unauthorized是怎么产生的?
在网页能播放,说明源可用的情况下,客户端发describe,无sdp返回该怎么排查呢?
**如何复现**
不推流,配置文件使用默认选项,网页在线播放正常,转出的RTSP地址无法播放

**预期行为**
vlc能够播放代理后RTSP地址
**截图**
代理后的流确实在线,且有流信息
![Dingtalk_20220902151339](https://user-images.githubusercontent.com/30211090/188080415-af32c13c-08c6-4ce8-a011-9bc16bb0e80b.jpg)
![DA3B7B97-DAAF-403c-AB8C-AFF9F7978594](https://user-images.githubusercontent.com/30211090/188080428-39cff0a8-1417-4813-bd3f-23db9d862f2d.png)
![Dingtalk_20220902151450](https://user-images.githubusercontent.com/30211090/188080433-be69dd22-5fdd-4aba-a4b7-bbfdd792328c.jpg)

**环境信息:**
 - 1. 部署方式 
 wvp-prp + zlm都是编译部署
 - 2. 部署环境  
 centos 7
 - 3. 端口开放情况 
  防火墙已关闭
 
 - 4. 是否是公网部署
 内网部署
 - 5. 是否使用https 
 不使用
 - 6. 方便的话提供下使用的设备品牌或平台 
 大华NVR/IPC
 - 7. 你做过哪些尝试 
    抓包,显示服务器不返回SDP或者返回的sdp需要vlc输入密码
  抓包文件请见
ZLMediaKit/ZLMediaKit#1922

**Comment by 648540858** [comment]
更新代码试试，最近的提交的代码已经解决这个问题。

**Comment by zionzheng** [comment]
嗯我试下,之前构建用的是前天的最新代码

**Comment by 648540858** [comment]
你的554端口开放了吗
