### ISSUE TITLE
录像功能不能正常使用

### ISSUE THREAD

**Issue by Gozly** [648540858/wvp-GB28181-pro#598]
**描述错误**
录像服务启动后，不能后正常录像，配置的路径下也没有生成视频文件

**如何复现**
部署好wvp、assist 视频录像功能失效

**截图**
服务已经启动
![image](https://user-images.githubusercontent.com/46513884/188084005-e703c128-ae1a-4faf-9edf-af38bff42f8b.png)

> assist配置

![image](https://user-images.githubusercontent.com/46513884/188084290-871ee149-f714-460e-9859-77e9edc3463a.png)

> assist日志

![image](https://user-images.githubusercontent.com/46513884/188084592-96cb82f5-76b4-4b2b-8652-a76a4de43413.png)

> wvp配置文件

![image](https://user-images.githubusercontent.com/46513884/188085457-94d56480-edf7-4e78-901c-d696ae5172ee.png)

> 能够正常播放视频，但是就是录像不了
![image](https://user-images.githubusercontent.com/46513884/188086581-c5af8258-624b-452d-8d86-ee22e826abca.png)

**环境信息:**
 - 1. 部署方式编译wvp-pro + zlm +assist都是编译部署
 - 2. 部署环境 centos 
 - 3. 端口开放情况 开放防火墙
 - 4. 是否是公网部署 否
 - 5. 是否使用https 无
 - 6. 方便的话提供下使用的设备品牌或平台  海康
 - 7. 你做过哪些尝试  更换最新的代码

**Comment by 648540858** [comment]
仔细查看配置，那个路径配置 

>  # [必选 ] zlm配置的录像路径
> recird

是需要你配置成和zlm中一样的，而不是你这里配置了什么他就会给你录制到哪里，assist不负责录像，只是管理录像，录像还是由zlm进行录像的

**Comment by Gozly** [comment]
感谢大大   我找到配置了  就是配置路径错了
