### ISSUE TITLE
【技术咨询贴】关于级联点播，作为下级平台触发停止点播的场景

### ISSUE THREAD

**Issue by szy833** [648540858/wvp-GB28181-pro#600]
**描述错误**
级联测试的时候，上级平台点播的时候，下级平台也会触发点播，这是如果在下级平台，关闭点播的话，上级平台的点播也会停止。

**如何复现**
两个wvp级联，上级点播，下级关闭点播。上下级拉流都会停止

**预期行为**
这个是否应该是，下级点播的时候增加判断，如果上级还继续推流的话，就不关闭？

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
点击停止下级的点播。纳比必然是要把上级一起停止的，不然点击时候因为给上级推流就停不掉，是不是也像是个bug。你仔细考虑下。
