### ISSUE TITLE
点播超时或者出现收流超时

### ISSUE THREAD

**Issue by Gozly** [648540858/wvp-GB28181-pro#602]
**描述错误**
在点播开始后，接收平台第一次点播成功了，但是多次就不回成功了

**预期行为**
点播成功，ZLM分配资源成功

**截图**
第一次是成功的
![b739c999294e986c620e6db0806f805](https://user-images.githubusercontent.com/46513884/188796635-747767da-c0db-45fa-a556-84b1ace2bfe6.jpg)

关流后，再次点击观看同一个设备和同一通道就不成功了
![image](https://user-images.githubusercontent.com/46513884/188796687-47b34530-88fd-4b48-b125-70e9b1293d8c.png)

wvp配置 media部分
![image](https://user-images.githubusercontent.com/46513884/188797074-2f0885e2-35b6-4572-8427-c53e0357901b.png)
ZLM配置
![image](https://user-images.githubusercontent.com/46513884/188797321-2ed3ed1e-0e43-4121-bdc2-145b3332d477.png)
[config.txt](https://github.com/648540858/wvp-GB28181-pro/files/9502997/config.txt)

**环境信息:**
 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos 
 - 3. 端口开放情况 开放防火墙
 - 4. 是否是公网部署 否 全部内网
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试  更换最新版本wvp 或者 更换media的端口 ZLM的端口

**Comment by 648540858** [comment]
换个设备试试，你的设备没有回复点播消息

**Comment by Gozly** [comment]
我试了有几个了，还是没有成功的  关闭了多端口重试也一样
![eaaf81ca2e83f7f85709e6539ea4ece](https://user-images.githubusercontent.com/46513884/188804686-dbc3632b-5904-4049-8817-58da63bb1508.jpg)
![70420f4dedb4dbf6137e154c79f5e79](https://user-images.githubusercontent.com/46513884/188804819-79daa33e-7405-46c5-ad21-c0a84788dc8e.jpg)

**Comment by 648540858** [comment]
什么品牌的摄像机。代码是最新的吗

**Comment by Gozly** [comment]
代码是9月6日拉取编译的  摄像机有两个品牌都不用   
海康：iDS-TCE900-LMDP
大华：DH-PSDW8849M-A180-D440

**Comment by 648540858** [comment]
zlm也是最新的是吧
抓个包吧，重启下摄像机以及wvp和zlm，包括第一次成功和第二次失败的内容

**Comment by Gozly** [comment]
zlm是最新的  抓不了包  内网服务器  不联网的那种【笑哭】

**Comment by 648540858** [comment]
那没有办法了。我帮不了你

**Comment by Gozly** [comment]
![image](https://user-images.githubusercontent.com/46513884/189295762-8b05c91d-3f32-4787-9165-897bcb5a55e9.png)
设备一多  也会导致点播失败 
代码我也sh试了一下8月份的  也不行
[wvp-2022-09-09.0 (1).log](https://github.com/648540858/wvp-GB28181-pro/files/9533247/wvp-2022-09-09.0.1.log)

**Comment by 648540858** [comment]
确定下你服务的状态，内存，CPU，带宽是否足够

**Comment by Gozly** [comment]
感谢大大   现在已经解决了  跟服务器的带宽有关   解决办法：将摄像机的视频分辨率、码率等适当降低 就可以点播到了
