### ISSUE TITLE
wvp代码哪里实现的GB28181推流与断流的？

### ISSUE THREAD

**Issue by August1023** [648540858/wvp-GB28181-pro#603]
当关闭掉视频播放弹框时，前端代码调用了close()方法，但因为convertKey与recordPlay是空字符串，所以整个close()方法并没有实际性的操作(没有触发任何后端接口)，但是短时间之后ZLMediaKit流媒体服务器占用的udp端口会释放。能不能告诉我哪里触发了操作，使得GB28181不再推流给ZLMediaKit流媒体服务器？非常感谢！！！

![image](https://user-images.githubusercontent.com/45287355/189030234-7698e034-8a19-45b8-afb4-af31ccf26d07.png)

**Comment by 648540858** [comment]
> src/main/java/com/genersoft/iot/vmp/media/zlm/ZLMHttpHookListener.java
> 流无人观看时事件，用户可以通过此事件选择是否关闭无人看的流。
> on_stream_none_reader

**Comment by August1023** [comment]
找到了，感谢！
