### ISSUE TITLE
加了域名ssl 使能，但是拉流报错wss 失败

### ISSUE THREAD

**Issue by songdongwu** [648540858/wvp-GB28181-pro#606]
**描述错误**
我设置了 ssl 使能
![image](https://user-images.githubusercontent.com/33368314/189322088-5e907b08-29a0-4e28-b079-0aac3e37ed17.png)
但是取视屏的时候
![image](https://user-images.githubusercontent.com/33368314/189322301-020851fa-69b9-48f5-9372-ab29ae6572da.png)
报错
jessibuca.js:1 WebSocket connection to 'wss://47.109.17.73:50443/rtp/34020000001320000408_34020000001310000001.live.flv' failed: 

**环境信息:**
 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos ...
 - 3. 端口开放情况 都开放了
 - 4. 是否是公网部署 是
 - 5. 是否使用https

**Comment by 648540858** [comment]
wvp开启https之后，默认会使用zlm的https端口拉流，所以：
1. 你需要开启zlm的https端口
2. 最好给zlm也配置上证书，wvp的配置文件中media的stream.ip配置为域名即可。

**Comment by 648540858** [comment]
你的wvp中配置的证书叫xxx.jks?
