### ISSUE TITLE
wvp-pro 无法下载录像

### ISSUE THREAD

**Issue by wenyanjun** [648540858/wvp-GB28181-pro#607]
**描述错误**
wvp-pro 无法下载录像

**如何复现**
部署wvp-pro-assist  然下载视频

**预期行为**
录像能正常下载

**截图**
![image](https://user-images.githubusercontent.com/28703812/190039023-c8091f78-aa16-4f59-aced-fdd5983a6381.png)
![image](https://user-images.githubusercontent.com/28703812/190039058-813fa06c-1319-4bc4-8bdf-f521a1478b9f.png)

**环境信息:**
 - 1. 部署方式  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境ubuntu20.4
 - 3. 端口开放情况 同一台服务器部署端口完全开放
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台  海康摄像机
 - 7. 你做过哪些尝试  经过与群里交流,发现都存在这个问题

**Comment by wenyanjun** [comment]
经过代码调试发现是因为 录像路径配置不正确,但是配置正确的路径文件下载下来了不能合并
这个路径必须是 ZLM的下载路径
![image](https://user-images.githubusercontent.com/28703812/190053658-63632600-3165-4bfb-a591-501b8affa9c4.png)
配置好之后文件在本地有了,但是不能合并
![image](https://user-images.githubusercontent.com/28703812/190053800-ea0ecdda-7a84-41b8-bf3c-9e4a50e51c64.png)

![image](https://user-images.githubusercontent.com/28703812/190053614-3df0301c-b0cf-4709-8a6b-7d89400644b7.png)

**Comment by wenyanjun** [comment]
经排查,前端代码有问题第一处 进度问题
![image](https://user-images.githubusercontent.com/28703812/190074492-e117ff2e-25bd-491e-87a9-123706ae27b2.png)
第二处下载问题
![image](https://user-images.githubusercontent.com/28703812/190074821-dc253308-b3fd-4354-b468-8ff5b22f2839.png)
问题完美解决

**Comment by 648540858** [comment]
好的，已经合并了。
