### ISSUE TITLE
怎么挂载多台zlm流媒体服务器？

### ISSUE THREAD

**Issue by skywsp** [648540858/wvp-GB28181-pro#61]
设备太多了，一台zlm承受不了，怎么同时挂载多台zlm?

比如1000台NVR（上万个IPC），10台zlm，提供一种算法（比如轮询），动态计算nvr应该使用那台zlm。

另外客户点播时，如果nvr通过某台zlm拉流后，后续的截图/录屏/断流等操作，都需要和这台确定的zlm进行交互。

**Comment by 648540858** [comment]
多谢贡献

**Comment by 1216955142** [comment]
这个代码，没有合并主分支？

**Comment by socyli** [comment]
> 设备太多了，一台zlm承受不了，怎么同时挂载多台zlm?
> 
> 比如1000台NVR（上万个IPC），10台zlm，提供一种算法（比如轮询），动态计算nvr应该使用那台zlm。
> 
> 另外客户点播时，如果nvr通过某台zlm拉流后，后续的截图/录屏/断流等操作，都需要和这台确定的zlm进行交互。

实际中有没有测过一台什么样配置的机器能承受多少IPC或者nvr？

**Comment by 648540858** [comment]
已实现，可以部署测试。
