### ISSUE TITLE
录像下载失败（在文件夹里确实是下载了但是进度条一直是0%）

### ISSUE THREAD

**Issue by xue9957** [648540858/wvp-GB28181-pro#613]
**描述错误**
描述下您遇到的问题
录像下载失败（在文件夹里确实是下载了但是进度条一直是0%）
**如何复现**
有明确复现步骤的问题会很容易被解决
wvp、assist一同启动,点击录像下载还是0% 打断点发现duration返回值始终是0 
**预期行为**
清晰简洁的描述您期望发生的事情
下载100成功
**截图**
![H%)MX7F~5N~QORG8J`P R0](https://user-images.githubusercontent.com/77611572/190966485-36d6ecb7-9b92-4625-a699-2352f9aeb4aa.jpg)
![image](https://user-images.githubusercontent.com/77611572/190966976-a5727b6d-a0cd-4520-9b7d-927c8d579975.png)
![image](https://user-images.githubusercontent.com/77611572/190966997-bb94e2a5-eec2-44f0-89fc-6a533f937b8f.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
更新代码试试

**Comment by xue9957** [comment]
> 更新代码
![image](https://user-images.githubusercontent.com/77611572/191636693-b2801928-88a3-4ef9-baaf-9d9ac9b80532.png)
现在又成这样了

**Comment by xue9957** [comment]
![image](https://user-images.githubusercontent.com/77611572/191637475-77e18de4-77b0-4d6a-8b23-18a1c3fcde04.png)
wvp得传个开始结束时间给assist 然后在assist这的转时间后文件找不到就没有进这个循环 （windows系统）
![image](https://user-images.githubusercontent.com/77611572/191637615-a3ebf1a3-4c22-45c6-802f-271d5afc175c.png)

**Comment by skzdemo** [comment]
前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受

**Comment by skzdemo** [comment]
前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受

**Comment by skzdemo** [comment]
前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受

**Comment by xue9957** [comment]
> 前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受

不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间

**Comment by skzdemo** [comment]
你更新最新的代码，前端代码记得重新打包，然后就有进度了

**Comment by skzdemo** [comment]
> 

你更新最新的代码，前端代码记得重新打包，然后就有进度了

**Comment by skzdemo** [comment]
> > 前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受
> 
> 不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间

你更新最新的代码，前端代码记得重新打包，然后就有进度了

**Comment by xue9957** [comment]
> 



> > > 前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受
> > 
> > 
> > 不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间
> 
> 你更新最新的代码，前端代码记得重新打包，然后就有进度了

你是什么系统 我是windows系统做的

**Comment by skzdemo** [comment]
> 



> > 
> 
> > > > 前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受
> > > 
> > > 
> > > 不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间
> > 
> > 
> > 你更新最新的代码，前端代码记得重新打包，然后就有进度了
> 
> 你是什么系统 我是windows系统做的

ZLMediaKit和assist是部署在同一台centos上的。wvp是本地idea跑起来的

**Comment by xue9957** [comment]
> > 
> 
> > > 
>
> > 
> > > > > 前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受
> > > > 
> > > > 
> > > > 不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间
> > > 
> > > 
> > > 你更新最新的代码，前端代码记得重新打包，然后就有进度了
> > 
> > 
> > 你是什么系统 我是windows系统做的
> 
> ZLMediaKit和assist是部署在同一台centos上的。wvp是本地idea跑起来的




> 

但是我生成的本地文件都是当前的时间 并不是录像的时间  你有没有这问题

**Comment by skzdemo** [comment]
> > > 
> > 
> > 
> > > >
> > 
> > 
> > > > > > 前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受
> > > > > 
> > > > > 
> > > > > 不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间
> > > > 
> > > > 
> > > > 你更新最新的代码，前端代码记得重新打包，然后就有进度了
> > > 
> > > 
> > > 你是什么系统 我是windows系统做的
> > 
> > 
> > ZLMediaKit和assist是部署在同一台centos上的。wvp是本地idea跑起来的
> 
> > 
> 
> 但是我生成的本地文件都是当前的时间 并不是录像的时间 你有没有这问题

跟生成的文件名没关系的，我这边也是当前时间的

**Comment by skzdemo** [comment]
> 

duration返回值始终是0

> > > > 
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > > 前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受
> > > > > > 
> > > > > > 
> > > > > > 不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间
> > > > > 
> > > > > 
> > > > > 你更新最新的代码，前端代码记得重新打包，然后就有进度了
> > > > 
> > > > 
> > > > 你是什么系统 我是windows系统做的
> > > 
> > > 
> > > ZLMediaKit和assist是部署在同一台centos上的。wvp是本地idea跑起来的
> > 
> > 
> > > 
> > 
> > 
> > 但是我生成的本地文件都是当前的时间 并不是录像的时间 你有没有这问题
> 
> 跟生成的文件名没关系的，我这边也是当前时间的

duration返回值始终是0，你就要排查一下assist的那个接口有没有正确获取到录制文件夹的视频的时长了

**Comment by xue9957** [comment]
> > 
> 
> duration返回值始终是0
> 
> > > > > 
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > > > 前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受
> > > > > > > 
> > > > > > > 
> > > > > > > 不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间
> > > > > > 
> > > > > > 
> > > > > > 你更新最新的代码，前端代码记得重新打包，然后就有进度了
> > > > > 
> > > > > 
> > > > > 你是什么系统 我是windows系统做的
> > > > 
> > > > 
> > > > ZLMediaKit和assist是部署在同一台centos上的。wvp是本地idea跑起来的
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > 但是我生成的本地文件都是当前的时间 并不是录像的时间 你有没有这问题
> > 
> > 
> > 跟生成的文件名没关系的，我这边也是当前时间的
> 
> duration返回值始终是0，你就要排查一下assist的那个接口有没有正确获取到录制文件夹的视频的时长了



> > 
> 
> duration返回值始终是0
> 
> > > > > 
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > > > 前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受
> > > > > > > 
> > > > > > > 
> > > > > > > 不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间
> > > > > > 
> > > > > > 
> > > > > > 你更新最新的代码，前端代码记得重新打包，然后就有进度了
> > > > > 
> > > > > 
> > > > > 你是什么系统 我是windows系统做的
> > > > 
> > > > 
> > > > ZLMediaKit和assist是部署在同一台centos上的。wvp是本地idea跑起来的
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > 但是我生成的本地文件都是当前的时间 并不是录像的时间 你有没有这问题
> > 
> > 
> > 跟生成的文件名没关系的，我这边也是当前时间的
> 
> duration返回值始终是0，你就要排查一下assist的那个接口有没有正确获取到录制文件夹的视频的时长了

现在duration不是0了 但是生成的文件还是当前时间 然后下载到100后又弹出那个框 然后就不动了就一直0了

**Comment by skzdemo** [comment]
> 



> > > 
> > 
> > 
> > duration返回值始终是0
> > > > > > 
> > > > > 
> > > > > 
> > > > > > >
> > > > > 
> > > > > 
> > > > > > > > > 前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间
> > > > > > > 
> > > > > > > 
> > > > > > > 你更新最新的代码，前端代码记得重新打包，然后就有进度了
> > > > > > 
> > > > > > 
> > > > > > 你是什么系统 我是windows系统做的
> > > > > 
> > > > > 
> > > > > ZLMediaKit和assist是部署在同一台centos上的。wvp是本地idea跑起来的
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > 但是我生成的本地文件都是当前的时间 并不是录像的时间 你有没有这问题
> > > 
> > > 
> > > 跟生成的文件名没关系的，我这边也是当前时间的
> > 
> > 
> > duration返回值始终是0，你就要排查一下assist的那个接口有没有正确获取到录制文件夹的视频的时长了
> 
> > > 
> > 
> > 
> > duration返回值始终是0
> > > > > > 
> > > > > 
> > > > > 
> > > > > > >
> > > > > 
> > > > > 
> > > > > > > > > 前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间
> > > > > > > 
> > > > > > > 
> > > > > > > 你更新最新的代码，前端代码记得重新打包，然后就有进度了
> > > > > > 
> > > > > > 
> > > > > > 你是什么系统 我是windows系统做的
> > > > > 
> > > > > 
> > > > > ZLMediaKit和assist是部署在同一台centos上的。wvp是本地idea跑起来的
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > 但是我生成的本地文件都是当前的时间 并不是录像的时间 你有没有这问题
> > > 
> > > 
> > > 跟生成的文件名没关系的，我这边也是当前时间的
> > 
> > 
> > duration返回值始终是0，你就要排查一下assist的那个接口有没有正确获取到录制文件夹的视频的时长了
> 
> 现在duration不是0了 但是生成的文件还是当前时间 然后下载到100后又弹出那个框 然后就不动了就一直0了

看这个
https://github.com/648540858/wvp-GB28181-pro/pull/621

**Comment by skzdemo** [comment]
我改了前端两处代码之后是可以下载的，不知道你遇到的问题跟我一不一样






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月23日(星期五) 下午3:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [648540858/wvp-GB28181-pro] 录像下载失败（在文件夹里确实是下载了但是进度条一直是0%） (Issue #613)





  
前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受
  
不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间

**Comment by xue9957** [comment]
> 我改了前端两处代码之后是可以下载的，不知道你遇到的问题跟我一不一样
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年9月23日(星期五) 下午3:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [648540858/wvp-GB28181-pro] 录像下载失败（在文件夹里确实是下载了但是进度条一直是0%） (Issue #613) 前端取值问题导致的文件没有下载，已提交PR等待作者大佬接受 不是前端问题 后端那个命名规则得改一下 但是下载的视频命名是当前时间 不是录像时间 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我是windows系统 生成文件的符号不一样

**Comment by 648540858** [comment]
你是zlm部署再windows上吗

**Comment by xue9957** [comment]
> windows系统我尽量按照兼容的当时些，但是几乎没怎么测试，建议zlm + assist是部署在linux，wvp目前在win/linux都是可以的

对  zlm assits wvp 都在同一台win上 买的服务器的系统都是win的

**Comment by 648540858** [comment]
换linux吧，win10以上你可以用在windows使用linux子系统很方便。

**Comment by xue9957** [comment]
> 换linux吧，win10以上你可以用在windows使用linux子系统很方便。

好的 感谢大大
