### ISSUE TITLE
设备显示在线，但通道数为0

### ISSUE THREAD

**Issue by houge101** [648540858/wvp-GB28181-pro#614]
**描述错误**
海康设备显示在线，但通道数为0

**如何复现**
偶尔，没能找到规律

**预期行为**
海康摄像头注册成功后应该能显示设备通道号

**截图**
![image](https://user-images.githubusercontent.com/3355923/190978511-84c03277-c983-4c0e-bdaf-4395908387ed.png)
![image](https://user-images.githubusercontent.com/3355923/190978584-7edb815d-0810-4f71-a74e-9f6a44ab1bc0.png)

**环境信息:**
 - 1. 部署方式编译wvp-pro + zlm都是编译部署
 - 2. 部署环境wvp-pro部署到 windows10 /zlm部署到 centos
 - 3. 局域网（wvp-pro、zlm和海康摄像头在同一个路由器）
 - 4. 是否是公网部署（否）
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台（海康摄像头，惠普台式机）
 - 7. 你做过哪些尝试（仅仅部署了wvp-pro和zlm，修改码流信息，重启设备（包括只启动WVP，ZLM，数据库和全部重启），以及刷新等操作）
海康IP：192.168.50.64，台式机（WVP）192.168.50.59， 服务器（ZLM）192.168.50.130

wireshark抓包。issue不让上传，所以传网盘里面了
链接：https://pan.baidu.com/s/1ob-yOAMEEZs5fPtXJJSUDg 
提取码：z6op

**Comment by houge101** [comment]
yml部署如下
![image](https://user-images.githubusercontent.com/3355923/190980409-8dcd0b87-3e6c-48b5-ba6c-8cae5be7e051.png)
密码确定二者相同（海康和WVP）

**Comment by houge101** [comment]
![image](https://user-images.githubusercontent.com/3355923/191145717-ac81114c-2460-4dc5-b5dc-f2e4f21f44f4.png)
![image](https://user-images.githubusercontent.com/3355923/191145750-1650ba39-c5d2-4061-b3c7-2b19cf7f625a.png)
![image](https://user-images.githubusercontent.com/3355923/191145781-ede2329b-924f-4b23-a348-40400a7ece1a.png)
我又测试了另外一台设备，上面的 id 跟配置文件不同，但一样能显示。所以没太明白通道数为0的原因

**Comment by 648540858** [comment]
抓包里没看到catalog请求，你的代码是什么时候的

**Comment by houge101** [comment]
9月7号的

**Comment by treespringace** [comment]
我也是同样的问题,如何排查

**Comment by 648540858** [comment]
开启抓包，点击刷新通道，然后把抓包文件穿上来看下

**Comment by 648540858** [comment]
你没有点击刷新呀

**Comment by HuangDayu** [comment]
> 抓包里没有目录查询请求

没有目录查询的原因是因为没有点击刷新吗？

**Comment by 648540858** [comment]
是啊，我加了通道为0时更新通道，你可以再测试下。

**Comment by HuangDayu** [comment]
> 是啊，我加了通道为0时更新通道，你可以再测试下。

我们部署的环境是联通4G物联网专网。多个网卡，多次转发。

现在出现两个情况：

1. 消息发送超时错误，回调了processTimeout方法；
2. 存在摄像头只注册设备情况，而没有注册通道，发现mvp服务没有发送catalog和deviceInfo指令，即使调用sync()方法，也不起作用。

请问这样的情况，如何排查问题？如何延长sip发送请求的超时时间？ @648540858

**Comment by HuangDayu** [comment]
[15070-1 (1).zip](https://github.com/648540858/wvp-GB28181-pro/files/9830519/15070-1.1.zip)

发送catalog没有回复的抓包文件。 @648540858

**Comment by duhaohao** [comment]
我也有相同的问题。

**Comment by 648540858** [comment]
消息发送不过去，你需要确认下网络是否通畅，猜测你的设备收不到服务的信息。

**Comment by duhaohao** [comment]
好的，谢谢您的回复。确实是网络问题，路由器上可能有些配置, 导致数据过不来。内网部署正常。&nbsp;


清浅-
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月25日(星期二) 下午2:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [648540858/wvp-GB28181-pro] 设备显示在线，但通道数为0 (Issue #614)





 
消息发送不过去，你需要确认下网络是否通畅，猜测你的设备收不到服务的信息。

**Comment by 648540858** [comment]
好的

**Comment by HuangDayu** [comment]
我在设备端抓包，设备事实上是收到了[catalog请求](https://github.com/648540858/wvp-GB28181-pro/issues/614#issuecomment-1285544497)的，但是却始终没有回复。

我在内网环境也是正常的，可是到了物联网专网环境下就不行了。这是设备端抓包结果，麻烦帮忙分析一下：

[nvr-package.zip](https://github.com/648540858/wvp-GB28181-pro/files/9875180/nvr-package.zip)

@648540858 谢谢。

PS：一点猜想，catalog请求是否跟sdpIp有关？因为经过了多层的网络转发，多层ip代理，是否跟sip协议包中所包含的ip地址或端口的准确性有关？如果设备注册消息能收到回复，说明整个网络路径是正常的，可用的。

**Comment by HuangDayu** [comment]
![0f3b2f5b5cf72ff2801fc0ea65b826f](https://user-images.githubusercontent.com/23421574/198237887-b0dba36f-b7cf-413c-a154-c3c2794b553a.png)

失败的原因可能是因为From中的IP和端口与SIP服务代理的IP和端口不同所致。

那么怎么能在代码中指定From中的IP和端口呢？看了源码，没找到方法。

**Comment by HuangDayu** [comment]
问题已解决，确是IP和端口不一致引起。

**Comment by zhuuvzhi** [comment]
> 问题已解决，确是IP和端口不一致引起。

@HuangDayu 请问是怎么解决的🙏🏻

**Comment by wx46846548** [comment]
非常好

**Comment by Felixchen1024** [comment]
同样出现设备在线但是通道号为0，不知道如何解决。
PS使用场景：
1、内网测试都OK；
2、云服务器部署，出现设备在线但是通道号为0
请问大佬们怎么解决的

**Comment by Felixchen1024** [comment]
> 
大佬，请问怎么改代码解决的？

**Comment by Felixchen1024** [comment]
@HuangDayu 请问大佬，是怎么解决的？改源码吗？
定位到下面代码，但只涉及设备端的IP。。
/**
     * 查询目录列表
     *
     * @param device 视频设备
     */
    @Override
    public void catalogQuery(Device device, int sn, SipSubscribe.Event errorEvent) throws SipException, InvalidArgumentException, ParseException {

        StringBuffer catalogXml = new StringBuffer(200);
        String charset = device.getCharset();
        catalogXml.append("<?xml version=\"1.0\" encoding=\"" + charset + "\"?>\r\n");
        catalogXml.append("<Query>\r\n");
        catalogXml.append("  <CmdType>Catalog</CmdType>\r\n");
        catalogXml.append("  <SN>" + sn + "</SN>\r\n");
        catalogXml.append("  <DeviceID>" + device.getDeviceId() + "</DeviceID>\r\n");
        catalogXml.append("</Query>\r\n");

        

        Request request = headerProvider.createMessageRequest(device, catalogXml.toString(), SipUtils.getNewViaTag(), SipUtils.getNewFromTag(), null,sipSender.getNewCallIdHeader(sipLayer.getLocalIp(device.getLocalIp()),device.getTransport()));

        sipSender.transmitRequest(sipLayer.getLocalIp(device.getLocalIp()), request, errorEvent);
    }

**Comment by Zonciu** [comment]
截图中的白名单，把服务器IP地址加上去

**Comment by SugaraguS** [comment]
遇到了类似的问题，初次注册进来时候通道数时正常的，但是删除设备后，重新注册进来就只有设备没有通道了，然后给redis清空，重启服务之后再注册进来就有通道了

**Comment by Kkmdfuck** [comment]
类似的问题，我海康摄像头接入是正常的，但是大华的摄像头接入进来就是设备在线，但是通道离线的情况，大华摄像头也无法点播。我开启了https，云服务器部署。有大佬知道是什么问题吗？

**Comment by mstaryi** [comment]
我也遇到类似问题了，接入的多个摄像头，有的显示有通道，有的没有。有大佬知道是怎么回事么？
