### ISSUE TITLE
WVP点播拉取ZML时RPTServer打开超时

### ISSUE THREAD

**Issue by lanwilliam** [648540858/wvp-GB28181-pro#615]
**描述错误**
WVP点播拉取ZML时RPTServer打开超时

**截图**
![image](https://user-images.githubusercontent.com/8511385/191225483-7b54718c-40d7-43e8-9d6b-1d44c4df89c7.png)

**环境信息:**
我其实已经按照要求配置过wvp的media.ip为ZML的内网ip了
![image](https://user-images.githubusercontent.com/8511385/191225759-fc238d96-d9c4-445a-9a2b-198224ad3af8.png)
但仍然不解决问题
目前是全端口开放了tcp和udp协议。
ZML通过ffmepge测试过推流，没有问题
![image](https://user-images.githubusercontent.com/8511385/191225993-3e8e666e-cb86-4d9e-9e92-22ff47276520.png)
![image](https://user-images.githubusercontent.com/8511385/191226055-606c8f56-e9c8-435a-9193-59e1747f667d.png)
不清楚问题出在哪里。

**Comment by HammerZhao** [comment]
先把rtp 的端口改为固定端口 然后看相机有没有发送rtp包也顺便看看wvp  sip 跟相机的交互的过程的细节这里得看懂
这里的片段看着跟zlm没有关系

**Comment by lanwilliam** [comment]
找到问题了，是由于wvp默认yml配置少了很多配置项目，参考application-all.yml重新配置后解决。
