### ISSUE TITLE
WVP配置ssl数字证书后，导致ZML拉流错误

### ISSUE THREAD

**Issue by lanwilliam** [648540858/wvp-GB28181-pro#617]
**描述错误**
给wvp和ZML均配置了域名和数字证书。
wvp可以正常启动，并且能够注册上来设备。
但是播放视频流失败。
发现wvp调取ZMLhook等接口均使用http调用，导致ZML通过FFmepg的时候使用的是http的地址。
引发后续一系列问题。图片如下：
![image](https://user-images.githubusercontent.com/8511385/191650783-8ff4c66d-4c13-4d1e-b6b9-2e4faf14ecfd.png)

![image](https://user-images.githubusercontent.com/8511385/191650749-47cf4045-e132-457a-b6b9-0c1b8827015f.png)

![image](https://user-images.githubusercontent.com/8511385/191650863-9ad8b794-57ca-42f3-859b-7c04b8775dcb.png)

zml配置（wvp修改的）
![image](https://user-images.githubusercontent.com/8511385/191651637-de97a811-f392-466b-a1ff-b7d2c357a96a.png)

在配置ssl后，会默认吧ZML的hook都改成https的地址

感觉问题出在这里，需要核实。

**环境信息:**
环境信息不在放了，因为http的时候都是通的，应该不存在环境问题。所有ssl端口也全部放通了

**Comment by 648540858** [comment]
代码什么时候的

**Comment by lanwilliam** [comment]
直接拉的git上的，应该是最新版本

**Comment by lanwilliam** [comment]
不是wvp的问题，是zml的pem文件配置问题。
zml的pem不能直接用ca给的pem，需要吧key手动和到pem中去。
