### ISSUE TITLE
ZLM节点丢失

### ISSUE THREAD

**Issue by houge101** [648540858/wvp-GB28181-pro#618]
**描述错误**
wvp-pro正常运行，网页打开后长时间不管理（大约三小时），再次打开网页，zlm节点不显示，控制台无数据

**如何复现**
正常打开后不在管ZLM和WVP一段时间。（我还用VLC拉取一路rtsp流，不知是否有影响）

**预期行为**
正常打开

**代码时间**
（ZLM与WVP代码都为9月21日拉取）

**截图**
![image](https://user-images.githubusercontent.com/3355923/191680716-1be3a5bc-8d86-417a-84bb-f13df4334473.png)
![image](https://user-images.githubusercontent.com/3355923/191682363-a7d0a043-3d24-4ab3-afb7-f290a3cf2748.png)
ZLM侧打印如下（11点10分开始设置拉流）
![image](https://user-images.githubusercontent.com/3355923/191682913-5e08c5a9-d3f4-4f61-9516-4c7829255bb5.png)

**环境信息:**
 - 1.  部署方式编译wvp-pro + zlm都是编译部署
 - 2. 部署环境wvp-pro部署到 windows10 /zlm部署到 centos
 - 3. 局域网（wvp-pro、zlm和海康摄像头在同一个路由器），端口默认
 - 4. 是否是公网部署（否）
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台（海康普通枪机摄像头，惠普台式机）
 - 7. 你做过哪些尝试

**Comment by houge101** [comment]
![image](https://user-images.githubusercontent.com/3355923/191684379-69632f52-354c-485f-b61a-4e9cfb3fcb42.png)
wvp一直打印更新保活失败。

**Comment by 648540858** [comment]
wvp 与zlm之间不通了，你自己测试下。中间是不是有休眠之类的情况

**Comment by SUNRise666s** [comment]
我也一直有同样的情况

**Comment by houge101** [comment]
> 

休眠是电脑休眠还是wvp休眠啊。我看了下，好像一切都正常呢。不知道该往哪个方向查啊。方便指点一下么？
