### ISSUE TITLE
回看控制失效

### ISSUE THREAD

**Issue by skzdemo** [648540858/wvp-GB28181-pro#619]
**描述错误**
设备录像回看，回看正常，但是一切的回看控制是失效的。debugger代码发现是在从事务中获取dialog信息的时候，dialog信息为null。致使没有发送sip消息给设备。获取dialog方法com.genersoft.iot.vmp.gb28181.session.VideoStreamSessionManager#getDialogByStream

**如何复现**
1、点击一个设备录像进行回看->回看的过程中点击暂停、倍速播放、控制播放进度条等

**预期行为**
回看能够正确控制

**截图**
1、回看页面
![image](https://user-images.githubusercontent.com/32671613/191755467-a60dd0cb-a603-417c-b950-1f69f9418111.png)
2、debugger页面
![image](https://user-images.githubusercontent.com/32671613/191756226-4dd6a3c8-94e0-46f5-9fcb-4b96395ab8d3.png)

**环境信息:**
 - 1. 部署方式 
 -  wvp-pro + zlm都是编译部署
 - 2. 部署环境 
 - wvp-pro-本地windows
 -zlm是内网centos
 - 3. 端口开放情况
 - 全开放
 - 4. 是否是公网部署
 - 否，使用内网，全部可达
 - 5. 是否使用https
 - 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 品牌是京目摄像头（带本地存储）；型号是JW-W2024-Y
 - 7. 你做过哪些尝试
 - 由于对sip不熟悉，所以还在了解sip事务以及会话知识中。烦请大佬帮忙指教一下

**Comment by skzdemo** [comment]
排查之后请求回放视频流时没有将dialog存到redis，导致回放控制的时候获取不到，已提交PR

**Comment by skzdemo** [comment]
但是验证之后发现，回放控制只有倍速播放、暂停可以使用。但是其他操作 快进以及暂停之后重新播放不能有效控制。初步排查是因为快进以及暂停之后重新播放会导致ZLMedia流被注销。目前不知道怎么入手修改。烦请大佬指定。谢谢

**Comment by 648540858** [comment]
更新代码测试下

**Comment by 648540858** [comment]
这个后面考虑怎么优化下

**Comment by skzdemo** [comment]
> 更新代码测试下

已更新代码验证。目前只支持倍速播放。其余操作均会导致ZLMediaKit的流被注销

**Comment by skzdemo** [comment]
> 这个后面考虑怎么优化下

好的，非常感谢大佬

**Comment by 818ajian** [comment]
最新版本海康、大华摄像头都存在同样问题。

**Comment by 648540858** [comment]
我考虑了一下，这个目前没有好的办法，因为无法知道这个时间播放到了哪里，如果知道这个可以通过重新开启回放解决

**Comment by 648540858** [comment]
从播放器获取播放的时间是可以的，但是这个目前只能是在这个播放器器上实现，意义不大

**Comment by 648540858** [comment]
已修复，测试如果发现仍然不行，就发个抓包，看看是不是设备主动停止了

**Comment by tianya2222** [comment]
> 已修复，测试如果发现仍然不行，就发个抓包，看看是不是设备主动停止了

更新最新代码部署运行后仍然有这个问题

**Comment by 648540858** [comment]
抓个包，目前已经是修复了的
