### ISSUE TITLE
流已经关闭后，再次调用关闭流的接口，返回超时

### ISSUE THREAD

**Issue by longegit** [648540858/wvp-GB28181-pro#62]

**Comment by longegit** [comment]
还有个问题，当服务部署在云上当时候，关闭流会导致超时，当siplayer收到processResponse关闭应答当时候，zlm当回调已经把流删除流，导致走了如下当代码，引起超时。
		cmder.streamByeCmd(streamId, event -> {
			StreamInfo streamInfo = redisCatchStorage.queryPlayByStreamId(streamId);
			if (streamInfo == null) {
				RequestMessage msg = new RequestMessage();
				msg.setId(DeferredResultHolder.CALLBACK_CMD_PlAY + uuid);
				msg.setData("streamId not found");
				resultHolder.invokeResult(msg);

**Comment by 648540858** [comment]
我查下一下

**Comment by 648540858** [comment]
已修复
