### ISSUE TITLE
请求截图功能有问题，貌似被缓存了

### ISSUE THREAD

**Issue by realbillwong** [648540858/wvp-GB28181-pro#622]
**描述错误**
调用请求截图功能的时候，返回的图片始终都是第一次截的图。我试过隔两天后再次截图，接口返回的图片仍然是2天前的画面。

**如何复现**
隔一段时间发送请求截图接口，查看截图图片

**预期行为**
截当前时间点的图片

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker)
 - 2. 部署环境 Centos
 - 3. 端口都已开放
 - 4. 是公网部署
 - 5. 使用https
 - 6. 海康摄像头和 NVR 都试过

**Comment by 648540858** [comment]
截图只会发生在点播成功时，不会实时更新
