### ISSUE TITLE
google浏览器实时直播,画面倒立

### ISSUE THREAD

**Issue by treespringace** [648540858/wvp-GB28181-pro#624]
**描述错误**
在google最新版本的浏览器上,直播画面是倒立的
![image](https://user-images.githubusercontent.com/83049927/191943040-66be65b5-4c80-4c9e-b229-38461532658b.png)

**如何复现**
火狐的画面是正常的,google上直播画面倒立

**预期行为**

**截图**
![image](https://user-images.githubusercontent.com/83049927/191942843-321a1340-8300-4200-abcb-bda6e7e91d44.png)

**环境信息:**
 - 1. 部署方式 wvp-pro idea启动 / zlm(linux虚拟机)  wvp和zlm均是最新的代码
 - 2. 部署环境 windows /centos 7
 - 3. 端口开放情况
 - 4. 没有公网部署
 - 5. 未使用https
 - 6. 海康摄像头
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
播放器的原因，可以自行替换自己合适的播放器
