### ISSUE TITLE
ZLM丢失

### ISSUE THREAD

**Issue by FlowerGhost** [648540858/wvp-GB28181-pro#629]
**描述错误**
wvp正常连接到zlm服务之后，中间突然断开zlm服务(杀进程，后重启zlm服务)，会导致wvp一直无法重新连接到zlm服务。

**如何复现**
wvp正常连接到zlm服务之后，中间突然断开zlm服务(杀进程，后重启zlm服务)

**预期行为**
日志产看到如下信息：
WARN  c.g.iot.vmp.service.impl.MediaServerServiceImpl:655 - [更新ZLM 保活信息]失败，未找到流媒体信息,尝试重连zlm
WARN  c.g.iot.vmp.service.impl.MediaServerServiceImpl:660 - [更新ZLM 保活信息]失败，未找到流媒体信息
源码中有一处注释了重连方法。

**截图**
![image](https://user-images.githubusercontent.com/28777365/192990179-f6014eef-fa45-433c-9a28-1e5917fb71f7.png)

**环境信息:**
 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows 
 - 3. 端口开放情况 正常放
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否

**Comment by 648540858** [comment]
重启zlm后zlm会发送hook的，你是在wvp帮你拉起zlm进程吗

**Comment by 648540858** [comment]
wvp和zlm之间就是简单的http连接，没有其他的

**Comment by FlowerGhost** [comment]
[ ZLM HOOK ]on_server_keepalive API调用，参数：{"mediaServerId":"FQ3TF8yT83wh5Wvz","data":{"Buffer":8,"RtpPacket":0,"Frame":0,"RtmpPacket":0,"TcpSession":0,"UdpServer":16,"TcpServer":43,"FrameImp":0,"BufferList":0,"BufferRaw":8,"MediaSource":0,"MultiMediaSourceMuxer":0,"TcpClient":0,"BufferLikeString":0,"Socket":59,"UdpSession":0}}
WARN  c.g.iot.vmp.service.impl.MediaServerServiceImpl:655 - [更新ZLM 保活信息]失败，未找到流媒体信息,尝试重连zlm
WARN  c.g.iot.vmp.service.impl.MediaServerServiceImpl:660 - [更新ZLM 保活信息]失败，未找到流媒体信息
DEBUG GB28181_SIP:212 - BUILD TIMESTAMP = null
DEBUG GB28181_SIP:213 - Config Propeties = {}{gov.nist.javax.sip.CANCEL_CLIENT_TRANSACTION_CHECKED=false, gov.nist.javax.sip.RELIABLE_CONNECTION_KEEP_ALIVE_TIMEOUT=60, gov.nist.javax.sip.RELEASE_REFERENCES_STRATEGY=Normal, gov.nist.javax.sip.AUTOMATIC_DIALOG_ERROR_HANDLING=false, gov.nist.javax.sip.COMPUTE_CONTENT_LENGTH_FROM_MESSAGE_BODY=true, javax.sip.AUTOMATIC_DIALOG_SUPPORT=off, gov.nist.javax.sip.TRACE_LEVEL=ERROR, gov.nist.javax.sip.DELIVER_UNSOLICITED_NOTIFY=true, gov.nist.javax.sip.DELIVER_TERMINATED_EVENT_FOR_NULL_DIALOG=true, javax.sip.STACK_NAME=GB28181_SIP, javax.sip.IP_ADDRESS=0.0.0.0}
2022-09-29 12:50:24.774 [Thread-279] DEBUG GB28181_SIP:216 - gov.nist.javax.sip.stack.UDPMessageChannel.processIncomingDataPacket(UDPMessageChannel.java:449) [Not sending ping back]


日志中会一直不断的重复这一块信息，zlm服务是我手动启动的，就是wvp 不会自动重连到zlm服务上。

**Comment by FlowerGhost** [comment]
目前的处理方法是 再一次重启wvp服务 就能自动连接到zlm服务

**Comment by energyjry** [comment]
我也发现zlm重启之后无法自动连接的情况了。经查是wvp接收到zlm的on_server_started回调之后报错，原因是回调的参数里包含中文，估计是utf8编码格式的问题。临时解决办法是把修改zlm的config.ini，把[http][notFound]里的中文“您访问的资源不存在！”改为"404"。

`notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>404</h1></center><hr><center>ZLMediaKit(git hash:679c798,branch:master,build time:Aug 30 2022 10:22:14)</center></body></html>
`

**Comment by FlowerGhost** [comment]
好的 谢谢您提供给的方法 因为很经常断开服务 导致wvp一直重连不上zlm

**Comment by FlowerGhost** [comment]
> 



> 我也发现zlm重启之后无法自动连接的情况了。经查是wvp接收到zlm的on_server_started回调之后报错，原因是回调的参数里包含中文，估计是utf8编码格式的问题。临时解决办法是把修改zlm的config.ini，把[http][notFound]里的中文“您访问的资源不存在！”改为"404"。
> 
> `notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>404</h1></center><hr><center>ZLMediaKit(git hash:679c798,branch:master,build time:Aug 30 2022 10:22:14)</center></body></html> `
好的 谢谢您的方法

**Comment by 648540858** [comment]
具体报了什么错误

**Comment by FlowerGhost** [comment]
就是会一直重试连接zlm服务

**Comment by 648540858** [comment]
你是启动就一直没连上吧

**Comment by FlowerGhost** [comment]
你是不看我描述 或者看不懂我的描述吗？

**Comment by FlowerGhost** [comment]
描述错误 难道我的描述是摆设？

**Comment by 648540858** [comment]
中间断开不会一直重联，会有
```
[ZLM] 离线，ID：***
```
这样的提示

**Comment by 648540858** [comment]
如果一直有
```
[更新ZLM 保活信息]失败，未找到流媒体信息,尝试重
```
那就是主动连接成功，但是zlm的hook心跳通知失败了

**Comment by energyjry** [comment]
> 具体报了什么错误
![image](https://user-images.githubusercontent.com/49065390/193225767-15adecc5-d86e-4db9-b0db-6d0dd79ee17e.png)

**Comment by 648540858** [comment]
这种对功能没有影响，比如zlm发送hook花费了太长时间，你截图这个似乎是http消息体拿不到，导致转json失败了

**Comment by 648540858** [comment]
抓包看看zlm发来的请求内容

**Comment by 648540858** [comment]
手动重启就是主动连接了

**Comment by 648540858** [comment]
> > 具体报了什么错误
> > ![image](https://user-images.githubusercontent.com/49065390/193225767-15adecc5-d86e-4db9-b0db-6d0dd79ee17e.png)

你这个似乎是发送请求不全，你抓包看看http请求是不是不全

**Comment by FlowerGhost** [comment]
是的，所以想问的是如何能够自动重连

**Comment by energyjry** [comment]
> 抓包看看zlm发来的请求内容

把zlm的hook里中文参数换掉就好了。所以很可能是utf8编码的问题

"http.notFound" : "<html><head><title>404 Not Found</title></head><body bgcolor=\"white\"><center><h1>您访问的资源不 存在！</h1></center><hr><center>ZLMediaKit(git hash:679c798,branch:master,build time:Aug 30 2022 10:22:14)</center></body></html>",

**Comment by 648540858** [comment]
> zlm的hook心跳通知失败了 那我们一般需要怎处理呢？目前处理方式 是手动重启wvp服务即可

从zlm服务器访问wvp试试，看看可不可以通

**Comment by FlowerGhost** [comment]
都是部署在同一台主机上的。

**Comment by 648540858** [comment]
你的电脑是不是开防火墙了

**Comment by energyjry** [comment]
> > > 具体报了什么错误
> > > ![image](https://user-images.githubusercontent.com/49065390/193225767-15adecc5-d86e-4db9-b0db-6d0dd79ee17e.png)
> 
> 你这个似乎是发送请求不全，你抓包看看http请求是不是不全

把zlm请求参数里包含的的中文换掉就行了。所以很可能是utf8编码的问题。
![image](https://user-images.githubusercontent.com/49065390/193227294-3d67f9b3-34fc-4cf3-a808-563408edf392.png)

**Comment by 648540858** [comment]
> > > > 具体报了什么错误
> > > > ![image](https://user-images.githubusercontent.com/49065390/193225767-15adecc5-d86e-4db9-b0db-6d0dd79ee17e.png)
> > 
> > 
> > 你这个似乎是发送请求不全，你抓包看看http请求是不是不全
> 
> 把zlm请求参数里包含的的中文换掉就行了。所以很可能是utf8编码的问题。 ![image](https://user-images.githubusercontent.com/49065390/193227294-3d67f9b3-34fc-4cf3-a808-563408edf392.png)

这个我不确定，我自己一直使用的带中文的，再一个问题，不应该走到这里的，这个访问http的接口时，出现404才会返回的内容

**Comment by energyjry** [comment]
> on_server_started
zlm在重启的时候会把它的配置都hook返回给wvp。里面包含了这个中文的内容，wvp那里报错了。所以zlm重启之后和wvp恢复连接的机制失效了，wvp会一直重连。我这边测试到的现象就是这样的。
![image](https://user-images.githubusercontent.com/49065390/193229088-db57f4b3-f671-4f44-ba61-93c183c91be3.png)

**Comment by 648540858** [comment]
你这截图跟问题有关联吗。这是发hook。是zlm->wvp，你移除的内容属于wvp->zlm呀
