### ISSUE TITLE
请问一下用一个wvp平台去监控分布在各个地方的摄像头，应该怎么操作

### ISSUE THREAD

**Issue by ppepenpeng** [648540858/wvp-GB28181-pro#631]
每个摄像头是放在内网的，摄像头配置wvp平台的的信息，注册上去
![image](https://user-images.githubusercontent.com/108248278/194696216-8e885368-bb03-47b2-8a40-cf186705b0c6.png)

然后就能在这个页面看见所有摄像头的信息了
![image](https://user-images.githubusercontent.com/108248278/194696253-c9c46c96-aa73-45d8-a475-f7ae1a547103.png)
请问这样的操作有问题吗？我现在只有一个摄像头，而且wvp平台和摄像头是在同一个内网里的，不方便测试，请问一下大佬这个的解决方案。
另外请问一下项目是如何支持nat穿透的，文档没有看见。

**Comment by 648540858** [comment]
wvp部署在公网就可以了呀

**Comment by yogo-zhangyingzhe** [comment]
> wvp部署在公网就可以了呀

意思是wvp实现了nat穿透吧。 我把摄像头部署在内网， wvp放在公网， 只要摄像头注册到wvp， 那么wvp就能给摄像头invite进行点播吧？
