### ISSUE TITLE
开始点播功能接口调用返回参数与定义的不符

### ISSUE THREAD

**Issue by cxy-abing** [648540858/wvp-GB28181-pro#635]
调用这个接口 com.rainyhon.media.vmanager.gb28181.play.PlayController#play,返回值应该是一个string,但是我的返回值是这个,明显是一个大对象,请问是什么原因?
`{
    "code": 0,
    "msg": "success",
    "data": {
        "app": "rtp",
        "stream": "51010700491110000001_34020000001320000001",
        "deviceID": "51010700491110000001",
        "channelId": "34020000001320000001",
        "flv": "http://192.168.1.243:8080/rtp/51010700491110000001_34020000001320000001.live.flv",
        "ip": "192.168.1.243",
        "https_flv": "https://192.168.1.243:443/rtp/51010700491110000001_34020000001320000001.live.flv",
        "ws_flv": "ws://192.168.1.243:8080/rtp/51010700491110000001_34020000001320000001.live.flv",
        "wss_flv": "wss://192.168.1.243:443/rtp/51010700491110000001_34020000001320000001.live.flv",
        "fmp4": "http://192.168.1.243:8080/rtp/51010700491110000001_34020000001320000001.live.mp4",
        "https_fmp4": "https://192.168.1.243:443/rtp/51010700491110000001_34020000001320000001.live.mp4",
        "ws_fmp4": "ws://192.168.1.243:8080/rtp/51010700491110000001_34020000001320000001.live.mp4",
        "wss_fmp4": "wss://192.168.1.243:443/rtp/51010700491110000001_34020000001320000001.live.mp4",
        "hls": "http://192.168.1.243:8080/rtp/51010700491110000001_34020000001320000001/hls.m3u8",
        "https_hls": "https://192.168.1.243:443/rtp/51010700491110000001_34020000001320000001/hls.m3u8",
        "ws_hls": "ws://192.168.1.243:8080/rtp/51010700491110000001_34020000001320000001/hls.m3u8",
        "wss_hls": "wss://192.168.1.243:443/rtp/51010700491110000001_34020000001320000001/hls.m3u8",
        "ts": "http://192.168.1.243:8080/rtp/51010700491110000001_34020000001320000001.live.ts",
        "https_ts": "https://192.168.1.243:443/rtp/51010700491110000001_34020000001320000001.live.ts",
        "ws_ts": "ws://192.168.1.243:8080/rtp/51010700491110000001_34020000001320000001.live.ts",
        "wss_ts": "wss://192.168.1.243:443/rtp/51010700491110000001_34020000001320000001.live.ts",
        "rtmp": "rtmp://192.168.1.243:1935/rtp/51010700491110000001_34020000001320000001",
        "rtmps": null,
        "rtsp": "rtsp://192.168.1.243:554/rtp/51010700491110000001_34020000001320000001",
        "rtsps": null,
        "rtc": "https://192.168.1.243:443/index/api/webrtc?app=rtp&stream=51010700491110000001_34020000001320000001&type=play",
        "mediaServerId": "rainyhon_zlm_media",
        "tracks": [
            {
                "codecIdName": null,
                "codecId": 0,
                "channels": 1,
                "sampleBit": 0,
                "ready": true,
                "fps": 0,
                "width": 0,
                "codecType": 0,
                "sampleRate": 0,
                "height": 0
            },
            {
                "codecIdName": null,
                "codecId": 0,
                "channels": 0,
                "sampleBit": 0,
                "ready": true,
                "fps": 25,
                "width": 1920,
                "codecType": 0,
                "sampleRate": 0,
                "height": 1080
            }
        ],
        "startTime": null,
        "endTime": null,
        "progress": 0.0,
        "transactionInfo": null
    }
}`

**Comment by FlowerGhost** [comment]
个人建议，就是在liunx上docker部署一套，能正常运行的服务，然后增加日志查看与对比你自己调用的方式。是不是哪里参数或者参数错误导致。
