### ISSUE TITLE
删除用户失败

### ISSUE THREAD

**Issue by FlowerGhost** [648540858/wvp-GB28181-pro#636]
**描述错误**
用户管理中，删除用户无反应，删除失败，未有任何提示

**如何复现**
用户管理，增加新用户，然后再进行用户删除操作

**预期行为**
删除用户成功

**截图**
![image](https://user-images.githubusercontent.com/28777365/195226630-ee3734fc-2ada-42dd-8ec9-33c522018bb9.png)
![image](https://user-images.githubusercontent.com/28777365/195226719-f6f53110-6f20-4a5c-ba7f-013f51198ca2.png)

**环境信息:**
 - 1. 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos
 - 3. 端口开放情况  全部开放
 - 4. 是否是公网部署  否
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台 
 - 7. 你做过哪些尝试
 - 修改源代码  
 - @DeleteMapping("/delete")
    @Operation(summary = "删除用户")
但会导致服务起不来

**Comment by 648540858** [comment]
好的 我测试下

**Comment by 648540858** [comment]
已修复
