### ISSUE TITLE
推流集群连接问题

### ISSUE THREAD

**Issue by L120820** [648540858/wvp-GB28181-pro#638]
**描述错误**
在推流重启的时候 redis的 推流集群 刷新出现空白 value

**如何复现**
启动zlm 调用设备开始推流 停止zlm 即可复现

**预期行为**
zlm的上下线 删除对应的zlm 不应该出现 空value

**截图**
![image](https://user-images.githubusercontent.com/115628991/195321704-e5732b95-2f51-4d3f-ba72-c2026e8218c4.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker 
 - 2. 部署环境  centos 
 - 3. 端口开放情况 使用docker的host网络模式 所有端口都开放
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 不涉及
 - 7. 你做过哪些尝试 尝试使用redis命令对 VMP_MEDIA_ONLINE_SERVERS_000000 进行value删除 和添加 未复现 怀疑是删除的过程触发了添加 放入了 空value

**Comment by L120820** [comment]
出现这个情况后 会使设备推流直接返回 “未找到可用的zml”

**Comment by 648540858** [comment]
明白，我测试下

**Comment by L120820** [comment]
> 明白，我测试下

您好请问怎么样了

**Comment by 648540858** [comment]
你的问题是必现吗。我复现不出来呀
