### ISSUE TITLE
SIP服务器ID和SIP用户名、SIP用户认证ID，一样的时候报错

### ISSUE THREAD

**Issue by 598652647** [648540858/wvp-GB28181-pro#639]
**描述错误**
海康摄像头设置国标，当SIP服务器ID和SIP用户名、SIP用户认证ID一样的时候，启动程序报错。页面不报错，摄像头可正常观看

**如何复现**
设置SIP服务器ID和SIP用户名、SIP用户认证ID一样相同参数

**截图**
![image](https://user-images.githubusercontent.com/59715712/195509863-59a70107-f91b-4904-a727-2942375177c5.png)
![image](https://user-images.githubusercontent.com/59715712/195510120-b0a946c7-a03f-42b2-8d1c-4ec8de4107cf.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) 
 - 2. 部署环境  centos7
 - 3. 端口开放情况：全开
 - 4. 是否是公网部署：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：海康
 - 7. 你做过哪些尝试：删除数据库重新添加

**Comment by 648540858** [comment]
你这不是自寻烦恼吗

**Comment by 648540858** [comment]
服务的10-13位一般为200,设备一般为132,你做成一样的本来就不符合国标呀，规范一点吧，不然你会遇到很多问题。
