### ISSUE TITLE
有线网络能点播成功,4G网络收流超时

### ISSUE THREAD

**Issue by muboyan** [648540858/wvp-GB28181-pro#648]
wvp映射了公网端口5060,用宽带时能正常拉流,用4G网络的时候却报收流超时。 ![image](https://user-images.githubusercontent.com/34343049/196909932-ae6f8db7-f71b-4fbf-a1cd-d6a723584d26.png)  
![26749fae8fcf45e913782e87b77ec79](https://user-images.githubusercontent.com/34343049/196910269-7c76c2f4-e8f8-4cc5-9238-710e2ae48df3.jpg)

**Comment by 648540858** [comment]
不符合提问规则
