### ISSUE TITLE
device_channel表有数据。device表无数据

### ISSUE THREAD

**Issue by zionzheng** [648540858/wvp-GB28181-pro#649]
**描述错误**
日志已经打印设备上线，device_channel表中有数据，device表中无数据

**如何复现**
使用最新版本，device_channel表有数据。但是device表是空的，前端无国标设备，日志打印出设备已经上线了。

**截图**
查询表数据
![图片](https://user-images.githubusercontent.com/30211090/197170312-0ed665c5-e073-4369-a062-8f811a721759.png)
打印日志，设备已经注册成功
![图片](https://user-images.githubusercontent.com/30211090/197170470-956ef2c4-12bf-4257-83e8-7863ce4e0d4c.png)

**Comment by 648540858** [comment]
不符合提问规则
