### ISSUE TITLE
wvp对接海康nvr时出现问题

### ISSUE THREAD

**Issue by jygyt** [648540858/wvp-GB28181-pro#65]
nvr设备发送sip/sdp的invite请求时，wvp无ack应答
nvr
<img width="1109" alt="截屏2021-03-11 10 55 56" src="https://user-images.githubusercontent.com/13568311/110728630-5d5c6000-8258-11eb-9176-043d0734b0aa.png">
直接链接摄像头
<img width="1162" alt="截屏2021-03-11 10 59 32" src="https://user-images.githubusercontent.com/13568311/110728970-deb3f280-8258-11eb-8894-eb79702f9ca4.png">

**Comment by jbztech** [comment]
你好，想问下nvr接入怎么玩？

**Comment by 648540858** [comment]
方便传一份pcap的转包文件吗
