### ISSUE TITLE
能否升级到fastjson2

### ISSUE THREAD

**Issue by AlphaWu** [648540858/wvp-GB28181-pro#651]
与wvp对接的代码使用的是fastjson2，无法解析fastjson格式的内容，wvp能不能也升级到fastjson2？谢谢！

**Comment by 648540858** [comment]
fastjson2 api有变化，目前还不能完全满足使用，还得摸索下，你可以修改的话，欢迎提PR。

**Comment by AlphaWu** [comment]
已提交PR，#662。
