### ISSUE TITLE
FFMPEG推流提示签权失败

### ISSUE THREAD

**Issue by angelbaal2022** [648540858/wvp-GB28181-pro#653]
FFMPEG推流提示签权失败。需要带什么参数吗？

**Comment by angelbaal2022** [comment]
ffmpeg -re -i /Users/angel/Desktop/1.mp4 -vcodec libx264 -acodec aac -f flv rtmp://192.168.88.102:1935/test/123"?sign=9c8e21a91f69edc6db1e1761dd0fe8a5" 增加参数后提示 INFO  c.genersoft.iot.vmp.media.zlm.ZLMHttpHookListener:239 - 推流鉴权失败： sign 无权限: callId=null. sign=9c8e21a91f69edc6db1e1761dd0fe8a5

**Comment by 648540858** [comment]
看wiki
