### ISSUE TITLE
无人观看自动断流，有概率出现未成功发送SIP BYE请求，导致设备无限推流

### ISSUE THREAD

**Issue by fymdchenwei** [648540858/wvp-GB28181-pro#654]
**描述错误**
WVP GB28181流媒体平台部署在公网，平台正常的推流和拉流服务正常。
运行一段时间后，在没有任何用户观看时，发现服务器带宽占用并未释放，
使用IFTOP监控服务器网卡，发现大量有NVR设备推流连接，这些连接会一直存在无法释放
在将WVP服务停止一段时间后所有推流连接断开。

**如何复现**
开启了auto_apply_play,播放器使用easyPlayer,使用HLS协议
使用Web端或移动端多次请求、关闭视频播放
大部分的请求在无人观看时会自动关闭，偶尔会出现拉流没有断开问题，且后端日志没有任何报错信息
**预期行为**
1.定时监测平台中异常的拉流信息，并断开。
2.怀疑在并发请求同一个点播时，没有同步锁处理，导致向设备发起了多次Invite请求，前面的事务会话被最后的一个覆盖，导致事务会话丢失并且没有向设备发送Bye请求。

**截图**
如下图，推流连接一直存在，且无法释放
![image](https://user-images.githubusercontent.com/5651742/198870033-7a535c1a-c917-4f39-8dcf-a7975229f5de.png)

**环境信息:**
 - 1. 部署方式 编译wvp-pro + zlm都是编译部署，WVP版本：2.6.5， ZLMediaKit:最新版本
 - 2. 部署环境：centos7.8
 - 3. 公网部署
 - 4. 使用https
 - 5. 海康NVR，大华NVR均支持GB28181-2016

**Comment by realbillwong** [comment]
请问这个问题修复了吗？我们这里也会有这种情况发生

**Comment by wEnchanters** [comment]
你是通过无线网连接的吗
