### ISSUE TITLE
公网无法正常收到摄像头心跳

### ISSUE THREAD

**Issue by luo1227135067** [648540858/wvp-GB28181-pro#657]
**描述错误**
服务器端防火墙已经全部关闭, 试过两台服务器都部署同一套,  其中一个服务器, 摄像头端到服务器端, 心跳包的Body内容消失了, 现在摄像头是注册到公网上, 注册成功后, 三次心跳失败,又重新注册........ 
另一个服务器就没这种情况, 还有就是我本都局域网测试一切正常, 以前也试过别的服务器, 也遇到过这种情况, 不知道是什么原因

**如何复现**
看服务器来的, 现在是腾讯云领取的一个月免费的, 百分百复现 https://cloud.tencent.com/act/free?from=17301
![image](https://user-images.githubusercontent.com/47409459/199630323-3bd314aa-5d4a-40a3-9ea8-8599661fc312.png)

**预期行为**
body内容: <?xml version="1.0" encoding="GB2312" standalone="yes" ?><Notify><CmdType>Keepalive</CmdType><SN>40</SN><DeviceID>34020000001320000001</DeviceID><Status>OK</Status></Notify> 这段到服务器端就不见了
**截图**
![image](https://user-images.githubusercontent.com/47409459/199631013-039207cb-250c-4746-babf-acffb9164997.png)

**环境信息:**
 - 1. 部署方式 
 - wvp 直接在centos7上 java -jar wvp.jar
 
 - 2. 部署环境 
 - centos7

 - 3. 端口开放情况
 - 防火墙已经全部关闭

 - 4. 是否是公网部署
 - 是

 - 5. 是否使用https
 - 否

 - 6. 方便的话提供下使用的设备品牌或平台
 - 大华

 - 7. 你做过哪些尝试
 - 目前解决办法就是,服务端只要是massage, 不管有没有body, 正常响应心跳......

我抓了摄像头端和服务器端的包, 难道服务器还自带xss之类的过滤 ? 为啥获取设备信息和通道信息又能正常发送

[设备端和服务端抓包.zip](https://github.com/648540858/wvp-GB28181-pro/files/9925086/default.zip)

**Comment by 648540858** [comment]
不清楚你的问题，理论上能发送注册，就能发送心跳，除非设备没发。
