### ISSUE TITLE
gps定位上传失败后永不执行Notify的后续请求

### ISSUE THREAD

**Issue by 1281152329** [648540858/wvp-GB28181-pro#659]
**描述错误**
![image](https://user-images.githubusercontent.com/32828202/199728226-dfa433a2-fb76-487e-850e-60c2cae0bf2b.png)
如图所示 在某次异常经纬度上传为null的时候，报错捕获未上报导致taskQueueHandlerRun一直为true，后续再有Notify请求不生效

![image](https://user-images.githubusercontent.com/32828202/199728799-922f8c46-0ca2-4b36-ba71-299ea3f30746.png)

**如何复现**
mobilePosition notify请求下经纬度为null时

**预期行为**

taskQueueHandlerRun永远为true
**截图**

**环境信息:**
 - 1. wvp-prp + zlm都是编译部署/
 - 2. 部署环境 macos
 - 3. 端口开放
 - 4. 非公网部署
 - 5. 使用http
 - 6. 无
 - 7. 添加finally
 finally {
    taskQueueHandlerRun = false;
}

**Comment by 648540858** [comment]
已经修改了，可以测试了
