### ISSUE TITLE
部署到云服务器无法点播，刷新

### ISSUE THREAD

**Issue by zhangxun05** [648540858/wvp-GB28181-pro#66]
在本地，包括公司网都能实现点播， 但部署到云服务上点播出现timeout，zlm无法给出回应，试了论坛的几种方法配置都不行，首先确定防火墙开的，端口试开的。 不知道还有什么原因导致不能点播
!
![image](https://user-images.githubusercontent.com/33276715/110766075-c4493b80-828f-11eb-9ec0-c9070ade6bc1.png)

**Comment by 648540858** [comment]
看下你的配置
