### ISSUE TITLE
前后端分离部署,通过nginx代理,nginx配置文件具体怎么配置

### ISSUE THREAD

**Issue by zph-mi** [648540858/wvp-GB28181-pro#665]
**描述错误**
nginx代理前端,访问失败

**如何复现**
server
{
    listen 80;
    server_name 192.168.175.120;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/static;

    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #SSL-END

    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END

    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-00.conf;
    #PHP-INFO-END

    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/192.168.175.120.conf;
    #REWRITE-END

    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }

    #禁止在证书验证目录放入敏感文件
    if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" ) {
        return 403;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log /dev/null;
        access_log /dev/null;
    }

    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log /dev/null;
        access_log /dev/null;
    }
    
    location /debug{
      proxy_pass http://192.168.175.120:8880;
    }
    
    access_log  /www/wwwlogs/192.168.175.120.log;
    error_log  /www/wwwlogs/192.168.175.120.error.log;
}

**预期行为**
可以提供一下nginx配置信息吗

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro 前后端分离 前端打包,nginx代理  后端jar包部署     zlm编译部署
 - 2. 部署环境  centos7
 - 3. 端口开放情况   防火墙关闭
 - 4. 是否是公网部署   否
 - 5. 是否使用https     否

**Comment by 648540858** [comment]
不属于wvp的研究范围呀，自己研究下吧，我也没配置过，

**Comment by ShanMuqaq** [comment]
解决了吗，可以使用nginx转发吗
