### ISSUE TITLE
media.rtp.enable=false时ssrc无法重用

### ISSUE THREAD

**Issue by nashiracn** [648540858/wvp-GB28181-pro#667]
**描述错误**
配置为：media.rtp.enable=false
每次重启后一段时间获取播放地址的接口就会包http 500错误，日志中报错信息类似：

`
11月 10 21:49:39 wenjiang-zvp-cdn java[1381604]: java.lang.NumberFormatException: For input string: "000001BC"
11月 10 21:49:39 wenjiang-zvp-cdn java[1381604]:         at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
11月 10 21:49:39 wenjiang-zvp-cdn java[1381604]:         at java.base/java.lang.Integer.parseInt(Integer.java:652)
11月 10 21:49:39 wenjiang-zvp-cdn java[1381604]:         at java.base/java.lang.Integer.parseInt(Integer.java:770)
11月 10 21:49:39 wenjiang-zvp-cdn java[1381604]:         at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.openRTPServer(MediaServerServiceImpl.java:153)
11月 10 21:49:39 wenjiang-zvp-cdn java[1381604]:         at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.openRTPServer(MediaServerServiceImpl.java:168)
11月 10 21:49:39 wenjiang-zvp-cdn java[1381604]:         at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.openRTPServer(MediaServerServiceImpl.java:125)
11月 10 21:49:39 wenjiang-zvp-cdn java[1381604]:         at com.genersoft.iot.vmp.service.impl.PlayServiceImpl.play(PlayServiceImpl.java:213)
11月 10 21:49:39 wenjiang-zvp-cdn java[1381604]:         at com.genersoft.iot.vmp.vmanager.gb28181.play.PlayController.play(PlayController.java:91)
11月 10 21:49:39 wenjiang-zvp-cdn java[1381604]:         at jdk.internal.reflect.GeneratedMethodAccessor377.invoke(Unknown Source)
`

代码分析：
1.  openRTPServer()在配置media.rtp.enable=false时streamId是16进制的ssrc
2. closeRTPServer()直接将16进制的streamId当做ssrc释放，16进制的streamId进入SsrcConfig.notUsed之后下次分配到这个ssrc时就会报错

<img width="810" alt="image" src="https://user-images.githubusercontent.com/15014009/201114764-d892a7a0-2b4d-4fc0-8b50-a6103db4d58d.png">
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/15014009/201115136-a54fb35e-6646-4cff-af00-723e7408e8c9.png">

**如何复现**
服务启动后多运行一段时间就会复现

**预期行为**
服务可以长期稳定运行

**截图**

**环境信息:**
 - 1. 部署方式：  wvp-prp + zlm都是编译部署
 - 2. 部署环境：Debian 11
 - 3. 端口开放情况： tcp:28181,28200,5060；udp:5060,28200
 - 4. 是否是公网部署：是
 - 5. 是否使用https：是
 - 6. 方便的话提供下使用的设备品牌或平台：海康
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
已修复
