### ISSUE TITLE
可配置无人观看时不关闭推流管道

### ISSUE THREAD

**Issue by zionzheng** [648540858/wvp-GB28181-pro#668]
向zlm一段推流后,如果触发无人观看事件,推流管道会关闭,导致推流失败.可否新增配置项,类似拉流,即使无人观看也不关闭.而且默认应该不关闭管道,推流方如果sign正确,就应该有主动权.

**Comment by Gozly** [comment]
stream-none-reader-delay-ms: -1    当为-1 时为永不关流

**Comment by 648540858** [comment]
stream-on-demand 配置为false
