### ISSUE TITLE
级联录像记录

### ISSUE THREAD

**Issue by AtomweiGithub** [648540858/wvp-GB28181-pro#672]
**描述错误**
wvp作为下级平台，上级请求录像记录时，请求多个通道后，Map<String, RecordEndEventHandler> handlerMap中会有多个元素，而收到记录后，就会重复回调向上级发送录像记录，且该map没有清空逻辑，易导致内存泄露。

**Comment by 648540858** [comment]
好的，我看看

**Comment by 648540858** [comment]
已修复
