### ISSUE TITLE
视频画面闪动，webRTC不能播放

### ISSUE THREAD

**Issue by zzgghhzzgghh** [648540858/wvp-GB28181-pro#674]
**描述错误**
描述下您遇到的问题
jessibuca视频播放画面闪动，webRTC不能播放

**预期行为**
视频播放画面平滑，webRTC能播放

**环境信息:**
 - 1. 部署方式 编译wvp-GB28181-pro + zlm都是编译部署/
 - 2. 部署环境  ubuntu
 - 3. 端口开放情况  开放
 - 4. 是否是公网部署  否
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台   海康IPC
 - 7. 你做过哪些尝试

**Comment by Gozly** [comment]
降低视频图像质量（海康的配置视频页面），更换浏览器重试
