### ISSUE TITLE
[技术咨询] 海康安防平台级联到WVP，添加平台成功后无法共享通道

### ISSUE THREAD

**Issue by partoftom2** [648540858/wvp-GB28181-pro#675]
**描述错误**
海康安防平台级联到WVP，添加平台成功后，平台能正常注册，但是无法共享通道（无法看到共享上来的通道）

**如何复现**

**预期行为**
海康综合安防管理平台联到WVP，添加平台成功后，预期能将海康安防平台已经接入的摄像头，共享到WVP，但是WVP一直发现不了通道

**截图**
WVP接入海康综合安防管理平台，但是没有任何通道的截图：
![image](https://user-images.githubusercontent.com/52817660/202639102-ded3ccb6-a563-4f27-8a3b-168f66960de0.png)

海康综合安防管理平台的截图：
![image](https://user-images.githubusercontent.com/52817660/202639123-3b62d62e-f9ac-47f5-85ec-af649937cef0.png)

**环境信息:**
 - 1. 部署方式： wvp-prp + zlm都是编译部署
 - 2. 部署环境：centos 7.6
 - 3. 端口开放情况：开放
 - 4. 是否是公网部署：是
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：摄像头接入了海康的NVR，海康的NVR通过Ehome协议接入到了海康综合安防管理平台
 - 7. 你做过哪些尝试
 - 咨询海康的支撑人员，他们不太了解

**Comment by partoftom2** [comment]
海康安防平台注册成功后抓包的截图:
![image](https://user-images.githubusercontent.com/52817660/202639280-0634b859-4a6a-47e2-af4e-f8b244c141d0.png)

海康的技术支撑人员的回复，怀疑通道没有共享到WVP的原因如下：
![image](https://user-images.githubusercontent.com/52817660/202639368-69a5bb88-4b9b-496a-95ed-81600cbc4577.png)

**Comment by partoftom2** [comment]
WVP级联日志：
![image](https://user-images.githubusercontent.com/52817660/202640904-357a2306-92b6-4d30-9b1d-7dfa028d473c.png)

**Comment by partoftom2** [comment]
在WVP中，对于下级接入的海康安防平台，点击通道后，日志报错，日志截图：
![image](https://user-images.githubusercontent.com/52817660/202641477-11c312bc-94e3-4a49-b08d-b18f08e6f1cc.png)

点击通道的截图：
![image](https://user-images.githubusercontent.com/52817660/202641645-3a0b6ef8-4cb6-4a35-b976-c543f2063b5e.png)

**Comment by partoftom2** [comment]
同步接口的具体报错信息：
![image](https://user-images.githubusercontent.com/52817660/202652061-6f3825b1-82ab-4a04-b906-7d52d7129a0a.png)

**Comment by Little-White-Ant** [comment]
你好！请问你的问题解决了吗？

**Comment by Mr-Zhang-Object** [comment]
![image](https://user-images.githubusercontent.com/62411354/217995820-5b9f218e-c446-4822-a2de-db50b8f8d575.png)
你好，请问当时您这个问题如何解决的？我现在也遇到这个问题了，但没有任何异常日志，无从下手！！

**Comment by 648540858** [comment]
更新代码测试下，最近优化了一下，海康平台对国标编号要求比较严格，参考国标文档设置好国标编号，主要是11-13位的类型。

**Comment by 648540858** [comment]
还有一个情况要抓包才可以看到，发送消息中消息头content-length 为0，导致无法获取消息内容，请自行联系海康技术解决吧
