### ISSUE TITLE
ptz坐标获取与设置

### ISSUE THREAD

**Issue by iclearwater** [648540858/wvp-GB28181-pro#68]
想问下 国标支持获取球机的PTZ坐标吗，还有是否可以直接设置一个ptz坐标？项目支持吗

**Comment by 648540858** [comment]
支持预置位设置，你可以通过添加预置位实现

**Comment by iclearwater** [comment]
> 支持预先位置设置，您可以通过添加预先位置实现

这里预备用大华、海康私有协议实现，还有问下大佬有没有现成的摄像机ptz坐标与屏幕坐标和经纬度坐标的转换算法代码

**Comment by 648540858** [comment]
屏幕坐标和经纬度坐标的转换看你使用什么gis平台，一般gis引擎自带的，ptz坐标和这个没啥关系吧，你还要在gis显示摄像头
的方向？

**Comment by iclearwater** [comment]
> 屏幕坐标和经纬度坐标的转换看你使用什么gis平台，一般gis引擎自带的，ptz坐标和这个没啥关系吧，你还要在gis显示摄像头
> 的方向？

好的
