### ISSUE TITLE
添加国标级联上级平台，信令传输UDP时，添加失败

### ISSUE THREAD

**Issue by eanfs** [648540858/wvp-GB28181-pro#682]
**描述错误**
添加国标级联上级平台，信令传输UDP时，日志提示
```
2022-11-23 18:19:55.704 ERROR 8 --- [io-18080-exec-7] c.g.i.v.v.g.platform.PlatformController  : [命令发送失败] 国标级联 注册: Could not create a message channel for 192.168.25.198:5060/UDP
```
**如何复现**
添加国标级联平台

**预期行为**
添加成功

**截图**
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/5432110/203523765-ea9d9618-db6b-406d-8996-be03f66276e4.png">
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/5432110/203523863-9c9a8000-9867-4409-9f7c-8cffb6f40b00.png">

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) 
 - 2. 部署环境 / centos ...

**Comment by 648540858** [comment]
确定你上级端口是通的

**Comment by eanfs** [comment]
端口是通的

**Comment by 648540858** [comment]
那就在对方平台抓包，看看消息有没发过去
