### ISSUE TITLE
Docker版SQLite数据库和MySQL版不一致。

### ISSUE THREAD

**Issue by Azreulo** [648540858/wvp-GB28181-pro#683]
部署Docker版使用外部MySQL数据库，发现Docker版SQLite数据库和编译下载使用sql文件导入MySQL数据库不一致。

Docker版使用内置SQLite时运行正常，但因实际需求，需使用外部MySQL数据库。

使用Navicat对比发现，两个库结构不一致，使用数据传输功能转换数据库失败。
请教如何解决，或者能否提供和SQLite一样的数据结构sql文件吗？
![DB](https://user-images.githubusercontent.com/21158437/203531470-17d5be9d-e986-4e47-9ec2-92ce3e11e71c.jpg)

**Comment by 648540858** [comment]
目前版本不再支持sqlite
