### ISSUE TITLE
设备集体离线

### ISSUE THREAD

**Issue by tainyalangzibei** [648540858/wvp-GB28181-pro#687]
**描述错误**
描述下您遇到的问题
运行20小时左右，设备集体离线 wvp不回复任何消息 所有线程进入空闲状态
**如何复现**
有明确复现步骤的问题会很容易被解决
一千台设备发送心跳和注册
**预期行为**
清晰简洁的描述您期望发生的事情
线程正常运行
**截图**
![image](https://user-images.githubusercontent.com/66810016/204171024-a0cafb0a-9669-44a0-a366-782a4141d5e1.png)
![776371ef48cd6c563da7f5c76bc5190](https://user-images.githubusercontent.com/66810016/204171038-ee908bb9-096c-4722-9312-fa74fe5e8a08.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 编译部署
 - 2. 部署环境 windows / ubuntu/ centos ...
 - ubuntu
 - 3. 端口开放情况
 - 全部开放
 - 4. 是否是公网部署
 - 是
 - 5. 是否使用https
 - 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 重启服务后恢复正常 但每次都是运行20小时左右 全部离线

**Comment by 648540858** [comment]
更新代码测试下，今天优化了一下。
