### ISSUE TITLE
公网IP ，端口映射出虚拟服务器

### ISSUE THREAD

**Issue by hudeyi100** [648540858/wvp-GB28181-pro#688]
在内网机器A部署 WVPPro+ZLMediaKit ，通过端口映射（目前开启NAT DMZ服务 ，方便测试，不需要配置端口映射），指向部署的局域网机器A。视频流超时，请教如何配置
下图是虚拟服务器配置截图
![image](https://user-images.githubusercontent.com/3301365/204500241-c0a404c5-cdca-4295-8a47-65861b5ae6c2.png)

**Comment by AlphaWu** [comment]
机器A的防火墙是否允许相关端口。

**Comment by hudeyi100** [comment]
问题已解决
