### ISSUE TITLE
设备串流

### ISSUE THREAD

**Issue by bruce920701** [648540858/wvp-GB28181-pro#69]
国标设别长时间注册上运行时，经常出现串流，比如a设备的画面会变成和b画面的一样，重启a，b设备串流会好

**Comment by 648540858** [comment]
使用多端口了吗，可以使用多端口试试，可能是ssrc重复了

**Comment by 648540858** [comment]
我先关闭了，有问题你再打开

**Comment by bruce920701** [comment]
您好，
能帮我看下这样配置有没有问题吗？




spring:
    # [不需要改]
    application:
        name: iot-vmp-vmanager
        # [不需要改] 影子数据存储方式，支持redis、jdbc,暂不支持mysql,
        database: db 
        # [不需要改] 通信方式，支持kafka、http
        communicate: http
    # REDIS数据库配置
    redis:
        # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
        host: 127.0.0.1
        # [必须修改] 端口号
        port: 6379
        # [可选] 数据库 DB
        database: 6
        # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        password:
        # [可选] 超时时间
        timeout: 10000
    # [不可用] jdbc数据库配置, 暂不支持
    datasource:
        #        name: eiot
        #        url: jdbc:mysql://127.0.0.1:3306/eiot?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true
        #        username:
        #        password:
        #        type: com.alibaba.druid.pool.DruidDataSource
        #        driver-class-name: com.mysql.jdbc.Driver
        name: eiot
        url: jdbc:sqlite::resource:wvp.sqlite
        username:
        password:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name:  org.sqlite.JDBC
        max-active: 1
        min-idle: 1


# [可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 10028


# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP, 必须是网卡上的IP
    ip: 172.18.0.5
    # [可选] 28181服务监听的端口
    port: 10029
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 3402000000
    # [可选]
    id: 34020000002000000001
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码
    password: 12345678


# 登陆的用户名密码
auth:
    # [可选] 用户名
    username: admin
    # [可选] 密码, 默认为admin
    password: 21232f297a57a5a743894a0e4a801fc3


#zlm服务器配置
media:
    # [必须修改] zlm服务器的内网IP
    ip: 127.0.0.1
    # [可选] zlm服务器的公网IP, 内网部署置空即可
    wanIp: 111.23.126.16 
    # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip
    hookIp: 
    # [必须修改] zlm服务器的http.port
    port: 10027
    # [可选] 是否自动配置ZLM, 如果希望手动配置ZLM, 可以设为false, 不建议新接触的用户修改
    autoConfig: true 
    # [可选] zlm服务器的hook.admin_params=secret
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc 
    # [可选] zlm服务器的general.streamNoneReaderDelayMS
    streamNoneReaderDelayMS:  600000  # 无人观看多久自动关闭流, -1表示永不自动关闭,即 关闭按需拉流
    # [可选] 自动点播， 使用固定流地址进行播放时，如果未点播则自动进行点播, 需要rtp.enable=true
    autoApplyPlay: true
    # [可选] 部分设备需要扩展SDP，需要打开此设置
    seniorSdp: false
    # 启用udp多端口模式, 详细解释参考: https://github.com/xia-chu/ZLMediaKit/wiki/GB28181%E6%8E%A8%E6%B5%81 下的高阶使用
    rtp:
        # [可选] 是否启用udp多端口模式, 开启后会在udpPortRange范围内选择端口用于媒体流传输
        enable: true
        # [可选] 在此范围内选择端口用于媒体流传输, 不只是udp, 使用TCP被动传输模式时,也是从这个范围内选择端口
        udpPortRange: 20400,20700 # 端口范围


# [可选] 日志配置, 一般不需要改
logging:
    file:
        name: logs/wvp.log
        max-history: 30
        max-size: 10MB
        total-size-cap: 300MB
    level:
        com:
            genersoft:
                iot: debug


在 2021年4月1日 ***@***.***> 写道：


Closed #69.
