### ISSUE TITLE
CentOS安装服务，服务启动失败，手动运行成功。求教？

### ISSUE THREAD

**Issue by Azreulo** [648540858/wvp-GB28181-pro#693]
为了权限最小化，添加了一个独立的用户，su切换到此用户，运行正常，但是把命令写成服务运行，却一直失败。
服务文件：

[Unit]
Description=wvp-GB28181-pro Service
After=network.target
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/bin/java -jar /opt/wvp-GB28181-pro/wvp-pro-*.jar --spring.config.location=/opt/wvp-GB28181-pro/application.yml &
ExecReload=/usr/bin/kill -s HUP $MAINPID
ExecStop=/usr/bin/kill -9 $(ps -ef |grep wvp-pro|gawk '$0 !~/grep/{print $2}')
User=wvp
Group=wvp

[Install]
WantedBy=multi-user.target

报错信息：
12月 01 20:30:38 CentOS.ENDLESS systemd[1]: [/etc/systemd/system/wvp.service:10] Trailing garbage, ignoring.
12月 01 20:30:45 CentOS.ENDLESS systemd[1]: Started wvp-GB28181-pro Service.
12月 01 20:30:45 CentOS.ENDLESS systemd[1]: wvp.service: main process exited, code=exited, status=1/FAILURE
12月 01 20:30:45 CentOS.ENDLESS systemd[1]: Unit wvp.service entered failed state.
12月 01 20:30:45 CentOS.ENDLESS systemd[1]: wvp.service failed.
12月 01 20:33:01 CentOS.ENDLESS systemd[1]: [/etc/systemd/system/wvp.service:10] Trailing garbage, ignoring.
12月 01 20:33:06 CentOS.ENDLESS systemd[1]: [/etc/systemd/system/wvp.service:10] Trailing garbage, ignoring.
12月 01 20:33:14 CentOS.ENDLESS systemd[1]: Started wvp-GB28181-pro Service.
12月 01 20:33:14 CentOS.ENDLESS systemd[1]: wvp.service: main process exited, code=exited, status=1/FAILURE
12月 01 20:33:14 CentOS.ENDLESS systemd[1]: Unit wvp.service entered failed state.
12月 01 20:33:14 CentOS.ENDLESS systemd[1]: wvp.service failed.

但是切换到su切换到wvp用户，运行：
/usr/bin/java -jar /opt/wvp-GB28181-pro/wvp-pro-*.jar --spring.config.location=/opt/wvp-GB28181-pro/application.yml &
又能正常运行，求指点。

**Comment by 648540858** [comment]
从你使用服务的方式找原因吧，这个我也没研究过。
