### ISSUE TITLE
谷歌浏览器、Edge浏览器播放一会后黑屏，火狐浏览器不会黑屏，但延时较大

### ISSUE THREAD

**Issue by August1023** [648540858/wvp-GB28181-pro#694]
**描述错误**
我在使用wvp项目，里面的播放器是jessibuca。当我用谷歌浏览器、Edge浏览器播放视频监控一会后会黑屏，浏览器Console日志：Uncaught DOMException: Failed to execute 'transferToImageBitmap' on 'OffscreenCanvas': ImageBitmap construction failed。火狐浏览器不会黑屏但延迟会越来越大。

**如何复现**
分屏监控、实时播放、录像播放，播放一会后就会出现该问题。同时播放数大出现的更快。

**预期行为**
播放视频不会出现黑屏问题。

**截图**
<img width="960" alt="2cfc4e508b143ad48b87353d1fbcc54" src="https://user-images.githubusercontent.com/45287355/205209486-b91eca50-b2f3-45d5-ab12-757480601951.png">

**环境信息:**
 - 1. 部署方式 
 - wvp-pro本地运行/wvp-pro编译部署 +  zlm编译部署  
 - 2. 部署环境  
 - wvp-pro在windows10， zlm在Centos7(虚拟机)
 - 3. 端口开放情况
 - 防火墙已关闭
 - 4. 是否是公网部署
 - 否
 - 5. 是否使用https
 - 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - DH
 - 7. 你做过哪些尝试
 - 尝试过谷歌，Edge和火狐浏览器

**Comment by xiaohuiL** [comment]
@August1023 请问你的问题解决了吗？我也遇到了，wvp平台和摄像头本身平台画面不同步问题，延时很大
