### ISSUE TITLE
[个人需求]设备上线后自动执行播放操作

### ISSUE THREAD

**Issue by AlphaWu** [648540858/wvp-GB28181-pro#697]
在src/main/java/com/genersoft/iot/vmp/service/impl/DeviceServiceImpl.java的online方法，增加下面的代码：

MediaServerItem newMediaServerItem = playService.getNewMediaServerItem(device);
// 在所有通道开启自动播放（录制）
List<SsrcTransaction> ssrcTransactions = streamSession.getSsrcTransactionForAll(device.getDeviceId(), null, null, null);
if (ssrcTransactions != null && ssrcTransactions.size() > 0) {
    for (SsrcTransaction ssrcTransaction : ssrcTransactions) {
        playService.play(newMediaServerItem, device.getDeviceId(), ssrcTransaction.getChannelId(), null, null, null);
    }
}

但是编译提示错误，无法注册IPlayService playService。

**Comment by 648540858** [comment]
自救修改的代码不做讨论，自行解决吧
