### ISSUE TITLE
新设备首次上线后，无设备名称，厂商等信息

### ISSUE THREAD

**Issue by 1994shl** [648540858/wvp-GB28181-pro#699]
**描述错误**
       大佬您好，这次为了使用“无人观看自动断流”功能而升级wvp版本，我发现设备首次上线后设备表中（Device）设备名称、厂商等信息未同步，通道表看着都正常（Device_channel），升级前后使用的都是同一批设备，升级时mysql和redis的数据确认都删掉了。

       恳请回复，祝大佬身体健康，生活愉快！

**预期行为**
设备上线后，设备表中（Device）的设备名称，厂商等信息也能正常同步。

**截图**
升级前版本
![image](https://user-images.githubusercontent.com/54757504/206074394-f4dfe4ed-5515-46eb-bec9-a6c6a5baab1e.png)
升级后版本
![image](https://user-images.githubusercontent.com/54757504/206074468-4411a3d7-1569-458c-8495-1d502233a965.png)
设备表截图：
![image](https://user-images.githubusercontent.com/54757504/206074550-77592932-1444-4d35-8d4f-b752d4b44837.png)
通道表截图：
![image](https://user-images.githubusercontent.com/54757504/206074625-998674f4-d90d-4f03-81a7-8a65e8b2d7f9.png)

**Comment by 1994shl** [comment]
![image](https://user-images.githubusercontent.com/54757504/207804446-ce27d627-a14e-4b06-953b-376730195980.png)
大佬，还是同一批设备，相关信息都删掉了，redis中也删掉了，还是没有设备名称等相关信息。（图片是某一次设备上线日志的截图，确定是首次上线注册）

**Comment by 1994shl** [comment]
![image](https://user-images.githubusercontent.com/54757504/207804930-1441a412-c611-4f22-9bcb-5b742cf51da5.png)
现象还是一致，device表没设备名称相关数据，设备通道表正常，大佬，是不是我哪里没配置好，祝您生活愉快！

**Comment by 648540858** [comment]
如果第一次上线都没有,可能是设备不支持设备信息查询。

**Comment by 1994shl** [comment]
wvp版本没升级之前，还是这一批设备，是可以查到设备信息的，设备名等都是正常显示的，就比较奇怪了。大佬，是不是设备端也有啥配置要更新。
        祝大佬新年快乐，阖家幸福！

**Comment by 648540858** [comment]
新年快乐，抓个包看看有没有发送查询消息，清理了数据库和redis再操作

**Comment by 1994shl** [comment]
感谢大佬指导回复，我试试。 手动笑脸
