### ISSUE TITLE
对接海康nvr 点播视频SDP问题

### ISSUE THREAD

**Issue by Alec-DSheng** [648540858/wvp-GB28181-pro#7]
在对接海康nvr过程中，点播视频时部分视频不支持
在SDP中添加以下数据可正常播放
------------------------

content.append("a=fmtp:126 profile-level-id=42e01e\r\n")
					.append("a=rtpmap:126 H264/90000\r\n")
					.append("a=rtpmap:125 H264S/90000\r\n")
					.append("a=fmtp:125 profile-level-id=42e01e\r\n")
					.append("a=rtpmap:99 MP4V-ES/90000\r\n")
					.append("a=fmtp:99 profile-level-id=3\r\n");

**Comment by 648540858** [comment]
好的,我这边测试下

**Comment by 648540858** [comment]
已添加你测试下
