### ISSUE TITLE
mysql.sql导入报错

### ISSUE THREAD

**Issue by xiguapengpeng** [648540858/wvp-GB28181-pro#701]
**描述错误**
mysql.sql导入报错，脚本文件逻辑混乱

**如何复现**
使用Navicat导入sql，异常报错

**预期行为**
期望成功导入sql

**截图**
![导入报错](https://user-images.githubusercontent.com/25153667/206343168-07e2c761-1bb0-4e46-892f-3a23532aaa4b.png)
![微信截图_20221208103801](https://user-images.githubusercontent.com/25153667/206343333-c04c0c26-de27-433e-9ab6-5e791df795d7.png)
![微信截图_20221208103716](https://user-images.githubusercontent.com/25153667/206343345-5deb636f-aedd-40e8-a257-f5c5d59a98cb.png)

**环境信息:**
 - 1. windows本地调试

**Comment by BussanQ** [comment]
> 脚本都是使用mysql官方工具导出的，如果报错，确认你的mysql版本使用正确。

脚本确实是错的，上面同学图上标的很清楚，调整一下之后导入就正常了

**Comment by xiguapengpeng** [comment]
> 脚本都是使用mysql官方工具导出的，如果报错，确认你的mysql版本使用正确。

无关版本的，您可以阅读一下脚本，是存在问题的，后面我自己调整了就可以导入了

**Comment by testing2007** [comment]
mysql.sql 文件 platform_gb_channel, platform_gb_stream 表 DROP TABLE IF EXISTS 对应的写错了， 同时同  ENGINE=InnoDB 行加上ROW_FORMAT=DYNAMIC 导入sql语句就成功了
