### ISSUE TITLE
点播返回地址异常

### ISSUE THREAD

**Issue by mayongbin** [648540858/wvp-GB28181-pro#702]
**描述错误**
使用gb28181接入一个IPC，点播的时候异常查看地址之后，ip地址被换成了我的服务器的名字，这个是在哪个配置来控制吗？我已经仔细查看过了配置文件的配置，试了一些，还是没有解决

**如何复现**
注册gb28181摄像头，点击播放

**预期行为**
地址内容返回的是IP不是我的服务器名字

![207088521-9b0b1273-0c26-4af3-b841-426c5dbace27](https://user-images.githubusercontent.com/19423532/207231846-99a7368c-b7f2-4ad0-9583-c13bf1b8d692.png)

**环境信息:**
 - 1. 部署方式  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu20.4
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 支持https

**Comment by MrHCM** [comment]
我也遇到同样问题，查看redis配置数据是正常的
![image](https://user-images.githubusercontent.com/43276144/209034733-74d65e13-46f4-4d35-a159-85c8c340f445.png)
![image](https://user-images.githubusercontent.com/43276144/209034811-ebc53d8e-a5b3-44db-b069-47c89dd9bde5.png)

1. 编译wvp-pro/ wvp-prp + zlm都是编译部分
2. 部分环境 ubuntu server 22.04

**Comment by mayongbin** [comment]
> 

是配置文件决定的。将yml配置文件的这个属性use-source-ip-as-stream-ip 改为false

**Comment by MrHCM** [comment]
> > 
> 
> 是配置文件决定的。将yml配置文件的这个属性use-source-ip-as-stream-ip改为false

我改了，没有起作用啊

**Comment by MrHCM** [comment]
> 

感谢啦，可以的

**Comment by mayongbin** [comment]
> > 
> 
> 感谢啦，可以的

没事儿，我是自己一个配置一个配置试验出来的 哈哈
