### ISSUE TITLE
wvp级联海康平台视频点播问题

### ISSUE THREAD

**Issue by du15160768077** [648540858/wvp-GB28181-pro#708]
**描述错误**
wvp作为下级级联到上级海康iSC平台，wvp国标设备的流推送过去,上级可以正常点播，拉流代理的
流下级可以正常播放，推送给上级海康平台，上级无法播放，上级点播报错：0x02201034【解析请求报文错误】,上级点播时，抓包发现sip交互时，下级平台回一个媒体流的端口为0的sdp报文给上级，被上级拒绝，回了一个bye的报文给下级，没有建立起连接，zlm日志暂未发现异常

**预期行为**
拉流代理的流推送给上级海康平台，上级可以正常播放

**截图**
![8af32ccff77f0b2abab41ee5ab5e284](https://user-images.githubusercontent.com/121075969/208594434-e8dfa30e-4e6e-4a03-b069-f78defba96de.png)

**环境信息:**
 - 1. 部署方式 wvp-pro jar, zlm编译部署
 - 2. 部署环境  centos7.6
 - 3. 端口开放情况: 部分指定端口开放
 - 4. 是否是公网部署:  否，内网，上下级平台的服务器在同一个云服务器下，分别都有一个内部ip和一个对外的ip
 - 5. 是否使用https: 否
 - 6设备：海康设备，wvp，海康ISC平台

**Comment by du15160768077** [comment]
问题已解决

**Comment by liwenyan703** [comment]
怎么解决的
