### ISSUE TITLE
设备录像不能回放。

### ISSUE THREAD

**Issue by leebaozhong** [648540858/wvp-GB28181-pro#709]
**描述错误**
描述下您遇到的问题
可显示设备sd卡录像文件清单，点击回放，不能显示图像。
**如何复现**
有明确复现步骤的问题会很容易被解决
跟踪代码，发现获取url地址不对。修改后可以回放。devicePlayer.vue。452行，            if (location.protocol === "https:") {
              this.videoUrl = this.streamInfo[this.player[this.activePlayer][1]].url
            }else {
              this.videoUrl = this.streamInfo[this.player[this.activePlayer][0]].url
            }
这样修改后，点播（直播）不正常。
**预期行为**
清晰简洁的描述您期望发生的事情
点播和回放都正常。
**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
抓包看看

**Comment by 648540858** [comment]
更新代码试试，最近刚修复了这个。
