### ISSUE TITLE
回放自动播放结束后  没有关闭回放流

### ISSUE THREAD

**Issue by github1359930721** [648540858/wvp-GB28181-pro#712]
**描述错误**
点一个设备回放后  让回放自动播完 然后触发无人观看   在流注销中 好像没有把对应的这个回放流给关闭

**截图**

**环境信息:**
 - 1. 部署方式  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境  centos
 - 3. 端口开放情况 内网测试 
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康摄像头
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
你是怎么确认流没有关闭的

**Comment by github1359930721** [comment]
我这个摄像头回放流只能存在一路   wvp播放一个回放片段之后   在摄像头上看回放 看不了

**Comment by github1359930721** [comment]
> 你是怎么确认流没有关闭的

我这个摄像头回放流只能存在一路 wvp播放一个回放片段之后 在摄像头上看回放 看不了

**Comment by 648540858** [comment]
抓包看看设备有没有发回放结束的通知，如果没有就不会发送bye

**Comment by github1359930721** [comment]
> 抓包看看设备有没有发回放结束的通知，如果没有就不会发送bye
单个回放片段结束 然后触发无人观看之后  摄像头后台是不可以看回放的 但是 wvp前端的话 是可以看另外的回放片段

**Comment by github1359930721** [comment]
> 抓包看看设备有没有发回放结束的通知，如果没有就不会发送bye

单个回放片段结束 然后触发无人观看之后  摄像头后台是不可以看回放的 但是 wvp前端的话 是可以看另外的回放片段

**Comment by 648540858** [comment]
看另外的就会把之前的停止

**Comment by github1359930721** [comment]
> 看另外的就会把之前的停止

已经播放过并触发无人观看的那些回放片段  是播放不了的

**Comment by 648540858** [comment]
抓包看吧
