### ISSUE TITLE
对点播地址新增拉流代理，访问拉流代理的参数无法传递到点播地址

### ISSUE THREAD

**Issue by zdystar** [648540858/wvp-GB28181-pro#715]
1. 先接入了一个国标设备，点播流地址ipaddr1: https://192.168.1.100:1443/rtp/34020000001320000011_34020000001320000011.live.ts
2. 对这个点播地址在新增一个拉流代理ipaddr2: https://192.168.1.100:1443/app1/stream1.live.ts
3. auto-apply-play参数设置为 true
4. 使用vlc播放给ipaddr2地址传的参数无法传递到ipaddr1，如下图所示。咨询下有没有好办法解决
![image](https://user-images.githubusercontent.com/14068724/210375669-2b612b8e-cade-4a42-a611-0bb3a1fd6dd0.png)

**Comment by 648540858** [comment]
你说的东西你是怎么理解的，这本来就是不可能通的呀，你先理解下拉流代理的含义吧
