### ISSUE TITLE
针对海康摄像头布防撤防返回信令DeviceId问题

### ISSUE THREAD

**Issue by szy833** [648540858/wvp-GB28181-pro#717]
**描述错误**
海康摄像头，布防返回的DeviceControl 中 DeviceId 是设备id。但是controller中key是由deviceId + channelId。这样会导致resultHolder 找不到对应的key 会返回Timeout。

**如何复现**
海康摄像头对接，发送布防请求，携带 deviceId,channelId

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
已修复
