### ISSUE TITLE
历史视频下载 callId 问题

### ISSUE THREAD

**Issue by szy833** [648540858/wvp-GB28181-pro#720]
**描述错误**
历史视频即将结束之后，下级发送MediaStatus。wvp没有发送bye。原因是SIPCommander.java中downloadStreamCmd方法最后streamSession.put()中的sipSender.getNewCallIdHeader(sipLayer.getLocalIp(device.getLocalIp()),device.getTransport()).getCallId()生成的CallId与信令交互中的CallId不一致。

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
已修复，你更新测试下
