### ISSUE TITLE
求改进云端录像操作方式

### ISSUE THREAD

**Issue by r59461900** [648540858/wvp-GB28181-pro#722]
求改进云端录像操作方式,并完善功能，感谢大佬！

**Comment by 648540858** [comment]
具体说说哪里体验不好，或者有问题

**Comment by r59461900** [comment]
录像搞半天都不行，我自己写了SHELL替代 ，你看能不能把这SHELL做成服务，并把录像目录投射网页上，供使用者查找.


录像命令

#!/bin/bash
t1=rtsp://192.168.12.250:554/rtp/34020000001320000011_34020000001320000011/
t2=rtsp://192.168.12.250:554/rtp/34020000001320000001_34020000001320000001/

for i in {$t1,$t2};do

nohup  ffmpeg -use_wallclock_as_timestamps 1 -rtsp_transport tcp -i  $i  -vcodec copy -acodec copy -f segment -reset_timestamps 1 -segment_atclocktime 1 -segment_time 3600 -strftime 1 /media/${i:51:-1}/%Y-%m-%d/%Y%m%d%H%M.mp4  > /dev/null 2>&1 &

done



文件夹自动创建
#!/bin/bash
a1=34020000001320000001
a2=34020000001320000011

for i in {$a1,$a2};do
cd /media/

if [ ! -d "$i" ];then
mkdir "$i"
else
echo "通道文件夹已存在"
fi
done

for i in {$a1,$a2};do
cd /media/$i

if [ ! -d "$(date +"%Y-%m-%d")" ];then
mkdir "$(date  +"%Y-%m-%d")"
else
echo "今天的文件夹已存在"
fi

if [ ! -d "$(date -d"tomorrow" +"%Y-%m-%d")" ];then
mkdir "$(date -d"tomorrow" +"%Y-%m-%d")"
else
echo "明天的文件夹已存在"
fi
done


if [ ! -d "$(date -d"-32 day" +"%Y-%m-%d")" ];then
rm -rf "$(date -d"-31 day" +"%Y-%m-%d")"
else
echo "删除文件夹不存在"
fi
if [ ! -d "$(date -d"-33 day" +"%Y-%m-%d")" ];then
rm -rf "$(date -d"-31 day" +"%Y-%m-%d")"
else
echo "删除文件夹不存在"
fi
if [ ! -d "$(date -d"-34 day" +"%Y-%m-%d")" ];then
rm -rf "$(date -d"-31 day" +"%Y-%m-%d")"
else
echo "删除文件夹不存在"
fi

#sed 's/\r//' -i 1.sh

**Comment by 648540858** [comment]
你如果看过文档，就不会这么觉得了。你是不是没装assist服务。
