### ISSUE TITLE
WVP作为下级平台接收并响应DeviceStatus指令问题

### ISSUE THREAD

**Issue by gaofuwang** [648540858/wvp-GB28181-pro#723]
**描述错误**
在WVP作为下级平台时，接收DeviceStatus指令时，虽然存在响应的逻辑处理但是却是硬编码的设备状态，统一在线。

**如何复现**
无需复现，代码已经写明
**预期行为**
我希望修复这个问题，我已经有了解决的方法并实践，希望参与到开发中。

**截图**
![image](https://user-images.githubusercontent.com/57347853/211484763-6a38a80f-eb45-4753-9b52-efe4cd8fa88b.png)

**环境信息:**
无

**Comment by 648540858** [comment]
如果你已经有解决方案，欢迎pr
