### ISSUE TITLE
画面颠倒

### ISSUE THREAD

**Issue by r59461900** [648540858/wvp-GB28181-pro#725]
**描述错误**
描述下您遇到的问题
在系统打开画面颠倒，在摄像头里打开又是正常的，下载的录像也正常画面。
**如何复现**

**预期行为**

**截图**
![微信截图_20230111000008](https://user-images.githubusercontent.com/116871699/211601283-5b8c2e30-da9c-4809-aefb-ddeba88ac53d.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos 8.4

**Comment by 648540858** [comment]
自行更换播放器解决即可
