### ISSUE TITLE
国标级联推上来的实时监控播放用的内网IP,应该用公网IP

### ISSUE THREAD

**Issue by threadroc** [648540858/wvp-GB28181-pro#726]
**描述错误**
国标级联推上来的实时监控播放用的内网IP,应该用公网IP
录像播放地址是内网IP:ws://192.168.0.49:9080/rtp/44010200492200000006_34020000001310000001.live.flv
应该是公网IP才对: ws://公网IP:9080/rtp/44010200492200000006_34020000001310000001.live.flv

录像下载也是这样,用的内网IP.

**环境信息:**
2023.1.11编译的最新版 ubuntu

**Comment by 648540858** [comment]
自行配置stream-ip
