### ISSUE TITLE
在阿里云上部署相关配置问题请教

### ISSUE THREAD

**Issue by ajax2019** [648540858/wvp-GB28181-pro#73]
wvp 部署在阿里云
zlm docker方式 部署在与wvp同一台云服务器

请问现在配置怎么配？目前按照如下配置，貌似前端摄像机注册不了

[可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 18080

作为28181服务器的配置
sip:
    # [必须修改] 本机的IP, 必须是网卡上的IP
    ip: 172.19.5.19  #101.131.233.114（公网，配置这个编译不过去） #172.19.5.19（阿里内网ip）
    # [可选] 28181服务监听的端口
    port: 5060

#zlm服务器配置
media:
    # [必须修改] zlm服务器的内网IP
    ip: 172.17.0.2  --- docker内部的ip

摄像机sip服务器地址和端口要配置哪个？
ip  101.131.233.114 ？ 172.19.5.19?
port 18080？5060?

**Comment by 648540858** [comment]
# [必须修改] 本机的IP, 必须是网卡上的IP

**Comment by ajax2019** [comment]
摄像机sip服务器地址和端口要配置哪个？
ip 101.131.233.114 ？ 172.19.5.19?
port 18080？5060?

**Comment by ajax2019** [comment]
摄像机sip服务器地址和端口要配置哪个？
ip 101.131.233.114 ？ 172.19.5.19?
port 18080？5060?

**Comment by ajax2019** [comment]
摄像机sip服务器地址和端口要配置哪个？
ip 101.131.233.114 ？ 172.19.5.19?
port 18080？5060? 
哪里配置有问题么？为什么注册不了？

**Comment by 648540858** [comment]
网卡查询结果贴一下，

> ```ip addr```

**Comment by ulyn** [comment]
请问下，如果wvp部署在docker容器内，本机ip应该填的是docker内的ip还是物理机器上的网卡ip？
