### ISSUE TITLE
录像下载中日志出现 “[录像]下载结束， 发送BYE失败 缓存事务信息未找到”

### ISSUE THREAD

**Issue by eanfs** [648540858/wvp-GB28181-pro#732]
**描述错误**
录像下载第一个片段下载完成后，后续片段还在下载中，日志中出现以下内容，视频无法下载完成
```
[录像]下载结束， 发送BYE失败 缓存事务信息未找到，device：31011232111188000183 channel: 34020000001320000073 ,callId: 6e39e127dbca97f8e0e062a9a44a5cc9@192.168.11.122,stream: 42494D81
```
![image](https://user-images.githubusercontent.com/5432110/215703618-e22ad664-af5c-4287-aba6-8f6f3b840d94.png)

**如何复现**
国标录像下载功能，
![image](https://user-images.githubusercontent.com/5432110/215702822-6a7512b9-5e0c-4479-a5e1-b27c9dc523ce.png)

**预期行为**

录像能够正常下载

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 mac
 - 3. 端口开放情况 
 - 4. 是否是公网部署 否
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台 HIK
 - 7. 你做过哪些尝试

**Comment by eanfs** [comment]
[download-failed.log](https://github.com/648540858/wvp-GB28181-pro/files/10544229/download-failed.log)
补充日志文件

**Comment by 648540858** [comment]
一般可以不关注，如果设备自己结束了事务是没有影响的

**Comment by eanfs** [comment]
但现在好像下载一直没有到100%，实际下载已经下载到最后了。

**Comment by kevin1406070662** [comment]
您好问题解决了吗

**Comment by kevin1406070662** [comment]
您好问题解决了吗，我也有这个错误提示，无法下载视频

**Comment by ketaxiang** [comment]
> 但现在好像下载一直没有到100%，实际下载已经下载到最后了。

录像下载的进度计算方案是存在问题的，比如你要下载某一个时段的录像，但实际上该段时间内的录像因为某些原因有缺失，根据时间计算的进度就达不到100%，所以还是应该根据信令来判断下载结束了。

**Comment by kevin1406070662** [comment]
我这个完全没法下载 ，不知道可否加个微信交流下&nbsp;


&nbsp;


Aholic
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月25日(星期六) 晚上11:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [648540858/wvp-GB28181-pro] 录像下载中日志出现 “[录像]下载结束， 发送BYE失败 缓存事务信息未找到” (Issue #732)





  
但现在好像下载一直没有到100%，实际下载已经下载到最后了。
  
录像下载的进度计算方案是存在问题的，比如你要下载某一个时段的录像，但实际上该段时间内的录像因为某些原因有缺失，根据时间计算的进度就达不到100%，所以还是应该根据信令来判断下载结束了。

**Comment by 648540858** [comment]
> > 但现在好像下载一直没有到100%，实际下载已经下载到最后了。
> 
> 录像下载的进度计算方案是存在问题的，比如你要下载某一个时段的录像，但实际上该段时间内的录像因为某些原因有缺失，根据时间计算的进度就达不到100%，所以还是应该根据信令来判断下载结束了。
根据信令判断是有的，只有设备不规范不发送停止推送的信令时，才会按照时间计算结束
