### ISSUE TITLE
[咨询]录像回放控制

### ISSUE THREAD

**Issue by ketaxiang** [648540858/wvp-GB28181-pro#740]
部署了wvp+zlm作为上级接入下级视频平台；
在录像回放时，调用了暂停，过了一段时间30秒左右，收到了视频平台发来的bye消息；
想请教一下是什么原因。

**Comment by 648540858** [comment]
暂停之后前端播放器的播放就暂停了，一段时间后触发无人观看，自动发送bye结束了。
