### ISSUE TITLE
一次点播时遇到触发两次invite的sip请求，如何阻止重复的sip信令发送？

### ISSUE THREAD

**Issue by sur1-123** [648540858/wvp-GB28181-pro#745]
**描述错误**
一次点播时遇到触发两次invite的sip请求，如何阻止重复的sip信令发送？

**如何复现**
使用wireshark抓包，sip机器为windows或者linux都出现了这种现象，（windows机器基本都有，也有linux机器不会触发这个现象），debug后只触发了一次 ` sipProvider.sendRequest `，但是发送了两次invite的sip信令。对方如果是设备还好说，设备一般都只会响应一次，但对方是平台时，对方处理的方式多种多样，有时会响应两次推流现象。
![QQ图片20230213114932](https://user-images.githubusercontent.com/64386388/218366230-4f9746df-1c0e-4c21-93a8-6ea6361aedee.jpg)

**预期行为**
如何阻止重复的sip信令发送？

**截图**
![`HIGHVLI67$U H)92Y8DP N](https://user-images.githubusercontent.com/64386388/218365995-66f5ab8c-2139-4162-ba2a-13c3db143200.jpg)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/  本地代码 zlm在centos部署
 - 2. 部署环境 windows / ubuntu/ centos ...  windows/linux的wvp-pro cnetos的zlm
 - 3. 端口开放情况 本地内网测试 都开发 无防火墙
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 大华
 - 7. 你做过哪些尝试 windows/linux下做同样点播抓包测试，出现了相同现象

**Comment by 648540858** [comment]
设备响应太慢，服务认为信令丢包导致自动重发了
