### ISSUE TITLE
点播视频，提示收流超时，请稍后重试

### ISSUE THREAD

**Issue by innocence-awr** [648540858/wvp-GB28181-pro#748]
**描述错误**
描述下您遇到的问题

**如何复现**

有明确复现步骤的问题会很容易被解决
点击国标设备中的通道列表，然后点击播放按钮，提示转圈，稍等一会就提示了图一收流超时

**预期行为**
清晰简洁的描述您期望发生的事情
播放正常

**截图**
![1676357268373](https://user-images.githubusercontent.com/37831893/218660388-927bd81d-4162-49d1-b83f-8ab3beb831ff.png)
![image](https://user-images.githubusercontent.com/37831893/218660529-67f2e460-8929-49f0-991a-2f62830d3377.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ... window+centos
 - 3. 端口开放情况 是
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试 查找状态码

**Comment by liukuan1** [comment]
遇到一样的问题

**Comment by 648540858** [comment]
查看[https://github.com/648540858/wvp-GB28181-pro/issues/434](https://github.com/648540858/wvp-GB28181-pro/issues/434)或者查看文档网站，基本都是配置问题。
