### ISSUE TITLE
VUE前端页面无法单独启动

### ISSUE THREAD

**Issue by 939216838** [648540858/wvp-GB28181-pro#749]
**描述错误**
代码版本最新版.vue项目 不能直接run dev. 启动页面报错
Cannot GET /

**如何复现**
直接拉取代码启动vue项目
解决办法 web_src/config/index.js  
assetsPublicPath 路径改一下 就好了 路径  现在是 ./    改成/
就可以正确启动
**预期行为**
正确启动vue

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by CoderLin99** [comment]
感谢感谢

**Comment by 648540858** [comment]
已经修复了
