### ISSUE TITLE
历史视频下载失败无法下载视频前端下载进度条一直是百分之0

### ISSUE THREAD

**Issue by kevin1406070662** [648540858/wvp-GB28181-pro#754]
**描述错误**
历史视频下载失败无法下载视频前端下载进度条一直是百分之0，报错提示来看是 ，录像下载结束通知后，无法获取redis中缓存的key 导致空指针错误报错提示。
0
**如何复现**
有明确复现步骤的问题会很容易被解决
只要点击历史视频下载就会出现
**预期行为**
清晰简洁的描述您期望发生的事情
可以正常下载历史视频
**截图**
![微信图片_20230224095222](https://user-images.githubusercontent.com/65798104/221072867-088fd512-eef4-4e82-a5fa-05e60f31a941.jpg)

**环境信息:**
部署方式：  idea 启动测试
部署环境:  windows
端口开放情况: 全开放
是否是公网部署: 内网测试
是否使用https :否
方便的话提供下使用的设备品牌或平台 : 海康设备
你做过哪些尝试： 
检查了录像路径 和配置的一致性 redis 保持在同一个数据库

**Comment by 648540858** [comment]
确定设备指出录像回放吗

**Comment by wildwindyevan** [comment]
开了 assi 录像助手服务吗？

**Comment by no-f** [comment]
怎么关了，so 结论是啥

**Comment by kevin1406070662** [comment]
现在改了可以了&nbsp;


Aholic
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月22日(星期一) 中午11:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [648540858/wvp-GB28181-pro] 历史视频下载失败无法下载视频前端下载进度条一直是百分之0 (Issue #754)





 
怎么关了，so 结论是啥

**Comment by no-f** [comment]
> 



> 怎么关了，so 结论是啥

ojbk
