### ISSUE TITLE
拉流代理配置流地址，报“保存失败，请检查地址是否可用！”

### ISSUE THREAD

**Issue by SilentsDesire** [648540858/wvp-GB28181-pro#755]
**描述错误**
拉流代理配置流地址，报“保存失败，请检查地址是否可用！”
![image](https://user-images.githubusercontent.com/21096504/221486039-2a992495-e9c7-4189-ae96-129ed44a9cd7.png)

**如何复现**
打开通道里面的播放按钮，拷贝请求里面的rtsp地址到拉流代理的流地址里面，然后点击启用报错
![image](https://user-images.githubusercontent.com/21096504/221486423-e46c7313-7fd5-4c1f-8ed2-ec2fa384c8a8.png)
![image](https://user-images.githubusercontent.com/21096504/221486583-03e8ffd6-78c4-4910-875f-b1774b16afa9.png)
![image](https://user-images.githubusercontent.com/21096504/221486648-cc544a9e-8870-48f2-93ab-6b04c0b15d7e.png)
查看docker logs,有个错误是连接拒绝
![image](https://user-images.githubusercontent.com/21096504/221487323-05f7ac37-224a-4200-92fd-53db43b67dd0.png)

**预期行为**
目前有个问题，我必须在通道里面打开播放的按钮，其它地方使用ws://xxxxx.flv这个地址才能播放，只要我把通道的播放停止了，其它地方也不能播放了，现在我想要实现的是，不需要打开通道里面的播放按钮，其它地方也能正常播放
**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/  都是docker 部署
 - 2. 部署环境 windows / ubuntu/ centos ...   centos
 - 3. 端口开放情况  554和其它配置的里面的端口都开放了
 - 4. 是否是公网部署  是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 华为的摄像头
 - 7. 你做过哪些尝试 开始以为是端口问题，端口全部开放后还是这样

**Comment by SilentsDesire** [comment]
解决了， # [可选] 自动点播， 使用固定流地址进行播放时，如果未点播则自动进行点播, 需要rtp.enable=true
    auto-apply-play: false    
改成true即可

**Comment by kodyds** [comment]
我也是这个issue，但auto-apply-play: true后也没有用

**Comment by xun-feng** [comment]
> 我也是这个issue，但auto-apply-play: true后也没有用

你解决了吗，我的也报错，提示启动失败，请检查地址是否可用
