### ISSUE TITLE
摄像头GB28181推流时如何设置鉴权

### ISSUE THREAD

**Issue by zkbiocloud-open** [648540858/wvp-GB28181-pro#758]
### 推流规则

支持推流时自定义播放鉴权Id，参数名为callId，此时sign=md5(callId_pushKey)
例如app=test，stream=live，pushKey=1000，callId=12345678, ip=192.168.1.4, port=10554 那么推流地址为：

rtsp://192.168.1.4:10554/test/live?callId=12345678&sign=c8e6e01dde2d60c66dcea8d2498ffef1

问题：默认接入的摄像头能够实现推拉流播发，默认是app=rtp,不需要任何鉴权信息的验证。

现在想按照官方的推流鉴权规则，需要如何实现呢？找不到设置sign的位置
rtsp://192.168.1.4:10554/test/live?callId=12345678&sign=c8e6e01dde2d60c66dcea8d2498ffef1

**Comment by 648540858** [comment]
国标推流不鉴权

**Comment by zkbiocloud-open** [comment]
如果这样处理的话，让摄像头拉流鉴权是不是也不需要呢？这样是不是有安全隐患呢，只要抓到拉流地址都可以随意播放了呢？

**Comment by 648540858** [comment]
是的。这确实不够安全，可以自己开发安全规则，也可以定制

**Comment by 2105424002** [comment]
如果国标拉流不需要鉴权，wvp辅助工具是不是就使用不了
