### ISSUE TITLE
网络校时

### ISSUE THREAD

**Issue by JacksonChao** [648540858/wvp-GB28181-pro#759]
大佬，请问一下您的国际网络校时的代码逻辑在哪里写的，想学习一下，万分感谢

**Comment by 648540858** [comment]
![image](https://user-images.githubusercontent.com/18274453/222999169-3378741d-ffa0-486f-bf48-ab525886d1eb.png)
```
com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.RegisterRequestProcessor:131行
```
