### ISSUE TITLE
查询录像无数据时空指针异常

### ISSUE THREAD

**Issue by zhangjian4** [648540858/wvp-GB28181-pro#767]
**描述错误**
查询国标录像时如果查询的时间范围内没有录像，会报空指针异常
releaseRequest方法中对recordInfo.getRecordList()进行了排序，但是当录像数据为空时recordInfo.getRecordList()为null

**如何复现**

**预期行为**

**截图**
![image](https://user-images.githubusercontent.com/23302214/223063370-0bf52398-b535-4dc7-b693-d5dd6b84f1e4.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker
 - 2. 部署环境 centos
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
是最新的代码。我测试没发现这个问题

**Comment by zhangjian4** [comment]
> 是最新的代码。我测试没发现这个问题

嗯，我看了下已经修复过了
