### ISSUE TITLE
同时请求同一个设备通道的录像数据时，只有一个请求能返回数据，其他的会超时

### ISSUE THREAD

**Issue by zhangjian4** [648540858/wvp-GB28181-pro#768]
**描述错误**
同时请求同一个设备通道的录像数据时，只有一个请求能返回数据，其他的会超时

**如何复现**
同一时间请求`/api/gb_record/query/{deviceId}/{channelId}`接口，传同一个deviceId和channelId

**预期行为**
两个请求都能正常返回

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker
 - 2. 部署环境 centos
 - 3. 端口开放情况 全部开放
 - 4. 是否是公网部署 是
 - 5. 是否使用https 是
 - 6. 方便的话提供下使用的设备品牌或平台 大华NVR
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
我测试下

**Comment by fmy2017** [comment]
我也是 访问同设备同通道 同一个时间段,只有第一次请求才能播放,其他的超时,就是同时只能一个人看

**Comment by scdn** [comment]
这个解决了吗？

**Comment by johnchunge** [comment]
遇到同样的问题，请问解决了吗？

**Comment by scdn** [comment]
https://github.com/648540858/wvp-GB28181-pro/issues/1436
可以看下这个

> 遇到同样的问题，请问解决了吗？
