### ISSUE TITLE
开始历时媒体下载的接口执行后，响应的Headers缺少 content_type字段

### ISSUE THREAD

**Issue by wildwindyevan** [648540858/wvp-GB28181-pro#769]
**描述错误**
postman调用该接口失败
/api/gb_record/download/start/

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/47787983/223424074-76bc096e-c4d8-4e37-ba7e-1b47b9276c37.png">

**Comment by 648540858** [comment]
![image](https://user-images.githubusercontent.com/18274453/226841019-bc1a406b-8be9-4c47-815c-75feb2061399.png)
