### ISSUE TITLE
设备录像总显示暂无数据

### ISSUE THREAD

**Issue by liufeng4466** [648540858/wvp-GB28181-pro#772]
**描述错误**
在设备使用功能中的设备录像页面的数据是否是从硬盘录像机中获得？

**Comment by liufeng4466** [comment]
进入设备录像页面，没有显示录像数据。
![20230309173514](https://user-images.githubusercontent.com/5681378/223982615-46a1af80-0579-4415-89ba-6862dd7a77fd.png)

**Comment by liufeng4466** [comment]
阿里云服务器， 海康摄像头。

**Comment by 648540858** [comment]
你的摄像头不支持录像查询
