### ISSUE TITLE
想通过发送询问设备状态,判断设备是否在线,设备不在线的话,就是超时了,怎么样获取设备超时呢

### ISSUE THREAD

**Issue by wangzheooo** [648540858/wvp-GB28181-pro#775]
**描述错误**
想通过发送询问设备状态,判断设备是否在线,设备不在线的话,就是超时了,怎么样获取设备超时呢

**如何复现**
![image](https://user-images.githubusercontent.com/55420071/224242716-332e9d6f-fb07-47b0-bcd9-394680d94872.png)

**预期行为**
想在SipSubscribe.Event errorEvent中取到超时

**截图**
![image](https://user-images.githubusercontent.com/55420071/224242944-48220c87-4220-4597-ba4f-55fd52a1833b.png)

**环境信息:**
 - 1. 部署方式 wvp-pro + zlm都是编译部署
 - 2. 部署环境 wvp-pro(本机windows),zlm(centos)
 - 3. 端口开放情况 无防火墙
 - 4. 是否是公网部署 内网
 - 5. 是否使用https 不使用
 - 6. 方便的话提供下使用的设备品牌或平台 海康的摄像头
 - 7. 你做过哪些尝试 找了代码和issue,水平有限

**Comment by 648540858** [comment]
目前不支持，可以设置一个定时任务，如果到时间了，没有成功也没有失败，则为超时。
