### ISSUE TITLE
使用docker部署，点播回来的流的IP是乱码，录像的流没问题

### ISSUE THREAD

**Issue by ken626014896** [648540858/wvp-GB28181-pro#776]
**描述错误**
使用docker部署，点播回来的流的ip是乱码，录像的流没问题
奇怪的是直接部署没有这个问题

**截图**
![image](https://user-images.githubusercontent.com/38373469/224467710-873a8f27-8e1a-49b5-a7f3-9a8e5d067d6e.png)

![image](https://user-images.githubusercontent.com/38373469/224467859-7fcb0ee7-690b-4250-8ed4-3d4908a53d9c.png)

发现只有ts流的ip是正确的
sip.ip是0.0.0.0  

**环境信息:**
 - 1. 部署方式   docker wvp-pro和zlm在同一个容器  redis和mysql在宿主机
 - 2. 部署环境 ubuntu...
 - 3. 端口开放情况 端口都开放了
 - 4. 局域网部署
 - 5. 不使用https

**Comment by 648540858** [comment]
这不是乱码，这是ipv6地址

**Comment by 648540858** [comment]
这是自动根据请求ip设置为流IP导致的，设置
```
    # 是否使用设备来源Ip作为回复IP， 不设置则为 false
    sip-use-source-ip-as-remote-address: false
```
为false，关闭这个特性测试下

**Comment by ken626014896** [comment]
好像不是这个原因 
![image](https://user-images.githubusercontent.com/38373469/224961553-d46896bf-f51d-416b-812f-85e785126024.png)
配置文件就是false的

**Comment by 648540858** [comment]
自行研究吧，我对docker也不熟悉，似乎和你docker的网络有关
