### ISSUE TITLE
sql文件咨询

### ISSUE THREAD

**Issue by MengFanLu1** [648540858/wvp-GB28181-pro#777]
**描述错误**
描述下您遇到的问题
初始化sql文件放哪去了，不给提供了吗？现在只有一个clean.sql文件
**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by oyange** [comment]
同问，用了其他分支的sql文件，报错了

**Comment by oyange** [comment]
> 同问，用了其他分支的sql文件，报错了

选错分支了，选最新分支就ok了

**Comment by fang12100** [comment]
> 同问，用了其他分支的sql文件，报错了

在wvp-GB28181-pro/src/main/resources/db/migration/
