### ISSUE TITLE
拉流代理拉流失败

### ISSUE THREAD

**Issue by fly2016git** [648540858/wvp-GB28181-pro#779]
**描述错误**
有一个rtsp地址定时变化的流，使用拉流代理拉流时需要不停的删除和重新添加代理，保持了app和stream两个字段是一致的，这时就会出现播放失败的错误。

**如何复现**
1. 为rtsp1添加一个拉流代理, app=t01, stream=t01
2. 确认添加成功后，端口rtsp1的流(拔掉摄像头网线，或者停掉模拟流)
3. 为rtsp2添加拉流代理，同样app=t01, stream=t01
4. 拉流播放失败
5. 重新插上rtsp1的摄像头网线，播放rtsp2的拉流，看到的是rtsp1的视频内容

**预期行为**
希望看到的是rtsp2的内容

**Comment by 648540858** [comment]
`同样app=t01, stream=t01` 这个第一个拉流代理是删除了吧，不删除你应该无法添加
还有第四步拉流代理失败，是添加rtsp2后无法播放吗

**Comment by penghd** [comment]
> **描述错误** 有一个rtsp地址定时变化的流，使用拉流代理拉流时需要不停的删除和重新添加代理，保持了app和stream两个字段是一致的，这时就会出现播放失败的错误。
> 
> **如何复现**
> 
>     1. 为rtsp1添加一个拉流代理, app=t01, stream=t01
> 
>     2. 确认添加成功后，端口rtsp1的流(拔掉摄像头网线，或者停掉模拟流)
> 
>     3. 为rtsp2添加拉流代理，同样app=t01, stream=t01
> 
>     4. 拉流播放失败
> 
>     5. 重新插上rtsp1的摄像头网线，播放rtsp2的拉流，看到的是rtsp1的视频内容
> 

你这个是使用了ZLM一直拉流，ZLM的streamt01指向的就是rtsp1，你第二次添加实际上ZLM报错了，要灵活处理只能自己写ZLM的hook程序
