### ISSUE TITLE
部署到外网不能播放

### ISSUE THREAD

**Issue by angel-baal** [648540858/wvp-GB28181-pro#78]
media:
    # [必须修改] zlm服务器的内网IP
    ip: 192.168.100.67
    # [可选] zlm服务器的公网IP, 内网部署置空即可
    wanIp: 221.222.168.163
    # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip
    hookIp: 
    # [必须修改] zlm服务器的http.port
    port: 6780
    # [可选] 是否自动配置ZLM, 如果希望手动配置ZLM, 可以设为false, 不建议新接触的用户修改
    autoConfig: true

**Comment by 648540858** [comment]
如果你的rtp->enable 是true， 查看的你的udpPortRange设置的端口范围是否开放了。
tp->enable 是false， 确定10000端口开了
