### ISSUE TITLE
前端非GET请求403错误

### ISSUE THREAD

**Issue by LuoTaotaotaotaotao** [648540858/wvp-GB28181-pro#782]
**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**
![image](https://user-images.githubusercontent.com/39144782/226238577-4968a52d-cdb4-4066-a7b7-ea9bad9b2a66.png)

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
我测试下，之前测试没有发现这个问题。另外不建议你刚开始就用docker部署测试，更容易遇到问题。

**Comment by 648540858** [comment]
自行检查代码吧，我测试并无这个问题

**Comment by LuoTaotaotaotaotao** [comment]
已经没问题了

**Comment by liu279** [comment]
> 已经没问题了

请问怎么解决的，我这本地跑的除了get方式其他还是403

**Comment by LuoTaotaotaotaotao** [comment]
就是前端那个代理配置那有个changeOrigin改成false

**Comment by liu279** [comment]
> 就是前端那个代理配置那有个changeOrigin改成false

可以了，多谢
