### ISSUE TITLE
时间参数验证的BUG

### ISSUE THREAD

**Issue by Steven0621** [648540858/wvp-GB28181-pro#784]
当查询条件中存在可为空的时间参数时，验证时间格式时发生异常，所有涉及到可空时间参数的地方都存在这个bug。详情见截图。

**截图**

![20230320145444](https://user-images.githubusercontent.com/6915294/226268452-d698eeb0-2a9c-47c3-b8b3-0187bc375136.png)

应该修改为：
if (time != null && !DateUtil.verification(time, DateUtil.formatter)){
    return null;
}

**Comment by 648540858** [comment]
好的，我处理一下
