### ISSUE TITLE
跨域配置不生效

### ISSUE THREAD

**Issue by Steven0621** [648540858/wvp-GB28181-pro#789]
**描述错误**
在配置文件中配置了跨域相关配置，但是跨域仍然报错，在响应头里没有看到相关的跨域配置，请测试一下是不是bug。

**截图**
![20230323081116](https://user-images.githubusercontent.com/6915294/227066868-2fab4909-4a67-42ba-a026-7a6dcc80894a.png)
![20230323081326](https://user-images.githubusercontent.com/6915294/227066870-4a14ddcd-c7b1-4004-981e-d20f910675fc.png)
![20230323081401](https://user-images.githubusercontent.com/6915294/227066873-01fddacd-9e6c-4312-8023-2a033af2aaf1.png)

**Comment by 648540858** [comment]
已修复
