### ISSUE TITLE
关闭接口鉴权功能, 页面上获取不到任何数据。

### ISSUE THREAD

**Issue by Steven0621** [648540858/wvp-GB28181-pro#790]
**描述错误**
关闭接口鉴权功能，网页登录一段时间后，页面上什么数据都没有了，每个页面都是空数据(猜测是token过期导致的)，注销报404，无法注销，只有手动删除localStorage里的wvp-token才能转到登录页面重新登录。

**截图**
![20230323081954](https://user-images.githubusercontent.com/6915294/227069591-29de8d94-f182-4a1d-ab2a-4475eb6573cc.png)
![20230323082023](https://user-images.githubusercontent.com/6915294/227069595-3805c7bd-248b-432a-9378-d9c74165923b.png)
![20230323082918](https://user-images.githubusercontent.com/6915294/227069596-471f1fd6-671b-4ae9-a69f-76296bd4bff4.png)

**Comment by 648540858** [comment]
已修复

**Comment by 648540858** [comment]
刚修复了另一个问题，可能与这个问题有关，你也一并测试下。

**Comment by Steven0621** [comment]
好的

**Comment by Steven0621** [comment]
> 刚修复了另一个问题，可能与这个问题有关，你也一并测试下。

刚测试了一下，没问题了。
