### ISSUE TITLE
在非测试类中@Order 使用的是org.junit.jupiter.api.Order，而不是org.springframework.core.annotation.Order

### ISSUE THREAD

**Issue by Dream-s-Wang** [648540858/wvp-GB28181-pro#792]
**描述错误**
在非测试类中@Order 使用的是org.junit.jupiter.api.Order，而不是org.springframework.core.annotation.Order
**如何复现**
见源码使用@Order的地方
**预期行为**
在会降低springboot版本时，org.junit.jupiter.api.Order会报无法使用，修改为org.springframework.core.annotation.Order后可用，已测试版本2.4.2、2.5.12

**Comment by 648540858** [comment]
已修复
