### ISSUE TITLE
用户管理中新增、删除、管理员改用户密码实际无法使用

### ISSUE THREAD

**Issue by penghd** [648540858/wvp-GB28181-pro#796]
UserController.java中，判断当前用户是否管理员角色才能进行下一步操作，实际都不可用，涉及：
add、delete、changePushKey、changePasswordForAdmin（最后这个函数语句略有不同）
4个函数使用：
 int currenRoleId = SecurityUtils.getUserInfo().getRole().getId();
而实际上getUserInfo()返回的user只有用户名和时间，获取不到角色Id，抛出异常

用户类和接口比较多，没有仔细看，用以下简单方法解决供参考：
建一个函数获取用户角色Id：
    private int getCurrenRoleId(LoginUser userInfo){
        User currenUser = userService.getUserByUsername(userInfo.getUsername());
        return currenUser.getRole().getId();
    }

把 4个函数中的：
 int currenRoleId = SecurityUtils.getUserInfo().getRole().getId();
替换为：
int currenRoleId = getCurrenRoleId(SecurityUtils.getUserInfo());

这样还是不规范，应该在调整的是 SecurityUtils.getUserInfo()，但这是个静态类来调userService，仅供大佬参考做整体调整，就不pull了

**Comment by criver31** [comment]
我的代码在登录时setAuthentication进了authenticate,但后续其他接口调用到SecurityUtils.getAuthentication()时返回是null，请问这是为什么

**Comment by slpBerry** [comment]
> 我的代码在登录时setAuthentication进了authenticate,但后续其他接口调用到SecurityUtils.getAuthentication()时返回是null，请问这是为什么

配置文件里 user-settings.allowed-origins 加一下跨域配置的地址，除了localhost，本地ip的也配置一下

**Comment by slpBerry** [comment]
@criver31 配置文件里 user-settings.allowed-origins 加一下跨域配置的地址，除了localhost，本地ip的也配置一下，试试
> 我的代码在登录时setAuthentication进了authenticate,但后续其他接口调用到SecurityUtils.getAuthentication()时返回是null，请问这是为什么

**Comment by criver31** [comment]
> @criver31 配置文件里 user-settings.allowed-origins 加一下跨域配置的地址，除了localhost，本地ip的也配置一下，试试
> 
> > 我的代码在登录时setAuthentication进了authenticate,但后续其他接口调用到SecurityUtils.getAuthentication()时返回是null，请问这是为什么



> @criver31 配置文件里 user-settings.allowed-origins 加一下跨域配置的地址，除了localhost，本地ip的也配置一下，试试
> 
> > 我的代码在登录时setAuthentication进了authenticate,但后续其他接口调用到SecurityUtils.getAuthentication()时返回是null，请问这是为什么

我在配置文件中没找到这个配置，代码中也没有使用这个配置项的地方；可以加个联系方式问下你吗

**Comment by criver31** [comment]
> @criver31 配置文件里 user-settings.allowed-origins 加一下跨域配置的地址，除了localhost，本地ip的也配置一下，试试
> 
> > 我的代码在登录时setAuthentication进了authenticate,但后续其他接口调用到SecurityUtils.getAuthentication()时返回是null，请问这是为什么

我在配置文件中没有找到这个配置，代码中也没有使用到这个配置项，可以留个联系方式问下你吗

**Comment by slpBerry** [comment]
> > @criver31 配置文件里 user-settings.allowed-origins 加一下跨域配置的地址，除了localhost，本地ip的也配置一下，试试
> > > 我的代码在登录时setAuthentication进了authenticate,但后续其他接口调用到SecurityUtils.getAuthentication()时返回是null，请问这是为什么
> 
> 我在配置文件中没有找到这个配置，代码中也没有使用到这个配置项，可以留个联系方式问下你吗
@criver31 你留吧，我加你，qq?

**Comment by criver31** [comment]
> > > @criver31 配置文件里 user-settings.allowed-origins 加一下跨域配置的地址，除了localhost，本地ip的也配置一下，试试
> > > > 我的代码在登录时setAuthentication进了authenticate,但后续其他接口调用到SecurityUtils.getAuthentication()时返回是null，请问这是为什么
> > 
> > 
> > 我在配置文件中没有找到这个配置，代码中也没有使用到这个配置项，可以留个联系方式问下你吗
> > @criver31 你留吧，我加你，qq?

741714398

**Comment by 648540858** [comment]
已修复
