### ISSUE TITLE
录像回放，暂停后，调用resume恢复回放失败

### ISSUE THREAD

**Issue by Steven0621** [648540858/wvp-GB28181-pro#797]
**描述错误**
录像回放调用pause方法，暂停录像回放后，再调用resume恢复回放，第一次能成功，但是第二次暂停，再调用resume恢复回放，显示是成功的，但是实际视频图像还是暂停状态，没有恢复成功。多次调用resume接口，会返回500错误，请检查是否是bug。

**Comment by Steven0621** [comment]
调用录像回放的倍速播放，也没有效果，好像也是个bug

**Comment by Steven0621** [comment]
调用录像回放的倍速播放，也不生效。

**Comment by 648540858** [comment]
> **描述错误** 录像回放调用pause方法，暂停录像回放后，再调用resume恢复回放，第一次能成功，但是第二次暂停，再调用resume恢复回放，显示是成功的，但是实际视频图像还是暂停状态，没有恢复成功。多次调用resume接口，会返回500错误，请检查是否是bug。

这个是因为你的停止播放一段时间后，wvp认为无人观看就停止了，建议把无人观看时间加长，后者直接使用回放接口重新开始，进一步的修复的话，比如对于暂停的流不进行无人观看停止，需要过一段时间了。

**Comment by 648540858** [comment]
> 调用录像回放的倍速播放，也不生效。

目前的国标的倍速播放都只是倍速发流，但是时间戳不加倍，所以目前的播放器不支持。你需要使用支持的播放器或者定制，或者定制zlm使其支持时间戳加倍

**Comment by Steven0621** [comment]
好的，谢谢

**Comment by bigff-0527** [comment]
> 好的，谢谢

你好，请问有解决方案吗？
