### ISSUE TITLE
RESTful接口getServerConfig返回的是原ZML初始化配置文件的内容

### ISSUE THREAD

**Issue by 1085665987** [648540858/wvp-GB28181-pro#798]
**描述错误**
通过RESTful接口setServerConfig设置之后，但是RESTful接口getServerConfig返回的是原ZML初始化配置文件的内容

**截图**
![问题](https://user-images.githubusercontent.com/57886182/228169293-a2483a49-23b9-44c7-ac1c-8e38ff7fd3ee.png)

**Comment by 1085665987** [comment]
作者能答复一下吗，感谢解释

**Comment by 648540858** [comment]
这个你应该去zlm的issue下面提
