### ISSUE TITLE
request中via部分注释了 那个ip为sip的ip，改为了设备的ip，我发现这个有问题，海康威视的nvr不会回复 INVITE消息

### ISSUE THREAD

**Issue by xsShuang** [648540858/wvp-GB28181-pro#8]
request中via部分注释了 那个ip为sip的ip，改为了设备的ip，我发现这个有问题，海康威视的nvr不会回复 INVITE消息
sip中 via 的部分应该是发起本次回话的sip服务器的地址，形成一个回环。

**Comment by 648540858** [comment]
已修复, 更新代码测试下吧
