### ISSUE TITLE
SQL错误

### ISSUE THREAD

**Issue by songzihao** [648540858/wvp-GB28181-pro#802]
**描述错误**
DeviceMapper.java
275行、289行遗漏逗号

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by songzihao** [comment]
<img width="879" alt="截屏2023-03-30 17 45 19" src="https://user-images.githubusercontent.com/12580098/228797939-71a24d6f-6046-4917-a54d-cb66e20f8412.png">

**Comment by 648540858** [comment]
已修复
