### ISSUE TITLE
跨域配置，设置为*，报错

### ISSUE THREAD

**Issue by Steven0621** [648540858/wvp-GB28181-pro#803]
**描述错误**
在配置文件中将跨域配置如下，会报错：
allowed-origins
        - *

**截图**
![20230331135111](https://user-images.githubusercontent.com/6915294/229034449-db672ac3-c7f6-4e84-a8d8-ad4eaa9c8637.png)

**Comment by 648540858** [comment]
哪里的文档告诉你可以这么配置的，你这不是自己找难受吗

**Comment by 648540858** [comment]
没有允许所有跨域的配置，好好的把具体的配置上就可以了。
