### ISSUE TITLE
云端录像页面查看录像视频不显示/网络请求视频录像超时/录像时长缺失

### ISSUE THREAD

**Issue by wangran99** [648540858/wvp-GB28181-pro#804]
**描述错误**
1. 云端录像页面查看录像视频不显示/网络请求视频录像超时
2. 拖动时间轴，视频跟时间轴不对应
3. 页面卡死，导致chrome占用cpu越来越高，然后操作系统卡死、无响应

**如何复现**
ipc设备注册到wvp，观看直播10分钟，进入云端录像产看ipc录像。

**预期行为**
拖动时间轴，视频录像快速响应播放

**截图**
![image](https://user-images.githubusercontent.com/17898332/229037298-a73c8ea4-4452-4168-9d59-e079281e3466.png)
网络请求录像超时（1分钟），视频没有播放。
assist安装了，没有报错日志

![image](https://user-images.githubusercontent.com/17898332/229040104-32146cd7-f0b5-4976-aeb5-2911c8b16e73.png)
录像时长缺失。连续观看俩小时直播，查看录像发现视频都是分段的且录像时长不完整，有缺失，每个视频录像文件之间缺少几分钟的视频录像。

**环境信息:**
 - 1. 部署方式   wvp-prp + zlm都是编译部署
 - 2. 部署环境 centos 
 - 3. 端口开放情况 全部开放
 - 4. 是否是公网部署 公网
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 大华
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
你确定期间一直在前台保持播放了？

**Comment by 648540858** [comment]
比较可能的原因是你你开启了自动点播，中间有段时间没有点播，后来你有开始播放自动点播了

**Comment by wangran99** [comment]
>  配置文件中开启了推流直播录制

    # 推流直播是否录制
    record-push-live: true
    # 国标是否录制
    record-sip: true
    # 是否将日志存储进数据库
    logInDatebase: true
    # 使用推流状态作为推流通道状态
    use-pushing-as-status: true

![image](https://user-images.githubusercontent.com/17898332/229055128-6916d6f9-6091-428e-817c-80882c403abf.png)
[拉流中新建了苹果的拉流地址：点击进入苹果视频流](http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear2/prog_index.m3u8)
但是云端录像中没有找到录制的视频文件有的不完整 ，有的压根没有视频文件

**Comment by fanfanertan** [comment]
我的连录像文件也不显示
![image](https://user-images.githubusercontent.com/32301941/235088568-b8dfa587-0efd-4c51-ba9d-da4a1e26c3ec.png)

**Comment by xun-feng** [comment]
> 我的连录像文件也不显示 ![image](https://user-images.githubusercontent.com/32301941/235088568-b8dfa587-0efd-4c51-ba9d-da4a1e26c3ec.png)
我也遇到了这个问题，不显示录像文件，你解决了吗
