### ISSUE TITLE
拉流代理界面可以播放，但是分屏监控无法播放

### ISSUE THREAD

**Issue by ziyuewu1105** [648540858/wvp-GB28181-pro#806]
我在接入海康摄像头的时候，平台接入方式为萤石云，我不想改变它原有的配置，然后还能再平台中接入，所以就通过拉流的方式，配置好了之后在拉流代理界面可以正常播放，但是无法在分屏监控中播放，请问是本身就不支持这样操作还是说我有哪里没配置好呢？

**Comment by 648540858** [comment]
分屏播放那里只能播放国标的，自己根据业务修改吧
