### ISSUE TITLE
如何调用wvp接口发起点播请求

### ISSUE THREAD

**Issue by jeffman2020** [648540858/wvp-GB28181-pro#808]
现在如果要用wvp生成的网页地址播放实时视频（无论通过rtsp地址或者rtmp地址，或者hls地址等），必须首先在wvp里该通道点播放，不点播放按钮，是播放不出视频的，因为wvp没有视频源。有没有办法不需要在wvp里点一下播放按钮，就可以直接通过页面启动通道并播放。意思就是在网页里通过调用wvp接口发起点播请求，启动wvp的通道（相当于点了播放按钮那个动作），然后在网页里通过地址播放出来。
实际上面的根本问题就是如何从外部通过接口调用wvp的功能

**Comment by penghd** [comment]
一旦在wvp设置拉流代理并且无人观看不处理就不再需要通过wvp，播放对话框最底下的就是ZLM的媒体地址，你用vlc等播放器可以直接播放。如果要在网页播放，需要用flv.js等播放插件，最好的就是wvp自带的jessibuca

**Comment by Steven0621** [comment]
WVP提供了API接口，可以直接调用啊，具体的API接口，可以查看你wvp网页里的在线文档。
![20230403093450](https://user-images.githubusercontent.com/6915294/229392575-e4bc17de-67fe-439e-97aa-77ed54b636b5.png)
