### ISSUE TITLE
默认本地sip端口只能监听一个，上联上级平台可以用不同的sip端口吗

### ISSUE THREAD

**Issue by itcareer** [648540858/wvp-GB28181-pro#81]
请问是否可以支持下，谢谢

**Comment by 648540858** [comment]
不可以的，对于服务来说。收消息和发消息是一个端口，暂时不支持使用其他的 648540858 ***@***.*** 签名由 网易邮箱大师 定制 在2021年04月13日 17:35，gwl 写道： 请问是否可以支持下，谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
