### ISSUE TITLE
wvp-assist-pro启动报错

### ISSUE THREAD

**Issue by mrfneo** [648540858/wvp-GB28181-pro#812]
![image](https://user-images.githubusercontent.com/42573097/230535162-b8f5809d-cd37-4dea-b190-4009cc0836b7.png)
![image](https://user-images.githubusercontent.com/42573097/230535233-35156823-72b5-464b-93ad-6ddd118d9dbd.png)

**Comment by mrjackwang** [comment]
先确保文件路径是否正确，然后确认ffmpeg和ffprobe是否有已授权可执行，chmod -x ffmpeg ,chmod -x ffmpeg

**Comment by mrfneo** [comment]
权限都给到了，路径也是对的，他报的错应该是内部错误。
![image](https://user-images.githubusercontent.com/42573097/231045843-ae3f2251-385d-4376-ad5f-1bdb7d51b4ab.png)

**Comment by 648540858** [comment]
ffmpeg路径错误或者无权限使用

**Comment by mrfneo** [comment]
![image](https://user-images.githubusercontent.com/42573097/231053188-2d7e2056-5b5f-4d77-80ec-0174a1e48a20.png)
![image](https://user-images.githubusercontent.com/42573097/231053221-fb0b4dd6-cd8b-4706-a9b2-2e198bf1340b.png)确认完路径和权限都是正常的啊，而且路径会提示路径错误，权限现在都是777

**Comment by 648540858** [comment]
你直接执行下
```bash
./ffmpeg
```
贴一下打印的内容
