### ISSUE TITLE
重启wvp-pro设备离线

### ISSUE THREAD

**Issue by sxh-netizen** [648540858/wvp-GB28181-pro#814]
**描述错误**
设备假离线

**如何复现**
重启wvp-pro
**预期行为**
可以准确的知道设备的在离线
**截图**
![image](https://user-images.githubusercontent.com/58098910/230809831-20228387-bd58-4085-93ea-ace5129dbfd9.png)
![image](https://user-images.githubusercontent.com/58098910/230810432-edb34352-2df9-4071-a8d8-3cddd101bc3d.png)

**环境信息:**
 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows
 - 3. 端口开放情况:内网环境
 - 4. 是否是公网部署：否
 - 5. 是否使用https ： 否
 - 6. 设备品牌：大华
 - 7. 你做过哪些尝试：当我把 在接收到设备的Keepalive信令，将设备注册周期是否过期的判断解除后，不会造成假掉线的情况

**Comment by 648540858** [comment]
设备离线是服务器根据心跳时间去判断，不可能启动后去鉴空每个设备的状态的，不现实，如果有几十万设备，你怎么一个个去获取状态呢。所以启动后的默认机制是判断上一次心跳的时间，来判断是否离线，等到设备第一次心跳或者注册，就上线了。如果你有更优的设计，欢迎一起讨论。

**Comment by sxh-netizen** [comment]
但是现在有一种情况，当服务器显示这边设备掉线了，但是设备那边并没有感知它自己一定掉线了，还是一直发送 Keepalive

**Comment by 648540858** [comment]
服务端显示设备离线是因为你重启了服务，打断服务对在线状态的监听，设备可能并没有离线，所以一段时间后就会恢复。

**Comment by BeyondTheBlade** [comment]
> 我先关闭了，你有问题就再打开

我这边发现相同问题，掉线后还有发心跳日志，但是没重新注册的日志。导致设备看着是假死，设备状态没为在线。重新把设备删除后恢复正常
