### ISSUE TITLE
 点击播放视频偶尔会出现failed: address already in use

### ISSUE THREAD

**Issue by liwenyan703** [648540858/wvp-GB28181-pro#819]
**描述错误**
描述下您遇到的问题
 点击播放视频偶尔会出现下面的错误，视频就无法播放了，等10秒左右再点击就好了，希望得到你的帮助

2023-04-14 19:37:29.720  INFO --- PlayServiceImpl : [点播消息] 收到invite 200, 发现下级自定义了ssrc: 0002004466
2023-04-14 19:37:29.720  INFO --- PlayServiceImpl : [点播消息] SSRC修正 0102008325->0002004466
2023-04-14 19:37:29.722  INFO --- ZLMRTPServerFactory : {"code":0,"exist":false}
2023-04-14 19:37:29.723  INFO --- ZLMRTPServerFactory : {"code":-400,"msg":"Listen on :: 30362 failed: address already in use"}
2023-04-14 19:37:29.723 ERROR --- ZLMRTPServerFactory : 创建RTP Server 失败 Listen on :: 30362 failed: address already in use: 
2023-04-14 19:37:29.751  INFO --- StackLoggerImpl : Setting SIPMessage peerPacketSource to: /43.80.110.103:7100
2023-04-14 19:37:29.751  INFO --- StackLoggerImpl : 发送：目标--->43.80.110.103:7100
BYE sip:44010200492000000001@43.87.122.11:5060 SIP/2.0
Via: SIP/2.0/UDP 43.80.110.103:7100;rport=7100;branch=z9hG4bK1301543826z45258_8d8c1c1cca03;received=43.80.110.103
From: <sip:43100200001310061714@43.80.110.103:7100>;tag=2129725798_8d8c1c1cca03
To: <sip:44010200492000000001@4401020049>;tag=4372ef6eed9a4c5eb0a2a0d18e09fbbd
Call-ID: e7a87677c1c70891892fed65d3dbec64@43.87.122.11
CSeq: 2838349 BYE
Max-Forwards: 70
User-Agent: NcgV5.14.100
Content-Length: 0

**如何复现**
 点击播放视频按钮，偶尔会出现创建RTP Server 失败 Listen on :: 30362 failed: address already in use

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**
<img width="1280" alt="无标题2" src="https://user-images.githubusercontent.com/39700864/232040722-44ec256b-439d-434c-8b10-b91a8a60544f.png">

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) 
 - 2. 部署环境 centos 7
 - 3. 端口开放情况  端口5060 18080 需要的都开了，整个流程没问题
 - 4. 是否是公网部署 没有公网
 - 5. 是否使用https  没有
 - 6. 方便的话提供下使用的设备品牌或平台  海康平台
 - 7. 你做过哪些尝试

**Comment by 648540858** [comment]
代码更新到最新测试下，最近刚修复这个问题，但是没有测试环境测试。你可以测试下。

**Comment by liwenyan703** [comment]
> 代码更新到最新测试下，最近刚刚修复这个问题，但是没有测试环境测试。你可以测试下。
测试不可以的，如果关闭ssrc 效验就不会出现这个错误

**Comment by liwenyan703** [comment]
代码我是更新到了最新了，还是存在这个问题，如果是关闭了ssrc效验就不会出现这个问题哥，你看一下，方便的话我给你联系方式18501931541&nbsp;


1184490717
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 上午9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro]  点击播放视频偶尔会出现failed: address already in use (Issue #819)





 
代码更新到最新测试下，最近刚修复这个问题，但是没有测试环境测试。你可以测试下。

**Comment by 648540858** [comment]
那就端口释放不及时造成的，我考虑下怎么优化

**Comment by liwenyan703** [comment]
好的你喊我一下，我帮你测试




1184490717
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 上午10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro]  点击播放视频偶尔会出现failed: address already in use (Issue #819)





 
那就端口释放不及时造成的，我考虑下怎么优化

**Comment by 648540858** [comment]
好

**Comment by liwenyan703** [comment]
问题还存在，关闭ssrc效验就不存在了，目前能用的方式的tcp被动，关闭效验这个组合，可以其它的组合还不行，从海康那边同步过来的业务资源树，也有问题看不到摄像头，只到目录这一级别，这个问题，回头我贴给你哥





1184490717
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro]  点击播放视频偶尔会出现failed: address already in use (Issue #819)





 
添加了修复代码，你测试下，zlm编译到最新的再测试。

**Comment by 648540858** [comment]
好的，我们在研究下

**Comment by liwenyan703** [comment]
要的




1184490717
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 下午3:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro]  点击播放视频偶尔会出现failed: address already in use (Issue #819)





 
好的，我们在研究下

**Comment by liwenyan703** [comment]
哥我在另外一个平台上用的mysql8.0的这些问题不存在了没有端口占用的情况了，你先别优化我在观察一下


1184490717
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 下午3:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro]  点击播放视频偶尔会出现failed: address already in use (Issue #819)





 
好的，我们在研究下

**Comment by 648540858** [comment]
好的

**Comment by jackytang** [comment]
经过测试, 目前暂时未发现该问题了

**Comment by 648540858** [comment]
好的
