### ISSUE TITLE
直播流保活的信令是什么样子的呢

### ISSUE THREAD

**Issue by wkdepth** [648540858/wvp-GB28181-pro#82]
麻烦问下大佬，直播流保活的信令是什么样子的呢？谢谢

**Comment by 648540858** [comment]
wireshark过滤rtcp 648540858 ***@***.*** 签名由 网易邮箱大师 定制 在2021年04月14日 15:08，wkdepth 写道： 麻烦问下大佬，直播流保活的信令是什么样子的呢？谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
