### ISSUE TITLE
[BUG]国标级联中当上级平台掉线时点击编辑保存有时会出现注册失败的情况

### ISSUE THREAD

**Issue by SixSix-God** [648540858/wvp-GB28181-pro#820]
> **环境信息:**

 - 1. 部署方式  wvp-prp + zlm都是编译部署
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 已开放
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间 最新代码

**描述错误**
当上级平台掉线时点击编辑保存重新注册时会出现注册失败的情况

**如何复现**
当上级平台掉线时点击编辑保存重新注册时会出现注册失败的情况，看代码是点击保存时会重复调用注册命令两次，第一次时返回成功，第二次时失败，抓包看第一次注册和第二次注册的callid相同，有可能是上级平台认为同一个callid只能在一次注册中使用所以返回400错误，注释掉第二次注册请求的代码或者修改代码使第一次和第二次callid不同可以注册成功

**截图**  
![微信图片_20230419084639](https://user-images.githubusercontent.com/53391873/232937528-45036258-126e-4eaa-9fec-e32a6381093e.png)
![image](https://user-images.githubusercontent.com/53391873/232937603-1c72bc34-acdd-41b0-9e17-6cb334c196b8.png)
![image](https://user-images.githubusercontent.com/53391873/232937655-0bbc5b13-816e-4cd3-8c08-315c69730ca8.png)
![image](https://user-images.githubusercontent.com/53391873/232937698-f5904535-7632-486b-b90b-956a22e59478.png)
**抓包文件**
  
**日志**

日志内容放这里， 文件的话请直接上传

**Comment by 648540858** [comment]
短时间两次注册确实不对，我测试下

**Comment by SixSix-God** [comment]
请问这个问题有解决吗

**Comment by smallxingxing** [comment]
解决了吗，我也遇到了

**Comment by 648540858** [comment]
使用新版本测试下
