### ISSUE TITLE
机器有多张网卡，一个连视频内网，一个访问外网，外网要给上位机传视频，怎么设置

### ISSUE THREAD

**Issue by chenhailong118** [648540858/wvp-GB28181-pro#821]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
画个图说明下你的结构

**Comment by 648540858** [comment]
我关闭了，你有需要再打开吧
