### ISSUE TITLE
一个设备之前可以正常点播，过了一阵点播提示“点播接口等待超时”，重启正常

### ISSUE THREAD

**Issue by caomingyu** [648540858/wvp-GB28181-pro#822]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker)
 - 2. 部署环境 centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署  否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 最新

**描述错误**
描述下您遇到的问题
服务启动后，一个相机设备之前可以正常点播，大概半天后，点播会提示“点播接口等待超时”
大概排查了下，发现调用链play接口，没有调用zlm服务，在127行就结束了
![image](https://user-images.githubusercontent.com/29753523/233539904-a34ef722-846c-4981-8da2-341b598fccfc.png)
详细分析后，发现93行返回的一直为true
![image](https://user-images.githubusercontent.com/29753523/233539958-d3e58293-b3dc-437e-bef6-e805649c1b09.png)
超时后，调用resultHolder.invokeResult（）方法，也只执行到了117行，未进行释放
![image](https://user-images.githubusercontent.com/29753523/233540020-eaf72906-8385-485d-a632-1877caa662a3.png)
卡死在这里了，只有重启服务才恢复正常

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
已修复，你试试

**Comment by caomingyu** [comment]
好的，感谢大佬！
在分支“wvp-28181-2.0”嘛？

**Comment by 648540858** [comment]
是的
