### ISSUE TITLE
接收成功，写入失败，共1条，已接收1条

### ISSUE THREAD

**Issue by yangyangdg** [648540858/wvp-GB28181-pro#825]
在点击设备列表设备的【刷新】按钮，出现【接收成功，写入失败，共1条，已接收1条】，查看日志是：
ERROR c.g.iot.vmp.storager.impl.VideoManagerStorageImpl:200 - 未处理的异常 
Duplicate entry '34020000001320000001-44010200492000000001' for key 'device_channel.device_channel_pk' 错误。
手动删除device_channel表里的记录后就不会出现该错误
**该错误是否可以避免**

**Comment by 648540858** [comment]
修复了。更新代码测试下
