### ISSUE TITLE
推流时，重启服务后，不能关流的问题能给解决下吗

### ISSUE THREAD

**Issue by longegit** [648540858/wvp-GB28181-pro#83]

**Comment by 648540858** [comment]
重启服务后原来的会话会丢失，导致无法发送bye消息，暂时没找到办法保存会话信息，所以暂时还无法解决

**Comment by longegit** [comment]
ClientTransaction是Serializable的，能保存到本地吗

**Comment by 648540858** [comment]
就这个没有办法，你可以尝试下，我之前尝试了几个办法都不理想。 在2021年04月17日 19:27，十八线程序员 写道： ClientTransaction是Serializable的，能保存到本地吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by 648540858** [comment]
优化代码已添加， 测试中发现海康设备无效，大华可用。你自己测试下

**Comment by longegit** [comment]
> 优化代码已添加， 测试中发现海康设备无效，大华可用。你自己测试下

如果使用动态端口的时候，直接调用zlmediakit的关闭接口就可以。
