### ISSUE TITLE
前端播放器空指针BUG

### ISSUE THREAD

**Issue by Qiiamx** [648540858/wvp-GB28181-pro#831]
**环境信息:**

Chrome浏览器

**描述错误**

GB28181视频打开时，浏览器控制台报空指针异常
this.$refs[this.activePlayer].play(this.getUrlByStreamInfo(streamInfo))
这里的this.$refs在页面加载后才会有播放器，但是它在页面加载时就被调用了

**修复过程**
在前端页面中的devicePlayer.vue，修改
`this.$refs[this.activePlayer].play(this.getUrlByStreamInfo(streamInfo))`
为 
`this.$nextTick(() => {
    console.log(this.$refs)
    this.$refs[this.activePlayer].play(this.getUrlByStreamInfo(streamInfo))
})`

另：服务器记得开放media.http-port端口，如果是nginx反向代理的还要处理websocket协议

**Comment by 648540858** [comment]
已修复
