### ISSUE TITLE
[BUG] 启停大量拉流代理接入的摄像头导致节点挂了

### ISSUE THREAD

**Issue by duankeke** [648540858/wvp-GB28181-pro#832]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) 
 - 2. 部署环境 centos ...
 - 3. 端口全开放
 - 4. 内网 
 - 5. http
 - 6. 海康
 - 7. 重启wvp，重启zlm，重启服务器
 - 8. 最近

**描述错误**
对接了590来个摄像头，用的都是拉流代理，然后因为服务器断电，后面来电了，重启了docker，这时候节点在线，是正常的，然后拉流代理里面的摄像头会自动启动，在启动到200来个左右，节点掉了，就不存在了

**Comment by 648540858** [comment]
好的我测试下

**Comment by 648540858** [comment]
使用新版本测试下
