### ISSUE TITLE
观看回放之后  让回放正常播放完毕之后 向摄像头关闭流的时候存在问题

### ISSUE THREAD

**Issue by github1359930721** [648540858/wvp-GB28181-pro#834]
**描述错误**
播放器正常把回放播放完成之后 会进入这个方法   
![image](https://user-images.githubusercontent.com/94958189/234828442-73576781-2ca6-44f6-aefb-6602a1ad7a57.png)
给摄像头回复停流通知之后 又给摄像头回复了个404

回复404的原因是  这个截图中的deviceId 是通道Id  不是 设备Id 导致redis没找到
![image](https://user-images.githubusercontent.com/94958189/234829010-c0a3d5b1-07b4-4780-ab78-87b1cbb23f85.png)
![image](https://user-images.githubusercontent.com/94958189/234829744-1322201f-648f-438c-8b62-9c108c6f90a6.png)

**Comment by 648540858** [comment]
使用新版本测试下
