### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SitInAndWatchSky** [648540858/wvp-GB28181-pro#835]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...     windows
 - 3. 端口开放情况     配置文件要求端口都开放
 - 4. 是否是公网部署 否
 - 5. 是否使用https   否
 - 6. 方便的话提供下使用的设备品牌或平台   工作站
 - 7. 你做过哪些尝试                                       单端口能播放
 - 8. 代码更新时间                                            2023-4-27

**描述错误**
描述下您遇到的问题
单端口播放没问题，打开30000-30500端口这个错误

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://user-images.githubusercontent.com/39214201/234856735-9a875254-d6ee-4e31-b425-5e3f768ef0aa.png)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
![image](https://user-images.githubusercontent.com/39214201/234857241-f73dfbf2-074d-452c-aafc-4a7fd01b0a65.png)

```

**Comment by 648540858** [comment]
你的zlm是什么时候下载的

**Comment by SitInAndWatchSky** [comment]
是呢，我编译新版zlm，确实没这个错误了（端口异常），但是本地播放不了。

**Comment by 648540858** [comment]
配置文件贴一下，wvp zlm
