### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by fanfanertan** [648540858/wvp-GB28181-pro#838]
**环境信息:**

 - 1. 部署方式 wvp-pro 编译 + zlm都是编译部署/
 - 2. 部署环境 ：windows
 - 3. 端口开放情况都开放：开放
 - 4. 是否是公网部署 ：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：windows11笔记本电脑，品牌小米
 - 7. 你做过哪些尝试
 - 8. 代码更新时间：刚拉的代码

**描述错误**
前端问题：webRtc无法播放

**如何复现**
操作步骤：页面上依次点击，拉流代理->播放->WebRTC(播放报错)

**截图**  
![image](https://user-images.githubusercontent.com/32301941/235115806-77c5b536-7943-450a-8e8f-450bd1e4b34c.png)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你zlm是编译的支持webrtc的吗

**Comment by fanfanertan** [comment]
我需要额外的配置吗，zlm不是本身就支持webrtc的吗

**Comment by 648540858** [comment]
你需要编译的时候开始webrtc，因为需要编译时引入额外的依赖才可以得到支持webrtc的zlm

**Comment by fanfanertan** [comment]
那我知道问题所在了，谢谢你的回答

**Comment by 648540858** [comment]
欢迎加入知识星球鼓励作者😁&nbsp;https://t.zsxq.com/0d8VAD3Dm
