### ISSUE TITLE
技术咨询, 视频播放一分多钟后无法播放, 刷新后也不行

### ISSUE THREAD

**Issue by qianchaozhao** [648540858/wvp-GB28181-pro#839]
**环境信息:**

 - 1. 部署方式    ->zlmdocker部署
 - 2. 部署环境   -> mac
 - 3. 端口开放情况
 - 4. 是否是公网部署  -> 否
 - 5. 是否使用https    -> 否
 - 6. 方便的话提供下使用的设备品牌或平台   -> 海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

视频播放一分多钟后无法播放, 刷新后也不行

**截图**  

![image](https://user-images.githubusercontent.com/33817608/236613855-252ea50a-81ec-4e4a-90e5-75bddd0c4eb8.png)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你这写的到底是怎么部署的，看不懂呀，另外你播放时必须播放窗口在前台待者

**Comment by qianchaozhao** [comment]
> 

播放的时候窗口是在前台待着呢

**Comment by qianchaozhao** [comment]
> 你这写的到底是怎么部署的，看不懂呀，另外你播放时必须播放窗口在前台待者

播放的时候窗口是在前台待着呢

**Comment by Yvan0329** [comment]
你改成tcp被动试试

**Comment by 648540858** [comment]
播放中断后无法播放，一般有两个可能的原因：
1. 播放停止或者暂停，或者后台播放自动被浏览器暂停了，导致触发了无人观看自动停止。解决办法就是加大无人观看时间配置
2. 可能下级开启了rtcp保活，但是你与下级rtcp保活失败了，解决办法可以抓包解决rtcp失败，或者使用tcp被动测试，tcp方式不需要rtcp保活。
你按照这两个思路排查吧，如果仍然无法解决，欢迎来知识星球讨论。
