### ISSUE TITLE
视频回放技术咨询

### ISSUE THREAD

**Issue by jparameter** [648540858/wvp-GB28181-pro#842]
**内容描述:**
大佬，平台使用便捷顺利，但是在视频回放时遇到问题，请求回来的视频流类型大都为直播流
.live.flv   .m3u8这种，放入播放器后就会是一小段的切片在一点点加载
想请问一下有没有考虑说这种请求能返回整体视频的   .flv  .mp4这种格式的

**Comment by 648540858** [comment]
国标的录像回放也是由设备推流上来，不是拿到一整个文件的地址，所以给出的地址只能是类似直播流这种。

**Comment by jparameter** [comment]
嗯嗯查了一下资料确实如此，万分感谢解答

**Comment by 648540858** [comment]
不客气，欢迎来知识星球支持作者。
