### ISSUE TITLE
技术咨询-大华监控-分屏监控查看超时失败

### ISSUE THREAD

**Issue by SnailShelled** [648540858/wvp-GB28181-pro#843]
**环境信息:**

 - 1. 部署方式  wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos ...
 - 3. 端口开放情况 开放
 - 4. 是否是公网部署  是腾讯云
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 大华
 - 7. 你做过哪些尝试 暂时没有
 - 8. 代码更新时间 2023-5-4

**内容描述:**
按照手册配置了大华的摄像头，平台端也显示这台设备在线，但是点击分屏监控查看该设备视频时无法查看显示延时同时查看后台服务报-处理MESSAGE请求  未获取到消息体MESSAGE
**截图**  
![image](https://user-images.githubusercontent.com/43066669/236766020-2cf1cccb-c09e-4a72-bd72-fbd607cf5b48.png)

**Comment by 648540858** [comment]
无法查看显示延时同时查看后台服务报

这里什么意思

**Comment by SnailShelled** [comment]
哦哦是这样的就是我点击分屏监控想要在平台端查看下监控视频，就一直加载然后就超时了，这时同步去看后台报错就是我截图的这个
![image](https://user-images.githubusercontent.com/43066669/236767167-06ba3fe4-3c28-4853-b5aa-5ee76efcaa33.png)

**Comment by 648540858** [comment]
1.不要使用zlm默认配置文件。这个在zlm文档有写，你注意看下。
2. 收流超时一般是sdp ip设置错误或者网络不通，你需要自行排查下，或者知识星球提问。

**Comment by SnailShelled** [comment]
好的我去试试先
