### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by zzs89117920** [648540858/wvp-GB28181-pro#849]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 5060
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间

**内容描述:**
您好，我们是自己的机房，服务部署在内网服务器上，想要开前置机的端口映射，都需要开哪些端口，走国标协议，内网测试是好使的
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
文档里描述了，翻翻文档吧

**Comment by zzs89117920** [comment]
就是没找到，才来咨询啊
