### ISSUE TITLE
拖住条技术咨询

### ISSUE THREAD

**Issue by jparameter** [648540858/wvp-GB28181-pro#851]
**内容描述:**
大佬，我在h5中做了一版使用的jessibuca播放器能播放回放并且调用拖拽进度条方法也成功
但是vue中不管使用什么播放器，在播放出回放视频流后，再调用进度条方法后画面就卡住了，播放器有流量信息  状态但就是画面卡住，换了一个hls.js也是如此
进度条方法返回 200 ok
我主观觉得可能跟vue有关，因为 同样的服务下h5是好用的，但是又很困惑换了几个播放器都不行

**Comment by 648540858** [comment]
这个不太清楚，建议你去播放器的社区提问。
