### ISSUE TITLE
海康NVR某些版本回复Catalog指令报文内通道分包后导致通道列表无法入库

### ISSUE THREAD

**Issue by aiwatcher** [648540858/wvp-GB28181-pro#853]
**环境信息:**

 - 1. 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况，无端口限制或防火墙限制
 - 4. 私网部署 
 - 5. 是否使用https  否
 - 6. 海康威视NVR 
 - 7. 你做过哪些尝试
 - 手动发起设备通道同步
 - TCPDUMP抓包，可以观察到catalog指令下发及nvr的回复，回复内容内有通道列表数据
 - 8. 代码更新时间
 - wvp-pro-2.6.7-02210754

**描述错误**
NVR在收到catalog指令后开始发送通道注册报文到WVP，如果发送的报文里是多个通道列表在一个报文里可以正常同步进系统，但是个别版本的NVR在报文里将通道列表拆分成了多个包，每个catalog回应包里只包含一个通道，这时wvp没有任何日志记录也没有正常将通道保存进系统。

**如何复现**
使用下面的报文内容可以复现

**截图**  

**抓包文件**
**日志**
```
此过程中wvp没有错误日志打印，也没有看到”通道注册
[catalog抓包.txt](https://github.com/648540858/wvp-GB28181-pro/files/11485431/catalog.txt)
“字样日志
```

**Comment by 648540858** [comment]
抓个包看看， 默认都有分包，一个一个是没有问题的

**Comment by aiwatcher** [comment]
tcpdump抓包文件：
[dump.cap.txt](https://github.com/648540858/wvp-GB28181-pro/files/11493535/dump.cap.txt)
wvp日志：
[wvp-2023-05-17.0.log.txt](https://github.com/648540858/wvp-GB28181-pro/files/11493536/wvp-2023-05-17.0.log.txt)

**Comment by 648540858** [comment]
你是把sip包直接拆了？然后一个个发过来？你可以查看下抓包文件，都已经不能识别成sip协议了，那还怎么解析。这样的协议我这边协议栈直接就给返回错误了，没办法解析。

**Comment by aiwatcher** [comment]
tcpdump -i eth1 port 5060 -w dump.cap
是用这个命令直接写的抓包文件，只是这里上传抓包文件的时候改了下文件扩展名

**Comment by 648540858** [comment]
扩展名我改回来看的，wirshark只识别成了普通的udp，协议栈直接认为是错误的数据包，直接返回了400错误，所以你得nvr的问题。建议找厂家沟通下。

**Comment by aiwatcher** [comment]
[catalog.pcap.txt](https://github.com/648540858/wvp-GB28181-pro/files/11493808/catalog.pcap.txt)
之前的抓包有问题是因为kill掉的tcpdump进程导致包不完整，这个包用wireshark测试可用了

**Comment by aiwatcher** [comment]
> 协议栈直接认为是错误的数据包，直接返回了400错误

好的，我先跟厂商沟通一下，谢谢

**Comment by aiwatcher** [comment]
> 你是把sip包直接拆了？然后一个个发过来？你可以查看下抓包文件，都已经不能识别成sip协议了，那还怎么解析。这样的协议我这边协议栈直接就给返回错误了，没办法解析。

[catalog.pcap.txt](https://github.com/648540858/wvp-GB28181-pro/files/11503472/catalog.pcap.txt)
重新抓了完整的报文，麻烦确认一下是否就是nvr回复的报文错误导致，谢谢

**Comment by aiwatcher** [comment]
![wvp回复](https://github.com/648540858/wvp-GB28181-pro/assets/84110437/acc979c0-3ad8-4f35-99d6-471e7b8c5f2e)
跟厂商核对了下报文，确认nvr回复的catalog response报文没问题，目前是不清楚wvp为什么会回复 ”untexpected token: .spvmn.cn“的400错误

**Comment by 648540858** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/18274453/d2dc802f-af06-40a3-880c-aa3256e53024)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/18274453/32c51c2e-c5b7-4054-8c85-b67c91f0c145)
wirshark无法识别为SIP协议，同样的jain-sip协议栈也无法识别，那么这肯定是错误的SIP内容，可能又是海康的什么花活吧，jain-sip都无法识别那肯定兼容不了。
