### ISSUE TITLE
为什么要单独部署一个wvp-pro-assis来做云端录像呢？

### ISSUE THREAD

**Issue by Pharaohhhha** [648540858/wvp-GB28181-pro#854]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
直接把代码写到wvp_pro中就行了吧
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
因为wvp和zlm是可以分开部署的，同时zlm是可以部署多个的，每一个zlm都会有各自的录像文件，wvp pro无法管理zlm所在服务器的录像文件，所以必须有一个服务来在zlm旁边帮它管理录像文件

**Comment by Pharaohhhha** [comment]
> 因为wvp和zlm是可以分开部署的，同时zlm是可以部署多个的，每一个zlm都会有各自的录像文件，wvp pro无法管理zlm所在服务器的录像文件，所以必须有一个服务来在zlm旁边帮它管理录像文件

可以使用跨主机共享卷把文件存到同一个地方

**Comment by Pharaohhhha** [comment]
> 因为wvp和zlm是可以分开部署的，同时zlm是可以部署多个的，每一个zlm都会有各自的录像文件，wvp pro无法管理zlm所在服务器的录像文件，所以必须有一个服务来在zlm旁边帮它管理录像文件

在docker中部署wvp-pro-assist没有ffmpeg环境呢

**Comment by 648540858** [comment]
那就不满足部署条件，无法使用了。

**Comment by Pharaohhhha** [comment]
> 那就不满足部署条件，无法使用了。

那怎么在docker中运行wvp-pro-assist项目呢，容器中无法使用主机上的ffmpeg，启动会报错

**Comment by mengxing2017** [comment]
你要用docker,可以把wvp-pro-assist打包进zlm的镜像中

**Comment by Pharaohhhha** [comment]
> 你要用docker,可以把wvp-pro-assist打包进zlm的镜像中

这个怎么操作

**Comment by mengxing2017** [comment]
问一下你们公司的运维，他们会的
