### ISSUE TITLE
[BUG] 多台机器录像回放同一设备时，第二及以后的机器无法执行pause、resume操作

### ISSUE THREAD

**Issue by pinkcao** [648540858/wvp-GB28181-pro#855]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 否
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台  无关
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 2023.5.15

**描述错误**
描述下您遇到的问题
在录像回放时，如果有大于等于两台机器同时回放同一 deviceId_channelId摄像机的录像，第一台可以暂停、恢复回放，第二台不行。
同时衍生为同一台机器快速执行多次播放时，第二次及以后的播放将无法暂停、恢复回放

**如何复现**
有明确复现步骤的问题会很容易被解决
1.机器1打开国标设备→选中设备A→录像回放→查询录像→播放录像
2.机器2打开国标设备→选中设备B→录像回放→查询录像→播放录像

应该可观察到机器2的录像暂停与恢复功能失效。服务器报错：streamId不存在

**截图**  
![QQ截图20230517110412](https://github.com/648540858/wvp-GB28181-pro/assets/36530450/d7316bed-c1d7-4ab8-8100-00efe4747ad2)

第一条录像回放的redis:
![success](https://github.com/648540858/wvp-GB28181-pro/assets/36530450/98fb0093-d8de-4294-8bf9-306a7a53f206)
![success2](https://github.com/648540858/wvp-GB28181-pro/assets/36530450/8720e8c8-adab-440d-9635-2f54fd21dcbe)

第二条录像回放的redis:
![fail](https://github.com/648540858/wvp-GB28181-pro/assets/36530450/7b9c0361-93e5-486b-87e5-3baf66d1fe7e)
![fail2](https://github.com/648540858/wvp-GB28181-pro/assets/36530450/e086c263-678f-4e57-a97b-0012475825f5)

涉及的后端代码块：
![failres](https://github.com/648540858/wvp-GB28181-pro/assets/36530450/49cadb15-4388-47c4-bcfc-cd91cba658b7)

可能出现的问题：在插入键值对时做了判断或是啥，导致了在已经有相应的deviceId_channelId在redis中时，再插入新的时streamInfo不会被一同插入，导致程序判断时inviteInfo.getStreamInfo() == null

**Comment by 648540858** [comment]
我测试下

**Comment by pinkcao** [comment]
不知道这个问题在你那里还能不能复现？时间已经有点久了，如果还有这个问题的话请尝试修改一下PlayServiceImpl.java第397行，playback获取InviteInfo时应该根据stream来获取而非deviceId和channelId的组合，不然会选取第一个，把第一个的streamInfo覆盖而导致后续的streamInfo未被更新，进而导致后续的一系列问题。理论上修改成
`InviteInfo inviteInfo = inviteStreamService.getInviteInfoByStream(InviteSessionType.PLAYBACK, streamInfo.getStream());`
就可以了

**Comment by 648540858** [comment]
可以根据最新的代码再测试下，目前应该已经修复了，多个设备打开不同时间的录像是可以分开控制，我先关了，如果测试有问题你再打开
