### ISSUE TITLE
播放不了

### ISSUE THREAD

**Issue by 16605613297** [648540858/wvp-GB28181-pro#856]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - docker pull zlmediakit/zlmediakit:master
 - docker run -id -p 1935:1935 -p 80:80 -p 443:443 -p 554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp -v /home/docker/zlmediakit/media/bin:/opt/media/bin -v /home/docker/zlmediakit/media/conf:/opt/media/conf zlmediakit/zlmediakit:master
 - wvp是直接源码编译
 - 2. 部署环境 windows / ubuntu/ centos ...
 - centos
 - 3. 端口开放情况
 - 防火墙关掉了

**内容描述:**
播放不了，收流超时。

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/97587826/cdd7e0cb-620b-4777-b997-983bdf6262a2)

**日志**
![image](https://github.com/648540858/wvp-GB28181-pro/assets/97587826/d0165d05-0c06-4a40-9cd8-81c2b06fa3c4)

**Comment by mengxing2017** [comment]
zlm没开端口，30000-30500端口没放通

**Comment by 16605613297** [comment]
就是docker启动的zlm命令有问题

**Comment by 16605613297** [comment]
docker run -id -p 1935:1935 -p 80:80 -p 443:443 -p 554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp -p 30000-30500:30000-30500   -v /home/docker/zlmediakit/media/bin:/opt/media/bin -v /home/docker/zlmediakit/media/conf:/opt/media/conf zlmediakit/zlmediakit:master
加上了启动还是超时

![image](https://github.com/648540858/wvp-GB28181-pro/assets/97587826/dbb417bb-7a95-45ed-a032-b32d3cf9cde3)

**Comment by mengxing2017** [comment]
你30000-30500udp不开，80端口也不开udp

**Comment by 16605613297** [comment]
是的

**Comment by 16605613297** [comment]
是的，解决了
