### ISSUE TITLE
移动位置信令正常，接口超时

### ISSUE THREAD

**Issue by criver31** [648540858/wvp-GB28181-pro#857]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

位置信息管理 中  获取移动位置信息接口调用超时，抓包sip返回正常，但是接口返回Timeout

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/54142345/3b2d2111-2ea9-4076-a14f-92ff2f886da9)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/54142345/c6d59aeb-b4ab-4cb7-a778-567b5d25a841)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
已修复
