### ISSUE TITLE
技术咨询，只能同步部分通道

### ISSUE THREAD

**Issue by Gona9z** [648540858/wvp-GB28181-pro#858]
**环境信息:**

 - 1. 部署方式 wvp-pro 和 zlm 都是源码编译
 - 2. 部署环境 centos 7.9
 - 3. 端口开放情况 全公网端口开放
 - 4. 是否是公网部署  是
 - 5. 是否使用https  否
 - 6. 方便的话提供下使用的设备品牌或平台 海康摄像头国标接入

**内容描述:**
1、我在公网Centos7.9部署了wvp和zlm，别人的平台通过国标推送信息给我。
2、我这边能收到设备信息，但是通道只能收到部分通道，共140个通道，慢慢的只能同步到大概10个通道后就不会同步了。
3、手工点击同步的话，只会显示同步第一个，然后就失败了。

**截图**  
<img width="617" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/13264284/3073e236-8c79-4e88-88a0-d6df49c84b5f">

请问可以从哪个方向考虑解决这个问题

**Comment by Gona9z** [comment]
抓包的话，会发现有部分疑似乱码的问题，咨询对方，说是wvp不支持报文切片导致，不知道是否是该原因

**Comment by Gona9z** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/13264284/eb767770-91a5-4546-b2d8-f76b607b58bc)

**Comment by aiwatcher** [comment]
有没tcpdump完整抓包文件传上来，看看是否跟我遇到的问题类似 [https://github.com/648540858/wvp-GB28181-pro/issues/853](url)

**Comment by Gona9z** [comment]
[catalog-ubuntu.pcap.txt](https://github.com/648540858/wvp-GB28181-pro/files/11506007/catalog-ubuntu.pcap.txt)
@aiwatcher  看起来跟你的问题比较类似，这是完整的抓包文件，我发现相同的代码，部署在2台电脑，国标视频源那边都是同一个设备注册到这2台服务器，只有一台电脑会出现这个情况

**Comment by Gona9z** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/13264284/6cc1e6b5-183a-470b-a63f-717c086a0de0)
最新的发现是消息体中有2个字符的ascii码编码错误，错误的位置在消息体的中间，应该不是分包的问题

**Comment by 648540858** [comment]
他这种错误会导致xml都无法解析的，看看你的下级怎么说吧
