### ISSUE TITLE
[新功能] wvp-pro-assist 添加https支持

### ISSUE THREAD

**Issue by YTed** [648540858/wvp-GB28181-pro#859]
**环境信息:**

 - 部署方式  wvp-pro + wvp-pro-assist + zlm都是编译部署
 - 部署环境 centos 7
 - wvp-pro/wvp-pro-assist/zlm 均使用 https
 - 代码更新时间 commit: 512b0cc8f5606f08b93afb154f0cffd92b93cac8

**描述错误**
wvp-pro-assist 配置为使用 ssl 的时候，wvp-pro 的 record_proxy 仍然尝试使用 http 转发请求，导致请求失败

**如何复现**
配置 wvp-pro 和 wvp-pro-assist 均为 https，访问 wvp-pro 的 record_proxy 接口和对应的 wvp-pro-assist 接口（均用 https 访问），wvp-pro 的 record_proxy 接口访问失败，提示不能使用 TLS，wvp-pro-assist 访问成功正常返回数据。

**Comment by 648540858** [comment]
assist目前不支持https

**Comment by lunasaw** [comment]
能分享下assist配置吗，我这边 wvp-pro-assist 代理跨域，wvp访问正常是什么原因呀

**Comment by 648540858** [comment]
先关了，大部分时候不需要assist了
