### ISSUE TITLE
作为开发的个体，其实没有什么真实的测试环境，比如视频源，建议视频源添加中支持本地视频文件

### ISSUE THREAD

**Issue by callinglove** [648540858/wvp-GB28181-pro#863]
**项目的详细需求**
在视频设备添加选项中，支持本地视频文件的添加

**这样的实现什么作用**
便于个体开发人员，或者缺乏视频源设备的人员便于开发测试

**Comment by mengxing2017** [comment]
网上不是有模拟器？

**Comment by mengxing2017** [comment]
你也可以部署两套wvp去测试，一个做上级，一个做下级，下级拉流转gb就行了
