### ISSUE TITLE
通道推送与接收管理

### ISSUE THREAD

**Issue by wsgzjx** [648540858/wvp-GB28181-pro#865]
作为上级时不希望接收某些通道，可选择是否接收；
作为下级时不希望推送某些通道，可选择是否推送；

**Comment by mengxing2017** [comment]
作为下级时不希望推送某些通道，可选择是否推送；  这个可以选择指定的通道
作为上级时不希望接收某些通道，可选择是否接收；  这个视而不见不就完了
