### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by FeiYoungP2P** [648540858/wvp-GB28181-pro#867]
**环境信息:**

 - 1. 部署方式 wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境  centos ...
 - 3. 端口开放情况 全部开放
 - 4. 是否是公网部署  否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台  
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 5月25号，最新版本代码

**内容描述:**
wvp在国标级联中添加上级平台，显示上级平台离线，重启后抓包，发现没有发送SIP注册消息，只有正常启动的日志。这个上级平台是我自己开发的一个信令服务，不是wvp官方的服务，不知道自己开发的信息服务作为上级，能否作为上级平台接入wvp
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
信息太少，看不出啥问题
