### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by gfxh1** [648540858/wvp-GB28181-pro#870]
**环境信息:**

 - 1. 部署方式 wvp-pro+ zlm都是编译部署/
 - 2. 部署环境 windows
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
级联时，双网卡怎么处理，内外网怎么处理
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
级联时只支持单网卡
