### ISSUE TITLE
open Invalid URL port: "0" BUG

### ISSUE THREAD

**Issue by xianghu1314** [648540858/wvp-GB28181-pro#874]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/27937545/11001482-6240-46f0-b374-8e3c1bc872f2)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/27937545/019ea25f-525e-404c-a942-d4f75d2a6322)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/27937545/fa2e3c76-86ee-4651-b672-06d24a353fd2)
media server port 获取到的端口为0？？？

**Comment by xianghu1314** [comment]
解决了，配置有问题

**Comment by xianghu1314** [comment]
mybatis:
  configuration:
    map-underscore-to-camel-case: true

**Comment by 648540858** [comment]
最新代码已经不需要配置了
