### ISSUE TITLE
本地推流nvr属于动态公网ip环境，每当ip变动，设备离线，需要手动重启获取到新ip才能上线BUG

### ISSUE THREAD

**Issue by Wss-20170929** [648540858/wvp-GB28181-pro#877]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
本地动态公网ip环境，每当ip变动时，设备就会离线 ，重启设备或者网络设备，获取到正确的ip地址后才能正常在线，

**如何复现**
安装环境测试正常 ，等待动态ip变化，查看nvr的ip变化

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by mengxing2017** [comment]
这个看起来有点像设备的问题，设备离线是不是不自动重新注册？抓包分析一下，是设备不注册还是wvp的redis缓存问题，另外wvp是部署在静态ip上吧，wvp是不支持动态ip的

**Comment by Wss-20170929** [comment]
wvp和zlm分离部署，全部固定IP环境，不确定是设备不主动注册还是缓存问题，遇到多台设备出现如此问题 。明天抓包看看 。

**Comment by mengxing2017** [comment]
建议wvp和nvr两端都抓包分析一下排查一下中间网络问题
