### ISSUE TITLE
通道页面按下蓝色返回键报错

### ISSUE THREAD

**Issue by longegit** [648540858/wvp-GB28181-pro#88]
GET http://localhost:8080/debug/api/device/query/sub_channels/undefined/undefined/channels?page=NaN&count=NaN&query=&online=&channelType=

还有这个错误 GET http://localhost:8070/api/emit?browserId=b7de6a9e28c620517b2eb3019b79937b 405

**Comment by 648540858** [comment]
第一个错误已经修复并提交，第二个不是问题，只是无法在调试环境下使用，你打包后就会发现他是正常的了
