### ISSUE TITLE
视频播放时，报收流超时，会是什么原因呢

### ISSUE THREAD

**Issue by Xjccheng** [648540858/wvp-GB28181-pro#880]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/135321090/a17a769a-6f45-4b35-a584-860776493ff8)

报这样的错：[点播超时] 收流超时 deviceId: 34020000001110000001, channelId: 34020000001320000264，端口：10000, SSRC: 0200004966

**Comment by mengxing2017** [comment]
端口开了吗？sdp-ip设置对吗

**Comment by Xjccheng** [comment]
sdp-ip应该是nvr的地址是吗，端口的话，防火墙关了应该是没问题的了吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月3日(星期六) 下午3:25
收件人: "648540858/wvp-GB28181-pro";
抄送: "Author";
主题: Re: [648540858/wvp-GB28181-pro] 视频播放时，报收流超时，会是什么原因呢 (Issue #880)





 
端口开了吗？sdp-ip设置对吗
 
&mdash;

**Comment by mengxing2017** [comment]
nvr能访问的地址

**Comment by Xjccheng** [comment]
地址是这样配置的，能指点一下不，大佬


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月3日(星期六) 下午3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro] 视频播放时，报收流超时，会是什么原因呢 (Issue #880)





 
nvr能访问的地址

**Comment by Xjccheng** [comment]
地址是这样配置的，能指点一下不，大佬
三个IP之间是可以相互ping通的，192.168.220.131是虚拟机


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "648540858/wvp-GB28181-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月3日(星期六) 下午3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [648540858/wvp-GB28181-pro] 视频播放时，报收流超时，会是什么原因呢 (Issue #880)





 
nvr能访问的地址

**Comment by mengxing2017** [comment]
192.168.0.120跟 192.168.220.131通的？192.168.0.120能ping通192.168.220.131？不是 192.168.220.131ping192.168.0.120哦

**Comment by Xjccheng** [comment]
通了，感谢，最后我换了IP在同一网段，并且关了SSRC校验之后才通的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月3日(星期六) 下午4:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [648540858/wvp-GB28181-pro] 视频播放时，报收流超时，会是什么原因呢 (Issue #880)





 
192.168.0.120跟 192.168.220.131通的？192.168.0.120能ping通192.168.220.131？不是 192.168.220.131ping192.168.0.120哦

**Comment by xue9957** [comment]
> 

想问下怎么关闭SSRC校验的？

**Comment by xue9957** [comment]
> 通了，感谢，最后我换了IP在同一网段，并且关了SSRC校验之后才通的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年6月3日(星期六) 下午4:20 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [648540858/wvp-GB28181-pro] 视频播放时，报收流超时，会是什么原因呢 (Issue #880) 192.168.0.120跟 192.168.220.131通的？192.168.0.120能ping通192.168.220.131？不是 192.168.220.131ping192.168.0.120哦 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

想问下是怎么关闭SSRC检验的？

**Comment by mengxing2017** [comment]
界面上关闭就行了
