### ISSUE TITLE
BUG 最新代码添加国标级联设备添加目录SQL错误

### ISSUE THREAD

**Issue by yand9807** [648540858/wvp-GB28181-pro#881]
**描述错误**
国标级联->选择通道->添加目录，后台接口报错，insert语句找不到platform_catalog表，新版代码使用的表名换成了wvp_platform_catalog,但Dao层中的的插入语句使用的仍旧表名

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/53848372/fea2fbb4-98dc-40c5-ae02-6a2acf3918dd)

**Comment by 648540858** [comment]
已修复
