### ISSUE TITLE
rtmp推流成功 ，web页面状态栏不显示正确在线路数，全部显示不在线。版本2.6.7	 GIT版本 2d2832d

### ISSUE THREAD

**Issue by Wss-20170929** [648540858/wvp-GB28181-pro#883]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
更新最新代码测试了，不在旧代码上排查问题
