### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by SuXiaoKang** [648540858/wvp-GB28181-pro#886]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
设备插上电，可以看20秒。之后就一直在线，但是点击播放就是点播超时。怎么办？海康摄像头
**截图**  

**抓包文件**
  
![1686212100832](https://github.com/648540858/wvp-GB28181-pro/assets/47264278/306b754a-dedf-4da2-9274-a1640b58de94)

**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
抓包截图只能看到是设备不再回复消息了
