### ISSUE TITLE
点播收流失败

### ISSUE THREAD

**Issue by boboforgithub** [648540858/wvp-GB28181-pro#888]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/95910741/e5e4f890-565e-4f53-8bb9-2876b2cc1a1e)

**Comment by boboforgithub** [comment]
wvp和ZKL都在华为云服务器，设备是海康球机，无线拨号上网模式

**Comment by yx800** [comment]
设置被动模式吧，摄像头是设置成被动模式。
