### ISSUE TITLE
[BUG] 结束点播后，sip bye没有发送

### ISSUE THREAD

**Issue by yx800** [648540858/wvp-GB28181-pro#890]
**环境信息:**

 1.  wvp-pro + zlm都是编译部署/ 
 2. 部署环境 
 debian10.7
 3. 端口开放情况 
 都开了
 4. 是否是公网部署  
 公网
 5. 是否使用https  
 否
 6. 方便的话提供下使用的设备品牌或平台 ，
 tplink

7. 你做过哪些尝试
sngrep抓信令
8. 代码更新时间
GIT最后提交时间： 20230610 构建版本： 2.6.9
**描述错误**
sip bye没有发送

2023-06-11 18:52:40.712 ERROR --- ZLMHttpHookListener : [无人观看]点播， 发送BYE失败 缓存事务信息未找到，device：44010200492001000001 channel: 34020000001320000001 ,stream: 44010200492001000001_34020000

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/115491862/d892cedd-4ac7-46f8-abed-514dd76a0085)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/115491862/a4c55e5b-4660-487d-916b-5b193c6b2de4)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/115491862/0fe36150-590b-4294-950e-17a237b97cbe)

**Comment by 648540858** [comment]
中间重启过服务吗

**Comment by 648540858** [comment]
我测试了大华，海康的设备，测试接口点播，自动点播，级联点播三钟方式都没有出现这个问题，你这边可否提供详细的复显步骤
