### ISSUE TITLE
调用接口跨域问题

### ISSUE THREAD

**Issue by zgxsm** [648540858/wvp-GB28181-pro#897]
**环境信息:**

 - 1. 部署方式 
    编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 
    centos 
 - 3. 端口开放情况 内网环境全部开放端口测试
 - 4. 是否是公网部署 
 否
 - 5. 是否使用https 
 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试 
 尝试修改配置文件、直接修改WebSecurityConfig、在controller设置@CrossOrigin(origins = "*")
 - 8. 代码更新时间
 origin/wvp-28181-2.0（ e68eb85 去除多余日志）

**描述错误**
正常部署启动WVP+ZLM后调用WVP api接口获取播放地址出现跨域问题，尝试如下方式解决：
1、修改yaml跨域配置（无法解决）
user-settings:
  interface-authentication-excludes:
    - /api/proxy/**
    - /api/push/**
  allowed-origins:
    - http://ip:8090/
    - http://ip:8090
    - http://127.0.0.1
    - http://127.0.0.1/
2、修改WebSecurityConfig（无法解决）
corsConfiguration.setAllowedOrigins(Arrays.asList("*"));
3、controller添加允许跨域（解决问题）
@CrossOrigin(origins = "*")
public class StreamProxyController {

**如何复现**
A服务器部署WVP+ZLM，本地调用/api/push/getPlayUrl等wvp接口

**截图**  

**抓包文件**
  
**日志**
Access to XMLHttpRequest at 'http://172.16.120.201:8081/api/push/getPlayUrl?mediaServerId=xxx&app=140&stream=140' from origin 'http://172.16.120.26:8090' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你的前端部署位置是哪里，allowed-origins:里添加访问前端服务的地址
