### ISSUE TITLE
使用OBS推流，rtmp，报鉴权失败，解析参数后面多了个斜杠

### ISSUE THREAD

**Issue by mengdengke** [648540858/wvp-GB28181-pro#899]
**环境信息:**

 - 1. 部署方式  wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu

**描述错误**
使用OBS推流，rtmp，报鉴权失败

**如何复现**

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/73207641/71a9ca2d-2e54-4947-933a-0fd9cf0c6ba7)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/73207641/1c9417f3-9ab9-492d-8193-78e646b791a9)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/73207641/9510e7bf-af3c-47dc-97ff-c47a3ee3e06d)

请问该如何处理

**Comment by Alysondao** [comment]
![image](https://github.com/user-attachments/assets/59aa9924-daca-4ceb-a579-46fc8b394e39)
解决了，obs会自己在后面加一个/，所以就拆成这样写
