### ISSUE TITLE
设备录像无法查看

### ISSUE THREAD

**Issue by xuanhuangkeji** [648540858/wvp-GB28181-pro#9]
第一次点设备录像，会显示查询到11项，已获取2项，共11项，已获取2项，共11项，等待后续包。。。等待后续包
就什么都没有了，后边不管是重新点还是切换日期都会变成是执行方法调用超时
另外，通道获取一直不正确，摄像头也是获取出来的两个，redis清理依旧是
[wvp.log](https://github.com/648540858/wvp-GB28181-pro/files/5687097/wvp.log)

**Comment by 648540858** [comment]
好的我看下

**Comment by 648540858** [comment]
优化了录像的超时时间，你测试下

**Comment by showhand** [comment]
这个跟超时时间没有关系,是因为录像消息是多次返回的,消息由MessageRequestProcessor处理,多次返回由不同的线程处理。
不同的线程处理时,得到的redis中的数据可能不一致. 我这边加了个private static final Lock lock = new ReentrantLock();来处理,可以解决这个问题。也可以使用redission针对redis使用分布式锁

**Comment by showhand** [comment]
看到新版本改了,可以正常显示了
