### ISSUE TITLE
使用拉流代理，无法播放转协议之后的rtmp流

### ISSUE THREAD

**Issue by bobin168** [648540858/wvp-GB28181-pro#900]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
通过拉流代理添加了rtsp流，这个rtsp流用vlc能正常播放的，但是复制资源地址里面的rtmp地址放到vlc就无法播放，无法连接。在运行zlmediakit的服务器上也配置了nginx包括nginx-rtmp-module模块。

**Comment by 648540858** [comment]
是不是h265的视频，rtmp不支持h265

**Comment by bobin168** [comment]
> 

是h264流的视频

**Comment by bobin168** [comment]
> 是不是h265的视频，rtmp不支持h265

是h264流的视频

**Comment by bobin168** [comment]
> 音频什么格式
音频是aac格式的

**Comment by 648540858** [comment]
用ffplay播放试试，看看具体的报错
