### ISSUE TITLE
BUG-华为摄像机（型号：D2120-AEI-P）选择TCP被动拉流方式无法播放视频

### ISSUE THREAD

**Issue by zhengxx6612** [648540858/wvp-GB28181-pro#902]
**环境信息:**

 - 1. 部署方式 ：wvp-pro + zlm都是编译部署
 - 2. 部署环境 
 - Linux server4 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - 3. 端口开放情况：关闭了防火墙
 - 4. 是否是公网部署 ：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：华为相机（D2120-AEI-P）
 - 7. 你做过哪些尝试：尝试过大华、海康相机TCP被动拉流方式都可以播放
 - 8. 代码更新时间：最新版

**描述错误**
描述下您遇到的问题
华为摄像机（型号：D2120-AEI-P）选择TCP被动拉流方式无法播放视频
**如何复现**
有明确复现步骤的问题会很容易被解决
将华为相机通过GB28181接入，通过wvp页面将拉流方式切换为TCP被动拉流方式，进入通道，点击播放
**截图**  
![1687141202864](https://github.com/648540858/wvp-GB28181-pro/assets/137019492/03b39f46-61e7-408d-8fe3-9023aecfeaa3)

**抓包文件**
  
[scap.zip](https://github.com/648540858/wvp-GB28181-pro/files/11783415/scap.zip)

**日志**
```message.zip为华为相机日志
日志内容放这里， 文件的话请直接上传
```
[message.zip](https://github.com/648540858/wvp-GB28181-pro/files/11783607/message.zip)
[wvp.zip](https://github.com/648540858/wvp-GB28181-pro/files/11783692/wvp.zip)

**Comment by 648540858** [comment]
设备不支持，我看抓包中没有设备发起的tcp连接

**Comment by zhengxx6612** [comment]
> 设备不支持，我看抓包中没有设备发起的tcp连接

华为相机日志中存在错误，有没有可能是sdp命令需要调整？

**Comment by 648540858** [comment]
建议你咨询华为客服，目前在这个sdp只有华为报错了

**Comment by zhengxx6612** [comment]
> 建议你咨询华为客服，目前在这个sdp只有华为报错了

好的，谢谢
