### ISSUE TITLE
[BUG]分屏控制和电子地图无法获取通道

### ISSUE THREAD

**Issue by oldolddu** [648540858/wvp-GB28181-pro#907]
**环境信息:**

 - 1. 部署方式： Ubuntu编译部署，没使用docker
 - 2. 部署环境 ： Ubuntu
 - 3. 端口开放情况 ：全开
 - 4. 是否是公网部署 ： 是
 - 5. 是否使用https： 否
 - 6. 方便的话提供下使用的设备品牌或平台： 海康枪机
 - 7. 你做过哪些尝试 ：使用接口调试可以正常获取到list
 - 8. 代码更新时间 : 20230621

**描述错误**
在web界面的分屏控制和电子地图中点击设备无法出现通道
url:http://ip:18080/api/device/query/tree/34020000001320000012?page=1&count=100&parentId=34020000001320000012&onlyCatalog=false
![Snipaste_2023-06-23_18-19-14](https://github.com/648540858/wvp-GB28181-pro/assets/66262260/a095fe9b-6557-408a-8b5b-86fcdfb0fa58)
上面的url是点击设备后发的get请求，url里的parentid和MySQL库里的不一致，导致返回的list[]里面没有数据，就无法加载出来通道
**如何复现**
拉取0621的代码在Ubuntu上，添加设备应该就可以复现，我完全安装了5次，都复现了

**截图**  
![Snipaste_2023-06-23_17-07-05](https://github.com/648540858/wvp-GB28181-pro/assets/66262260/cbbad96d-bc2c-4627-aa21-b18b11e7e201)
![Snipaste_2023-06-23_17-08-12](https://github.com/648540858/wvp-GB28181-pro/assets/66262260/b5982312-1ceb-4259-a830-d0d4e18b7df8)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by oldolddu** [comment]
![Snipaste_2023-06-26_19-03-05](https://github.com/648540858/wvp-GB28181-pro/assets/66262260/d3c40dcc-9c1c-4799-ace4-aa90ae35f655)
解决方法，将这一句sql删了，我猜测是传参的时候有点小问题，这种删除sql的解决方法直接在查表的时候把问题过滤掉就好了

**Comment by 648540858** [comment]
已修复
