### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by Dadong-88** [648540858/wvp-GB28181-pro#909]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
mp4_max_second=3600    这个录像分片  不起作用  是什么原因    保存的都是24s的录像
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/65882385/38fbd4d9-9da6-4d68-b24d-e1ae02f46c2e)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
这是什么产生的录像

**Comment by Dadong-88** [comment]
解决啦  感谢
