### ISSUE TITLE
大华NVR国标注册成功了但是还是继续在刷注册请求

### ISSUE THREAD

**Issue by yu1183688986** [648540858/wvp-GB28181-pro#91]
导致一直刷下面的日志输出：
A1: 340xxxx0001110000001:340xxx0000:xxxxx
A2: REGISTER:sip:xxxx@xxx
HA1: xxx
HA2: xxxx
nonce: d1a4fa656d9aad663c55cf2a4c048c0f
nc: -00000001
cnonce: null
qop: null
KD: xxxx:xxxxf:xxx
mdString: xxxxx
response: xxxxxx

**Comment by 648540858** [comment]
更新下代码，确定注册来自同一台设备

**Comment by yu1183688986** [comment]
> 更新下代码，确定注册来自同一台设备

是同一台设备，测试时候就用了一台设备。

**Comment by 648540858** [comment]
看一下你设备设置的注册间隔，注册有效期这个值

**Comment by yu1183688986** [comment]
> 看一下你设备设置的注册间隔，注册有效期这个值

有效期3600s，心跳周期60，注册间隔么找到这个配置

**Comment by 648540858** [comment]
wvp的日志贴一下，用
```
```
包一下

**Comment by yu1183688986** [comment]
> wvp的日志贴一下，用
> 
> 包一下
`A1: 34020000001110000001:3402000000:87fee8c
A2: REGISTER:sip:34020000002000000001@3402000000
HA1: 3d51a078af6120129645c6460a269b23
HA2: 95fced343cf76247d3e2102931f17507
nonce: d1a4fa656d9aad663c55cf2a4c048c0f
nc: -00000001
cnonce: null
qop: null
KD: 3d51a078af6120129645c6460a269b23:d1a4fa656d9aad663c55cf2a4c048c0f:95fced343cf76247d3e2102931f17507
mdString: 508deb8793d6e118249dd1e1aa055e93
response: bbdf8cd86b6d24669bbdc7413b03998d
A1: 34020000001110000001:3402000000:87fee8c
A2: REGISTER:sip:34020000002000000001@3402000000
HA1: 3d51a078af6120129645c6460a269b23
HA2: 95fced343cf76247d3e2102931f17507
nonce: e23e25e7788ceabdb6d4a13adabb2d13
nc: -00000001
cnonce: null
qop: null
KD: 3d51a078af6120129645c6460a269b23:e23e25e7788ceabdb6d4a13adabb2d13:95fced343cf76247d3e2102931f17507
mdString: 4c3af412fdba356cb458a2051760fdce
response: e6dd70832f06c2ccf3bbd06425d575b1
A1: 34020000001110000001:3402000000:87fee8c
A2: REGISTER:sip:34020000002000000001@3402000000
HA1: 3d51a078af6120129645c6460a269b23
HA2: 95fced343cf76247d3e2102931f17507
nonce: c9a93faa1abde10ba8ed614bf1273538
nc: -00000001
cnonce: null
qop: null
KD: 3d51a078af6120129645c6460a269b23:c9a93faa1abde10ba8ed614bf1273538:95fced343cf76247d3e2102931f17507
mdString: 53d082d82c9c4261ef6274f2e14c3a27
response: ca7caa649768d129e759fbeebc6647e8`

**Comment by 648540858** [comment]
还是抓个包吧

**Comment by yu1183688986** [comment]
> 还是抓个包吧

谢谢，查到问题了 是我们这边自己的原因，万分感谢！
