### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by bianhw1208** [648540858/wvp-GB28181-pro#910]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows 
 - 3. 端口开放情况，都开放了
 - 4. 是公网部署 
 - 5. 否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**上级invite，下级回复181是啥原因。怎么处理这个问题呢。

**截图**  
![1688009255554](https://github.com/648540858/wvp-GB28181-pro/assets/50901292/25dc2005-2cb2-46fe-a620-3a7fd461609f)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
100相关的状态码只是表示在尝试，这不是问题
