### ISSUE TITLE
添加拉流代理后，播放停用后会自动删除

### ISSUE THREAD

**Issue by orcfnjmlns908** [648540858/wvp-GB28181-pro#913]
**环境信息:**

 - 1. 部署方式  咸鱼哥的docker-compose
 - 2. 部署环境 ubuntu 22.04
 - 3. 端口开放情况 wvp:http sip
 - 4. 是否是公网部署  否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试   WEB UI直接操作
 - 8. 代码更新时间   wvp-28181-2.0  fec69c714c632eaed01f77cb419d1d6a02e273ea

**描述错误**
1、通过WEB UI上的【拉流代理】，选择【添加代理】，表单内容填写【直接代理】、无人观看时【停用】而不是【移除】、默认不启动，不添加音频
2、添加完成后，选择启动，过多一阵子会自动删除拉流代理（旧版本不会）
3、检查过数据库表【wvp_stream_proxy】，字段【enable_remove_none_reader】为0【enable_disable_none_reader】均为1
**如何复现**
通过WEB操作，每一次都能复现

**截图**  

<img width="984" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/126919071/d77a7581-842b-4d13-9848-d7734523ddd4">

  
**日志**
```
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5a23d1c8] was not registered for synchronization because synchronization is not active
JDBC Connection [HikariProxyConnection@282152583 wrapping com.mysql.cj.jdbc.ConnectionImpl@778b09e9] will not be managed by Spring
==>  Preparing: DELETE FROM wvp_stream_proxy WHERE app=? AND stream=?
==> Parameters: test(String), 555(String)
<==    Updates: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5a23d1c8]
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2df7adeb] was not registered for synchronization because synchronization is not active
JDBC Connection [HikariProxyConnection@1763607564 wrapping com.mysql.cj.jdbc.ConnectionImpl@778b09e9] will not be managed by Spring
==>  Preparing: DELETE FROM wvp_gb_stream WHERE app=? AND stream=?
==> Parameters: test(String), 555(String)
<==    Updates: 0
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2df7adeb]
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@ac6958a] was not registered for synchronization because synchronization is not active
JDBC Connection [HikariProxyConnection@441379276 wrapping com.mysql.cj.jdbc.ConnectionImpl@778b09e9] will not be managed by Spring
==>  Preparing: DELETE from wvp_platform_gb_stream WHERE gb_stream_id = (select gb_stream_id from wvp_gb_stream where app=? AND stream=?)
==> Parameters: test(String), 555(String)
<==    Updates: 0

```

**Comment by 648540858** [comment]
已修复

**Comment by orcfnjmlns908** [comment]
> 已修复

您好，问题依旧，我拉取的版本是：01bc6c857e49597df0f1b2e8c5d482786db3a475

<img width="1407" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/126919071/febfc98d-0928-42c0-b329-93151e0f4f89">

<img width="690" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/126919071/8591956e-2726-440f-bfa4-0252ad205318">
