### ISSUE TITLE
BUG 三级级联后，最上级无法查看最下级平台的设备录像

### ISSUE THREAD

**Issue by DavidSche** [648540858/wvp-GB28181-pro#914]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境   centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 私有部署
 - 5. 是否使用https
 - 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
搭建 1（wvp 10.10.10.10）、2（wvp 10.10.10.11）、3（wvp 10.10.10.12） 三级级联平台，1 推送给2，2推送给3 ；在3的wvp上可以看见设备1，可以看到实时录像，但无法查看设备录像，列表为空，无法查看及下载设备录像。

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
2平台可以看到录像列表吗

**Comment by DavidSche** [comment]
2平台可以看到1平台发送上来的设备列表和视频回放，但3平台上无法看到1级联推送2平台，2平台级联推送到3平台设备录像列表，点页面后，2平台和1平台后端日志没有消息内容输出。知道提示页面超时，timeout.

**Comment by DavidSche** [comment]
这是2平台上的设备列表的录像回放
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/7c511849-e646-40ae-a9c9-9b82ec3771f7)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/892357fe-d029-434a-a50a-e30740b5c698)
2 平台的日志 
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/b71bbf00-46a3-4464-ba5a-78d9645f4765)

这是3平台上看到的信息
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/5a062d5f-72c7-443c-9971-b5e1998e49ff)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/902c365d-6548-40e1-aee7-48c27769489c)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/87666c31-73a7-448e-b890-d6f35448d08a)

**Comment by 648540858** [comment]
好的，我测试下

**Comment by DavidSche** [comment]
你好，测试的结果如何？支持吗？@648540858   谢谢 ！！！

**Comment by DavidSche** [comment]
是不是没有实现这个功能级联的级联支持？
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/e8f49ba4-c571-4ab4-bd63-dfd336f8b12c)

**Comment by DavidSche** [comment]
@648540858  大佬测试的有结果吗？支持吗？

**Comment by 648540858** [comment]
还没时间

**Comment by DavidSche** [comment]
2平台在解析收到的消息时，获取的设备ID不一致

![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/040ba452-d9e7-41e2-9c61-c318e164e6fb)

获取的消息内容为
ESSAGE sip:37010100002000000026@192.168.161.26:5060 SIP/2.0
Call-ID: 4b95a6bc7b7adbffe4f04a106a5cbb15@192.168.151.25
CSeq: 3697 MESSAGE
From: <sip:370101000020000000025@3701010000>;tag=aa40cc5b094e4cecad9e8c941263bbcd
To: <sip:37010100002000000026@192.168.161.26:5060>
Via: SIP/2.0/UDP 192.168.151.25:5060;branch=z9hG4bK6820802831;rport
Max-Forwards: 70
User-Agent: WVP-Pro v2.6.9.20230707
Content-Type: Application/MANSCDP+xml
Content-Length: 700

<?xml version="1.0" encoding="GB2312"?>
<Response>
<CmdType>RecordInfo</CmdType>
<SN>643130</SN>
<DeviceID>37010100001180000001</DeviceID>
<SumNum>10</SumNum>
<RecordList Num="2">
<Item>
<DeviceID>34020000001310000002</DeviceID>
<Name>DH-IVSS708</Name>
<StartTime>2023-07-12T00:00:00</StartTime>
<EndTime>2023-07-12T00:00:01</EndTime>
<Secrecy>0</Secrecy>
<Type>time</Type>
<FileSize>706475761</FileSize>
</Item>
<Item>
<DeviceID>34020000001310000002</DeviceID>
<Name>DH-IVSS708</Name>
<StartTime>2023-07-12T00:00:01</StartTime>
<EndTime>2023-07-12T02:08:50</EndTime>
<Secrecy>0</Secrecy>
<Type>time</Type>
<FileSize>4127863204</FileSize>
</Item>
</RecordList>
</Response>

消息中的设备ID 不一致

是否应该使用 34020000001310000002（2平台ID） 触发消息，否则2平台上的监听不起作用

**Comment by DavidSche** [comment]
进一步跟踪发现
监听事件时

在三级平台中设备ID是不一样的，一样的是通道ID
1平台
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/8127f40d-bf6c-4976-becf-2542719e7ea6)
2平台
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/dae43ff6-709b-4469-ae2d-0f581ff014d1)
3平台
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/e9a9cfeb-b4c4-453d-b947-985a8b4aaac8)

接收响应的代码将设备ID和通道ID都写入

![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/52a1021a-539f-4cb4-9477-6bcfcd38fbea)

响应接收到向上级发送SIP请求的处理只写入设备ID 
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/81ce6d80-6a48-442a-8c8b-73e581172d22)

请 @648540858 大佬 帮忙看看，这个地方是不是应该获取  recordInfo.getChannelId()
