### ISSUE TITLE
网络环境咨询

### ISSUE THREAD

**Issue by tank520** [648540858/wvp-GB28181-pro#915]
摄像头：内网
wvp + ZLMediakit：外网
这种环境是不是不支持摄像头视频播放，ZLMedia日志连接摄像头内网ip，无法连接。

**Comment by 648540858** [comment]
wvp配置下sdpIP为公网IP，stream ip 为公网IP

**Comment by tank520** [comment]
有个疑问这个stream ip指的是摄像头吧，因为目前局域网的摄像头注册上来后，无法播放视频
