### ISSUE TITLE
[设备兼容] catalog请求时content-length为0，导致消息内容无法读取

### ISSUE THREAD

**Issue by 1207702931** [648540858/wvp-GB28181-pro#920]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows
 - 3. 端口开放情况: 全部开放
 - 4. 是否是公网部署 ：本地，公网
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试，修改基本配置文件
 - 8. 代码更新时间，最新代码

**描述错误**
本地部署，设备注册到平台，在线状态正常，通道数量正常，视频显示正常，云台控制值有放大缩小可用
公网部署，设备注册到平台，在线状态正常，通道数量为0，视频显示无。

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
<img width="1128" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/49967413/cccd6b6e-13c1-4c3e-aff7-04112a1c7b89">
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 1207702931** [comment]
liveGBS 平台，同服务器，公网部署，一切正常，说明端口，网络没问题？

**Comment by 648540858** [comment]
> liveGBS 平台，同服务器，公网部署，一切正常，说明端口，网络没问题？

你能注册，那么端口我觉得没问题。刷新通道，抓个包看下对方发送catalog目录内容

**Comment by 648540858** [comment]
看日志是对方发送的信令中关键字段content-length为0，这个为0，协议栈就会认为没有消息体，上层业务就无法读取这个信息内容了

**Comment by 1207702931** [comment]
感觉有点没有头绪，报文有摄像头传过来的，如果不正常，本地的WVP服务应该也不正常，liveGBS 也不会正常；
但奇怪的是，本地相同的WVP代码部署就没问题，公网服务端liveGBS 也没问题。
能提供下排查思路吗？

**Comment by 648540858** [comment]
消息要经过一层云服务器厂商的网络，所以如果设备发的没问题，到wvp就不一样了，那么就需要找云服务器厂商沟通一下了

**Comment by 1207702931** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/49967413/e938037d-17f9-415c-bbcd-6d132426dac1)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/49967413/27bbe41d-62ea-42c0-9185-9f052f603672)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/49967413/bda2ed9c-6ebe-4376-8322-7dfa268fa74a)

大佬这是我用抓包工具抓到的，帮我看看有问题吗？通道的报文也是5060端口吧？

**Comment by 648540858** [comment]
是的，你得抓包里也是消息长度为0

**Comment by 1207702931** [comment]
liveGBS 接收到同样的报文，能继续处理。
咱这个WVP要兼容一下，咋改也？领导要得急。

**Comment by 648540858** [comment]
改不了，协议栈直接返回的。

**Comment by 648540858** [comment]
着急的话还是建议使用livegbs，功能丰富，兼容性好。

**Comment by 648540858** [comment]
加了一点优化代码，测试下有没有效果吧，最好能从设备网络里有抓个包。

**Comment by 1207702931** [comment]
感谢大佬，我跟新部署上去看看

**Comment by 648540858** [comment]
直接用wirshark保存下来给我就行，二进制数据我也看不懂，没法分析，另外局域网你的从路由器抓取，从你电脑抓不到的。

**Comment by 648540858** [comment]
更新代码再测试下，我从底层优化了一下

**Comment by 1207702931** [comment]
通道也注册上来了，但是 播放视频的时候还有问题：点播接口等待超时
![image](https://github.com/648540858/wvp-GB28181-pro/assets/49967413/9dda269d-8d59-4906-87dd-d3e687c57fcd)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/49967413/29ef0289-cc70-444c-a183-1a7d80eb9752)

**Comment by 648540858** [comment]
新的问题开新的issue提问题，超时的问题看看相关issue，有很多了。
