### ISSUE TITLE
BUG 2.6.8 分屏监控，设备列表通道显示存在bug，国标设备里显示有通道；请问最新的稳定分支是哪个

### ISSUE THREAD

**Issue by song01** [648540858/wvp-GB28181-pro#922]

**Comment by 648540858** [comment]
不符合提问规范

**Comment by handsometong** [comment]
我也有同样问题，国标连接，系统国标设备tab上可以正常播放，分屏tab的列表无法显示摄像机信息
<img width="1672" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/12708876/393ae2bd-03f6-42ae-98d1-092514c04d58">
