### ISSUE TITLE
技术咨询-国标级联的点播流程

### ISSUE THREAD

**Issue by ivanlebron** [648540858/wvp-GB28181-pro#929]
**内容描述:**

三个层级的国标级联点播流程中，最上级发起点播之后，与中间级和下级的整个交互流程是什么样的？

**Comment by ivanlebron** [comment]
文档中没有多级级联流程的描述

**Comment by 648540858** [comment]
与上级点播下级，平台点播设备没有区别

**Comment by 648540858** [comment]
有不理解的地方欢迎来知识星球讨论
[https://t.zsxq.com/0d8VAD3Dm](https://t.zsxq.com/0d8VAD3Dm)
