### ISSUE TITLE
[技术咨询] SIP注册可能未进入服务

### ISSUE THREAD

**Issue by zhanglei-sq** [648540858/wvp-GB28181-pro#930]
wvp  部署到阿里云上面，摄像头配置28181信息之后，SIP服务注册不进去，日志没有打印任何注册信息，网络是通的，可以抓到tcp包。

**Comment by zhanglei-sq** [comment]
![1052260aee3ef74cd599c66e5ac10e8](https://github.com/648540858/wvp-GB28181-pro/assets/138198875/1c062e0a-596d-4d0b-919d-039da900f0c8)

**Comment by zhanglei-sq** [comment]
![72bcd3a25938423ad3dcc2587352fad](https://github.com/648540858/wvp-GB28181-pro/assets/138198875/a6ce35af-0b57-44ea-90ed-cae1c870e455)

**Comment by 648540858** [comment]
> ![1052260aee3ef74cd599c66e5ac10e8](https://github.com/648540858/wvp-GB28181-pro/assets/138198875/1c062e0a-596d-4d0b-919d-039da900f0c8)
> 
> 

发抓包文件

**Comment by zhanglei-sq** [comment]
[demo.zip](https://github.com/648540858/wvp-GB28181-pro/files/11966049/demo.zip)

**Comment by zhanglei-sq** [comment]
本地wvp启动，正常可以接收摄像头注册信息和视频流，部署到服务器上就不行    服务器tcp  UDP  安全组策略全都是放开的

**Comment by 648540858** [comment]
> ![72bcd3a25938423ad3dcc2587352fad](https://user-images.githubusercontent.com/138198875/251385439-a6ce35af-0b57-44ea-90ed-cae1c870e455.png)

你这跟没贴一样，全是马塞克我看啥，先自行解决吧
