### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by boyup6** [648540858/wvp-GB28181-pro#932]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题
拉流代理播放视频时视频跳动，时间会跳  每隔一定的时间间隔都会跳一下
![image](https://github.com/648540858/wvp-GB28181-pro/assets/137864911/e7e650e3-3425-4adf-81a4-4cab985c4da5)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/137864911/cc86f4f3-88bc-4889-aad8-45c9d3c5965b)

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
确认下原始流播放是否正常
网络是不是带宽不足
分辨率是多少

**Comment by 648540858** [comment]
长时间没有反馈我先关闭了
