### ISSUE TITLE
宇视视频监控系统通过国标接入视频回放不成功

### ISSUE THREAD

**Issue by myskybeyond** [648540858/wvp-GB28181-pro#934]
**环境信息:**

 - 1. 部署方式  编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境  ubuntu
 - 3. 端口开放情况 所需端口均已开放
 - 4. 是否是公网部署  否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 宇视视频监控系统
 - 7. 你做过哪些尝试 zlmediaKit换版本，宇视视频监控系统参数调整
 - 8. 代码更新时间

**内容描述:**
宇视视频监控平台推流，宇视视频监控系统通过国标接入视频回放不成功，wvp-pro日志提示回放超时，zlmediakit日志报错(开启ssrc校验的情况下)图1，不开启ssrc校验的情况下图2，其他说明：实时视频点播和云台控制是正常的。
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37172114/5dfc015d-ae67-4705-afe4-5af54f199252)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37172114/caa8506c-a72e-4315-b9c1-b6f23a5cbbec)
宇视视频监控系统外域配置如下图：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/37172114/ea2f7d5a-05eb-4317-a269-63d2e6b48291)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
看不出来，还是抓个包吧

**Comment by 648540858** [comment]
长时间没有反馈我先关闭了
