### ISSUE TITLE
[BUG]使用ipv6网络点播时，返回的视频流地址错误

### ISSUE THREAD

**Issue by AbnerSC** [648540858/wvp-GB28181-pro#935]
**环境信息:**

 - 1. 部署方式：wvp-prp + zlm都是编译部署
 - 2. 部署环境：ubuntu
 - 3. 端口开放情况：按照实际需求开放端口
 - 4. 是否是公网部署：否，内网部署
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试：尝试配置域名（配置media.stream-ip），结果返回的还是IP
 - 8. 代码更新时间：2023年7月7日更新部署

**描述错误**
点播后，期望播放地址：http://[240e:xxx:xxx:xxx:xxx:xxx:xxx:xxx]:8080/rtp/xxxx.live.flv
目前得到的错误播放地址：http://240e:xxx:xxx:xxx:xxx:xxx:xxx:xxx:8080/rtp/xxxx.live.flv
在ipv6协议里面，少了方括号[]

**如何复现**
使用ipv6协议访问wvp平台，发起视频点播

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
目前不支持ip v6
