### ISSUE TITLE
BUG/api/playback/start/{deviceId}/{channelId}  接口，单独调用时，可以正常返回地址，但是地址无法播放

### ISSUE THREAD

**Issue by hoheyho** [648540858/wvp-GB28181-pro#937]
api/playback/start/{deviceId}/{channelId}  接口，单独调用时，可以正常返回地址，但是地址无法播放
但是在配套web页面上调用的时候，返回地址可以正常播放

步骤是，
1先调用的登录接口（/api/user/login）
2回看列表接口（/api/gb_record/query/{deviceId}/{channelId}）
3回看接口（/api/playback/start/{deviceId}/{channelId}）----这个时候正常返回地址，但地址无法播放

**Comment by 648540858** [comment]
对比下你的调用和web页面有什么不同吧，如果你中间重启过服务器，也有可能导致真个现象

**Comment by hoheyho** [comment]
@648540858 中间确实重启过wvp服务，请问下这个问题怎么解决呢？
虽然重启过，但是web上面还是可以正常播放回放，
但是通过调用接口，获得的地址却无法播放，

**Comment by 648540858** [comment]
无法理解，web页面可以播放，那么您拿到的地址就可以播放
