### ISSUE TITLE
BUG-webrtc无法播放

### ISSUE THREAD

**Issue by zhanpc** [648540858/wvp-GB28181-pro#938]
**环境信息:**

 - 1. 部署方式 wvp-pro/zlm + 编译wvp-pro + zlm都是编译部署
 - 2. 部署环境-windows 
 - 3. 端口开放情况-全开放
 - 4. 是否是公网部署-否 
 - 5. 是否使用https-否
 - 6. 方便的话提供下使用的设备品牌或平台-海康威视网络半球摄像头
 - 7. 你做过哪些尝试
 - 8. 代码更新时间-最新代码

**内容描述:**
Jessibuca 视频播放正常 
webrtc 一直转圈加载不出来
zlm webrtc已编译 提示webrtc功能已开启
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/86341644/53c32ff3-a7e7-4752-a32b-71498d471920)

**抓包文件**
 浏览器  console无报错 
ZLMediaKit有两个error
![image](https://github.com/648540858/wvp-GB28181-pro/assets/86341644/3026d4c6-5434-4885-bea1-c36b785f85fd)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/86341644/dcd5a822-abb8-4383-9387-c1f9fcc74536)

**日志**
```
日志内容放这里， 文件的话请直接上传
```

[log.txt](https://github.com/648540858/wvp-GB28181-pro/files/12009877/log.txt)

**Comment by 648540858** [comment]
参考zlmwiki，编译zlm为支持rtc的版本
