### ISSUE TITLE
使用大华evs获取通道后  点击播放时提示接收到失败的response响应！status：400,message:Bad Request

### ISSUE THREAD

**Issue by boyup6** [648540858/wvp-GB28181-pro#942]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题
使用大华evs获取通道后  点击播放时提示接收到失败的response响应！status：400,message:Bad Request
**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/137864911/4063155f-7bb9-488a-a275-ebd50fc817da)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by shuting16** [comment]
我同样遇到这个问题，接入的是海康威视的摄像头。遇到400错误后，重启后这个问题消失了，过一段时间会复现。

**Comment by boyup6** [comment]
> 我同样遇到这个问题，接入的是海康威视的摄像头。遇到400错误后，重启后这个问题消失了，过一段时间会复现。
我一直有  重启也没用

**Comment by boyup6** [comment]
补充抓包文件
[wvp.txt](https://github.com/648540858/wvp-GB28181-pro/files/12023370/wvp.txt)

**Comment by boyup6** [comment]
补充抓包文件
[wvp.txt](https://github.com/648540858/wvp-GB28181-pro/files/12024148/wvp.txt)

**Comment by 648540858** [comment]
调用点播后可能重启过服务器，看看重启后可不可以正常释放

**Comment by boyup6** [comment]
重启后还是报400

**Comment by 648540858** [comment]
重启设备，正常点播一次，然后点播结束后点击停止按钮，看看设备会发400不，如果会，把整个过程抓个包发出来我看看

**Comment by boyup6** [comment]
解决了 谢谢大佬

**Comment by XUXIAODI1119** [comment]
> 解决了 谢谢大佬

请问是什么问题导致的呢？目前我也碰到类型情况，使用一段时间后，执行点播提示 接收到失败的response响应！status：400,message:Bad Request 
重启设备，过段时间之后就会复现

**Comment by WEINUONIKA** [comment]
请问是什么问题导致的啊？俺也遇到这种情况了

**Comment by WEINUONIKA** [comment]
排查了三天定位了三个问题，在这里写一下，方便后面遇到同样问题的小伙伴解决：
（1）拉流的时候是子码流还是主码流。海康威视摄像头是在摄像头后台管理界面配置，推送的是主码流还是子码流，有个下拉框可以选择，但是大华需要在SDP消息头中增加streamnumber字段，1表示子码流，0表示主码流。在代码中增加该字段即可，例如content.append("a=streamnumber:1\r\n");
（2）wvp.sqllite中不能包含域名。在打包编译的时候，application-dev.yml文件中不能有域名，之前为了方便部署，将其中的zlm服务改成了域名，导致与设备交互的时候，直接携带了域名，设备没法解析，不知道这算不算wvp的一个坑。。。
（3）大华摄像头本身的问题。我拉的是子码流，结果大华摄像头资源不足，根本无法播放子码流，建议在拉流之前先确认一下要拉的流能不能在摄像头后端管理界面预览成功。
