### ISSUE TITLE
BUG 国标级联新增平台报错

### ISSUE THREAD

**Issue by MetSystem** [648540858/wvp-GB28181-pro#946]
**环境信息:**

 - 1. 部署方式 wvp-pro 源码部署+ zlm编译部署/
 - 2. 部署环境 windows
 - 3. 端口开放情况
 - 4. 是否是公网部署 局域网
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 wvp2.6.7版本
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间
截至今天最新20230712
**描述错误**
描述下您遇到的问题
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: int overflow, value 45130000002000000001; nested exception is com.alibaba.fastjson2.JSONException: int overflow, value 45130000002000000001

**如何复现**
有明确复现步骤的问题会很容易被解决
http://localhost:18080/api/platform/add
```
{"id":null,"enable":true,"ptz":true,"rtcp":false,"asMessageChannel":false,"name":"45130000002000000001","serverGBId":"45130000002000000001","serverGBDomain":"4513000002","serverIP":"192.168.4.64","serverPort":"45130000002000000001","deviceGBId":"41010500002000000001","deviceIp":"172.16.30.140","devicePort":8116,"username":"41010500002000000001","password":"123#@!qwe","expires":3600,"keepTimeout":60,"transport":"UDP","characterSet":"GB2312","startOfflinePush":false,"catalogGroup":1,"administrativeDivision":"410105"}
```
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
更新代码测试，只针对最新的代码排查问题
