### ISSUE TITLE
上级联模式下，本级向上级推送设备和通道信息时有一个BUG，请处理一下。

### ISSUE THREAD

**Issue by qiaoshubin** [648540858/wvp-GB28181-pro#95]
具体位置在com.genersoft.iot.vmp.gb28181.transmit.cmd.SIPRequestHeaderPlarformProvider中的createMessageRequest中，有两个变量fromSipURI和toSipURI，它们对应的第一个参数，即本级和上级的国标ID写反了。

**Comment by 648540858** [comment]
好的我看一下

**Comment by qiaoshubin** [comment]
bug已上报

**Comment by 648540858** [comment]
已修复 c82608125353a7cd96aa19c2c96ac7a40d1ec23f
