### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by zhangzhenxing1** [648540858/wvp-GB28181-pro#954]
1.部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
wvp-prp + zlm都是编译部署- 
2。部署环境 windows / ubuntu/ centos ..
centos7
3.端口开放情况- 
server.port     sip.port    media.http-port
4.是否是公网部署-
是
 5。是否使用https- 
否
目前设备无法连接服务器 ip为公网ip

**Comment by 648540858** [comment]
自行确定网络是否通畅，设备配置是否正确吧，什么信息都不贴，我也帮不了你
