### ISSUE TITLE
【BUG 】目录订阅后，在国标级联选择通道时，如果添加通道到跟根目录（即平台本身），无法触发目录变更事件

### ISSUE THREAD

**Issue by DavidSche** [648540858/wvp-GB28181-pro#958]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题
在上及平台的国标设备对下级平台设置目录订阅
![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/9eb8b9ab-9f37-4b0c-a26f-e568ae71b9e9)

当在下级平台的国标级联中 选择通道时，如果添加通道到跟根目录（即平台本身），无法触发目录变更事件

![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/51ac1f36-5d33-44fe-901e-a8948228965a)

因为平台本身不在平台目录表中记录，所以直接触发下面代码中的目录为空条件，返回 null  值。导致目录变更事件不被触发，

![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/767b7ef8-0463-4074-9b0f-3ab66306d856)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/20830127/a9eed9a6-235e-423f-9d5d-fa74a2385201)
导致无法向上级平台发送通道变更消息，上级平台无法收到变更信息

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
好的，我看看
