### ISSUE TITLE
国标级联后上级平台同时点播多路会出现SDP回复端口号重复问题

### ISSUE THREAD

**Issue by MengFanLu1** [648540858/wvp-GB28181-pro#961]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
国标级联后上级平台同时点播多路会出现SDP回复端口号重复问题，我附上了抓包文件，麻烦给分析下吧

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
https://wx.mail.qq.com/ftn/download?func=3&key=c7cc5166b7093938f5bf1e66333436377c0fa665313436371d1c481205020e0e5a551d53090d0e1a5b0b54001c0657060e1e5453070d5002000b065e090426370a0302550103040608030448415757472c26983b8f9daae2c981dfdeccb9e213edf1847e0c&code=830f1467&k=c7cc5166b7093938f5bf1e66333436377c0fa665313436371d1c481205020e0e5a551d53090d0e1a5b0b54001c0657060e1e5453070d5002000b065e090426370a0302550103040608030448415757472c26983b8f9daae2c981dfdeccb9e213edf1847e0c&fweb=1&cl=1
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
已修复
