### ISSUE TITLE
BUG 更新通道信息失败

### ISSUE THREAD

**Issue by VirensCn** [648540858/wvp-GB28181-pro#962]
mysql： 8.0.33
proxysql:  一主2从 

![image](https://github.com/648540858/wvp-GB28181-pro/assets/9736815/3ebee563-0016-448e-87be-92708eaf5a59)

**Comment by 648540858** [comment]
你是跟哪个平台同步过来的？我看日志是你的平台给乱码的数据，问问他们用什么编码格式，可以在设备编辑中设置成utf-8试试

**Comment by VirensCn** [comment]
直接在页面中点击刷新按钮，更新通道信息时失败的，数据库编码采用：utf8mb4

**Comment by 648540858** [comment]
是不是你的数据库配置不支持批量更新datasource下的url要有allowMultiQueries这个参数
