### ISSUE TITLE
BUG 代码中数据库兼容出错

### ISSUE THREAD

**Issue by IKangXu** [648540858/wvp-GB28181-pro#966]
[PlatformGbStreamMapper.java](https://github.com/648540858/wvp-GB28181-pro/blob/59d8f2f9152b3c3106abae64bef343cde842f225/src/main/java/com/genersoft/iot/vmp/storager/dao/PlatformGbStreamMapper.java#L19)
[GbStreamMapper.java](https://github.com/648540858/wvp-GB28181-pro/blob/59d8f2f9152b3c3106abae64bef343cde842f225/src/main/java/com/genersoft/iot/vmp/storager/dao/GbStreamMapper.java#L17)
这两个文件中的 `REPLACE INTO` 这个操作在Postgresql中不支持，除Mysql外的其他数据库暂时没有测试过。

**Comment by 648540858** [comment]
好的，我测试下

**Comment by IKangXu** [comment]
> 好的，我测试下

有结果吗

**Comment by 648540858** [comment]
已经修复了
