### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by tank520** [648540858/wvp-GB28181-pro#969]
**环境信息:**

 - 1. 部署方式 wvp-pro、zlm均使用k8s部署，同一pod。
 - 2. zlm未配置多端口模式，仅开启80、10000（TCP + UDP）
 - 3. 公网部署 
 - 5. 仅zlm单独配置了证书
 - 6. 宇视IPC摄像头
 - 7. 你做过哪些尝试
 - 8. 代码更新时间：2023-07-13

**内容描述:**
目前摄像头接入wvp正常，心跳、点播均正常（TCP被动模式）。使用设备录像回放时，TCP被动模式下wvp回放接口返回正常，服务日志也ok，前端页面出现画面后就卡死，zlm后台出现媒体注销，断流了；将流传输模式改为UDP后，视频录像播放正常。

**问题**
1、设备录像播放是否支持TCP被动模式，如果支持，请问这个报错原因是什么？
  
**日志**
wvp：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/25721782/bf98447d-0e58-43a0-b979-687dffca23d2)
zlm：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/25721782/da2999b7-b009-4eb1-9ba4-ca757b25fd5b)

**Comment by 648540858** [comment]
应该是前端播放器播放不了这个流，或者流本身有问题，从播放窗口复制rtsp地址，然后g用vlc或者ffplay播放试试

**Comment by wangguodong8602** [comment]
你好，请问wvp使用k8s部署有什么需要注意的事项吗，我这边部署后设备始终无法通过5060端口进行注册。
对应service如下：
`apiVersion: v1
kind: Service
metadata:
  name: sip-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 7051
      targetPort: 7051
    - name: sip
      protocol: UDP
      port: 5060
      targetPort: 5060
  selector:
    app: sip-app
  type: LoadBalancer`

对应pod如下
`apiVersion: v1
kind: Pod
metadata:
  name: sip-pod
  labels:
    app: sip-app
spec:
  containers:
    - name: sip-container
      image: 172.16.203.172:81/sip-server/sip:v1.5
      stdin: true
      tty: true
      ports:
        - containerPort: 7051
        - containerPort: 5060`

**Comment by tank520** [comment]
确保设备到服务端之间的链路是通的就行

**Comment by wangguodong8602** [comment]
我现在遇到的问题是，设备发送rtp 数据到流媒体，流媒体报错，说rtp 长度不合法，怀疑是k8s的service对数据包有修改，不知道你遇到过这个问题没有，谢谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月18日 16:04 |
| 收件人 | 648540858/wvp-GB28181-pro ***@***.***> |
| 抄送人 | wangguodong8602 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [648540858/wvp-GB28181-pro] 技术咨询 (Issue #969) |

确保设备到服务端之间的链路是通的就行

**Comment by tank520** [comment]
我没遇到过呢，可以去 zlmediakit 里面去搜搜

**Comment by yuetsao** [comment]
> 你好，请问wvp使用k8s部署有什么需要注意的事项吗，我这边部署后设备始终无法通过5060端口进行注册。 对应service如下： `apiVersion: v1 kind: Service metadata: name: sip-service spec: ports: - name: http protocol: TCP port: 7051 targetPort: 7051 - name: sip protocol: UDP port: 5060 targetPort: 5060 selector: app: sip-app type: LoadBalancer`
> 
> 对应pod如下 `apiVersion: v1 kind: Pod metadata: name: sip-pod labels: app: sip-app spec: containers: - name: sip-container image: 172.16.203.172:81/sip-server/sip:v1.5 stdin: true tty: true ports: - containerPort: 7051 - containerPort: 5060`

我使用k8s部署时遇到了端口范围开通的问题，请问您这个解决了吗？

**Comment by tank520** [comment]
注册不上应该就是网络不通或者配置不对
