### ISSUE TITLE
技术咨询 登陆失败

### ISSUE THREAD

**Issue by KajiMaCN** [648540858/wvp-GB28181-pro#972]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) 
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 554/tcp, 0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:5060->5060/tcp, :::5060->5060/tcp, 1935/tcp, 0.0.0.0:18080->18080/tcp, 0.0.0.0:5060->5060/udp, :::18080->18080/tcp, :::5060->5060/udp, 0.0.0.0:30000-30500->30000-30500/tcp, :::30000-30500->30000-30500/tcp, 18081/tcp, 554/udp, 0.0.0.0:30000-30500->30000-30500/udp, :::30000-30500->30000-30500/udp, 0.0.0.0:6579->6379/tcp, :::6579->6379/tcp   wvp
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 无
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间

**内容描述:**
我要进行推流鉴权，文档中表示要查询push key，然后我通过接口 `/api/user/all` 查询用户，返回结果说要登陆，然后我通过 `/api/user/login` 接口发送 登陆请求password=456b7016a916a4b178dd72b947c152b7 username=admin 返回结果说是账号或者密码错误，我要怎么处理呢？
**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
你知道你的密码是多少吗，password是通过密码， md5之后得到的

**Comment by 648540858** [comment]
对比web前端的登陆接口看看，看看发送的内容是否一致
