### ISSUE TITLE
技术咨询 控制台中文乱码怎么解决

### ISSUE THREAD

**Issue by dodu2014** [648540858/wvp-GB28181-pro#973]
**环境信息:**

 - 1. 部署方式 wvp-pro / zlm + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows

**内容描述:**

java -jar 启动，控制台中文乱码

**截图**  

![image](https://github.com/648540858/wvp-GB28181-pro/assets/15245544/ec6a4e7c-432c-4b6a-a488-f1318209e37e)

**Comment by 648540858** [comment]
自行解决吧，你控制台编码的问题

**Comment by dodu2014** [comment]
谢谢 @648540858 

不过，zlm 控制台中文正常呢，wvp zlm 同在一pc

![image](https://github.com/648540858/wvp-GB28181-pro/assets/15245544/3994ca2d-6e99-4ddb-a618-595db194ee0d)

**Comment by dodu2014** [comment]
尝试的操作：
设置控制台编码：
```
chcp 65001
```
设置java语言编码：
```
System.setProperty("file.encoding", "UTF-8");
```

**Comment by dodu2014** [comment]
@648540858 wvp-pro-assist 控制台中文也能正常显示的，同一台pc，同一环境，如下图：

![image](https://github.com/648540858/wvp-GB28181-pro/assets/15245544/30b73d25-58ed-427e-809b-46e15841e0a9)

**Comment by dodu2014** [comment]
@648540858 我找到是哪的问题了，windows环境下，需要把设置的 logback-spring-local.xml charset 注释掉

![image](https://github.com/648540858/wvp-GB28181-pro/assets/15245544/3ee54bcc-df54-4547-a47f-c745dd1094f1)

这样，控制台中文就正常了，是否需要添加兼容配置？

![image](https://github.com/648540858/wvp-GB28181-pro/assets/15245544/f3b05529-9a5d-42e0-bcd1-95196a9b32a9)

**Comment by 648540858** [comment]
好的，我加一下

**Comment by LeiYangGH** [comment]
> @648540858 我找到是哪的问题了，windows环境下，需要把设置的 logback-spring-local.xml charset 注释掉
> 
> ![image](https://private-user-images.githubusercontent.com/15245544/257971041-3ee54bcc-df54-4547-a47f-c745dd1094f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTk0MjQsIm5iZiI6MTczNDMxOTEyNCwicGF0aCI6Ii8xNTI0NTU0NC8yNTc5NzEwNDEtM2VlNTRiY2MtZGY1NC00NTQ3LWE0N2YtYzc0NWRkMTA5NGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAzMTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OWEyY2Q5MDcyMjg2MTdhYTczOGIwNmQ4NTFjYjZmNmE3ZDNhZWRhMzAzYjgxNTcxYTc3YTYxZjM3NGMxOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YahHw6WTv__cka2PiNQA2V3nPAezuh_NPs1HdoNmCYE)
> 
> 这样，控制台中文就正常了，是否需要添加兼容配置？
> 
> ![image](https://private-user-images.githubusercontent.com/15245544/257971170-f3b05529-9a5d-42e0-bcd1-95196a9b32a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTk0MjQsIm5iZiI6MTczNDMxOTEyNCwicGF0aCI6Ii8xNTI0NTU0NC8yNTc5NzExNzAtZjNiMDU1MjktOWE1ZC00MmUwLWJjZDEtOTUxOTZhOWIzMmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAzMTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNzA1YTQ2YTE1OWE0YTIwOTY1MGJmODUxMjMzZTdiNmE0OTljMWFhYjk1MTRjOTUyYTRhYTM2NGZlNmUwMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ECZfFJr0t3L4Hwoklp2jh7YYhFvrJMe8h9-QH0PchKk)

我也遇到一样的问题，可以解释下为什么要去掉那个配置吗？
