### ISSUE TITLE
BUG 2.6.9 版本中，设备接入后云台控制无效(海康，其他品牌未测)

### ISSUE THREAD

**Issue by dodu2014** [648540858/wvp-GB28181-pro#977]
**环境信息:**

 - 1. 部署方式  wvp-prp + zlm都是编译部署
 - 2. 部署环境 windows
 - 3. 端口开放情况 默认提供端口
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康

**描述错误**
云台操作不可用，在设备提供的管理应用中是可以操控云台的，使用提供的api来操控，api 响应也是成功的，但无效。

**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/15245544/9a162bf2-3104-4720-84c8-6f0b1a7e6777)

![image](https://github.com/648540858/wvp-GB28181-pro/assets/15245544/3acd1c56-a8a3-47d5-9d3f-0edc1eb63904)

**Comment by 648540858** [comment]
设备不支持使用国标控制云台

**Comment by dodu2014** [comment]
好的。谢谢了 @648540858
