### ISSUE TITLE
技术咨询 使用docker部署wvp时sip设置的相关问题

### ISSUE THREAD

**Issue by kangxiaojia0** [648540858/wvp-GB28181-pro#979]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker)  使用dockerfile进行构建
 - 2. 部署环境 windows / ubuntu18.04
 - 3. 端口开放情况 使用host模式
 - 4. 是否是公网部署  否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 无
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**
在使用docker部署的时候，如果sip服务器填写为本机地址 则提示
tcp://192.168.1.135:8085 SIP服务启动失败,请检查端口是否被占用或者ip是否正确
udp://192.168.1.135:8085 SIP服务启动失败,请检查端口是否被占用或者ip是否正确
如果将sip服务器地址改为0.0.0.0 则提示
your_server_id验证后zlm仍在线，恢复心跳信息,请检查zlm是否可以正常向wvp发送心跳

已经将wvp-pro的网络改为host模式了

wvp与zlm部署在不同的容器中 当配置为0.0.0.0时 zlm日志中显示是在向着http://0.0.0.0:8095/index/hook/on_server_keepalive 发送心跳信息

这种怎么处理啊？请教一下

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by phlahut** [comment]
理论上sip开启监听时，ip直接设置成0.0.0.0就可以，通过docker的映射成宿主机的监听端口。设置zlm hook时应该设置wvp所在的宿主机的ip

**Comment by xueshuai0922** [comment]
怎么处理的呢？

**Comment by phlahut** [comment]
> 怎么处理的呢？
sip监听0.0.0.0，docker运行时，将sip监听端口映射外网监听端口就可以了

**Comment by xiaohuiL** [comment]
你好，请问你解决了吗？我也出现一样的问题了

**Comment by deng-h** [comment]
如果解决了，能否告诉一下怎么做的，谢谢
