### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by languis** [648540858/wvp-GB28181-pro#983]
**环境信息:**

 - 1. 部署方式 wvp-pro docker 
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况  全部
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 无
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**内容描述:**

你好，通过 api/play/start 接口获取到流的播放地址之后，我使用h5 播放器直接播放，一定时间段内没问题。
<img width="1000" alt="1" src="https://github.com/648540858/wvp-GB28181-pro/assets/14243687/bcbb2d04-ea5b-4f3d-948a-dc1f135728b1">

但是过了几个小时之后再打开则无法播放了，访问相应地址提示资源不存在。
<img width="1139" alt="Snipaste_2023-08-02_15-09-47" src="https://github.com/648540858/wvp-GB28181-pro/assets/14243687/76bc21e6-60a0-48cb-b1bf-ad90752d3c47">

我找遍了zlm和wvp的文档里，都没找到生成相应直链的api，请问能告知一下要如何才能获取到直链吗？

**Comment by xiaofuoffice** [comment]
创建拉流代理
![微信截图_20230802164826](https://github.com/648540858/wvp-GB28181-pro/assets/25221899/b5620a8d-9e05-4764-aa3d-dca369ede964)

**Comment by xiaofuoffice** [comment]
使用拉流代理

**Comment by languis** [comment]
> 使用拉流代理

非常感谢，我去试试
