### ISSUE TITLE
[增强 ]通道状态随设备离线显示为离线

### ISSUE THREAD

**Issue by xiaofuoffice** [648540858/wvp-GB28181-pro#984]
1、设备列表页面，显示设备离线：

![微信截图_20230802162955](https://github.com/648540858/wvp-GB28181-pro/assets/25221899/4c830d52-a20f-493c-9b2d-3c90eeed7354)

2、进入通道页面，通道依然显示在线：
![微信截图_20230802163327](https://github.com/648540858/wvp-GB28181-pro/assets/25221899/cefdc798-dd42-418f-8a29-b1eaed29fee9)

3、

**Comment by xiaofuoffice** [comment]
1.设备列表请求返回设备状态：onLine: false/true

![微信截图_20230802164129](https://github.com/648540858/wvp-GB28181-pro/assets/25221899/f0b365ad-0b34-4e4a-9ed2-de881800a40d)

2、通道页面代码判断错误 ：v-bind:disabled="device == null || device.online === 0"
![微信截图_20230802164429](https://github.com/648540858/wvp-GB28181-pro/assets/25221899/fb3fc298-55c7-408a-b85e-81a76223ef5d)

**Comment by 648540858** [comment]
通道状态目前不会随设备状态变化更新

**Comment by 648540858** [comment]
#1417
