### ISSUE TITLE
希望wvp仓储保持一个稳定的分支，一个dev分支，版本号可以使用 tag 来实现

### ISSUE THREAD

**Issue by dodu2014** [648540858/wvp-GB28181-pro#986]
希望wvp仓储保持一个稳定的分支，比如 master，一个dev分支，用于临时开发或合并pr，稳定后合并到 master，项目的版本号可以使用 tag 来实现。

有利于应用者跟随或保持最新稳定的功能

**Comment by mrshengzyzy** [comment]
同意。

**Comment by 648540858** [comment]
你说的是对的，但是一个稳定的稳定的分支是需要额外的精力来维护，需要花大量时间来测试的，目前没有这样的精力，建议自己选择最新版本在公司内测试，自行根据测试情况酌情更新代码。项目目前稳定的维护人员只有我自己。

**Comment by dodu2014** [comment]
@648540858 好的，理解，作者辛苦了。👍👍
我也是最近刚刚开始接触 wvp，希望能尽可能多的来做些测试工作吧，之后把问题反馈给你，可能有些比较小白，望理解。😊

**Comment by 648540858** [comment]
好的
