### ISSUE TITLE
希望wVP实现的新功能，此功能应与你的具体业务无关

### ISSUE THREAD

**Issue by 895512223** [648540858/wvp-GB28181-pro#987]
**项目的详细需求**
您好  是否可以将海康提供的设备【nvr】，ip地址，通过用户名和密码接入的程序中
**这样的实现什么作用**
这个如果可以，可以有偿合作

**Comment by 895512223** [comment]
海康、大华等厂家都有

**Comment by 648540858** [comment]
你如果可以给wvp赞助一个海康大华的平台费，那么可以给你加，提问题请尊重下彼此，标题都不改，也不要拿大厂平台来绑架一个开源项目。
