### ISSUE TITLE
[增强] JT1078支持

### ISSUE THREAD

**Issue by zgxsm** [648540858/wvp-GB28181-pro#994]
**环境信息:**

 - 1. 部署方式 wvp-pro + zlm都是编译部署
 - 2. 部署环境 centos
 - 3. 端口开放情况 全部开放
 - 4. 是否是公网部署  否
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试 
 - 8. 代码更新时间：最新代码

**内容描述:**
近期想使用部标1078相关功能，我这里设备注册是可以的，但是我在调用代码中播放示例接口的时候不知道该向设备传递的参数是什么，我传递zlmdiakit的rtmp(1935)和rtp(305000)端口zlm都会提示非法连接然后断开，想问下您这块应该怎么配置。
**截图**  
![image](https://github.com/648540858/wvp-GB28181-pro/assets/27176642/f4296052-7d77-4e5b-829c-8c16736888c1)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/27176642/db43b283-a28c-4d1b-9eee-68f332f44538)
![image](https://github.com/648540858/wvp-GB28181-pro/assets/27176642/c54b9597-87a5-4191-bdd1-833354c56160)

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
这块目前只是示例改代码，还没有整和到可用的地步

**Comment by zgxsm** [comment]
> 

这块的代码修改参数后也不能测试么？后续有推出的计划吗？

**Comment by 648540858** [comment]
有，目前还没有时间。具体现在怎么用你需要自己研究。

**Comment by zgxsm** [comment]
> 有，目前还没有时间。具体现在怎么用你需要自己研究。

好的感谢

**Comment by keDaYao** [comment]
应该传递zlmdiakit的配置文件中rtp_proxy.port的端口

**Comment by flylee85** [comment]
目前zlm流媒体不支持jt1078吧

**Comment by 648540858** [comment]
1078目前已经开发完成，支持视频接入，云台控制，位置上报，录像回放，双向对讲

**Comment by 648540858** [comment]
付费提供，需要的邮件或者i星球联系我就行
